### ISSUE TITLE
Update task null pointer

### ISSUE THREAD

**Issue by emiteze** [Netflix/conductor#1000]
When trying to update a task status using task resource API (/tasks endpoint) if I pass a invalid workflow instance id conductor returns a 404 with this payload:

```
{
  "code": "NOT_FOUND",
  "message": "No such workflow found by id: bla",
  "retryable": false,
  "instance": "54aee5aad659"
}
```

This seems very correct to me, but if I pass a valid workflowId but a invalid taskId, I got a 500 server error and a nullpointer on logs, and this response as well:

```
{
  "code": "INTERNAL_ERROR",
  "message": "INTERNAL_ERROR - null",
  "retryable": false,
  "instance": "54aee5aad659"
}
```

Opening this issue just to keep you on track of this problem, I'm planning to submit a PR soon to solve this issue.

Thanks

**Comment by kishorebanala** [comment]
@emiteze Great, thanks for looking into this.

**Comment by apanicker-nflx** [comment]
@emiteze Please check #1001 which I believe should fix this issue. Thanks for pointing this out.
