### ISSUE TITLE
Scaling Task Workers Question

### ISSUE THREAD

**Issue by joshuadeanhall** [Netflix/conductor#1011]
Hi all I am trying to get a definitive answer on a question related to scaling out task workers. 

Is it possible to deploy the same task worker multiple times to increase throughput of the task execution? Are there any concerns/issues with the same task being picked up by different task workers and being executed multiple times?

I assume that it does scale this way but I can't find any documentation that directly supports this.

**Comment by apanicker-nflx** [comment]
> Is it possible to deploy the same task worker multiple times to increase throughput of the task execution?

Yes, this is possible.

> Are there any concerns/issues with the same task being picked up by different task workers and being executed multiple times?

When using the [WorkflowTaskCoordinator](https://github.com/Netflix/conductor/blob/master/client/src/main/java/com/netflix/conductor/client/task/WorkflowTaskCoordinator.java#L358-L367), the ack method followed by the execute ensures that the same task is not executed multiple times by different task workers.
