### ISSUE TITLE
How to use WAIT task?

### ISSUE THREAD

**Issue by litian33** [Netflix/conductor#1014]
> Contrib module provides SQS integration where an external system can place a message in a pre-configured queue that the server listens on. As the messages arrive, they are marked as COMPLETED or FAILED.

Where to set the **pre-configured queue** ?  I din't find it in the code or docs, can you help me? Thanks.

**Comment by apanicker-nflx** [comment]
The pre-configured queues are set here - https://github.com/Netflix/conductor/blob/15106380ffe69383b67352c2a9b4f5f38ddf5e31/contribs/src/main/java/com/netflix/conductor/contribs/ContribsModule.java#L82.
By default, the sqs queues are configured to `conductor_sqs_notify_COMPLETED` and `conductor_sqs_notify_FAILED`
