### ISSUE TITLE
How to start a Task when Workflow fail?

### ISSUE THREAD

**Issue by MaksimRT** [Netflix/conductor#1017]

**Comment by apanicker-nflx** [comment]
@MaksimRT Can you please provide more information about your use-case? 
Please elaborate with the steps you have taken so far.

**Comment by MaksimRT** [comment]
@apanicker-nflx Yes, sure. Thanks for replay.

I would like to make a workflow. 
The workflow consists of two tasks.
If a task in the workflow fails then I would like to notify client about it by calling another task.

**Comment by apanicker-nflx** [comment]
There are 2 possible ways in which you can choose to achieve this:

1. Using a failure workflow.
    - Set the `failureWorkflow` field in your workflow definition to the name of the workflow that should be triggered when this workflow fails.
    - The task to notify client in case of failure could be a task in this failure workflow.

2. Using the Workflow Status Listener.
   - Set the `workflowStatusListenerEnabled` field in your workflow definition to true which enables [notifications](https://netflix.github.io/conductor/configuration/workflowdef/#workflow-notifications).
   - Add a custom implementation of the Workflow Status Listener. Refer [this ](https://netflix.github.io/conductor/extend/#workflow-status-listener).
   - This notification can be implemented in such a way as to either send a notification to an external system or to send an event on the conductor queue to complete/fail another task in another workflow as described [here](https://netflix.github.io/conductor/configuration/eventhandlers/#event-handler).

**Comment by apanicker-nflx** [comment]
Closing this issue for now, please reopen if this does not answer your question.

**Comment by MaksimRT** [comment]
@apanicker-nflx 

I tried the first approach "Using a failure workflow". 
It really works as expected! 
Thanks you very much!

Maybe later add information in documentation about how to handle errors in workflows?

**Comment by apanicker-nflx** [comment]
Glad that helped. Thanks for the feedback, I will add this to the FAQ section.
