### ISSUE TITLE
HTTP task Timeouts

### ISSUE THREAD

**Issue by naveenchlsn** [Netflix/conductor#1018]
We are using conductor in our company as orchestration engine and we need to configure variable timeouts for our HTTP tasks. 

Would this be a good contribution to conductor? 

If you guys say yes, then we can open a PR soon to this.

**Comment by kishorebanala** [comment]
Hey @naveenchlsn , That would be great. Can you provide more details on how you plan to implement this? Specifically, would it be applicable to HttpTask vs all the tasks. Also, how do you intend to configure the variable timeouts?

**Comment by naveenchlsn** [comment]
HI @kishorebanala . 
I am planning on adding parameters only to the HTTP task. 
I will take the parameters as part of the HTTP input object, with a fallback to system configuration. 

I have raised a PR . Please let me know your thoughts.  
 https://github.com/Netflix/conductor/pull/1025
