### ISSUE TITLE
searchArchivableWorkflows test fails while trying to build server

### ISSUE THREAD

**Issue by animathe** [Netflix/conductor#1020]
hi,
       I'm trying to build jar of of latest conductor changes, using "gradle build" command. It fails with following test case failure.

com.netflix.conductor.dao.es5.index.TestElasticSearchRestDAOV5 > testSearchArchivableWorkflows FAILED
    org.awaitility.core.ConditionTimeoutException at TestElasticSearchRestDAOV5.java:309
        Caused by: java.lang.AssertionError at TestElasticSearchRestDAOV5.java:312

33 tests completed, 1 failed

> Task :conductor-es5-persistence:test FAILED

FAILURE: Build failed with an exception.

**Comment by kishorebanala** [comment]
@animathe I've increased timeouts for the failing test, and it is working fine: https://github.com/Netflix/conductor/pull/1039. Please let us know if you still see this issue.
