### ISSUE TITLE
Event UI representation

### ISSUE THREAD

**Issue by jkaipa** [Netflix/conductor#1022]
Any thoughts on changing the shape for event? This marijuana shaped polygon is appearing quite big if the event reference name is a little longer.

**Comment by kishorebanala** [comment]
@jkaipa I believe the event polygon resizes automatically with space available. But, if you have better suggestions, let us know.

**Comment by apanicker-nflx** [comment]
We will be addressing the issue of task representation in UI shortly. Please feel free to contribute with any suggestions you may have.
