### ISSUE TITLE
Event & Wait Issue

### ISSUE THREAD

**Issue by jkaipa** [Netflix/conductor#1023]
@apanicker-nflx 
I have a workflow where every **event** task is followed by a **wait** task. In ideal situation, the **event** task publishes the message and when conductor schedules **wait** task, the **wait** task listens to the success/failure queue for external message. When too many instances of the same workflow is in progress, the conductor is taking too long time before scheduling the **wait** task after the event. The consumer of the **event** message is responding quick and posting a message into the success/failure queue. By the time this message is processed by the queue manager, due to the unscheduled **wait** task I am running into issues.

I came up with a new **system task type** called EVENT_WAIT in which, The task goes into Inprogress state as soon as the **event** publish is successful. As soon as the message is ready on success/failure queue I will have additional handling in QueueManager and which completes the task.

Any additional thoughts?

**Comment by kishorebanala** [comment]
@jkaipa I'm not sure if adding a EVENT_WAIT task would help in this case.

> When too many instances of the same workflow is in progress, the conductor is taking too long time before scheduling the wait task after the event.
Can you provide an example for this please? I'd like to see the Start and End times of Event and consecutive wait task, if possible.

**Comment by jkaipa** [comment]
@kishorebanala I have an integration with an external system through a sink (some queue implementation). Source is publishing event to the queue and the Consumer is responding much quicker.

```
{
  "name": "workflow",
  "description": "test workflow",
  "version": 1,
  "tasks": [
    {
      "name": "fork_join",
      "taskReferenceName": "fork1",
      "type": "FORK_JOIN",
      "forkTasks": [
        [
          {
            "name": "REQUEST1",
            "taskReferenceName": "request1",
            "inputParameters": {
              "oldServerId": "${workflow.input.a}",
              "newServerId": "${workflow.input.b}",
              "callBackInfo": {
                "taskReferenceName": "response1"
              }
            },
            "type": "EVENT",
            "startDelay": 0,
            "sink": "sqs:testQueue",
            "optional": false
          },
          {
            "name": "RESPONSE1",
            "taskReferenceName": "response1",
            "type": "WAIT",
            "startDelay": 0,
            "optional": false
          }
        ]
      ],
      "startDelay": 0,
      "optional": false
    },
    {
      "name": "join1",
      "taskReferenceName": "join1",
      "type": "JOIN",
      "startDelay": 0,
      "joinOn": [
        "response1",
        "response2",
        "response3",
        "response4",
        "response5",
        "response6",
        "response7",
        "response8",
        "response9"
      ],
      "optional": false
    },
    {
      "name": "sendEmail",
      "taskReferenceName": "notify",
      "inputParameters": {
        "oldServerId": "${workflow.input.a}",
        "newServerId": "${workflow.input.b}"
      },
      "type": "EVENT",
      "sink": "sqs:testQueue",
      "startDelay": 0
    }
  ],
  "schemaVersion": 2
}
```
"callBackInfo" in the event request is used by the consumer to post bask the message with specific task reference name into success/failure queue.
If the response from consumer into success/failure queue is received before the scheduling of the wait task, the queue manager is failing with message "No matching tasks to be found to be marked as completed for workflow {}, taskRefName {}, taskId {}". 

EVENT_WAIT as a new system task helped me to come out of this issue (Still in development).

**Comment by kishorebanala** [comment]
@jkaipa That makes sense. But, we'd still prefer to fix current eventing mechanism to consider this, over creating a new Task. If you have ideas on how to do this, or if you're thinking of creating a PR, please let us know. Thank you.

**Comment by jkaipa** [comment]
@kishorebanala Please review the  PR https://github.com/Netflix/conductor/pull/1058 and let me know your comments.

**Comment by kishorebanala** [comment]
Continuing the discussion in #1058
