### ISSUE TITLE
Just curious  .. What is the reason for pattern in this memory graph ? 

### ISSUE THREAD

**Issue by kchaturanga** [Netflix/conductor#1026]
Internal Elastic search + AWS redis service 
24 hour JVM graph of conductor server .. 

I found this pattern in the 24 hour memory graph . Any specific  reason  for this pattern ? Just curious .. 

![screenshot from 2019-03-05 16-21-09](https://user-images.githubusercontent.com/2740501/53800765-75ab8d00-3f63-11e9-8b97-5c2ec6365882.png)

Note : please close this issue if inappropriate ..

**Comment by kishorebanala** [comment]
Hey @kchaturanga, While someone from community who has actually tested this might best answer this question, I don't see anything abnormal with it, apparently GC kicks in every once a while to cleanup stale workflow related objects.

I'm closing this as there isn't much activity, but please feel free to reopen if this topic needs more review.
