### ISSUE TITLE
Is it possible to add a PostgresSQL support?

### ISSUE THREAD

**Issue by MaksimRT** [Netflix/conductor#1027]
- Is it possible to add a PostgresSQL support, for example based on "mysql-persistence"?
- What is the performance of "mysql-persistence" storage engine compare to the Dynomite storage engine?

**Comment by kishorebanala** [comment]
@MaksimRT Please refer to this issue about adding new database support: https://github.com/Netflix/conductor/issues/1013.

Someone in the community who is using MySql in production might best answer your questions about performance comparison.
