### ISSUE TITLE
Does the conductor support data migration in case of schema changes?

### ISSUE THREAD

**Issue by MaksimRT** [Netflix/conductor#1028]

**Comment by kishorebanala** [comment]
Hey @MaksimRT, what schema are you referring to in Dynomite?

**Comment by MaksimRT** [comment]
Hi @kishorebanala! 
Thanks for response!
I know that NoSQL database such as Dynomite or Redis is schemaless, but you have a schema in the code, right?
So I want to know how do you handle appication upgrade.
For example, I have v2.7.2 (you could choose any other version), could I skip v2.8.0 and install v2.8.1?
What happen if I install v2.8.1 and then decide to rollback to v2.7.2?

I also have the same questions for MySQL  database as well.

**Comment by kishorebanala** [comment]
@MaksimRT We follow Semantic versioning, and any minor version upgrade should be backwards compatible. Any breaking changes will go to a major version upgrade, and will be mentioned explicitly.
