### ISSUE TITLE
Task versioning

### ISSUE THREAD

**Issue by andrea11** [Netflix/conductor#1030]
Hello everybody,
I follow this project since several months and I am very surprise of the work that you did it.
I was wondering which is your position about an eventual task versioning. Is it faisable? And do you think that there is any chance that it will be implemented one day?
And further more, do you have a roadmap for the next months?

Thank you

**Comment by kishorebanala** [comment]
@andrea11 Thanks for your kind words. We don't have any plans to implement Task versioning at the moment, but it would be nice to have. Also, we're in the process of building backlog instead of roadmap as reference.
