### ISSUE TITLE
Construct of "goto" task.

### ISSUE THREAD

**Issue by naveenchlsn** [Netflix/conductor#1031]
Hi, 
We are interested in adding loop construct to conductor

There are similar discussions in old tickets.  https://github.com/Netflix/conductor/issues/938. 

One approach would be to add goto construct. In addition, have the ability to run a task multiple times, 
saving each execution. 

@cyzhao @apanicker-nflx @v1r3n @mashurex @kishorebanala  Can you please let us know your thoughts, so we can work on this.

**Comment by andrea11** [comment]
Hello @naveenchlsn,
Indeed this will be very helpful. But they could be considered as two different features.
I would be interested as well in knowing the position of @cyzhao @apanicker-nflx @v1r3n @mashurex @kishorebanala about that.

Were you thinking about a static loop or a dynamic loop (like FORK or DYNAMIC_FORK) ?

**Comment by cyzhao** [comment]
@naveenchlsn contributions are always welcome, please provide details on how you plan to add the support so we can discuss here, once we all agree with the approach then you can start working on it.

**Comment by naveenchlsn** [comment]
Thanks @cyzhao.

### **Proposal.**
To support goto contruct in the workflow def, we can have a field "next" in the worflowtask,
containing the taskReferenceName of the task we want to execute after the current task.

### **Rationale** 
This approach is similar to what [States Language](https://states-language.net/spec.html)  proposes.

### **Implementation.**
We can enhance the WorkflowDef.getNextTask to return the "next" Task, falling back to old logic if next field is absent.Currently, each workflowTask corresponds to one task , because task instance is uniquely identified by taskReferenceName.
In contrast, we need to make task identity independent of taskReferenceName, by using a UUID instead.
This would require changes in database layer and other places where we identify task by referenceTaskName.

### **Backward Compatability.** 
If the next field is absent we fall back to old logic,  maintaining backward compatability. 


Please let me know your thoughts.  @cyzhao @apanicker-nflx @mashurex @kishorebanala

**Comment by apanicker-nflx** [comment]
Hi @naveenchlsn, thanks for the proposal. We will review this and get back to you soon with feedback.

**Comment by mudit3774** [comment]
@apanicker-nflx Any update on the proposal ? @naveenchlsn I think it would make sense to add more details in the implementation section. For instance : 

1. How will we maintain history of all runs ? 
2. How will the registration change ? 
3. How will the execution change ?

**Comment by kishorebanala** [comment]
@naveenchlsn This is a great start. Just keep in mind that by supporting `goto`, Conductor would be deviating from DAG structure to a general Graph structure. Which means, we'll need to consider several scenarios, thoroughly evaluate and test this feature.

Please continue by defining a concrete plan, addressing questions or concerns from others (particularly @mudit3774 has asked some great questions) in this thread, including (but obviously not limited to):
- How would `goto` task support looping with state; Eg: A subsection of workflow processing a bulk of workload in chunks / pagination.
- How does it differ from `goto` without state; I.e previous loop's state is not important and workflow can continue from the goto task.
- How will `goto` consider other system tasks in it's path (if it has to). Eg: Decision tasks, Fork joins etc.

**Comment by choubisat** [comment]
@naveenchlsn This will be very useful and can help model several kinds of workflows in the conductor. As per the proposal, How do you plan to break the loop when "next" field will point to a previous task in workflow execution chain? Perhaps, adding a new system task construct like "goto taskReferenceName" may be more useful. Added by changes you are proposing to maintain the task state in the backend. 

The new construct will allow any workflow author to escape or jump the default execution flow (serial order of tasks) when required i.e. in conjunction with a "DECISION". 

In Addition, the goto implementation can manipulate List workflow.tasks.
e.g.; say the list is currently workflow.tasks [] = { T1, T2, T3, T4, T5 } now if the "goto" requires to jump to T2 then workflow state is adjusted to be like 

workflow.tasks[] = { T1} And
workflow.historyTask [] =  { T1, T2, T3, T4, T5 }
So, the next iteration of decide() will schedule T2 again and so on. 

@kishorebanala , @cyzhao , @mudit3774 and all: please share if this makes sense.

**Comment by mudit3774** [comment]
We have been discussing internally and it seems that goto implementation would not be the cleanest and would require more thinking. 

On the other hand, a do-while like construct would be easier to model and could potentially derive inspiration from ForkJoin and Decision. We still need to worry about execution history. 

We do understand that goto is more generic than do-while but if "do-while" fits the bill for a majority of use-cases we can consider that also. It is similar to goto + decision but bounded. 

Thoughts? @kishorebanala @choubisat @naveenchlsn

**Comment by shivambansal2222** [comment]
@mudit3774 Even if we go with "do-while" , we'll have to maintain task's output of previous iteration if that is used in next iteration. So anyway we need to preserve states if we are implementing do-while with states. I guess  goto like construct gives more flexibility and gives more completeness in terms of richness of workflow. Maybe we could start with simpler approach of goto without states. 

Thoughts? @kishorebanala  @naveenchlsn

**Comment by mudit3774** [comment]
I agree that "goto" is a more generic task but it will lead to complexities like "can I go to a specific branch in fork join?" or "what if I goto to a specific case?". If we restrict the implementation, we can avoid complexity. 

Also, do-while without the state would be useful for cases like these: 

```
do {
   a = getRandom(0,10);
   b = getRandom(0,10);
} while (a+b < 15) 

```

a and b will have only the last value of the last run. Will this make sense ?

**Comment by shivambansal2222** [comment]
@mudit3774 I agree "goto" without any restriction will be very hard to implement because of various multithreaded constructs like fork-join etc. We could consider implementing a "goto"  which will take you to only a state whose successor nodes will not be in running state. 
think of a simple workflow t1->t2->t3 , based on what t3 produces the workflow could either reach in t1 state or it could go in terminal stage. this could be achieved with the help of restricted "goto".
Moreover, the example which you mentioned above can also be modelled in this restricted "goto construct".

**Comment by mudit3774** [comment]
@shivambansal2222 it is hard to convey the restriction and we would be making changes for all future task types since the task that goto can point to is limited and depends on the flow. 

Also, we can model it with goto but goto is prone to be misused.

**Comment by shivambansal2222** [comment]
@mudit3774 Yes I agree the limited functionally makes more sense with do-while. But we should think about approaches implementing go-to as well.

**Comment by choubisat** [comment]
A do while can still be acheived without making any changes: lets say the workflow definition is 
T1->W1->T; Where W1 is a sub workflow over that one needs to run a do-While loop.

Now if W1 can be modified by adding a Decision task with two cases like below
case 1: Execute sub_workflow W1.
case 2: default, do nothing.

This way one can orchestrate and loop over same task. though it may not be  very clean but perhaps only UI can be modified to treat each sub_workflow execution as simple iteration.

**Comment by manan164** [comment]
Hi all, I have raised PR for loop functionality. https://github.com/Netflix/conductor/pull/1169. Please have a look.

**Comment by shivambansal2222** [comment]
Hi, we are trying to implement "GOTO" construct in conductor. We wanted to share our approach and schema for "GOTO" with conductor community before actual implementation to know if the approach is aligned and we are not missing anything.
Sample "GOTO" task:
   
   {
    "name": "gotoLereview",
    "taskReferenceName": "gotoLereview",
    "inputParameters": {
      "fileName": "${MrReview.output.reviewFileName}"
    },
    "type": "GOTO",
    "gotoTask": "LeReview"
  } 

The "GOTO" task would take a task reference t1 where it would take the workflow execution. Task t1 task will be created again with new task id. Data-passing from "GOTO" task to the previously executed task t1 will work with superimposed new input. Whatever input parameters in t1 matches with input parameters of GOTO, will be replaced with GOTO task's input.

Following is the sample two stage review workflow schema which uses "GOTO" construct:
   
  

{
  "name": "TwoStageReviewWithGoto",
  "description": "sample review workflow using GOTO",
  "version": 1,
  "tasks": [
    {
      "name": "review",
      "description": "legal review task",
      "taskReferenceName": "LeReview",
      "inputParameters": {
        "fileName": "${Workflow.input.reviewFileName}"
      },
      "type": "SIMPLE"
    },
    {
      "name": "review",
      "taskReferenceName": "MRreview",
      "description": "marketing review task",
      "inputParameters": {
        "fileName": "${LeReview.output.reviewFileName}"
      },
      "type": "SIMPLE"
    },
    {
      "name": "gotoDecision",
      "taskReferenceName": "gotoDecision",
      "inputParameters": {
        "reviewAccepted": "{MrReview.output.reviewRejected}"
      },
      "type": "DECISION",
      "caseValueParam": "reviewRejected",
      "decisionCases": {
        "1": [
          {
            "name": "gotoLereview",
            "taskReferenceName": "gotoLereview",
            "inputParameters": {
              "fileName": "${MrReview.output.reviewFileName}"
            },
            "type": "GOTO",
            "gotoTask": "LeReview"
          }
        ]
      }
    },
    {
      "name": "search_elasticsearch",
      "taskReferenceName": "get_es_1",
      "type": "HTTP",
      "inputParameters": {
        "http_request": {
          "uri": "http://localhost:9200/conductor/_search?size=10",
          "method": "GET"
        }
      }
    }
  ],
  "outputParameters": {
    "workflowIds": "${get_es_1.output..workflowId}",
    "status": "${get_es_1.output..status}"
  },
  "schemaVersion": 2
}

Explanation: A review file is taken as workflow input. The first task is a legal review (LeReview) which starts legal review. Then it's output file is shared for marketing review (MrReview). The MRreview task will generate output "reviewRejected" and based on it's value, workflow can either continue or it can go to previously executed task "LeReview". The "GOTO" task has an input parameter "fileName" which matches with "LeReview" task's input parameter "fileName", so it will superimpose value of "fileName" with the earlier one. This could be one of the approach of passing data to earlier task. 


Please let us know if this approach looks good. Looking forward for the feedback.

@andrea11 @cyzhao @apanicker-nflx @kishorebanala

**Comment by kishorebanala** [comment]
@shivambansal2222 Thanks for the proposal, it looks great. Here are some of my questions:

1. `The "GOTO" task would take a task reference t1 where it would take the workflow execution.` - Can the same GOTO task be executed multiple times (essentially becoming a loop task)?
2. What happens to tasks executed between GOTO reference task (t1 in above example) and GOTO task?  Should we still keep the previous executions? I'm concerned about the race conditions when downstream tasks reference the task outputs, if they have to differ. We might be able to avoid this by making sure the references are always returned from latest task executions.
3. Would GOTO task work from Fork-Joins, do-while etc? If so, what would the specifics looks like?

**Comment by shivambansal2222** [comment]
Thanks @kishorebanala for reviewing it. Here are my response:
1. Yes the same GOTO task can be executed multiple times depending on workflow DSL. For example in the review DSL , the GOTO task will run as many times the MRreview, rejects the review.  
2. The workflow DSL has output associated with a task_reference name only. So, whatever task is running will always refer to task_reference output's latest value. We will keep just latest value associated with particular task reference.
3. Essentially, if we compare this GOTO with programming language's construct of GOTO, this can be used anywhere. But things get tricky here as an immature programmer can misuse GOTO. Hence, it would be better if we limit the use of GOTO from fork join and do-while type of constructs.

**Comment by andrea11** [comment]
Hello @shivambansal2222,
I have some questions as well:
1. Could the GOTO task used to go back and forth in the workflow?
1.1. If yes, how could you be sure that the mapping of the input/output of workflow/tasks are still valid, supposing that some tasks could had been skipped?
2. When do you say that in a first draft this task could be limited to linear construct, what do you mean exactly? Should we check that the task is at root level? But in this case it is not future-proof and new task could break this behaviour

Nice proposition 😄. Wait for your reply

**Comment by shivambansal2222** [comment]
Hi @andrea11 , please find my response:

1. Yes GOTO could take you back and forth in workflow. A bad programmer can always use GOTO to skip some tasks, but thats something which the workflow DSL writer/programmer has to take care. There can be cases when you want  GOTO  to a future task "t1" by skipping few task and  "t1" might not always be taking any input from previous task. It's analogical to programming language construct of GOTO. 

2. No, we need not to check whether the task is at root level. By linear construct, I meant GOTO task could be used anywhere as long it is taking you to a previous task which is in same branch of execution flow. Let's understand this with the help of an example:

                        t4-->t5-->t6
                     / .                       \ 
t1-->t2-->t3                            t10-->t11->t12
                    \                          /
                        t7-->t8-->t9

In the above workflow, t3 is a fork task with two branches of fork [t4,t5,t6] and [t7, t8, t9]. Both of these branches joins at t10. 

**some valid GOTO moves:**

1. t6->t4
2. t12->t11
3.  t12->t2 (although there is a fork at t3 , but that has already joined at t10; so there is no problem going from t12 to t2)

**some invalid GOTO moves: **

1. t6->t2 as this will lead to an inconstant state because we have other forked branch [t7,t8, t9] still running and not joined yet. 

2. t12->t5 (we should not use GOTO to reach an intermediate task inside a forked task)

I hope these examples would help to understand the semantics of GOTO task. 
 

 @cyzhao @apanicker-nflx @kishorebanala

**Comment by apanicker-nflx** [comment]
@shivambansal2222 Thanks for the detailed explanation. The example with the valid and invalid scenarios were especially helpful in visualizing the semantics.

Can you also illustrate how the GOTO task would behave when used in conjunction with a DECISION task in a workflow? Specifically, how do you prevent jumping across branches?

Also, while I completely agree that the DSL writer has to take care of preventing invalid cases, it would also be beneficial if we could also add validation to a GOTO task such that most of the above mentioned invalid cases can be identified and flagged during workflow registration.

**Comment by shivambansal2222** [comment]
@apanicker-nflx Thanks for reviewing it. Yes, I agree on the part that these kind of invalid moves should be flagged during workflow registration and it is in my plan. 
Let me work through a sample workflow with DECISION and GOTO. I will update on this thread soon.

**Comment by sarmuru2** [comment]
@shivambansal2222, will you be merging this goto construct to main? We are facing big workflow issues when we define 6 decision tasks in a workflow. To accommodate 6 decision tasks, a workflow definition file with 1.7 mb of size needs to be created. For saving this big workflow definition it takes 2 minutes.
