### ISSUE TITLE
Roughly 0.5 second gap between http tasks

### ISSUE THREAD

**Issue by mgregory-carecloud** [Netflix/conductor#1035]
I'm consistently seeing a gap of ~0.5 seconds between the end of one task and the beginning of the next task that is severely slowing down my workflow. I'm running conductor using `docker-compose up` locally. I'm not sure what the problem is. Any guidance would be greatly appreciated.
![image](https://user-images.githubusercontent.com/22304107/53982327-9fd78900-40e2-11e9-96fd-51dc9400db4f.png)

**Comment by kishorebanala** [comment]
Hey @mgregory-carecloud, the way Workflow evaluates after each step, and completes the lifecycle of HttpTask (asynchronously), ~0.5 seconds sounds reasonable to me. If you're expecting to send a batch of requests in sub second, I'd suggest to do them in a worker.

**Comment by fnolla-carecloud** [comment]
@kishorebanala so are you saying that if they were workers they wouldn’t have a 500 millisecond delay between each call? These tasks should be asynchronous and could be separate tasks that are ran by workers but would still need to be ran sequentially and not parallel. So I am curious if this will elimate that delay and also if so I am curious as to why?

**Comment by kishorebanala** [comment]
Pardon if I was not clear in above response. From your example, Tasks 4-9 are all Http tasks, and I think you'd like to execute them sequentially. I'm suggesting to keep them all in one Worker task, and send all these requests from the Worker. I.e Instead of Http Tasks 4-9, there would be only one Worker task.

That way, you'd avoid scheduling multiple Http tasks asynchronously, and might save on ~.5 seconds delay. You might find Http task implementation helpful to see how it works, and how you can best use it in your workflows.

**Comment by fnolla-carecloud** [comment]
While I agree with you that it is possible to make all of those calls happen in a worker there is still a 500ms gap between a decision task and an HTTP request. You can see that between step 3 & 4. Even if we changed them to be 1 call we would still have that delay between tasks which is a problem.

If you could point me to the code that would be great.

**Comment by fnolla-carecloud** [comment]
I tried a quick sample using the go client and just polling for the task as if they were workers. These tasks did nothing and just returned the sample response that the client has. I guess what my question is, is there anyway to speed up the time between tasks. Here it is about 200ms between each task. I am running on my local with docker compose.
![image](https://user-images.githubusercontent.com/26090625/54099946-3c738280-4392-11e9-9e0c-124fbcefcd50.png)

**Comment by tafael** [comment]
Hi @fnolla-carecloud, i managed to decrease delay between sequencial tasks by changing the class com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator at this line:

List<String> polledTaskIds = queueDAO.pop(taskName, realPollCount, 200);

to

List<String> polledTaskIds = queueDAO.pop(taskName, realPollCount, 0);

Before it was wating up to 200 ms before returning polledTasksIds.
Now it just get the messages that are already in the queue, not waiting to pop realPollCount messages. For example if realPollCount = 10, it doesn't matter if there are only 1 message in the queue, it returns right away.

Also this line is important:

this.pollInterval = config.getIntProperty("workflow.system.task.worker.poll.interval", 50);

It defines the interval between polling to the system worker task queues. The bigger this inteval the bigger the latency between sequencial tasks.

I also used async indexing of IndexDAO

**Comment by mudit3774** [comment]
Please note that there is a lead in IndexDao which @naveenchlsn has contributed a PR for. 

@kishorebanala would it make sense to add this to documentation. We also spent some time to tune the HTTP task consumption. I'll be happy to contribute if you can point me the doc that you'd want updated.

**Comment by kishorebanala** [comment]
@mudit3774 Sure. do you mind briefly explaining what the docs will address? I can point you to relevant docs based on that.
