### ISSUE TITLE
Terminate task

### ISSUE THREAD

**Issue by emiteze** [Netflix/conductor#1044]
Hi guys,

I was wondering if it would be helpful to have a new system task that terminates the current workflow execution. During our usage, we found a specific case that when a condition is met on a conditional task, we want to terminate the execution, like the following picture:

[Image](https://imgur.com/a/jjk23YO) (sorry for the bad drawing)

I don't know if you guys already had faced this use case, but since I didn't found nothing related on issues, I decided to open this up to discuss the utility of this and the better approach to do this enhancement.

The only issue that we would have to deal specifically is when the user fork some tasks and put a terminate task on a single branch of fork task, so maybe the workflow would be terminated with things still running on other workers, and I don't know what would be the consequences of this.

What do you guys think about it?

**Comment by apanicker-nflx** [comment]
@emiteze This can currently be achieved by setting a task to [FAILED_WITH_TERMINAL_ERROR](https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/metadata/tasks/Task.java#L39) status.
In this case, the workflow will be terminated. Also, in the case of forks, if one branch of the fork fails with this status, then the tasks in the other branches are marked as CANCELED.

**Comment by emiteze** [comment]
@apanicker-nflx I'm glad to hear that but I don't know if this solves our problem, since in our case we need to terminate the execution explicitly through workflow definition. In that way the workflow status would be completed or maybe that terminate task could be a FINISH TASK that receives the status that you want to set to workflow execution, sounding like an END STATE. Does that makes sense to you?
