### ISSUE TITLE
conductor:ui npm install failed

### ISSUE THREAD

**Issue by gregoirer** [Netflix/conductor#1054]
Step 1/11 : FROM node:9-alpine
 ---> a56170f59699
Step 2/11 : MAINTAINER Netflix OSS <conductor@netflix.com>
 ---> Using cache
 ---> 475d5ce19b9b
Step 3/11 : RUN apk update && apk add   autoconf   automake   libtool   build-base   libstdc++   gcc   abuild   binutils   nasm   libpng   libpng-dev   libjpeg-turbo   libjpeg-turbo-dev   python
 ---> Using cache
 ---> b776d67dd815
Step 4/11 : RUN mkdir -p /app/ui
 ---> Using cache
 ---> 659fcd1789c9
Step 5/11 : COPY ./docker/ui/bin /app
 ---> e010e1893c7d
Step 6/11 : COPY ./ui /app/ui
 ---> a55889874880
Step 7/11 : RUN chmod +x /app/startup.sh
 ---> Running in 7f182567f2c9
Removing intermediate container 7f182567f2c9
 ---> 4720ed77b58b
Step 8/11 : RUN cd /app/ui   && npm install   && npm run build --server
 ---> Running in 37a633261d35
npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=minimatch&version=0.3.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=minimatch&version=0.2.14 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.2.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] node.extend has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=node.extend&version=1.1.6 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.6.8 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=4.17.10 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm ERR! code EINTEGRITY
npm ERR! sha1-U3cWwHduTPeePtG2IfdljCkRsbE= integrity checksum failed when using sha1: wanted sha1-U3cWwHduTPeePtG2IfdljCkRsbE= but got sha1-gswqb03PNvrPDHp5RoV7/2KCisc=. (3612 bytes)
npm WARN notice [SECURITY] growl has the following vulnerability: 1 critical. Go here for more details: https://nodesecurity.io/advisories?search=growl&version=1.9.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.10.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=minimatch&version=2.0.10 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=1.0.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] cached-path-relative has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=cached-path-relative&version=1.0.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-16T12_54_41_271Z-debug.log
The command '/bin/sh -c cd /app/ui   && npm install   && npm run build --server' returned a non-zero code: 1

**Comment by gregoirer** [comment]
By the way I may want to contribute (on python client), how do you proceed ?

**Comment by robpickerill** [comment]
I deleted `ui/package-lock.json` as it appeared to be outdated, allowing the npm install to recreate it.

**Comment by anshumanr** [comment]
For the install i changed the command to `npm install --no-shrinkwrap --update-binary`. This worked for me.

**Comment by demichej** [comment]
> to fixe the issue apply the following patch in package-json.lock:
> 
> ```
>      "lazy-debug-legacy": {
> -       "version": "0.0.1",
> +       "version": "0.0.3",
>        "resolved": "https://registry.npmjs.org/lazy-debug/-/lazy-debug-0.0.3.tgz",
> -      "integrity": "sha1-U3cWwHduTPeePtG2IfdljCkRsbE=",
> +      "integrity": "sha1-gswqb03PNvrPDHp5RoV7/2KCisc=",
>        "dev": true
>      },
> ```

@gregoirer  Should this be committed permanently? Seems like it should be...
