### ISSUE TITLE
Is it possible to fire an event via REST API?

### ISSUE THREAD

**Issue by MaksimRT** [Netflix/conductor#1056]

**Comment by kishorebanala** [comment]
Hey @MaksimRT, which event were you referring to? Can you provide more details and possibly an example for what you are trying to achieve.

**Comment by MaksimRT** [comment]
@kishorebanala Hi! Thank you for responce!
Yes, sure.
I just want to test eventHandler via REST API.

**Comment by kishorebanala** [comment]
@MaksimRT EventHandler could handle events received. The only way conductor can fire an event is with Event task. Checkout documentation: https://netflix.github.io/conductor/configuration/eventhandlers/ or Event Handler lab in documentation, or the API structure to learn more.
