### ISSUE TITLE
Info for workflow scheduling

### ISSUE THREAD

**Issue by ajayaks** [Netflix/conductor#106]
Hi, 

I have 2 questions here as below:-

1. Is there way we can schedule a workflow? Means instead of running workflow via workflow/{name} on request, request should be scheduling the workflow?

2. When we start a new workflow , its goes into Running state, means its already started. Where teh concept queue comes into picture ? I have seen info about the dyno ques , so what changes in need to make it use with dyno queus and how will it impact the current flow and UI? I am currently running it without any queue.

What changes i need to do for this?

Please suggest.

Regards
Ajay

**Comment by v1r3n** [comment]
Ajay,

1.  Scheduling is currently not supported.  You can use an external scheduler to make REST calls to the workflow APIs and execute them on a scheduled basis,  but Conductor does not provide any scheduling function.
2.  Queues are used internally to store the pending tasks.  The poll() method for tasks are polling work items through queue.  Dyno queues are used by default, you do not need to make any changes to use them.

**Comment by jas34** [comment]
Commenting to provide the latest update:
- The capability to schedule conductor workflow is here: https://github.com/jas34/scheduledwf
- The project has been listed in the conductor community projects: https://github.com/Netflix/conductor/blob/main/RELATED.md#schedule-conductor-workflow
