### ISSUE TITLE
Wrong times for decision and fork tasks

### ISSUE THREAD

**Issue by emiteze** [Netflix/conductor#1061]
During some tests we noticed that scheduled, start and end times for decision and fork tasks were a little bit confusing. We ran the above workflow:

![Screenshot from 2019-03-20 17-07-57](https://user-images.githubusercontent.com/13343278/54715831-1fc61000-4b33-11e9-9940-1de1ea5c965a.png)

Here are the resumed JSON from the execution that I took from conductor-ui:

```json
{  
   "createTime":1553108639406,
   "updateTime":1553108644261,
   "status":"COMPLETED",
   "endTime":1553108644261,
   "workflowId":"8684d51a-73b5-4b5f-bdc7-b9eba85441d3",
   "tasks":[  
      {  
         "taskType":"DECISION",
         "status":"COMPLETED",
         "referenceTaskName":"Conditional01",
         "scheduledTime":1553108639892,
         "startTime":1553108640457,
         "endTime":1553108639655,
         "updateTime":1553108644319
      },
      {  
         "taskType":"FORK",
         "status":"COMPLETED",
         "referenceTaskName":"Fork01",
         "scheduledTime":1553108640052,
         "startTime":1553108640535,
         "endTime":1553108639575,
         "updateTime":1553108644399
      },
      {  
         "taskType":"HTTP",
         "status":"COMPLETED",
         "referenceTaskName":"Request01",
         "scheduledTime":1553108640209,
         "startTime":1553108641042,
         "endTime":1553108643079,
         "updateTime":1553108644479
      },
      {  
         "taskType":"HTTP",
         "status":"COMPLETED",
         "referenceTaskName":"Request02",
         "scheduledTime":1553108640338,
         "startTime":1553108641201,
         "endTime":1553108643075,
         "updateTime":1553108644557
      },
      {  
         "taskType":"JOIN",
         "status":"COMPLETED",
         "referenceTaskName":"Join01",
         "scheduledTime":1553108641579,
         "startTime":1553108641683,
         "endTime":1553108643847,
         "updateTime":1553108644635
      }
   ]
}
```

In this case, DECISION task has scheduledTime greater than startTime and endTime less than both. For the FORK task, just the endTime is less than scheduled and start times.

After some debugging we noticed that in some cases scheduledTime was being set more than one time, and endTime was not being updated after being set. Have you guys noticed this as well or this is the first report for this problem? Maybe this is a good contribution that we can do.

**Comment by apanicker-nflx** [comment]
@emiteze Thanks for pointing this out, please feel free to contribute a fix for this.

**Comment by apanicker-nflx** [comment]
Closing issue as #1073 is merged.
