### ISSUE TITLE
Can I set a timeout for a WAIT task

### ISSUE THREAD

**Issue by rajanigk** [Netflix/conductor#1062]
Is it possible to set a timeout for the wait task. Let us say we are waiting for a sqs event to happen to wake up the wait state, and if the event does not happen with in a time period, then the wait task can timeout and the workflow can fail.

**Comment by apanicker-nflx** [comment]
@rajanigk Yes, you can register a task definition for the WAIT task with a timeout set to a particular value and this would cause the WAIT task to be timed out if no external event is received within that time.

**Comment by rajanigk** [comment]
WAIT_TASK is a system task, i used to not write a task definition for the same. After seeing this response i set the taskdef as follows, but the task did not timeout, it continued to be IN_PROGRESS state.  Can you tell me what mistake i am making in my taskdef or workflow definition?
 {
      "name": "response1",
      "retryCount": 1,
      "retryLogic": "FIXED",
      "retryDelaySeconds": 10,
      "timeoutSeconds": 30,
      "timeoutPolicy": "TIME_OUT_WF",
      "responseTimeoutSeconds": 18
    },

And in the workflow i have the following task,

  {
            "name": "response1",
            "taskReferenceName": "response1",
            "type": "WAIT",
            "startDelay": 0
            },
