### ISSUE TITLE
Cannot set responseTimeoutSeconds to 0

### ISSUE THREAD

**Issue by NV4RE** [Netflix/conductor#1067]
Ref document

responseTimeoutSeconds | If greater than 0, the task is rescheduled if not updated with a status after this time (heartbeat mechanism). Useful when the worker polls for the task but fails to complete due to errors/network failure. | defaults to 0
-- | -- | --

task def
```
{
      name: "hello_world",
      retryCount: 3,
      inputKeys: [],
      outputKeys: [],
      timeoutPolicy: "TIME_OUT_WF",
      retryLogic: "FIXED",
      retryDelaySeconds: 0,
      responseTimeoutSeconds: 0,
      timeoutSeconds: 0
    }
```

conductor's response
```
{
  "status": 400,
  "message": "Validation failed, check below errors for detail.",
  "retryable": false,
  "validationErrors": [
    {
      "path": "registerTaskDef.arg0[0].responseTimeoutSeconds",
      "message": "TaskDef responseTimeoutSeconds: 0 should be minimum 1 second",
      "invalidValue": "0"
    }
  ]
}
```

But in reality the **default value is 3600** and it **cannot set to 0**

ENV: docker
TAG: V2.8.3

**Comment by kishorebanala** [comment]
Thanks for pointing this out. We've just updated the docs.
