### ISSUE TITLE
Can I set a timeout for a WAIT TASK

### ISSUE THREAD

**Issue by rajanigk** [Netflix/conductor#1068]

**Comment by rajanigk** [comment]
This is related the issue https://github.com/Netflix/conductor/issues/1062, it was closed so i had to open another issue. As per the comment in the issue 1062, we can set timeout for the WAIT TASK.
WAIT_TASK is a system task, i used to not write a task definition for the same. After seeing this response i set the taskdef as follows, but the task did not timeout, it continued to be IN_PROGRESS state. Can you tell me what mistake i am making in my taskdef or workflow definition?
{
"name": "response1",
"retryCount": 1,
"retryLogic": "FIXED",
"retryDelaySeconds": 10,
"timeoutSeconds": 30,
"timeoutPolicy": "TIME_OUT_WF",
"responseTimeoutSeconds": 18
},

And in the workflow i have the following task,

{
"name": "response1",
"taskReferenceName": "response1",
"type": "WAIT",
"startDelay": 0
},

**Comment by kishorebanala** [comment]
@rajanigk Thanks for reporting this. We'll debug to figure out why the WAIT task wouldn't timeout and update here.

**Comment by rajanigk** [comment]
I did some debugging of the code and found that in the DeciderService.java (com.netflix.conductor.core.execution;) the task definition for the pendingTask (when it is WAIT_TASK) is coming as null. That is why the timeout is not getting honored. I did not figure out why it is coming as null.

 for (Task pendingTask : pendingTasks) {

            if (SystemTaskType.is(pendingTask.getTaskType()) && !pendingTask.getStatus().isTerminal()) {
                tasksToBeScheduled.putIfAbsent(pendingTask.getReferenceTaskName(), pendingTask);//TODO This line is not needed
                executedTaskRefNames.remove(pendingTask.getReferenceTaskName());
            }

            Optional<TaskDef> taskDefinition = pendingTask.getTaskDefinition();

            if (taskDefinition.isPresent()) { <--- here it is null for WAIT TASK
                checkForTimeout(taskDefinition.get(), pendingTask);
                // If the task has not been updated for "responseTimeoutSeconds" then mark task as TIMED_OUT
                if (isResponseTimedOut(taskDefinition.get(), pendingTask)) {
                    timeoutTask(taskDefinition.get(), pendingTask);
                }
            }

**Comment by rajanigk** [comment]
I was looking at the following code in the MetaDataMapperService.java 

public static boolean shouldPopulateDefinition(WorkflowTask workflowTask) {
        Preconditions.checkNotNull(workflowTask, "WorkflowTask cannot be null");
        Preconditions.checkNotNull(workflowTask.getType(), "WorkflowTask type cannot be null");
        return workflowTask.getType().equals(TaskType.SIMPLE.name()) &&
              workflowTask.getTaskDefinition() == null;
      
    }

If i change the return statement to the following it works, but i am not sure whether that is the right fix
  return    ((workflowTask.getType().equals(TaskType.SIMPLE.name())) ||  (workflowTask.getType().equals(TaskType.WAIT.name()))) &&   workflowTask.getTaskDefinition() == null;
