### ISSUE TITLE
Dynamic fork join task fails if any subworkflow fork fails

### ISSUE THREAD

**Issue by swarooppradhan** [Netflix/conductor#1070]
I have dynamic fork join with subworkflow tasks as forks. If any subworkflow fails then join task fails, failing the entire workflow. I set optional=true on dynamically created subworkflow task but did not help. How can I make sure that join task and workflow doesn't fail if any subworkflow fork fails?
I'm using conductor version 1.12.3

**Comment by swarooppradhan** [comment]
It seems join task doesn't check if the forked task is optional or not.

**Comment by swarooppradhan** [comment]
https://github.com/Netflix/conductor/pull/1072

**Comment by swarooppradhan** [comment]
Join task is checking for forked subworkflow task status before DeciderService updates the status for forked task to COMPLETED_WITH_ERRORS

**Comment by apanicker-nflx** [comment]
Closing this issue since it is fixed as part of #1166
