### ISSUE TITLE
Java Heap Memory Error occured while doing performance test with single redis instance

### ISSUE THREAD

**Issue by gsambasiva** [Netflix/conductor#1080]
Hi,
we are doing peformance testing for conductor using single redis instance.
After some time, we are getting java heap memory error.
Took the heap dump using jvisualvm and analyze that heap dump using Eclipse MAT.

Observed that there is memory leak occured with class RedisDynoQueue and for filed prefetchedIds of type ConcurrentLinkedQueue.

Attached MAT analyzer diagram.
Could any one plese help on this issue.

<img width="653" alt="OE_memory_leak_error_1" src="https://user-images.githubusercontent.com/22830714/55228694-d10a2b80-5240-11e9-898a-40767859f5c4.PNG">
<img width="737" alt="OE_memory_leak_error_2" src="https://user-images.githubusercontent.com/22830714/55228695-d1a2c200-5240-11e9-8bf5-7b2c5eef4819.PNG">

**Comment by kishorebanala** [comment]
@gsambasiva Thanks for sharing this. Queues remain in Redis cluster or node for the duration of Workflow or Task lifecycle, and across workflows for task reference name. It may or may not be a memory leak after all.

Could you share more details on how many workflows and tasks were in running state when you see this error.

**Comment by mudit3774** [comment]
@gsambasiva are you using ES Async DAO ?

**Comment by gsambasiva** [comment]
I am not facing this issue again, and closing the ticket
