### ISSUE TITLE
What is the recommended way of testing workflow?

### ISSUE THREAD

**Issue by MaksimRT** [Netflix/conductor#1081]

**Comment by kishorebanala** [comment]
Hey @MaksimRT, It'd help to have more details on what you're trying to achieve, preferably with an example. I'm not sure if you're looking to test Workflow execution as an integration test, or to test a specific task type.

If it is integration testing a workflow, you can define workflow executions with fake data and run regression tests on your test cluster or a container.

**Comment by MaksimRT** [comment]
Hi @kishorebanala! Thank you for reply!

Yes, I want to run an integration test. 

I want to check that all steps (fork, join, if, switch and order of execution) is executed correctly based on input data.

I have to use the following API to do this:
`GET /workflow/{workflowId}?includeTasks=true`

Then I have to parse the result and check it.

Am I right?
