### ISSUE TITLE
Is it possible to turn dag-format workflow definition to conductor's dsl-format automatically?

### ISSUE THREAD

**Issue by yangjiajun2014** [Netflix/conductor#1082]
A workflow defined in dag-format looks like:
{
 "tasks":{
     "t1":{
         "Task definition of t1" 
      },
	  "t2":{
         "Task definition of t2" 
      },
	  "t3":{
         "Task definition of t3"
      },
	  "t4":{
         "Task definition of t4"
      }
  },
  "links":{
	"1":{
		"src":"t1",
		"dst":"t2"
	},
	"2":{
		"src":"t1",
		"dst":"t3"
	},
	"3":{
		"src":"t2",
		"dst":"t4"
	},
	"4":{
		"src":"t3",
		"dst":"t4"
	}
  }
}
The tasks' execution order of this workflow will be: t1->[t2,t3]->t4,which means t2,t3 execute in parallel.Such format provides an opportunity to define workflow visually.Is it possible to let conductor support it?

**Comment by apanicker-nflx** [comment]
@yangjiajun2014 This is not possible currently. It is a long-term goal for conductor to be able to define workflows using a visual tool at which time such a feature could come in handy/would be implemented.
