### ISSUE TITLE
How to use 'vipAddress' feild in 'http_request'?

### ISSUE THREAD

**Issue by wudadadaju** [Netflix/conductor#1085]
I want to make a Task that can be associated with erueka service cluster.
But i don't know how can i use it.
I know 'http_request' has a feild 'vipAddress'.
How do I configure the url of the eureka service?

**Comment by kishorebanala** [comment]
Hi @wudadadaju, this question is best answered by Eureka service. HttpTask can optionally support vipAddress and using it is straightforward as simply adding it to task configuration params, along with URI.
