### ISSUE TITLE
failureWorkflow doesn't have access to workflow output

### ISSUE THREAD

**Issue by avorima** [Netflix/conductor#1086]
This feature was mentioned in [this comment](https://github.com/Netflix/conductor/issues/212#issuecomment-309128082) almost two years ago.

I'm using conductor 2.8.4 and it still doesn't seem to be implemented. Does this feature have an ETA yet?

**Comment by kishorebanala** [comment]
Hey @avorima, thanks for checking. This is still not a priority over other features we're working on and the bandwidth we have. Feel free to initiate a conversation or submit a PR, if you think this is something valuable to you and community.
