### ISSUE TITLE
Help needed for writing a new system task

### ISSUE THREAD

**Issue by rajanigk** [Netflix/conductor#1090]
i was trying to see how to extend conductor by writing a new system task.  As per the documentation given at https://netflix.github.io/conductor/extend/
following steps are given in the documentation.
1. Extend com.netflix.conductor.core.execution.tasks.WorkflowSystemTask
I created a new project in intellij and created a new class newSysTask which extends WorkFlowSystemTask

2. Instantiate the new class as part of the startup (eager singleton)
Created a new class: 
public class NewTaskModule extends AbstractModule {
    protected void configure() {
        bind(newSystemTask.class).asEagerSingleton();
    }
    @ProvidesIntoMap
    @StringMapKey("NEWSYSTASK")
    @Singleton
    @Named("TaskMappers")
    public TaskMapper getnewSysTaskMapper(ParametersUtils parametersUtils) {
        return new newSysTaskMapper(parametersUtils);
    }

}
3.Implement the TaskMapper interface
Created another class called newTaskMapper which implements the TaskMapper

4. Add this implementation to the map identified by TaskMappers

I think this step is covered in what i did in step 2.

Later on in the server.properties file i added the following line

conductor.additional.modules=com.hp.example.systask.NewTaskModule

in the build.gradle under server i put a dependency on the jar by placing the jar in the mylibs folder under the home directory of conductor
compile fileTree(dir: 'mylibs', include: 'newSysTask-1.0-SNAPSHOT.jar')

But when i run gradlew server i get the following error
java.lang.ClassNotFoundException: com.hp.example.systask.NewTaskModule
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.netflix.conductor.core.config.SystemPropertiesConfiguration.getAdditionalModules(SystemPropertiesConfiguration.java:196)
	at com.netflix.conductor.bootstrap.ModulesProvider.get(ModulesProvider.java:47)
	at com.netflix.conductor.bootstrap.Main.main(Main.java:53)

Am i missing something? Any help to get my newSystask added to conductor will greatly help.
Regards,
Rajani

**Comment by kishorebanala** [comment]
Hey @rajanigk, you can check one of the merged PRs as reference to add new system task. But before you do that, can you open a conversation about what this system task would do, how it would look like, what value it provides to community etc. Once we decide on specifics, you can send in PR with your implementation. Looking forward to your contributions. Thanks.

**Comment by rajanigk** [comment]
we are evaluating netflix conductor to be used as a workflow engine, so i was trying to see how to extend a system task, i was able to make changes to conductor code and add a new system task . I was thinking may be i can create a jar with new new system task , and just a dependency on that jar in the build.gradle of the server and add it is as an additional module by settting the property in server.properties,  would work. While i tried to add as additional module it did not work.
