### ISSUE TITLE
Need Help in Designing Micro-service deployed on ECS

### ISSUE THREAD

**Issue by saurabhsharma721** [Netflix/conductor#1093]
We are currently going to work on Solution which will work with collaboration of multiple microservices to provide us with solution.  Dataflow like below

![MicroserviceDataFLow](https://user-images.githubusercontent.com/14283388/55590535-2b9ffd80-5701-11e9-93e4-17ea8e86170d.jpg)

These services will be deployed in ECS with ALB in front of it. Needed to stich toigether a workflow for the system and needed help in following

1- We plan to use Route 53 DNS service for Service Discovery.  I know that conductor uses eureka client for service discovery. Is it possible just to swap put of use DNS based implementation rather than Eureka??

2- Can Conductor be deployed as docker images in ECS cluster? Can i create this internal to Ecs cluster and not deploy it on Ec2 servers?Any documentation will help? Do we maintain Docker Images or we need to create our own?

Thanks for any help in advance.

3-

**Comment by dskarataev** [comment]
1. you can use Application Load Balancer + dynamic ports in ECS cluster, it is working fine for us
2. of course can, running fine for us in ECS cluster. We use Docker images from Conductor repository and push Docker containers to ECR, then ECS service can use them to run

**Comment by saurabhsharma721** [comment]
@dskarataev How will this work  in multiple environments? I.e we will change the Load-balancer DNS in all environments while updating workflow jsons?So no need for svc discovery? Any other pointers we need to run it for ECS for very high load application. Thanks for the help

**Comment by dskarataev** [comment]
As I know from reading answers of maintainers in older issues of this repo, Netflix Conductor was not designed to be a "very high load application". Or maybe it is a matter of what exactly you consider as a very high load.

Answering your Load Balancer & ECS question, you can read details here: http://www.tothenew.com/blog/dynamic-port-mapping-in-ecs-with-application-load-balancer/

In two words, you set up it just once and then it works automatically, no need to update anything.

**Comment by saurabhsharma721** [comment]
@dskarataev One more query . and then we can close the issue. Is Conductor suitable for Low latency systems?we are asking Latency in mili seconds. When i sayhigh load , we are thinking about 1 to 2 million per day with 70 percent in 10 hr window?

**Comment by saurabhsharma721** [comment]
Closing issue
