### ISSUE TITLE
Add a workflow version column on executions page

### ISSUE THREAD

**Issue by dskarataev** [Netflix/conductor#1095]
Right now it is not convenient to do not see what workflow version is executed inside the executions list.

We execute more than one version at the same time to compare their results so it would be really nice to see the "Version" column right after the "Workflow" column and also have the "Version" filter to easily see all executions for a specific version of the workflow.

Thank you!

**Comment by apanicker-nflx** [comment]
@dskarataev Thanks for the suggestion. Please feel free to make a contribution for the same, we will add it to our wishlist.

**Comment by dskarataev** [comment]
thanks a lot! really happy to see it is implemented!
