### ISSUE TITLE
start a new subworkflow task rather than retry

### ISSUE THREAD

**Issue by HenryLauu** [Netflix/conductor#1099]

**Comment by HenryLauu** [comment]
I have several subworkflow in my workflow(say wf1), when one of the subworkflow (say wf2) failed, I retry the wf1 and then engine launch a completely new wf2,rather than retry from the last failed task in wf2, is there any way to achieve that?

**Comment by kishorebanala** [comment]
@HenryLauu From your example, wf1 considers wf2 as one of the tasks, and on retry, it reschedules a new task, which translates to new wf2 as expected. If this is not intended, then instead of wf1, wf2 should be retried.

**Comment by HenryLauu** [comment]
thanks @kishorebanala but how can I make wf1 continue when I retry wf2 and completed it ?

**Comment by HenryLauu** [comment]
wf1 is now staying in CANCELLED status
