### ISSUE TITLE
Ability to fetch workFlow execution status  from  indexdao  through the api. 

### ISSUE THREAD

**Issue by naveenchlsn** [Netflix/conductor#1100]
We clean up our workflow execution data from our execution database(redis) once the workflow has completed/terminated.
 
But we are not able to view the workflow on the ui dashboard once its removed from execution database.
This is because workFlow service queried by UI only looks up workflows in execution dao. I would like to have WorkflowService.getExecutionStatus accept a parameter to include workflows from indexed database. 

Please let me know your thoughts. @cyzhao @apanicker-nflx @mashurex @kishorebanala @mudit3774

**Comment by kishorebanala** [comment]
Hey @naveenchlsn, If you're using ExecutionDAOFacade, this should be done readily: https://github.com/Netflix/conductor/blob/8fc13b09347383c746fb789240114860ac945354/core/src/main/java/com/netflix/conductor/core/orchestration/ExecutionDAOFacade.java#L71. However, if you're using your custom implementation to get workflows, you can implement something similar.
