### ISSUE TITLE
Isolation and Scaling of HTTP tasks. 

### ISSUE THREAD

**Issue by naveenchlsn** [Netflix/conductor#1103]
**Issue** 
We have http tasks for running multiple apis. HTTP tasks take different times to execute based on the api they are calling. This causes slow running HTTP tasks to pile up and cause fast running tasks to starve. 
**Proposal** 
Have the ability for separate queue and worker for each HTTP task. 

**Implementation.**  
1)  Accept a param isolationGroup in WorkFlowTask definition. 
2) Change QueueUtils to append isolationGroup to the queueName if the task has it. 
3) Have a TemplateSystemCoordinator, get all the queues with isolation groups and execute each queue in a different thread pool. 
4) TemplateSystemCoordinator can be a optional module, as it increases the complexity of system task execution.  

**Benefits.** 

1. Slow Running HTTP tasks wont block fast running tasks. 
2. If conductor wants to support tasks for sending template messages to rabbitMQ, Kafka similar to HTTP  this can help. 

**Rejected Implementations**  

1. We have thought of leveraging domain instead of isolation group. But domain is made for polling tasks and I wanted to support a similar notion for system tasks. 
2. We can have multiple JVM deployments for a group of HTTP task queues, but this would lead to  increased maintenance of conductor due to multiple deployments. 

I am implementing this in our organisation.  I would like to contribute if you think this is helpfull to the community. Please let me know your thoughts
@cyzhao @apanicker-nflx @mashurex @kishorebanala @mudit3774

**Comment by cyzhao** [comment]
@naveenchlsn thanks for the proposal, I definitely think this is something nice to have. @kishorebanala please @apanicker-nflx please chime in and work with Naveen on this.

**Comment by kishorebanala** [comment]
Hey @naveenchlsn, This looks great to me. I have a question or concern though:

If users were to create hundreds or thousands of isolation groups in a shared server environment, how would creating thread pool per isolation group scale?

**Comment by mudit3774** [comment]
@naveenchlsn we need to consider a workerDomain in which we group tasks together. So the client can choose to have thread-pool level isolation for "isolationGroup" and "workerDomain" level isolation which corresponds to JVM / Runtime level isolation. 

IMO, we should not be spending time coming up with the right scheduling algorithms. It should be left to the client to come up with a scheduling algorithm using these two levers - isolationGroups and workerDomains

Thoughts? @cyzhao @naveenchlsn @kishorebanala

**Comment by naveenchlsn** [comment]
@mudit3774  This looks great to me. I think we can implement the isolation incrementally. The first draft can contain plain isolation groups. Then we can enhance it with "workerDomain". 

@cyzhao @apanicker-nflx @mashurex @kishorebanala @mudit3774 I have a branch ready with changes for isolation groups. If you are okay with the approach, I can raise the PR for the same.

**Comment by naveenchlsn** [comment]
Raised a PR regarding the changes we are discussing. Please take a look. @cyzhao @apanicker-nflx @mashurex @kishorebanala @mudit3774

**Comment by josephrjd** [comment]
Hi Team,

I have tried this with a couple of times, but this feature is not working for me with the http system tasks.
I tried debugging with the configurations and versions, but seems i am stuck with this will all combinations.

Can someone help me on this? - I have added simple def of what i am trying to do

Task
```
[
    {
        "name": "fetch_data",
        "retryCount": 0,
        "timeoutSeconds": 3600,
        "timeoutPolicy": "TIME_OUT_WF",
        "retryLogic": "FIXED",
        "retryDelaySeconds": 0,
        "responseTimeoutSeconds": 3000
    },
    {
        "name": "fetch_data1",
        "retryCount": 0,
        "timeoutSeconds": 3600,
        "timeoutPolicy": "TIME_OUT_WF",
        "retryLogic": "FIXED",
        "retryDelaySeconds": 0,
        "responseTimeoutSeconds": 3000,
        "executionNameSpace": "executionNameSpace1"
    }
]
```

Workflows
```
{
    "ownerApp": "test-app",
    "createdBy": "eventbus-backend",
    "name": "test-quick-run-flow",
    "description": "Test Workflow to quickly run and complete workflow to test",
    "version": 1,
    "tasks": [
        {
            "name": "fetch_data",
            "type": "HTTP",
            "taskReferenceName": "fetch_data",
            "inputParameters": {
                "http_request": {
                    "connectionTimeOut": "6000",
                    "readTimeOut": "6000",
                    "uri": "http://slowwly.robertomurray.co.uk/delay/3000/url/http://www.google.com",
                    "method": "GET",
                    "accept": "application/json",
                    "content-Type": "application/json",
                    "headers": {
                    }
                }
            }
        }
    ],
    "outputParameters": {
    }
}

{
    "ownerApp": "test-app",
    "createdBy": "eventbus-backend",
    "name": "test-quick-run-flow",
    "description": "Test Workflow to quickly run and complete workflow to test",
    "version": 2,
    "tasks": [
        {
            "name": "fetch_data1",
            "type": "HTTP",
            "taskReferenceName": "fetch_data",
            "inputParameters": {
                "http_request": {
                    "connectionTimeOut": "6000",
                    "readTimeOut": "6000",
                    "uri": "http://slowwly.robertomurray.co.uk/delay/3000/url/http://www.google.com",
                    "method": "GET",
                    "accept": "application/json",
                    "content-Type": "application/json",
                    "headers": {}
                }
            }
        }
    ],
    "outputParameters": {
    }
}
```

Let me know in case i can help with something
