### ISSUE TITLE
Could you add a sleep task to System Tasks?

### ISSUE THREAD

**Issue by MaksimRT** [Netflix/conductor#1104]
I want to have ability for workflow instance to wait for a while.

**Comment by kishorebanala** [comment]
@MaksimRT There already exists a WAIT task: https://netflix.github.io/conductor/configuration/systask/#wait

Or, are you looking for something different? If so, please reopen the ticket with more details.

**Comment by MaksimRT** [comment]
Yes, I am looking for something different.

I just want that the WAIT (or any other task) could be set as COMPLETED by conductor itself after some fixed amount of time. Right know I have to manually set it via externel REST call.

Do you get what I mean?

**Comment by kishorebanala** [comment]
You can try using `timeoutSeconds` in task definition and `optional` in Workflow tasks to achieve the same with WAIT task.

**Comment by vmaks** [comment]
Great idea! 
Never think about it (
Thank you!

**Comment by yangzhang21** [comment]
I tried this but looks it doesn't work. The wait task runs forever.....The task I added is like this. Did I make anything wrong? Thanks. @kishorebanala 
`                {
                    "name": "delay",
                    "taskReferenceName": "delay",
                    "type": "WAIT",
                    "optional": True,
                    "timeoutSeconds": 60
                },`

**Comment by neokyle1** [comment]
Yeah, it looks like maybe this workaround broke with Conductor v3?
