### ISSUE TITLE
Should worker send a update task state request to conductor before executing task?

### ISSUE THREAD

**Issue by leikao** [Netflix/conductor#1105]
When I'm trying to set `responseTimeoutSeconds` to a little period such as 10 seconds, the task state will be set to `TIMED_OUT` while task is still executing.
So should worker add a request to update the task state before executing the polled task?

I'm using the go client:
https://github.com/Netflix/conductor/blob/8fc13b09347383c746fb789240114860ac945354/client/go/conductorworker.go#L88-L95

**Comment by kishorebanala** [comment]
Hey @leikao, If your worker couldn't finish task execution within `responseTimeoutSeconds`, it should update the task. Otherwise, Conductor would assume that the Worker is dead and times out the task.
