### ISSUE TITLE
How to get workflow completed event from conductor?

### ISSUE THREAD

**Issue by carlylou** [Netflix/conductor#1108]
I know I can get workflow status using workflowid. But in my use case, I have too many workflow instance and I can not keep all those workflow id and keep querying whether this workflow completed.  And I know I can make the last task worker send some message to outside. But in my case, I can not make this. So, I want to ask, is there another way to get informed that a particular workflow instance completed just from conductor server side? Thanks in advance.

**Comment by kishorebanala** [comment]
Hey @carlylou, You can use https://github.com/Netflix/conductor/blob/master/contribs/src/main/java/com/netflix/conductor/contribs/listener/DynoQueueStatusPublisher.java or implement https://netflix.github.io/conductor/extend/#workflow-status-listener to provide your own custom listener.
