### ISSUE TITLE
redis pub/sub to publish when a task is created

### ISSUE THREAD

**Issue by philipodev** [Netflix/conductor#1110]
Hi. first and foremost, thank you guys for this awesome piece of software.

I was wondering about the possibilities, and if it has been brought up yet and in that case what was the verdict, regarding using redis to `PUBLISH` to a channel (ex: `conductor.worker.W1` when there is a new task scheduled for it. 

I think in our case that would be a nice complement to traditional polling where we are using docker swarm and each worker/service usually is scaled up to 2 or more. So instead of having `N` workers polling (1 * scaled) times a second for tasks, using redis (or other) pub/sub to publish.

**Comment by kishorebanala** [comment]
Hey @philipodev, Thanks for the suggestion in using pub/sub with Redis over polling. We do have plans to implement pub/sub, most probably as major version V3. But, we're not sure about the timeline. If you think you've enough bandwidth to help us accomplish this, we'd be very glad to coordinate with you.

**Comment by philipodev** [comment]
Hi. Thank you for the reply.
I made a quick check before opening this issue and it seems that right now `publish` and `subscribe` is currently unsupported/not implemented in `DynoJedisClient`: 
https://github.com/Netflix/dyno/blob/master/dyno-jedis/src/main/java/com/netflix/dyno/jedis/DynoJedisClient.java#L3229

I would love to help in any way you would let me.

**Comment by kishorebanala** [comment]
@philipodev Apologies for delayed response. Yeah, Dyno client is yet to support pub / sub. But, the implementation in Conductor should be generic, configurable with at least one default implementation. Say, using Redis client. We shall check with Dynomite's roadmap for adding pub/sub.

Please add your proposal to this thread, with a brief overview of how the implementation would look like, and we shall take it to PR from there.

**Comment by manheiba** [comment]
Conductor client registers available nodes to the server, then the server calls the client through RPC, would that be better?

**Comment by kishorebanala** [comment]
@manheiba Conductor already has a gRPC implementation, which can be leveraged to support push tasks to workers. This also avoids the need to maintain a discovery layer. The specifics of this implementation, for eg., how the server would schedule tasks on 'n' available workers is yet to be figured.
