### ISSUE TITLE
Workflows get marked Completed while tasks are still remaing

### ISSUE THREAD

**Issue by mohelsaka** [Netflix/conductor#1111]
We've encountered very weird issue with conductor. Some workflows were marked as "Completed" while their tasks were still "Scheduled". Therefore, those tasks were marked as "Canceled" by the Conductor background systemTask worker.

This happened for HTTP tasks in particular. Looking into the logs of the server, we saw the following warnings:
```
Workflow WF_ID has been completed for HTTP/TASK_ID
```

Looking at the code from which this warning come from, it came from [here](https://github.com/Netflix/conductor/blob/8fc13b09347383c746fb789240114860ac945354/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L1006).

Could you please tell me what could be causing this problem?

We're running conductor server v2.9.1 with Redis.

**Comment by mohelsaka** [comment]
Can that be related by anyway to the concurrency problem mentioned in this [issue](https://github.com/Netflix/conductor/issues/759)?

**Comment by kishorebanala** [comment]
Hey @mohelsaka, thanks for reporting this. Can you please provide workflow execution json and relevant logs.

**Comment by ggrekhov** [comment]
Hey @kishorebanala, please, check this gists out.
1. [Workflows definitions](https://gist.github.com/ggrekhov/2c2dfcb61402bf61afb8c041ba203f23).
2. [Server logs 1](https://gist.github.com/ggrekhov/be216f98098be0172d764abd8e44b8e8).
3. [Server logs 2](https://gist.github.com/ggrekhov/6d7723bcce184ebc77fab255da081ac1).

We run Conductor 2.9.1 on 2 servers using a shared Redis and Elasticsearch setup.
![workflow](https://i.imgur.com/vH6DZ43.png)

**Comment by mohelsaka** [comment]
Hi @kishorebanala,
Can we please get help with that? It happened multiple times on our production setup and we failed to find the root cause.

**Comment by kishorebanala** [comment]
Hey @mohelsaka, apologies for delays. From the logs, I believe it's a concurrency issue. But that's only a part of the problem. One of the concurrent decides have passed `checkForWorkflowCompletion`, and we cannot reason why. Because this method can be tested in isolation, we'll try to add unit tests with different workflow executions.

On the other side, we're working on a locking solution, which should prevent concurrent decides.
