### ISSUE TITLE
Bug in workflow metadata validation

### ISSUE THREAD

**Issue by artpdr** [Netflix/conductor#1115]
I updated conductor to version 2.10.0 and after that I am seeing a bug that was not present on a previous version (2.1.1).
The bug happens during workflow definition, when a worker task has a vector as an input parameter and this vector has an entry with an empty string (e.g. inputParameters: {distinct_paths_used_per_task: ["", "foo", "bar"]}).

Here is the response from conductor server:
ERROR: {"status":400,"message":"Validation failed, check below errors for detail.","retryable":false,"validationErrors":[{"path":"updateWorkflowDef.arg0[0]","message":"key: distinct_paths_used_per_task input parameter value: is null or empty"}]}

**Comment by apanicker-nflx** [comment]
@artpdr Thanks for reporting the bug. Please feel free to contribute a fix for this issue.

**Comment by artpdr** [comment]
@apanicker-nflx I may contribute to this if there isn't anyone working on this issue.

**Comment by apanicker-nflx** [comment]
There isn't anyone actively working on this atm, so feel free to send a PR with the fix.

**Comment by artpdr** [comment]
PR sent. I will be waiting for news from your side...
