### ISSUE TITLE
Task definition timeouts being ignored by HTTP task

### ISSUE THREAD

**Issue by emiteze** [Netflix/conductor#1117]
So, we are facing a "problem" here that we don't know yet if it is a problem, or just a misunderstanding.

I created a workflow definition with 1 http task that calls an endpoint "https://httpstat.us/200?sleep=30000" that answers with 30 seconds of delay. The timeoutSeconds was set to 15 and responseTimeoutSeconds to 10 on the task definition used by this http task.

Apparently, the HTTP task is ignoring the timeoutSeconds property of the task definition. We noticed that when the http call is being made, the task still remains SCHEDULED, which might be a problem cause according to the documentation, timeoutSeconds works when the task remains too much time in the status IN_PROGRESS (right?)

According to #1025 we have 2 new properties that can be passed as inputParameters of HTTP_TASK (or via application.properties) and would be set on jersey client, but is these properties the right properties that we want to set? Should these properties had the same behaviour of the task definition timeout properties? I tought that we could set these 2 properties to 0 and let the task definition controls the timeout (that makes sense to me).

- [task_definition](https://gist.github.com/emiteze/0ee8d45f0dcaf8c9f3261d3c3ff60d7d)
- [workflow_definition](https://gist.github.com/emiteze/8101e9541d933c5e7ae041799136b050)
- [execution](https://gist.github.com/emiteze/68c75b87d696ce6431b7440603ecb1fa)

**Comment by kishorebanala** [comment]
Hi @emiteze, It is possible the Http task (which is a System task) may not be respecting task definition timeouts as SIMPLE tasks would do. We'll try to debug and verify this case. The new properties would enforce timeouts through jersey client, you should be able to enforce timeouts with those properties. From your example, the jersey client should timeout after 15s, and end the http task.

**Comment by yangzhang21** [comment]
@kishorebanala  @mohelsaka , i had an issue similar. I use conductor to start a HTTP task, which will take two minutes to finish. However, after a round 30 seconds, before the task is done, somehow conductor kicks off the task again and I see poll count become 2. Here I set the task timetoutSeconds, responseTimeoutSeconds, http readTimeout and connectionTimeout to some value big enough. But it still doesn't work. What I want is just to let the task run once. Any clue? Thanks!

**Comment by kishorebanala** [comment]
@yangzhang21 I'm curious, how the Http task message is available again for poll (after ~30s), while the task is still in progress. What does your Conductor set-up look like?

Also, HTTP task taking ~2mins is an anti-pattern, and I'd recommend looking into `asyncComplete`, or executing this process in a simple task.

**Comment by yangzhang21** [comment]
@kishorebanala , yea, i use a HTTP task to invoke a lambda which will run a while. now I changed it to async type and it works fine. the extra work for async is to call back to conductor and mark the task done when the task finishes.
