### ISSUE TITLE
keep task execution on same worker (question)

### ISSUE THREAD

**Issue by gregoirer** [Netflix/conductor#1119]
Hello,

Let's say I have a simple workflow T1 -> T2 (move file to encoder) -> T3 (encode). Two different workers (machines) can handle T2, T3. 
But after T2 completed I would like T3 be executed by the same machine than T2. I there a way to dynamically change the task domains of a running workflow ? or any other way to solve this use case ?

PS: I don't know when I start the workflow which worker will be available first.

Thanks

**Comment by kishorebanala** [comment]
@gregoirer The tasks and workers are supposed to be loosely coupled. The most simplest way to achieve what you're looking for is to have just one task, that does the work of both tasks. Other than that, I don't think there are any out of box solutions to solve this use case.

**Comment by gregoirer** [comment]
@kishorebanala many thanks for your answer
