### ISSUE TITLE
Deprecation of Nashorn JavaScript Engine in OpenJDK

### ISSUE THREAD

**Issue by gsambasiva** [Netflix/conductor#1120]
Hello, 
Conductor is using Nashorn javascript Engine and it is going to be deprecated in from OpenJDK.
I got to know from this link (https://openjdk.java.net/jeps/335)

If it is the case, how Netflix conductor will work with OpenJDK, once Nashron javascript Engine get deprecated?

**Comment by kishorebanala** [comment]
@gsambasiva Thanks for mentioning about Nashorn engine deprecation. When we migrate Conductor to latest JDK version, which would definitely be a Major Conductor release, we'll try to replace Nashorn with closer implementation. For eg., https://stedolan.github.io/jq/ seems a reasonable alternative.
