### ISSUE TITLE
What to do in eclipse so it builds the proto files

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1121]
Building 2.10.1 works fine from the commandline as gradle has the plugins to compile the .proto files. With Eclipse these files dont get generated even if conductor is imported as a gradle project. What is the preferred way to build the grpc modules in eclipse?

**Comment by jkaipa** [comment]
This is what I do. 
1. run gradlew build in the root folder of conductor. This will generate all java sources from proto files.
2. Add source folder per the image.
![Screen Shot 2019-04-29 at 2 26 32 PM](https://user-images.githubusercontent.com/30670101/56921319-1f525a80-6a8b-11e9-9347-b3403982881e.jpg)

**Comment by rickfish** [comment]
Thanks for the help. Will do the same.
