### ISSUE TITLE
workflow.elasticsearch.version not being used anymore?

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1122]
Is there a reason why the workflow.elasticsearch.version prop is not used to decide on whether to use es5 or es6? Is es6 not working yet?

**Comment by RuriRyan** [comment]
If you want to use es6 you have to compile conductor yourself. It's all described here: https://github.com/Netflix/conductor/tree/master/es6-persistence

**Comment by kishorebanala** [comment]
@rickfish When we added this property, we were shadowing ES2 dependencies. But it has slowed down builds considerably. Hence, we avoided shadowing and preferred to use only one of ES modules since Conductor v2.0
