### ISSUE TITLE
conductor-ui is failing to build with docker-compose build on fresh checkout

### ISSUE THREAD

**Issue by demichej** [Netflix/conductor#1123]
I am not sure why, but this ticket was closed out, but never actually resolved:

#1054 

One of the dependencies had its resolve url updated to a new version......but nothing else was updated to use that new version. So it fails with an EINTEGRITY error.

@apanicker-nflx , is there a bug tracking this? It's currently broken.

**Comment by smullins3000** [comment]
This same issue bit me yesterday.

**Comment by apanicker-nflx** [comment]
@demichej Thanks for pointing this out, seems like I accidentally closed the issue. We will roll out a fix for this soon. Please feel free to contribute a fix if you need it soon.

**Comment by demichej** [comment]
@apanicker-nflx I submitted a PR to fix up the integrity issue.
