### ISSUE TITLE
How to implement a workflow for Member Detail Search?

### ISSUE THREAD

**Issue by gansa1986** [Netflix/conductor#1128]
Team,

We have an use case where we would need to query a member detail search using the first name and zipcode of the member as filter conditions.

We have two microservices, 1. Member 2. Member Address
1. From Netflix Conductor we are trying to implement a workflow
2. Search member by first name
3. Search member address by Zipcode
4. Both are parallel calls
5. Now we want to merge the #2,#3 based on member Id returned from the response.

How do we do that from Conductor?

**Comment by kishorebanala** [comment]
@gansa1986 How about creating another task that accepts above two task's output as input? You can check this: https://netflix.github.io/conductor/configuration/workflowdef/#wiring-inputs-and-outputs, if you're not already familiar with task i/o wiring.

Feel free to reopen the issue if that doesn't answer your question.
