### ISSUE TITLE
How to Consume a Conductor workflow from a Client Microservice?

### ISSUE THREAD

**Issue by gansa1986** [Netflix/conductor#1129]
Team,

We have our workflow metadata and tasks configured in Conductor. But we would like to execute the workflow with a wrapper service which will act as a simple webservice and polls workflow to trigger a request and get response once the workflow is completed. How do we do that?

Does worker server means a wrapper service or is it different from wrapper service?

**Comment by kishorebanala** [comment]
Hi @gansa1986, I believe you're looking for Worker implementation? Here is a sample in Java: https://github.com/Netflix/conductor/blob/master/client/src/test/java/com/netflix/conductor/client/sample/SampleWorker.java 

Basically, SIMPLE tasks in workflow are implemented by Workers, which would be part of your micro service.
