### ISSUE TITLE
Implement generic locking interface

### ISSUE THREAD

**Issue by kishorebanala** [Netflix/conductor#1137]
Provide a generic locking interface, that is plugged into Decider service to avoid #759 .

Other features:
- Locking interface should be reusable; Along with Decider service, it should be generic enough to be used in other features as required.
- Users should be able to plug-in their own locking implementations.
- Decider service should have a property to disable locking for maintenance.

**Comment by milongapau** [comment]
Broadly speaking, Conductor chunks up a workflow execution into a series of segments, each segment has a “load-execute-persist” pattern.  To use Redlock (see below for analysis), we need to address:
- Write (persist) inconsistency
- Double execution: a segment of a workflow may be executed more than once (see example in analysis below).
- Ttl expiry: with `decider()` recursively calling itself, one segment of a workflow execution may take longer than ttl duration, the server should not expire the lock while a Worker is still in the midst of active execution.

Our first choice for locking implementation is with dynomite.  We're in conversation with dynomite team with this proposal:
- Dynomite supports fencing:
    + generates monotonically increasing tokens on acquireLock
    + supports write with fencing
- Dynomite supports automatic expiry extension
- Conductor system tasks are idempotent
- Conductor simple tasks are _strongly_ urged to be idempotent, or have a way to compensate double execution

====================
### **Proposed Locking API**

 An example usage:
```
    fencingToken = acquireLock(workflowInstanceId, 5, TimeUnit.MILLISECONDS);
    [load and execute workflow....]
    DAO.writeWithFencing(fencingToken, workflow)
    releaseLock(workflowInstanceId, fencingToken)
```

```
public interface Lock {
  
   /**
    * acquire a re-entrant lock on lockId, return immediately regardless if the lock is available
    * @param lockId resource to lock on
    * @return a monotonically increasing number if successful
    */
   Optional<Long> acquireLock(String lockId);

   /**
    * acquires a re-entrant lock on lockId, block for timeToTry duration before giving up
    * @param lockId resource to lock on
    * @param timeToTry blocks up to timeToTry duration in attempt to acquire the lock
    * @param unit time unit
    * @return a monotonically increasing number (fencing token), if successful
    */
   Optional<Long> acquireLock(String lockId, long timeToTry, TimeUnit unit);

   void releaseLock(String lockId, Long fencingToken);

   Boolean hasLock(String lockId, Long fencingToken);
}
```

====================
### **Redlock Algorithm Analysis**
Redlock is a distributed locking algorithm recommended by [Redis](https://redis.io/topics/distlock).  In the same article, it states three properties are the minimum guarantees needed to use distributed locks effectively:

1. Safety property: Mutual exclusion: at any given moment, only one client can hold a lock
2. Liveness property: Deadlock free: eventually it is always possible to acquire a lock, even if the client that locked a resource crashes or gets partitioned.
3. Liveness property: Fault tolerant: as long as the majority of Redis nodes are up, clients are able to acquire and release locks.

Martin Kleppmann wrote a [detailed analysis ](http://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html)on Redlock, in which he makes the case that Redlock is not a safe choice when _correctness (or consistency)_ depends on the lock.  Redlock works correctly only in a synchronous system model with these properties:
Bounded network delay
Bounded process pauses
Bounded clock error
With internet-scale distributed systems, one should not make the above assumptions.  

There are several scenarios where the system can end up with two threads both believe it holds the valid lock(guarantee #1 above is not met).  One example is a process pause:

1. Thread 1 requests lock on workflowInstanceA
2. Thread 1 goes into stop-the-world GC after receiving the lock
3. Lock expires on servers after ttl
4. Thread 2 acquires lock on workflowInstanceA and starts execution
5. Thread 1 finishes GC, and starts execution
6. Thread 1 and 2 now both believe it holds the valid lock, and are both executing workflowInstanceA ==> double execution

Fundamentally a client cannot know if the server has expired the lock it holds, thus will continue execution until the next check in.  To address this, Martin proposed adding a fencing token(monotonically increasing) with every write request to Redis storage service.  Add fencing makes write to datastore consistent, however double execution, like in the above process pause example, can still occur.

**Comment by skyrocknroll** [comment]
@milongapau We can implement fencing using Redis lua script?

**Comment by naveenchlsn** [comment]
Since the aim of the locking interface is to prevent conflicting writes and not mutual exclusion,  can we use optimistic locking as mentioned [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.OptimisticLocking.html)?

I think the locking mechanism, as mention above, would be expensive to implement. 
* To get the lock, we would need consensus among the Redis nodes about which client holds the lock. 
* In the article by [Martin Kleppmann](http://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html), he has mentioned we would need another consensus algorithm to generate the fencing tokens. 

Reducing the high overheads with optimistic locking will make the conductor more scalable. 
Thoughts? @kishorebanala @milongapau

**Comment by milongapau** [comment]
@skyrocknroll Redis lua script ensures write consistency (i.e. write only if my fencing token > what's already there).  Someone still need to generate fencing tokens.  If you use zookeeper for locking, znode version number can be used as fencing token.

**Comment by milongapau** [comment]
@naveenchlsn optimistic locking alone will address write inconsistency, but does not attempt to address multiple executions (that's where the locking part comes in).

**Comment by naveenchlsn** [comment]
@milongapau @kishorebanala  Two questions. 
1. Can we not allow parallel executions since workflow tasks are idempotent. 
>  Conductor system tasks are idempotent
Conductor simple tasks are strongly urged to be idempotent, or have a way to compensate double execution

2. The lock is not entirely safe, and parallel executions can still happen. Please let me know what we are loosing by not having such a lock? 
> Add fencing makes write to datastore consistent, however double execution, like in the above process pause example, can still occur.

**Comment by milongapau** [comment]
@naveenchlsn you're correct.  If you can (1)ensure tasks are idempotent or can be compensated easily at the frequency they occur, and (2)you don't care about efficiency, optimistic locking at data persistence level is sufficient and simpler to implement.

**Comment by naveenchlsn** [comment]
@milongapau Thanks for the clarification. 

Can we make the locking interface so we can choose between optimistic and pessimistic locking? 

We are running conductor at high throughput, and having a costly decide function would  not be ideal for us. Our tasks are idempotent, and we can live with only optimistic locking. 

Tangent on locking: 

If you want a lock for performance optimization, consider using single instance [lock](https://redis.io/commands/set ) by Redis.  Although this provides lower guarantees than your current implementation, this will be more efficient as we won't need to generate a  fencing token using a linearisable store like Zookeeper

**Comment by milongapau** [comment]
@naveenchlsn great suggestion.  I'll rework locking API so it's cleaner for those who only want/need one part of the proposed solution.

**Comment by milongapau** [comment]
### **AN UPDATE (9/9/2019):**
Since May, we internally have moved to use Cassandra for data persistence instead of Redis. Consequently we decided to implement this solution using zookeeper for distributed locking instead of dynamite and Cassandra LWT for consistent datastore write.

**Comment by kishorebanala** [comment]
Update: Locking service Beta is available: https://github.com/Netflix/conductor/releases/tag/v2.15.2-beta. 

Here's some documentation for more context and getting started:
- https://netflix.github.io/conductor/technicaldetails/#maintaining-workflow-consistency-with-distributed-locking-and-fencing-tokens
- https://netflix.github.io/conductor/server/#setting-up-zookeeper-to-enable-distributed-locking-service
- https://netflix.github.io/conductor/extend/#locking-service

Please feel free to reach-out with any questions or concerns.

**Comment by kelnos** [comment]
Hi @kishorebanala, you mentioned in https://github.com/Netflix/conductor/issues/759 that the dynomite team would be adding a Redlock implementation to the dyno library that could also be used.  Looks like there's an impl in dyno now, but it seems like this hasn't been integrated into Conductor yet as a possible implementation.  Is there any downside to using that instead of Zookeeper?  I'd rather not have to stand up a ZK cluster to get this working.

**Comment by kishorebanala** [comment]
@kelnos I'll copy over the convo from email here, if anyone in the community also has same question.

Locking with Dyno client is not implemented in Conductor. It is possible to implement another module for locking with DynoLock, similar to Zookeeper module. We're also working on a Redlock with Redisson client module.

**Comment by AnnsPhilip** [comment]
@kishorebanala We are using V2.29.0 release with Redis. Still we are facing issues. Subworkflow is completed but main workflow is still in running state. Is there any configuration to be added or am I missing anything?
![subworkflow](https://user-images.githubusercontent.com/65964511/98084586-0ad1f800-1ea2-11eb-8c1e-549e661c6d18.PNG)
![MainWorkflow](https://user-images.githubusercontent.com/65964511/98084590-0c9bbb80-1ea2-11eb-8c6b-27f2d4a6690c.PNG)
