### ISSUE TITLE
Issue when using a virtual Host for a service in 2.10.1

### ISSUE THREAD

**Issue by rabonja** [Netflix/conductor#1142]
I am having an issue with the new conductor build that is causing my task to throw an error of : 
ERROR com.netflix.conductor.contribs.http.HttpTask  - Failed to invoke http task - uri: http://virtual.host:5555/, vipAddress: null
com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out
 
If I change the virtual host to the actual server name the task will complete and work as normal.  I have other task using the same virtual host and they work just fine.  All of these task are working correctly in build 2.5.8.  This issue only started to happen when moving to the newest build 2.10.1.

**Comment by naveenchlsn** [comment]
We have 2 new properties that can be passed as inputParameters of HTTP_TASK (or via application.properties) and would be set on jersey client, Please refer #1025 

Please update the properties if the defaults are not working for you.

**Comment by rabonja** [comment]
Used the new options and also changed the default timeout settings
