### ISSUE TITLE
Do you have API for generation workflow in code?

### ISSUE THREAD

**Issue by MaksimRT** [Netflix/conductor#1143]

**Comment by apanicker-nflx** [comment]
Hi @MaksimRT , we do not have an API to programmatically generate workflows at this time. However, it is on our [wishlist](https://github.com/Netflix/conductor/wiki/Conductor-Wishlist#usability) to provide this through a self-service UI. 
An API to facilitate this UI would definitely be a good starting point.

Please feel free to contribute by starting a discussion about the implementation.
