### ISSUE TITLE
Task startTime not reset when rerunning a workflow from that task

### ISSUE THREAD

**Issue by renuka-raju** [Netflix/conductor#1148]
Upon rerunning a workflow from a specific task, the task's startTime is not reset, causing the workflow to get TIMEDOUT. I can see from the code that, when the task is executed, it checks if the startTime is already set and doesn't reset it. Could we also reset the startTime of this task while resetting its status upon rerun, before adding it to the queue?

**Comment by apanicker-nflx** [comment]
@renuka-raju Thanks for pointing this out. We will release a fix in a future release. Also, please feel free to contribute a fix for this issue.
