### ISSUE TITLE
Question about deploying conductor in a jee container

### ISSUE THREAD

**Issue by virursingh** [Netflix/conductor#115]
Hi,

While the server seems to embed jetty in it.
How easy it would be to build it and deploy in a standard JEE container?

Thanks !

**Comment by v1r3n** [comment]
@virursingh it is possible.  We do deploy into a tomcat container.  Take a look at the code for the server module, if you assemble the required modules into a war and deploy to a standard container.

**Comment by virursingh** [comment]
Hi,

Appreciate the quick response. 

I am trying to put the war together. 

It would be useful to add web.xml into git repo so others can benefit. If u have it handy could u please email it to me?

Thanks,

- Viru. 

*Snt frm a typogrphicaly challengd dvice

**Comment by v1r3n** [comment]
@virursingh please take a look at the server module in `dev` branch.  We have some initial config for producing a war file that can be deployed in a jee container.

**Comment by virursingh** [comment]
cool. let me give it a try. will revert with findings. Thanks!

**Comment by v1r3n** [comment]
The new builds also publishes war files to repository.  There is no certified built yet (we are working on it), but you can use one of the snapshots.  Let us know your findings.

**Comment by v1r3n** [comment]
@virursingh as part of the 1.7.0 changes, we publish the war files. The files are also available in the release version in github here:

https://github.com/Netflix/conductor/releases/tag/v1.7.0

Give it a try and let us know if you face any issues.

**Comment by virursingh** [comment]
Hi Viren,

Appreciate the information. 
I have been a bit busy in some other areas. I should be back playing around with Conductor this week. I will provide the feedback in the later part of the week.

Thanks,

- Viru. 

*Snt frm a typogrphicaly challengd dvice

**Comment by v1r3n** [comment]
@virursingh If you were able to make use of the `war` file please share your feedback. meantime, closing this issue.  Newer versions now include a `war` file which can be downloaded from the github's release page.
