### ISSUE TITLE
Sequential loop of list?

### ISSUE THREAD

**Issue by goodengineer** [Netflix/conductor#1152]
Hi, I have the following scenario:

Task A: generates a list
Task B: can handle an element in that list

With Dynamic fork I was able to process the elements in taskA.output.list using taskB, but it is done in a concurrent way. Now I need to do the same but in a sequential way (i.e: one element at a time). After all elements are done, I need to handle all results in a single place, similar to what I get as the output of the Join task after a dynamic fork. Is there any way to do so with current Conductor system tasks?

**Comment by Jiehong** [comment]
Such a task does not exist (yet) as far as I know

**Comment by apanicker-nflx** [comment]
This is correct, this feature does not exist yet. Please follow #1169 for this feature.
