### ISSUE TITLE
Cannot poll scheduled tasks from AWS Managed Elasticcache Redis cluster

### ISSUE THREAD

**Issue by surendrapamidi** [Netflix/conductor#116]
At Cars.com we are introducing this framework for some of the workflows and we are looking at ways to reduce the operational complexity of the hosting the persistence infrastructure  in the cloud ( a.k.a Dynomite and Elasticsearch) and and leverage existing AWS managed services.  We have successfully extended the indexDAO to communicate with AWSHosted Elasticsearch, the existing ElasticsearchDAO does not work as the AWS managed ES only offers http/s transport. 

For the persistence, we are trying to figure out if we could leverage the AWS managed Elasticcache Redis Cluster with Multi-AZ support introduced for 3.2.X version for high availability and we are running into issues with DynoQueues and the client does not receive the polling tasks with no errors indicated in the logs.  The batch poll returns an empty array though we can see the in-progress tasks for scheduled {taskName} queue as well as _deciderQueue. The RedisMetaDAO and RedisExecutionDAO seems to work fine. 

Before we spend too much time on this, We'd like to know if we should try this approach or leverage Dynomite instead. Also any pointers to help debug the issue.

Here are the conductor JVM arguments.
-Dconductor.additional.modules=com.netflix.conductor.contribs.ContribsModule,com.netflix.conductor.contribs.AWSElasticsearchModule -Dworkflow.elasticsearch.index.name=conductor -Dworkflow.elasticsearch.tasklog.index.name=task_log -Dworkflow.dynomite.cluster.name=dynomite_conductor -Dworkflow.dynomite.cluster.hosts=conductor-db.xxxxxxxx.clustercfg.use1.cache.amazonaws.com:6379:us-east-1b; -Ddb=redis -Dqueues.dynomite.nonQuorum.port=6379 -DEC2_AVAILABILTY_ZONE=us-east-1b -Dworkflow.namespace.queue.prefix=conductor_queues -Dworkflow.namespace.prefix=conductor

Let us know if we are missing anything and appreciate any assistance in this regard.

**Comment by v1r3n** [comment]
@surendrapamidi We have not tested with ElasticCache but technically it should work.  
The reason for the queues not polling seems to be the typo in the `DEC2_AVAILABILTY_ZONE` parameter, which causes the queues to not read the correct shard resulting in empty polls.

```
#This is the config - notice the typo
#EC2_AVAILABILTY_ZONE=us-east-1b
#Change to this
EC2_AVAILABILITY_ZONE=us-east-1b
```

Let me know if this helps.  
It would be great if you can contribute back the DAO layer for AWS hosted Elasticsearch - might be beneficial to others too.

**Comment by surendrapamidi** [comment]
Thank you. Appreciate the quick response. It is working now. We will test this further and post the changes required for this for others to benefit.

We would love to contribute the AWSElasticsearchDAO (just needs some cleanup and comments) but lets us know the process involved.

**Comment by v1r3n** [comment]
@surendrapamidi You can send a pull request from your fork to `dev` branch.  This is probably best suited to be put in the `contribs` module - it already has a dependency on the aws client SDK.

**Comment by v1r3n** [comment]
@surendrapamidi let us know if possible your experience with aws elasticservice and if you will consider contributing it back.

**Comment by surendrapamidi** [comment]
@v1r3n We have got the Conductor Server to work on AWS managed infrastructure using Elastic Search and Redis. Conductor Server and UI were running on Docker Swarm framework on AWS as well.  However, we haven't really tested in the production yet as the team got de-railed to tackle few other priorities and we will soon begin the work again. I'll commit the Elastic Search code today.

**Comment by kpdude7** [comment]
@surendrapamidi Our company is also looking at an Elasticache/Redis cluster solution; did you ever commit your code? Where can I find it? And can you elaborate on any other details you had to do to get this solution to work (config changes, etc)?

**Comment by bitbier** [comment]
Having the same issue here. We were running a single redis server and then went into using elasticache so that we can scale up and have failover built in. But since moving to elasticache (Redis with Cluster Mode enabled), we are having issues with our workflows failing in multiple random parts of the workflow. Not sure if there is a missing configuration issue or not. I've also set the `EC2_AVAILABILITY_ZONE` to the appropriate value, but still having trouble with workflows randomly stopping in various parts of the workflow (even for system specific tasks like decide and join, etc).
