### ISSUE TITLE
Question : Retrying workflows having concurrently executing tasks

### ISSUE THREAD

**Issue by renuka-raju** [Netflix/conductor#1160]
If I have a workflow like the one below and tasks T2 and T3 fails, how can I retry this workflow to run from failed tasks(T2,T3 in parallel) -> JOIN -> Task T4

                    FORK
                /       |      \
               /        |        \
             T1      T2      T3
               \        |        /
                 \      |      /
                    JOIN
                        |
                        |
                       T4

Does the retry workflow api that fetches failed tasks and schedules them, execute the workflow to completion, if it has concurrent tasks? How are sequence numbers assigned to tasks that needs to execute in parallel? 
Thanks!

**Comment by apanicker-nflx** [comment]
Please follow this codepath - https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L415 to see how tasks are retried.

**Comment by renuka-raju** [comment]
Thanks for the update.
