### ISSUE TITLE
how to reference an output file from a previous task in a fork task ?

### ISSUE THREAD

**Issue by fabienpesty** [Netflix/conductor#1165]
Hi,
Here is my workflow : 

![workflow_pluri_simplified](https://user-images.githubusercontent.com/10595704/58465385-de0ba400-8137-11e9-95c2-a8949c174234.jpg)

described as follows : 

![worflow_definition_simplified](https://user-images.githubusercontent.com/10595704/58467305-aef73180-813b-11e9-9fed-e3068fde1f77.jpg)

Both tasks in the fork (t11 and t21) need the ouput file of t02 task as input file (line 54/55 and 73/74).
When i run the workflow, i have the following error :  "InputFile.Path": ["The Path field is required."]
Input file (and bucket) reference seems to be unreachable. Do you know why ? 
And do you know how is it possible to reference the output file (anf bucket) from t02 in the fork tasks ?

Thanks a lot

**Comment by kishorebanala** [comment]
Hi @fabienpesty, Referencing previous task outputs from forked tasks wouldn't be any different from any other task types. I'm guessing it is a json path error, where the tasks t11 & t21 are unable to locate the bucket and path from given json path.

You can try debugging this by making sure t11 and t21 are getting inputs first. This can be checked by dumping all the output from t2, for eg: ```"bucket":"${t02.output}"```. Once it is determined that the tasks are actually getting the data from t02, you can tune your json path to find right values. You might find it helpful to use any json path validator tools to find right path, especially if your json is nested.
