### ISSUE TITLE
Not working on AWS

### ISSUE THREAD

**Issue by ajayaks** [Netflix/conductor#117]
Hi, 

I have deployed conductor on AWS and I am getting below issue:-

1. Can't read from server. It may not have the appropriate access-control-origin settings. I can see the swagger ui but not the apis list.

Regards
Ajay

**Comment by v1r3n** [comment]
@ajayaks Please provide the errors you see in the logs with the issues and some details on how you have deployed to AWS.

**Comment by ajayaks** [comment]
Hi viren,

no exception in log but getting below on swagger, please sugget.
![image](https://cloud.githubusercontent.com/assets/7519767/23597659/90474f96-01e9-11e7-82eb-9ed405be0f90.png)

**Comment by v1r3n** [comment]
@ajayaks the URL for swagger is pointing to localhost - it needs to point to the host where you have deployed. Checkout swagger documentation @ http://swagger.io/ if you need help with swagger.

**Comment by ajayaks** [comment]
You means to say i have to change the url in swagger index.html ? I think we have old version of swagger in conductor.

**Comment by v1r3n** [comment]
Yes.

**Comment by ajayaks** [comment]
I have already tested with url changes and its working but the solution is dirty. Do we have better solution like pass the host name and port via config file?

**Comment by v1r3n** [comment]
Thanks for the feedback.  We will try and address this in the coming releases.
