### ISSUE TITLE
Limiting parallelism in Dynamic Fork Task

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#118]
I have a follow up question to [here](https://github.com/Netflix/conductor/issues/30).

Let's say, I generate 100 dynamic tasks.
But I want Conductor to always have only up to a certain configured amount of tasks in the queue to be picked up by workers (i.e. a threshold).
Let's say, my "parallelism threshold amount" is set to 20. Then Conductor should only but 20 out of the 100 into the queue.
When one worker has finished one task, then Conductor is adding a new task to the queue to meet the maximum threshhold. 

Is there any way to implement this in Conductor workflows.

Many thanks for your help.

**Comment by v1r3n** [comment]
@blueelephants This is an interesting problem.  There is no server side support for this, but this can be done at the worker level using following:

* Limit the number of workers to a max value (say 20).   This means at a given time only 20 workers are executing tasks.
* Worker interface has a method `paused()` which returns true if the WorkflowTaskCoordinator should not poll for new tasks.  
* Return `true` when worker is "executing" as task.  Return false only if the worker is not busy (maintain an internal flag in worker implementation)

This will ensure that number of tasks that is getting polled out of the queue and getting executed are limited by the concurrency level set by workers.

Hope this helps.
