### ISSUE TITLE
How to generate Subworflow in dynamic_fork_join

### ISSUE THREAD

**Issue by milansanjeev** [Netflix/conductor#1185]
How to generate subworkflow dynamically on the in Dynamic Fork task. As I write my custom task to generate subworkflows and it is able to generate but non of the instace of subworkflow running.
In server I am observing No Such Workflow Error in conductor server.

**Comment by kishorebanala** [comment]
@milansanjeev You should be able to pass in subworkflow task to dynamic workflow, just like the other tasks. Ensure the sub workflow you're passing in is valid and available. Here is one example we use to do this:
```json
{
  "name": "my_adhoc_unregistered_workflow",
  "workflowDef": {
    "ownerApp": "my_owner_app",
    "createdBy": "my_username",
    "name": "my_adhoc_unregistered_workflow",
    "description": "Test Workflow setup",
    "version": 1,
    "tasks": [
        {
            "name": "test_task_1",
            "taskReferenceName": "sub1_test",
            "inputParameters": {
                "dynamicTasks": "${workflow.input.dynamicTasksJSON}",
                "dynamicTasksInput": "${workflow.input.dynamicTasksInputJSON}"
            },
            "type": "FORK_JOIN_DYNAMIC",
            "dynamicForkTasksParam": "dynamicTasks",
            "dynamicForkTasksInputParamName": "dynamicTasksInput"
        },
        {
            "name": "exclusive_join",
            "taskReferenceName": "exclusiveJoin",
            "type": "JOIN"
        }
    ],
    "outputParameters": {
    }
  },
  "input": {
    "dynamicTasksJSON": [
        {
            "name": "sub_workflow_task",
            "taskReferenceName": "sub1",
            "type": "SUB_WORKFLOW",
            "subWorkflowParam": {
                "name": "kbanala_test_http",
                "version": 0
            }
        }
    ],
    "dynamicTasksInputJSON": {
        "sub1": {
            "http_request": {
               "uri": "http://www.google.com",
               "method": "GET",
               "contentType": "application/json"
            }
         }
    }
    }
}
```

**Comment by milansanjeev** [comment]
Thanks, @kishorebanala for quick help.

I am also doing same generating multiple instances of sub workflow with the dynamic fork on the basis of data and it is able to create success but unable to run as all sub-workflow in scheduled status and on the server we are getting
Error No such workflow found by id
Es Error: Cannot execute jest action, response code: 400

Unfortunately, I am unable to post code due to security concern. But I will try to mock up the same on my local.

**Comment by apanicker-nflx** [comment]
Closing this for now since the response provided a solution, please reopen if you run into further issues.
