### ISSUE TITLE
collecting specific output from dynamic fork tasks as an array

### ISSUE THREAD

**Issue by SK465** [Netflix/conductor#1186]
I have a dynamic fork tasks and I want to pick specific output data in the form of array.
Like if I have forkTask0, forkTask1.. I need to collect specific values from each and create an array. How can I do that?

**Comment by apanicker-nflx** [comment]
@SK465 The JOIN task collects all the outputs from all the forked tasks. You can either use a LAMBDA task after the JOIN to pick out specific values from this output or you can use a SIMPLE task, wired with the output of the JOIN and you can write a worker to create this array.
