### ISSUE TITLE
Error when creating local server on my machine

### ISSUE THREAD

**Issue by SudheerD231** [Netflix/conductor#1188]
Popping Up error when installing Gradle on local machine to Create Local server- 
Gradle version - 5.4.1
Java 1.8.0_211

1 - >FAILURE: Build failed with an exception.
* Where:
Build file 'C:\Users\YQ8W\Documents\conductor-2.12.5\conductor-2.12.5\build.gradle' line: 12

* What went wrong:
Plugin [id: 'nebula.netflixoss', version: '5.1.1'] was not found in any of the following sources:

 2 -> BUILD FAILED in 2m 10s

C:\Users\YQ8W\Documents\conductor-2.12.5\conductor-2.12.5>ls -ltr
'ls' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\YQ8W\Documents\conductor-2.12.5\conductor-2.12.5>gradle -version
'gradle' is not recognized as an internal or external command,
operable program or batch file.

**Comment by apanicker-nflx** [comment]
@SudheerD231 Looks like you are running the server on a Windows machine and it is unable to find the path to the gradle executable.
