### ISSUE TITLE
Workflows using environment variables

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#119]
Hello,

Currently, I am providing some variables to a workflow by passing them via workflow input parameters when I start a workflow via the REST call.

However, is there any way that a workflow can access directly environment variables from the Conductor Server where it is run?

Thanks

**Comment by v1r3n** [comment]
Yes, for the input parameter configuration, you can pass env variables and they will be converted to the value when setting the input value.

e.g.  If the task's input is configured as:
```json
{
  "hostname": "${HOSTNAME}"
}
```

The input to the task will contain the actual hostname of the conductor server.  You can use any System properties (passed with -Dkey=value) or environment variable here.
