### ISSUE TITLE
HTTP task state changes from SCHEDULED to COMPLETED directly

### ISSUE THREAD

**Issue by rituparnopal** [Netflix/conductor#1193]
I am working with in-memory Conductor server instance with a some HTTP tasks in my workflow. However it seems there is no In Progress status as depicted in the Task State Diagram. I have a sufficient long running HTTP task of 1 min, but the status remain as SCHEDULED even when the task is executing and changes to COMPLETED almost instantly.

**Comment by kishorebanala** [comment]
@rituparnopal Because Http task is a system task and is expected to be finished instantly, it transitions from SCHEDULED to COMPLETED state, there by skipping IN_PROGRESS state.
