### ISSUE TITLE
HTTP task output content other than application/json

### ISSUE THREAD

**Issue by rituparnopal** [Netflix/conductor#1195]
I have some microservices which gives content other than application/json. However it is not working. If I set the contentType as text/plain under http_request it gives an exception that Message Convertor not found. Is it that Conductor is at present equipped to work with only application/ json content?

**Comment by apanicker-nflx** [comment]
@rituparnopal As mentioned here, currently Conductor HTTP task only supports `application/json` content type. If your api response is not json, you could implement this task as a SIMPLE task and write a worker to handle this response and transform the task output into json. 
Please also feel free to submit a PR with modifications to the HTTP task to enable other content types.

**Comment by rituparnopal** [comment]
But it is written in the table under HTTP Task-
contentType | Content Type - supported types are text/plain, text/html and, application/json
So is this wrong? 
(https://netflix.github.io/conductor/configuration/systask/)
I tried text/plain but it didn't work giving MessageOutputFormatException. For api which are xml based I am using worker only.

**Comment by apanicker-nflx** [comment]
Thanks for reporting the error in the docs. We will update this. For now, I would recommend using a worker for this api as well. And also, feel free to submit a PR with modifications to the HTTP task to add support for this.

**Comment by rituparnopal** [comment]
Sure, thanks!
