### ISSUE TITLE
killing the workflow task as per time mentioned

### ISSUE THREAD

**Issue by SudheerD231** [Netflix/conductor#1197]
I am trying to kill workflow task as per the time  i mentioned 300 seconds but even after that workflow is in progress stay and i don't know why and couldn't figure it out.

I would appreciate if anyone can help me out on this issue.

**Comment by apanicker-nflx** [comment]
Can you please elaborate on "kill workflow task"? Also it would be helpful if you could list out the steps that you have followed.
