### ISSUE TITLE
Workflow Update Request Silently Fails Unless Incremented Version is Provided

### ISSUE THREAD

**Issue by paltamadura** [Netflix/conductor#1199]
When attempting to update a workflow (`PUT /metadata/workflow`), it silently fails unless an incremented version is explicitly provided in the request object.

For example, a workflow with name "save_file" is currently at version 2. A `PUT /metadata/workflow` request to update the workflow with `"version": 2` specified will succeeded, however the changes are not actually saved to the workflow "save_file" version 2, nor is a new version, version 3, created. The behavior is the same (request succeeds, but no change actually occurs) if the version field is omitted from the request.

So it seems the only way to update a workflow is to manually provide the incremented version in the `PUT` request. In the example above, to update the "save_file" workflow which is currently at version 2, the update request must specify `"version": 3`.

Should the update workflow endpoint be enhanced to fail if the version is omitted from the request or if the version provided already exists? Or perhaps omitting the version should create a new incremented version of the workflow.

**Comment by apanicker-nflx** [comment]
@paltamadura Please provide details of your setup. Are you using dynomite persistence or mysql?

**Comment by paltamadura** [comment]
I didn't realize we had some custom logic in the persistence layer. Please disregard.
