### ISSUE TITLE
Disabling elastic search and indexing

### ISSUE THREAD

**Issue by kyle--lee** [Netflix/conductor#1202]
I looked through some of the existing issues opened and some indicated that it was not possible to disable use of elastic search (https://github.com/Netflix/conductor/issues/668), while others imply that indexing is optional (https://github.com/Netflix/conductor/issues/1087 and https://github.com/Netflix/conductor/issues/181). 

What exactly is the process of disabling indexing and elastic search?
1 ) Is there a configuration flag I can pass?
2) Do I have to extend `IndexDAO` that does nothing, and rebuild conductor from source?
3) Can I simply use an in-memory indexing, i.e. https://github.com/Netflix/conductor/blob/master/docker/server/config/config-local.properties#L38? It seems indexing is not useful for any of conductor's core functions, besides search abilities?

Thanks!

**Comment by apanicker-nflx** [comment]
@kyle--lee Elasticsearch cannot be disabled in the current version. 

1. This is not supported yet. It is one of our wishlist items to remove this enforcement (See 13 [here](https://github.com/Netflix/conductor/wiki/Conductor-Wishlist#usability)). 

2. Yes, if you do not intend to use ES, you should be able to achieve the same behavior using this option. However, the UI will be mostly non-functional.

3. You can choose to use in-memory indexing.

**Comment by kyle--lee** [comment]
Thanks for the quick reply!

**Comment by kyle--lee** [comment]
Actually - had one follow up question:
When using in-memory indexing, what exactly is the behavior? Reading through the source code, it seems to write files to disk/container filesystem - what is the index's behavior if it runs out of space/memory?

**Comment by apanicker-nflx** [comment]
@kyle--lee It is not advised to use in-memory indexing for your production usage, this should only be used for testing purposes.

**Comment by mdepak** [comment]
@apanicker-nflx In the [wishlist](https://github.com/Netflix/conductor/wiki/Conductor-Wishlist#usability), feature for making elastic search indexing optional is removed.  Is this feature implemented or is there any specific reason why indexing cannot be made optional?

**Comment by apanicker-nflx** [comment]
@mdepak This was removed after we enabled asynchronous indexing and removed elasticsearch from the critical path of workflow execution. The main reason why indexing cannot be made optional is that the UI would become non-functional without it and the search APIs can no longer be used. Given that the UI is a vital part of Conductor's offering, we decided to keep this a required dependency.

**Comment by RomanAlberdaSoftserveInc** [comment]
Hey, can we disable elastic search in our app and get a functional UI?
