### ISSUE TITLE
A sample code snippet to create the HTTPTask using conductor-client 

### ISSUE THREAD

**Issue by alexdethose** [Netflix/conductor#1203]
hi 
I am new to Netflix conductor.Can you please point out to some example how can i create/use HTTP TASK ,
how to start the workflow with httptask
How the http task is getting executed when the workflow is started

**Comment by apanicker-nflx** [comment]
Hi @alexdethose , Please check out the documentation for HTTP task [here](https://netflix.github.io/conductor/configuration/systask/#http) for usage. 
Please follow the documentation [here](https://netflix.github.io/conductor/gettingstarted/startworkflow/#start-workflow-request) for starting a new workflow. 

For an example of how to start a new workflow which uses a HTTP task, please try out the kitchensink workflow [here](https://netflix.github.io/conductor/labs/kitchensink/#definition). The `search_elasticsearch` task in this workflow is a HTTP task.
