### ISSUE TITLE
docker-compose command failing due to UI project issues

### ISSUE THREAD

**Issue by rituparnopal** [Netflix/conductor#1206]
Please let me know how this can be fixed-

C:\conductor\docker>docker-compose up
Building conductor-ui
Step 1/11 : FROM node:9-alpine
 ---> a56170f59699
Step 2/11 : MAINTAINER Netflix OSS <conductor@netflix.com>
 ---> Using cache
 ---> cb58c3671e7c
Step 3/11 : RUN apk update && apk add   autoconf   automake   libtool   build-base   libstdc++   gcc   abuild   binutils   nasm   libpng   libpng-dev   libjpeg-turbo   libjpeg-turbo-dev   python
 ---> Using cache
 ---> 33c048fe4926
Step 4/11 : RUN mkdir -p /app/ui
 ---> Using cache
 ---> a5877487f7cf
Step 5/11 : COPY ./docker/ui/bin /app
 ---> Using cache
 ---> 2ace4d9866ed
Step 6/11 : COPY ./ui /app/ui
 ---> Using cache
 ---> 4c713228f340
Step 7/11 : RUN chmod +x /app/startup.sh
 ---> Using cache
 ---> d6193446068c
Step 8/11 : RUN cd /app/ui   && npm install   && npm run build --server
 ---> Running in 8accfa7b0927
npm WARN notice [SECURITY] js-yaml has the following vulnerabilities: 1 high, 1 moderate. Go here for more details: https://www.npmjs.com/advisories?search=js-yaml&version=3.12.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] js-yaml has the following vulnerabilities: 1 high, 1 moderate. Go here for more details: https://www.npmjs.com/advisories?search=js-yaml&version=3.7.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] js-yaml has the following vulnerabilities: 1 high, 1 moderate. Go here for more details: https://www.npmjs.com/advisories?search=js-yaml&version=3.12.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=minimatch&version=0.3.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=minimatch&version=0.2.14 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=debug&version=2.2.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] braces has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=braces&version=1.8.5 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] node.extend has the following vulnerability: 1 moderate. Go here for more details: https://www.npmjs.com/advisories?search=node.extend&version=1.1.6 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://www.npmjs.com/advisories?search=debug&version=2.6.8 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] axios has the following vulnerability: 1 moderate. Go here for more details: https://www.npmjs.com/advisories?search=axios&version=0.17.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] marked has the following vulnerability: 1 moderate. Go here for more details: https://www.npmjs.com/advisories?search=marked&version=0.3.17 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=lodash&version=4.17.10 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm ERR! code EINTEGRITY
npm ERR! sha1-U3cWwHduTPeePtG2IfdljCkRsbE= integrity checksum failed when using sha1: wanted sha1-U3cWwHduTPeePtG2IfdljCkRsbE= but got sha1-gswqb03PNvrPDHp5RoV7/2KCisc=. (3612 bytes)
npm WARN notice [SECURITY] growl has the following vulnerability: 1 critical. Go here for more details: https://www.npmjs.com/advisories?search=growl&version=1.9.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has the following vulnerabilities: 1 high, 1 low. Go here for more details: https://www.npmjs.com/advisories?search=lodash&version=3.10.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has the following vulnerabilities: 1 high, 1 low. Go here for more details: https://www.npmjs.com/advisories?search=lodash&version=1.0.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=minimatch&version=2.0.10 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] cached-path-relative has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=cached-path-relative&version=1.0.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-04T05_18_51_408Z-debug.log
ERROR: Service 'conductor-ui' failed to build: The command '/bin/sh -c cd /app/ui   && npm install   && npm run build --server' returned a non-zero code: 1

**Comment by emiteze** [comment]
When I had this issue, deleting package-lock.json or updating like was did on this commit solved  (https://github.com/Netflix/conductor/commit/a8b3e24d66f3e53a5d032e0d60654ba3a5990eba).

**Comment by rituparnopal** [comment]
Worked like a charm! Thank you emiteze!
