### ISSUE TITLE
Introduce security model for workflows/tasks

### ISSUE THREAD

**Issue by andrea11** [Netflix/conductor#1208]
Hello,
I was wondering which approach do you suggest to add an access control to determine which tasks and workflows can be created, updated, retrieved, etc.

I have actually two propositions:

1. Have an interface that have a method for each action to determine if someone has right or not to perform this action. By default a stub implementation could be provided that authorize everything (backwards compatibility)
2. (More permissive) Have hooks that allows developper to perform action before and after each action (maybe achieved with an interface, or trying Aspect Oriented Programming)

What do you think? It is something that could be implemented in Conductor? 
If you have other propositions, please do not hesitate to mention it. 

Thanks

**Comment by kishorebanala** [comment]
Hey @andrea11, thanks for the proposal. Do you mind elaborating or providing an example for this: `Have hooks that allows developper to perform action before and after each action`?

Also, How is authorization handled for users vs task workers?

Both approaches looks promising, but I'd prefer a cleaner interface with backwards compatible defaults, that can easily be plugged in with any authorization implementation - meaning all the details of authorization provider like roles, scopes, permissions etc. which could differ for each authorization provider should be abstracted.

**Comment by smullins3000** [comment]
We are starting a project that includes securing the conductor APIs so I'm curious about this. The approach we're probably going to go forward with is to deploy conductor in multi-image containers where the conductor server is one image and the secured APIs are a second image with the secured APIs being the only ones that are publicly exposed by the container/orchestration layer.

What do you see as the main advantages of embedding the security in the current conductor APIs?

**Comment by Jiehong** [comment]
@kishorebanala I also agree with you here.

I think we cannot make any assumptions about how the security is handled, and we can also suppose that users/task workers can be handled differently maybe?

What about this idea:

For each Service, such as `WorkflowService`, we could add a new interface named "WorkflowServiceSecurity" containing 1 function throwing a specific exception for each function in `WorkflowService`. This exception can be cached, and the response can be determined by the clients directly, depending on its content (also filled by clients).
Then, we only need `WorkflowService` to have a new `withSecurity(WorkflowServiceSecurity security)` method, and the default implementation to call the security function at the beginning of each function.

Rinse and repeat for each service.

Pros: it's flexible in the security implementation
Cons: it's quite a lot of boilerplate. People could as well re-implement/extend `WorkflowService` directly
Question: what inputs do you provide to the methods in `WorkflowServiceSecurity`? Probably same is the ones in `WorkflowService`.

As an AOP functionality, we could indeed catch all access to all Services methods, and ask users to return a boolean given: 1. the method name/class, 2. the list of arguments that method takes, and follow-up with or not with the execution. That requires some reflection though, which might be a performance issue.

Any better ideas?

**Comment by kishorebanala** [comment]
@Jiehong Thanks for your suggestions. We're also researching about best possible approach to handle Authentication and Authorization in Conductor with internal Netflix security teams and other partners. We'll definitely take your inputs into consideration and will come up with a proposal when we have a plan defined.
