### ISSUE TITLE
Can we implement netflix conductor in Asp.Net C# applications ?

### ISSUE THREAD

**Issue by ghost** [Netflix/conductor#121]
Hi Team,

We have evaluating your Netflix conductor and have been struck with the following challenges,

#1. Is it possible integrate with C# , ASP.Net web applications ?
#2. If possible please post any reference link
#3. if not possible to integrate C# applications could you specify the challenges.

**Comment by v1r3n** [comment]
@RRDSeedTeam 

Conductor provides HTTP endpoints for its APIs that are used by remote workers to communicate.
This allows integration with workers written in any language or stack.  Conductor server is written in Java so the server needs to have Java installed, but you can write workers in any programming language.

Take a look at the client written in Python for example, that should give you an idea on how to write one in C#.

https://github.com/Netflix/conductor/tree/dev/client/python

**Comment by courosh12** [comment]
https://github.com/courosh12/conductor-dotnet-client
