### ISSUE TITLE
PATCH method not supported.

### ISSUE THREAD

**Issue by SK465** [Netflix/conductor#1210]
One of my http task involves PATCH method but seems like it's not supported by netflix conductor. Is there a way to get around it or I'll have to make changes to the api?

**Comment by apanicker-nflx** [comment]
@SK465 The HTTP task in Conductor uses the Jersey client internally to make HTTP requests. As discussed [here](https://github.com/eclipse-ee4j/jersey/issues/1639) , Jersey client does not support PATCH method.
As a workaround for this, you could implement your task as a SIMPLE task and a worker for this task can then use the Apache HTTP client internally to make the PATCH request to your API.
