### ISSUE TITLE
Build always uses 1.8 as inferred project

### ISSUE THREAD

**Issue by manjurad** [Netflix/conductor#1212]
I have a build machine on which I setup conductor builds (from a fork) a while ago (2017) and have been using it. This was 1.8 version at that time. Now I have synced from master to my fork and trying to build latest version but the inferred build still stays at 1.8. Is something cached in my system that is fixing the build at 1.8? I have tried to clean and run "./gradlew build".

**Comment by kishorebanala** [comment]
Hi @manjurad, Conductor doesn't pin to any version number. Is it possible to build on a fresh clone of Conductor?

**Comment by manjurad** [comment]
It wasn't on a fresh setup and it was an my environment
