### ISSUE TITLE
Passing State between Multiple Executions of the Same Task

### ISSUE THREAD

**Issue by paltamadura** [Netflix/conductor#1213]
When using the technique quoted directly below, how can state be passed from one execution of task to the next execution of the same task?

#35 
> When the task is marked as IN_PROGRESS it is put back in the queue and delivered to the worker again. However, the worker can set `callbackAfterSeconds` field along with the task status to indicate how many second, the server should wait before delivering the task again. With this, Conductor allows you to execute the same task multiple times with a delay between subsequent execution.

I found one way to do this (code snippet below), but it seems odd to use `task.getOutputData()` when typically a task would only use `task.getInputData()` to get the parameters required for its execution. 

Is there anything wrong with using this approach to pass state between executions of the same task? Or is there a better/cleaner way?

```
public TaskResult execute(Task task) {
    String state = (String) task.getOutputData().get("state");
    TaskResult result = new TaskResult(task);
    result.setStatus(TaskResult.Status.IN_PROGRESS);
    result.setCallbackAfterSeconds(1);
    result.getOutputData().put("state", isNullOrEmpty(state) ? "1" : state + state);
    return result;
}
```

**Comment by kishorebanala** [comment]
Hey @paltamadura, while it doesn't look intuitive, you can use the above approach to pass states b/w task executions. 

We're looking into looping and global state variables (#1207, #1169), which would solve this use case.
