### ISSUE TITLE
Identity System Task

### ISSUE THREAD

**Issue by paltamadura** [Netflix/conductor#1215]
I'm looking at using a DYNAMIC system task type essentially to avoid have to use a CASE and create a fanout of branches in the workflow. But I believe there's a need for an identity system task which is executed on the server and just passes its inputs through to its outputs (I can create a worker to do this but it's inefficient). Then you can have a DYNAMIC task which acts like an optional step. And maybe in addition to this proposed identity task type, the DYNAMIC task could be enhanced to take a default task which is run if the `dynamicTaskNameParam` (see below). Exposing this default task name in the workflow definition is favorable as it makes it clear and explicit rather than burying it in a task's code.

Thoughts?

```
{
  "name": "user_task",
  "taskReferenceName": "t1",
  "inputParameters": {
    "files": "${workflow.input.files}",
    "taskToExecute": "${workflow.input.user_supplied_task}"
  },
  "type": "DYNAMIC",
  "dynamicTaskNameParam": "taskToExecute",
  "defaultTaskNameIfNotProvided": "system_task_identity"
}
```

**Comment by kishorebanala** [comment]
@paltamadura Sounds interesting.

```I believe there's a need for an identity system task which is executed on the server and just passes its inputs through to its outputs``` - how about using `Lambda` task to achieve the same?

Also, `defaultTaskNameIfNotProvided` should probably be renamed to `fallBackTaskName` or something that explains the task to be executed in absence of `dynamicTaskNameParam `.
