### ISSUE TITLE
Order of execution of tasks

### ISSUE THREAD

**Issue by sathyatvrcbe** [Netflix/conductor#1223]
I have a small doubt on the order in which the tasks are executed in a given workflow. Pasting below one of the examples given in the documentation.

```
{
  "name": "encode_and_deploy",
  "description": "Encodes a file and deploys to CDN",
  "version": 1,
  "tasks": [
    {
      "name": "encode",
      "taskReferenceName": "encode",
      "type": "SIMPLE",
      "inputParameters": {
        "fileLocation": "${workflow.input.fileLocation}"
      }
    },
    {
      "name": "deploy",
      "taskReferenceName": "d1",
      "type": "SIMPLE",
      "inputParameters": {
        "fileLocation": "${encode.output.encodeLocation}"
      }
    }
  ],
  "outputParameters": {
    "cdn_url": "${d1.output.location}"
  },
  "failureWorkflow": "cleanup_encode_resources",
  "restartable": true,
  "workflowStatusListenerEnabled": true,
  "schemaVersion": 2
}
```

Here we have listed two tasks in the ```tasks``` array. Do the tasks get executed in the order they are mentioned in the array? Is there any way to set a dependency DAG and trigger execution based on the DAG?

**Comment by purohitatul** [comment]
Yes - they get executed in the order they appear in the array. https://netflix.github.io/conductor/configuration/workflowdef/#tasks-within-workflow. I don't believe there is any other dependency driven execution currently.

**Comment by apanicker-nflx** [comment]
Thanks for the response @purohitatul .

> Is there any way to set a dependency DAG and trigger execution based on the DAG?

@sathyatvrcbe  Can you please expand on this?

**Comment by sathyatvrcbe** [comment]
@apanicker-nflx 

Here is an example for DAG based workflow: https://github.com/argoproj/argo/blob/master/examples/README.md#dag

**Comment by apanicker-nflx** [comment]
@sathyatvrcbe Thanks for the explanation. This is currently not supported explicitly using the DAG dependencies, however, you can mimic a similar pattern using [system tasks](https://netflix.github.io/conductor/configuration/systask/) viz. fork/join, dynamic task, dynamic fork/join etc. Please let us know if this meets your requirement.
