### ISSUE TITLE
Testing workflow/task with  priority

### ISSUE THREAD

**Issue by shrimank** [Netflix/conductor#1224]
In the latest code observed that, you have added support to priority for workflow.
Need to understand how priority works with workflow/tasks when startWorkflow invoked.

I have tested with simple workflow, just calling an http task.
submitting 3 workflows with different priority, but the conductor server executing those workflows in order of submission(since you are scheduling the workflow for later some time).

Please need your help to understand and implement the priority with workflow.

Thanks in advance

**Comment by shrimank** [comment]
Few More details:
I have followed below steps to check the priority testing:
1.Registered Task
2.Registered Workflow(SIMPLE)
3.Created Worker and started polling the registered the tasks.

Then, submitted 5 curl request to start the workflow with different priority(0-99) (used endpoint which accepts priority in query param),.
But the worker is polling the task & getting in the order of submission.

Let me know if I am doing anything wrong.

**Comment by neokyle1** [comment]
Also curious about this. I was looking at the dyno-queue code for this and it seems that priority would only take effect if the entries were on the exact same millisecond. Is that correct? Reference Code:

https://github.com/Netflix/dyno-queues/blob/2fb9f8b9886396025eecd827066bcec9afa946a3/dyno-queues-redis/src/main/java/com/netflix/dyno/queues/redis/RedisDynoQueue.java#L158

**Comment by shrimank** [comment]
Thanks you, I have delegated this request to dynoQueue team.
