### ISSUE TITLE
Pass workflow instance ID as a param for HTTP task

### ISSUE THREAD

**Issue by codetiger** [Netflix/conductor#1228]
How do I pass the workflow instance id as a parameter for a http task. I am not able to refer the instanceID using any variable.

**Comment by kishorebanala** [comment]
You can use `${workflow.workflowId}` to pass workflowId as a parameter. Please refer to https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/ParametersUtils.java#L81 for list of available parameters.
