### ISSUE TITLE
Issues while starting Conductor server with standalone redis and external elasticsearch 

### ISSUE THREAD

**Issue by rituparnopal** [Netflix/conductor#1229]
I am trying to run Conductor on a single redis instance with elasticsearch instance running on my local machine but getting below exception-
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{IDtlvqqXS2muHx1OhtUSgQ}{localhost}{127.0.0.1:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)

Conductor configuration
db=redis
workflow.dynomite.cluster.hosts=localhost:6379:us-east-1b
EC2_AVAILABILTY_ZONE=us-east-1b
EC2_REGION=us-east-1
workflow.dynomite.cluster.name=conductor
workflow.dynomite.connection.maxConnsPerHost=31
workflow.namespace.prefix=conductor
workflow.namespace.queue.prefix=conductor_queues
queues.dynomite.threads=10
queues.dynomite.nonQuorum.port=6379
workflow.elasticsearch.instanceType=external
workflow.elasticsearch.url=localhost:9300
workflow.elasticsearch.index.name=conductor
loadSample=false

Elasticsearch configuration-
cluster.name: conductor
node.name: node-1
path.data: /data
path.logs: /logs
http.port: 9200

**Comment by apanicker-nflx** [comment]
Looks like a connection error to your local elasticsearch instance. Please ensure that your elasticsearch is up and discoverable.

**Comment by rituparnopal** [comment]
My elasticsearch was up and discoverable. Hence I posted here. However found out that issue is with version 7.2.0. The Netty jar used by Conductor to connect to ElasticSearch is supported upto 6.8.0
