### ISSUE TITLE
Output from Dynamic Fork task

### ISSUE THREAD

**Issue by clari-akhilesh** [Netflix/conductor#123]
I have a workflow where a Dynamic Fork task is firing multiple sub-workflows. My question is how do I collect the output from all the sub-workflows?

**Comment by v1r3n** [comment]
Output of the sub workflows are collected in the join task.  It will be a map, with key being the reference name of the sub workflow task and value being output from the subworkflow.

To define outputs for workflows, see: https://netflix.github.io/conductor/metadata/#workflow-definition
