### ISSUE TITLE
Issue : Rerun workflow from a specific task fails (on multiple calls from different tasks) if worklow is not in Redis

### ISSUE THREAD

**Issue by renuka-raju** [Netflix/conductor#1231]
When a workflow not in Redis is being rerun(from a specific task), when the workflow is pulled from ES back into Redis, its tasks are not updated. So, only the task from which I am trying to run and the ones after that are being added to the workflow. For eg, if there are tasks T1, T2, T3 in a workflow, rerun from T2 only adds T2&T3 back to the workflow. Now, when I try to rerun again from T1, it fails saying T1 is not available. I think this is handled in 'retry', by updating the tasks relationship. Should the same be added in rerun workflows as well?

**Comment by kishorebanala** [comment]
@renuka-raju Correct. Only task being rerun is added back to primary store from ES. The tasks before should be added back to primary store, if archived. I'll mark this as a bug. Thanks.

**Comment by renuka-raju** [comment]
Thanks for your response. Submitted a PR for this.

**Comment by apanicker-nflx** [comment]
Thanks for the PR. We will merge this soon.
