### ISSUE TITLE
gulp watch not working

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [Netflix/conductor#1232]
Hello.

I have been trying to use UI as it was [written in these docs](https://netflix.github.io/conductor/architecture/#start-ui-server). However, it throws me these errors:

    [10:31:10] Requiring external module babel-register
    gulp watch[28196]: ../src/node_contextify.cc:651:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion 
    `args[1]->IsString()' failed.
     1: 0x9afed0 node::Abort() [gulp watch]
     2: 0x9aff57  [gulp watch]
     3: 0x9a84df node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp watch]
     4: 0xb91b53  [gulp watch]
     5: 0xb926a2 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [gulp watch]
     6: 0x1318979  [gulp watch]
    Aborted (core dumped)

Why this is happening? Is there some kind of bug in UI?

I'm using Ubuntu Xenial

**Comment by shrimank** [comment]
> Hello.
> 
> I have been trying to use UI as it was [written in these docs](https://netflix.github.io/conductor/architecture/#start-ui-server). However, it throws me these errors:
> 
> ```
> [10:31:10] Requiring external module babel-register
> gulp watch[28196]: ../src/node_contextify.cc:651:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion 
> `args[1]->IsString()' failed.
>  1: 0x9afed0 node::Abort() [gulp watch]
>  2: 0x9aff57  [gulp watch]
>  3: 0x9a84df node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp watch]
>  4: 0xb91b53  [gulp watch]
>  5: 0xb926a2 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [gulp watch]
>  6: 0x1318979  [gulp watch]
> Aborted (core dumped)
> ```
> 
> Why this is happening? Is there some kind of bug in UI?
> 
> I'm using Ubuntu Xenial
 You need to Install gulp in order to use it
make sure you have `node `and `npm `installed
execute '` npm install --save gulp`'

then execute `gulp watch` command to start the ui

**Comment by SuperMasterBlasterLaser** [comment]
@shrimank 

I have installed as you instructed nad now I have this error:

fs.js:27
const { Math, Object } = primordials;
                         ^

    ReferenceError: primordials is not defined
        at fs.js:27:26
        at req_ (/home/vagrant/conductor/ui/node_modules/natives/index.js:143:24)
        at Object.req [as require] (/home/vagrant/conductor/ui/node_modules/natives/index.js:55:10)
        at Object.<anonymous> (/home/vagrant/conductor/ui/node_modules/vinyl- 
    fs/node_modules/graceful-fs/fs.js:1:37)
        at Module._compile (internal/modules/cjs/loader.js:777:30)
        at Module._extensions..js (internal/modules/cjs/loader.js:788:10)
        at Object.require.extensions.<computed> [as .js] 
    (/home/vagrant/conductor/ui/node_modules/babel-register/lib/node.js:152:7)
        at Module.load (internal/modules/cjs/loader.js:643:32)
        at Function.Module._load (internal/modules/cjs/loader.js:556:12)
        at Module.require (internal/modules/cjs/loader.js:683:19)


I think there is some errors in UI code itself.

**Comment by mstier-nflx** [comment]
Looks like this is a bug with Node 12 and Gulp 3+.  [stackoverflow](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node)  I will take a look.  Currently the work around appears to be using node 10.

**Comment by SuperMasterBlasterLaser** [comment]
Looks like you are right. I have just switched to docker

**Comment by apanicker-nflx** [comment]
Closing since the issue seems to be addressed. Please re-open if you are facing problems.

**Comment by jwulf** [comment]
The solution to this is to use a pre-12 version of Node (like 9.9.0) and do `npm rebuild`

**Comment by yanghaogn** [comment]
> The solution to this is to use a pre-12 version of Node (like 9.9.0) and do `npm rebuild`

but it says "To run it you need to have [Node](https://nodejs.org/) 14 (or greater) and [Yarn](https://yarnpkg.com/) installed."

https://netflix.github.io/conductor/architecture/

**Comment by apanicker-nflx** [comment]
@yanghaogn The original issue applies to v2.x of conductor which used gulp. 
The newer versions (v3.3.+) does not use gulp and the documentation has been updated to reflect that.
