### ISSUE TITLE
Add persistence support for Dynamo. 

### ISSUE THREAD

**Issue by naveenchlsn** [Netflix/conductor#1236]
Hi,

We require using dynamo DB as the backend for our conductor instance.

I see dynamo backend support is not there, could you please let me know if this would be a useful addition to the conductor? 

@kishorebanala @apanicker-nflx @mudit3774 @cyzhao 

Thanks

**Comment by apanicker-nflx** [comment]
Hi @naveenchlsn , This would definitely be a useful addition to the project. Since the persistence layer is pluggable, this can be added without impacting other components. Please submit a proposal with implementation details and schema designs.

**Comment by naveenchlsn** [comment]
Thanks, @apanicker-nflx . I am going through the Cassandra execution Dao implementation for understanding the design of executiondao in No SQL databases. 

I can see that some methods in the Dao like exceedsRateLimitPerFrequency, exceedsInProgressLimit are not implemented and these are required for executing system tasks.  

How are we running system tasks when we are using CassandraExecutionDAO ?

**Comment by naveenchlsn** [comment]
The `WorkflowExecutor` class is binded to single `ExecutionDAO` at compile time from what I can see. 

Can you please let me know how we are changing the binding to use `RedisExecutionDAO` for few methods and `CassandraExecutionDAO` for few methods?

**Comment by apanicker-nflx** [comment]
Since the execution DAO is pluggable, we configure an additional module which implements the `ExecutionDAO` interface and delegates the underlying methods to Cassandra and Dynomite depending on the usage. Since Dynomite cluster is already being used to serve `MetadataDAO` (for now) and `QueueDAO`, this does not impose any additional infrastructure costs.
