### ISSUE TITLE
why do i have to specify AWS rack in the config?

### ISSUE THREAD

**Issue by 123Neil123** [Netflix/conductor#1239]
i don't use AWS.
Conductor doesn't start if i don't use "us-east-1b" in the config file
If running locally:

workflow.dynomite.cluster.hosts=localhost:6379:conductor
should work, but doesn't.

i need something similar to:
"workflow.dynomite.cluster.hosts=localhost:6379:us-east-1b:conductor"

is this expected?

**Comment by kishorebanala** [comment]
Hey @smukil @rsrinivasanNetflix, Is there is any requirement from dyno-queues to provide the availability zone? If not, can we remove them to allow non-aws users?

https://github.com/Netflix/conductor/blob/a7a6e32900b7c5cf78b861a144d3e663b9be11c3/redis-persistence/src/main/java/com/netflix/conductor/dyno/DynoShardSupplierProvider.java#L24
https://github.com/Netflix/conductor/search?q=getAvailabilityZone%28%29&unscoped_q=getAvailabilityZone%28%29
