### ISSUE TITLE
Break indexDAO to publisherDAO and indexDAO

### ISSUE THREAD

**Issue by manan164** [Netflix/conductor#1243]
Hi all,
Currently for high throughput scenario we are facing issue while indexing to ElasticSearchDAO. 
We are dropping the message so we are not able to search in conductor UI.
I was thinking to break it into publisherDAO and consumerDAO. We can use kafka to publish to any kafka topic and indexDAO which will consume from kafka topic and index to indexDAO i.e. ElasticSearch.

Let me know your thoughts on this
@apanicker-nflx @kishorebanala @mudit3774 @cyzhao

**Comment by manan164** [comment]
Another approach I tried was to send bulk request while indexing. As of now we bulk only task execution logs but we can bulk indexing task workflow and messages.

**Comment by apanicker-nflx** [comment]
@manan164 I would suggest keeping the indexDAO as is but you can customize the implementation that is being used underneath to tailor it to your needs.
In your implementation, you can choose to break up the producer actions to write to an intermediate kafka layer which eventually sinks to an ES index and the consumer actions to directly read from ES. Also, you can choose to do bulk indexing in this approach.

This way the provided implementation can stay generic for wider usage and do feel free to submit your implementation as a contribution in a separate module, since this can be added as a niche optimization that other users can choose to adopt.

**Comment by manan164** [comment]
Hi, @apanicker-nflx I am working on this approach. 
One potential issue I am facing is since the consumer has to know about indexDAO to index into ES and producer will override indexDAO method to publish to Kafka. 
1) Add a set of (sync and async) methods in indexDAO which will be eventually called by consumer service. We have to add a method because the producer will call the overridden method so ExecutionDAOFacade need not be changed.
2) Write completely another service for this. Which will not be in scope with the conductor.

**Comment by apanicker-nflx** [comment]
Let me clarify what I was proposing earlier: 
> In your implementation, you can choose to break up the producer actions to write to an intermediate kafka layer which eventually sinks to an ES index

This could be implemented in a standalone implementation of the `IndexDAO` such that all the write operations (indexWorkflow, indexTask, updateWorkflow, removeWorkflow, indexEventExecution, etc) are published to a Kafka topic. The Kafka consumer here, does not need to be aware of the indexDAO implementation, rather can read messages from the Kafka topic and index to ES. The caveat here is that the message published to the topic needs to have details about the type of action (CREATE,UPDATE,DELETE), the document type and the index name. 

>and the consumer actions to directly read from ES.

I apologize for this confusing statement. By "consumer", I meant that the read operations (getWorkflow, getEventExecution, etc) can be implemented in this IndexDAO implementation to make GetRequest directly to ES and need not go through an intermediate layer.

**Comment by manan164** [comment]
Hi, @apanicker-nflx  I saw the PR [async Indexing](https://github.com/Netflix/conductor/pull/1333/files). We are using this only in production.
 I will raise the PR with the changes. Then things will fall into place.

**Comment by manan164** [comment]
Hi @apanicker-nflx Create a PR [kafka-persistance](https://github.com/Netflix/conductor/pull/1337) with these changes.

**Comment by manan164** [comment]
One approach I can think of is While doing asyncIndex will publish to Kafka and while consuming from Kafka will call sync methods. so that we will avoid this type of hack.

**Comment by manheiba** [comment]
I think it's good to add Kafka middle tier, but we need to make sure about the producer order and consumer orderly of taskid and workflowid. To prevent the lastest update from being overwritten by previous updates.

**Comment by apanicker-nflx** [comment]
As @manan164 mentioned [here](https://github.com/Netflix/conductor/pull/1338#issuecomment-537818723), we feel that the best way to achieve this in the current setup is by using a separate consumer service outside of Conductor to perform the indexing from the Kafka topic.
