### ISSUE TITLE
workflow_running, task_in_progress Metrics Not Getting Published

### ISSUE THREAD

**Issue by indiv0** [Netflix/conductor#1245]
Hello!

First of all, thank you all for your excellent library and contributions to open source.

I currently have conductor setup to send metrics to atlas.
Some metrics (e.g., `workflow_execution`, `task_queue_wait`, `task_execution`) are getting collected but others are not (e.g., `workflow_running`, `task_in_progress`).

In particular, it looks as though none of the metrics that are supposed to be collected by the [WorkflowMonitor](https://github.com/Netflix/conductor/blob/v2.14.0/core/src/main/java/com/netflix/conductor/service/WorkflowMonitor.java) are being collected.

I'm unfamiliar with guice, but I'm getting the feeling that the class isn't getting initialized. How is the `WorkflowMonitor::init` method supposed to be called? Should I be initializing the `WorkflowMonitor` in my `AbstractModule`-extending class somehow?

I'm running conductor `v2.14.0`, built from source.

**Comment by apanicker-nflx** [comment]
@indiv0 Thank you for the kind words.

Your findings are correct. In your AbstractModule class, you will need to initialize the WorkflowMonitor class like so:
```java
bind(WorkflowSweeper.class).asEagerSingleton();
```
This should initialize the monitors correctly during startup and publish these metrics to Atlas.

**Comment by indiv0** [comment]
Yep, that did it! Thank you.
