### ISSUE TITLE
Wiring Tasks in Dynamic Workflow

### ISSUE THREAD

**Issue by aharonamir** [Netflix/conductor#1248]
Hi, I am trying to run 2 tasks in a dynamic workflow and wire the first task output to the second input:
 {
	"name": "testCoder",
	"workflowDef": {
		"ownerApp": "scp",
		"createdBy": "scp",
		"name": "workflow_chicago_31957dc0_bc35_11e9_83fd_e9eef0ec962a",
		"description": "test coder and sms",
		"version": 2,
		"schemaVersion": 2,
		"tasks": [{
			"name": "geo",
			"description": "",
			"taskReferenceName": "**geo**",
			"taskDefinition": {
				"timeoutPolicy": "TIME_OUT_WF",
				"retryDelaySeconds": 0,
				"retryCount": 0,
				"retryLogic": "FIXED",
				"responseTimeoutSeconds": 3000,
				"timeoutSeconds": 3600
			},
			"type": "HTTP",
			"inputParameters": {
				"http_request": {
					"headers": {},
					"method": "GET",
					"readTimeOut": "3600",
					"content-Type": "application/json",
					"connectionTimeOut": "3600",
					"uri": "https://api.mapbox.com/geocoding/v5/mapbox.places/${workflow.input.lon},${workflow.input.lat}.json?access_token=cmNlNm9kcm5jIn0.OfEmboQMPT8ZU27UOqxyjA",
					"accept": "application/json"
				}
			}
		}, {
			"name": "sms",
			"description": "",
			"taskReferenceName": "sms",
			"taskDefinition": {
				"timeoutPolicy": "TIME_OUT_WF",
				"retryDelaySeconds": 0,
				"retryCount": 0,
				"retryLogic": "FIXED",
				"responseTimeoutSeconds": 3000,
				"timeoutSeconds": 3600
			},
			"type": "HTTP",
			"inputParameters": {
				"http_request": {
					"headers": {},
					"method": "POST",
					"readTimeOut": "3600",
					"content-Type": "application/json",
					"body": {
						"from": "+15592585089",
						"to": "${workflow.input.to}",
						"message": "${workflow.input.message} in the Area of: ${**geo.output.type**} "
					},
					"connectionTimeOut": "3600",
					"uri": "http://mde2:50041/mde/service/api/v2/anycity/messaging/sendSMS",
					"accept": "application/json"
				}
			}
		}],
		"outputParameters": {}
	},
	"input": {
		"to": "+972545596165",
		"message": "Outage",
		"id": "chicago/alert/f7a0ad80-bc32-11e9-a083-0242ac120012",
		"triggerId": "chicago/alertTrigger/eae9fa60-bc32-11e9-a083-0242ac120012",
		"status": "open",
		"label": "outage",
		"tenant": "chicago",
		"created": 1565526270040,
		"updated": null,
		"lat": 41.869872838485804,
		"lon": -87.63322075122863,
		"metaData": {...}
	}
}
While the http requests are carried out, the output of the first task (geo.output.type) does not pass to the second task. 
I am running an in-memory docker of conductor.
What can be the issue here?
I can add the logs if requested, altough there is no error message.
Amir.

**Comment by apanicker-nflx** [comment]
@aharonamir I see that in your definition, the body is wired so `"message": "${workflow.input.message} in the Area of: ${geo.output.type} "`. Currently, this type of string substitution is not supported. If you at the [ParametersUtils](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/ParametersUtils.java#L196) class, you will see the implementation. However, if your body were defined like so:
```json
{
  "from": "+15592585089",
  "to": "${workflow.input.to}",
  "message": "${workflow.input.message}",
  "area": "${geo.output.type} "
}
```
this would perform the substitutions correctly.

If you need your body to be in the format in your example, you can achieve this by adding a LAMBDA task before this task which performs the string concatenation.
