### ISSUE TITLE
How do I add vipAddress in httpTask for Netflix Conductor?

### ISSUE THREAD

**Issue by Prajsp** [Netflix/conductor#1253]
I have the microService registered on eureka discovery service with service registered under hostname:service_name: port. How do I add it as VipAddress for a http_task in my conductor service?

**Comment by kishorebanala** [comment]
@Prajsp You can use `vipAddress` in `http_request`, and then `uri` to provide the path. Checkout docs for http task for an example: https://netflix.github.io/conductor/configuration/systask/#http

**Comment by krishnaputhran** [comment]
Can anyone provide a simple example? Document is not very explanatory. I appreciate any help on this. For eg: my microService is registered in eurekha, by the name "helloService". Now how I form my HTTP request to from HTTP system task?
