### ISSUE TITLE
Workflow metrics

### ISSUE THREAD

**Issue by clari-akhilesh** [Netflix/conductor#126]
In the documentation, you mentioned that server and worker metrics are collected using spectator. I'm not familiar with spectator. Can you tell me how I can expose these metrics either in a UI or a log file?

**Comment by v1r3n** [comment]
You can find more details about spectator here:

https://github.com/Netflix/spectator
http://netflix.github.io/spectator/en/latest/

By defaults all the metrics are exposed as JMX MBeans.  
<img width="889" alt="conductor_metrics" src="https://cloud.githubusercontent.com/assets/2246128/24059638/0b801ea0-0b0d-11e7-8781-a045870c81df.png">

**Comment by v1r3n** [comment]
closing this - please re-open if required.

**Comment by clari-akhilesh** [comment]
Not metrics are visible in the console. Should I do anything to enable them?
![screen shot 2017-04-14 at 6 14 35 pm](https://cloud.githubusercontent.com/assets/25108672/25059599/69750696-213e-11e7-88da-7de623d629da.png)
![screen shot 2017-04-14 at 6 14 48 pm](https://cloud.githubusercontent.com/assets/25108672/25059600/69759372-213e-11e7-9405-af64b9a25fd3.png)
