### ISSUE TITLE
Log4j  1 vs 2 mixed up when running server

### ISSUE THREAD

**Issue by s50600822** [Netflix/conductor#1271]
```java -jar ./server/build/libs/conductor-server-2.15.0-SNAPSHOT-all.jar
```
shows
<img width="1423" alt="Screen Shot 2019-08-21 at 1 53 56 pm" src="https://user-images.githubusercontent.com/5586453/63433871-5815a580-c467-11e9-81bc-622aeb3946ae.png">

dependency report seems to indicate we actually want log4j2, check output of ```gradle dependencyReport```. See https://scans.gradle.com/s/ss35tnzbn3i3u/dependencies?dependencies=log4j&expandAll

Run time managed bean confirm log4j2 is being loaded:
<img width="986" alt="Screen Shot 2019-08-21 at 8 06 19 pm" src="https://user-images.githubusercontent.com/5586453/63434020-957a3300-c467-11e9-8713-0ae0e1942758.png">

Given the benefit of log4j 2.x over 1.x we should fix this inconsistency.
https://github.com/Netflix/conductor/pull/1270

So that we can be free of limitation like
https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/PropertyConfigurator.html
The PropertyConfigurator does not handle the advanced configuration features supported by the DOMConfigurator such as support custom ErrorHandlers, nested appenders such as the AsyncAppender, etc.

And get all the cool stuff that was built into log4j2 like Async Appender
https://logging.apache.org/log4j/2.x/manual/async.html
![async-vs-sync-throughput](https://user-images.githubusercontent.com/5586453/64099754-68097f80-cdad-11e9-8711-d81f4e16f2af.png)

Lazy input evaluation:
https://jira.qos.ch/browse/SLF4J-371
https://issues.apache.org/jira/browse/LOG4J2-599
And future proof our configuration for a while.

**Comment by mdepak** [comment]
@s50600822 did you find a way to get over this problem with log4j library inconsistency?

**Comment by s50600822** [comment]
@mdepak if you have a fork do this https://github.com/Netflix/conductor/pull/1270
