### ISSUE TITLE
Ubuntu 18.04 docker-compose up gradle build failure

### ISSUE THREAD

**Issue by aresares** [Netflix/conductor#1276]
Im having troubles on running conductor on docker under linux

root@server:/home/netflixConductor/conductor/docker# docker-compose up
Building conductor-server
Step 1/16 : FROM openjdk:8-jdk AS builder
 ---> b84359d0cbce
Step 2/16 : MAINTAINER Netflix OSS <conductor@netflix.com>
 ---> Running in b4d3a452fffb
Removing intermediate container b4d3a452fffb
 ---> fa9345e8b3b5
Step 3/16 : COPY . /conductor
 ---> 6f7ffe923e95
Step 4/16 : WORKDIR /conductor
 ---> Running in db2d727a928b
Removing intermediate container db2d727a928b
 ---> 151856088ff1
Step 5/16 : RUN ./gradlew build -x test
 ---> Running in c72956c120ee
Downloading file:/conductor/gradle/wrapper/./dists/gradle-4.8.1-all.zip
.........................................................................................................

Welcome to Gradle 4.8.1!

Here are the highlights of this release:
 - Dependency locking
 - Maven Publish and Ivy Publish plugins improved and marked stable
 - Incremental annotation processing enhancements
 - APIs to configure tasks at creation time

For more details see https://docs.gradle.org/4.8.1/release-notes.html

**Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/conductor/build.gradle' line: 16

* What went wrong:
Plugin [id: 'nebula.netflixoss', version: '5.1.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'nebula.netflixoss:nebula.netflixoss.gradle.plugin:5.1.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s**
**_ERROR: Service 'conductor-server' failed to build: The command '/bin/sh -c ./gradlew build -x test' returned a non-zero code: 1_**

**Comment by josemonteiro** [comment]
Hello, I'm getting a similar error during the Gradle build:

```
...
Step 5/16 : RUN ./gradlew build -x test
 ---> Running in 84b87b43dc05
Downloading https://services.gradle.org/distributions/gradle-4.8.1-all.zip
.........................................................................................................

Welcome to Gradle 4.8.1!

Here are the highlights of this release:
 - Dependency locking
 - Maven Publish and Ivy Publish plugins improved and marked stable
 - Incremental annotation processing enhancements
 - APIs to configure tasks at creation time

For more details see https://docs.gradle.org/4.8.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
Download https://plugins.gradle.org/m2/nebula/netflixoss/nebula.netflixoss.gradle.plugin/5.1.1/
...(REMOVED)...
Download https://jcenter.bintray.com/com/netflix/nebula/nebula-bintray-plugin/3.5.5/nebula-bintray-plugin-3.5.5.jar

FAILURE: Build failed with an exception.

* Where:
Build file '/conductor/build.gradle' line: 12

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '5.1.1']
> Failed to apply plugin [class 'nebula.plugin.bintray.NebulaBintrayPublishingPlugin']
   > Walk failure.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 40s
ERROR: Service 'conductor-server' failed to build: The command '/bin/sh -c ./gradlew build -x test' returned a non-zero code: 1
```

**Comment by josemonteiro** [comment]
Nevermind, I was using running `docker-compose build` from a different place and using the git URI as build context, and for some reason this doesn't work. Building locally in this repo works for me.

**Comment by aresares** [comment]
I build always in the same way, on windows 10 it works , on ubuntu server no, I get the above error
