### ISSUE TITLE
Netflix conductor-query - asynchronous behavior.

### ISSUE THREAD

**Issue by amoolya19** [Netflix/conductor#128]
Hi, i have kind of requirement, please tell whether i can do with this. consider in a workflow there are 3 tasks, t1,t2,t3. t1 gather data n inputs to t2 and t2 calls external system. now i want workflow should not halt here till the repnse comes for t2, should continue with t3. everywhere its mentioned its aschronous but is this kind of asyncronous allowed?

**Comment by v1r3n** [comment]
@amoolya19 Conductor supports fork/join.  Forked tasks are executed in parallel and join can wait for these forks to complete after which the next set of tasks will continue.  Look at the kitchensink example in the documentation and documentation on fork/join.  

Based on what you described, it seems like you need a fork where one path executed t1->t2 and another path executes t3.  and a join task that waits for t2 and t3 and continues further or completes the workflow.  With this setup, t1 and t3 will run get scheduled in parallel, but t2 will only start after t1 completes.

**Comment by amoolya19** [comment]
@v1r3n consider t4 joins the t2 and t3. this case, t4 waits till t2 gets completed. the workflow will not be progressed i assume.

**Comment by amoolya19** [comment]
@v1r3n ,

what i meant to ask is, currently the http task works syncronously, sends req and gets response and after that proceeds with next task in the workflow.I am not able to provide any real time scenarios but i dont want to use fork.  Is there anything like AMQP support or any other with such type for async behavior. 
our business scenario is handle 600 transactions per second and each shouldnt take more than 6s.

**Comment by v1r3n** [comment]
@amoolya19 the current version runs HTTP task in an asynchronous fashion.  
As far as AMQP support, is that for running HTTP task in async?  If so - it is probably not required as Conductor has internal queues that are used for doing that.

**Comment by rkbalgi** [comment]
@amoolya19 - We have a similar situation where we are calling multiple http post tasks as part of a single workflow at a high rate (say about 1000 transactions/workflows per second). I would be interested to know if were you able to test conductor under that load and if yes, what were your observations?
