### ISSUE TITLE
Configuration issue with HA dynomite deployment.

### ISSUE THREAD

**Issue by msf** [Netflix/conductor#1287]
hi there, I have a 3-node setup of a dynomite cluster (sinle datacenter, 1 node per AZ/rack, read and write consistencty set to DC_SAFE_QUORUM) and for the life of me can't get conductor to work correctly w/ this setup.
I believe the dynomite deployment is correct, it passes some various tests I've done (using redis-cli and redis-benchmark against the individual nodes)

I've confirmed that each dynomite instance holds the same data and is the single owner of the whole rash-ring in its respective rack (3 racks: eu-west-1a, eu-west-1b, eu-west-1c)

When I launch workflows, they get stuck on some task SCHEDULED state, the specific task to get stuck varies per workflow instance.

I currently have a single conductor server and all task workers connecting to that server.

I can share the conductor config.properties or even the dynomite servers yaml config if needed.

it runs correctly if I use only a single node of the 3-node dynomite setup, but not if I put the 3-nodes

Here is the exact configuration (server.properties) change that makes conductor stop working:
```
 #format is host:port:rack separated by semicolon  
-workflow.dynomite.cluster.hosts=10.0.16.61:8102:eu-west-1a;10.0.52.159:8102:eu-west-1b;10.0.74.57:8102:eu-west-1c
+workflow.dynomite.cluster.hosts=10.0.74.57:8102:eu-west-1c
```

my issue might be related to this issue: Netflix/conductor#1246 -- however in my case, I only have a single instance per rack, so, all dynomite+redis instances should be complete copies of each other, so I don't understand why it doesn't.

**Comment by apanicker-nflx** [comment]
@msf As mentioned [here](https://github.com/Netflix/conductor/issues/1246#issuecomment-525554811), if your dynomite configuration is such that you have a 3-node setup across 3 AZs, then you would need a 3-node Conductor cluster deployed across the 3 AZs.

**Comment by kimabd** [comment]
@apanicker-nflx Could you please share dynomite and conductor's working configs for this case, one conductor and dynomite node per AZ. I can't bring it up

**Comment by apanicker-nflx** [comment]
@kimabd In you case, it seems like your workers are polling on only one Conductor node. Can you ensure that your deployment is fronted by a load-balancer so that your workers poll for tasks across all conductor instances?
