### ISSUE TITLE
Docker Compose +  Windows = Error

### ISSUE THREAD

**Issue by haigopi** [Netflix/conductor#1288]
F:\conductor\docker>docker-compose up
Building conductor-server
Step 1/16 : FROM openjdk:8-jdk AS builder
 ---> 08ded5f856cc
Step 2/16 : MAINTAINER Netflix OSS <conductor@netflix.com>
 ---> Using cache
 ---> 6e56c49b3752
Step 3/16 : COPY . /conductor
 ---> Using cache
 ---> b4c5788f3fd9
Step 4/16 : WORKDIR /conductor
 ---> Using cache
 ---> 402538e9818c
Step 5/16 : RUN ./gradlew build -x test
 ---> Running in 789324ff9318
/usr/bin/env: ‘sh\r’: No such file or directory
ERROR: Service 'conductor-server' failed to build: The command '/bin/sh -c ./gradlew build -x test' returned a non-zero code: 127

**Comment by apanicker-nflx** [comment]
You're right, I misread the message.

**Comment by courosh12** [comment]
I had the same issue. In my case its was because of line endings. u need linux line endings and not windows. Try using dos2unix in git bash. https://stackoverflow.com/questions/11929461/how-can-i-run-dos2unix-on-an-entire-directory

**Comment by TwoUnderscorez** [comment]
Issuing the `git clone` command from `WSL` and not `Git Bash` also works.
