### ISSUE TITLE
WorkflowTask deserialisation initialise empty lists

### ISSUE THREAD

**Issue by Stephane90** [Netflix/conductor#1290]
Hello,
I noticed when deserialising [WorkflowTask](https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowTask.java) that all collections are initialised as empty collections even when the field in the json is absent. This is due to the fact that the empty constructor initialises them. This is present in all collections in the model.
It makes it impossible to differentiate the case when the json field is actually an empty array and the case when it is absent.

Do you know if there would be any impact if we remove these initialisations? Or do you have any other solution that could help for this issue?

**Comment by kishorebanala** [comment]
@Stephane90 Do you have an example for when it would be useful to have null fields over empty fields? Having empty collections helps avoid null checks and we can infer there are no values if the list is empty anyways.
