### ISSUE TITLE
What is "taskDefName"?

### ISSUE THREAD

**Issue by smullins3000** [Netflix/conductor#1291]
The attribute taskDefName is returned in task polling, and it appears to always and only be set to the taskType value (from Task.name). Attempts to set it in the workflow definition fail as the value is not persisted.

Is this attribute used for anything?

**Comment by apanicker-nflx** [comment]
`taskDefName` is the name of the task definition that is registered for this particular task. It is set to `taskType` if a definition does not exist, which can be the case for system tasks.
