### ISSUE TITLE
NullException on task input upload to external storage (not S3)

### ISSUE THREAD

**Issue by MikeTangoEcho** [Netflix/conductor#1292]
When payload size > `conductor.workflow.input.payload.threshold.kb` and you don't use S3 External Storage, the DummyPayloadStorage's function getLocation returns null and trigger a NullException.

https://github.com/Netflix/conductor/blob/02feca03104711332d160283a77b454ac5e5df1a/core/src/main/java/com/netflix/conductor/core/utils/DummyPayloadStorage.java#L30-L32

https://github.com/Netflix/conductor/blob/02feca03104711332d160283a77b454ac5e5df1a/core/src/main/java/com/netflix/conductor/core/utils/ExternalPayloadStorageUtils.java#L160-L164

Before all, I would like your feedback on theses following solutions, and which would be the best to implement:
- Trigger a FileNotFoundException in DummyPayloadStorage:getLocation instead of returning null and receive a comprehensive error message `"Unable to upload payload to external storage for workflow: {}"`
- Skip ExternalPayloadStorageUtils:verifyAndUpload execution when the storage is Dummy and wait until the datastore explodes
- nothing and add another entry in a troubleshoot section ?
- something else

**Comment by apanicker-nflx** [comment]
@MikeTangoEcho Thanks for flagging this issue. 

> Skip ExternalPayloadStorageUtils:verifyAndUpload execution when the storage is Dummy and wait until the datastore explodes

This option seems to be best suited for backward compatibility. 
However, you could also introduce a boolean flag which is configuration-driven to enable/disable the use of external payload storage. The method `ExternalPayloadStorageUtils:verifyAndUpload` could be skipped when this is disabled (default behavior).

Please let me know your thoughts and feel free to contribute a fix for this issue.

**Comment by MikeTangoEcho** [comment]
From my point of view:
- Introducing a boolean flag to switch on/off the feature would undermine the need of a Dummy implementation of an external storage, thus better removing it to avoid confusion.
- Modifying the behaviour of `verifyAndUpload` is more than a quick hack for backward compat than a fix, it would be simpler to remove the dummy external storage and prevent the instanciation of `ExternalPayloadStorageUtils` in `WorkflowExecutor` and `DeciderService` but doing so would imply lot of refactoring.

@apanicker-nflx I don't have a lof of experience on Guice nor overlooked all the code, but do you think it would be easier to add a `DummyExternalPayloadStorageUtils` and add its binding in

https://github.com/Netflix/conductor/blob/master/server/src/main/java/com/netflix/conductor/bootstrap/ModulesProvider.java#L123-L128

Or this solution would defeat the purpose of this **"Utils"** class ?

**Comment by apanicker-nflx** [comment]
>Modifying the behaviour of verifyAndUpload is more than a quick hack for backward compat than a fix, it would be simpler to remove the dummy external storage and prevent the instanciation of ExternalPayloadStorageUtils in WorkflowExecutor and DeciderService but doing so would imply lot of refactoring.

Agreed. But as you pointed out, it defeats the purpose of the `Utils` class which is agnostic of the implementation underneath. 

Given your ideas above, I am now leaning towards
> Trigger a FileNotFoundException in DummyPayloadStorage:getLocation instead of returning null

The error message could say that an external payload storage is not configured and the payload size is beyond the configured limits.
