### ISSUE TITLE
KAFKA_PUBLISH stuck in "Scheduled"

### ISSUE THREAD

**Issue by ibivibiv** [Netflix/conductor#1295]
Ok I surrender, I have no idea why this is happening.  I have this task created:

{
        "name": "call_kafka",
        "taskReferenceName": "call_kafka",
        "inputParameters": {
            "kafka_request": {
                "topic": "userTopic",
                "value": "Message to publish",
                "bootStrapServers": "confluent-cp-kafka-headless:9092",
                "headers": {

                },
                "key": "123",
                "keySerializer": "org.apache.kafka.common.serialization.IntegerSerializer"
            }

        },
        "type": "KAFKA_PUBLISH",
        "startDelay": 0,
        "optional": False
    }

and I have it in this workflow:

{
    "name": "testkafka",
    "description": "testkafka",
    "version":2,
    "tasks": [
        {
            "name": "call_kafka",
            "taskReferenceName": "call_kafka",
            "inputParameters": {
                "kafka_request": {
                    "topic": "userTopic",
                    "value": "Message to publish",
                    "bootStrapServers": "confluent-cp-kafka-headless:9092",
                    "headers": {

                    },
                    "key": "123",
                    "keySerializer": "org.apache.kafka.common.serialization.IntegerSerializer"
                }

            }
        }
    ],
    "schemaVersion": 2,
    "restartable": True,
    "workflowStatusListenerEnabled": False
}

No visible errors and it sits in Scheduled. I can ping the Kafka instance and publish manually from the same instance as the conductor server is running on.  I'm guessing since other tasks that behave like this usually have a bad config of some kind but I lifted this one mostly from the docs online already.  I'm guessing something wrong/missing in the docs?  Anybody have any clues?

**Comment by manan164** [comment]
@naveenchlsn  See if you can help.

**Comment by naveenchlsn** [comment]
@ibivibiv  Yes. you are right. The documentation is missing something. We have to specify the task type for the conductor to recognize this as a Kafka task. 


Please try with the following definition. Sorry for the trouble, I will raise a PR to update the docs. 

```
{
  "name": "call_kafka",
  "taskReferenceName": "call_kafka",
  "inputParameters": {
    "kafka_request": {
      "topic": "userTopic",
      "value": "Message to publish",
      "bootStrapServers": "localhost:9092",
      "headers": {

      },
      "key": "123",
      "keySerializer": "org.apache.kafka.common.serialization.IntegerSerializer"
    }
  },
  "type": "KAFKA_PUBLISH"
}
```

**Comment by ibivibiv** [comment]
Good catch!  I had the type on the task definition but not in the workflow!  Yes the documentation only had the input parameters so I had to guess at it.  Its working now.  Thank you guys, you're the best!
