### ISSUE TITLE
Latest master merge - cannot find dyno-core 1.6.5-rc.3

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1297]
The latest merge to master has redis-persistence using the 2.0.0-rc6 version of dyno-queues-redis. This depends on dyno-core-1.6.5-rc.3. That version cannot be found in Maven. Is there something I need to do to make the build work?

**Comment by apanicker-nflx** [comment]
The dependencies seem to be available here - https://bintray.com/netflixoss/oss-candidate/dyno.

**Comment by rickfish** [comment]
Thank you
