### ISSUE TITLE
Best practice for elastic search setup in conductor 

### ISSUE THREAD

**Issue by naveenchlsn** [Netflix/conductor#1298]
Hi, 

1) What kind of elastic search cluster is ideal for the traffic ingested by the conductor. Currently, we are running 100k workflows per minute at peak and a  5 node m5.x large cluster is not able to keep up.  Is there any tuning in the index configuration we can make to make the ingestion faster?  

2) From the [blog post, ](https://medium.com/netflix-techblog/evolution-of-netflix-conductor-16600be36bca) you are planning on making the elastic search optional. In that setup, are you planning on keeping the UI functionality fully supported? Because some queries required by the UI need indexing and cannot be served from key-value stores.

**Comment by kishorebanala** [comment]
Hi @naveenchlsn, You can consider making more fields non-indexable. For eg.
```
         "rawJSON": {
            "type": "keyword",
            "index": false,
            "include_in_all": false
          }
```

This might impact UI usage on some fields though. While we haven't done ES cluster tuning ourselves, there are some good resources such as this: https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-search-speed.html.

For #2, there are some tradeoffs, but I'd think UI should be customizable to disable some non-supported features like searching for workflows with free text.
