### ISSUE TITLE
How to run & configure Conductor binaries from Maven Central

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#13]
After successfully testing the test-harness setup according to the "getting started" guide, I wanted to try the jars from Maven Central.

However, I cannot really figure out 
- which jar is the "main" jar to run in e.g. Tomcat
- where/how I can configure various settings (e.g. related to Dynomite, connection to ElasticSearch, etc)  
- how to e.g. change the port from the UI and configure its connection to Conductor Backend

I appreciate any help.

**Comment by v1r3n** [comment]
* Conductor publishes all the artifacts as jar files into maven central.  
* You can create a simple web application using Jersey and Guice that should allow you to expose the REST endpoints from ```conductor-jersey``` module.
* The web application can be deployed in any container (tomcat or jetty).  To run it in embedded mode (without a dedicated app server) look at the [Main.java](https://github.com/Netflix/conductor/blob/dev/test-harness/src/test/java/com/netflix/conductor/demo/Main.java) in test-harness.
* Depending upon the servlet container (tomcat, jetty etc.) you can configure the port and HTTP or HTTPS connection.

**Comment by blueelephants** [comment]
Thanks for clarification!

**Comment by blueelephants** [comment]
Thanks again for your comments.

After digging deeper into the test-harness code, I am still having some questions where I would like to ask you for further help.

The test-harness code is very good to quickly try Conductor as everything is mocked/embedded (ElasticSearch, Dyno-Queues, etc.) 

I am now working on two things

(a) Short-term: 
  - Creating a single web app with Conductor Server (and all its embedded components like ElasticSearch, Dyno-Queues, Jetty as in test-harness code ) - but everything packaged in one "uber-jar" ... 
  - and finally putting this uber-jar in a Docker Container to run it with "java jar..."                       

  Is it possible to easily create this uber jar out of the test-harness demo-app?
  Can you give me some help on how to do that?

(b) Medium-term:
  - Create a new web app which uses the pre-built Maven Central jars and and also runs in an embedded Tomcat/Jetty container - everything again finally packaged in one "uber jar" 
  - Additionally: 
    - Remove step-by-step all "mocked/embedded" components - i.e. connect Conductor Server to a standalone ElasticSearch cluster, Dynomite database, etc.
    - having an application.properties/bootstrap.properties file to configure Tomcat/Jetty details (e.g. port, SSL), connection details to ElasticSearch/Dynomite, etc.

  I am struggeling to start to write this web app to use all the available jars. 
  Do you have some more demo code which shows how to use the jars and to expose the REST endpoints from conductor-jersey (unfortunately I am not familiar with Jersey & Guice but with Spring Boot).

  Conc. removing the mocked/embedded components of test-harness ... can you provide some more information how the code currently works? 

  What I can see from Main.java in test-harness is:
 - An embedded Elastic Search Cluster gets created (via EmbeddedElasticSearch.java) at 127.0.0.1:9200 with an index called "conductor" - but where/how is Conductor Server configured on which address/port this embedded ElasticSearch Cluster is running?
 - Dependency injection seems to be done for TestModule.java: `Guice.createInjector(new TestModule(), new JerseyModule())`
   TestModule.java seems to bind the various DAO classes and mocks the embedded Dynomite/Dyno-queues? 
   But how/where are Jersey REST endpoints incorporated (e.g. TaskResource.java, MetadataResource.java, AdminResource.java, etc.) - I can't see how this is done in JerseyModule.java.

Many thanks for some more help & background information.

**Comment by v1r3n** [comment]
It seems like you are looking for a deployable server component.  test-harness does "mock" the components and is meant only for a demo purpose, it is not meant to be deployed to production.

Here are my thoughts:

* Having a server component with required dependencies (maybe published as zip/tarball and an executable like start-conductor.sh) is a good idea and probably a way to go.
* I would embed app server like jetty or netty that is lightweight
* Dynomite and Elasticsearch are configured via [Configuration](https://github.com/Netflix/conductor/blob/dev/core/src/main/java/com/netflix/conductor/core/config/Configuration.java).  An implementation of this class that takes a property file to load the required properties will let someone use existing installation of Dynomite and Elasticsearch along with other properties.
* Create a docker file that includes conductor-server binaries along with Dynomite and Elasticsearch which can be used to bring up a single node instance.

There is already an existing PR for the docker image, and I think we can make it work.

@ jcantosz what do you think?

**Comment by v1r3n** [comment]
I have created https://github.com/Netflix/conductor/issues/29 to track this and will get it addressed in the upcoming release.

**Comment by blueelephants** [comment]
Perfect, many thanks
