### ISSUE TITLE
lambda provides Invalid JSON error

### ISSUE THREAD

**Issue by acho22** [Netflix/conductor#1303]
Hi all,

Hoping someone might see if I'm doing something wrong.  I tested the lambda expression on Nashorn directly & it worked.  But when I run it as a task I get a processing error with the input JSON.

Below is the lambda task:
		{
			"name": "mergeresult",
			"taskReferenceName": "mergeresult",
			"type": "LAMBDA",
			"inputParameters": {
				"offshore": "${joinus.output.shell-offshore.response.body.enrichment[0]}",
				"ticker": "${joinus.output.shell-ticker.response.body}",
				"scriptExpression": "var tic = JSON.parse($.ticker); var off = JSON.parse($.offshore); tic['enrichment'].push(off); JSON.stringify(tic)"
			}
		}

Here is the error:
SyntaxError: Invalid JSON: <json>:1:1 Expected , or } but found d {datasource=lei, legalName=AECOM Limited, ids=[{id=2WKCM9EOCM4UGJU1F243, type=lei_number}], entityStatus=ACTIVE, regStatus=LAPSED, addresses=[{type=legal, address=AECOM House,63-77 Victoria Street,City: St Albans,Country: GB}, {type=HQ, address=AECOM House,63-77 Victoria Street,City: St Albans,Country: GB}], corroborationLevel=FULLY_CORROBORATED, relationships={managing-lou={links={related=https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/managing-lou}}, lei-issuer={links={related=https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/lei-issuer}}, modifications={links={related=https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/modifications}}, direct-parent={links={reporting-exception=https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/direct-parent-reporting-exception}}, ultimate-parent={links={reporting-exception=https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/ultimate-parent-reporting-exception}}}, mergescore=0, enrichment=[{id=10, name=ticker, description=checks if an entity is publicly traded, version=1, attributes=[{is_in_list=false, exchanges=NA}], status={code=200, message=OK, hasError=false}}]} ^ in <eval> at line number 1

I believe the failure occurs with the first JSON.parse($.ticker).

The task input is as such & the JSON is fine.
{
    "datasource": "lei",
    "legalName": "AECOM Limited",
    "ids": [
      {
        "id": "2WKCM9EOCM4UGJU1F243",
        "type": "lei_number"
      }
    ],
    "entityStatus": "ACTIVE",
    "regStatus": "LAPSED",
    "addresses": [
      {
        "type": "legal",
        "address": "AECOM House,63-77 Victoria Street,City: St Albans,Country: GB"
      },
      {
        "type": "HQ",
        "address": "AECOM House,63-77 Victoria Street,City: St Albans,Country: GB"
      }
    ],
    "corroborationLevel": "FULLY_CORROBORATED",
    "relationships": {
      "managing-lou": {
        "links": {
          "related": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/managing-lou"
        }
      },
      "lei-issuer": {
        "links": {
          "related": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/lei-issuer"
        }
      },
      "modifications": {
        "links": {
          "related": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/modifications"
        }
      },
      "direct-parent": {
        "links": {
          "reporting-exception": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/direct-parent-reporting-exception"
        }
      },
      "ultimate-parent": {
        "links": {
          "reporting-exception": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/ultimate-parent-reporting-exception"
        }
      }
    },
    "mergescore": 0,
    "enrichment": [
      {
        "id": "10",
        "name": "ticker",
        "description": "checks if an entity is publicly traded",
        "version": "1",
        "attributes": [
          {
            "is_in_list": false,
            "exchanges": "NA"
          }
        ],
        "status": {
          "code": 200,
          "message": "OK",
          "hasError": false
        }
      }
    ]
  }

**Comment by acho22** [comment]
I played around a bit more & changed my expression to:
JSON.parse(${joinus.output.shell-offshore.response.body.enrichment[0]})

I can see that it removes all the double quotes:
"scriptExpression": "JSON.parse(JSON.stringify({id=1, name=Offshore, description=checks if an entity is included in the lists, version=1, attributes=[{type=panama_papers, is_in_list=false}, {type=paradise_papers, is_in_list=false}, {type=offshore_leaks, is_in_list=false}, {type=bahamas_leaks, is_in_list=false}], status={code=200, message=OK, hasError=false}}))"
}

leading to this error:
"<eval>:1:50 Expected : but found =\nfunction scriptFun(){JSON.parse({id=1, name=Offshore, description=checks if an entity is included in the lists, version=1, attributes=[{type=panama_papers, is_in_list=false}, {type=paradise_papers, is_in_list=false}, {type=offshore_leaks, is_in_list=false}, {type=bahamas_leaks, is_in_list=false}], status={code=200, message=OK, hasError=false}})} scriptFun();\n ^ in <eval> at line number 1 at column number 50"

even though the inputs come in with valid JSON when used in the script expression all the double quotes are removed & then it becomes invalid JSON

**Comment by manan164** [comment]
@acho22 Not sure what is the exact issue. But you can use Java construct inside lambda task scriptExpression. Please look at -:https://docs.oracle.com/javase/8/docs/technotes/guides/scripting/nashorn/api.html. 
If it is removing quotes you can use java json parser.

**Comment by acho22** [comment]
Hi @manan164 , thanks for replying back.  I look at the link, I'm not sure it will help because it seems the value is already modified by Conductor itself & I loose all the double quotes.

I'm actually trying to keep all the double quotes.  This will keep it as a valid JSON string.

**Comment by acho22** [comment]
My guess is that when the variable is evaluated all the double quotes are stripped because the scriptExpression is a string incased in double quotes.  But I would have expected the internal double quotes to be escaped.

**Comment by manan164** [comment]
Hi @acho22 . Since you are getting JSON input why you want to parse it again.
You can use definition
```{
"name": "mergeresult",
"taskReferenceName": "mergeresult",
"type": "LAMBDA",
"inputParameters": {
"offshore": "${joinus.output.shell-offshore.response.body.enrichment[0]}",
"ticker": "${joinus.output.shell-ticker.response.body}",
"scriptExpression": "var tic = $.ticker; var off = $.offshore; tic['enrichment'].push(off);"
}
}```

**Comment by acho22** [comment]
Also noticed it is converting the colons to equal signs too

**Comment by acho22** [comment]
hi @manan164 , because it's just still a JSON string but it needs to be a JSON object.

otherwise, you get this:
{
  "error": "TypeError: tic.enrichment.push is not a function"
}

**Comment by manan164** [comment]
Hi @acho22 I don't see body in the input you have provided. I took empty list body.
and this worked,
```{
  "createdBy": "App",
  "name": "TestWF",
  "description": "TestWF",
  "version": 1,
  "tasks": [
    {
      "name": "mergeresult",
      "taskReferenceName": "mergeresult",
      "type": "LAMBDA",
      "inputParameters": {
      "offshore": "${workflow.input.enrichment[0]}",
      "ticker": "${workflow.input.body}",
      "scriptExpression": "var tic = $.ticker; var off = $.offshore; tic['enrichment'] = off; JSON.stringify(tic); "
      }
      }
  ],
  "schemaVersion": 2,
  "restartable": true,
  "workflowStatusListenerEnabled": false
}``` Can you give exact input and workflow def you are trying.

**Comment by acho22** [comment]
Sure, this is the input coming from the previous join task.

{
  "shell-offshore": {
    "response": {
      "headers": {
        "Transfer-Encoding": [
          "chunked"
        ],
        "Access-Control-Allow-Origin": [
          "*"
        ],
        "Connection": [
          "keep-alive"
        ],
        "Date": [
          "Fri, 06 Sep 2019 15:34:55 GMT"
        ],
        "Content-Type": [
          "application/json"
        ]
      },
      "reasonPhrase": "OK",
      "body": {
        "datasource": "lei",
        "legalName": "AECOM Limited",
        "ids": [
          {
            "id": "2WKCM9EOCM4UGJU1F243",
            "type": "lei_number"
          }
        ],
        "entityStatus": "ACTIVE",
        "regStatus": "LAPSED",
        "addresses": [
          {
            "type": "legal",
            "address": "AECOM House,63-77 Victoria Street,City: St Albans,Country: GB"
          },
          {
            "type": "HQ",
            "address": "AECOM House,63-77 Victoria Street,City: St Albans,Country: GB"
          }
        ],
        "corroborationLevel": "FULLY_CORROBORATED",
        "relationships": {
          "managing-lou": {
            "links": {
              "related": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/managing-lou"
            }
          },
          "lei-issuer": {
            "links": {
              "related": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/lei-issuer"
            }
          },
          "modifications": {
            "links": {
              "related": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/modifications"
            }
          },
          "direct-parent": {
            "links": {
              "reporting-exception": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/direct-parent-reporting-exception"
            }
          },
          "ultimate-parent": {
            "links": {
              "reporting-exception": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/ultimate-parent-reporting-exception"
            }
          }
        },
        "mergescore": 0,
        "enrichment": [
          {
            "id": "1",
            "name": "Offshore",
            "description": "checks if an entity is included in the lists",
            "version": "1",
            "attributes": [
              {
                "type": "panama_papers",
                "is_in_list": false
              },
              {
                "type": "paradise_papers",
                "is_in_list": false
              },
              {
                "type": "offshore_leaks",
                "is_in_list": false
              },
              {
                "type": "bahamas_leaks",
                "is_in_list": false
              }
            ],
            "status": {
              "code": 200,
              "message": "OK",
              "hasError": false
            }
          }
        ]
      },
      "statusCode": 200
    }
  },
  "shell-ticker": {
    "response": {
      "headers": {
        "Transfer-Encoding": [
          "chunked"
        ],
        "Access-Control-Allow-Origin": [
          "*"
        ],
        "Connection": [
          "keep-alive"
        ],
        "Date": [
          "Fri, 06 Sep 2019 15:34:55 GMT"
        ],
        "Content-Type": [
          "application/json"
        ]
      },
      "reasonPhrase": "OK",
      "body": {
        "datasource": "lei",
        "legalName": "AECOM Limited",
        "ids": [
          {
            "id": "2WKCM9EOCM4UGJU1F243",
            "type": "lei_number"
          }
        ],
        "entityStatus": "ACTIVE",
        "regStatus": "LAPSED",
        "addresses": [
          {
            "type": "legal",
            "address": "AECOM House,63-77 Victoria Street,City: St Albans,Country: GB"
          },
          {
            "type": "HQ",
            "address": "AECOM House,63-77 Victoria Street,City: St Albans,Country: GB"
          }
        ],
        "corroborationLevel": "FULLY_CORROBORATED",
        "relationships": {
          "managing-lou": {
            "links": {
              "related": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/managing-lou"
            }
          },
          "lei-issuer": {
            "links": {
              "related": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/lei-issuer"
            }
          },
          "modifications": {
            "links": {
              "related": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/modifications"
            }
          },
          "direct-parent": {
            "links": {
              "reporting-exception": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/direct-parent-reporting-exception"
            }
          },
          "ultimate-parent": {
            "links": {
              "reporting-exception": "https://api.gleif.org/api/v1/lei-records/2WKCM9EOCM4UGJU1F243/ultimate-parent-reporting-exception"
            }
          }
        },
        "mergescore": 0,
        "enrichment": [
          {
            "id": "10",
            "name": "ticker",
            "description": "checks if an entity is publicly traded",
            "version": "1",
            "attributes": [
              {
                "is_in_list": false,
                "exchanges": "NA"
              }
            ],
            "status": {
              "code": 200,
              "message": "OK",
              "hasError": false
            }
          }
        ]
      },
      "statusCode": 200
    }
  }
}
