### ISSUE TITLE
Should conductor initiate reindex should data mistmatch?

### ISSUE THREAD

**Issue by s50600822** [Netflix/conductor#1308]
There'r cases where ES index does not agree with DB for example below is one where the doc on ES has status = RUNNING but the payload in DB is COMPLETED:

<img width="1585" alt="Screen Shot 2019-09-10 at 11 13 31 pm" src="https://user-images.githubusercontent.com/5586453/64679132-67b06900-d4be-11e9-8d66-a4ae00995fe0.png">
The query as we can see is ```status in RUNNING``` which the document matched, however the Workflow entity is loaded from DB to fill into the response. 
While this could be manually fixed, perhaps conductor could have double check the data and initiate a reindex in the background along with some log.warn...

I think the fact that inside ES index, the document had an old status was because the call to update the index failed when the wf came to completion.

**Comment by kishorebanala** [comment]
@s50600822 Given that persist makes two separate calls to primary data store and index, and workflow state is updated frequently during the execution, we'll have to be careful when syncing the primary store data with ES index. However, for the workflows that are marked as COMPLETED in primary store, but failed to update to ES, we can improve the current logic to ensure the state is synced eventually.

Do you mind elaborating your approach with examples please.
