### ISSUE TITLE
Make Conductor model extendable

### ISSUE THREAD

**Issue by andrea11** [Netflix/conductor#1316]
Hello,
I was thinking to "change" (more precisely extend) my data model of conductor. Today I could fork the project and edit directly. But I was thinking to a more generic approach, using in the interface only generics that extend your base model. For example:

```java
public interface ExecutionDAO<T extends Task, W extends Workflow> {
    List<T> getPendingTasksByWorkflow(String taskName, String workflowId);
    W getWorkflow(String workflowId, boolean includeTasks);
```

What do you think? Is there a better approach to avoid this huge refactoring?

**Comment by Jiehong** [comment]
Hello @andrea11,

I think something more in this vein might make more sense if I understand your point well. Here with the ExecutionDAO as well:

```java
public interface ExecutionDAO {
  <T extends Task> List<T> getPendingTasksByWorkflow(String var1, String var2);

  <T extends Task> List<T> getTasks(String var1, String var2, int var3);

  <T extends Task> List<T> createTasks(List<T> var1);

  <T extends Task> void updateTask(T var1);
}
```

As a `T` should always be a valid `Task` in this case, very few issues should occur I reckon, but it's a breaking change, indeed.

What do you think?

**Comment by Jiehong** [comment]
but I'd be curious to see if a Task is a valid T, but that might be the case

**Comment by Jiehong** [comment]
However, for now, if you implement DAOs with a T that actually extends your model, you should be fine with upcasting/downcasting, even though it's ugly.

**Comment by Jiehong** [comment]
> 
> 
> but I'd be curious to see if a Task is a valid T, but that might be the case

Well, after testing, it seems it is indeed perfectly valid:

```java
public class Test {
  private <T extends String> void handle(final T input) {
    return;
  }
  
  private void start() {
    this.handle("Hello");
  }
}
```

**Comment by andrea11** [comment]
@apanicker-nflx @kishorebanala @naveenchlsn Any suggestion about it? It could be something that could be accepted by/interesting for the community? Me and my team were thinking to prepare a first draft PR to give a better overview. 

Waiting for your advice 😃 
Thanks

**Comment by naveenchlsn** [comment]
@andrea11  Can you please let me know what are the benefits of run-time binding of data models? 
What functionality in the service classes/api's are we aiming to achieve with this change?

**Comment by apanicker-nflx** [comment]
@andrea11 and @AlexVinogradov Thank you for your suggestions and contributions. This is breaking change on the interface contracts and anyone extending the current interfaces would need to update their codebases. 
While this is useful and improves the extensibility of Conductor, we believe that this change should be made as part of a major version release. We will evaluate this and look into integrating this feature into the next major release (v3.0)

**Comment by Jiehong** [comment]
Re-opening this: version 3 happened, but it was not changed… (thanks github-bot I guess?)
