### ISSUE TITLE
Are JavaScript string methods supported in decision task caseExpression?

### ISSUE THREAD

**Issue by PreetiSinghal1989** [Netflix/conductor#1317]
I'm trying to create a decision task where I've different decision cases based on the following caseExpression.

`"caseExpression": "$.someInputParameter.includes('abc') ? 'abc' : 'default'",`

This doesn't seem to work. Is there a way to do something similar?

**Comment by manan164** [comment]
Hi. Try using java construct in caseExpression. 
```"var String = Java.type('java.lang.String'); var val = new String($.someInputParameter); if (val.contains('abc')) {return 'abc';} else { return  'default';}"```
