### ISSUE TITLE
failureWorkflow doesn't run when a TERMINATE task failed the workflow

### ISSUE THREAD

**Issue by kyle--lee** [Netflix/conductor#1328]
I noticed that when I had a task fail out - either `FAILED` or `FAILED_WITH_TERMINAL_ERROR`, my configured `failureWorkflow` would be started.

However, when I terminated the workflow with a `TERMINATE` system task, and set the `terminationStatus` to `FAILED`, my failure workflow isn't scheduled.

Is this expected?

**Comment by Ismaley** [comment]
Hello @kyle--lee,

I'm not fully aware of the details of this failureWorkflow feature, but for the TERMINATE task, the implementation only changes the wokflow status and it's output, then the decider service takes care of the rest. From a quick check here the failureWorkflow is referenced in terminateWorkflow method and I'm not sure this method is being called.

**Comment by apanicker-nflx** [comment]
Hi @kyle--lee Thanks for flagging this and bringing this to our attention.
@Ismaley thanks for the quick check. 

I have tagged this as a bug and we will roll out a fix for this soon. In the meantime, if you can contribute a fix for this issue, we would welcome that too :)

**Comment by krishnaputhran** [comment]
HI is the fix rolled out for this? As of today the bug is still there. Since TERMINATE task ends the workflow abruptly, it has to trigger the failure workflow.

**Comment by apanicker-nflx** [comment]
@krishnaputhran We have yet to resolve this issue, but we can try to prioritize this. In the meantime, please feel free to contribute a fix for this if you have some cycles to spare.

**Comment by krishnaputhran** [comment]
Sure will see, if i'll see if I can. Thanks for the response

**Comment by apanicker-nflx** [comment]
Fixed in #1759
