### ISSUE TITLE
dyno-core build error

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1329]
I tried all repository which i know, bug always got the below errors when i build project:

Could not find com.netflix.dyno:dyno-core:1.6.5-rc.4.
Searched in the following locations:
  - https://maven.aliyun.com/repository/jcenter/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.pom
  - https://maven.aliyun.com/repository/jcenter/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.jar
  - https://maven.aliyun.com/repository/central/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.pom
  - https://maven.aliyun.com/repository/central/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.jar
  - https://maven.aliyun.com/repository/google/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.pom
  - https://maven.aliyun.com/repository/google/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.jar
  - https://maven.aliyun.com/repository/gradle-plugin/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.pom
  - https://maven.aliyun.com/repository/gradle-plugin/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.jar
  - https://maven.aliyun.com/nexus/content/repositories/gradle-plugin/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.pom
  - https://maven.aliyun.com/nexus/content/repositories/gradle-plugin/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.jar
  - https://repo.maven.apache.org/maven2/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.pom
  - https://repo.maven.apache.org/maven2/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.jar
  - http://jcenter.bintray.com/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.pom
  - http://jcenter.bintray.com/com/netflix/dyno/dyno-core/1.6.5-rc.4/dyno-core-1.6.5-rc.4.jar
Required by:
    project :conductor-server > project :conductor-redis-persistence > com.netflix.dyno-queues:dyno-queues-redis:2.0.0-rc8
    project :conductor-server > project :conductor-redis-persistence > com.netflix.dyno-queues:dyno-queues-redis:2.0.0-rc8 > com.netflix.dyno-queues:dyno-queues-core:2.0.0-rc8

**Comment by rickfish** [comment]
We have the same issue. The package is at dl.bintray.com. Unfortunately our artifactory product does not have access to that repo....

**Comment by apanicker-nflx** [comment]
@andyyumiao @rickfish Is this still the case with the latest version? We are planning to upgrade to the newest dyno stable version (v2.0.12) soon and this may solve this concern.

**Comment by rickfish** [comment]
Yes, it is the case but we found that we could download from bintray so we are good.

**Comment by andyyumiao** [comment]
> @andyyumiao @rickfish Is this still the case with the latest version? We are planning to upgrade to the newest dyno stable version (v2.0.12) soon and this may solve this concern.

It works now, as I changed my network.....many thanks

**Comment by andyyumiao** [comment]
> @andyyumiao @rickfish Is this still the case with the latest version? We are planning to upgrade to the newest dyno stable version (v2.0.12) soon and this may solve this concern.



> @andyyumiao @rickfish Is this still the case with the latest version? We are planning to upgrade to the newest dyno stable version (v2.0.12) soon and this may solve this concern.

**Comment by andyyumiao** [comment]
> @andyyumiao @rickfish Is this still the case with the latest version? We are planning to upgrade to the newest dyno stable version (v2.0.12) soon and this may solve this concern.

@apanicker-nflx It works in the latest version, the package for dyno-core has been upgrated, many thanks.
