### ISSUE TITLE
Docker-compose uses unofficial v1r3n/dynomite image

### ISSUE THREAD

**Issue by robertlagrant** [Netflix/conductor#1332]
The Conductor docker-compose.yml uses the unofficial (-looking) v1r3n/dynomite image instead of Netflix/dynomite:
https://github.com/Netflix/conductor/blob/e100b98451ece8fec1bc6b4e2af6e5d5a8f9fb90/docker/docker-compose.yaml#L44

Is there a reason for this? It'd be good to know why Conductor recommends this, if it does.

Thanks!

**Comment by apanicker-nflx** [comment]
@robertlagrant Thanks for reporting this.
This docker image belongs to the original author of Conductor and Dyno-Queues (a queueing recipe built on top of Dynomite). We will work with the dynomite team for an official docker image that can be used here.
