### ISSUE TITLE
Support for Blast/Bleve indexing

### ISSUE THREAD

**Issue by flaviostutz** [Netflix/conductor#1335]
Elasticsearch is too heavyweight for most applications we've been employing Conductor (spending too much on AWS!) so we would like to use some other lightweight indexing services like "Bleve" (by using Blast as a server) because it would use minimal resources for each Conductor deployment.

What do you think about receiving a PR on an indexing module for Blast (https://github.com/mosuka/blast)?

**Comment by apanicker-nflx** [comment]
@flaviostutz Indexing the execution documents are mainly used within Conductor for searching across workflows and tasks. The `[IndexDAO](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/dao/IndexDAO.java)` interface can be implemented by any indexing engine and this should serve the purpose. Please feel free to submit a PR with your implementation of this interface with Blast. This would definitely be helpful to the community.
