### ISSUE TITLE
Ability to use Cassandra for persistence

### ISSUE THREAD

**Issue by kelnos** [Netflix/conductor#1339]
We'd really like to use Cassandra for persistence rather than Dynomite, as we're not comfortable with the manual, multi-step, time-consuming nature of re-partitioning a Dynomite cluster in the case where we need to add nodes in order to keep up with data storage and/or traffic requirements as more of our internal teams adopt Conductor.  (We already use Cassandra quite a bit and have an existing, well-tested process for resizing clusters.)

I noted here -- https://github.com/Netflix/conductor/issues/1137#issuecomment-529678354 -- that it seems Netflix has started using Cassandra for persistence?  Is there an ETA as to when this support will be available in open-source Conductor?  I was considering writing support myself, but would rather not if the code has already been written.

**Comment by kelnos** [comment]
@milongapau apologies, but tagging you here since you're the author of the comment I reference above; perhaps you'd be the right person to answer this question.

**Comment by apanicker-nflx** [comment]
@kelnos The [Cassandra persistence](https://github.com/Netflix/conductor/tree/master/cassandra-persistence) module is already available, albeit its a partial implementation. Currently, we are in the process of implementing the MetadataDAO in C* and will will publish this soon.
