### ISSUE TITLE
How to register Event Handler using Conductor Client

### ISSUE THREAD

**Issue by sameekb** [Netflix/conductor#134]
Hi Team,

Is there any conductor-client API to register **EventHandler** object. I can create an object of

`com.netflix.conductor.common.metadata.events.EventHandler`

But couldn't find any API to register the object. 

I had to do the same using Swagger, but an API around this will be helpful.

Regards,
Sameek

**Comment by v1r3n** [comment]
@sameekb Yes, we do not have an API yet, but should be available in the subsequent versions.
Thanks for the feedback.
