### ISSUE TITLE
Optional usage for Task Timeout

### ISSUE THREAD

**Issue by gergelna** [Netflix/conductor#1340]
I am using now the conductor-2.15.2 RELEASE version, and I am trying timeouts and optional usage. I would like to ask if there is a way to use the "optional = true" task setting to be taken into account on task timeout as well? I've tried with different variations but it seems the optional is taken into account only if taskResult.status = FAILED, but not on task timeout.
 
I mean we have a task called manual_task in which some kind of user action is needed which can take even days. Our intention would be to give for example 2 days for users to finish their manual activity, but even if that activity is finished or not the workflow should be continued.

The variations I tried:
SIMPLE task(optional = true, retryCount: 0; timeoutSeconds: 5; responseTimeoutSeconds: 1):
 - timeoutPolicy = TIME_OUT_WF --> the wf is stopped after 5 seconds
 - timeoutPolicy = ALERT_ONLY   --> the wf is not continued nor stopped it gets stuck forever, at least I left it for an hour and still it was in IN_PROGRESS

However with WAIT task seems to be working with optional = true and ALERT_ONLY (with MR https://github.com/Netflix/conductor/pull/1221):

WAIT task(retryCount: 0; timeoutSeconds: 5; responseTimeoutSeconds: 1):
 - optional = false; timeoutPolicy = TIME_OUT_WF --> the wf is stopped: Task timed out after 33765 millisecond
 - optional = false; timeoutPolicy = ALERT_ONLY   --> the wf is stopped: responseTimeout: 1 exceeded
 - optional = true; timeoutPolicy = TIME_OUT_WF --> the wf is stopped: Task timed out after 32609 millisecond. Timeout configured as 5000
 - optional = true; timeoutPolicy = ALERT_ONLY   --> the wf is continued well after waiting ~34 sec

So the waiting time does not seem to be good, however it does use the optional = true with WAIT task if the timoutPolicy = ALERT_ONLY

Is it intentional that optional is not taken into account on SIMPLE task timeout?

many thanks in advance

**Comment by apanicker-nflx** [comment]
@gergelna Can you provide your workflow definition where you are able to reproduce the issue? Optional flags should be honored for task timeouts as well and not just for FAILED tasks.
