### ISSUE TITLE
2 questions about mysql and ElasticSearch

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1346]
1. Is mysql not necessary? 
2. Are the data stored in ElasticSearch？
Can they be replaced with each other?

**Comment by apanicker-nflx** [comment]
@andyyumiao Conductor uses a primary store (MySQL/Dynomite/Cassandra) for storing execution data of workflows and tasks and a secondary store (Elasticsearch) for indexing the execution documents to provide search capability (primarily for the UI).

 > 1. Is mysql not necessary?

The primary execution store (MySQL, in this case) is necessary and you would not be able to execute workflows and tasks without it.

> 2. Are the data stored in ElasticSearch？
Can they be replaced with each other?

Data is stored in elasticsearch to enable search operations. Elasticsearch CANNOT replace the primary store. In fact, Elasticsearch can be made optional in your configuration given the caveat that the UI will be mostly non-functional.

**Comment by andyyumiao** [comment]
> 1. Can they be replaced with each other?

@apanicker-nflx I've now understood, many thanks for the greate work.
