### ISSUE TITLE
Make Elastic Search calls asynchronous 

### ISSUE THREAD

**Issue by mohelsaka** [Netflix/conductor#1360]
Hello,

We recently had some issues with Elastic Search backend for conductor server and that made the ExecutionService fail for some requests, and eventually, some workflows became stuck.

We were thinking of changing any calls to ES to be asynchronous so it will not be a hard dependency for the ExectionService. In addition to that, calls to conductor server will be much faster because we will be writing to the operational data store (mysqly, redis ....).

One way of implementing this is to extend the IndexDaoInterface and wrap all the calls to ES5 (and/or ES6) implementations.

Do you see any bigger problems that can result of that of this? ... If you think it makes sense, I can work on it.

**Comment by manan164** [comment]
Hi @mohelsaka It is already there but not released. Please check https://github.com/Netflix/conductor/blob/dev/core/src/main/java/com/netflix/conductor/core/config/Configuration.java#L56.

**Comment by apanicker-nflx** [comment]
@mohelsaka @manan164 This was released as part of [v2.16.0](https://github.com/Netflix/conductor/releases/tag/v2.16.0)
