### ISSUE TITLE
Conductor task logs maximum 10 lines

### ISSUE THREAD

**Issue by tristind** [Netflix/conductor#1363]
Hello,

I am logging over 10 lines into a conductor task. The problem is I am seeing the last 10 log lines. Is there a reason why all the other lines are being ignored?

**Comment by marius1** [comment]
It looks like this is because the default size for an elasticsearch search is 10, see: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-request-from-size.html

In the ElasticSearchDAOV5.getTaskExecutionLogs you could do a setSize(<something>) to make this larger, but what size should the be?

**Comment by apanicker-nflx** [comment]
@tristind As suggested by @marius1 , the default size of 10 is being used. 

The task execution logs in the UI are mainly used to provide context regarding task execution and I would recommend using logstash for storing task logs.

**Comment by sakim-hooda** [comment]
> @tristind As suggested by @marius1 , the default size of 10 is being used.
> 
> The task execution logs in the UI are mainly used to provide context regarding task execution and I would recommend using logstash for storing task logs.

@apanicker-nflx we can define a configurable properties for task log count. so it can be changed as per  requirement. simply adding setSize() need to redeployment  while making it configurable only need server restart.

As i  have checked we are getting hits  more  than 10 from elastic-search but shown only 10.

**Comment by sakim-hooda** [comment]
i have working solution prepared with configurable property  for log count and would like to merge if it is needed.

**Comment by apanicker-nflx** [comment]
@sakim-hooda Please create a PR with your proposed changes. Please add description of what changes you are suggesting to the PR.

**Comment by cesar-moya** [comment]
@sakim-hooda @apanicker-nflx Hi guys, we're facing this same limitation, was the PR ever merged? otherwise, could you share what configurations need to be done on elastic to be able to retrieve more than 10 entries? - Thanks.

**Comment by apanicker-nflx** [comment]
@cesar-moya Please configure this property `tasklog.elasticsearch.query.size` as seen [here](https://github.com/Netflix/conductor/blob/90ab0ba34a678755d6de8b253da4a808b34d545d/es5-persistence/src/main/java/com/netflix/conductor/elasticsearch/ElasticSearchConfiguration.java#L78)
