### ISSUE TITLE
ElasticSearch 7 Compatibility

### ISSUE THREAD

**Issue by indiv0** [Netflix/conductor#1367]
Hi! Are there any plans to add ElasticSearch 7 compatibility?

**Comment by apanicker-nflx** [comment]
@indiv0 We haven't planned to add an ES7 module yet. However, since the indexing module is pluggable in Conductor, this should be a straightforward implementation of the [IndexDAO](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/dao/IndexDAO.java) interface.

Please feel free to contribute your implementation as this would help out the community greatly.

**Comment by sfeitler-oracle** [comment]
Hi, I have been looking at adding ElasticSearch 7 support to Conductor. The IndexDAO stuff seems pretty straightforward. But one of the integration tests would require a change that is incompatible with ElasticSearch 5.

Specifically, ESRestClientHttpEndToEndTest.java is not version-specific, and it calls ES's performRequest method. All the various ways to invoke performRequest have been deprecated in version 6 with 2 new ones added; basically if it used a Map of parameters, now it uses an ElasticSearch Request object in the call. In version 7, the various kinds are gone, just the 2 new ones using a Request object remain.

I think ElasticSearch 5 is end-of-life. So one option would be dropping support for it from Conductor? But I don't know if that's acceptable.

**Comment by kishorebanala** [comment]
@sfeitler-oracle Thanks for looking into ES7 integration. We can deprecate ES5 and replace with ES6/7 modules.

However, the cleaner option would be to move version specific code from this integration test to each module version. I.e `waitForGreenCluster` can be moved to `EmbeddedElasticSearch` implementations, say `EmbeddedElasticSearchV5`, which already has start, stop etc. methods, thereby keeping the tests independent of versions.

**Comment by sfeitler-oracle** [comment]
Ok, I'll investigate that.

**Comment by surajrrao** [comment]
@sfeitler-oracle where you able to progress on ES 7
