### ISSUE TITLE
Rewrite Docker Image for UI to use CentOS -  Contact https://registry.npmjs.org/nf-workflow-ui Error

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#137]
Hello,

I want to rewrite the very well working provided [Dockerfile](https://github.com/Netflix/conductor/blob/dev/docker/ui/Dockerfile) from Conductor UI to CentOS 7.3.
(The provided Dockerfile from @jcantosz  is based on Docker image "node", which itself is based on "debian:jessie".)

Here is the rewritten Dockerfile, which installs nodejs 6.9.4 via EPEL package in CentOS:

<pre>
FROM centos:7.3.1611

# Make app folders
RUN mkdir -p /app/config /app/logs /app/libs

# Startup script(s)
COPY ./bin /app

# Get all the dependencies
RUN yum update -y \
  && yum -y install git \

  # Chmod scripts
  && chmod +x /app/startup.sh

# Install nodejs 6.9.4-2.el7 via EPEL
RUN yum install -y epel-release \
    && yum install -y nodejs \
    && yum install -y npm

# Get and install conductor UI
RUN git clone https://github.com/netflix/conductor.git \

  # Get UI project
  && mv /conductor/ui /app \

  # Remove the conductor project
  && rm -rf conductor \

  # Install UI packages
  && cd /app/ui \
  && npm install \
  && npm run build --server

EXPOSE 5000

CMD ["/app/startup.sh"]
ENTRYPOINT ["/bin/bash"]
</pre>

I am facing problems when it comes to build the nodejs application with this command:
<pre>
npm run build --server
</pre>

The error message I  always get is this:

<pre>
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14)

npm
 ERR! Linux 4.8.0-41-generic

npm ERR! argv
 "/usr/bin/node" "/usr/bin/npm" "run" "build" "--server"

npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! nf-workflow-ui@1.0.0 build: `gulp build --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nf-workflow-ui@1.0.0 build script 'gulp build --release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nf-workflow-ui package,
npm ERR! not with npm itself.
npm 
ERR! Tell the author that this fails on your system:
npm ERR!     gulp build --release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nf-workflow-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nf-workflow-ui
npm ERR!
 There is likely additional logging output above.

npm ERR!
 Please include the following file with any support request:
npm ERR!     /app/ui/npm-debug.log
</pre>

The debug file shows an errror to contact https://registry.npmjs.org/nf-workflow-ui:

<pre>
[root@bc138256fbc0 app]# cat /app/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'bugs', 'nf-workflow-ui' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 silly fetchPackageMetaData nf-workflow-ui
5 silly fetchNamedPackageData nf-workflow-ui
6 silly mapToRegistry name nf-workflow-ui
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry data Result {
9 silly mapToRegistry   raw: 'nf-workflow-ui',
9 silly mapToRegistry   scope: null,
9 silly mapToRegistry   escapedName: 'nf-workflow-ui',
9 silly mapToRegistry   name: 'nf-workflow-ui',
9 silly mapToRegistry   rawSpec: '',
9 silly mapToRegistry   spec: 'latest',
9 silly mapToRegistry   type: 'tag' }
10 silly mapToRegistry uri https://registry.npmjs.org/nf-workflow-ui
11 verbose request uri https://registry.npmjs.org/nf-workflow-ui
12 verbose request no auth needed
13 info attempt registry request try #1 at 6:28:55 AM
14 verbose request id 517f9915d1650745
15 http request GET https://registry.npmjs.org/nf-workflow-ui
16 http 404 https://registry.npmjs.org/nf-workflow-ui
17 verbose headers { 'content-type': 'application/json',
17 verbose headers   'cache-control': 'max-age=0',
17 verbose headers   'content-length': '2',
17 verbose headers   'accept-ranges': 'bytes',
17 verbose headers   date: 'Sat, 25 Mar 2017 06:28:55 GMT',
17 verbose headers   via: '1.1 varnish',
17 verbose headers   age: '0',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'x-served-by': 'cache-fra1223-FRA',
17 verbose headers   'x-cache': 'MISS',
17 verbose headers   'x-cache-hits': '0',
17 verbose headers   'x-timer': 'S1490423335.246396,VS0,VE712',
17 verbose headers   vary: 'Accept-Encoding' }
18 silly get cb [ 404,
18 silly get   { 'content-type': 'application/json',
18 silly get     'cache-control': 'max-age=0',
18 silly get     'content-length': '2',
18 silly get     'accept-ranges': 'bytes',
18 silly get     date: 'Sat, 25 Mar 2017 06:28:55 GMT',
18 silly get     via: '1.1 varnish',
18 silly get     age: '0',
18 silly get     connection: 'keep-alive',
18 silly get     'x-served-by': 'cache-fra1223-FRA',
18 silly get     'x-cache': 'MISS',
18 silly get     'x-cache-hits': '0',
18 silly get     'x-timer': 'S1490423335.246396,VS0,VE712',
18 silly get     vary: 'Accept-Encoding' } ]
19 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/nf-workflow-ui
19 silly fetchPackageMetaData     at makeError (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:302:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:280:14)
19 silly fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:210:14)
19 silly fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:187:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:1048:10)
19 silly fetchPackageMetaData     at emitOne (events.js:96:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:969:12)
19 silly fetchPackageMetaData  error for nf-workflow-ui { Error: Registry returned 404 for GET on https://registry.npmjs.org/nf-workflow-ui
19 silly fetchPackageMetaData     at makeError (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:302:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:280:14)
19 silly fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:210:14)
19 silly fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:187:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:1048:10)
19 silly fetchPackageMetaData     at emitOne (events.js:96:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:969:12) pkgid: 'nf-workflow-ui', statusCode: 404, code: 'E404' }
20 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/nf-workflow-ui
20 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:302:12)
20 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:280:14)
20 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:210:14)
20 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:187:22)
20 verbose stack     at emitTwo (events.js:106:13)
20 verbose stack     at Request.emit (events.js:191:7)
20 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:1048:10)
20 verbose stack     at emitOne (events.js:96:13)
20 verbose stack     at Request.emit (events.js:188:7)
20 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:969:12)
21 verbose statusCode 404
22 verbose pkgid nf-workflow-ui
23 verbose cwd /app
24 error Linux 4.8.0-41-generic
25 error argv "/usr/bin/node" "/usr/bin/npm" "bugs" "nf-workflow-ui"
26 error node v6.9.4
27 error npm  v3.10.10
28 error code E404
29 error 404 Registry returned 404 for GET on https://registry.npmjs.org/nf-workflow-ui
30 error 404
31 error 404 'nf-workflow-ui' is not in the npm registry.
32 error 404 You should bug the author to publish it (or use the name yourself!)
33 error 404 Note that you can also install from a
34 error 404 tarball, folder, http url, or git url.
35 verbose exit [ 1, true ]
</pre>

Also, npm bugs shows me this very same error message:
<pre>
[root@bc138256fbc0 app]# npm bugs nf-workflow-ui
npm ERR! Linux 4.8.0-41-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "bugs" "nf-workflow-ui"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/nf-workflow-ui
npm ERR! 404 
npm ERR! 404  'nf-workflow-ui' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
</pre>

Google searches pointed me to websites saying to point packages.json to the git repository.
But as far as I can see within packages.json the repository is already defined:
<pre>
"repository": {
    "type": "git",
    "url": "git@github.com:Netflix/conductor.git"
  },
</pre>

What puzzles me most is, that it works perfectly with the provided Dockerfile based on "node".
I have investigated the "node" image and the other images it relies on, but cannot find any useful things.

What I also tried:
As the EPEL package, does not contain the latest nodejs version, I also tried to install nodejs 7.7.4 with these commands instead:
<pre>
ENV NODEJS_VERSION=v7.7.4
ENV PATH=/apps/node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin

RUN mkdir /apps && cd /apps && curl -s -L -O https://nodejs.org/dist/${NODEJS_VERSION}/node-${NODEJS_VERSION}-linux-x64.tar.xz && tar xf node-${NODEJS_VERSION}-linux-x64.tar.xz && mv node-${NODEJS_VERSION}-linux-x64 node
</pre>

But I still get the very same error.

Thanks for some more hints to fix the problem.

**Comment by jcantosz** [comment]
Hey @blueelephants, I tried this out and got the same results. 

The server will compile/run if you remove the `image` task from the gulp sequence (line 179 in gulpfile.babel.js).  This leads me to believe, that you are missing some packages required for **imagemin**, or **pngquant** on CentOS.

I tried `yum install -y libpng-devel pngquant` which did not resolve the issue.

**Comment by blueelephants** [comment]
Thanks for investigating my issue @jcantosz.

I tried to follow your instructions, but I always run into the very same error.
Did you completely remove line 179?
Or did you just remove the "image" part of this line?

I tried both and it didn't work for me.

Having said that, I also tried to find the package imagemin for CentOS, but with no success.
Seems to be a rather "exotic" package?

**Comment by jcantosz** [comment]
No problem @blueelephants. 

(imgmin)[https://github.com/sindresorhus/gulp-imagemin] is an npm package. My guess is that there are system dependencies that the package uses which are present on Ubuntu but not CentOS.

I removed just the `, 'image'` part. I was doing this in interactive mode, but have updated the Dockerfile you provided to do this at build time (see line 25). See if this builds:

```
FROM centos:7.3.1611

# Make app folders
RUN mkdir -p /app/config /app/logs /app/libs

# Startup script(s)
COPY ./bin /app

# Get all the dependencies
RUN yum update -y \
  && yum -y install git \

  # Chmod scripts
  && chmod +x /app/startup.sh

# Install nodejs 6.9.4-2.el7 via EPEL
RUN yum install -y epel-release \
    && yum install -y nodejs \
    && yum install -y npm

# Get and install conductor UI
RUN git clone https://github.com/netflix/conductor.git \
 
  # Remove images
  && sed -i "179s/, 'images'//g" /conductor/ui/gulpfile.babel.js \ 

  # Get UI project
  && mv /conductor/ui /app \

  # Remove the conductor project
  && rm -rf conductor \

  # Install UI packages
  && cd /app/ui \
  && npm install \
  && npm run build --server

EXPOSE 5000

CMD ["/app/startup.sh"]
ENTRYPOINT ["/bin/bash"]
```

**Comment by blueelephants** [comment]
Thanks @jcantosz ... I am still looking for the missing libraries to install on CentOS.
I debuged the underlying Debian images of the "node" images... but its quite time consuming to find and install all those libraries to get it up & running in a clean way.

The reason I want to run CentOS is because of trying to adhere to "in-house standards", but in the end, if Debian is the only way to go.. I don't mind

**Comment by jcantosz** [comment]
@blueelephants No problem. Unless your requirements are strict about CentOS, I would think Debian would be the way to go. If you continue down the CentOS path, it may be easier to re-write or update portions of the UI project to not depend on the modules that are causing you trouble.

**Comment by saidatta** [comment]
Weirdly, I encounter this issue when I do `docker-compose build` on MacOSx. When I login into the container and run the `npm build --server`. It works. hmm

**Comment by saidatta** [comment]
I finally figured out the solution! Before running `docker-compose build` I ran npm install && npm build` on my host machine (OS-X).

This was clashing with the Copy command that happened in DockerFile.
