### ISSUE TITLE
Duplicate tasks pulled when try to update task's outputData field using worker thread

### ISSUE THREAD

**Issue by patelraju** [Netflix/conductor#1379]
Hi,

Scenario:- I have a worker thread that pulls the tasks from Netflix conductor and immediately acknowledge the task with ack=true then worker thread perform some operations and try to update task outputData field along with status= IN_PROGESS then again the same task is getting pulled by the worker thread.

Endpoint used to poll tasks:-

http://127.0.0.1:8080/api/tasks/poll/print_task

Endpoint ,request header and request body that used to update task's outputData field:-
    "http://127.0.0.1:8080/api/tasks/'"

Request header:- Content-Type: application/json; Accept: application/json;

Request Body:-
{
  "workflowInstanceId": "118e7efe-bc55-45c5-928c-881fdb897b5c",
  "taskId": "35e449a2-5330-4a0a-9657-4f9727802759",
  "workerId": "GFZSM4Q2E",
  "reasonForIncompletion" : " ",
  "callbackAfterSeconds": "0",
  "status": "IN_PROGRESS",
  "outputData": {"K":"V"}
}

I'm expecting that the same task should not be pulled by the worker while updating it's outputData field. Could you please help me with this issue.?

**Comment by skyrocknroll** [comment]
You need to set `callbackAfterSeconds` to a time duration between the current task update and next task update.

**Comment by patelraju** [comment]
> You need to set `callbackAfterSeconds` to a time duration between the current task update and next task update.

Thanks for your reply. 
In suggested scenario worker is pulling same task after specified duration even If I completely remove callbackAfterSeconds field from request body then also immediately same task will be pulled by worker.

I would like to know,  why NFC is allowing to poll the tasks which is already acknowledged as true.?

**Comment by Shole4ever** [comment]
@patelraju I think this is similar to an issue I am also facing https://github.com/Netflix/conductor/issues/1378

**Comment by kishorebanala** [comment]
@patelraju Please set `callbackAfterSeconds` to some duration that you don't want this task to be available in poll. For eg., Your updated task result would look like:

```
{
"workflowInstanceId": "118e7efe-bc55-45c5-928c-881fdb897b5c",
"taskId": "35e449a2-5330-4a0a-9657-4f9727802759",
"workerId": "GFZSM4Q2E",
"reasonForIncompletion" : " ",
"callbackAfterSeconds": "60",
"status": "IN_PROGRESS",
"outputData": {"K":"V"}
}
```

**Comment by patelraju** [comment]
> @patelraju Please set `callbackAfterSeconds` to some duration that you don't want this task to be available in poll. For eg., Your updated task result would look like:
> 
> ```
> {
> "workflowInstanceId": "118e7efe-bc55-45c5-928c-881fdb897b5c",
> "taskId": "35e449a2-5330-4a0a-9657-4f9727802759",
> "workerId": "GFZSM4Q2E",
> "reasonForIncompletion" : " ",
> "callbackAfterSeconds": "60",
> "status": "IN_PROGRESS",
> "outputData": {"K":"V"}
> }
> ```

Thanks for your reply. I tried with same , In such case after 60 secs the task is getting pulled again that means in every 60 secs I need to keep updating the task until the workflow is completed but in my scenario the worker can not assure to update task in every 60 secs, sometimes it can take uncertain duration of time.

**Comment by skyrocknroll** [comment]
You can set any value. It need not to be 60 sec . You can set a values little leas than response timeout seconds

**Comment by patelraju** [comment]
After setting callbackAfterSeconds field's value little less than response response timeout , it is working as expected for me. 
Thank you so much @skyrocknroll @kishorebanala @Shole4ever
