### ISSUE TITLE
Need Help: Issue with Http task input/output payload size 

### ISSUE THREAD

**Issue by ketantalreja** [Netflix/conductor#1381]
Hi Anoop, and Netflix Conductor Team, 

I am using Netflix Conductor version v2.11.0.
I am working on one use case where large input payloads are expected be send to HTTP task defined in the workflow, but the task fails with "FAILED_WITH_TERMINAL_ERROR" due to the implementation in this class here below https://github.com/Netflix/conductor/blob/master/client/src/main/java/com/netflix/conductor/client/http/TaskClient.java

```java public void evaluateAndUploadLargePayload(TaskResult taskResult, String taskType) {
        Preconditions.checkNotNull(taskResult, "Task result cannot be null");
        Preconditions.checkArgument(StringUtils.isBlank(taskResult.getExternalOutputPayloadStoragePath()), "External Storage Path must not be set");

        try (ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream()) {
            objectMapper.writeValue(byteArrayOutputStream, taskResult.getOutputData());
            byte[] taskOutputBytes = byteArrayOutputStream.toByteArray();
            long taskResultSize = taskOutputBytes.length;
            WorkflowTaskMetrics.recordTaskResultPayloadSize(taskType, taskResultSize);

            long payloadSizeThreshold = conductorClientConfiguration.getTaskOutputPayloadThresholdKB() * 1024;
            if (taskResultSize > payloadSizeThreshold) {
                if (!conductorClientConfiguration.isExternalPayloadStorageEnabled()
                        || taskResultSize > conductorClientConfiguration.getTaskOutputMaxPayloadThresholdKB() * 1024) {
                    taskResult.setReasonForIncompletion(String.format("The TaskResult payload size: %d is greater than the permissible %d MB", taskResultSize, payloadSizeThreshold));
                    taskResult.setStatus(TaskResult.Status.FAILED_WITH_TERMINAL_ERROR);
                    taskResult.setOutputData(null);
                } else {
                    WorkflowTaskMetrics.incrementExternalPayloadUsedCount(taskType, ExternalPayloadStorage.Operation.WRITE.name(), ExternalPayloadStorage.PayloadType.TASK_OUTPUT.name());
                    String externalStoragePath = uploadToExternalPayloadStorage(ExternalPayloadStorage.PayloadType.TASK_OUTPUT, taskOutputBytes, taskResultSize);
                    taskResult.setExternalOutputPayloadStoragePath(externalStoragePath);
                    taskResult.setOutputData(null);
                }
            }
        } catch (IOException e) {
            String errorMsg = String.format("Unable to update task: %s with task result", taskResult.getTaskId());
            logger.error(errorMsg, e);
            throw new ConductorClientException(errorMsg, e);
        }
    }
```

I have tried using the configuration properties based on the documentation https://netflix.github.io/conductor/externalpayloadstorage/ 
and as I understand correctly, if I define configuration, 

**workflow.external.payload.storage=S3
conductor.task.input.payload.threshold.kb=9072
conductor.task.output.payload.threshold.kb=9072**

then I have to provide AWS S3 instance access for storing payload data.

Now, I don't want to add S3 in my design architecture, could you please suggest what could be other approach to overcome this input/output payload size limitation?  And would be helpful if you provide some examples. 

Thanks,
Ketan

**Comment by apanicker-nflx** [comment]
@ketantalreja The motivation for implementing the external payload storage integration in Conductor is documented [here](https://netflix.github.io/conductor/externalpayloadstorage/#context).

If you do not want use S3 in your design, you can choose to override the default values for the client [here](https://github.com/Netflix/conductor/blob/master/client/src/main/java/com/netflix/conductor/client/config/DefaultConductorClientConfiguration.java) such that the values are greater than the expected size of your payloads. This would ensure that the client does not stop you from updating the task with large payloads (as is the case in your example).

**Comment by apanicker-nflx** [comment]
Alternatively, I would suggest you to implement the [ExternalPayloadStorage](https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/utils/ExternalPayloadStorage.java) interface with an object store of your choice to avoid having to store large payloads as part of the workflow. More details about this can be found [here](https://netflix.github.io/conductor/extend/#external-payload-storage).
