### ISSUE TITLE
Conductor installation error while running gradlew.bat server

### ISSUE THREAD

**Issue by CG-ADAMS** [Netflix/conductor#1384]
Hi,

I am receiving following error while installing the conductor: Can you please help

> Task :conductor-server:server FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conductor-server:server'.
> A problem occurred starting process 'command 'C:\Program Files\Java\jdk1.8.0_2
31\bin\java.exe''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with
Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:comm
and_line_warnings

BUILD FAILED in 9m 37s
40 actionable tasks: 40 executed

C:\Netflix\conductor-master\server>

**Comment by kishorebanala** [comment]
@CG-ADAMS Do you have a full stack trace? Were you able to find out why ```A problem occurred starting process 'command 'C:\Program Files\Java\jdk1.8.0_2
31\bin\java.exe''``` this is happening in your system?

**Comment by CG-ADAMS** [comment]
hi kishore,

its on windows 2012 server. i dont see any issue while running java.exe command:
```

C:\Program Files\Java\jdk1.8.0_231\bin>java.exe -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```

**Comment by kishorebanala** [comment]
@CG-ADAMS But, the gradle process to start Conductor server might have trouble running some commands.

**Comment by CG-ADAMS** [comment]
the issue has been resolved after reinstalling the JDK and JRE on the system.
