### ISSUE TITLE
[Question] Has anybody considered using Elasticsearch as their Primary backing DB?

### ISSUE THREAD

**Issue by cshen200** [Netflix/conductor#1387]
Just curious if people have considered the approach and if so what are the pros and cons and who drove you to one way or the other?

Thanks,
Chao

**Comment by apanicker-nflx** [comment]
@cshen200 There are a number of resources that you can find that explain why choosing elasticsearch as a primary store is not recommended. While it can definitely be a primary store in certain situations, it is not suitable for Conductor.
The primary reason is that elasticsearch is an eventually-consistent data store that does not provide read-after-write guarantees. Documents that are indexed can take a few seconds to be available for reading after being written successfully. This would violate the requirements from Conductor where tasks are created and executed at high frequency.
