### ISSUE TITLE
Is anyone running Conductor on-premise or different data center?

### ISSUE THREAD

**Issue by dctc42** [Netflix/conductor#1388]
Hi,

I'm considering using Conductor but a lot of the documentation and config give me the impression that running in AWS is a requirement. This won't work for me as I need to deploy this in multiple non-AWS data centers as well as customer's data centers.

Is anyone running Conductor outside of AWS?

**Comment by RuriRyan** [comment]
We're running conductor inside of a kubernetes cluster, running on-prem, setup with kubeadm. The requirements are just an elasticsearch and dynomite/redis deployment. We use elasticsearch for logging and for conductor. And a redis-ha deployment running with redis sentinel.
There is no hard requirements for AWS. You just need the dependent services.

**Comment by dctc42** [comment]
Thanks for the reply. This was my impression as well but I wanted to hear from someone who's done it.
