### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by TangKunjun** [Netflix/conductor#139]
Hello！
   I have successfully installed this project.Can successfully open http: // localhost: 8080 and http: // localhost: 3000 pages.But what should be done next?How to create a new workflow?Is there a more detailed use of documentation available?

**Comment by v1r3n** [comment]
@TangKunjun Please visit https://netflix.github.io/conductor/ for details on getting started.

**Comment by TangKunjun** [comment]
Thank you very much for your answer. I am a freshman, so I will have a lot of problems that I don’t know, I hope you can help me answer. Now I have been able to simply operate the workflow, but only limited to the server ui, I would like to know, can operate the workflow in java? Is it possible to drag the page view to operate the workflow?

**Comment by v1r3n** [comment]
@TangKunjun the UI is only used for monitoring the workflows.  Operational aspects are handled via REST APIs.  Refer to the documentation for more.
