### ISSUE TITLE
Create a more detailed Contributing.md file

### ISSUE THREAD

**Issue by vmr1532** [Netflix/conductor#1398]
Create more detailed Contributing.md file regarding the different ways that newcomers can contribute like writing content,  creating new features to the project. Create a more detailed documentation guide.

**Comment by kishorebanala** [comment]
@vmr1532 Thanks for the suggestions. We definitely are considering restructuring contribution guidelines ASAP. Meanwhile, if you have any questions, feel free to ask in [Gitter](https://gitter.im/netflix-conductor/community).

**Comment by raja589** [comment]
I am interested to work on this. Can I contribute to this?

**Comment by vmr1532** [comment]
I am interested to work on this. Can I contribute to this?

**Comment by vmr1532** [comment]
Can you please make me a member of this organization.

**Comment by vmr1532** [comment]
@kishorebanala

**Comment by kishorebanala** [comment]
@vmr1532 That'd be great. You don't have to be a member to contribute. You can just fork the repo and create a pull request against `dev` branch.
