### ISSUE TITLE
Asking for help，BulkRequest operation , which caused many threads to be blocked 

### ISSUE THREAD

**Issue by manheiba** [Netflix/conductor#1399]
### Conductor version: 2.19.0

Recently, I found that there was a serious synchronization lock problem during ES operation, which caused many threads to be blocked

workflow.elasticsearch.index.batchSize=10
```
ElasticSearchRestDAOV6.java

    private synchronized void indexBulkRequest(String docType) {
       .....
    }

```

For example:

- Updateworkflow of system task worker - *  blocked by indexBulkRequest method
- Workflowsweeper blocked by indexBulkRequest method
- Startworkflow  blocked by indexBulkRequest 
[26603.stack.zip](https://github.com/Netflix/conductor/files/3854272/26603.stack.zip)
method

Do you have any plans to improve this situation?
Thanks.

Attachment is stack information

**Comment by manan164** [comment]
Hi @manheiba . From the stack trace looks like you are using sync configuration but environment is high throughput. Can you please try enable [async indexing](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/config/Configuration.java#L56)

**Comment by manheiba** [comment]
@manan164 Thank you for your reply. Using "enable async indexing", in a high throughput scenario, asyncindexworkflow and asyncindextask will be discarded after the linkedblockingqueue is full. If asyncindexworkflow is discarded, it cannot be guaranteed that the conductor UI can query this workflow。

```
        this.executorService = new ThreadPoolExecutor(CORE_POOL_SIZE,
            maximumPoolSize,
            KEEP_ALIVE_TIME,
            TimeUnit.MINUTES,
            new LinkedBlockingQueue<>(workerQueueSize),
                (runnable, executor) -> {
                    logger.warn("Request  {} to async dao discarded in executor {}", runnable, executor);
                    Monitors.recordDiscardedIndexingCount("indexQueue");
                });
```

**Comment by manan164** [comment]
Exactly, We have discussed this issue in another thread. You can check https://github.com/Netflix/conductor/issues/1243 I have also opened the PR to demonstrate approach. https://github.com/Netflix/conductor/issues/1243

**Comment by manan164** [comment]
Also, you can try having a higher queue size.

**Comment by apanicker-nflx** [comment]
@manheiba  As @manan164 suggested, we recommend using asynchronous indexing with a higher queue size. An extension to this approach as discussed in #1243 is to introduce a Kafka middle tier to publish indexing operations. A simple consumer with ordering guarantees can then sink these to ES without affecting Conductor latency.
