### ISSUE TITLE
Asynchronous HTTP request

### ISSUE THREAD

**Issue by lydialmr120** [Netflix/conductor#140]
When use HTTP Task to invoke an asynchronous HTTP request, how to keep the task scheduled?
Maybe  I can add simple task or wait task after HTTP task, but they all need callback from HTTP service, and HTTP service doesn't know the task id for the simple task or wait task.
 Is there a better solution?

**Comment by v1r3n** [comment]
@lydialmr120 You can extend the http task to not mark as completed and keep it in progress.  The extended class can override the `execute` method to check if async call is completed and mark the task completed as needed.  We do this for some of our internal async http tasks.
