### ISSUE TITLE
Use redis distributed lock , How  to configure redis password ?

### ISSUE THREAD

**Issue by manheiba** [Netflix/conductor#1402]
Hi, @kishorebanala 

Thank you very much for providing redis distributed lock. What I want to know is to configure redis password there？

Thanks

Here is my configuration
```
#enable locking during workflow execution
workflow.decider.locking.enabled=true
workflow.decider.locking.namespace=conductor
workflow.decider.locking.server=REDIS
workflow.decider.locking.leaseTimeInSeconds=60

#Redis cluster settings for locking module
workflow.redis.locking.server.type=single
#Comma seperated list of server nodes
workflow.redis.locking.server.address=redis://127.0.0.1:6379
```

**Comment by kishorebanala** [comment]
@manheiba Thank you. Here's how the client configuration is set-up, and passwords are not parameterized through configuration: https://github.com/Netflix/conductor/blob/master/redis-lock/src/main/java/com/netflix/conductor/locking/redis/RedisLock.java#L64

I'll try adding that when I get a chance, but if it is blocking you, please go ahead and modify that and/or send us a PR.

**Comment by manheiba** [comment]
@kishorebanala   thanks，I got it!

**Comment by pavelhalabala** [comment]
I need it as well. Pull request submitted here: 
https://github.com/Netflix/conductor/pull/1549

Added new configuration property:
workflow.redis.locking.server.password=xxx
