### ISSUE TITLE
Condutor Server Build failed - Execution failed for task ':conductor-grpc:generateProto'.

### ISSUE THREAD

**Issue by imprabha89** [Netflix/conductor#1403]
Hi  All,

I cloned the netflix conductor to my local & tried to bring the conductor server, but it is fialing with below error.  Please assist.

* What went wrong:
Execution failed for task ':conductor-grpc:generateProto'.
> protoc: stdout: . stderr:
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':conductor-grpc:generateProto'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.

**Comment by smullins3000** [comment]
Did you run it with --info or debug? You can also turn on stack trace as well.

Most likely the problem is that you have to run gradle using jdk 1.8. Running with 1.9 I've seen this issue.

**Comment by NoahLiot** [comment]
Thank you. Should this be documented? In a `README.md` in the gRPC module maybe?

**Comment by apanicker-nflx** [comment]
Thanks for the response @smullins3000.
We will update the README for the gRPC module with this info.
