### ISSUE TITLE
./gradlew build fails (and clean build)

### ISSUE THREAD

**Issue by funston** [Netflix/conductor#1405]
master branch.

> Task :conductor-cassandra-persistence:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conductor-cassandra-persistence:test'.
> Process 'Gradle Test Executor 6' finished with non-zero exit value 1
  This problem might be caused by incorrect test process configuration.
  Please refer to the test execution section in the user guide at https://docs.gradle.org/4.8.1/userguide/java_plugin.html#sec:test_execution

**Comment by apanicker-nflx** [comment]
@funston Can you share more details about the failure? 
Running this command does not produce any errors on our local development environments or on TravisCI. Some more information about your setup would be helpful to better understand the issue.
