### ISSUE TITLE
No UI running prebuilt Jar

### ISSUE THREAD

**Issue by funston** [Netflix/conductor#1406]
Per the docs, running:

% java -jar conductor-server-2.21.0-all.jar

The UI is not running on localhost:5000, only the API on 8080

**Comment by kishorebanala** [comment]
Here's the documentation to run server locally: https://netflix.github.io/conductor/architecture/#installing-and-running, and particularly starting UI server: https://netflix.github.io/conductor/architecture/#start-ui-server. I'll consider adding the UI start docs to Conductor Server page as well.
