### ISSUE TITLE
docker-compose build fails with "conductor-ui" failed to build.

### ISSUE THREAD

**Issue by funston** [Netflix/conductor#1407]
Step 8/11 : RUN cd /app/ui   && npm install   && npm run build --server
 ---> Running in 165f88b71003
npm WARN notice [SECURITY] set-value has the following vulnerability: 1 high. Go here for more details: https://www.npmjs.com/advisories?search=set-value&version=0.4.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN react-dom@15.6.2 requires a peer of react@^15.6.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/union-value/-/union-value-1.0.0.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-20T20_10_10_785Z-debug.log
ERROR: Service 'conductor-ui' failed to build: The command '/bin/sh -c cd /app/ui   && npm install   && npm run build --server' returned a non-zero code: 1

**Comment by mstier-nflx** [comment]
npm ERR! code EAI_AGAIN is a DNS timeout.  I was able to pull the file down from npm registry and confirm the docker file still builds.  Can you elaborate the environment you are building in?
