### ISSUE TITLE
Is there a plan for workflow visual editing?

### ISSUE THREAD

**Issue by manheiba** [Netflix/conductor#1410]
Hi @apanicker-nflx and all，

We recently felt inefficient in defining processes. We want to define workflow visually on the Conductor-UI, Is anyone already working on similar features？

What's your suggestion？

**Comment by apanicker-nflx** [comment]
@manheiba This is one of the features that we would like to add to Conductor to improve usability. As listed [here](https://github.com/Netflix/conductor/wiki/Conductor-Wishlist#usability), these are some of the features that would add great add value to the project. This list is by no means exhaustive, feel free to suggest any other improvements that you would like to be added.

We also welcome and encourage the community to contribute to the project. If this is a feature that you would be willing to contribute, we would greatly appreciate it and I am sure the community would benefit a lot from this too.
