### ISSUE TITLE
Poll for task of a specific workflow instance

### ISSUE THREAD

**Issue by cquon** [Netflix/conductor#142]
There is a scenario that we want to poll tasks only from a specific workflow instance.  For example we have a specific worker responsible for completing a given workflow.  Do you see an issue if "workflowInstanceId" is added as a param to the poll GET requests and after we read from the given "taskType" queue we compare the Task's "workflowInstanceId" with the passed in parameter before returning it as the polled task?

**Comment by v1r3n** [comment]
@cquon in such case, you can use the GET api on the workflow instance Id to receive the workflow execution details, which contains the list of tasks - completed, scheduled and in progress.  Take the task in progress update the status to desired result and do a task update.  That should work.

**Comment by cquon** [comment]
Thanks @v1r3n !
