### ISSUE TITLE
Input parameters do not support lambda expressions

### ISSUE THREAD

**Issue by Hajar1** [Netflix/conductor#1421]
Hi there, 

our team is having lots of unnecessary lambda expressions pre and post workers execution. 
Most of which are checking for null values or exist checks increasing the size of the workflows drastically.

Our first goal, was to do something like this:
```
"inputParameters":{
        "pn": "${ ${w1.output.nb} == null ?  null : \"w1.output.nb\"},
        "http_request": {
                 "uri": "http://someEndPoint/user",
                 "method": "POST",
                 "accept": "application/json",
                 "body": "{ \"username\":  \"w1.output.username\" , \"pn\": $.pn}
        }
 },
```
Q:
1. Is there a way to do what I've attempted to do with `pn` without using lambda workers?
2. If what I am attempting to do is not supported is there a plan of adding feature similar to what I've described in the next release?
3. If this is something that you guys are interested in but don't find super essential. Would you like our team to take it on?

Thank you!

**Comment by apanicker-nflx** [comment]
> 1. Is there a way to do what I've attempted to do with pn without using lambda workers?

Currently, there isn't a way to achieve this without using lambda tasks.

> 2. If what I am attempting to do is not supported is there a plan of adding feature similar to what I've described in the next release?

This is not supported currently, but we feel that this would be a great addition to the project. Unfortunately, we will not be able to work on adding this feature.

> 3. If this is something that you guys are interested in but don't find super essential. Would you like our team to take it on?

We would greatly appreciate it if your team can contribute this feature. I am sure this would benefit other users of Conductor as well.

**Comment by Hajar1** [comment]
Hi @apanicker-nflx,

that's awesome, our team is probably able to handle this! 
We will add it to our backlog whenever we get more info from you.

Here's a list of questions the team had in mind for you.

Q:
1- What is the character sequence of choice to signal embedded JS code. 
     We were thinking `${ JS_code }` 
2-  Our proposed approach would be to add a regex matcher that check at every task in the workflow 
      for un-escaped `${ JS_CODE }`  after variables declaration for that worker and before the worker 
      call kicks off.
     a) What is your input on this approach? 
         if you agree with it, where in the current repo would this change needs to reside. 
         Otherwise, what other approach would you suggest?

Any other guidance you think off will really help us achieve this.

**Comment by apanicker-nflx** [comment]
That is awesome, thanks for your contribution.

>1- What is the character sequence of choice to signal embedded JS code.
We were thinking ${ JS_code }
2- Our proposed approach would be to add a regex matcher that check at every task in the workflow
for un-escaped ${ JS_CODE } after variables declaration for that worker and before the worker
call kicks off.
a) What is your input on this approach?

${ } is a good choice to signal embedded JS. Please note that this character sequence is currently being used to identify JSONPath expressions. [Reference](https://netflix.github.io/conductor/configuration/workflowdef/#wiring-inputs-and-outputs). So this can be extended to support JS code as well while keeping the workflow definition syntax the same.

> if you agree with it, where in the current repo would this change needs to reside.

The class that evaluates parameters is [ParametersUtils](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/ParametersUtils.java). This would be a good reference point for where you could look into adding your JS evaluation.
