### ISSUE TITLE
No delete for workflow

### ISSUE THREAD

**Issue by amoolya19** [Netflix/conductor#144]
Hi,
 why there is no delete for workflow def? i could see for task but not for workflow in metadata management. if i want to delete the definition from metadata, how can i do so? 
Note : using 1.7 version of conductor.

**Comment by v1r3n** [comment]
@amoolya19 we haven't exposed delete yet.  This is something we will address in 1.8

**Comment by nbraquart** [comment]
Hello @v1r3n,

Thanks for the information. You are talking about 1.8, is there any information available regarding the roadmap/versions somewhere? This page https://github.com/Netflix/conductor/wiki/Conductor-Roadmap does not mention the soft delete for instance.

Have a nice day!

**Comment by leonardossz** [comment]
Until is not addressed here is a small workaround:
Make sure the server container is running then:
 
`docker cp <CONTAINER_NAME>:/app/config/config-local.properties .`

Edit the config file and change the `loadSamples` key to `false`.

You have to restart the container but __not__ recreate from image. Use `docker commit` to create a new image with this small change.
