### ISSUE TITLE
Clearer explanation of how ephemeral workflows work

### ISSUE THREAD

**Issue by chard4** [Netflix/conductor#1440]
I've been trying to better understand how Conductor implements its ephemeral workflows. Looking at the source code has been slow going, however, and it is not that clear what the flow is. In particular, `WorkflowExecutor`'s `startWorkflow()` method seems to interact heavily with the various DAOs in both the static and ephemeral cases. It is not clear to me what the difference is between the two cases if the workflow gets written to the executionDAO no matter what. Is this process documented somewhere?

**Comment by apanicker-nflx** [comment]
@chard4 Ephemeral workflows are a pseudonym used for [dynamic workflow executions](https://netflix.github.io/conductor/technicaldetails/#dynamic-workflow-executions). 

What this implies is that the workflow and task definitions in this case need not be registered with Conductor beforehand and can be supplied as part of the start workflow request. In these cases, the workflow and task definitions are not stored within Conductor's metadata store and are always persisted as part of the workflow execution.

**Comment by chard4** [comment]
My confusion stemmed from not understanding the distinction between the MetadataDAO and ExecutionDAO. Thanks!
