### ISSUE TITLE
Conductor loses connection to dynomite and workflow stays in running state forever

### ISSUE THREAD

**Issue by flavioschuindt** [Netflix/conductor#1443]
Hi,

I'm trying to understand some load scenarios in conductor and need some help.

This is my configuration (running in kubernetes):

* Conductor 2.11
* Dynomite (Custom build using the [dockerfile](https://github.com/Netflix/dynomite/blob/dev/docker/Dockerfile) available in dynomite project)
* Redis 3.0

For dynomite, I just removed the installation of redis-server in the container as it externalized (Redis 3.0 above).

This is my configuration for dynomite cluster:

```
dyn_o_mite:
  dyn_listen: 0.0.0.0:8101
  data_store: 0
  listen: 0.0.0.0:8102
  dyn_seed_provider: simple_provider
  servers:
  - redis:6379:1
  tokens: 437425602
  stats_listen: 0.0.0.0:22222
```

Note that this configuration is pretty much similar to the one available in [redis_single.yaml](https://github.com/Netflix/dynomite/blob/dev/conf/redis_single.yml) from the offical dynomite repo.

Yes, I know I should provide at least one more redis, because otherwise is a Single Point of Failure. However, right now, I just wanna understand conductor behavior when it loses connection to dynomite.

So, I've been using this configuration for some time and it has been working fine, since today that I started to see some weird behaviors that I don't know if it is a issue or misconfiguration. I have a workflow that starts ~ 80 HTTP tasks in parallel. At certain point I start to see these entries in conductor logs:

```
216511107 [qtp2004687135-1137] WARN  com.netflix.dyno.jedis.JedisConnectionFactory  - Caught RuntimeException: ERR Storage: Datastore refused connection
216511107 [pool-7-thread-1] WARN  com.netflix.dyno.jedis.JedisConnectionFactory  - Caught RuntimeException: ERR Storage: Datastore refused connection
216511107 [pool-13-thread-1] WARN  com.netflix.dyno.jedis.JedisConnectionFactory  - Caught RuntimeException: ERR Storage: Datastore refused connection
216511107 [pool-11-thread-1] WARN  com.netflix.dyno.jedis.JedisConnectionFactory  - Caught RuntimeException: ERR Storage: Datastore refused connection
216511108 [pool-13-thread-1] WARN  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Received FatalConnectionException; closing connection {port=8102, host=dynomite} to host Host [hostname=dynomite, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null, password=null]
216511108 [qtp2004687135-1137] WARN  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Received FatalConnectionException; closing connection {port=8102, host=dynomite} to host Host [hostname=dynomite, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null, password=null]
216511108 [pool-7-thread-1] WARN  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Received FatalConnectionException; closing connection {port=8102, host=dynomite} to host Host [hostname=dynomite, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null, password=null]
216511108 [pool-11-thread-1] WARN  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Received FatalConnectionException; closing connection {port=8102, host=dynomite} to host Host [hostname=dynomite, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null, password=null]
216511108 [pool-13-thread-1] ERROR com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dynomite, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null, password=null] Unexpected end of stream.
216511108 [pool-7-thread-1] ERROR com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Failed to close connection for host: Host [hostname=dynomite, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null, password=null] Unexpected end of stream.
216511108 [pool-13-thread-1] ERROR com.netflix.conductor.core.execution.WorkflowSweeper  - Error when sweeping workflow
java.lang.RuntimeException: java.lang.RuntimeException: Operation: ( peekIds ) failed on key: [conductor_queues.test.QUEUE._deciderQueue.c ].
	at com.netflix.dyno.queues.redis.RedisDynoQueue.pop(RedisDynoQueue.java:232)
	at com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO.pop(DynoQueueDAO.java:153)
	at com.netflix.conductor.core.execution.WorkflowSweeper.lambda$init$0(WorkflowSweeper.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Operation: ( peekIds ) failed on key: [conductor_queues.test.QUEUE._deciderQueue.c ].
	at com.netflix.dyno.queues.redis.RedisDynoQueue.executeWithRetry(RedisDynoQueue.java:599)
	at com.netflix.dyno.queues.redis.RedisDynoQueue.execute(RedisDynoQueue.java:581)
	at com.netflix.dyno.queues.redis.RedisDynoQueue.peekIds(RedisDynoQueue.java:518)
	at com.netflix.dyno.queues.redis.RedisDynoQueue.prefetchIds(RedisDynoQueue.java:252)
	at com.netflix.dyno.queues.redis.RedisDynoQueue.pop(RedisDynoQueue.java:224)
	... 9 more
```

Readind the logs, looks like the connection to dynomite is lost. After it, I can see some entries in logs that connection is established again:

```
[2019-12-11 16:40:51.388] core_close:419 close <CONN_CLIENT 0x55c7b67989e0 246 from '10.244.0.1:53516'> on event FF00FF eof 0 done 0 rb 88335 sb 6795: Connection reset by peer
[2019-12-11 16:40:51.388] client_unref_internal_try_put:95 <CONN_CLIENT 0x55c7b67989e0 -1 from '10.244.0.1:53516'> unref owner <POOL 0x55c7b64784f0 'dyn_o_mite'>
[2019-12-11 16:41:05.691] proxy_accept:203 <CONN_PROXY 0x55c7b6486380 13 listening on '0.0.0.0:8102'> accepted <CONN_CLIENT 0x55c7b67989e0 15 from '10.244.0.1:40314'>
```

Now, comes my question: If I understood correctly, wouldn't conductor manages it again for me? As soon as I have the connection back again, the workflow should be able to complete the task, but I only see them in Running state forever and workflow never completes.

Also, one more point to add, looks like we have a key on conductor config that configures the max connection allowed per host (```workflow.dynomite.connection.maxConnsPerHost```). When I started to work with conductor this was set by default as ```31``` and with this value I was seeing a lot of these connection failures. I increased it to ```200``` and the connection failures stop at all. Now, as per the above logs, for some workflow executions they started to appear again. Anything I am missing here?

Thank you!

Flávio

**Comment by kishorebanala** [comment]
@flavioschuindt Persistence failures could leave the workflows in inconsistent state. We're working on a recovery mechanism that tries to reverts the workflows to consistent state on transient persistence errors. ETA Q1.

**Comment by flavioschuindt** [comment]
Thanks for replying @kishorebanala. For now, do you know/recommend any workaround? Like I described, I can see that when the load increases, connection from dynomite to redis is lost and I don't see the recovery which is impacting a lot of workflows.

**Comment by kishorebanala** [comment]
@flavioschuindt I don't think there is any other clean workaround that preserves the workflow consistency on persistence failures. Consider using Redis based locking solution we've recently introduced to minimize the impact, as the number of decides in parallel could make it worse. This along with the recovery mechanism I've mentioned before would be the best bet near term. In the long run, we're considering stronger consistency guarantees.

Also, reach out to Dynomite / Dyno-queues owners regarding the performance at load and minimizing the connection issues.
