### ISSUE TITLE
UI Regression on searching

### ISSUE THREAD

**Issue by demichej** [Netflix/conductor#1445]
We just upgraded to 2.22.3, and it looks like there's a bug/regression in the UI. It used to be that when you clicked any of the sidebar links (All, Running, Completed, etc). It would issue a "search" automatically and populate the table. 

However, it appears that the auto-Search of whatever item you select on the sidebar doesn't kick off a search. You now have to click the actual "Search" button to search.

**Comment by ml-** [comment]
Can reproduce. Browser console shows errors as well.

**Comment by demichej** [comment]
@ml- what are the JS errors you see? I see Warnings, but I don't see errors necessarily.

**Comment by ml-** [comment]
@demichej Sorry, I'm at home now and post the errors (or warnings?) monday the earliest. Or maybe I can so a quick build locally, we'll see.

Will make sure I don't forget this!

**Comment by ml-** [comment]
You're right @demichej, those messages are **Warnings**:
```
Warning: Failed propType: Invalid prop `allowNew` of type `string` supplied to `Typeahead`, expected `boolean`. Check the render method of `OnClickOutside(Typeahead)`. app.js:7:4674
Warning: Failed propType: Invalid prop `search.version` of type `array` supplied to `t`, expected `string`. Check the render method of `Connect(t)`. app.js:7:4674
```

**Comment by demichej** [comment]
Right, but those are just warning @ml- 

I haven't had a chance to debug locally, but would to try and figure out a fix :)

**Comment by demichej** [comment]
@ml- Looks like this commit made that change:
https://github.com/Netflix/conductor/commit/2cf4f0413f452e4f9549726a3571c336bec83ee5#diff-03e4bf1f523c6bb8e97e4eef067cce3f

I'll reach out to @mstier-nflx to see if we can either revert it, or get a fix in so that we fetch.

**Comment by demichej** [comment]
@ml- made a PR for this:
https://github.com/Netflix/conductor/pull/1447

**Comment by ml-** [comment]
@demichej Cool, thanks. Will check out later. Hope it gets merged

**Comment by demichej** [comment]
Sorry, my previous PR was in a bad state. This is the right PR now: https://github.com/Netflix/conductor/pull/1451

**Comment by apanicker-nflx** [comment]
@demichej @ml- Thank you for reporting the issue. We will review the PRs and merge these soon. 
@mstier-nflx for visibility.

**Comment by ml-** [comment]
I guess this can be closed?
https://github.com/Netflix/conductor/pull/1451#issuecomment-575028395
