### ISSUE TITLE
SCHEDULED tasks never being provided to polling workers

### ISSUE THREAD

**Issue by indiv0** [Netflix/conductor#1446]
* Conductor version: `v2.14.0`
* Persistence configuration: single-instance Redis

We have a task that has a `concurrent_execution_limit` of 1. We queued up 5000 workflows nearly simultaneously, each of which ran that task. Processing went normally for the first ~1150 workflows. Then, Conductor continued processing the remaining workflows, but would get stuck on that concurrently-limited task. All remaining (~3850) workflows have that task in the `SCHEDULED` state. Conductor is continuously printing for each of the tasks:

```
Task execution count limited. task - <TASK_ID>:<TASK_DEF_NAME>, limit: 1, current: 0"
```

Looking at the queue for that task, we see the number of tasks getting decremented as the tasks are added to the `TASK_LIMIT_BUCKET`. Eventually the sweeper puts those tasks back into the queue.

No task of this type ever leaves the `SCHEDULED` state once it's stuck like this. Manually clearing the `TASK_LIMIT_BUCKET` (`DEL conductor:conductor.TASK_LIMIT_BUCKET.<TASK_DEF_NAME>`) allows for some processing to happen, but it gets stuck again after ~30 workflows.

We can see that tasks are regularly being removed from the `TASK_LIMIT_BUCKET` (by checking with `PSUBSCRIBE __keyspace@0__:conductor:conductor.TASK_LIMIT_BUCKET.<TASK_DEF_NAME>`), because we can see `zrem` commands. From our understanding of the code flow, this should only happen in one of three cases for task instance A:
1. When task instance A is updated (`RedisExecutionDAO::updateTask`)
2. When task instance B is being limited and task instance A is `IN_PROGRESS` (`RedisExecutionDAO::exceedsInProgressLimit`)
3. When task instance A is removed (`RedisExecutionDAO::removeTask`)
None of these appear to be the case for us since no tasks are leaving the `SCHEDULED` state and we're not updating the tasks manually.

We're not certain whether we're misunderstanding the flow or this is a bug in Conductor's rate limiting functionality. Any assistance would be greatly appreciated.

P.S. if someone with appropriate understanding is reading this, could you explain the difference between the `TASKS_IN_PROGRESS_STATUS` and `IN_PROGRESS_TASKS` lists?

**Comment by apanicker-nflx** [comment]
@indiv0 Seems like this could be something related to Redis. Since clearing the key manually fixes the issue but resurfaces after a while, I believe this is not caused by application (Conductor) code.
