### ISSUE TITLE
Health check prior to http system task requests

### ISSUE THREAD

**Issue by Hajar1** [Netflix/conductor#1448]
Hello there,

We are trying to expand on the functionalities of the http system tasks and specifically for one particular disadvantage of http system task.

What we noticed is that if one micro Service is down or not able to respond to the system task then the task would fail. We are wondering if there is a way for us to check the health of an endpoint prior to doing the http request to it. This way a task would stay waiting until the health check of the endpoint is satisfied

Thank you!

**Comment by apanicker-nflx** [comment]
@Hajar1 You should be able to expand on this functionality by extending the Http system task and building your custom system task which performs the healthcheck prior to making the http request. You can then register this custom system task in your Conductor deployment.
