### ISSUE TITLE
How to improve task pull performance

### ISSUE THREAD

**Issue by 0532** [Netflix/conductor#1452]
my client config:
```
config.jd.conductor.url=http://conductor/api/
#client executorService threadCount
config.jd.conductor.thread=200
#clinet executorService threadQueueSize
config.jd.conductor.queue.size=1000
conductor.worker.longPollTimeout=100
conductor.worker.pollInterval=500
```
server : 8servers 4c8g
client : 4servers  4c8g

1,And is there any way to increase the pull speed
![image](https://user-images.githubusercontent.com/5317048/70958501-693c8f00-20b4-11ea-99c8-e53b5612ab8c.png)

2,Time spent per pull, What factors can affect this pull time
￼
![image](https://user-images.githubusercontent.com/5317048/70961997-88d8b500-20be-11ea-874a-70e4f0457689.png)
![image](https://user-images.githubusercontent.com/5317048/70962005-90985980-20be-11ea-8bba-c7c30108d853.png)
![image](https://user-images.githubusercontent.com/5317048/70962015-95f5a400-20be-11ea-8edc-450f56267239.png)
![image](https://user-images.githubusercontent.com/5317048/70962018-9a21c180-20be-11ea-8799-1eb3c27dc19f.png)
![image](https://user-images.githubusercontent.com/5317048/70962026-9e4ddf00-20be-11ea-88d8-c4c7c8692c5c.png)

￼￼
Thanks for any reply  @kishorebanala

**Comment by kishorebanala** [comment]
@0532 Task poll performance is reliant on several factors like queue size, number of threads polling for that queue, queuing system performance etc. We don't have metrics on the throughput of queues for Dyno-queues, but it is possible to load test and obtain optimal number of workers, threads, queue sizes etc. for your given set-up.

**Comment by 0532** [comment]
Thank you very much for your reply, Merry Christmas
