### ISSUE TITLE
Can conductor match machine learning train scene?

### ISSUE THREAD

**Issue by stayHF** [Netflix/conductor#1461]
Is the Conductor can be applied to machine learning model training tasks? the training time may be relatively long, such as more than 10 hours, and task scheduling may need to be customized according to the number of CPU cores or GPU cards. and which load balancer can impletment the customize schedule rule easily ?

**Comment by apanicker-nflx** [comment]
@stayHF Conductor can handle tasks within a workflow which can execute for a really long time. 

> task scheduling may need to be customized according to the number of CPU cores or GPU cards. and which load balancer can impletment the customize schedule rule easily ?

Conductor does not schedule tasks to be implemented within specific worker instances. Rather workers poll Conductor for tasks, so if you have different task types each of which use different resources, you may be able to model your workflow accordingly. Please refer to the [documentation](https://netflix.github.io/conductor/) to learn more about modeling workflows.
