### ISSUE TITLE
timeoutSeconds of 0 for WAIT tasks does not seem to be honored

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1472]
From our experience, if a WAIT task has a task metadata definition with a timeoutSeconds of 0, the responseTimeoutSeconds is used instead, so the WAIT task times out in the responseTimeoutSeconds setting. According to the documentation a timeoutSeconds of 0 means the task will not time out.

Is this expected? I know that having no metadata definition for the task will cause it to not timeout. Is that our only option?

**Comment by rickfish** [comment]
Additional information: During the sweep operation, DeciderService.decide() is called. In it, it first calls checkForTimeout(). In that method, if timeoutSeconds is <= 0 it will return. That is good but right after that it calls isResponseTimedOut() and it will time out the task. Shouldn't either checkforTimeout return a true/false so it can be used to determine whether or not to call isResponseTimedOut or in isResponseTimedOut() check for timeoutSeconds <=0?

**Comment by apanicker-nflx** [comment]
@rickfish Thats a good observation.
The usage and need of `timeoutSeconds` and `responseTimeoutSeconds` is very different and indeed crucial to workflow execution. Please refer the [documentation](https://netflix.github.io/conductor/tasklifecycle/#timeout-seconds) to see the differences.

>According to the documentation a timeoutSeconds of 0 means the task will not time out. Is this expected? 

This is correct.

> I know that having no metadata definition for the task will cause it to not timeout. Is that our only option?

I am curious as to why you would need a metadata definition for a WAIT task if you do not intend to set timeouts on it.

Having said that though, we will re-consider the evaluation of timeouts of system tasks in similar scenarios.

**Comment by rickfish** [comment]
I agree that it is not necessary to have a task metadata def on a WAIT task. Unfortunately there are several teams at our company that use our shared Conductor servers and they mainly go by the documentation. Some have gone to production without realizing that their WAIT tasks have timed out and we as the team that maintains our Conductor servers have to remediate when that happens.

We are working on getting the organization to allow us to contribute back. Once that happens we will be able to be a good player and propose solutions rather than just posting issues. 

Thanks for considering this.

**Comment by apanicker-nflx** [comment]
@rickfish As maintainers of Conductor servers used by several teams, we can relate your experience. 
For the time being, till we have a fix for this issue, you would need to unregister the wait task definitions to prevent them from being timed out.

>We are working on getting the organization to allow us to contribute back. Once that happens we will be able to be a good player and propose solutions rather than just posting issues.

This is great and we would appreciate the contribution. We are really grateful to all the users and contributors who help us make Conductor a better product. We look forward to your contribution.
