### ISSUE TITLE
Server doesn't come up when one of the dynomite node is unreachable

### ISSUE THREAD

**Issue by manjurad** [Netflix/conductor#1473]
I have a setup with one instance of conductor server and 3 dynomite nodes. If I make one of the node as unreachable, then conductor server doesn't come up. Is it a requirement that all dynomite nodes in the configuration should be reachable for the server to come up? The server logs indicate that it keeps trying to prime connection to all 3 nodes, and one of them fails.

**Comment by apanicker-nflx** [comment]
During the server initialization, all dynomite nodes should be available.

**Comment by manjurad** [comment]
Thanks for confirming.
