### ISSUE TITLE
jsondsl with dag not tree

### ISSUE THREAD

**Issue by wangsan** [Netflix/conductor#1476]
dag like this
task: a b c d e
links: a-d b-d b-e c-e
looks like 

> a-d
>   /
> b
>  \\
> c-e

how can I define this dag via jsondsl?

**Comment by kishorebanala** [comment]
@wangsan Not sure if we understood your requirements from the description, but Conductor doesn't support graph like connections between tasks. I.e from your example, task 'd' cannot be connect to both 'a' and 'b' outside of decision, fork-join etc. building blocks. Consider checking of the types of system tasks available [here](https://netflix.github.io/conductor/configuration/systask/) and see if you can best construct your task structure using them.

**Comment by wangsan** [comment]
![image](https://user-images.githubusercontent.com/1916361/72031452-6bff5e00-32c7-11ea-8f85-c44d09cfef89.png)

I mean b will be used in two or more fork-join. fork (a,b) join and d, fork (b,c) join and e.

**Comment by kishorebanala** [comment]
Conductor tasks are not graphs per se. But, both tasks d & e can definitely get inputs from task b's output. You just have to order your task execution DAG in such a way. One possibility is to execute all the tasks linearly (you can optimize this however).. eg: [a,b,c,d,e], and then tasks d,e would refer to task b's outputs, and will only be executed after task b.
