### ISSUE TITLE
Lambda after loop - stuck execution

### ISSUE THREAD

**Issue by Valarin** [Netflix/conductor#1478]
Execution of this WF never finishes

`{
  "name": "stuck_execution",
  "description": "Lambda after loop - stuck execution",
  "version": 1,
  "schemaVersion": 2,
  "tasks": [
    {
      "name": "LoopTask",
      "taskReferenceName": "LoopTask",
      "type": "DO_WHILE",
      "loopCondition": "($.LoopTask['iteration'] < 2)",
      "loopOver": [
        {
          "name": "LAMBDA_TASK",
          "taskReferenceName": "result_lambda_ref",
          "type": "LAMBDA",
          "inputParameters": {
            "scriptExpression": "return { status: 'STH' };"
          }
        }
      ],
      "startDelay": 0,
      "optional": false
    },
    {
      "name": "LAMBDA_TASK",
      "taskReferenceName": "result_lambda_ref",
      "type": "LAMBDA",
      "inputParameters": {
        "scriptExpression": "return { status: 'Executed' };"
      }
    }
  ]
}
`

![Screenshot from 2020-01-07 10-47-40](https://user-images.githubusercontent.com/11278978/71885737-3c234f80-313b-11ea-8bac-af14b1b2457a.png)

Lambda task that is supposed to run after loop never gets executed and is somehow partially treated as if it was inside the loop.

**Comment by manan164** [comment]
Hi @Valarin 
Thanks for pointing out. I am working on a fix. Basically it is treating next task as loopOver task. 
I will raise PR in some time.

**Comment by manan164** [comment]
Hi @Valarin ,
I have created a PR https://github.com/Netflix/conductor/pull/1479
Please pull this branch till the time.
Also ideally we should not use the loopover task outside the scope of DO_WHILE task as it can hamper the Loop task operation.
