### ISSUE TITLE
Elasticache configuration

### ISSUE THREAD

**Issue by albertldlan** [Netflix/conductor#1483]
I have a question about Elasticache Redis configuration. There is some differing documentation in https://netflix.github.io/conductor/server/#configuration-parameters and https://netflix.github.io/conductor/server/#using-standalone-redis-elasticache regarding the properties needed for Elasticache configuration - namely, the `db` value. The above indicates that for Elasticache Redis in cluster mode the value of `db` should be `redis_cluster` but in the second link the value of `db=redis`. Would we use `db=redis` in the case of a Elasticache instance NOT in cluster mode? And `db=redis_cluster` for Elasticache in cluster mode?

Also, for the Elasticache (cluster mode enabled) case, is the `EC2_AVAILABILITY_ZONE` variable required? In the case of a multi-node cluster with multiple AZ's, which one should be the required value? The same question applies to the `workflow.dynomite.cluster.hosts` value - am I correct that it's `${configuration_endpoint}:${port}:${THIS_VALUE_DOESNT_MATTER}` for Elasticache? That is, the AZ value doesn't matter, but some dummy value needs to be included?

Thanks!

**Comment by kishorebanala** [comment]
I haven't tried setting up Conductor with Elasticache cluster myself, but if Elasticache is configured in cluster mode, then `db=redis_cluster` should work. Also, Yes, the AZ value shouldn't matter for Elasticache.
