### ISSUE TITLE
Issues with docker images

### ISSUE THREAD

**Issue by KashyapKunal** [Netflix/conductor#1486]
I am having issues building conductor:server and conductor:ui using docker-compose/ dockerfile. 

Conductor:ui issues:
Building conductor-server
Step 1/16 : FROM openjdk:8-jdk AS builder
 ---> f8146facf376
Step 2/16 : MAINTAINER Netflix OSS <conductor@netflix.com>
 ---> Using cache
 ---> 80324909f12c
Step 3/16 : COPY . /conductor
 ---> Using cache
 ---> bc36ff4d2502
Step 4/16 : WORKDIR /conductor
 ---> Using cache
 ---> 237bab98bd40
Step 5/16 : RUN ./gradlew build -x test
 ---> Running in f4ee060ecb7e
/usr/bin/env: ‘sh\r’: No such file or directory
ERROR: Service 'conductor-server' failed to build: The command '/bin/sh -c ./gradlew build -x test' returned a non-zero code: 127

Conductor:ui issues:
Sending build context to Docker daemon   5.12kB
Step 1/11 : FROM node:9-alpine
 ---> a56170f59699
Step 2/11 : MAINTAINER Netflix OSS <conductor@netflix.com>
 ---> Using cache
 ---> 6058aa5b75b1
Step 3/11 : RUN apk update && apk add   autoconf   automake   libtool   build-base   libstdc++   gcc   abuild   binutils   nasm   libpng   libpng-dev   libjpeg-turbo   libjpeg-turbo-dev   python
 ---> Using cache
 ---> 65b827fc5dea
Step 4/11 : RUN mkdir -p /app/ui
 ---> Using cache
 ---> db909ba3553f
Step 5/11 : COPY ./docker/ui/bin /app
COPY failed: stat /var/lib/docker/tmp/docker-builder106287803/docker/ui/bin: no such file or directory

**Comment by demichej** [comment]
This looks more like an environment issue than a conductor issue:

/usr/bin/env: ‘sh\r’: No such file or directory
