### ISSUE TITLE
http task output

### ISSUE THREAD

**Issue by amoolya19** [Netflix/conductor#149]
Hi,
I was trying a simple hello world example. but i was not able to figure out how to configure the output of the microservices in workflow json. example my wf has only 1 task which will call hello world. this would return a json. 
Also i was wondering on how to have the inputs mapped to the task and microservices other than sending params through uri.

**Comment by v1r3n** [comment]
@amoolya19 do you want to do an HTTP POST with request body?  Take a look at the documentation for http task:
https://netflix.github.io/conductor/metadata/systask/#http

**Comment by amoolya19** [comment]
Hi @v1r3n ,

i tried to a scenario where output of task1 (HTTP type) is input of task2 (type HTTP). i tried to place input of task1 in body tag for task2. but task2 fails and output json has null in the body.

worflow json
`[{
	"name": "test_workflow",
	"description": "test http workflow",
	"version": 1,
	"tasks": [{
		"name": "test_task1",
		"taskReferenceName": "tt0",
		"inputParameters": {
			"http_request": {
				"uri": "http://localhost:8081/2",
				"method": "GET"
			}
		},
		"type": "HTTP"
	},
	
	{
		"name": "test_task1",
		"taskReferenceName": "tt1",
		"inputParameters": {
			"http_request": {
				"uri": "http://localhost:8081/tt1",
				"method": "GET",
				"body" : "${tt0.output.number}"
			}
		},
		"type": "HTTP"
	}
	]
	
	"schemaVersion": 2
}]`

output json for task 2
 {
         "taskType": "HTTP",
         "status": "FAILED",
         "inputData": {
            "http_request": {
               "uri": "http://localhost:8081/tt1",
               "method": "GET",
               **"body": null**
            }
         },

am i missing anything here?

**Comment by amoolya19** [comment]
@v1r3n 

i also tried with simpler version for workflow where there is only 1 task which is of type http and tried to output the response like 
"outputParameters": {
    "number": "${test_task1.output.number}"
  } and after execution, still the output was null for number. is there any other configuration that needs to be done?

**Comment by v1r3n** [comment]
@amoolya19 the output of the HTTP task is contained in the `response` field of the output of the task.
In your original workflow example, the configuration you have supplied for the second task is:
```
"body" : "${tt0.output.number}"
```
If you look at the output of the HTTP task, the `number` is located at`response.body.number`.
You have to use the JSON Path of the field from the `outputData` parameter to inject the value in another task.

Try modifying the parameter config for `tt1` task, as follows:
```
"body" : "${tt0.output.response.body.number}"
```
OR below should also work, as it is a valid JSON Path.
```
"body" : "${tt0.output..number}"
```

**Comment by amoolya19** [comment]
@v1r3n,

this worked. actually i had tried this yesterday but not sure why it dint work that time.Any ways thank you for the reply.

**Comment by sudvarma** [comment]
I am facing the same issue - not able to extract value from JSON

Both ${tt0.output.response.body.number} and "${tt0.output..number}" returns null.

where as ${tt0.output.*} returns the whole string. But ${tt0.output.response*} returns null. Any pointers would help.

**Comment by sudvarma** [comment]
@v1r3n

Any pointers would help. Thanks

**Comment by sudvarma** [comment]
May be I'm missing out on this oint.

One more thing, outputParameters cannot be configured as part of workflow definition, as it is created/updated as the tasks are getting executed.

How else to configure output parameters?

**Comment by sudvarma** [comment]
It is working, i was using an old server jar.
