### ISSUE TITLE
HTTP Task Connection Refused 

### ISSUE THREAD

**Issue by IamManifold** [Netflix/conductor#1496]
starting to dig into the system tasks with conductor and i'm at a point where the server is processing my task but i'm receiving an error and just looking for some direction on where to go from here.  I've tried changing the url to other servers but getting the same result. 

Failed to invoke http task due to: com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused)

`{
   "ownerApp": "",
   "createTime": 1579038713878,
   "updateTime": 1579038714474,
   "status": "FAILED",
   "endTime": 1579038714474,
   "workflowId": "33a4027d-5f14-4a86-b8f5-4f996827c915",
   "tasks": [
      {
         "taskType": "HTTP",
         "status": "FAILED",
         "inputData": {
            "http_request": {
               "uri": "http://localhost:5000/updatetask/dc475886-c378-4774-b683-3f4e04b3987d/f65a87ab-dc84-428d-ac01-ef8f97a13869",
               "method": "GET"
            },
            "asyncComplete": false
         },
         "referenceTaskName": "CalltoNODE",
         "retryCount": 0,
         "seq": 1,
         "pollCount": 1,
         "taskDefName": "httpcall",
         "scheduledTime": 1579038713892,
         "startTime": 1579038714361,
         "endTime": 1579038714439,
         "updateTime": 1579038714363,
         "startDelayInSeconds": 0,
         "retried": false,
         "executed": false,
         "callbackFromWorker": true,
         "responseTimeoutSeconds": 0,
         "workflowInstanceId": "33a4027d-5f14-4a86-b8f5-4f996827c915",
         "workflowType": "httpcallwf",
         "taskId": "d44d21cf-742c-48a0-b6e0-c134edaa5455",
         "reasonForIncompletion": "Failed to invoke http task due to: com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused)",
         "callbackAfterSeconds": 0,
         "workerId": "57f2046a3afd",
         "outputData": {
            "response": "com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused)"
         },
         "workflowTask": {
            "name": "httpcall",
            "taskReferenceName": "CalltoNODE",
            "inputParameters": {
               "http_request": {
                  "uri": "http://localhost:5000/updatetask/dc475886-c378-4774-b683-3f4e04b3987d/f65a87ab-dc84-428d-ac01-ef8f97a13869",
                  "method": "GET"
               },
               "asyncComplete": false
            },
            "type": "HTTP",
            "decisionCases": {},
            "defaultCase": [],
            "forkTasks": [],
            "startDelay": 0,
            "joinOn": [],
            "optional": false,
            "taskDefinition": {
               "createTime": 1579038178933,
               "createdBy": "",
               "name": "httpcall",
               "description": "testing_timeout",
               "retryCount": 0,
               "timeoutSeconds": 15,
               "inputKeys": [],
               "outputKeys": [],
               "timeoutPolicy": "RETRY",
               "retryLogic": "FIXED",
               "retryDelaySeconds": 0,
               "responseTimeoutSeconds": 10,
               "concurrentExecLimit": 0,
               "inputTemplate": {},
               "rateLimitPerFrequency": 0,
               "rateLimitFrequencyInSeconds": 0
            },
            "defaultExclusiveJoinTask": [],
            "asyncComplete": false,
            "loopOver": []
         },
         "rateLimitPerFrequency": 0,
         "rateLimitFrequencyInSeconds": 0,
         "workflowPriority": 0,
         "iteration": 0,
         "taskDefinition": {
            "present": true
         },
         "loopOverTask": false,
         "queueWaitTime": 469,
         "taskStatus": "FAILED",
         "logs": []
      }
   ],
   "input": {},
   "output": {
      "response": "com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused)"
   },
   "workflowType": "httpcallwf",
   "version": 1,
   "reasonForIncompletion": "Failed to invoke http task due to: com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused (Connection refused)",
   "schemaVersion": 2,
   "taskToDomain": {},
   "failedReferenceTaskNames": [
      "CalltoNODE"
   ],
   "workflowDefinition": {
      "createTime": 1579038353639,
      "name": "httpcallwf",
      "description": "triggers call to node api",
      "version": 1,
      "tasks": [
         {
            "name": "httpcall",
            "taskReferenceName": "CalltoNODE",
            "inputParameters": {
               "http_request": {
                  "uri": "http://localhost:5000/updatetask/dc475886-c378-4774-b683-3f4e04b3987d/f65a87ab-dc84-428d-ac01-ef8f97a13869",
                  "method": "GET"
               },
               "asyncComplete": false
            },
            "type": "HTTP",
            "decisionCases": {},
            "defaultCase": [],
            "forkTasks": [],
            "startDelay": 0,
            "joinOn": [],
            "optional": false,
            "taskDefinition": {
               "createTime": 1579038178933,
               "createdBy": "",
               "name": "httpcall",
               "description": "testing_timeout",
               "retryCount": 0,
               "timeoutSeconds": 15,
               "inputKeys": [],
               "outputKeys": [],
               "timeoutPolicy": "RETRY",
               "retryLogic": "FIXED",
               "retryDelaySeconds": 0,
               "responseTimeoutSeconds": 10,
               "concurrentExecLimit": 0,
               "inputTemplate": {},
               "rateLimitPerFrequency": 0,
               "rateLimitFrequencyInSeconds": 0
            },
            "defaultExclusiveJoinTask": [],
            "asyncComplete": false,
            "loopOver": []
         }
      ],
      "inputParameters": [],
      "outputParameters": {},
      "schemaVersion": 2,
      "restartable": false,
      "workflowStatusListenerEnabled": false
   },
   "priority": 0,
   "startTime": 1579038713878,
   "workflowName": "httpcallwf",
   "workflowVersion": 1
}`

**Comment by apanicker-nflx** [comment]
Please post the stack trace from the error, this should be printed out in the logs. Also, make sure that you have an active server running on your localhost at port 5000 to which you are making the request to.
