### ISSUE TITLE
Bintray jcenter -> Maven Central synchronization broken

### ISSUE THREAD

**Issue by Valarin** [Netflix/conductor#1497]
Bintray jcenter contains the newest version available (2.22.6-alpha - lower minor number but released after 2.24.2) - https://bintray.com/netflixoss/maven/conductor/2.22.6-alpha
Latest version avaiable on Maven central version is 2.24.0 (2.24.2 is missing) - https://search.maven.org/search?q=g:com.netflix.conductor

Could this be fixed? Thanks!

**Comment by apanicker-nflx** [comment]
Thanks for bringing this to our attention, we will look into fixing this soon.

**Comment by Valarin** [comment]
@apanicker-nflx any news on this one? Thanks!

**Comment by mdepak** [comment]
@apanicker-nflx  Can you help fix this problem as we need the latest versions for our deployments? Thanks!

**Comment by apanicker-nflx** [comment]
Apologies for the delays, we will get back with an update on this soon.

**Comment by Valarin** [comment]
FYI it seems synchro work for alpha releases, but not the standard ones.

**Comment by apanicker-nflx** [comment]
@Valarin @mdepak We are still trying to figure out why maven publishing is broken. 
As a temporary relief, you can use `v2.24.5-alpha.2` which is available in maven and is the same as `v2.24.5`

**Comment by apanicker-nflx** [comment]
Also, `v2.24.5` is available on maven - https://mvnrepository.com/artifact/com.netflix.conductor/conductor-core/2.24.5

**Comment by mdepak** [comment]
@apanicker-nflx Thank you for publishing the latest version in maven.
