### ISSUE TITLE
failureWorkflow does not have taskToDomain

### ISSUE THREAD

**Issue by banduo** [Netflix/conductor#1498]
Hi I noticed when failureWorkflow is started, it takes null as the taskToDomain, is there any reason it does not use the same domain as the failed workflow? https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L740
All our workers have been configured to pull from specific domains and it leaves the failure workflow untended.

**Comment by kishorebanala** [comment]
Hey @banduo, Thanks for pointing this out. Please feel free to submit a proposal with a fix for this, that could lead to PR.
