### ISSUE TITLE
When task status is changed to CANCELED, it doesn't appear that ElasticSearch is updated

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1499]
We have noticed that when task status changes to CANCELED, the ElasticSearch document does not appear to be updated as IndexDAO.indexTask() does not seem to get invoked. Is this intentional? I haven't been able to isolate the code yet. This causes the tasks to come back on a search for their previous status and it is messing us up.

**Comment by rickfish** [comment]
More information in the context of an example: When a workflow has a fork task containing two tasks and both tasks are SCHEDULED, the tasks when set to SCHEDULED status never get written to Elastic Search. That is fine. I am sure that is intentional.

But when one of those task's status gets changed to FAILED_WITH_TERMINAL_ERROR, that task is written to ES with that status and the other task is then written to ES with its current SCHEDULED status. After that update takes place, the task that was still SCHEDULED gets updated in the database with CANCELED status but that task with that status never gets written to ES.

Should indexDao.indexTask be invoked when the status changes to CANCELED or will that cause other unforeseen problems?

**Comment by apanicker-nflx** [comment]
@rickfish Thanks for reporting the issue and digging into this. Ideally, the task should get updated with CANCELLED status in ES. We will look into having a fix out for this issue soon, in the meantime, please feel free to contribute a fix :).

**Comment by rickfish** [comment]
Sorry, I am still working on getting my customer/organization to allow me to contribute back. Since they consider it their proprietary code even though this is an OpenSource project, the lawyers are creating a roadblock. If I contribute on my own, that could cause issues since I am a contractor there and they could say I have taken code from the office onto my personal computer. I have been told we should be able to get permission to contribute back shortly but it still is not in place. Bureaucracy sucks.

**Comment by apanicker-nflx** [comment]
Ha, true. We really appreciate your help and will look into fixing this soon. Hopefully, you can get the permissions sorted out quickly 👍

**Comment by rickfish** [comment]
I can now contribute. I can take this if you want. You will have to bare with me as this would be my first contribution. I will follow the guidelines but I might need some handholding.

**Comment by rickfish** [comment]
I created pull request #1519 for this issue
