### ISSUE TITLE
Conductor and Eureka

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#15]
Is there support to register the Conductor backend service with Eureka?
Is there also support for multiple running Conductor backend service instances to build a high available cluster?

It would nice so that workers can discover Conductor instances via Eureka and do load-balancing.

At least in the client code, I could find some hint conc. usage of a Eureka Client here:

`client/src/main/java/com/netflix/conductor/client/task/WorkflowTaskCoordinator.java`

Thanks a lot.

**Comment by v1r3n** [comment]
WorkflowTaskCoordinator currently utilizes Eureka to check the instance status and stops polling when not active.

For the Conductor services - the Eureka registration is left up to the deployment model (at the moment) as the only artifacts we publish are Jar files which still needs to be packed into a war file or executable.
