### ISSUE TITLE
Ui and server in different servers

### ISSUE THREAD

**Issue by amoolya19** [Netflix/conductor#150]
is it possible to have server and UI in different system? when i just start the ui without starting the server i get message which means something like the server is not up(localhost :8080 not up). so is there a way  to configure ui for server running different ip? Also is there a way to config port of server other than 8080?

**Comment by v1r3n** [comment]
Yes, before you start the server, make sure to export `WF_SERVER` environment variable with location to the server.

e.g.

```
#make sure the wf_server ends with a "/"
export WF_SERVER=http://host:port/api/
#start the UI server now
```

**Comment by amoolya19** [comment]
Hi @v1r3n,

I am not using docker image. so is it "conductor/ui/gulpfile.babel.js" you are referring to? 

var wf_server = process.env.WF_SERVER || 'http://localhost:8080/api/';

**Comment by v1r3n** [comment]
@amoolya19 even if you do not use docker image, the WF_SERVER variable will work.  the line you pasted from gulpfile does exactly the same.

**Comment by amoolya19** [comment]
@v1r3n ,
Thank you Viren. i would try this when our server is ready. would reopen this if i face any hurdles.

**Comment by vijchint** [comment]
@v1r3n Can we config the port of server to other than 8080?
