### ISSUE TITLE
Readme page with indication for external tools

### ISSUE THREAD

**Issue by flaviostutz** [Netflix/conductor#1500]
I've created some tools based on Netflix Conductor to help on CRON like tasks or Backup management jobs.

* [Schellar](https://github.com/flaviostutz/schellar) is a scheduler tool for instantiating Conductor workflows from time to time
* [Backtor](https://github.com/flaviostutz/backtor) is a backup scheduler tool that uses Conductor workers to handle backup operations)

Do you think it is worth we create a link on the main README page to a page with "external" contribution" links? I've found it a bit hard to find this kind of tools over the Internet.

**Comment by kishorebanala** [comment]
@flaviostutz These look awesome. We'll definitely consider adding pointers in Conductor documentation. Thanks for your contributions.

**Comment by flaviostutz** [comment]
Great!
Please check PR https://github.com/Netflix/conductor/pull/1508
