### ISSUE TITLE
/tasks/{taskId}/ack always return false

### ISSUE THREAD

**Issue by balloonio** [Netflix/conductor#1501]
I'm following the add-idents developer lab [here](https://netflix.github.io/conductor/labs/beginner/#ack-the-task) and I don't seem to get the ack task step working.

**Question 1** - call to `/tasks/{taskId}/ack` with correct task id always returns `false`. Why?
**Question 2** - (probably because I always get `false` as the response) I don't see any changes or effect on Workflow UI being reflected. Is that expected?
**Question 3** - What does this ack step do exactly? I ended up just skipping this step entirely and the workflow worked fine. The task just changes from SCHEDULED to IN_PROGRESS after polling, and from IN_PROGRESS to COMPLETED after the mocked worker return response. Therefore, I'm confused if the ack call in the middle does anything at all.

For example, here is my response from task polling in [this step](https://netflix.github.io/conductor/labs/beginner/#poll-for-worker-task)
```
{
    "taskType": "add_idents",
    "status": "IN_PROGRESS",
    "inputData": {
        "identType": "animation",
        "contentId": "my_unique_content_id"
    },
    "referenceTaskName": "add_idents_by_type",
    "retryCount": 0,
    "seq": 3,
    "pollCount": 1,
    "taskDefName": "add_idents",
    "scheduledTime": 1579564011353,
    "startTime": 1579564721830,
    "endTime": 0,
    "updateTime": 1579564721830,
    "startDelayInSeconds": 0,
    "retried": false,
    "executed": false,
    "callbackFromWorker": true,
    "responseTimeoutSeconds": 180,
    "workflowInstanceId": "eaa3f523-9f0d-4426-b3f8-36d45a5d78cf",
    "workflowType": "add_netflix_identation",
    "taskId": "8452fcf4-f016-4da3-96a2-ea797068af4e",
    "callbackAfterSeconds": 0,
    "outputData": {},
    "workflowTask": {
        "name": "add_idents",
        "taskReferenceName": "add_idents_by_type",
        "inputParameters": {
            "identType": "${workflow.input.identType}",
            "contentId": "${workflow.input.contentId}"
        },
        "type": "SIMPLE",
        "decisionCases": {},
        "defaultCase": [],
        "forkTasks": [],
        "startDelay": 0,
        "joinOn": [],
        "optional": false,
        "taskDefinition": {
            "createTime": 1579563756480,
            "createdBy": "",
            "name": "add_idents",
            "retryCount": 3,
            "timeoutSeconds": 300,
            "inputKeys": [],
            "outputKeys": [],
            "timeoutPolicy": "TIME_OUT_WF",
            "retryLogic": "FIXED",
            "retryDelaySeconds": 10,
            "responseTimeoutSeconds": 180,
            "inputTemplate": {},
            "rateLimitPerFrequency": 0,
            "rateLimitFrequencyInSeconds": 1
        },
        "defaultExclusiveJoinTask": [],
        "asyncComplete": false,
        "loopOver": []
    },
    "rateLimitPerFrequency": 0,
    "rateLimitFrequencyInSeconds": 0,
    "workflowPriority": 0,
    "iteration": 0,
    "taskDefinition": {
        "present": true
    },
    "loopOverTask": false,
    "queueWaitTime": 710477,
    "taskStatus": "IN_PROGRESS"
}
```

And then I made the ack call which responded with `false`
```
curl --location --request POST 'http://localhost:8080/api/tasks/8452fcf4-f016-4da3-96a2-ea797068af4e/ack' \
--header 'Content-Type: application/json'
```

**Comment by kishorebanala** [comment]
@balloonio The documentation is to be updated, but with recent updates to Conductor, we don't need to ack anymore. Thanks for bringing this to our attention.

**Comment by balloonio** [comment]
@kishorebanala Thank you for the response. Would you like me to make a PR to remove that part of documentation?

**Comment by kishorebanala** [comment]
@balloonio That would be great! Thank you!!

**Comment by balloonio** [comment]
@kishorebanala I noticed that the `/{taskId}/ack` endpoint is still there
https://github.com/Netflix/conductor/blob/dev/jersey/src/main/java/com/netflix/conductor/server/resources/TaskResource.java#L110#L118.
I can also create a PR to retire this unused endpoint with you guys' reviews and help. Would you like me to do that?

**Comment by balloonio** [comment]
bumping up the thread

**Comment by kishorebanala** [comment]
@balloonio Yes, we can deprecate the endpoint. We may not be able to completely remove it in minor version upgrade though. Thanks for following through. We can make this change or we'd appreciate a PR too.

**Comment by balloonio** [comment]
@kishorebanala Cool, I will create a PR and subscribe you guys

**Comment by SuperMasterBlasterLaser** [comment]
Can I ask quesiton why Acking is considered as obsolete? Is it because when clients ack unintentionally their tasks and they will become hanging forever?

**Comment by jansonz** [comment]
If this is not required anymore why the supplied clients still do that? The Python client doesn't work for sure as it expects true on Ack action

**Comment by apanicker-nflx** [comment]
@SuperMasterBlasterLaser The semantic of `ack`ing a task was removed to reduce the number of round trips required for a worker to start processing a task and thereby reducing the failure points.

@jansonz The `ack` semantic was removed from the Java client in #1470 . We are actively welcoming contributions from the community to help us maintain the Python and Go clients (which were community contributions). Please feel free to submit a PR with the required changes.
