### ISSUE TITLE
Any problem adding an index to the workflow table for correlation id?

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1504]
Correlation id searches are slow using /workflow/{name}/correlated/{correlationId} in mysql and postgres. This is because there is not an index on the workflow table by correlation id.

Does anyone see any issue adding that index?

**Comment by kishorebanala** [comment]
@mashurex @mactaggart @s50600822 @ggrekhov Because you have more exposure into Mysql / Postgres modules, can you help with this please?

**Comment by rickfish** [comment]
I can take this if you want. I have already tested on our Postgres implementation. I don't have MySQL here but I can follow the same method as V4__1009_Fix_MySQLExecutionDAO_Index.sql

**Comment by mactaggart** [comment]
@rickfish I have no issue with adding an index for correlation_id to the workflow table.

**Comment by rickfish** [comment]
I created pull request #1520 for this

**Comment by mashurex** [comment]
I don’t see a problem with this index at all, in fact we’ve been running with this index in production for a while.

**Comment by apanicker-nflx** [comment]
Closing since #1520 is merged
