### ISSUE TITLE
Tasks not removed from ElasticSearch when deleting workflow

### ISSUE THREAD

**Issue by NLRemco** [Netflix/conductor#1505]
When removing a workflow instance using the CRUD API. The workflow index itself is removed from ElasticSearch, but the attached tasks are not removed.

When doing a `\DELETE` on the `http://conductor/api/workflow/<workflow-uuid>/remove?archiveWorkflow=false` endpoint, a `204 No Content` is returned: all the occurrences are removed from Redis, the workflow index is removed from ElasticSearch, but the tasks of that workflow are not.

**Comment by apanicker-nflx** [comment]
@RemcoBuddelmeijer Thank you for reporting this issue. We will look into fixing this in a future release, in the meantime please feel free to contribute the fix for this if you need this sooner.

**Comment by annair-dev** [comment]
@RemcoBuddelmeijer True! 
Memory cleanup has to be addressed @apanicker-nflx . 
We need a bulk delete API which would delete the Workflow along with the task entries from the DB and index. 
Do we have one now?

**Comment by apanicker-nflx** [comment]
@annair-dev This improvement is yet to be made to the remove workflow API. Please feel free to contribute a fix.

**Comment by james-deee** [comment]
Just wanted to see if we could re-open, since it's not fixed. Anyone working on a fix for this?

**Comment by RemcoBuddelmeijer** [comment]
Seeing that it has been two years and have flown under my radar, I wouldn't mind taking a look at this myself. So if no one else is working on this I'll be creating a PR. @james-deee

**Comment by apanicker-nflx** [comment]
@RemcoBuddelmeijer that would be great. Thank you

**Comment by RemcoBuddelmeijer** [comment]
@apanicker-nflx Can the issue be reopened? Currently working on the PR but would like for the progress to be followed here as well.

**Comment by RemcoBuddelmeijer** [comment]
Still working on the issue. Been a couple of very busy weeks. Currently only fixing harness tests then the PR will be posted.
@james-deee @apanicker-nflx

**Comment by apanicker-nflx** [comment]
Closed by #3300

**Comment by james-deee** [comment]
Still waiting on the PR https://github.com/Netflix/conductor/issues/1505 to be merged

**Comment by james-deee** [comment]
Re-opening because it still hasn't merged

**Comment by NLRemco** [comment]
PR has been merged. Closing issue. Thank you!
