### ISSUE TITLE
Batched task indexing in multi node deployment can create inconsistent indexes

### ISSUE THREAD

**Issue by mdepak** [Netflix/conductor#1506]
If we use batched indexing in multinode deployment, indexing on task can take inconsistent values.

The task index documents are created in the conductor server using the state from the Redis/MySQL. For example in the case of multi-node server deployment with batched indexing, while index request from server-1 is waiting in the queue to mark the task status as `IN_PROGRESS`, server-2 can create the index as the `COMPLETED` status. Later server-1 can overwrite the existing index as `IN_PROGRESS` status.

But consistency is maintained at workflow level indexes since workflow indexes do not use batching. 

Please confirm whether this issue can occur with the mentioned configuration. If so can we make use of timestamp-based versioning using `version_type` attribute in index requests so that the latest index data is maintained?

**Comment by kishorebanala** [comment]
@mdepak Task document is only indexed once, after the workflow is completed. Can you elaborate on why you think a Task status in index document can be overwritten?

**Comment by mdepak** [comment]
@kishorebanala  Thanks for the clarification. Since the task index is updated only on the workflow termination, the problem I mentioned shouldn't happen.
