### ISSUE TITLE
Persistance problem of conductor

### ISSUE THREAD

**Issue by Erenaliaslangiray** [Netflix/conductor#1515]
Hello,

I want to use Conductor for my project and have a little problem on persistence. I am currently using a single ec2 machine and using docker-compose for conductor ui, server, dynomite and es. 

The problem is: Is there any way to persist conductor server data, workflow and task defs so that If my machine or docker fails and I restart all the services with my old data? Or can I connect my conductor system to an AWS service that guarantees to persistence of system?

Thanks in advance!

**Comment by saidatta** [comment]
you can use aws elasticache or separate it to a different EC2 machine and allow it to have high availability.

**Comment by apanicker-nflx** [comment]
Thanks @saidatta for the response.
@Erenaliaslangiray As pointed out above, you can use use a different EC2 instance for your datastores such that the data durability is not reliant on your service.
