### ISSUE TITLE
TERMINATE workflow not working for Parent-Sub Workflows

### ISSUE THREAD

**Issue by ketantalreja** [Netflix/conductor#1517]
Hi @apanicker-nflx, @kishorebanala  and Netflix team, 

I was facing weird behavior while terminating a workflow which consists of sub-workflows. 

Let's say I have four workflows in my use case: 
Parent-workflow -> sub-workflow-1 -> sub-workflow-2 -> sub-workflow-3

where parent-workflow invoked sub-workflow-1 and sub-workflow-1 invokes sub-workflow-2 and so on and all the workflows in my case contains system tasks i.e. HTTP, SUB-WORKFLOW, DECISION, WAIT.

Now, when I invoke Conductor REST API _**DELETE /workflow/{workflowId}**_  where workflowId is my parent-workflow id, then, in this case, parent-workflow and sub-workflow-1 gets terminated i.e., also tasks which are in in-progress state are CANCELLED and workflow status changes to TERMINATED, however, the tasks in the sub-workflow-2 and in sub-workflow-3 are still in in-progress and workflow status is also in RUNNING state. Ideally, as per my understanding, the behavior should be if I TERMINATE parent-workflow, then all it's children i.e., sub-workflow-1, sub-workflow-2 etc. should get TERMINATED too, which is not the case. Looks like the parent-workflow and it's first child i.e. sub-workflow-1 is getting TERMINATED but not it's subsequent children i.e., sub-workflow-2 and sub-workflow-3.  

**Conductor version: 2.11**
I have traced conductor code just to see the how terminate workflow logic works i.e., 
**WorkflowService -> 
@Service
    public void terminateWorkflow(String workflowId, String reason) {
        workflowExecutor.terminateWorkflow(workflowId, reason);
    }

WorkflowExecutor -> 
public void terminateWorkflow(String workflowId, String reason) { ... } **  

And I could see in terminate workflow logic inside the WorkflowExecutor class, this should have updated the task status to CANCELLED and workflow status to TERMINATED for all the sub-workflows attached to the parent workflow. 

Please let me know, if this is the expected behavior in conductor which in my opinion is bug in the or is there something I am missing while invoking API to TERMINATE the workflows. 

Thanks, 
Ketan

**Comment by apanicker-nflx** [comment]
@ketantalreja This issue has already been fixed in a subsequent release. Specifically in [v2.12.2](https://github.com/Netflix/conductor/releases/tag/v2.12.2). Please update your Conductor version to the latest to pull in all code changes and bug fixes.

**Comment by ketantalreja** [comment]
Thanks @apanicker-nflx for the quick reply.
