### ISSUE TITLE
Question: why does "restart" not support setting new workflow input?

### ISSUE THREAD

**Issue by smullins3000** [Netflix/conductor#1518]
The rerun method allows you to set new workflow input. The restart (restartWorkflow in WorkflowService and "rewind" in WorkflowExecutor) does NOT support this.

Does anyone know why this might be true? I've looked at the code and it looks like restart should be able to support changing workflow input pretty readily. 

Thoughts?

**Comment by apanicker-nflx** [comment]
@smullins3000 Your observation is correct. We can make the restart API extensible to allow user to change the workflow input. We will look into this making this enhancement in a future release. Please feel free to contribute if you need this sooner.

**Comment by smullins3000** [comment]
I feel odd calling you apanicker, but thank you, apanicker! We'll almost undoubtedly get to this in the next 3-6 months. The fact that the restart method can run against the latest version of the workflow, rather than just the set of tasks it executed whenever it ran before, makes this very valuable in certain use cases. Those use cases many times also include having some modification to the workflow input. 

I'll put this on our backlog and we'll see who gets to it first.
