### ISSUE TITLE
Continue Workflow if Task Failed

### ISSUE THREAD

**Issue by cquon** [Netflix/conductor#152]
Hi,

I was wondering if there is any way to have a task "FAILED", but to continue the workflow.  The intent is to acknowledge that the current task was not completed successfully, but we do not want to fail the entire workflow and continue with the remaining tasks.  From testing it appears the entire workflow is failed once a task is FAILED.  I see the possible task results are COMPLETED, FAILED, IN_PROGRESS, SCHEDULED.  Would it be ok to introduce a new state to represent this?  And if so is there a suggested ENUM name?  I am not sure if there are other implications or another way to represent this.

**Comment by v1r3n** [comment]
@cquon This is the current behavior in 1.7.0, however as part of next minor update, we are adding ability to mark tasks as `optional` in the workflow.  When marked as optional, the workflow will continue to run even if the task fails.  When the worker marks the task as failed, the status is then reflected as `COMPLETED_WITH_ERRORS`

https://github.com/Netflix/conductor/blob/dev/common/src/main/java/com/netflix/conductor/common/metadata/tasks/Task.java#L31

If you want to try it out, do a build from `dev` branch - I plan to create a release in another 1-2 weeks.

**Comment by cquon** [comment]
I have tried it out with the "optional" and it seems to be the desired behavior thanks!

**Comment by microsoftly** [comment]
@cquon I don't see this option anywhere in the docs
