### ISSUE TITLE
canSearchAcrossWorkflows Question

### ISSUE THREAD

**Issue by demichej** [Netflix/conductor#1527]
Hello, I have a question about the need for the canSearchAcrossWorkflows() boolean. It doesn't look to me like there's any kind of workflow restriction that the indexDAO query path is going through.

Why would we not just use indexDAO for all queries? Wouldn't that be faster than going against the other backing store (e.g. Mysql, Postgres...)? We hit the index issue reported in another issue with a bug fix so the index works for us. However, I'm just wondering why we wouldn't want to go against ES for all users of that query? 

Is it because it avoids 2 queries?

https://github.com/Netflix/conductor/blame/master/core/src/main/java/com/netflix/conductor/core/orchestration/ExecutionDAOFacade.java#L152

**Comment by apanicker-nflx** [comment]
@demichej You are right, this was added as a quick workaround to enable datastore migration. But it would definitely be quicker to just use indexDAO for all search queries and reduce the burden on the primary datastore.

**Comment by demichej** [comment]
Thanks @apanicker-nflx I might put a pr out to remove that flag and just do the index Dao instead
