### ISSUE TITLE
ES7 with Kafka option?

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1529]
We currently are using our own es7-persistence module with the following options and I am trying to get my arms around how to make it contributable and/or if there is interest:

- option to push the documents to a Kafka topic and Logstash scripts to read from the topic and write to ES, as opposed to writing directly to ES.

- option to write to an 'active' index for non-terminal workflows/tasks and write terminal documents to monthly indexes for workflows/tasks so that the monthly indexes can be rolled off the cluster easily. When a terminal document is written to the monthly index it will be removed from the 'active' index. An ES alias would contain all the indexes and searches would go against the alias.

- option to create a 'tags' attribute at the root level of the workflow/task documents that will be populated by specified attributes in the input/output data so that these tags can be indexable/searchable. The 'tags' attribute would just be in the ES document, not the database document and would be created before indexing the document.

Any interest? It will take a while to make it contributable in the proper fashion if so, just trying to see if it is worth the effort...

**Comment by manan164** [comment]
HI @rickfish. We are using this in our environment. How we have implemented IndexDAO is all index calls will go to kafka and all search calls will be routed to existing ESDAO.

**Comment by rickfish** [comment]
@manan164 are you using ES7? Do you have high-volume? Do you want to be able to index some or all of the input/output attributes?

**Comment by apanicker-nflx** [comment]
@rickfish 
> Any interest? 

Yes, definitely. We would really appreciate an ES7 persistence module. 

> * option to push the documents to a Kafka topic and Logstash scripts to read from the topic and write to ES, as opposed to writing directly to ES.
> * option to write to an 'active' index for non-terminal workflows/tasks and write terminal documents to monthly indexes for workflows/tasks so that the monthly indexes can be rolled off the cluster easily. When a terminal document is written to the monthly index it will be removed from the 'active' index. An ES alias would contain all the indexes and searches would go against the alias. 

We are currently moving to using a similar model in our indexing pipeline but with ES6. We are currently migrating older workflows and tasks from ES2 and ES5 into this secondary ES6 index and will switch over to live data in the primary ES6 index once the migration is complete. For legacy reasons, we are unable to roll out the oldest data. But rolling over indices based on time/size using Elasticsearch lifecycle management helps keep index sizes in check. 

> * option to create a 'tags' attribute at the root level of the workflow/task documents that will be populated by specified attributes in the input/output data so that these tags can be indexable/searchable. The 'tags' attribute would just be in the ES document, not the database document and would be created before indexing the document.

This is an improvement we are looking to make to the indexing process. And are really glad to know that our thoughts align with the community. We see a potential for defining a "searchableFields" attribute in the workflow definition to specify fields that will be indexed as part of the workflow/task execution. Additionally, "tags" is a feature request from our users to add meta information to workflow executions during execution/after completion.

> It will take a while to make it contributable in the proper fashion if so, just trying to see if it is worth the effort...

I would definitely say that this would be a huge improvement to the current indexing model and hence is worth the effort. And as always, really appreciate your contributions.
