### ISSUE TITLE
I need to push data to an ElasticSearch server and I wanted to know how can I authenticate the connection using username and password

### ISSUE THREAD

**Issue by charan986** [Netflix/conductor#1532]
I need to push data to an ElasticSearch server and I wanted to know how can I authenticate the connection using username and password

**Comment by apanicker-nflx** [comment]
@charan986 I believe this PR #1209 would help your use-case. We are waiting on the user to pick up on the task. However, if you are comfortable with taking over this PR and addressing comments, we would really appreciate this.
