### ISSUE TITLE
Retrying a FAILED workflow from a TIMED_OUT task

### ISSUE THREAD

**Issue by renuka-raju** [Netflix/conductor#1535]
I have a workflow in which task T2(retyrCount=3) got timed out and got rescheduled thrice in the first execution. 

Now, I tried rerunning the workflow from this task by checking for a TIMED_OUT status too along with FAILED and CANCELED in the code for rerun/retry, this task got scheduled again and my worker put it to IN_PROGRESS, but doesn't send anymore updates. Now, the task is left IN_PROGRESS and workflow RUNNING. From the logs, I see that the worklfow is not being added back to the decider queue. 

Is there any condition that, we are not supposed to do a rerun action on a workflow from a timed_out task?

**Comment by apanicker-nflx** [comment]
>Is there any condition that, we are not supposed to do a rerun action on a workflow from a timed_out task?

There isn't a restriction like the one you are asking about. 

> I tried rerunning the workflow from this task by checking for a TIMED_OUT status too along with FAILED and CANCELED in the code for rerun/retry

Can you please post your code snippet for this change to help debug this issue?

**Comment by renuka-raju** [comment]
https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java 

1) For retry - by adding TIMED_OUT as one of the cases:

`
public void retry(String workflowId) {
.
.        
Map<String, Task> retriableMap = new HashMap<>();
        for (Task task : workflow.getTasks()) {
            switch (task.getStatus()) {
                case FAILED:
                case FAILED_WITH_TERMINAL_ERROR:
                    retriableMap.put(task.getReferenceTaskName(), task);
                    break;
                case CANCELED:
                    if (task.getTaskType().equalsIgnoreCase(TaskType.JOIN.toString())) {
                        task.setStatus(IN_PROGRESS);
                        // Task doesn't have to be updated yet. Will be updated along with other Workflow tasks downstream.
                    } else {
                        retriableMap.put(task.getReferenceTaskName(), task);
                    }
                    break;
                default:
                    retriableMap.remove(task.getReferenceTaskName());
                    break;
            }
        }
`

2) for rerun - I call the api from with a taskId that TIMED_OUT in the first run

`private boolean rerunWF(String workflowId, String taskId, Map<String, Object> taskInput,
                            Map<String, Object> workflowInput, String correlationId) {`

**Comment by renuka-raju** [comment]
https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java

1) For retry - by adding TIMED_OUT as one of the cases:
  ```
  public void retry(String workflowId) {
        Workflow workflow = executionDAOFacade.getWorkflowById(workflowId, true);
        if (!workflow.getStatus().isTerminal()) {
            throw new ApplicationException(CONFLICT, "Workflow is still running.  status=" + workflow.getStatus());
        }
        if (workflow.getTasks().isEmpty()) {
            throw new ApplicationException(CONFLICT, "Workflow has not started yet");
        }

        // Get all FAILED or CANCELED tasks that are not COMPLETED (or reach other terminal states) on further executions.
        // // Eg: for Seq of tasks task1.CANCELED, task1.COMPLETED, task1 shouldn't be retried.
        // Throw an exception if there are no FAILED tasks.
        // Handle JOIN task CANCELED status as special case.
        Map<String, Task> retriableMap = new HashMap<>();
        for (Task task : workflow.getTasks()) {
            switch (task.getStatus()) {
                case FAILED:
                case FAILED_WITH_TERMINAL_ERROR:
                    retriableMap.put(task.getReferenceTaskName(), task);
                    break;
                case CANCELED:
                    if (task.getTaskType().equalsIgnoreCase(TaskType.JOIN.toString())) {
                        task.setStatus(IN_PROGRESS);
                        // Task doesn't have to be updated yet. Will be updated along with other Workflow tasks downstream.
                    } else {
                        retriableMap.put(task.getReferenceTaskName(), task);
                    }
                    break;
                default:
                    retriableMap.remove(task.getReferenceTaskName());
                    break;
            }
        }

```

for rerun - I call the api from with a taskId that TIMED_OUT in the first run
`private boolean rerunWF(String workflowId, String taskId, Map<String, Object> taskInput, Map<String, Object> workflowInput, String correlationId) {`

**Comment by apanicker-nflx** [comment]
@renuka-raju 
Your observation about retrying a TIMED_OUT task is correct. We are also looking to enhance the retry functionality to extend to timed out tasks and workflows. We would really appreciate it if you could submit your changes upstream to make this available to the community.

For reruns, we would need to debug this further, please let us know if you make any progress in the meantime.
