### ISSUE TITLE
Making event execution persistence optional

### ISSUE THREAD

**Issue by mdepak** [Netflix/conductor#1536]
In `EventProcessor` event execution details are [persisted](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/events/SimpleEventProcessor.java#L235) and there is no way to clean up these event details in the conductor. Additionally, these event execution details are not used for any logic and there is no way of accessing status without querying the database.

Further, there is no way of removing the event execution indexes as well. So we are trying to make it optional.

Condition on `addEventExecution()` is used in `SimpleEventProcessor` to identify the potential duplicate messages from the event queues. Provided that conductor uses the two queues including Redis queues ( sorted set which does not allow/overrides duplicate message) and SQS (which handles duplicates messages within deduplication window), Is it ok to make addEventExecution() optional to ensure event execution messages are not persisted. 

In the `RedisExecutionDAO`, each event message is saved as a separate key in the Redis's hash and leads to an exponentially larger number of keys and it becomes inefficient to scan the keys and get the event messages. So, shall we use HSETNX with the same key for a particular event type with event IDs as properties of the hash?

**Comment by apanicker-nflx** [comment]
@mdepak Thank you for the suggestions and observations.
We have also been evaluating the persistence of event execution and are looking into ways to avoid persisting this data/cleaning up after execution. 

> shall we use HSETNX with the same key for a particular event type with event IDs as properties of the hash?

This might be helpful to reduce the number of records at the expense of larger hashes. If you can test this out and create a PR for this, we would really appreciate that.

**Comment by mdepak** [comment]
Closing this as PR is merged.
