### ISSUE TITLE
AMQP support for netflix conductor

### ISSUE THREAD

**Issue by ritu-p** [Netflix/conductor#1538]
We want AMQP support along with Netflix Conductor.
Saw that there was a  PR that had support for AMQP but was not merged.
Will that PR be merged anytime soon to the master branch?

**Comment by apanicker-nflx** [comment]
@ritu-p We [noticed failures in the tests](https://github.com/Netflix/conductor/pull/1063#issuecomment-520654211) as a result of these changes, which required us to revert them. It would be a valuable addition if you could take on this effort and submit the cleaned up PR.

**Comment by ritu-p** [comment]
@apanicker-nflx  Should I take the code from that reverted PR and create a new one from my end?
Or should I work on the same PR?
Just trying to understand the process here.
Thanks & Regards 
Ritu

**Comment by apanicker-nflx** [comment]
@ritu-p Since this was a contribution from the community, we do not have a definitive process. You could either fork off the reverted PR and make the relevant changes or you could start a completely new pull request for the implementation, whichever maybe more comfortable for you.

**Comment by ritu-p** [comment]
@apanicker-nflx I have made the necessary changes please take a look at this Pr.
This has most of the changes from original PR.
https://github.com/Netflix/conductor/pull/1589

**Comment by ritu-p** [comment]
#1589 fixes this issue

**Comment by shrikantmule** [comment]
I am stuck at publishing the event using Rabbit MQ. I have updated the server.properties with Rabbit MQ configuration. I could see endpoint /api/event/queues/providers' is returning me AMQPEventQueueProvider. However I was expecting that at start up FAILED and COMPLETED queues will get created in my RabbbitMQ but I don't see them getting created.

I could also see that AMQPModule.getAMQQueueEventQueueProvider and getAMQExchangeEventQueueProvider methods are getting called but there is no call made to getQueues

Any idea what could be wrong here ?

**Comment by ritu-p** [comment]
@shrikantmule ,
 Hope you have created event handlers via events that will create the listeners. with amqpObservablequeues

**Comment by shrikantmule** [comment]
@ritu-p I am very new to this product and didn't follow exactly what you mean. If you could post some example or sample code that will be really helpful.
