### ISSUE TITLE
How to capture response status code of HTTP post task in successive task?

### ISSUE THREAD

**Issue by Dhirajk772** [Netflix/conductor#1541]
1.I need to capture on HTTP status code received  in HTTP task so that according to the value next task task to be performed. I tried "statusCode": "${task_http1.output.statusCode}" but the value remains null.
2.Suppose HTTP status code is 4XX or 5XX then on basis of this different task to be executed : Do this can be done using DECISION task ?

Thanks in advance for your valuable help.

**Comment by apanicker-nflx** [comment]
@Dhirajk772 The JSONPath seems incorrect. Please try using `${task_http1.output.response.statusCode}`

**Comment by Dhirajk772** [comment]
Thanks
