### ISSUE TITLE
How to extend DECISION task?

### ISSUE THREAD

**Issue by lydialmr120** [Netflix/conductor#155]
What is the different between start and execute in WorkflowSystemTask?
May I add some code which will be executed before case in DECISION task? How to do this?
I know I can add a task before DECISION, but I have a lot of requirement like this, if that is OK, it will reduce many configuration in workflow definition.

**Comment by v1r3n** [comment]
`start` is called when the task is scheduled and executed the first time.
`execute` method is used to check the status of the current task or start if the previous start did not complete (backend transient errors etc)

**Comment by lydialmr120** [comment]
@v1r3n How to extend DECISION task? It seems to be impossible.

**Comment by v1r3n** [comment]
@lydialmr120 Yes, currently it is not possible to easily extend the decision task.  
We are looking at script tasks that can execute javascript code that might be able to help your case - but we have not prioritized them yet.
