### ISSUE TITLE
[UI]Poll data tab does not pull all queues

### ISSUE THREAD

**Issue by banduo** [Netflix/conductor#1556]
We noticed a lot of queues not show up under the "poll data" tab (in Task Queues). After a little bit of digging, I think the issue comes from the below code:
https://github.com/Netflix/conductor/blob/bfad64e00f8acafbe2922531f87022bb1641c961/core/src/main/java/com/netflix/conductor/service/ExecutionService.java#L185

The code filters out queue names that have a domain. However, all our tasks have been scheduled with the domain specified (even for default one). And the queue_names in queue_message table are all formatted as "domain: task_name". The missing results have caused this tab not usable.

**Comment by apanicker-nflx** [comment]
@banduo Thanks for reporting this. We will look into fixing this in a future release version. In the meantime, please feel free to contribute a fix.
