### ISSUE TITLE
Do-while task will loop all tasks in the workflow instead of only the tasks in loopOver!

### ISSUE THREAD

**Issue by leissen** [Netflix/conductor#1558]
Hi Guys, I just want to use do-while task to loop one task(task1) for several times then run another task(task2) as shown in the following workflow definition. But the do-while task will loop both task1 and task2. If I set ${workflow.input.value} to 3, the tasks execution will be task1 -> task2 -> task1 -> task2 -> task1 -> task2. I use conductor server 2.25.0. Is anything wrong with my configuration? Or is this a bug? Thanks a lot for any suggestion.  @manan164 

{
  "name": "workflow1",
  "description": "",
  "ownerEmail":"admin@163.com",
  "version": 1,
  "tasks": [
    {
      "name": "loop_task",
      "taskReferenceName": "LoopTask",
      "type": "DO_WHILE",
      "inputParameters": {
        "value": "${workflow.input.value}"
      },
      "loopCondition": "if ($.LoopTask['iteration'] < $.value) { true; } else { false; }",
      "loopOver": [
        {
          "name": "task1",
          "taskReferenceName": "while_task1",
          "type": "SIMPLE"
        }
      ],
      "startDelay": 0,
      "optional": false
    },
    {
      "name": "task2",
      "taskReferenceName": "task2",
      "type": "SIMPLE"
    }  ]
}

My workflow job invoking Json:
{
  "name": "workflow1",
  "version": 1,
  "correlationId": "workflow1_job1",
  "input": {
    "value" : 3
  }
}

**Comment by manan164** [comment]
Hi @leissen  This is the bug you are facing, we talked in another thread. If you want to tryout sample do_while task. Please look at [definition](https://github.com/Netflix/conductor/blob/master/test-harness/src/test/resources/integration/scenarios/legacy/DoWhileTest_1.json)

**Comment by leissen** [comment]
@manan164 Thank you very much. I really appreciate your help!

**Comment by leissen** [comment]
Hi, @manan164 , I find a workaround for this issue. Just put the do-while task in a sub workflow and this sub workflow contains only this do-while task. Of course this do-while task can have other tasks inside. The task loop issue is fixed even if there are other tasks after this sub workflow. How do you think of this workaround? Is there any other risk for this? Thanks.

**Comment by manan164** [comment]
Hi @leissen , Yes this is the workaround that we currently use. You can use dowhile sub-workflow output parameters to know what happens with the do while task like how many iterations ran etc and use that in parent workflow's subsequent task.
The only risk is spawning a new workflow is costlier in terms of redis and elastic search calls, than creating tasks.
By the way do while task does not support sub-workflow as loopOver task.
The cost was the reason for that. I have raise [PR](https://github.com/Netflix/conductor/pull/1435) for that also.

**Comment by krishnaputhran** [comment]
Hi, anyone know how to access the iterator value inside the tasks, which are running as part of the DO_WHILE loop. For eg: I want to read an array value inside the running tasks. The array would be an input to the looped task from another task output, which was executed before the loop started.  I am not sure how we can use the DO_WHILE 'iteration' variable for reading the array values. 

I want to use the 'iteration' value something like below

preOrder_service_get.output.response.body..products['iteration'].pluCode

**Comment by chnardi** [comment]
I have the same questions, I tried several things and the only way I could make it work is to receive the whole collection  as parameter and then use the iteration in the task object I receive in the worker to reference the element I need. But it would be great to just receive the element I need.

**Comment by krishnaputhran** [comment]
For some update please refer here. https://github.com/Netflix/conductor/issues/1677

**Comment by chnardi** [comment]
Thanks @krishnaputhran
