### ISSUE TITLE
POST /workflow/{name} response waits until workflow has completed

### ISSUE THREAD

**Issue by timoly** [Netflix/conductor#156]
Is it a bug or feature that when starting a workflow using rest api POST /workflow/foo?&correlationId=foobar the workflow id is only returned after the workflow has already completed or failed. 
If this is indeed by design, are there any plans to include maybe a parameter to indicate that the workflow should be started in background?
My test workflow is made up of http tasks which take about 20 seconds in total to complete.

**Comment by v1r3n** [comment]
@timoly this is true when all the tasks are system tasks such as HTTP.  We are addressing this in the upcoming version allowing for these to be executed asynchronously.

**Comment by amoolya19** [comment]
@timbozo ,

Even i had same query. 1 more thing i found out was, though the swagger was running for 1st start click, i was able to click for more starts. what i mean to say is you can click 5 times to start workflow 5 times ( 5 work flow instances), but returns only one of the workflow id and i assume its first 1.

**Comment by v1r3n** [comment]
@amoolya19 swagger will return the last response.  it will not accumulate the responses from each click and show.
