### ISSUE TITLE
How to get logs/information from running worker task?

### ISSUE THREAD

**Issue by leissen** [Netflix/conductor#1560]
Hi Guys, I have a long time execution worker task. I want to know the progress rate of this task during executing period and I can output some logs or information about the progress rate in the worker during task running. I don't want to bring in any other system such as Redis or MQ. Does Conductor support this functionality natively？ Thanks a lot for any help!

**Comment by apanicker-nflx** [comment]
@leissen You can update the task execution logs from your worker to provide information about the progress of your task using [this API](https://github.com/Netflix/conductor/blob/master/jersey/src/main/java/com/netflix/conductor/server/resources/TaskResource.java#L119-L124).
