### ISSUE TITLE
Archival Module with Default Implementation

### ISSUE THREAD

**Issue by pavelhalabala** [Netflix/conductor#1563]
Provide archival service module with default implementation of archiving workflows to elastic search immediately on completion through WorkflowStatusListener.

Implements point nr. 5 in Performance & Scalability section of Conductor wishlist: https://github.com/Netflix/conductor/wiki/Conductor-Wishlist

It is also discussed / proposed in this thread:
https://github.com/Netflix/conductor/issues/1097

I'm going to implement it now and submit PR after completion.

**Comment by pavelhalabala** [comment]
PR created here: https://github.com/Netflix/conductor/pull/1565

**Comment by apanicker-nflx** [comment]
@pavelhalabala Thank you for the contribution.

**Comment by pavelhalabala** [comment]
@apanicker-nflx Thanks for merging. Now it can be removed from conductor wishlist.

**Comment by manan164** [comment]
Hi @pavelhalabala , We are using this in our environment. 
However, deleting workflow the moment it completes from redis will impose one risk if that workflow is sub_workflow and its result is used later in parent workflow. Now if Elastic Search does not has that information then the parent workflow will never be able to complete. It will lead to a deciderQeueu pileup. Currently, we are working on a mechanism to delete is one we get confirmation that in ES index has happened.
Any thoughts @apanicker-nflx ?

**Comment by pavelhalabala** [comment]
Hi @manan164 , you are right that behavior with subworkflows is worth considering. But I see in the code that updating the workflow in ES is synchronous operation and workflow removal is done only after ES index is updated successfully. The ES update is retried 3 times and throws exception if all retries failed. In such case executionDAO.removeWorkflow(..) operation is skipped and the workflow execution data is not removed.

**Comment by apanicker-nflx** [comment]
> The ES update is retried 3 times and throws exception if all retries failed. In such case executionDAO.removeWorkflow(..) operation is skipped and the workflow execution data is not removed.

This is correct.

**Comment by mdepak** [comment]
Hi, @apanicker-nflx  @pavelhalabala Once we archive data to Elasticsearch do you recommend any scalable approach to delete data from Elasticsearch as search results are limited by 5000 items by the conductor ? Do you think it is good to insert archiving data to time-based rolling indices and enable search to query time-based indices as well so that workflow data will be available for parent workflow from sub-workflow and ES indices can be dropped by time?
