### ISSUE TITLE
Task Status Exporter

### ISSUE THREAD

**Issue by kushalhalder** [Netflix/conductor#1564]
Hi,
Use case: Task status is exported on task completion.
Is there a way to export Task completion status with the following payload:
```
{
workFlowId:"",
taskId:"",
taskRefName:"",
payload:"${$workflow.input.*}"
}
```
One way is to maintain a registry of the tasks running and poll Conductor for their statuses. Since this is not the best approach, what other options do we have?

**Comment by apanicker-nflx** [comment]
IIUC, your use-case is to be notified using eventing when a task has moved to a terminal status? Is that correct?
This is a use-case that we are looking to add in a future release and the implementation should be similar to that of the [WorkflowStatusListener](https://netflix.github.io/conductor/extend/#workflow-status-listener).

**Comment by kushalhalder** [comment]
`IIUC, your use-case is to be notified using eventing when a task has moved to a terminal status? Is that correct?`
You got it right. Future Release, okay.

**Comment by optimal-rhythm** [comment]
Hi,

We are planning to implement this feature if no one else is working on this. Basically, the design approach would be similar to WorkflowStatusListener. We are also considering adding a onWorkflowStarted method to the WorkflowStatusListener to help notify kick-off of workflow execution.

Please let us know if this is ok with the community. If so, we should be able to get a PR up hopefully.

**Comment by apanicker-nflx** [comment]
@optimal-rhythm I believe this is not being actively worked on. Please feel free to create a PR for this. Please also add documentation for this feature as part of the PR.

**Comment by optimal-rhythm** [comment]
thanks @apanicker-nflx ! will do
