### ISSUE TITLE
Workflow status notifications -feature request

### ISSUE THREAD

**Issue by timoly** [Netflix/conductor#157]
It would be great if there would be way to register actions for workflow events. For example to be able to start a specified task in case the workflow finishes in failure state. 
Currently, if I have understood correctly, the event system is only used for listening external events, and then executing a following action "Start a Workflow", "Fail a Task" or "Complete a Task".
And if I currently want to know whether or not my workflow has succeeded, I have to poll the status using the workflow id?

**Comment by picaron** [comment]
I agree this feature is really missing for our use cases as well.

We would like to have a way to trigger a system-wide workflow to extract the result of any completing workflow and push a report somewhere.

It would make sense to have system events on which we can define handlers.

**Comment by apanicker-nflx** [comment]
This feature is already available using Event Handlers.
