### ISSUE TITLE
Netflix Conductor Client -Poll Queues issue

### ISSUE THREAD

**Issue by degakrishna** [Netflix/conductor#1573]
Hi All,

It seems one of our task queue got piled up  and affecting processing of workflow. I have restarted Server and client apps, cleared redis cache but still queue is draining. Also, we don't see that many (equivalent queue size)workflow currently running in our server.

Kindly suggest how to reduce/purge the task Queues  in conductor .

![pollData](https://user-images.githubusercontent.com/31501716/76419069-c00ce880-63c5-11ea-9d48-a9645fbeaf53.png)

**Comment by apanicker-nflx** [comment]
If you're using DynoQueues, the quickest way to purge the task queues would be to ssh in to the dynomite instance and  run a `del` command on the key for the task queue.

**Comment by mdepak** [comment]
@apanicker-nflx  We observe a similar problem in the event queues. The event queue that DynoObservable is polling gets piled after a certain time in case of large loads in multi-node deployment. Any insights on this queue pile-up problem?

**Comment by apanicker-nflx** [comment]
Are you seeing any exceptions/errors in your logs? Do you see any connection errors with your dynomite instance? We use a multi-node dynomite deployment with multi-node conductor and the only time we have seen an issue with the queue pile-up was during a connection issue which resolved itself once the connection errors were resolved.
