### ISSUE TITLE
Gulp issues

### ISSUE THREAD

**Issue by ramyavakity** [Netflix/conductor#1578]
I have upgraded gulp version to 4 as we have some vulnerabilities with 3. 
Npm run build fails with some random errors.
Please help me to resolve gulp upgrade issues.

**Comment by srikanthjviru** [comment]
Even im facing the same issue after upgrading to gulp 4. Please let me know of you find any solution

**Comment by ramyavakity** [comment]
@apanicker-nflx  @kishorebanala  
I have created a pull request for the gulp issues PR #1660
