### ISSUE TITLE
Some configurations not work?

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1583]
I just modified server.properties with the config: 'async.update.short.workflow.duration.seconds=5' and 'async.update.delay.seconds=5' .

But it didn't work, still used old value, below is the json and workflow snapshot:
{
   "ownerApp": "",
   "createTime": 1584255584746,
   "updateTime": 1584255919700,
   "status": "COMPLETED",
   "endTime": 1584255919700,
   "workflowId": "22cf4f33-2c18-4858-b188-5f7df6c17ee3",
   "tasks": [
      {
         "taskType": "SUB_WORKFLOW",
         "status": "COMPLETED",
         "inputData": {
            "workflowInput": {
               "ipList": "2.2.2.2,4.4.4.41",
               "cmd": "hadoop_util.stopnn"
            },
            "subWorkflowTaskToDomain": null,
            "subWorkflowName": "bdpops_auto_deploy",
            "subWorkflowVersion": 1
         },
         "referenceTaskName": "stopnn_wf",
         "retryCount": 0,
         "seq": 1,
         "pollCount": 11,
         "taskDefName": "stopnn_wf",
         "scheduledTime": 1584255584755,
         "startTime": 1584255585112,
         "endTime": 1584255889103,
         "updateTime": 1584255889091,
         "startDelayInSeconds": 0,
         "retried": false,
         "executed": true,
         "callbackFromWorker": true,
         "responseTimeoutSeconds": 0,
         "workflowInstanceId": "22cf4f33-2c18-4858-b188-5f7df6c17ee3",
         "workflowType": "single_restartnn_new",
         "taskId": "ed6437e0-2778-4b70-87c0-3b6fcc374862",
         "callbackAfterSeconds": 30,
         "outputData": {
            "cdn_url": null
         },
         "workflowTask": {
            "name": "stopnn_wf",
            "taskReferenceName": "stopnn_wf",
            "inputParameters": {
               "ipList": "${workflow.input.ipList}",
               "cmd": "hadoop_util.stopnn"
            },
            "type": "SUB_WORKFLOW",
            "decisionCases": {},
            "defaultCase": [],
            "forkTasks": [],
            "startDelay": 0,
            "subWorkflowParam": {
               "name": "bdpops_auto_deploy",
               "version": 1
            },
            "joinOn": [],
            "optional": false,
            "taskDefinition": {
               "createTime": 1584253416330,
               "createdBy": "",
               "name": "stopnn_wf",
               "retryCount": 3,
               "timeoutSeconds": 0,
               "inputKeys": [],
               "outputKeys": [],
               "timeoutPolicy": "TIME_OUT_WF",
               "retryLogic": "FIXED",
               "retryDelaySeconds": 60,
               "responseTimeoutSeconds": 3600,
               "inputTemplate": {},
               "rateLimitPerFrequency": 0,
               "rateLimitFrequencyInSeconds": 1,
               "ownerEmail": "lookstorm@163.com"
            },
            "defaultExclusiveJoinTask": [],
            "asyncComplete": false,
            "loopOver": []
         },
         "rateLimitPerFrequency": 0,
         "rateLimitFrequencyInSeconds": 0,
         "workflowPriority": 0,
         "iteration": 0,
         "subWorkflowId": "3213b1be-8a5b-422f-a776-442729acf717",
         "taskStatus": "COMPLETED",
         "queueWaitTime": 704014,
         "loopOverTask": false,
         "taskDefinition": {
            "present": true
         },
         "logs": []
      },
      {
         "taskType": "SUB_WORKFLOW",
         "status": "COMPLETED",
         "inputData": {
            "workflowInput": {
               "ipList": "2.2.2.2,4.4.4.41",
               "cmd": "hadoop_util.startnn"
            },
            "subWorkflowTaskToDomain": null,
            "subWorkflowName": "bdpops_auto_deploy",
            "subWorkflowVersion": 1
         },
         "referenceTaskName": "startnn_wf",
         "retryCount": 0,
         "seq": 2,
         "pollCount": 2,
         "taskDefName": "startnn_wf",
         "scheduledTime": 1584255889119,
         "startTime": 1584255889348,
         "endTime": 1584255919684,
         "updateTime": 1584255919672,
         "startDelayInSeconds": 0,
         "retried": false,
         "executed": true,
         "callbackFromWorker": true,
         "responseTimeoutSeconds": 0,
         "workflowInstanceId": "22cf4f33-2c18-4858-b188-5f7df6c17ee3",
         "workflowType": "single_restartnn_new",
         "taskId": "898bf5dc-0bcd-4f5a-945d-64538f22edca",
         "callbackAfterSeconds": 30,
         "outputData": {
            "cdn_url": null
         },
         "workflowTask": {
            "name": "startnn_wf",
            "taskReferenceName": "startnn_wf",
            "inputParameters": {
               "ipList": "${workflow.input.ipList}",
               "cmd": "hadoop_util.startnn"
            },
            "type": "SUB_WORKFLOW",
            "decisionCases": {},
            "defaultCase": [],
            "forkTasks": [],
            "startDelay": 0,
            "subWorkflowParam": {
               "name": "bdpops_auto_deploy",
               "version": 1
            },
            "joinOn": [],
            "optional": false,
            "taskDefinition": {
               "createTime": 1584253416332,
               "createdBy": "",
               "name": "startnn_wf",
               "retryCount": 3,
               "timeoutSeconds": 0,
               "inputKeys": [],
               "outputKeys": [],
               "timeoutPolicy": "TIME_OUT_WF",
               "retryLogic": "FIXED",
               "retryDelaySeconds": 60,
               "responseTimeoutSeconds": 3600,
               "inputTemplate": {},
               "rateLimitPerFrequency": 0,
               "rateLimitFrequencyInSeconds": 1,
               "ownerEmail": "lookstorm@163.com"
            },
            "defaultExclusiveJoinTask": [],
            "asyncComplete": false,
            "loopOver": []
         },
         "rateLimitPerFrequency": 0,
         "rateLimitFrequencyInSeconds": 0,
         "workflowPriority": 0,
         "iteration": 0,
         "subWorkflowId": "c414eb91-56e4-406b-8f79-fbe4b2c4bbe2",
         "taskStatus": "COMPLETED",
         "queueWaitTime": 673433,
         "loopOverTask": false,
         "taskDefinition": {
            "present": true
         },
         "logs": []
      }
   ],
   "input": {
      "ipList": "2.2.2.2,4.4.4.41",
      "cmd": "ls -ls /root1"
   },
   "output": {
      "cdn_url": null
   },
   "workflowType": "single_restartnn_new",
   "version": 1,
   "schemaVersion": 2,
   "taskToDomain": {},
   "failedReferenceTaskNames": [],
   "workflowDefinition": {
      "updateTime": 1584243007810,
      "name": "single_restartnn_new",
      "description": "Restart namenode.",
      "version": 1,
      "tasks": [
         {
            "name": "stopnn_wf",
            "taskReferenceName": "stopnn_wf",
            "inputParameters": {
               "ipList": "${workflow.input.ipList}",
               "cmd": "hadoop_util.stopnn"
            },
            "type": "SUB_WORKFLOW",
            "decisionCases": {},
            "defaultCase": [],
            "forkTasks": [],
            "startDelay": 0,
            "subWorkflowParam": {
               "name": "bdpops_auto_deploy",
               "version": 1
            },
            "joinOn": [],
            "optional": false,
            "taskDefinition": {
               "createTime": 1584253416330,
               "createdBy": "",
               "name": "stopnn_wf",
               "retryCount": 3,
               "timeoutSeconds": 0,
               "inputKeys": [],
               "outputKeys": [],
               "timeoutPolicy": "TIME_OUT_WF",
               "retryLogic": "FIXED",
               "retryDelaySeconds": 60,
               "responseTimeoutSeconds": 3600,
               "inputTemplate": {},
               "rateLimitPerFrequency": 0,
               "rateLimitFrequencyInSeconds": 1,
               "ownerEmail": "lookstorm@163.com"
            },
            "defaultExclusiveJoinTask": [],
            "asyncComplete": false,
            "loopOver": []
         },
         {
            "name": "startnn_wf",
            "taskReferenceName": "startnn_wf",
            "inputParameters": {
               "ipList": "${workflow.input.ipList}",
               "cmd": "hadoop_util.startnn"
            },
            "type": "SUB_WORKFLOW",
            "decisionCases": {},
            "defaultCase": [],
            "forkTasks": [],
            "startDelay": 0,
            "subWorkflowParam": {
               "name": "bdpops_auto_deploy",
               "version": 1
            },
            "joinOn": [],
            "optional": false,
            "taskDefinition": {
               "createTime": 1584253416332,
               "createdBy": "",
               "name": "startnn_wf",
               "retryCount": 3,
               "timeoutSeconds": 0,
               "inputKeys": [],
               "outputKeys": [],
               "timeoutPolicy": "TIME_OUT_WF",
               "retryLogic": "FIXED",
               "retryDelaySeconds": 60,
               "responseTimeoutSeconds": 3600,
               "inputTemplate": {},
               "rateLimitPerFrequency": 0,
               "rateLimitFrequencyInSeconds": 1,
               "ownerEmail": "lookstorm@163.com"
            },
            "defaultExclusiveJoinTask": [],
            "asyncComplete": false,
            "loopOver": []
         }
      ],
      "inputParameters": [],
      "outputParameters": {
         "cdn_url": "${workflow.output.result}"
      },
      "schemaVersion": 2,
      "restartable": true,
      "workflowStatusListenerEnabled": true,
      "ownerEmail": "lookstorm@163.com",
      "timeoutPolicy": "ALERT_ONLY",
      "timeoutSeconds": 0
   },
   "priority": 0,
   "startTime": 1584255584746,
   "workflowName": "single_restartnn_new",
   "workflowVersion": 1
}

<img width="1485" alt="屏幕快照 2020-03-15 下午3 17 16" src="https://user-images.githubusercontent.com/11346379/76697346-2d27c300-66d1-11ea-876d-4beb4190d776.png">

**Comment by apanicker-nflx** [comment]
@andyyumiao these properties are only used in the async indexing to elasticsearch path to ensure that workflow states are consistently written in order to elasticsearch. What behavior are you trying to modify using the settings?
