### ISSUE TITLE
How to cancel the delay between different subworkflows？

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1584]
It seems have a delay(default 30s) between two subworkflows? How to cancel the delay between different subworkflows？

**My workflow definition：**
{
"name": "single_restartnn",
"description": "Restart namenode.”,
"callbackAfterSeconds": 0,
"version": 1,
"tasks": [{
"name": "stopnn_wf",
"taskReferenceName": "stopnn_wf",
"inputParameters": {
"ipList": "${workflow.input.ipList}",
"cmd": "hadoop_util.stopnn"
},
"type": "SUB_WORKFLOW”,
"callbackAfterSeconds": 0,
"subWorkflowParam": {
"name": "bdpops_auto_deploy",
"version": 1
}

},
{
"name": "startnn_wf",
"taskReferenceName": "startnn_wf",
"inputParameters": {
"ipList": "${workflow.input.ipList}",
"cmd": "hadoop_util.startnn"
},
"type": "SUB_WORKFLOW”,
"callbackAfterSeconds": 0,
"subWorkflowParam": {
"name": "bdpops_auto_deploy",
"version": 1
}
}
],
"outputParameters": {
"cdn_url": "${workflow.output.result}"
},
"restartable": true,
"workflowStatusListenerEnabled": true,
"schemaVersion": 2,
"ownerEmail": "lookstorm@163.com"
}

**A workflow snapshot：**
<img width="1455" alt="snapshot" src="https://user-images.githubusercontent.com/11346379/76697740-e9838800-66d5-11ea-86fa-bff7b655e687.png">

{
   "ownerApp": "",
   "createTime": 1584254853261,
   "updateTime": 1584254915240,
   "status": "COMPLETED",
   "endTime": 1584254915240,
   "workflowId": "a062267f-05a9-498f-a864-bbd0c8e30af0",
   "tasks": [
      {
         "taskType": "SUB_WORKFLOW",
         "status": "COMPLETED",
         "inputData": {
            "workflowInput": {
               "ipList": "2.2.2.2,4.4.4.41",
               "cmd": "hadoop_util.stopnn"
            },
            "subWorkflowTaskToDomain": null,
            "subWorkflowName": "bdpops_auto_deploy",
            "subWorkflowVersion": 1
         },
         "referenceTaskName": "stopnn_wf",
         "retryCount": 0,
         "seq": 1,
         "pollCount": 2,
         "taskDefName": "stopnn_wf",
         "scheduledTime": 1584254853456,
         "startTime": 1584254853826,
         "endTime": 1584254884219,
         "updateTime": 1584254884205,
         "startDelayInSeconds": 0,
         "retried": false,
         "executed": true,
         "callbackFromWorker": true,
         "responseTimeoutSeconds": 0,
         "workflowInstanceId": "a062267f-05a9-498f-a864-bbd0c8e30af0",
         "workflowType": "single_restartnn_new",
         "taskId": "cadbabe3-9899-4a56-9e87-9f905320643f",
         "callbackAfterSeconds": 30,
         "outputData": {
            "cdn_url": null
         },
         "workflowTask": {
            "name": "stopnn_wf",
            "taskReferenceName": "stopnn_wf",
            "inputParameters": {
               "ipList": "${workflow.input.ipList}",
               "cmd": "hadoop_util.stopnn"
            },
            "type": "SUB_WORKFLOW",
            "decisionCases": {},
            "defaultCase": [],
            "forkTasks": [],
            "startDelay": 0,
            "subWorkflowParam": {
               "name": "bdpops_auto_deploy",
               "version": 1
            },
            "joinOn": [],
            "optional": false,
            "taskDefinition": {
               "createTime": 1584253416330,
               "createdBy": "",
               "name": "stopnn_wf",
               "retryCount": 3,
               "timeoutSeconds": 0,
               "inputKeys": [],
               "outputKeys": [],
               "timeoutPolicy": "TIME_OUT_WF",
               "retryLogic": "FIXED",
               "retryDelaySeconds": 60,
               "responseTimeoutSeconds": 3600,
               "inputTemplate": {},
               "rateLimitPerFrequency": 0,
               "rateLimitFrequencyInSeconds": 1,
               "ownerEmail": "lookstorm@163.com"
            },
            "defaultExclusiveJoinTask": [],
            "asyncComplete": false,
            "loopOver": []
         },
         "rateLimitPerFrequency": 0,
         "rateLimitFrequencyInSeconds": 0,
         "workflowPriority": 0,
         "iteration": 0,
         "subWorkflowId": "ffbbf159-b7fb-44ed-bcb3-ef548d611262",
         "taskStatus": "COMPLETED",
         "queueWaitTime": 4142373,
         "loopOverTask": false,
         "taskDefinition": {
            "present": true
         },
         "logs": []
      },
      {
         "taskType": "SUB_WORKFLOW",
         "status": "COMPLETED",
         "inputData": {
            "workflowInput": {
               "ipList": "2.2.2.2,4.4.4.41",
               "cmd": "hadoop_util.startnn"
            },
            "subWorkflowTaskToDomain": null,
            "subWorkflowName": "bdpops_auto_deploy",
            "subWorkflowVersion": 1
         },
         "referenceTaskName": "startnn_wf",
         "retryCount": 0,
         "seq": 2,
         "pollCount": 2,
         "taskDefName": "startnn_wf",
         "scheduledTime": 1584254884242,
         "startTime": 1584254884720,
         "endTime": 1584254915174,
         "updateTime": 1584254915163,
         "startDelayInSeconds": 0,
         "retried": false,
         "executed": true,
         "callbackFromWorker": true,
         "responseTimeoutSeconds": 0,
         "workflowInstanceId": "a062267f-05a9-498f-a864-bbd0c8e30af0",
         "workflowType": "single_restartnn_new",
         "taskId": "8f3f6b50-bc91-4add-8b78-00d3d69a9671",
         "callbackAfterSeconds": 30,
         "outputData": {
            "cdn_url": null
         },
         "workflowTask": {
            "name": "startnn_wf",
            "taskReferenceName": "startnn_wf",
            "inputParameters": {
               "ipList": "${workflow.input.ipList}",
               "cmd": "hadoop_util.startnn"
            },
            "type": "SUB_WORKFLOW",
            "decisionCases": {},
            "defaultCase": [],
            "forkTasks": [],
            "startDelay": 0,
            "subWorkflowParam": {
               "name": "bdpops_auto_deploy",
               "version": 1
            },
            "joinOn": [],
            "optional": false,
            "taskDefinition": {
               "createTime": 1584253416332,
               "createdBy": "",
               "name": "startnn_wf",
               "retryCount": 3,
               "timeoutSeconds": 0,
               "inputKeys": [],
               "outputKeys": [],
               "timeoutPolicy": "TIME_OUT_WF",
               "retryLogic": "FIXED",
               "retryDelaySeconds": 60,
               "responseTimeoutSeconds": 3600,
               "inputTemplate": {},
               "rateLimitPerFrequency": 0,
               "rateLimitFrequencyInSeconds": 1,
               "ownerEmail": "lookstorm@163.com"
            },
            "defaultExclusiveJoinTask": [],
            "asyncComplete": false,
            "loopOver": []
         },
         "rateLimitPerFrequency": 0,
         "rateLimitFrequencyInSeconds": 0,
         "workflowPriority": 0,
         "iteration": 0,
         "subWorkflowId": "92910fd4-407c-4817-9a32-6f9da71c17d5",
         "taskStatus": "COMPLETED",
         "queueWaitTime": 4111415,
         "loopOverTask": false,
         "taskDefinition": {
            "present": true
         },
         "logs": []
      }
   ],
   "input": {
      "ipList": "2.2.2.2,4.4.4.41",
      "cmd": "ls -ls /root1"
   },
   "output": {
      "cdn_url": null
   },
   "workflowType": "single_restartnn_new",
   "version": 1,
   "schemaVersion": 2,
   "taskToDomain": {},
   "failedReferenceTaskNames": [],
   "workflowDefinition": {
      "updateTime": 1584243007810,
      "name": "single_restartnn_new",
      "description": "Restart namenode.",
      "version": 1,
      "tasks": [
         {
            "name": "stopnn_wf",
            "taskReferenceName": "stopnn_wf",
            "inputParameters": {
               "ipList": "${workflow.input.ipList}",
               "cmd": "hadoop_util.stopnn"
            },
            "type": "SUB_WORKFLOW",
            "decisionCases": {},
            "defaultCase": [],
            "forkTasks": [],
            "startDelay": 0,
            "subWorkflowParam": {
               "name": "bdpops_auto_deploy",
               "version": 1
            },
            "joinOn": [],
            "optional": false,
            "taskDefinition": {
               "createTime": 1584253416330,
               "createdBy": "",
               "name": "stopnn_wf",
               "retryCount": 3,
               "timeoutSeconds": 0,
               "inputKeys": [],
               "outputKeys": [],
               "timeoutPolicy": "TIME_OUT_WF",
               "retryLogic": "FIXED",
               "retryDelaySeconds": 60,
               "responseTimeoutSeconds": 3600,
               "inputTemplate": {},
               "rateLimitPerFrequency": 0,
               "rateLimitFrequencyInSeconds": 1,
               "ownerEmail": "lookstorm@163.com"
            },
            "defaultExclusiveJoinTask": [],
            "asyncComplete": false,
            "loopOver": []
         },
         {
            "name": "startnn_wf",
            "taskReferenceName": "startnn_wf",
            "inputParameters": {
               "ipList": "${workflow.input.ipList}",
               "cmd": "hadoop_util.startnn"
            },
            "type": "SUB_WORKFLOW",
            "decisionCases": {},
            "defaultCase": [],
            "forkTasks": [],
            "startDelay": 0,
            "subWorkflowParam": {
               "name": "bdpops_auto_deploy",
               "version": 1
            },
            "joinOn": [],
            "optional": false,
            "taskDefinition": {
               "createTime": 1584253416332,
               "createdBy": "",
               "name": "startnn_wf",
               "retryCount": 3,
               "timeoutSeconds": 0,
               "inputKeys": [],
               "outputKeys": [],
               "timeoutPolicy": "TIME_OUT_WF",
               "retryLogic": "FIXED",
               "retryDelaySeconds": 60,
               "responseTimeoutSeconds": 3600,
               "inputTemplate": {},
               "rateLimitPerFrequency": 0,
               "rateLimitFrequencyInSeconds": 1,
               "ownerEmail": "lookstorm@163.com"
            },
            "defaultExclusiveJoinTask": [],
            "asyncComplete": false,
            "loopOver": []
         }
      ],
      "inputParameters": [],
      "outputParameters": {
         "cdn_url": "${workflow.output.result}"
      },
      "schemaVersion": 2,
      "restartable": true,
      "workflowStatusListenerEnabled": true,
      "ownerEmail": "lookstorm@163.com",
      "timeoutPolicy": "ALERT_ONLY",
      "timeoutSeconds": 0
   },
   "priority": 0,
   "startTime": 1584254853261,
   "workflowName": "single_restartnn_new",
   "workflowVersion": 1
}

**Comment by kishorebanala** [comment]
Closing this issue as it hasn't been active for a while now. Please feel free to re-open if you still have questions or concerns.
