### ISSUE TITLE
Re-index from primary data store to embedded ES

### ISSUE THREAD

**Issue by cschuyle** [Netflix/conductor#1587]
Some use cases call for using an in-memory embedded Elasticsearch.

If using embedded ES, it would be useful to index all the current contents of the primary datastore into ES at application startup time, so that searches have access to the full history of the primary data store.

Since this re-index could take quite a while, it should be done on a background thread in order to not lengthen startup time.

**Comment by apanicker-nflx** [comment]
@cschuyle The usage of in-memory embedded ES is only recommended for testing purposes and for any production use-cases, we recommend using an external ES cluster. In this case, the ES cluster would start to be populated at the same time as that of the primary persistence layer.

**Comment by cschuyle** [comment]
Agreed.  However, not every use case will adhere to those recommendations.  Besides, for testing environments this is a legitimate need.  We have been using a fork in which we have implemented this functionality for MySQL and Redis backing stores.  Perhaps this could be a work in progress, where those who have the need would use and improve the current implementations, and contribute others.  Shall I push a branch?

**Comment by apanicker-nflx** [comment]
@cschuyle I agree that there could definitely be similar use-cases for testing environments. Please feel free to push a branch with your proposed changes. Please also provide documentation about how the re-index feature can be used.
