### ISSUE TITLE
QUESTION : How to get input variables of the Event task in an Event Handler ?

### ISSUE THREAD

**Issue by Arnaud-Francois-Fausse** [Netflix/conductor#1596]
Hi,
I can't manage to get the input values of an Event task in the listening event handler. According to the doc and various examples I came to thus syntax which doesn't work :
{
    "name": "process-actenmd-comornot-eventwf",
    "description": "Receives asynchronous comedec/notComedec result and triggers end of fetch_if_city_commedec_compatible http task",
    "version": 1,
    "schemaVersion": 2,
    "tasks": [
        {
            "name": "trigger_end_fetch_if_city_commedec_compatible",
            "taskReferenceName": "trigger_end_fetch_commedec_compatibility",
            "type": "EVENT",
            "inputParameters": {
                "sink": "conductor",
                "workflowId": "${workflow.input.workflowId}",
                "dematerialise" : "${workflow.input.dematerialise}"
            }
        }
    ],
    "restartable": true,
    "workflowStatusListenerEnabled": true,
    "ownerEmail": "info@gmail.com'
}

Is this syntax correct ? How to get the values workflowId and dematerialise in the Event Handler ?
Thanks a lot

**Comment by kishorebanala** [comment]
@Arnaud-Francois-Fausse I cannot reason what is missing, can you provide more details about the event handler you're trying to setup.

Also. Conductor labs have a complete example of getting Event task and Event handler working together: https://netflix.github.io/conductor/labs/eventhandlers/. Please check this if you haven't already and see if you can correlate this to your workflow.
