### ISSUE TITLE
Event handler to complete HTTP task doesnt' work

### ISSUE THREAD

**Issue by Arnaud-Francois-Fausse** [Netflix/conductor#1598]
Hi,
An HTTP task  is set with "asyncComplete": true. It is pending for the completion event.
The event task sends correctly the expected values (output is correct).
But the HTTP task doesn't resume to end.
What's wrong in this event handler (I also tested wirh "condition":"1==1").

{
  "name" : "comedec_compatibility_found_event_handler",
  "event": "conductor:process-actenmd-comornot-eventwf:trigger_end_fetch_commedec_compatibility",
  "actions": [
    {
      "action": "complete_task",
      "complete_task": {
        "workflowId": "${workflowId}",
        "taskRefName": "fetch_commedec_compatibility",
        "output": {
          "response": "${dematerialise}"
        }
      },
      "expandInlineJSON": true
    }
  ],
  "active": "true"
}

Thank you.
AF

**Comment by anupam587** [comment]
Can someone please look into this issue, since the http tasks are unable to complete . they are always in running mode.
My sample workflow is.
`{
		"name": "test-quick-run-flow",
		"workflowDef": {
			"ownerApp": "test-app",
			"createdBy": "eventbus-backend",
			"name": "test-quick-run-flow",
			"description": "Test Workflow to quickly run and complete workflow to test restart api",
			"version": 1,
			"tasks": [{
				"name": "fetch_http",
				"type": "HTTP",
				"taskReferenceName": "http_test",
				"inputParameters": {
  "http_request": {
    "uri": "https://www.google.com/",
    "method": "GET",
    "accept": "application/json"
  }
}
			}]
		}
	}`

**Comment by Arnaud-Francois-Fausse** [comment]
I have exactly the same problem.

**Comment by kishorebanala** [comment]
Hey @Arnaud-Francois-Fausse @anupam587, What is the state of event handler's complete task execution, when a message is received? Do you see any errors?

Http task's life cycle ends once it moves to `IN_PROGRESS` state with `asyncComplete:true`. Event handler then tries to complete this task, just as `WAIT` or any other asyncComplete task.
