### ISSUE TITLE
Does running data of workflow and task have an expiration date？

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1599]
as title, and use redis as the default storage.

**Comment by mahalaxmiganesh** [comment]
We are also using redis db.
There is no way of setting a expiration time on Conductor for data

Incase of Terminal status workflow - we have tried to implement the Quartz scheduler, leveraging the remove method for workflows with archiveWorkflow option set true, the workflow is archived in the elastic search useful for reporting purpose in our case, after removal from redis..

**Comment by andyyumiao** [comment]
> We are also using redis db.
> There is no way of setting a expiration time on Conductor for data
> 
> Incase of Terminal status workflow - we have tried to implement the Quartz scheduler, leveraging the remove method for workflows with archiveWorkflow option set true, the workflow is archived in the elastic search useful for reporting purpose in our case, after removal from redis..

Ok, I got it, thanks for the reply.

**Comment by apanicker-nflx** [comment]
Workflows do not have an expiration date, however you can use the [Archival Module](https://netflix.github.io/conductor/server/#1-enable-archiving-module) or implement a similar cleanup mechanism by extending the workflow status listener to expire/remove workflows upon completion.
