### ISSUE TITLE
Passing Sensitive Information from a Workflow to a Worker 

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#16]
I am having a generic worker program "`GetFileFromAnyFTPServer`" which I simply pass some parameters (FTP host, username, password, directory, filename) and it downloads the file from this server.

I created a workflow with some inputParameters to be able to pass username/password like this: 

```
    {
      "name": "GetFileFromAnyFTPServer",
      "taskReferenceName": "GetFileFromAnyFTPServer",
      "inputParameters": {
        "ftpHost": "workflow.input.ftpHost",
        "ftpDirectory": "workflow.input.ftpDirectory",
        "ftpFilename": "workflow.input.ftpFilename",
        "ftpUsername": "workflow.input.ftpUsername",
        "ftpPassword": "workflow.input.ftpPassword"
      },
      "type": "SIMPLE",
      "startDelay": 0,
      "callbackFromWorker": true
    },
```

The problem is, that the UI as well as the REST endpoints (e.g. /workflow/{workflowId} ), now show the username and password in cleartext.

Is there any way to more "securely" pass username / password from a Workflow or Task to a worker?

Are there any best-practices you can share with me?

Thanks a lot.

**Comment by v1r3n** [comment]
The worker and server communication is done over the REST endpoints. 
You can configure your tomcat/servlet engine to use HTTPS and use the HTTPS endpoint for the workers to communicate with the server.

**Comment by blueelephants** [comment]
Thanks for your comments.

Using HTTPS would surely help to establish a secure connection between the server and the workers.

But when I use inputParameters to pass on usernames/password, I can see those inputParameters in cleartext in the WebUI - which is not that nice (as everybody with access to the WebUI could see the passwords).

Is there any way to work around this issue in the WebUI?
Maybe some feature like: "sensitiveInputParameters" where values don't get displayed in the WebUI and values cannot be extracted otherwise?

**Comment by v1r3n** [comment]
Having parameters classified as "sensitive" could be a solution to this.  There is no current workaround, but I would think if there are sensitive parameters, you might want to pass around them in encrypted fashion and let the worker decrypt and it use it.  This way, they are protected on the wire, in the workflow's execution store and UI.  Only the Worker who is able to interpret them will be able to decode and use it.

**Comment by blueelephants** [comment]
Yes, that's a nice way to go. Thanks for pointing out this proposal.
