### ISSUE TITLE
conductor.worker.pollCount not supported anymore in worker client?

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1600]
Why no more support for the conductor.worker.pollCount and related system properties for TaskClient? How are the parameters for /tasks/batch/poll configured now in workers?

**Comment by apanicker-nflx** [comment]
@rickfish The pollCount and usage of the `/tasks/batch/poll` API was recently deprecated from the client side implementation. This change also removed the usage of client side queues and replaced this with the the `TaskRunnerConfigurer` and `TaskPollExecutor` which polls for a task only when a thread is idle. The primary motivator for this change was client side queueing led to duplicate executions and timeouts in a few edge cases, also the extra round-trip for the `ack` can be avoided by not using the client side queue.

**Comment by rickfish** [comment]
@apanicker-nflx What is the recommended way to process large volumes of SIMPLE tasks with this new client architecture? Several teams in our enterprise are having to stay at older versions of the client to get the throughput they need. Once their backlog of tasks gets too large, the peeking of messages in the engine starts taking longer and longer as well. What are you recommending to your users in order to increase throughput? The only thing I can think of at this point is to run multiple instances of the worker...

**Comment by apanicker-nflx** [comment]
> The only thing I can think of at this point is to run multiple instances of the worker...

This is the recommended way of running workers. Since the server handles the ack'ing of tasks  before delivering the task to the worker, it ensures that only a single worker instance can process a given task. You can also further increase parallelism by increasing the thread count for your workers within the java client. The client architecture ensures that a task is polled for only when a thread is available for processing the task.

**Comment by rickfish** [comment]
Unfortunately, increasing the worker threads doesn't really help with processing large volumes of quick-to-process SIMPLE tasks. If there is more than one thread per task type, those extra threads really sit idle waiting to be handed a task to process since most times the task processing is simple and one thread can handle what gets returned in the response from the poll. Using multiple instances of the worker JVM versus having a large batch size dramatically increases HTTP traffic through our enterprise. Infrastructure components used for security will be overwhelmed because of that traffic. Getting 100 tasks back on one HTTP request is much more palatable than making 100 HTTP requests. It is also much quicker and drains the queue much faster.

I understand why the change was made to remove batch polling but this is going to cause issues for our users.

Do you know what upcoming release will not support batch polling? We have several teams using Conductor that have a lot of workers in production. They will have to retrofit their workers and move them to production before I can deploy a release of Conductor that does not support it.

**Comment by apanicker-nflx** [comment]
>Do you know what upcoming release will not support batch polling?

This will only be removed in the next major version upgrade (3.0) and will continue to be part of the client library till then. 
On the server side, we would still keep the batch poll API but with the caveat that all tasks in the batch are ack'ed when the server responds.

We understand your concern about increased HTTP traffic caused during polls but in the previous scenario with the batch polls, each task would need to be ack'ed before processing it, so the cumulative HTTP traffic at the end would be similar given that there is no ack HTTP call in the current model.

**Comment by rickfish** [comment]
I didn't think about the ack for every task. Understood now. Thanks for  your patience.
