### ISSUE TITLE
missing runtime data

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1602]
I just used redis cluster as the storage, found that the runtime data was lost after restart conductor server. But the workflow and task defs of metadata not lost and still there.

**My server.properties as below:**
db=redis
workflow.dynomite.cluster.hosts=127.0.0.1:6379:us-east-1e
queues.dynomite.nonQuorum.port=6379
EC2_AVAILABILITY_ZONE=us-east-1e
workflow.elasticsearch.instanceType=memory
workflow.elasticsearch.url=localhost:9300

**Comment by mahalaxmiganesh** [comment]
workflow.elasticsearch.instanceType - This determines the type of ES instance we are using with conductor. The two values are either MEMORY or EXTERNAL. If MEMORY, then an embedded server will be run.  Hence when the Conductor was restarted the ES data which was stored in memory was lost. The Embedded ES creates temp dir in your local, when the instance is started,  EmbeddedElasticSearch::setupDataDir method performs cleanup of the existing temp dir.

**Comment by andyyumiao** [comment]
> workflow.elasticsearch.instanceType - This determines the type of ES instance we are using with conductor. The two values are either MEMORY or EXTERNAL. If MEMORY, then an embedded server will be run. Hence when the Conductor was restarted the ES data which was stored in memory was lost. The Embedded ES creates temp dir in your local, when the instance is started, EmbeddedElasticSearch::setupDataDir method performs cleanup of the existing temp dir.

Ok, if i set the value to EXTERNAL and use the external ES instance, the running data can not be missing?

**Comment by mahalaxmiganesh** [comment]
> > workflow.elasticsearch.instanceType - This determines the type of ES instance we are using with conductor. The two values are either MEMORY or EXTERNAL. If MEMORY, then an embedded server will be run. Hence when the Conductor was restarted the ES data which was stored in memory was lost. The Embedded ES creates temp dir in your local, when the instance is started, EmbeddedElasticSearch::setupDataDir method performs cleanup of the existing temp dir.
> 
> Ok, if i set the value to EXTERNAL and use the external ES instance, the running data can not be missing?

Yes, as mentioned earlier when the Conductor is restarted the Embedded ES instance is destroyed and restarted and hence ES data will be lost.
Mostly using in memory type is good for demo purpose and data will be lost once server dies.

For demo purpose you can also run ES instance in local with instanceType External. you can download the related version jar from here..  https://www.elastic.co/downloads/elasticsearch

**Comment by andyyumiao** [comment]
> > > workflow.elasticsearch.instanceType - This determines the type of ES instance we are using with conductor. The two values are either MEMORY or EXTERNAL. If MEMORY, then an embedded server will be run. Hence when the Conductor was restarted the ES data which was stored in memory was lost. The Embedded ES creates temp dir in your local, when the instance is started, EmbeddedElasticSearch::setupDataDir method performs cleanup of the existing temp dir.
> > 
> > 
> > Ok, if i set the value to EXTERNAL and use the external ES instance, the running data can not be missing?
> 
> Yes, as mentioned earlier when the Conductor is restarted the Embedded ES instance is destroyed and restarted and hence ES data will be lost.
> Mostly using in memory type is good for demo purpose and data will be lost once server dies.
> 
> For demo purpose you can also run ES instance in local with instanceType External. you can download the related version jar from here.. https://www.elastic.co/downloads/elasticsearch

OK，get it,  Many thanks！

**Comment by apanicker-nflx** [comment]
Thank you @mahalaxmiganesh for the responses.
