### ISSUE TITLE
s3 externalPayloadStorage: not passing output from task1 to input of task2

### ISSUE THREAD

**Issue by pweatherby-ccctc** [Netflix/conductor#1603]
Hey Team,

When using release 2.10.1, I've configured a conductor server to use s3 as the external payload storage system as per docs here: https://netflix.github.io/conductor/externalpayloadstorage/ 

When hooking up a client to this server, I've also configured the client to use the externalPayloadStorage system by implementing the ConductorClientConfiguration interface (and returning the appropriate sizes and true for the is-Enabled).

I'm running a workflow with 3 SIMPLE tasks in it. When a Task (lets call it 'Task1') completes, the TaskClient does the appropriate payload size checks and successfully recognizes the need to upload the payload to the s3 location given by a call to the server (via the /externalStorageLocation endpoint). The TaskClient uploads the payload to s3, sets the externalOutputPayloadStoragePath and nulls-out the outputData. So far so good.

But then trouble arises, as the next task, (lets call it 'Task2') in the same workflow is supposed to use that payload (output from Task1) as input. I'd expect the externalInputPayloadStoragePath of Task2 to be populated but neither it nor the inputData are populated which of course, wreaks havoc and all mayhem.

When using the Client-side externalPayloadStorage mechanisms for storing output payloads to s3, is there a way to have that output (either the data or the path) passed as input to the next task?

Note: when setting the Client-side getTaskOutputPayloardThresholdKB to sufficiently high (as to not trigger the client-side logic to attempt to store in s3), the server side is able to store the output payload in s3 and pass the storagePath to the Task2 as the externalInputPayloadStoragePath appropriately. everything seems to work just fine in this case. However, it work be more ideal for the client to upload the output to s3 instead of the server.

Is there a way to do this with the existing code-base? perhaps in a newer (than 2.10.1) release? If not, what class would be responsible for handling the linkage/mapping between task1's externalOutputPayloadStoragePath over to task2's externalInputPayloadStoragePath?

Much Appreciated.

**Comment by apanicker-nflx** [comment]
> Is there a way to do this with the existing code-base? perhaps in a newer (than 2.10.1) release? If not, what class would be responsible for handling the linkage/mapping between task1's externalOutputPayloadStoragePath over to task2's externalInputPayloadStoragePath?

@pweatherby-ccctc I believe this issue has been addressed in a newer release. Please update your conductor server/client to the newest version and you should see that the external payloads are being wired correctly across tasks. We have also added a few [integration tests](https://github.com/Netflix/conductor/blob/master/test-harness/src/test/java/com/netflix/conductor/tests/integration/AbstractWorkflowServiceTest.java#L5505-L5871) to test out these scenarios.

**Comment by pweatherby-ccctc** [comment]
@apanicker-nflx I've updated to the latest version (for both server and client) and the same behavior occurs.

I have found that when posting the task update (using postman directly against the task api), that if the outputData is null and the externalOutputPayloadStoragePath with a value: 
`{
  "workflowInstanceId":"{{workflowId}}",
  "taskId": "{{taskId}}",
  "reasonForIncompletion": "",
  "callbackAfterSeconds": 0,
  "workerId": "{{workerId}}",
  "status": "COMPLETED",
  "outputData": null,
  "outputMessage":null,
  "logs": [],
  "externalOutputPayloadStoragePath": "test/path/to/s3.json"
}`
Then everything works as expected. 
However, if outputData has an empty value: `"outputMessage": {}`, then the externalOutputPayloadStoragePath is ignored and the blank outputData is used. This lines up with line 832 of the WorkflowExecutor (https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L832).

I'm currently debugging our client to make sure that its setting the outputData to null and that there is no objectMapper or other process defaulting the outputData to an empty value.

**Comment by pweatherby-ccctc** [comment]
Upon further testing, I've found that the default behavior for TaskResult is to populate the outputData field with an empty HashMap. see https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskResult.java#L63

This default behavior is ok most of the time; when the client provides an outputData value of either, a legit/populated value, a legit empty {} value, or a null value. However, Its when the client doesn't provide/specify the outputData at all (not included in the payload at all), that the behavior becomes slightly misaligned/wonky. In this case, the TaskResult treats it as a populated, yet empty {}, value; instead of the expected null value.

For my/ccctc usage, the client is currently not including the outputData in the update task http call due to the jackson objectMapper version/settings we have specified client side; its not including any field that has a null value; (as oppose to including it with a null value).

Once I find the fix to this setting, I'll re-test to fully confirm it all, and then close out this issue. 

Unless, @apanicker-nflx, you think it would be better for us to default the outputData of TaskResult to null (instead of empty) in cases where the outputData field is not included at all?

**Comment by pweatherby-ccctc** [comment]
It was indeed an Jackson serialization settings error. adding to the objectMapper a call to setSerializationInclusion to ALWAYS now results in the service-workers/client properly including the outputData field even when it is null.

With the outputData field now being included, everything is back to working as expected.
