### ISSUE TITLE
SCHEDULED tasks being removed from queue when they should not be?

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1607]
While looking at another issue, I noticed this code in Workf;lowExecutor.java in the decide() method that might be removing SCHEDULED tasks from their queue unintentionally when a task is being updated:

```
            if (!outcome.tasksToBeUpdated.isEmpty()) {
                for (Task task : tasksToBeUpdated) {
                    if (task.getStatus() != null && (!task.getStatus().equals(Task.Status.IN_PROGRESS)
                            || !task.getStatus().equals(Task.Status.SCHEDULED))) {
                        queueDAO.remove(QueueUtils.getQueueName(task), task.getTaskId());
                    }
                }
            }
```
Won't this remove SCHEDULED tasks from their queue? Shouldn't it be this instead?

```
            if (!outcome.tasksToBeUpdated.isEmpty()) {
                for (Task task : tasksToBeUpdated) {
                    if (task.getStatus() != null && !(task.getStatus().equals(Task.Status.IN_PROGRESS)
                            || task.getStatus().equals(Task.Status.SCHEDULED))) {
                        queueDAO.remove(QueueUtils.getQueueName(task), task.getTaskId());
                    }
                }
            }
```

I can fix this while I submit my Pull Request for a TERMINATE task change if it was unintentional. Please let me know.

**Comment by apanicker-nflx** [comment]
@rickfish Good catch, thanks for pointing this out. Looking into this further, it seems like a task in SCHEDULED state would not be a part of the list of tasks in `tasksToBeUpdated`. 
So, while your suggestion definitely does fix this, I think we may be able to get rid of the condition `|| !task.getStatus().equals(Task.Status.SCHEDULED)` altogether.
