### ISSUE TITLE
decision task 

### ISSUE THREAD

**Issue by amoolya19** [Netflix/conductor#161]
Hi @v1r3n ,

I was trying to make a decision making task in workflow. workflow takes input as number: <some number>. Based on this number whether its odd or even, decision should be taken. As input is an user input it could be anything . where to have a logic to find out whether the input is even or odd? 

in kitchen example, decisoin task input is like  "oddEven": "${task_2.output.oddEven}". i could not make out how task_2 is generating "0" or "1".

**Comment by v1r3n** [comment]
@amoolya19 this logic will be implemented in a worker that takes the input from workflow and outputs the odd/even as true/false, 1/0 or any other value.  Conductor will not any math out of the box.

**Comment by amoolya19** [comment]
if i implement worker how to use it ? i am using only json based workflow definitions?

**Comment by v1r3n** [comment]
you will implement a new task type (look at the HTTP task implementation) and use it in your json definition with task type as the one you created.

**Comment by amoolya19** [comment]
@v1r3n,

yes, but what i asked is if i implement a new task type say "TEST" how can i import this jar /class into conductor? or do i have to do some configuration for this to make conductor understand this.

com.netflix.conductor.contribs.http.HttpTask is the one you are referring i assume. i dint see worker class impl or WorkflowTaskCoordinator class usage. Is my understanding wrong?

**Comment by amoolya19** [comment]
can we use ecpression in the case ? like this ${workflow.input.number}%2=0

**Comment by v1r3n** [comment]
@amoolya19 we are planning to add expression support for decision task sometime in Q2 of 2017.
