### ISSUE TITLE
io.chaossystems.grpc:grpc-healthcheck:1.0.1. is not resolved

### ISSUE THREAD

**Issue by empty85** [Netflix/conductor#1611]
Hi All,

I just downloaded the conductor project from github. (Not able to clone is due to restrictions on my machine)

Tried this with dev and 2.0 branches.

When I am running this. I dunno why this is getting downloaded from jcenter instead of repositories{ maven { url "https://dl.bintray.com/chaos-systems/mvn" } }
$ ./gradlew build

Task :conductor-grpc:extractProto FAILED

FAILURE: Build failed with an exception.

What went wrong:
Could not resolve all files for configuration ':conductor-grpc:protobuf'.
Could not resolve io.chaossystems.grpc:grpc-healthcheck:1.0.1.
Required by:
project :conductor-grpc
Could not resolve io.chaossystems.grpc:grpc-healthcheck:1.0.1.
> Could not get resource 'https://jcenter.bintray.com/io/chaossystems/grpc/grpc-healthcheck/1.0.1/grpc-healthcheck-1.0.1.pom'.
> Could not GET 'https://jcenter.bintray.com/io/chaossystems/grpc/grpc-healthcheck/1.0.1/grpc-healthcheck-1.0.1.pom'.
> Connect to jcenter.bintray.com:443 [jcenter.bintray.com/54.191.3.105] failed: connect timed out

**Comment by kishorebanala** [comment]
@empty85 Are you behind a proxy that could possibly block connections to jcenter? Please try it on an unrestricted laptop and/or connection.

**Comment by empty85** [comment]
@kishorebanala Thanks for replying back. jcenter is accessible and able to download all libraries via jcenter. But this specific library is not in jcenter, instead its available her: { maven { url "https://dl.bintray.com/chaos-systems/mvn" } } But when I am running gradle build its trying to fetch this library from jcenter and failing
