### ISSUE TITLE
About the performance

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1619]
I used Mysql as the storage, based on this, i have two questions:
1.The max task size for one workflow？
2.The max concurrent sub task for one task?
3.Is there a performance bottleneck？

**Comment by apanicker-nflx** [comment]
@s50600822 @mashurex Can you please share your experience with using MySQL as the persistence layer for Conductor which would help answer the above questions.

**Comment by mashurex** [comment]
The `json_data` column in the `workflow` table is a `MEDIUMTEXT` column which has about 16MB max size and all task data is currently stored in that column for a workflow, which means a single workflow cannot have more than about 16MB total input/output data in persistent storage. 

However,  Conductor can be configured to externalize the data so this limitation can be worked around.

As far as performance bottlenecks, the biggest issues seem to be in polling the queues for tasks in a high concurrency environment, but I don't have any specific numbers.

**Comment by andyyumiao** [comment]
> The `json_data` column in the `workflow` table is a `MEDIUMTEXT` column which has about 16MB max size and all task data is currently stored in that column for a workflow, which means a single workflow cannot have more than about 16MB total input/output data in persistent storage.
> 
> However, Conductor can be configured to externalize the data so this limitation can be worked around.
> 
> As far as performance bottlenecks, the biggest issues seem to be in polling the queues for tasks in a high concurrency environment, but I don't have any specific numbers.

@mashurex many thanks for the reply, it's very useful.
