### ISSUE TITLE
Conductor Failover

### ISSUE THREAD

**Issue by clari-akhilesh** [Netflix/conductor#162]
One area that seems not quite as robust is around detection of a worker going down.  Specifically, let's say I have a task X that is defined to have a very long timeout period (let's say several days), and such a task starts to execute on a worker and is acknowledged as in-progress.   Some short time later, the worker node dies (perhaps the JVM ran out of memory).  How does the orchestrator detect this condition and restart the task in question?  Does it have to wait until the 3 day timeout period expires? Or is there some other kind of heartbeat mechanism that would detect this condition earlier?

On the flip side of that same equation is the question of how can a worker be assured that the server doesn’t think it has timed out?  For example, let's assume a task has a relatively small timeout period of 2 minutes.  Our worker starts execution and acknowledges.  However, shortly thereafter, the JVM pauses for GC for 3 minutes.  The task starts re-executing after the pause completes, but it is already outside the timeout window, and presumably, the orchestrator has detected timeout and started the same task running on some other worker.  We want to ensure exactly-once execution semantics for the tasks - how can we detect and avoid these sorts of scenarios?

**Comment by v1r3n** [comment]
@clari-akhilesh given the tasks are running in remote workers Conductor has no knowledge of them being active once ack has been received.  However, to address the situation you described, we have thought about introducing `heartbeat` that will allow Conductor to detect a terminated worker (if there is no heartbeat received within a set time) and reschedule the task.  No prioritization of the work yet as we are still gathering requirements and potential use cases for such support.

To address the other question, GC pauses can cause issues with timeouts, so you want to keep the timeouts sufficiently large enough depending upon your application/worker's GC ergonomics.  
Exactly once semantics are harder to achieve in distributed systems - so we only guarantee at-least once semantics, but on the worker side you can maintain the state in a separate database or something to ensure if the task get re-queued the work is not duplicated.

It will be really interesting to find out your thoughts about implementing exactly-once semantics for your use cases.
