### ISSUE TITLE
gRPC

### ISSUE THREAD

**Issue by BohdanPr** [Netflix/conductor#1622]
Hi All,

I am trying to create a gRPC client for the conductor server using .Net Core. But I have a problem with the connection to the server: `Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Error starting gRPC call: The SSL connection could not be established, see inner exception.")`
Could you explain how to configure the gRPC server or share a link on the documentation which could explain this process?

**Comment by kishorebanala** [comment]
@BohdanPr It doesn't seem like Conductor specific issue, and quick search through gRPC dotnet revealed this: https://github.com/grpc/grpc-dotnet/issues/792, which might be of help to you.
