### ISSUE TITLE
Task execution

### ISSUE THREAD

**Issue by clari-akhilesh** [Netflix/conductor#163]
Are there any facilities for pausing or cancelling an in-progress task?  Or is this only at the level of the workflow?  If a workflow is cancelled, what happens to the tasks it was currently running?  Are they simply abandoned?  Does the orchestrator wait for them to complete prior to cancelling?  Is it possible that the cancelled workflow could later be restarted and result in re-running the task that was abandoned when the last workflow was cancelled?   We need to understand how much control is possible at the task level, and also whether there are certain sequences of operations at the level of the workflow that can result in tasks being run more than once.
Ultimately, we need a strong understanding of whether the task can rely on the orchestration layer to ensure exactly-once execution semantics, or it needs to be written in such a way that it can handle two versions of the task executing concurrently.

**Comment by v1r3n** [comment]
@clari-akhilesh Tasks are running in remote workers outside the control of Conductor server.  When a workflow is cancelled / terminated, the running tasks continue to execute (except as described in cases below).  Once the task completes and updates the status to Conductor, conductor treats that as NOP.  

If your tasks are running in remote workers with a way to terminate them (e.g. containers) you can implement a `WorkflowSystemTask` and execute them on a remote/local server, in that case the `cancel` method implementation can be used to terminate the running instances of the tasks.

We use this mechanism to start and manage the remote tasks running in containers. `start` method spawns the container and starts the task execution, but if the workflow is cancelled, the `cancel` method talks to the container orchestrator to terminate the container and stop the task progress.

Hope this helps.

**Comment by clari-akhilesh** [comment]
NOP is NoOp, I presume.
If it's not too much to ask, could you give an example of cancelling tasks using containers? Perhaps, add it in the documentation? Thanks!

**Comment by v1r3n** [comment]
@clari-akhilesh we work with container as a service infrastructure so scheduling is an HTTP call and cancelling is another HTTP call to cancel the running container.  the implementation will vary based on the orchestration service you use for containers.

In essence, it is an extension of HTTP task where the `start` method spins up a new container and `cancel` method implementation makes another call to the infra to terminate the container.
