### ISSUE TITLE
How to display or get execution log when task in running?

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1633]
As title, i want to know the progress of a task, and a lot of output will be generated during task running. (but the conductor task log will be displayed only when the task ends).

**Comment by s50600822** [comment]
"conductor task log will be displayed only when the task ends" - not true it display when the worker report to conductor. So make your worker send log back and you'll see. 
Note that currently you might only be able to see 10 entries because https://github.com/Netflix/conductor/pull/1630

**Comment by leissen** [comment]
@s50600822 Could you help to give a code sample to show how to send log back during worker running? Thanks in advance.

**Comment by andyyumiao** [comment]
> @s50600822 Could you help to give a code sample to show how to send log back during worker running? Thanks in advance.

In execute method of your worker, just like:
**TaskResult result = new TaskResult(task);
result.log("......");
result.setStatus(TaskResult.Status.IN_PROGRESS);
return result;**

**Comment by andyyumiao** [comment]
> "conductor task log will be displayed only when the task ends" - not true log can be displayed as worker report to conductor. So make your worker send log back and you'll see.
> Note that currently you might only be able to see 10 entries because #1630

yes, many thanks for your help!!! And that PR#1630 is very useful for me.

**Comment by andyyumiao** [comment]
> "conductor task log will be displayed only when the task ends" - not true log can be displayed as worker report to conductor. So make your worker send log back and you'll see.
> Note that currently you might only be able to see 10 entries because #1630

yes, many thanks for your help!!! And that PR#1630 is very useful for me.
