### ISSUE TITLE
Conductor at scale

### ISSUE THREAD

**Issue by JayantaP** [Netflix/conductor#1635]
Hi all,

We are planning to use Conductor as workflow engine in our SaaS application. We were doing some load testing during past few weeks with various combinations and tried to come up with some sizing benchmarks. 
Given the nature of our application, it is important to be able to have horizontal scale-out. There is no overall upper limit on number of workflows executed. We need to benchmark on how many workflows can run on a single pod and then extrapolate that to n number of pods.

The simplest of the workflows have around 40-50 tasks in it. The more complex ones can have 80-100 tasks each, included in 4-5 sub-workflows. Our starting load is 60k workflows per hour, but will increase with number of customers. We can add more pods and nodes as the load increases, but Conductor and the persistence layer should scale horizontally with that kind of load.

For all our tests, async.indexing.enabled was set to true.

It will be a great help if you could clarify or confirm some of our observations listed below: 

1. For 30k workflows per hour (with 40 tasks per workflow), the server pod metric shows a 600 Mi memory and 1200m cpu usage. Whereas the dynomite pod seems to consume a lot more resources, close to 4000 Mi memory and more than 2000m cpu. Is this a normal observation or we are doing something wrong?

2. The workflow completion time steadily increase with load. For a single workflow (40 tasks) executed in isolation, Conductor adds 3-5 seconds of extra to the overall execution time. Whereas, for the same workflow executed 30k per hour, it adds around 90 seconds to the total execution time. Is this a normal observation?

3.  We tried with MySQL (in fact started with that), it added a minimum of 4 mins 30 secs to total workflow execution time with 6000 workflows per hour. With 30k workflows per hour, some of the workflows took more than hours to complete. The MySQL memory was 400m CPU and around 2800 Mi memory. We ran MySQL engine on host, on single pod and on 2 pods, the results were similar. It was a little surprising. Do you think we can even try MySQL for the scale we are talking about?

4. We tried with AMQP, but the results were worse. We could not go beyond 6-7K workflows per hour. We observed that the task handler is synchronous and that is taking bulk of time, while the messages in RabbitMQ topic was piling up. Is there a reason why the task handler is synchronous? 

It will be a great help if you could answer some of these questions.

**Comment by JayantaP** [comment]
5. Do you think Cassandra can give better results than dynomite in scale-out architecture?

**Comment by JayantaP** [comment]
6. We were trying scale-out dynomite. Had 2 server pods and 2 dynomite pods. Looks like all requests are going to one of the dynomite pods. 

The connection string is provided as: 
workflow.dynomite.cluster.hosts=dynamodb-0:8102:us-east-1c;dynamodb-1:8102:us-east-1c

Dynomite Statefulset yml:
apiVersion:  apps/v1
kind: StatefulSet
metadata:
  name: dynomite
spec:
  serviceName: "dynomite"
  replicas: 2
  selector:
    matchLabels:
      app: dynomite
  template:
    metadata:
      labels:
        app: dynomite
    spec:
      containers:
      - image: <repo>/dynomite:latest
        name: dynomite
        ports:
        - containerPort: 8102
          name: dynomite
        resources:
           requests:
             memory: 1000Mi
             cpu: 250m
           limits:
             memory: 2000Mi
             cpu: 750m

**Comment by flavioschuindt** [comment]
We are observing the same behavior as described in (1) above. Any thought?
