### ISSUE TITLE
Update Task wrt workflowId and TaskRefName

### ISSUE THREAD

**Issue by kushalhalder** [Netflix/conductor#1636]
Is there a possibility to complete/update a task by passing only the workflowId and the taskrefname from the wrokflow definition?

**Comment by andyyumiao** [comment]
The first API of Task Management in Conductor swagger API:  **Update a task**

**Comment by kishorebanala** [comment]
@kushalhalder update task endpoint expects TaskResult payload, which has taskId. One possible way is to use Event handler to complete the task, and complete the message with Conductor event. https://netflix.github.io/conductor/configuration/eventhandlers/#actions

**Comment by kushalhalder** [comment]
Yeah. I did the event handler way to solve this.
