### ISSUE TITLE
Webpack@2.2.1 Help wanted!!!

### ISSUE THREAD

**Issue by ramyavakity** [Netflix/conductor#1638]
We did upgrade the webpack version to 2.2.1 due to some vulnerability checks and facing issues.

**Comment by kishorebanala** [comment]
@ramyavakity Please provide more details about the issue you're facing.

**Comment by ramyavakity** [comment]
Hey Kishore,

I did upgrade webpack version and see some random errors in the terminal.
Please help me figure out this.

![image](https://user-images.githubusercontent.com/16482787/79279750-b707af00-7e7c-11ea-94d3-b1cecaa21c60.png)
