### ISSUE TITLE
Events get parked if the respective Task has not been activated yet.

### ISSUE THREAD

**Issue by kushalhalder** [Netflix/conductor#1640]
Scenario:
1. Workflow has 2 consequent wait tasks.
2. These wait tasks have event handlers attached to them which is triggered by other workflows.

Partial flow: Start => Task_1 => ... => Wait Task A => ... => Wait Task B => Task_n => fin.

Event Handlers: 
1. EH_A to complete Wait Task A
2. EH_B to complete Wait Task B 

Happy flow: 
The external workflows run synchronously. Timing of events:
1. Wait Task A is activated, then we receive EH_A
2. Wait Task B is activated, then we receive EH_B
In this scenario, the tasks acknowledge the events and the workflow moves on.

Error scenario: 
Timing of events:
1. receive EH_B, but Wait Task B is inactive
2. receive EH_A and Wait Task A was active.
In this scenario, Wait Task A is marked complete, but the EH_B event is parked and the Wait Task B never acknowledges the event.

Is this is a bug or a part of the design?

**Comment by apanicker-nflx** [comment]
> Wait Task A is marked complete, but the EH_B event is parked and the Wait Task B never acknowledges the event.

@kushalhalder This observation is correct. This is part of the current design where only events that are received after the task is put into progress are processed and considered active. If an event is received and no corresponding task is found for the event, such an event will be dropped.

**Comment by kunalgithub** [comment]
Is there a way to handle such scenario - like writing a SIMPLE task which Queues these messages and then deliver the EVENT ? :( anything that is planned out in future ?

**Comment by kunalgithub** [comment]
> Scenario:
> 
>     1. Workflow has 2 consequent wait tasks.
> 
>     2. These wait tasks have event handlers attached to them which is triggered by other workflows.
> 
> 
> Partial flow: Start => Task_1 => ... => Wait Task A => ... => Wait Task B => Task_n => fin.
> 
> Event Handlers:
> 
>     1. EH_A to complete Wait Task A
> 
>     2. EH_B to complete Wait Task B
> 
> 
> Happy flow:
> The external workflows run synchronously. Timing of events:
> 
>     1. Wait Task A is activated, then we receive EH_A
> 
>     2. Wait Task B is activated, then we receive EH_B
>        In this scenario, the tasks acknowledge the events and the workflow moves on.
> 
> 
> Error scenario:
> Timing of events:
> 
>     1. receive EH_B, but Wait Task B is inactive
> 
>     2. receive EH_A and Wait Task A was active.
>        In this scenario, Wait Task A is marked complete, but the EH_B event is parked and the Wait Task B never acknowledges the event.
> 
> 
> Is this is a bug or a part of the design?

@kushalhalder How did go about the implementation of such scenario ?

**Comment by kushalhalder** [comment]
I am afraid that I did not do a good job :| @kunalgithub 

I created a small **service**, which **receives the events**, and these events have a lifecycle: **SCHEDULED, COMPLETE**. (I wanted to add In-Progress but it was not required by design).
The Wait tasks have been configured to be **SIMPLE** tasks by **definition**. 
The service also implements **Conductor Workers** for each of the Wait Tasks, these **poll** the Conductor-Server for tasks
```
if task found from conductor-server then
  find event
    if event exists, ack task 
else do nothing
```
If you don't send an acknowledgement, the conductor re-schedules the job. We can set a decent **poll interval** to avoid bombarding the server. 

One obvious improvement is to **poll tasks in batches.** 

Another design thought can be: Start => Task_1 => Task_2 => **KafkaTask** => WaitTask => Task_n => fin and the separate **Events service** that I mentioned earlier.
1. Push an event to **Kafka** with the WaitTask details namely: **taskRefName** and **workflowId**, and other payload.
1. The Wait task becomes a **WAIT** Task by definition.
2. The Service implements **KafkaConsumers** listening for the tasks on the Kafka Topic
3. When a Consumer receives a message, it checks for the events. The Consumer can make the `/tasks/in_progress/{workflowId}/{taskRefName}` **API** call to fetch the task details and update it's status
4. **Ack** the Kafka message accordingly. **Retry** the message if there are no events against it at that time. 

I don't like this approach because a Task in the workflow needs to know the context of the next task, which sounds wrong to me from a separation of concerns perspective. However, this solution will not bombard the system with task polls, which is a bigger concern. 

Anyway, do share your approach too when you finalise one.

**Comment by kushalhalder** [comment]
@apanicker-nflx Hey, is there any solution to the above issue in the new versions?
