### ISSUE TITLE
Using Cassandra and Redis DAOs together

### ISSUE THREAD

**Issue by rksinha** [Netflix/conductor#1641]
Hi,
I see recently there is an addition of Cassandra MetaData and EventHandler DAO, but still, Queue and RateLimiting DAO is missing. 
Is there any plan in near future for these DAOs addition?
Is it possible to use REDIS Queue and RateLimiting DAO with the rest of Cassandra DAOs 
and is it advisable?

@kishorebanala @v1r3n @apanicker-nflx @manan164 @mudit3774

**Comment by apanicker-nflx** [comment]
@rksinha Given the pluggable nature of each DAO implementation, you can mix and match any of these implementations together.
In our deployment today, we are using Dynomite (Redis) for queues and rateLimiting with Cassandra as the persistence layer for metadata and executions.

We do not plan to implement a queuing layer in Cassandra.
