### ISSUE TITLE
Why does the DO_WHILE task require a task definition?

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1642]
Why the need for a task definition for the DO_WHILE task? This makes it difficult to specify no timeout and I don't see the need for it. Seems like it is only used to bring in the defaults of rateLimitPerFrequency and rateLimitFrequencyInSeconds. Why not just set those to defaults if no task definition? Am I missing something? Can I remove the requirement for it in DoWhileTaskMapper.java?

**Comment by manan164** [comment]
Yes @rickfish , We can remove it. Please remove it.

**Comment by rickfish** [comment]
@manan164 Thanks, I created PR #1645 to make the task definition optional.
