### ISSUE TITLE
Workflow Creation - V0 Allowed or is it a dry run

### ISSUE THREAD

**Issue by maheshyaddanapudi** [Netflix/conductor#1647]
Create a workflow (i.e. metadata/workflow POST) with workflow version as 0 ? Apparently a 204 response, which is a successful workflow creation response, is recieved but the workflow isn't persisted. A GET workflow request is performed, the version 0 workflow doesn't appear in the list.
It's there any specific reason for this behaviour?

**Comment by apanicker-nflx** [comment]
Workflow with version 0 is supported. 

>but the workflow isn't persisted.

Can you provide more details about your setup? What persistence layer are you using? Can you also provide your workflow definition?

**Comment by maheshyaddanapudi** [comment]
Hi Anoop

I have tried in memory, embedded MariaDB4j, external MySQL persistence and with all of these, the result is the same. 

I will soon try to replicate the issue and provide the workflow json request.
