### ISSUE TITLE
Modifying the response based on decision case.

### ISSUE THREAD

**Issue by vamsibandarupalli** [Netflix/conductor#1652]
Hi,

I was trying to modify the response from one task output based on the decision case.

"caseExpression": "for (var i=0; i<$.outputAssignedValue.length; i++) {if($.outputAssignedValue[i]  ==  null) {'true';} else{'default';}}",
            "scriptExpression": null,
            "decisionCases": {
                "true": [
                    {
                        "name": "some_task",
                        "taskReferenceName": "simpleValueModifycations",
                        "inputParameters": {
                            "$.outputAssignedValue[i]": "10",
                        },

Not able to modify the original Value inside decision case.

**Comment by apanicker-nflx** [comment]
This is not supported. The keys in the inputParameters are not evaluated using JSONPath. Only the values in the map can be evaluated.
