### ISSUE TITLE
Not able to access the "i" value inside the condition task which is used in for loop of decision case.

### ISSUE THREAD

**Issue by vamsibandarupalli** [Netflix/conductor#1654]
Hi, 

I was trying to access the "i" value which used in for loop of decision case. Trying to access it inside the descision case task.

"caseExpression": "for (var i=0; i<$.hits_array.length; i++) {if($.hits_array  !=  null) {'true';} else{'default';}}",
            "scriptExpression": null,
            "decisionCases": {
                "true": [
                    {
                        "name": "some_task",
                        "taskReferenceName": "simpleDecisionMerge",
                        "inputParameters": {
                            "i_value": "i",

but "i_value" not getting populated with the integer value used inside the forloop is there a way to access the "i" value inside the decision task?

**Comment by apanicker-nflx** [comment]
Same as #1652, the keys are not available for JSONPath evaluation.
