### ISSUE TITLE
This does not work in go client 

### ISSUE THREAD

**Issue by zhou6675021** [Netflix/conductor#1659]
HI，
I made a sample according to the official website, but the task was received but not executed,code：

	c := conductor.NewConductorWorker("http://172.16.249.61:8080/api", 1, 10000)

	c.Start("test1", task.Create_Emr_Task, false)

func Create_Emr_Task(t *task.Task) (taskResult *task.TaskResult, err error) {
  //...//
}

Console log：
![image](https://user-images.githubusercontent.com/23535473/80475399-65cae580-897b-11ea-98f6-a777a404db1c.png)

The task was received but not executed， 
Forgive me newbie

**Comment by apanicker-nflx** [comment]
@zhou6675021 I see that you are using the go client for this purpose. The concept of `ack`ing a task has been deprecated and is no longer used. However, this change has not been propagated to the go client. Once a task is polled, it is expected that it will be executed by the worker and a response will be sent to the server within the `responseTimeoutSeconds`. 

A very simple example to get started with using Conductor is available [here](https://netflix.github.io/conductor/labs/beginner/). As seen here, the task is polled and a response is sent after with the execution result (ack is not sent).
