### ISSUE TITLE
Detail for extending EventQueueProvider.

### ISSUE THREAD

**Issue by lydialmr120** [Netflix/conductor#168]
I will extend event queue from kafka, can you give me more information about how to extend EventQueueProvider? Thank you very much!

**Comment by v1r3n** [comment]
Take a look at the following:

https://github.com/Netflix/conductor/blob/master/contribs/src/main/java/com/netflix/conductor/core/events/sqs/SQSEventQueueProvider.java

The key is to register:

https://github.com/Netflix/conductor/blob/master/contribs/src/main/java/com/netflix/conductor/core/events/sqs/SQSEventQueueProvider.java#L49

You will also need to extend the enums:

https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/events/EventQueues.java
