### ISSUE TITLE
Streaming flow of data to task

### ISSUE THREAD

**Issue by jsep925** [Netflix/conductor#1680]
Is conductor already support streaming data for HTTP task or other type of task?
Based on https://netflixtechblog.com/evolution-of-netflix-conductor-16600be36bca, 
is it roadmap or already implemented?

**Comment by apanicker-nflx** [comment]
@jsep925 This is still on the roadmap and will likely be implemented in the next major version upgrade of Conductor (3.x). The DO_WHILE task is available if that fits your use-case.
