### ISSUE TITLE
/workflow/<wfname>/correlated/<corrid>VERY SLOW if many workflows with that corr id

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1681]
The ExecutionDAO.getWorkflowsByCorrelationId() method has only correlation id as a parameter. There is no additional method that also passes in the workflow name. So on the /workflow/wfname/correlated/corrid endpoint there is no way to do a query that joins in the workflow_def_to_workflow table to get back just the workflows for that workflow name that have that correlation id. This is a problem, especially if there are several records in the workflow table that have the same correlation id, even though they are for different workflow names. 

The existing logic has to query the workflow table for all workflows with that correlation id, then get each workflow individually. If includeTasks is true all the tasks will be retrieved too. Only then do the results get filtered by workflow name.

In our case, the correlation id was '3' and there were 11,945 workflows with that correlation id but only 19 were for the workflow name specified. It took more than a minute to do that in our database that has millions of rows.

I would propose that an additional getWorkflowsByCorrelationId() method is added to all the ExecutionDAO-derived classes that takes the workflow name as a parameter. This would mean that all implementations would have to be changed. Is this something I should attempt to do? Is there a reason why this was not done?

**Comment by apanicker-nflx** [comment]
@rickfish I believe that this can be accomplished using the `/workflow/search` endpoint. Both the correlationId and workflowType are indexed fields and can be used for this purpose. Would this suffice your use-case?

**Comment by rickfish** [comment]
Yes, this can be accomplished with the /workflow/search endpoint. But that is like saying don't use the /workflow//correlated/ endpoint because it could be really slow. At that point, that endpoint would not be used so why even have it? That endpoint should be optimized I think. Since the workflow name is part of the endpoint path, why not pass it into the method that is supposed to retrieve those workflows?

**Comment by apanicker-nflx** [comment]
@rickfish Ahh I misunderstood the earlier comment. I believe the method implementation needs to be changed to retrieve only the correlated workflows of a specific type. I have labeled this as a bug and we will look into fixing this API soon. Thanks for reporting.

**Comment by apanicker-nflx** [comment]
Fixed in #1766
