### ISSUE TITLE
Avoid duplicate task definitions when using decisions

### ISSUE THREAD

**Issue by mcancio** [Netflix/conductor#1683]
Hi Team,
I am trying to create a very simple workflow described in the diagram. (see red dashes please).
However, I'm forced to define the tasks T3, T4 and T5 under both decision D1 and D2.
Is there a way to "go to" T3 when D1 result is 1?

![image](https://user-images.githubusercontent.com/58673273/81825942-d3753500-9569-11ea-9255-d6e6f4ed5a5a.png)

Appreciate the guidance on this.

**Comment by elisherer** [comment]
https://github.com/Netflix/conductor/pull/1373
Maybe someday...

**Comment by mcancio** [comment]
> #1373
> Maybe someday...
> 
> And to your diagram, I would suggest to connect D1 to D2, and use the `D1.output.caseOutput` to forcibly decide to go to D2/1.

:) Thanks for the reply. I had to wrap the tasks 3, 4 and 5 in a sub workflow, then call the subworkflow (with same taskReferenceName) from D1 and D2. It minimize the repeated coding of tasks at the expense of more workflow definitions.
