### ISSUE TITLE
Conductor docker image fail to register task

### ISSUE THREAD

**Issue by miguelC** [Netflix/conductor#1687]
Hi, I am brand new to conductor so I still don't understand completely what goes on under the hood. I am running the docker images by using docker-compose and I can see the following running on my docker desktop (MacOS):
conductor:ui                                          0.0.0.0:5000->5000/tcp   
conductor:server                                      8090/tcp, 0.0.0.0:8088->8080/tcp  
docker.elastic.co/elasticsearch/elasticsearch:5.6.8   0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp 
v1r3n/dynomite                                        8101/tcp, 22122/tcp, 22222/tcp, 0.0.0.0:8102->8102/tcp 

I am getting this error when I call /api/metadata/taskdefs:

169704475 [pool-2-thread-1] DEBUG com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Updating hosts: UP=[Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null, password=null]], DOWN=[]
169704475 [pool-2-thread-1] DEBUG com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - HostConnectionPool already exists for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null, password=null], ignoring addHost
169705743 [pool-2-thread-1] DEBUG com.netflix.dyno.connectionpool.impl.health.ConnectionPoolHealthTracker  - Running, pending pools size: 0
169708510 [pool-5-thread-1] DEBUG com.netflix.dyno.connectionpool.impl.health.ConnectionPoolHealthTracker  - Running, pending pools size: 0
169715713 [pool-2-thread-1] DEBUG com.netflix.dyno.connectionpool.impl.health.ConnectionPoolHealthTracker  - Running, pending pools size: 0
169716269 [qtp1069131391-66] ERROR com.netflix.conductor.server.resources.GenericExceptionMapper  - Error PoolTimeoutException url: 'metadata/taskdefs'
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$VoidOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:167)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)

The response body is:
`{
    "code": "INTERNAL_ERROR",
    "message": "INTERNAL_ERROR - PoolTimeoutException: [host=Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null, password=null], latency=800964(0), attempts=0]Fast fail waiting for connection from pool",
    "retryable": false,
    "instance": "93ad7a567e40"
}`

I did not modify any configuration files in the docker containers so this is from a  fresh run from docker. 
I appreciate any help to get me started.
Thanks.

**Comment by kishorebanala** [comment]
Hey @miguelC, It's not clear from the logs about what is happening. My best guess from the debug logs is that post 8102 is taken by some other service, and unable to map to dynomite.

Can you try debugging backwards, and see if you can connect to dynomite server.
