### ISSUE TITLE
[Conductor UI]: Do while is not showing looped lambda task for each iteration in UI under task details but works fine

### ISSUE THREAD

**Issue by simarpal** [Netflix/conductor#1696]
**Scenario**: I have looped an Http and Lambda task in Do While.
**When**: On executing do-while
**Excepted Result**: For every iteration, Conductor UI's task details tab should show Http and Lambda tasks.
**Actual Result**: For every iteration, Conductor UI's task details tab shows Http task only. It shows the Lambda task for first iteration only.

However, the working of the Lambda task is fine. The input of http task is dependent on Lambda task and for each iteration of http task, I can see a proper input.

Example
![DoWhileLoopedLambdaProblem](https://user-images.githubusercontent.com/25483663/82485145-fd1de700-9aa8-11ea-9c51-c3c5a6a94632.PNG)

**Comment by manan164** [comment]
Hi @simarpal , This is being discussed in another thread. It looks like sequence number issue. That is the reason you are not able to see the tasks. You can check do_while task output there you will see all the output.

**Comment by simarpal** [comment]
Hi @manan164, Thanks for the reply.
Yes, in do while output I can see the lambda task response.
Can you please tell me the issue number in which this is discussed and will there will be a fix for this.

**Comment by apanicker-nflx** [comment]
@simarpal Thanks for reporting the issue. We will look into releasing a fix soon. In the meantime, please feel free to contribute a fix for this.
