### ISSUE TITLE
Securing HTTP REST Endpoints

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#17]
Currently, it seems to no authentication/token/etc. is needed to access the REST endpoints.

So, basically
- "every evil" person could create/update/start workflow definitions
- "every evil" worker program could poll for tasks via /tasks/poll/{tasktype} and prevent workflow execution.
- etc.

Are there currently any features available to secure (some kind of authentication and authorization) the endpoints?

Thanks a lot.

**Comment by v1r3n** [comment]
Conductor endpoints can be secured by the container on which it is deployed.  Depending upon the app server you can use the container specific security mechanism to secure the endpoints.

**Comment by blueelephants** [comment]
Great - thanks for clarification.
