### ISSUE TITLE
redis lock with sentinel missing masterName

### ISSUE THREAD

**Issue by zodiac1214** [Netflix/conductor#1700]
according to https://github.com/redisson/redisson/wiki/2.-Configuration#27-sentinel-mode
we should call setMasterName() here: https://github.com/pavelhalabala/conductor/blob/master/redis-lock/src/main/java/com/netflix/conductor/locking/redis/config/RedisLockModule.java#L75

checking the https://github.com/pavelhalabala/conductor/blob/master/redis-lock/src/main/java/com/netflix/conductor/locking/redis/config/RedisLockConfiguration.java, i don't see a property defined for master name using sentinel.

**Comment by zodiac1214** [comment]
![image](https://user-images.githubusercontent.com/24868108/82558446-a0b7d780-9b3b-11ea-8447-1f0b89db3750.png)

**Comment by kishorebanala** [comment]
Hey @zodiac1214, Thanks for reporting this. Does adding it to the Sentinel configuration work for you? If so, can you send us a PR with the same.

**Comment by swayamraina** [comment]
Hi, I believe adding a property under `server.properties` with other `redis.lock.server` properties fixes this.
Also we need to add this property while creating the `reddison config`
