### ISSUE TITLE
docker-compose fails on building conductor-ui image

### ISSUE THREAD

**Issue by patrick-pt** [Netflix/conductor#1707]
Howdy - following the steps in the [Architecture](https://netflix.github.io/conductor/architecture/#or-start-all-the-services-using-docker-compose) page, `docker-compose up` exits with error on the Master branch and tag v2.27.1 when attemtping to build conductor-ui. 

```
Step 8/11 : RUN cd /app/ui   && npm install   && npm run build --server
[...]
[10:27:11] Finished 'server-bundle' after 36 s
[10:27:12] The following tasks did not complete: build, <parallel>, public
[10:27:12] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nf-workflow-ui@1.0.0 build: `gulp build --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nf-workflow-ui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-26T10_27_12_441Z-debug.log
ERROR: Service 'conductor-ui' failed to build: The command '/bin/sh -c cd /app/ui   && npm install   && npm run build --server' returned a non-zero code: 1
```

I haven't the foggiest why - I don't know javascript or gulp. But I can avoid the problem by modifying `ui/gulpfile.babel.js` in line with the recent changes to the gulpfile in d97f479b7. 

```diff
diff --git a/ui/gulpfile.babel.js b/ui/gulpfile.babel.js
index 2b907fad..7dd660ae 100644
--- a/ui/gulpfile.babel.js
+++ b/ui/gulpfile.babel.js
@@ -124,7 +124,7 @@ gulp.task('styles', () => {
 });

 gulp.task('public', () => {
-  gulp.src(paths.srcPublic).pipe(gulp.dest(paths.dist));
+  return gulp.src(paths.srcPublic).pipe(gulp.dest(paths.dist));
 });

gulp.task('fonts', () => {
  return gulp.src(paths.srcFonts).pipe(gulp.dest(`${paths.dist}/fonts`));
});
```

**Comment by slipmp** [comment]
I've tried the same thing, thanks for opening this issue

**Comment by demichej** [comment]
Good catch, we're seeing the same thing.

**Comment by slipmp** [comment]
I was able to overcome this error by checking out tag/v2.25.8 then executing docker-compose up for serverAndUI.
Suggestion provided here: https://github.com/Netflix/conductor/issues/1685

**Comment by slipmp** [comment]
Actually server docker is exiting with code 1 - error.
I've tried tag/2.24.2 and all dockers work.

**Comment by reidlai** [comment]
> I was able to overcome this error by checking out tag/v2.25.8 then executing docker-compose up for serverAndUI.
> Suggestion provided here: #1685

2.25.9 also works

**Comment by kishorebanala** [comment]
Thanks for reporting this @patrick-pt . I've create this PR to fix this: https://github.com/Netflix/conductor/pull/1733
