### ISSUE TITLE
gRPC client serialization bug breaks Decision task definition

### ISSUE THREAD

**Issue by Spikhalskiy** [Netflix/conductor#1711]
# Problem
Protobuf in gRPC client serialization changes null value of Java POJO fields to an empty string. The server code doesn't handle such cases correctly sometimes.

# Details
If we compose a workflow definition including Decision task in java gRPC client, for example by doing
```
WorkflowDef.class  def = new JsonMapperProvider().get().readValue(inputStream, WorkflowDef.class);
metadataClient.registerWorkflowDef(def);
```
from a stream with
```
{
  "name" : "DecisionWorkflow",
  "description" : "DecisionWorkflow",
  "version" : 1,
  "tasks" : [ {
    "name" : "decisionTask",
    "taskReferenceName" : "decisionTask",
    "inputParameters" : {
      "case" : "${workflow.input.case}"
    },
    "type" : "DECISION",
    "caseValueParam" : "case",
    "decisionCases" : {
      "c" : [...]
    },
    "defaultCase" : [...],
  }],
  "schemaVersion" : 2,
  "restartable" : true
}
```

The WorkflowDef after serializing into Protobuf producing an entity
WorkflowTaskPb$WorkflowTask that has an empty string in a field ```caseExpression``` which is absent (null) in the original java POJO. After deserialization on the server-side, it's still an empty string instead of null. It gets processed incorrectly in https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/mapper/DecisionTaskMapper.java#L125 which has only a null check and if ```caseExpression``` is not null we ignore ```caseValueParam``` completely. While the original entity has a defined ```caseValueParam``` and undefined ```caseExpression```.

# Proposed fix
https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/mapper/DecisionTaskMapper.java#L125
Replace
``` 
if (expression != null)
```
with
```
if (expression != null && expression.length() > 0)
```

**Comment by apanicker-nflx** [comment]
@Spikhalskiy Thanks for reporting the issue and the proposed fix. This was applied [here](https://github.com/Netflix/conductor/pull/1712/files#diff-548d01ba857168cef7fbf01b7379587eR126) and released as part of v2.27.2
