### ISSUE TITLE
Nested DO_WHILE task

### ISSUE THREAD

**Issue by alex-fu** [Netflix/conductor#1713]
I want to ask if there is a plan to support nested DO_WHILE task?

**Comment by manan164** [comment]
Hi @alex-fu , DO_WHILE is tricky use case. 
We are changing the task reference name with delimiter in each iteration so supporting nesting will be trickier. 
Please mention use case so that we can try to see if using single DO_WHILE it can be solved or not.

**Comment by alex-fu** [comment]
Thanks for reply. 
I want to bundle a couple of tasks to be a component for reuse, so I am implementing a COMPONENT system task to do this. But I found there is no possible to place DO_WHILE task to my COMPONENT task if there are DO_WHILE in the outside because the implementation in DO_WHILE task(as you mentioned, changing the task reference name with delimiter)

So I asked this question to see if there is a way to do nested DO_WHILE task, or I must set a ban to not allowed to use DO_WHILE in my COMPONENT task.
