### ISSUE TITLE
Running the same workflows back to back (Synchronization)

### ISSUE THREAD

**Issue by TwoUnderscorez** [Netflix/conductor#1714]
Hi,
In my use case we'll be running workflows back to back and I'm concerned about some synchronization edge cases. Say I have workflow FOO with tasks BAR and BAZ (retryCount = 0) which is most of the time run at an interval of 5 minutes but for some reason ended up running at a much smaller interval for 2 or 3 intervals. To mock this edge case I'll post to /workflow once (that's FOO1), wait 30 secs, and post again (and this will be FOO2). So now I'm at a point where FOO1 and FOO2 are in the running state. 
1. Is it guaranteed that BAR1 will be scheduled before BAR2?

Now BAR1 and BAR2 are both completed. Let's say for the sake of the edge case, BAR2 completed before BAR1, because I can have two replicas of BAR task runner and BAR2 got the better one (less busy k8s node, etc...)

2. Is it guaranteed that BAZ1 will be scheduled before BAZ2?

Thanks to everyone in advance!

**Comment by apanicker-nflx** [comment]
> Is it guaranteed that BAR1 will be scheduled before BAR2? 

In this scenario, it is guaranteed that BAR1 will be scheduled before BAR2. Currently, the request to start the workflow will schedule the first task in the workflow (BAR1 in this case) before returning with a response.

> Is it guaranteed that BAZ1 will be scheduled before BAZ2?

If the worker executing BAR1 completes processing and updates the status of BAR1 as COMPLETED before the worker executing BAR2, then it is guaranteed that BAZ1 will be scheduled before BAZ2.

**Comment by TwoUnderscorez** [comment]
I see, thank you for your response!
