### ISSUE TITLE
Mutliple domain polling functionality?

### ISSUE THREAD

**Issue by demichej** [Netflix/conductor#1715]
Hi, I don't think this is the case currently, but wanted to check. Is it possible for the Workers to poll by a list of domains, rather than just 1? I was looking in the client code and the TaskResource, but it looks like it would only support 1 domain at a time.

Would there be anything wrong with us looking to add that functionality? Take in a list of domains? Thanks

**Comment by apanicker-nflx** [comment]
Can you please elaborate on the use case of this functionality? Since the server supports domain lists wherein the tasks are enqueued in fallback domains in the list based on if a domain is active or not, how would polling from a list of domains augment this feature?
