### ISSUE TITLE
Workflow concurrentExecLimit

### ISSUE THREAD

**Issue by TwoUnderscorez** [Netflix/conductor#1717]
Hi,

How can I set something similar to a taskdef's `concurrentExecLimit` but for whole workflow. (i.e. If a workflow has been started and is still running, return an error when trying to start the workflow again from the `/workflow` endpoint). Would the correct approach be to implement the `WorkflowStatusListener` interface such that it notifies my scheduler of a status of a workflow?   

Thanks in advance!

**Comment by apanicker-nflx** [comment]
@TwoUnderscorez Currently, Conductor does not inherently support a concurrent execution limit semantic at a workflow level. However, if you were to use a scheduler application to periodically start workflows, implementing the `WorkflowStatusListener` to notify the scheduler application would be a good approach to accomplish this.
