### ISSUE TITLE
Exceptions such as 'workflow not found' not surfaced to ObservableQueue implementations

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1718]
There is no way for an ObservableQueue implementation to find out that its event execution failed so that it can do something about it. Is this intentional? For example, if a complete_task action is executed but the workflow id was invalid, the EventExecution gets persisted with an exception but the ObservableQueue implementation does not know about it. In my case I would like to write the error to a Kafka topic. 

I am thinking about changing the plumbing a little between the SimpleActionProcessor, SimpleEventProcessor and ObservableQueue to surface these errors but first - is it intentional to not surface these errors?

**Comment by apanicker-nflx** [comment]
Since events are asynchronous entities published from applications in a fire-and-forget semantic, can you please elaborate on how surfacing these errors to the ObservableQueue implementation would be useful from the event producers perspective?

**Comment by rickfish** [comment]
I am working on a Kafka event consumer. If someone publishes an event to a topic and the consumer picks it up and that event does not get processed because of an error, the publisher does not know about the failure. Therefore I would like the consumer to be able to publish the error to an 'error' topic that the publisher can monitor. The ObservableQueue implementation has no way of knowing about the errors that happen during the processing of the events because the SimpleEventProcessor does not interact with it when the error happens. The most that is done is a log entry. If the ObservableQueue could be told about the error it could publish the error to an 'error' topic.

**Comment by apanicker-nflx** [comment]
@rickfish Thanks for the explanation.
I believe you can extend the [ObservableQueue](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/events/queue/ObservableQueue.java) interface to implement this feature. The extension to publish to error queues/topics can be invoked from the exception block in the [SimpleEventProcessor](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/events/SimpleEventProcessor.java#L167-L169).

Please add this in a way that this can later be extended to SQS, Dyno, etc implementations of the ObservableQueue. For now, this can be stubbed out as no-ops in these implementations.

**Comment by rickfish** [comment]
@apanicker-nflx Thanks. Will follow this advice.
