### ISSUE TITLE
Workflow designer...

### ISSUE THREAD

**Issue by jvice152** [Netflix/conductor#172]
not sure if this is the right place to ask, but do you ever intend on creating a designer for the orchestration engine? I get the idea i can post a json object that represents a workflow, but id love to be able to use a designer instead of getting my hands dirty to start off ;)

edit- sorry, saw a article on the netflix tech blog (not linked to the github docs) that said it is planned in the future to create and modify flows

**Comment by v1r3n** [comment]
@jvice152 workflow designer is in the wishlist, we have not prioritized yet.
