### ISSUE TITLE
Dynamic Task does it support subworkflow? 

### ISSUE THREAD

**Issue by manjurad** [Netflix/conductor#1726]
Does Dynamic Task support the capability to launch a sub-workflow? I see that dynamic fork can support launching of task or sub-workflow, is the same support in dynamic task. I tried passing in the following

{
      "description":"Dynamic Workflow",
      "taskReferenceName": "t1",
      "name":"Test",
     "inputParameters": {
            "taskToExecute": "${workflow.input.user_supplied_task}"
       },
      "type": "DYNAMIC",
      "dynamicTaskNameParam": "taskToExecute"
}

And when starting workflow passed in inputs as 

{
   "taskToExecute": {
    "subWorkflowParam":{
            "name":"SubworkflowName",
            "version":1
         },
         "type": "SUB_WORKFLOW"
   }
}

I get the error 
Cannot find task by name {subWorkflowParam={name=SubworkflowName, version=1}, type=SUB_WORKFLOW} in the task definitions

**Comment by kishorebanala** [comment]
@manjurad This error is being thrown from https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/mapper/DynamicTaskMapper.java#L130

Can you verify if your `taskToExecute` is confirming to expected WorkflowTask definition please?

**Comment by HenryLauu** [comment]
any updates? I need to dynamic task to start a http task, too @manjurad @kishorebanala

**Comment by kishorebanala** [comment]
Hey @HenryLauu, Do you see any issues with using http task in dynamic task?
