### ISSUE TITLE
Cannot start Conductor Server with docker-compose

### ISSUE THREAD

**Issue by Jojo109** [Netflix/conductor#1727]
![image](https://user-images.githubusercontent.com/39783820/83857372-77a76180-a74d-11ea-8d98-8a388041d79f.png)

![image](https://user-images.githubusercontent.com/39783820/83856835-bd175f00-a74c-11ea-80ce-a7f5ff1f84ec.png)

I have tried use docker-compose up to build conductor environment. 
Conductor UI, Dynomite and Elasticsearch can be built successfully.
But Conductor Server cannot start with above error.

Please advice

**Comment by TwoUnderscorez** [comment]
Which branch are you on? Try checking out to a release like 2.27.0.

**Comment by Jojo109** [comment]
@TwoUnderscorez 
Thanks for prompt reply.
I am using lastest tag (v2.27.1) from master branch

**Comment by TwoUnderscorez** [comment]
Yeah I couldn't get ether 2.27.1 nor 2.27.0 to work. The newest release I got to work is 2.26.1.

**Comment by Jojo109** [comment]
@TwoUnderscorez 
Thanks a lot.
Then let me try with 2.26.1 with docker-compose.
But what is the reason of 2.27.0/1 are not working in docker-compose?

**Comment by TwoUnderscorez** [comment]
I have no clue why they are publishing releases before making sure that they work. I'm in the same boat as you...

**Comment by Jojo109** [comment]
@TwoUnderscorez 
Thanks a lot 
It works for 2.26.1 version

**Comment by apanicker-nflx** [comment]
@Jojo109 @TwoUnderscorez We have released a new version [v2.27.2](https://github.com/Netflix/conductor/releases/tag/v2.27.2) with the fix. Apologies for the inconvenience.
