### ISSUE TITLE
kitchen sink - event task

### ISSUE THREAD

**Issue by amoolya19** [Netflix/conductor#173]
Hi,

i was going through kitchen sink example and this time i was interested in event task. then i wanted to check how the handlers are written for this and i was hoping see something in the ui under event handlers. also where "event_task" is defined? i am not able to see under task defs and anywhere else. I also checked with GET method of /event but the result was empty. 

Am i missing something? is my understanding wrong?

**Comment by v1r3n** [comment]
@amoolya19 kitchensink does not have any event handlers defined - we plan to add some examples in future.  Meantime, you can use the swagger APIs page to add event handlers.
