### ISSUE TITLE
blocked when building project

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1730]
goto conductor folder and run: **./gradlew build -x test**, then got the blocking below:

```
<==-----------> 18% EXECUTING [1m 5s]
> :conductor-es6-persistence:shadowJar
```

**Comment by apanicker-nflx** [comment]
@andyyumiao This gradle task is a slow-running task (~6-7 mins). It is used to shade the ES6 dependency so that ES6 can be used without having the rebuild the project.

**Comment by SaumitraChaskar** [comment]
@apanicker-nflx The task is taking more than 10 mins even after multiple attempts.

C:\Users\conductor\server>..\gradlew clean build -x test
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Inferred project: conductor, version: 2.31.0-SNAPSHOT
Publication nebula not found in project :.
<====---------> 34% EXECUTING [14m 35s]
> :conductor-es6-persistence:shadowJar

Also what should be done regarding the Nebula publication ?
