### ISSUE TITLE
Workflow fails when HttpTask fails to reach target

### ISSUE THREAD

**Issue by davidoliviersaban** [Netflix/conductor#1739]
Hello,

I am running conductor (v2.27.2) on an openshift cluster and it is deployed as a simple pod.
I use conductor to trigger and monitor my jenkins jobs using http calls.
So I decided to use the HttpTask which is a system task as a first approach.
My workflow is quite basic:

1. HttpTask: get next build id
2. HttpTask: trigger jenkins build
3. Do-While jenkins result == null, HttpTask: check jenkins status
4. LambdaTask: retrieve jenkins result from Do-While

Yet, when a HttpTask call fails (due to some flaky network -> SocketTimeoutException), my whole workflow fails and I cannot do anything from a workflow perspective.
```
Workflow ID	                              Total Time (sec)	Start/End Time
af79d2ed-ef4e-4bcb-a06b-09cbe84da349		91.958	        06/15/2020, 11:27:24:427 - 06/15/2020, 11:28:56:385	
**Failed to invoke http task due to: com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out**
```

So I have 3 questions:

1. Should I write differently my workflow to avoid this kind of issue ?
2. Would it be possible to handle in a cleaner way this kind of exception and use some parameters such as retry to make sure that, if we face a connection issue (that will eventually happen) the entire workflow doesn't fail.
3. Is there a task that can check if there is a failure in the workflow and take an action?

Thanks for your support.

**Comment by elisherer** [comment]
Did you set `"optional": true` on the HttpTask?
Ref: https://netflix.github.io/conductor/configuration/workflowdef/#tasks-within-workflow

**Comment by davidoliviersaban** [comment]
I didn't set Optional on the HttpTask.
So what you propose is to make my HttpTasks optional and then setup a logic of retry if I have some network issues based on the task status? 
It should work but doesn't sound great :)

**Comment by davidoliviersaban** [comment]
Ok so I think my problem is solved for now.
What i did was to extend the `connectionTimeout: 60` and `readTimeout: 60` to reduce the chances to get the exception triggered.
I have as well set as `optional: true` my step 3 HttpTask as status check is a loop and I don't care if one or several http calls fail as long as one succeeds from time to time.

There is no actual retry but I am not sure retries would be necessary.
Thanks for your response elisherer.
