### ISSUE TITLE
supportting inline workflow definition within subworkflow?

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1742]
The releasing v2.27.1 mentioned that supportting inline workflow definition within subworkflow, how to understand it? and do you have instruction documents?

**Comment by apanicker-nflx** [comment]
@andyyumiao This feature enables the workflowDefinition to be passed in dynamically into a sub workflow task. Checking the [source code](https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/metadata/workflow/SubWorkflowParams.java#L48), the usage of this feature would look like so,
```json
  "name": "sub_workflow_task",
  "taskReferenceName": "sub1",
  "type": "SUB_WORKFLOW",
  "inputParameters": {
    "subWorkflowParam": {
      "name": "deployment_workflow",
      "version": 1,
      "taskToDomain": {
        "*": "mydomain"
      }
    },
    "anythingelse":  "value"
  },
 "workflowDefinition": {
   "name": "deployment_workflow",
  "description": "Deploys to CDN",
  "version": 1,
  "tasks": [
    {
      "name": "deploy",
      "taskReferenceName": "d1",
      "type": "SIMPLE",
      "inputParameters": {
        "fileLocation": "${workflow.input.encodeLocation}"
      }
    }
  ],
  "outputParameters": {
    "cdn_url": "${d1.output.location}"
  },
  "failureWorkflow": "cleanup_encode_resources",
  "restartable": true,
  "workflowStatusListenerEnabled": true,
  "schemaVersion": 2
 }
}
```
Please note the inlined workflow definition for the subworkflow in the example above.

**Comment by xiaowei582648206** [comment]
hello, I created a workflow which contains a sub_workflow with inline workflow definition mentioned above,  the wrokflow json is:
`{
	"name": "virtual_parent_workflow",
	"workflowDef": {
		"ownerApp": "xiaowei12",
		"ownerEmail": "xiaowei79@jd.com",
		"createdBy": "xiaowei12",
		"name": "virtual_parent_workflow",
		"description": "virtual test",
		"version": 1,
		"tasks": [
			{
				"name": "virtual_son_wf_01",
				"type": "SUB_WORKFLOW",
				"taskReferenceName": "virtual_son_wf_01",
				"inputParameters": {},
				"subWorkflowParam": {
					"name": "myDynamicWf",
					"version": "1",
					"workflowDefinition": {
						"name": "myDynamicWf",
						"description": "xxx",
						"version": 1,
						"tasks": [
							{
								"name": "simple_sleep_task",
								"taskReferenceName": "simple_sleep_task01",
								"inputParameters": {
									"simpleTimeout": "1"
								},
								"type": "SIMPLE"
							}
						],
						"failureWorkflow": "cleanup_encode_resources",
						"restartable": true,
						"workflowStatusListenerEnabled": true,
						"schemaVersion": 2
					}
				}
			}
		]
	},
	"input": {}
}`

the workflow can be executed completely , but when I try to look up the details of parent workflow , I got a nerror:
![image](https://user-images.githubusercontent.com/5030860/106454095-39716600-64c5-11eb-8e96-1d56256e1f52.png)
![image](https://user-images.githubusercontent.com/5030860/106454172-50b05380-64c5-11eb-8688-9281119d9c21.png)

could you help me solve this problem, thank you very much?
 @apanicker-nflx

**Comment by kishorebanala** [comment]
@xiaowei582648206 I believe the UI doesn't support inline subworkflow definitions yet. We're considering revamping the UI, which would have a fix for this, but we're not certain of the timelines yet. If you could get to this before the release of latest UI, please send us a PR.

**Comment by xiaowei582648206** [comment]
thanks a lot！
