### ISSUE TITLE
Workflow started one task twice

### ISSUE THREAD

**Issue by kushalhalder** [Netflix/conductor#1752]
I have a workflow that started the same sub-workflow twice in the same moment. How do we fix this? and Now my workflow is stuck, how do we move on from here?

**Comment by apanicker-nflx** [comment]
@kushalhalder Are you using  a locking module in your deployment. If not, in certain high-throughput scenarios, it is possible that the state evaluation of a workflow may be run from two separate threads leading to an inconsistency.

**Comment by kushalhalder** [comment]
Hey, thanks for the reply. I am not explicitly using a locking module. Is something there in the documentation?

**Comment by apanicker-nflx** [comment]
Seems like we need to improve the documentation about this. But you can refer the [code](https://github.com/Netflix/conductor/blob/master/server/src/main/java/com/netflix/conductor/bootstrap/ModulesProvider.java#L144-L174) for implementation/configuration. There is also documentation regarding a newly added locking implementation available [here](https://netflix.github.io/conductor/technicaldetails/#maintaining-workflow-consistency-with-distributed-locking-and-fencing-tokens)

**Comment by HenryLauu** [comment]
would you pls give me more details about fixing this problem? @apanicker-nflx

**Comment by HenryLauu** [comment]
hi @apanicker-nflx I am using zookeeper as lock service and this issue happened again and again , would you pls give me some advice

**Comment by HenryLauu** [comment]
> Hey, thanks for the reply. I am not explicitly using a locking module. Is something there in the documentation?

hi @kushalhalder , would you pls kindly tell me that how did you fix this problem?

**Comment by kushalhalder** [comment]
Hi @HenryLauu, I have not worked on this yet. But anyway, how are you sure that the locks are made in zookeeper?

**Comment by HenryLauu** [comment]
> Hi @HenryLauu, I have not worked on this yet. But anyway, how are you sure that the locks are made in zookeeper?

I config conductor sever something like :
`workflow.decider.locking.enabled=true

    workflow.decider.locking.server=zookeeper

    workflow.zookeeper.lock.connection=zookeeper:2181

    workflow.decider.locking.namespace=conductor`

**Comment by kushalhalder** [comment]
When you query zookeeper, can you see any data?

**Comment by HenryLauu** [comment]
yes something like _c_1e0c3655-1df3-4766-9b8e-df8b4b9656ed-lock-0000000005
