### ISSUE TITLE
Decider Locking with Zookeeper Causes Stuck Workflow

### ISSUE THREAD

**Issue by mcancio** [Netflix/conductor#1758]
Hi Team,
I've enabled decider locking using zookeeper. I noticed my workflows get stuck after completing the first task. In the logs, I can see that DeciderService only runs after the workflow has started, which is after a successful acquireLock. However, after the lock has been released, I don't see any other threads are able to acquire the lock for the workflow, therefore, decider is not triggered anymore (even when sweeper runs).

Appreciate if you can point me to the right direction here. 

![image](https://user-images.githubusercontent.com/58673273/85973462-5ad91380-ba05-11ea-88c5-2153acbd2ef5.png)

My configs are very simple: all set to default (in memory) except for the following:
```
workflow.zookeeper.lock.connection=localhost:2181
workflow.decider.locking.enabled=true
workflow.decider.locking.server=ZOOKEEPER
workflow.decider.locking.namespace=mc
```
Task Definition:
```
[
    {
        "name": "task1",
        "ownerEmail": "mc@gmail.com"
    },
    {
        "name": "task2",
        "ownerEmail": "mc@gmail.com"
    },
    {
        "name": "task3",
        "ownerEmail": "mc@gmail.com"
    },
    {
        "name": "task4",
        "ownerEmail": "mc@gmail.com"
    }
]
```

Workflow Def:
```
{
    "name": "main_workflow",
    "description": "this is the main worklow",
    "ownerEmail": "mc@gmail.com",
    "version": 1,
    "schemaVersion": 2,
    "tasks": [
        {
            "name": "task1",
            "type": "SIMPLE",
            "taskReferenceName": "task1"
        },
        {
            "name": "task2",
            "type": "SIMPLE",
            "taskReferenceName": "task2"
        },
        {
            "name": "task3",
            "type": "SIMPLE",
            "taskReferenceName": "task3"
        },
        {
            "name": "task4",
            "type": "SIMPLE",
            "taskReferenceName": "task4"
        }
    ]
}
```

**Comment by mcancio** [comment]
For additional info, I verified in Zookeeper that the lock entries are successfully created.
I tried Zookeeper 3.4.x and 3.6.x, I get the same behavior. 
Tested this behavior on Conductor Server 2.25.5 and 2.26.1.

Also, my initial understanding was, `ExecutionLockService.releaseLock` removes the lock from Zookeeper, however, I don't see the lock entry being removed. 

Hope you could help me on this. So far, I could say that the product works well during the demo's. Now we are moving to test it in a distributed environment.

**Comment by kishorebanala** [comment]
Hey @mcancio , Do you have any additional information on why subsequent acquire locks are failing? Also, is this behavior consistent? i.e are all the acquire locks failing after a certain step?

**Comment by mcancio** [comment]
Hi @kishorebanala,
Thanks for the quick reply. 

I am using default in-memory configuration (except for ZK settings) and the behavior (workflow stuck) is consistent when decider locking is enabled. 
Consistent across the two versions I tried as well. 
Consistent with using the local zookeeper or the zookeeper cluster which we have set up. (version 3.4.x and 3.6.x).

When I disable locking, everything runs fine.  

The subsequent acquire locks are failing after the first lock has been released. 

See logs for workflow: d9f3a53e-8841-4b57-9158-cf2c2aa58341

[workflowstuck.log](https://github.com/Netflix/conductor/files/4848919/workflowstuck.log)

**Comment by kishorebanala** [comment]
I see ```[DEBUG] 2020-06-30 09:23:23,957 [pool-11-thread-1]  com.netflix.conductor.service.ExecutionLockService acquireLock - Thread 112 failed to acquire lock to lockId d9f3a53e-8841-4b57-9158-cf2c2aa58341.``` in logs. This seems more like a Zookeeper configuration issue.. but it would help to see the stack trace or debug information on why Zookeeper client in failing to acquire lock from Conductor.

**Comment by apanicker-nflx** [comment]
Closing since #1791 is merged
