### ISSUE TITLE
Publish normal conductor-server.jar and source in same way as other jars are published

### ISSUE THREAD

**Issue by kosmjon** [Netflix/conductor#1762]
I am creating a custom version of Conductor and upon starting found that the conductor-server-2.27.1.jar was not available in jCenter only the war file.  As a result I had to go through hoops to build the jar myself and publish it to a local repo so it was available for builds.  It would be very nice if the conductor-server-x.xx.x.jar was available in jCenter. thx

**Comment by apanicker-nflx** [comment]
The sever jar file is available as `conductor-server-<version>-all.jar` . [Example](https://repo1.maven.org/maven2/com/netflix/conductor/conductor-server/2.27.6/)

**Comment by kosmjon** [comment]
OK thx.  Yes, depending on @war will work, but it is unfortunate that I have to download 100+MB vs the 1MB that it should be.
