### ISSUE TITLE
DynomiteDB is no longer maintained

### ISSUE THREAD

**Issue by TwoUnderscorez** [Netflix/conductor#1763]
Conductor is using DynomiteDB by default for persistence but when going to http://www.dynomitedb.com/ it says in big bold letters 
> THIS PROJECT IS NO LONGER MAINTAINED. Please use the upstream repo from Netflix.

and when clicking the button below that to go to https://github.com/Netflix/dynomite one can notice that the last commit was on Nov 21, 2019.
Would it be a good or bad idea to use Dynomite when deploying Conductor? Or should I use another persistence layer?
Thanks!

**Comment by apanicker-nflx** [comment]
@smukil Can you please comment on the OSS lifecycle of Dynomite?

**Comment by apanicker-nflx** [comment]
@TwoUnderscorez Based on my conversations with the Dynomite team, the website linked above was an independent company providing Dynomite as a service which is non-functional. However, the GitHub project for dynomite is still active.
