### ISSUE TITLE
Exposing COMPLETED_WITH_ERRORS in client code?

### ISSUE THREAD

**Issue by james-deee** [Netflix/conductor#1768]
Hello, I noticed that the status COMPLETED_WITH_ERRORS is not an option in which is available in the client code. It only has "IN_PROGRESS, FAILED, FAILED_WITH_TERMINAL_ERROR, COMPLETED"

Is there a reason that it would not be a good idea to expose this status to the Worker to manually set?

**Comment by apanicker-nflx** [comment]
The `COMPLETED_WITH_ERRORS` status is set by the state machine server-side when a task that is marked as optional enters a FAILED state. Do you a particular use-case that would fit the usage of this status in the worker side?

**Comment by demichej** [comment]
Yeah the use case we were considering is that in certain environments certain conditions may exist where we dont want to FAIL the task (which would end the workflow in a Failure), which would kick off a failure workflow. 

We thought that COMPLETED_WITH_ERRORS could help us in certain environments/conditions.

**Comment by apanicker-nflx** [comment]
In such cases, would marking the task as optional in the workflow definition be a better option for you? You could mark the task as FAILED from your worker but the state machine would mark this task as COMPLETED_WITH_ERRORS and continue the processing of the workflow.
