### ISSUE TITLE
Publishing metrics with Spectator

### ISSUE THREAD

**Issue by nikijain17** [Netflix/conductor#1769]
Hello, I am trying to use Spectator to publish metrics. I followed the instructions on this page: https://netflix.github.io/conductor/metrics/server/, but I'm not sure if it worked or if I have everything that is needed. How can I tell if metrics were published, or where can I check?

**Comment by kishorebanala** [comment]
@nikijain17 If you're just trying to verify that metrics are being published, you can push them to Log4j as suggested here: https://netflix.github.io/conductor/metrics/server/#collecting-metrics. On top of that, configuring the metrics server, for eg., Atlas, [Prometheus](https://netflix.github.io/conductor/metrics/server/#integration-with-fluentd-using-a-syslog-channel) etc. is really an implementation detail fo that metrics server.

**Comment by nikijain17** [comment]
Is there another way to view the metrics without using Log4j? I thought it was optional

**Comment by nikijain17** [comment]
I added the additional modules in config.properties. It says the metrics will be printed to the console, but I don't see anything different. Is there a way to check if it worked?

**Comment by kishorebanala** [comment]
@nikijain17 Not sure if something is still missing. You can check with Spectator folks at https://github.com/Netflix/spectator, who can better help with this.

Please feel free to reopen if you have further questions setting this up in Conductor.
