### ISSUE TITLE
Configurable queue settings for bound_to exchange queues

### ISSUE THREAD

**Issue by msdhivya** [Netflix/conductor#1771]
The settings of bound_to_exchange queues are not configurable. It is currently hard coded as explicit, non durable and auto deleted. Can this be made configurable by getting the values from the settings?

If the queue is exclusive, queue mirroring is not happening in rabbitmq cluster environment. So during failover of rabbitmq nodes, the queues are getting deleted and never created again. 

The fix can be to get the settings of bound_exchange queues also from config properties so that these can be set based on the environment.

**Comment by apanicker-nflx** [comment]
@ritu-p As the contributor for the AMQP module, can you please help with this?

**Comment by ritu-p** [comment]
Hi @msdhivya , the bound queue settings can be made configurable. please raise a PR for this fix.

**Comment by msdhivya** [comment]
Thank you @apanicker-nflx, @ritu-p . 
PR: https://github.com/Netflix/conductor/pull/1796

Can you please review?
