### ISSUE TITLE
Optional key use case in Decision Task.

### ISSUE THREAD

**Issue by vamsibandarupalli** [Netflix/conductor#1772]
Hi, This is not really bug more of an information.

I'm trying to understand how optional key used for decision case. I tried with wrong caseExpression but it's failing even when optional is set to true.

Here is task example I'm trying to create.

        {
            "name": "task1",
            "taskReferenceName": "Decision1",
            "description": null,
            "inputParameters": {
                "NAME": "${task1.output.name}"
            },
            "type": "DECISION",
            "dynamicTaskNameParam": null,
            "caseValueParam": null,
            "caseExpression": "test",
            "scriptExpression": null,
            "decisionCases": {
                "test1": [
                    {.....

On the Other cases where where I've given caseExpression as executable javascript then it's going into the default case of decsion branch. I'm confused what is the use case of "optional" key in decsion task.

**Comment by apanicker-nflx** [comment]
@vamsibandarupalli This is an interesting case that probably hasnt been tested yet. We will test out the usage of `optional` in DECISION task and get back to you. In the meantime, please feel free to report back any findings from your end.
