### ISSUE TITLE
Avoid aborting the entire workflow if some forked tasks are failing

### ISSUE THREAD

**Issue by picaron** [Netflix/conductor#178]
Hi, 

I am building a workflow that has a dynamic fork step of type HTTP followed by a join.

Currently, if any of the forked tasks fail, the entire workflow is aborted.

See example execution graph :

<img width="486" alt="workflow-graph-with-error" src="https://cloud.githubusercontent.com/assets/507577/25285836/9dbd10d8-2689-11e7-82b4-0bd764d2f45b.png">

I want to generate a report at the end of the workflow that will collect the result of each forked tasks.

I added a report task at the end of the workflow but if any of the forked tasks fail this last step never gets executed.

I tried marking the join step as optional but still no success.

Can you please advise on how I could implement the workflow I describe above?

Thanks and great framework by the way 👍

**Comment by picaron** [comment]
Here is the workflow definition I'm using : 

```
{
  "updateTime": 1492789695762,
  "name": "cancel_all_subscriptions",
  "description": "Cancel all subscriptions for a given company",
  "version": 9,
  "tasks": [
    {
      "name": "find_active_subscriptions",
      "taskReferenceName": "find",
      "inputParameters": {
        "http_request": {
          "uri": "https://827e9f2f.ngrok.io/tasks/find_subscriptions_for_company",
          "method": "GET",
          "accept": "application/json",
          "body": {
            "companyId": "${workflow.input.companyId}"
          }
        }
      },
      "type": "HTTP",
      "startDelay": 0
    },
    {
      "name": "dynamic_fork",
      "taskReferenceName": "fork_cancel",
      "inputParameters": {
        "dynamicTasks": "${find.output.response.body.dynamicTasksJSON}",
        "dynamicTasksInput": "${find.output.response.body.dynamicTasksInputJSON}"
      },
      "type": "FORK_JOIN_DYNAMIC",
      "dynamicForkTasksParam": "dynamicTasks",
      "dynamicForkTasksInputParamName": "dynamicTasksInput",
      "startDelay": 0
    },
    {
      "name": "dynamic_join",
      "taskReferenceName": "join",
      "type": "JOIN",
      "startDelay": 0,
      "optional": true
    },
    {
      "name": "generate_report",
      "taskReferenceName": "report",
      "inputParameters": {
        "http_request": {
          "uri": "https://827e9f2f.ngrok.io/tasks/generate_report",
          "method": "POST",
          "body": {
            "workflowId": "${workflow.workflowId}"
          }
        }
      },
      "type": "HTTP",
      "startDelay": 0
    }
  ],
  "schemaVersion": 2
}
```

**Comment by picaron** [comment]
It seems that the HTTP task does not support the `optional` parameter.

Looking at the code, it seems straightforward to add support for this additional input parameter.

I can submit a PR for that shortly.

**Comment by picaron** [comment]
@v1r3n 

I was able to test the fix locally. I created and submitted a PR : 

https://github.com/Netflix/conductor/pull/179

**Comment by picaron** [comment]
@v1r3n this is still a blocking issue for us to be able implement our workflow based on HTTP endpoints. 

Is there any way for you to consider supporting an `optional` parameter so that a workflow forking multiple intermediate steps could still continue and join to a common final step even if some forked tasks had errors?`

**Comment by v1r3n** [comment]
@picaron you can set `{"optional": true}` to any of the tasks in workflow.  When marked as optional the workflow will continue even if the task fails.  The issue with HTTP task not honoring this has been fixed in the recent versions.

**Comment by picaron** [comment]
@v1r3n I just tested again and now it works as expected
thanks!

**Comment by saidatta** [comment]
@picaron Out of curiosity, I have not yet programmatically tested this scenario. But, If one of those "optional" tasks failed, and the progress of the workflow is un-interrupted. 

Is the output of workflow marked as Success/Failed?
 Since, I run cron jobs periodically, my concern is on the visibility of on the tasks' failure would be become hidden unless added with extra checks.

**Comment by picaron** [comment]
@saidatta the workflow will end with a COMPLETED status (success) but if you read the status of the workflow, you will see the status of each intermediate tasks and see those that failed.

**Comment by xerxeArt** [comment]
This issue is present again now, due to [this commit](https://github.com/Netflix/conductor/commit/a9303c06e3a0e903fe169fc09cd0fa98d0d3ccf0), which sets status FAILED for COMPLETED_WITH_ERRORS.

**Comment by apanicker-nflx** [comment]
@xerxeArt This commit only maps to the FAILED status in TaskResult object that is sent back from a worker. If you mark your task with `{"optional": true}`, and then update the task result with FAILED status, the task will still be marked as `COMPLETED_WITH_ERRORS` and the workflow will continue to process further tasks.
