### ISSUE TITLE
What all is tested before releasing conductor ?

### ISSUE THREAD

**Issue by anuraggupta** [Netflix/conductor#1780]
Hi All,

We are planning to use conductor and wanted to understand how the release is performed mainly from performance tests point of view. I had following questions in mind 

- What is the infra setup for performance tests ? like which backed DB and it's specs, how many nodes ?
- Are other DBs part of the test like MySQL, Postgres, Redis etc.
- Where can I see performance numbers ?
-

**Comment by kishorebanala** [comment]
Hey @anuraggupta , we're in the process of setting up extensive load testing internally. But, Conductor open source already have several integration tests (test-harness module is the source of majority of them).

Internally, we use and test with Cassandra and internal flavor of queues. But, there are several others in the community who use MySQL, Dynomite and other supported databases.

If you haven't already checked, this blog is a good place to learn more (note that it is about an year old, but still mostly valid): https://netflixtechblog.com/evolution-of-netflix-conductor-16600be36bca

**Comment by anuraggupta** [comment]
@kishorebanala " internal flavor of queues "  what do you mean by that ? I thought the queues are maintained in the backend DB. Isn't using cassandra for queues a anti-pattern ?

**Comment by kishorebanala** [comment]
We use an internal Queuing service that is not open source yet, which can be plugged into QueueDAO: https://netflix.github.io/conductor/extend/#backend.

> I thought the queues are maintained in the backend DB. Isn't using cassandra for queues a anti-pattern ?

Queuing layer can be implemented and plugged in separate from persistence layer. Some persistence implementations do have both persistence and queueing implemented (For eg., redis-persistence, mysql-persistence etc.), while cassandra-persistence doesn't implement QueueDAO, and must be supplied other way (eg.,using `cassandra-persistence` for Workflow and Metadata persistence, and `redis-persistence` for QueueDAO).
