### ISSUE TITLE
A task is cancelled right after it gets scheduled.

### ISSUE THREAD

**Issue by kushalhalder** [Netflix/conductor#1781]
<img width="1374" alt="Screenshot 2020-07-14 12 18 58" src="https://user-images.githubusercontent.com/5244062/87394054-cce85580-c5cc-11ea-996b-32351eca35d8.png">
We have been using conductor for our production workload, however we are facing this issue intermittently. A task is scheduled but it gets cancelled without any logs or reasons. 
@apanicker-nflx Some help here would be appreciated.

**Comment by kushalhalder** [comment]
Any direction in this? I see a lot of workflows behaving in this way now.

**Comment by manan164** [comment]
Hi @kushalhalder , ideally we should be having some error logs Can you please try with debug log enabled. HTTP task is async in nature. There are only two places where we set the task status to cancel.
1. In case we terminate thee workflow https://github.com/Netflix/conductor/blob/e21ec25ad9a9389d5858f491ada1b37f6f3cd585/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L726
2. We are executing any task and we see that workflow is reached terminal state. https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L1192

**Comment by DemisB** [comment]
Hi 👋 
Would you have further information about this issue?

I observed that behaviour on our production conductor instance (that indeed has a significantly higher workload than our staging instance). We are using conductor 2.31.5.
I have not tried to look at the error logs yet.

Thanks!

**Comment by aravindanr** [comment]
Without details about the workflow and task, we can only speculate. Any running or scheduled task    is canceled when the workflow is terminated.
  
  
  
    
  
  
>
