### ISSUE TITLE
Failure Reason field is not getting cleared while hitting RERUN.

### ISSUE THREAD

**Issue by sanyamsidana** [Netflix/conductor#1782]
Let's start a **workflow**.
<img width="495" alt="Screenshot 2020-07-14 at 1 45 46 PM" src="https://user-images.githubusercontent.com/33194901/87401858-59e4dc00-c5d8-11ea-9841-c4475c078d6f.png">

An **error** occurred at **fetch_data**.
<img width="449" alt="Screenshot 2020-07-14 at 1 48 00 PM" src="https://user-images.githubusercontent.com/33194901/87402069-a5978580-c5d8-11ea-9f2e-701cb8d16c8d.png">

**Failure Reason** field gets populated with the reason of failure.
![failure](https://user-images.githubusercontent.com/33194901/87402765-a5e45080-c5d9-11ea-8f00-66651c6e2721.png)

After calling [RERUN](https://netflix.github.io/conductor/apispec/#rerun) API,
the workflow starts RUNNING as expected, but the Failure Reason field is not getting cleared.
<img width="1789" alt="Again Workflow in running state" src="https://user-images.githubusercontent.com/33194901/87403091-0f645f00-c5da-11ea-9d68-930778a2546b.png">

**Comment by apanicker-nflx** [comment]
@sanyamsidana Thanks for reporting this issue. I have applied the `bug` label to it. We will debug this issue and fix this in a future release.

**Comment by beatfreaker** [comment]
I think in [WorkflowExecutor.java#L1453](https://github.com/Netflix/conductor/blob/be9e74ebd8ee784abb2b5d0eeb9d4c3786fe108f/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L1453)

```java
// Along with changing status to RUNNING
workflow.setStatus(WorkflowStatus.RUNNING);

// We have to update below two properties as well
workflow.setReasonForIncompletion(null);
workflow.setFailedReferenceTaskNames(new HashSet<>());
```

@apanicker-nflx  Can I create a PR with this solution ?

**Comment by apanicker-nflx** [comment]
@beatfreaker Please feel free to contribute a PR with the fix. Please also add tests as part of your PR.
