### ISSUE TITLE
DO_WHILE system task not working on v2.28

### ISSUE THREAD

**Issue by nemiliani** [Netflix/conductor#1784]
Hi all,

I am trying to run a DO_WHILE task passing in some paramaters and keep hitting my head against the wall. I think there is some bug or I am not understanding something correctly.
I am defining the following WF :
```json
{
  "name": "loop_test",
  "description": "test the loop",
  "ownerEmail": "someone@somewhere.com",
  "version": 3,
  "schemaVersion": 2,
  "restartable": true,
  "tasks": [
    {
      "name": "LoopTask",
      "taskReferenceName": "LoopTask",
      "type": "DO_WHILE",
      "inputParameters": {
        "value": "${workflow.input.value}"
      },
      "loopCondition": "if ($.LoopTask['iteration'] < $.LoopTask['inputParameters']['value']) { true; } else { false; }",
      "loopOver": [
                {
                    "name": "first_task",
                    "taskReferenceName": "first_task",
                    "inputParameters": {
                        "http_request": {
                            "uri": "http://localhost:8080",
                            "method": "GET"
                        }
                    },
                    "type": "HTTP"
                }]
    }
  ]
}
```

Pretty much, iterate over the system HTTP task as many times as defined by workflow.input.value
This is how I instantiate the flow :
```
curl -v -X POST \
  http://localhost:8080/api/workflow/loop_test?version=3 \
  -H 'Content-Type: application/json' \
  -d '{"value":4 }'
```

Problem I see is that the inputParameters are not being sent to the LoopTask and thus the eval on the loopCondition fails with :
```
Unable to evaluate condition if ($.LoopTask['iteration'] < $.LoopTask['inputParameters']['value']) { true; } else { false; } , exception TypeError: Cannot get property "value" of null in <eval> at line number 1
```
I know that the input parameters are not being sent to the loop task because I see it empty on the UI :disappointed: 

![image](https://i.ibb.co/wM8PVxB/loop.png)

Another problem I experienced is that if I hardcode the amount of times it needs to iterate like this it works but the UI only shows 1 execution task instead of the 3 that actually happened 
```
 "loopCondition": "if ($.LoopTask['iteration'] < 3) { true; } else { false; }",
```
![image](https://i.ibb.co/bPR9rVd/loop2.png)

So, are these bugs or me doing something wrong ?

Thanks

**Comment by manan164** [comment]
Hi @nemiliani ,
1.  Instead of ```$.LoopTask['inputParameters']['value']``` in condition we have to use ```$.value``` This is the behaviour for all otheer tasks like LAMBDA,  DECISION etc.
2. There is a bug in a loop over tasks sequence numbering that is the reason we dont see all the tasks in UI but actually they are executed. Please check do-while task output.

**Comment by nemiliani** [comment]
Hi @manan164 
Thanks for you answer $.value did the trick :smile: , and I guess about 2 you are talking about this https://github.com/Netflix/conductor/issues/1696 so I'll wait for that to get resolved, I am sorry I can't contribute with code but I am a c++/python dev.

Last problem I came across is that if I make the task i loop over a SIMPLE task i did not find a way to wire the iteration number into the input parameters for the task. I am not even sure what I am trying to do since the Wiring doc only talks about task/workflow input/output wires and this is trying to access a metadata item from the "parent" loop task.

This:
```
{
                    "name": "bridge_data_suppression",
                    "taskReferenceName": "bridge_data_suppression",
                    "version": 2,
                    "inputParameters": {
                        "files": "${workflow.input.supp_files}",
                        "idx": "${LoopTask['iteration']}",
                        "result_s3_url": "s3://resultadenge"
                    },
                    "type": "SIMPLE"
                }
```
rendered "idx": **null**

This :
```
{
                    "name": "bridge_data_suppression",
                    "taskReferenceName": "bridge_data_suppression",
                    "version": 2,
                    "inputParameters": {
                        "files": "${workflow.input.supp_files}",
                        "idx": "${LoopTask['iteration']}",
                        "result_s3_url": "s3://resultadenge"
                    },
                    "type": "SIMPLE"
                }
```

This:
```
   "name": "bridge_data_suppression",
                    "taskReferenceName": "bridge_data_suppression",
                    "version": 2,
                    "inputParameters": {
                        "files": "${workflow.input.supp_files}",
                        "idx": "${.LoopTask['iteration']}",
                        "result_s3_url": "s3://resultadenge"
                    },
                    "type": "SIMPLE"
                }
```
rendered "idx": **[]**

Is it possible at all ? Thanks!

**Comment by apanicker-nflx** [comment]
Hi @nemiliani , currently it is not possible to wire the iteration number as an input parameter. However, having said that I believe this is a valid use case and would be a valuable improvement. We can look into adding this enhancement in a future release.

**Comment by nemiliani** [comment]
Hi @apanicker-nflx, thanks for your answer. Got it. Yes, I agree. Well, thanks all, I'll close the ticket since all is answered.
