### ISSUE TITLE
Dynamic fork type http tasks not executing

### ISSUE THREAD

**Issue by hodolizer** [Netflix/conductor#1785]
I think this is a simple question. I'm generating tasks and inputs for a FORK_JOIN_DYNAMIC task. The dynamic tasks are type HTTP. When I run the workflow I see the dynamic tasks and inputs and they look correct but the FORK_JOIN_DYNAMIC never executes them. The FORK_JOIN_DYNAMIC task shows as Yellow, and when I click on it it doesn't show anything. Should the Conductor automatically run the dynamic tasks if they are HTTP? I thought they would since HTTP is a system task?

**Comment by kishorebanala** [comment]
Copying over from gitter chat:

Hey @hodolizer, What state are the Http tasks inside FORK_JOIN_DYNAMIC are in (SCHEDULED? IN_PROGRESS)? Also, does Http tasks execute fine outside FORK_JOIN_DYNAMIC? Can you open a Github issue with simple (say FORK_JOIN_DYNAMIC with 2 Http tasks) and reproducible example please.

**Comment by hodolizer** [comment]
I'll try to come up with an example. I was going to try to catch this in a debug session with vscode but that is proving difficult. From what I can tell the tasks are never picked up (queued) by the FORK_JOIN_DYNAMIC task. Neither the FORK_JOIN_DYNAMIC task nor the generated tasks show up in the Task Details. HTTP tasks work fine outside of this, I'm using a HTTP task earlier in the workflow.

**Comment by hodolizer** [comment]
Okay, I discovered a missing curly bracket that vscode wasn't warning me about. That got me further along, but now it seems like the dynamic tasks are not getting matched up with the dynamic inputs. I think you can use this example, it uses a simple API call to generate pre-generated dynamic inputs and tasks. 
```{
  "name": "getPostComments",
  "description": "Gets comments for a post in my-json-server",
  "ownerEmail": "bobdobbs@somebogusserver.sh",
  "version": 1,
  "tasks": [
    {
      "name": "get_dynamic_comments",
      "taskReferenceName": "get_dynamic_comments",
      "ownerEmail": "bobdobbs@somebogusserver.sh",
      "type": "HTTP",
      "inputParameters": {
        "http_request": {
          "headers": {},
          "uri": "http://my-json-server.typicode.com/hodolizer/demo/dynamic-tasks-and-inputs",
          "method": "GET",
          "readTimeOut": "3600",
          "connectionTimeOut": "3600",
          "accept": "application/json",
          "content-Type": "application/json"
        }
      }
    },
    {
      "name": "async_fork_test",
      "taskReferenceName": "dynamic_fork_posts_test",
      "ownerEmail": "bobdobbs@somebogusserver.sh",
       "type": "FORK_JOIN_DYNAMIC",
      "dynamicForkTasksParam": "dynamicTasks",
      "dynamicForkTasksInputParamName": "dynamicTasksInput",
      "inputParameters": {
        "dynamicTasks": "${get_dynamic_comments.output.response.body.dynamicTasksJSON}",
        "dynamicTasksInput": "${get_dynamic_comments.output.response.body.dynamicTasksInputJSON}"
      }
    },
    { "name": "dynamic_join",
      "taskReferenceName": "join1",
      "type": "JOIN"
    }
  ],
   "outputParameters": {
  },
  "restartable": true,
  "workflowStatusListenerEnabled": true,
  "schemaVersion": 2
}```

**Comment by hodolizer** [comment]
I figured this out. The problem was the "inputParameters" key in the dynamicTasksInputJSON return. There should just be key/values for the parameters themselves, without the "inputParameters" object enclosure.
