### ISSUE TITLE
Recommended specs for Conductor

### ISSUE THREAD

**Issue by csalasl89** [Netflix/conductor#1790]
Greetings.
I was wondering about what are the recommended specs for CPU/Memory for running Conductor as a docker image?
We're having some issues where we're trying to run it on an AWS ECS infrastructure, but at some point Conductor's CPU usage always goes up to 100% and then crashes, so I was wondering if there's a way to prevent this (via configuration or upgrading the CPU).
Thank you.

**Comment by SuperMasterBlasterLaser** [comment]
I'm also interested in this. I have launched conductor via compose and I'm getting PoolTimeoutExceptions on development server where only 10 users calling their workflows.
