### ISSUE TITLE
UI authentication

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#18]
Currently, the UI doesn't seem to support any user authentication - so everybody could terminate or pause a running workflow.

Are there any configurations available to provide e.g. user authentication?

Thanks a lot.

**Comment by v1r3n** [comment]
We have plans to integrate with passport.js to authentication.  Currently, UI doe not do any authentication, but if fronted by apache, can achieve the same by configuring either apache to authenticate each request.

**Comment by blueelephants** [comment]
Many thansk for clarification - I am looking for passport.js integration.
