### ISSUE TITLE
Dynomite is having problem with Windows 10 Home

### ISSUE THREAD

**Issue by kedarchikorde** [Netflix/conductor#180]
Dynomite is intended to target the Linux systems. I am able to run conductor server on Ubuntu 14.4. How do I configure conductor server on Windows 10 Home. Is there any way?

**Comment by ipapapa** [comment]
Dynomite is a C application. As long as you have the proper libraries, it should work in any OS. Of course, Conductor is based on Java so it will work in any JVM.
