### ISSUE TITLE
SimpleTaskMapper getName() should be getType()

### ISSUE THREAD

**Issue by kosmjon** [Netflix/conductor#1803]
In core project com.netflix.conductor.core.execution.mapper.SimpleTaskMapper lines 84-85 are
` simpleTask.setTaskType(taskToSchedule.getName());`
` simpleTask.setTaskDefName(taskToSchedule.getName());`
But should be:
` simpleTask.setTaskType(taskToSchedule.getType());`
` simpleTask.setTaskDefName(taskToSchedule.getName());`
In our customized Conductor flows using SIMPLE task were never finishing without this change.  

I checked other mappers such as HTTPTaskMapper and it is using:
`httpTask.setTaskType(taskToSchedule.getType());`
`httpTask.setTaskDefName(taskToSchedule.getName());`

**Comment by apanicker-nflx** [comment]
> In our customized Conductor flows using SIMPLE task were never finishing without this change.

Could you please elaborate on this? Do you have specific handling by task type in your implementation?
