### ISSUE TITLE
How to setup a HA cluster of conductor in K8s ?

### ISSUE THREAD

**Issue by anuraggupta** [Netflix/conductor#1807]
I have been trying to get head around HA setup in K8, but the documentation doesn't contain all the information.
Like how Work is sharded between conductor servers, how would external workers get tasks (Documentation states that queues are sharded per server) ? Should the workers connect to all the servers ?

What I'm planning to do is as follows:

Load balancer -> GroupOf( Conductor-Server-1, Conductor-Server-2 ... ) -> Redis(Locking) and MySQL(DataStore)

Now my confusion is that if workers connect with the servers via LoadBalancer will they actually be able to process all the shards ? 
Is a discovery service necessary for the HA setup ?

**Comment by apanicker-nflx** [comment]
When using the MySQL datastore and queue recipe, queues will not be sharded for per server. This is specific to the dynomite implementation.

**Comment by imaffe** [comment]
Yeah I'm also wondering if we could add a Helm Chart directory for k8s users. Seems that Netflix is working mainly on EC2 but not k8s clusters. I couldn't find an official guide on how to properly deploy conductor on k8s clusters, and if someone know I would 
appreciate it if you can leave a comment~ thank you ~

**Comment by apanicker-nflx** [comment]
@imaffe I would suggest creating a separate issue for the k8s question so that other users have better visibility into it and can help you out if using a similar setup. I would also suggest you to post this question in our gitter channel for more visibility.

**Comment by apanicker-nflx** [comment]
Closing this for now, please post the k8s as a separate question.
