### ISSUE TITLE
Is there a reason why WorkflowStatusListener does not have an onWorkflowFailed() method?

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1808]
Our users want us to email them when a workflow status changes to FAILED. WorkflowStatusListener has an onWorkflowCompleted() method and an onWorkflowTerminated() method. Was it intentional not to provide an onWorkflowFailed() method in there? Is this something I should try to add?

**Comment by apanicker-nflx** [comment]
The `onWorkflowTerminated()` method is invoked even during workflow failures. The idea was to add listeners for success and failure cases and this sufficed the requirement.

**Comment by rickfish** [comment]
Oh sorry. I should have tested it. When I did searches on the code I only saw onWorkflowTerminated() called in the terminateWorkflow method of WorkflowExecutor so I didn't think it was called on just a FAILED workflow. I just tested it and it works fine. Thanks!
