### ISSUE TITLE
ElasticSearch Backend Questions

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#181]
I have some follow up questions to https://github.com/Netflix/conductor/issues/23, where I would like you to ask for some more background information.

(1) Is all workflow and task execution information stored in ElasticSearch "only"? 
     Or is this information also stored in Redis/Dynomite (for state machine activities) and additionally in ElasticSearch to offer better search capabilities?

I guess this information is somehow stored in ElasticSearch and Redis/Dynomite - is there any difference in what gets stored where?

If this information is also stored in Redis/Dynomite, is this information somehow deleted (lets say after x days?)?

(2) Where does the UI get its data to display from? From Redis/Dynomite or from ElasticSearch?

(3) Is there a possibility to run Conductor with Redis/Dynomite but without ElasticSearch - i.e. to disable ElasticSearch?

**Comment by v1r3n** [comment]
@blueelephants 

1. ES is used only as index and used only to search for workflow instances - by UI.  ES is not used for executing workflow.  The data is also present in Redis/Dynomite.
2. Redis/Dynomite data is not deleted automatically, there is an API endpoint under /workflow to actually remove the data when required.
3. UI searches the data using ES (/workflow/search endpoint) but when loading the actual workflow, it gets the data from Redis/Dynomite.
4. It is possible to run Conductor without ES - You can supply a version of IndexDAO that does nothing - UI will be impacted though.

Hope this helps.

**Comment by blueelephants** [comment]
Thank you very much for the detailled explanation
