### ISSUE TITLE
Conductor server metrics  how/help + prometheus

### ISSUE THREAD

**Issue by eins** [Netflix/conductor#1811]
Hello guys
I read a few tickets about conductor server and prometheus metrics

https://github.com/Netflix/conductor/issues/600
https://github.com/Netflix/conductor/issues/1769

And the conductor documentation
https://netflix.github.io/conductor/metrics/server/

But I can't understand how to enable spectator in conductor server and
then push metrics to a external prometheus server.

https://netflix.github.io/conductor/metrics/server/#publishing-metrics

Conductor uses spectator to collect the metrics.

+ To enable conductor serve to publish metrics, add this dependency to
  your build.gradle.

  is build.grade, server/build.gradle  ?

   I followed the link and I tried to add 

  ```   
    // metrics -- this line didn't work
   compile "com.netflix.spectator:spectator-reg-metrics3:0.89.0"
  ``` 
   or https://github.com/brharrington/spectator-examples/blob/master/metrics3/build.gradle

  I had errors

   A problem occurred configuring project ':conductor-server'.
   > Could not resolve all dependencies for configuration ':conductor-server:runtimeCopy'.
   > Could not find com.netflix.spectator:spectator-reg-metrics3:0.89.0.
  
   OR

   > Could not get unknown property 'version_guice' for object of type
   org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

+ Conductor Server enables you to load additional modules dynamically,
  this feature can be controlled using this configuration.

  I added to  docker/server/config/config.properties

  ```
  # Additional modules for metrics collection (optional)
  conductor.additional.modules=com.netflix.conductor.contribs.metrics.MetricsRegistryModule,com.netflix.conductor.contribs.metrics.LoggingMetricsModule
  com.netflix.conductor.contribs.metrics.LoggingMetricsModule.reportPeriodSeconds=15
  ```

+ Create your own AbstractModule that overides configure function and
  registers the Spectator metrics registry.

+ Initialize the Registry and add it to the global registry via
  ((CompositeRegistry)Spectator.globalRegistry()).add(...).

the last two option I don't know where I need to add it.

**Comment by marcocrasso** [comment]
@eins today I faced the same problem and a Web search brings me here. In case you still want to achieve this, I'd suggest to:

## for development purposes:

in server/build.gradle file add:

```
implementation 'org.springframework.boot:spring-boot-starter-actuator'
```

in server/src/main/resources/application.properties add:
```
conductor.metrics-prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus,health,info,metrics
```

then hit at root:

```
./gradlew server
```

visit: http://localhost:8080/actuator and follow the links. 


## for PRD
For production, build a docker image with the change in server/build.gradle and then configure your container as showed.

**Comment by marcocrasso** [comment]
By the way, the source I consulted:

1) Sections 1 and 2 (only the first two sentences) of : https://micrometer.io/docs/registry/prometheus#_installing
2) https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints-exposing-endpoints

**Comment by eins** [comment]
@marcocrasso thanks for the reply on this ticket. We moved to camundabpm . conductor was to green .

**Comment by yashwant-mv** [comment]
@marcocrasso anyway we can achieve this using configs and using docker images?
