### ISSUE TITLE
How to implement and deploy a WorkflowStatusListener

### ISSUE THREAD

**Issue by btafarelo** [Netflix/conductor#1812]
Hi

Conductor's documentation tells on expand session to implement this interface to have a "Workflow Status Listener" but this document doesn't tell where to deploy the jar generated, if it's a jar.

I have created a maven project, added conductor-core as a dependency but I don't know where to put it and how select it on my workflow.

Regards

**Comment by apanicker-nflx** [comment]
[Here](https://github.com/Netflix/conductor/blob/master/contribs/src/main/java/com/netflix/conductor/contribs/ArchivingWorkflowModule.java) is a simple example of how a workflow status listener implementation can be bound.

**Comment by btafarelo** [comment]
I found how to deploy using docker.

I copied the folder /app from my docker container, changed the startup.sh script and mounted my local folder.

I copied my jar into /app/libs

`java -cp libs/*.jar com.netflix.conductor.bootstrap.Main $config_file $log4j_file`

**Comment by yutaodou** [comment]
Also remember to setup property : `conductor.additional.modules=<your-binding-module>` in your config file
