### ISSUE TITLE
Conductor Server Logging Questions

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#182]
In the startup-script of the Docker deployment (https://github.com/Netflix/conductor/blob/master/docker/server/bin/startup.sh), the Conductor server gets started with this command:

`nohup` java -jar conductor-server-*-all.jar $config_file 1>&2 > /app/logs/server.log`

Is there a way to better "configure" the logging - i.e. to provide a logback.xml or log4j.properties to e.g. configure the log-level and the log message format?

Thanks for any help.

**Comment by v1r3n** [comment]
@blueelephants yes, it takes two arguments and second one (after the config file) is the location of log4j properties.

https://github.com/Netflix/conductor/blob/master/server/src/main/java/com/netflix/conductor/server/Main.java#L47

**Comment by blueelephants** [comment]
Many thanks for your help!
