### ISSUE TITLE
Build conductor server 2.28 with ES6, start up error

### ISSUE THREAD

**Issue by DivineDm** [Netflix/conductor#1827]
Hi All,
I am trying to build a conductor server in version 2.28 with es6, but there is a start error in my way, the error is "Caused by: java.lang.ClassNotFoundException: conductor.org.apache.logging.log4j.core.config.Configurator". 
My build command in maxOS is ./gradlew clean configureRelocationShadowJar shadowJar -x test -Prelease.version=1.0.0
Is there something i missing?
By the way, I had done with the guideline in https://github.com/Netflix/conductor/tree/master/es6-persistence#build

**Comment by kishorebanala** [comment]
Copying my response from Gitter:

```Hey @DivineDm, any particular reason to use Conductor 1.28 over the latest available 2.x deployments?```

**Comment by DivineDm** [comment]
@kishorebanala sorry, typo my bad! My forked conductor version is 2.28, also updated in gitter.  By the way, I had edited the build.gradle, and run with es6 successfully now, but I'm not sure what i did is the best practice

**Comment by kishorebanala** [comment]
@DivineDm No worries. Can you provide more details about changes in build.gradle that has fixed your error please.

**Comment by DivineDm** [comment]
@kishorebanala I had rollback the build.gradle to conductor 2.26, and it works

**Comment by kishorebanala** [comment]
@DivineDm Please feel free to reopen if you see this issue again.
