### ISSUE TITLE
How do I timeout WAIT system task ?

### ISSUE THREAD

**Issue by shrikantmule** [Netflix/conductor#1833]

**Comment by shrikantmule** [comment]
I would like to timeout the WAIT system task since there is not activity and Event listener didn't get any event to for the WAIT task for after a few hours and would like to timeout the WAIT task.

**Comment by apanicker-nflx** [comment]
@shrikantmule You can register a task definition with a desired timeout and use this name for your WAIT task within your workflow. This would apply the task definition to your WAIT task and will lead it to be timed out if it is IN_PROGRESS for longer than specified duration.
