### ISSUE TITLE
About dyno-queues

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1837]
I used MySQL as the default storage. I know that the conductor still depends on dyno-queues, but as far as I know, dyno-queues depends on Dynomite. So do we need to deploy a redis cluster separately for dyno-queues?

**Comment by apanicker-nflx** [comment]
When using MySQL as the persistence layer, Conductor can be configured to use MySQL for providing the queueing recipe as well. You do not need to deploy a redis cluster for dyno-queues. [See](https://github.com/Netflix/conductor/blob/master/mysql-persistence/src/main/java/com/netflix/conductor/mysql/MySQLWorkflowModule.java#L42)

**Comment by andyyumiao** [comment]
> When using MySQL as the persistence layer, Conductor can be configured to use MySQL for providing the queueing recipe as well. You do not need to deploy a redis cluster for dyno-queues. [See](https://github.com/Netflix/conductor/blob/master/mysql-persistence/src/main/java/com/netflix/conductor/mysql/MySQLWorkflowModule.java#L42)

Ok, got it, many thanks!!!
