### ISSUE TITLE
Conductor UI "Running" tab not showing "Running" Workflows

### ISSUE THREAD

**Issue by cquon** [Netflix/conductor#184]
Hi,

I have checked out a fresh Conductor workspace (Last commit a2731a21b48fa924693102af50b710459bac3184):

And have done a
```
docker-compose up
```
in the docker directory.

All of the containers are created correctly (dynomite, elasticsearch, conductor server, conductor ui)

Initially the kitchensink workflow is not indexed by elasticsearch properly which is likely due to a timing issue (not a problem)
Logs:
```
Started server on http://localhost:8080/
Creating kitchensink workflow
5009 [qtp10885570-34] ERROR com.netflix.conductor.dao.index.ElasticSearchDAO  - Indexing failed for conductor, workflow
5023 [qtp10885570-34] ERROR com.netflix.conductor.dao.index.ElasticSearchDAO  - Indexing failed for conductor, workflow
5034 [qtp10885570-34] ERROR com.netflix.conductor.dao.index.ElasticSearchDAO  - Indexing failed for conductor, workflow
5097 [qtp10885570-34] ERROR com.netflix.conductor.dao.index.ElasticSearchDAO  - Indexing failed for conductor, task
5107 [qtp10885570-34] ERROR com.netflix.conductor.dao.index.ElasticSearchDAO  - Indexing failed for conductor, task
5118 [qtp10885570-34] ERROR com.netflix.conductor.dao.index.ElasticSearchDAO  - Indexing failed for conductor, task
5142 [qtp10885570-34] INFO  com.netflix.dyno.queues.redis.RedisDynoQueue  - com.netflix.dyno.queues.redis.RedisDynoQueue is ready to serve task_1
5166 [qtp10885570-34] ERROR com.netflix.conductor.dao.index.ElasticSearchDAO  - Indexing failed for conductor, workflow
5178 [qtp10885570-34] ERROR com.netflix.conductor.dao.index.ElasticSearchDAO  - Indexing failed for conductor, workflow
5189 [qtp10885570-34] ERROR com.netflix.conductor.dao.index.ElasticSearchDAO  - Indexing failed for conductor, workflow
5200 [qtp10885570-34] INFO  com.netflix.dyno.queues.redis.RedisDynoQueue  - com.netflix.dyno.queues.redis.RedisDynoQueue is ready to serve _deciderQueue
5228 [main] INFO  com.netflix.conductor.server.ConductorServer  - Kitchen sink workflows are created!
```

However, after creating my own task / workflow metadata and starting the workflow, I only see the workflow in the "All" tab of the UI and not the "Running".

I have dug a little deeper and see it is a workflow search with freeText=*, in the "All" tab it is using no specific query and the "Running" tab is using status="RUNNING".

The server returns 0 results for the RUNNING scenario as I had printed out the result set for it.

However, in elasticsearch I do see the indexes being created:
```
curl -XPOST 'http://127.0.0.1:9200/conductor/_search?pretty=1'
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "conductor",
      "_type" : "task",
      "_id" : "aaddd78a-bb98-4211-99a4-41e0db6726f5",
      "_score" : 1.0,
      "_source" : {
        "workflowId" : "5e02ff7f-05fb-4e25-972f-3ee6534322ea",
        "scheduledTime" : "2017-04-26T23:00:51Z",
        "startTime" : "1970-01-01T00:00:00Z",
        "updateTime" : "2017-04-26T23:00:51Z",
        "endTime" : "1970-01-01T00:00:00Z",
        "status" : "SCHEDULED",
        "executionTime" : 0,
        "queueWaitTime" : 0,
        "taskDefName" : "corey_task_1",
        "taskType" : "corey_task_1"
      }
    }, {
      "_index" : "conductor",
      "_type" : "workflow",
      "_id" : "5e02ff7f-05fb-4e25-972f-3ee6534322ea",
      "_score" : 1.0,
      "_source" : {
        "workflowType" : "corey_flow_1",
        "version" : 1,
        "workflowId" : "5e02ff7f-05fb-4e25-972f-3ee6534322ea",
        "startTime" : "2017-04-26T23:00:50Z",
        "status" : "RUNNING",
        "input" : "{}",
        "output" : "{}",
        "executionTime" : 0,
        "updateTime" : "2017-04-26T23:00:51Z"
      }
    } ]
  }
}
```

And in the Swagger API, when specifying freeText="corey_flow_1" and query status="RUNNING" it does return 

Request URL:
http://localhost:8080/api/workflow/search?size=100&freeText=corey_flow_1&query=status%3D%22RUNNING%22

{
  "totalHits": 1,
  "results": [
    {
      "workflowType": "corey_flow_1",
      "version": 1,
      "workflowId": "5e02ff7f-05fb-4e25-972f-3ee6534322ea",
      "startTime": "2017-04-26T23:00:50Z",
      "updateTime": "2017-04-26T23:00:51Z",
      "status": "RUNNING",
      "input": "{}",
      "output": "{}",
      "executionTime": 0
    }
  ]
}

So it appears the backend server is properly returning, but from the UI it must be preparing an incorrect query to the backend.

**Comment by v1r3n** [comment]
@cquon what version of elasticsearch are you using?

**Comment by cquon** [comment]
@v1r3n When I was running it was using 2.4 with no local changes after a fresh clone

**Comment by v1r3n** [comment]
@cquon is this problem still existing?  If not, we can close it out.

**Comment by cquon** [comment]
I have not seen this in a while we can close it.

Thanks.

**Comment by supriya-mallikarjuna** [comment]
After creating my own task / workflow metadata and starting the workflow, I only see the workflow in the "All" tab of the UI and not the "Running".
