### ISSUE TITLE
broken link to the Distributed Locking Service

### ISSUE THREAD

**Issue by andyczerwonka** [Netflix/conductor#1842]
The following link is broken: https://netflix.github.io/technicaldetails/#maintaining-workflow-consistency-with-distributed-locking-and-fencing-tokens

If it referenced from https://netflix.github.io/conductor/server/

![image](https://user-images.githubusercontent.com/138898/91103274-59545200-e628-11ea-9d02-5baf7992e98c.png)

**Comment by andyczerwonka** [comment]
I'd love to reach about this, but can't see to track it down.

**Comment by apanicker-nflx** [comment]
Thanks for reporting the issue, we will fix the link ASAP. In the meantime, here's the link - https://netflix.github.io/conductor/technicaldetails/#maintaining-workflow-consistency-with-distributed-locking-and-fencing-tokens
