### ISSUE TITLE
HTTP system tasks are being sent without encoding

### ISSUE THREAD

**Issue by Hajar1** [Netflix/conductor#1844]
When it comes to the HTTP system task some of the inputs might contain space in them.
That space needs to be encoded as %20 before being sent to the endpoint. 

Example:
![image](https://user-images.githubusercontent.com/13091952/91334631-3eefb500-e79d-11ea-8a40-d2c5ad67f75f.png)

The url encoding version should be:
SMS%202008191839bfb57c2e8-2756-4

**Comment by kishorebanala** [comment]
Hey @Hajar1 , Http url in http task is passed through without any modifications. Given that Http task is generic and is intended to support several different types of resource servers, it'd be much simpler if the Http task doesn't modify the incoming uri paths.

That being said, you can encode the uri's in one of the several ways like using a Lambda task in between, modifying the client to send encoded inputs when passing through etc.
