### ISSUE TITLE
Subworkflow in progress but the workflow is completed

### ISSUE THREAD

**Issue by btafarelo** [Netflix/conductor#1848]
Hi!

I have a workflow that I splitted in few sub workflows, and one of them sometimes is work perfectly but many times it keep in progress indefinitely, as you can see in the screenshot attached.

Let me know any other information that can be useful.

**UPDATE: After start to deploy all workflows everytime and not only the one updated this behaviour seems to stopped.**

Regards

Snippet sub_workflow task
`{
            "name": "Simulator",
            "taskReferenceName": "sm_rs",
            "type": "SUB_WORKFLOW",
            "subWorkflowParam": {
              "name": "sm_rs"
            },
            "inputParameters": {
              "connectionTimeOut": "${workflow.input.connectionTimeOut}",
              "readTimeOut": "${workflow.input.readTimeOut}",
              "headers": "${workflow.input.headers}",
              "url": "${workflow.input.url}",
            }
          }`

Subworkflow status

![image](https://user-images.githubusercontent.com/3848106/91595638-25e53080-e964-11ea-8cf9-58af8072cb4b.png)

Workflow status (used as subflow)
![image](https://user-images.githubusercontent.com/3848106/91595783-617ffa80-e964-11ea-913f-965de5d79a91.png)

Main workflow
![image](https://user-images.githubusercontent.com/3848106/91595851-7c526f00-e964-11ea-8d14-a5aab8e316fb.png)

**Comment by apanicker-nflx** [comment]
@btafarelo Could you please let us know the result of manually forcing the evaluation of the parent workflow? This could be done by invoking this API manually using cURL or swagger - 
![image](https://user-images.githubusercontent.com/34087882/91779673-1a377b00-ebab-11ea-946e-34ecb00769d7.png)
