### ISSUE TITLE
Workflow execution time increased in high throughput scenario.

### ISSUE THREAD

**Issue by manan164** [Netflix/conductor#1853]
We have pulled the latest conductor release v2.28.3 in our environment. Since the last pull was around a few months back there are around 400+ commits that got merged.
During the high throughput scenario, we see that the HTTP task queue is getting piled up and that causes the overall task and workflow execution latency to become very high. 
Do we have to change any config for a high scale scenario? We use 25 worker thread count with a poll interval as 50 ms.
@apanicker-nflx @kishorebanala @mdepak

**Comment by apanicker-nflx** [comment]
>We use 25 worker thread count with a poll interval as 50 ms

Is the configuration for your system task workers? A major change around HTTP task processing would be the switch from batch polling to single poll from the task queue. This was further enhanced by a contribution form @mdepak in #1719 . Have you tried setting the property `workflow.system.task.queue.pollCount` to a value >1 as per your use case.

**Comment by manan164** [comment]
Hi @apanicker-nflx Yeah setting ```workflow.system.task.queue.pollCount``` to higher value did the trick.
