### ISSUE TITLE
Netflix Conductor installation doesnt work with docker-compose instructions

### ISSUE THREAD

**Issue by vikas1389** [Netflix/conductor#1854]
Hello Team,

We want to use the tool to orchestrate deployments of services- we are not able to standup the tool on docker - we get many gradle dependency error. Can someone please help on docker part of installation- it would be great if we have docker images for every components invoved in the tool.

**Comment by apanicker-nflx** [comment]
Could you please provide the errors that you are seeing? 

> it would be great if we have docker images for every components invoved in the tool.

This is something we are working on providing in the next major version upgrade of Conductor (3.0).
