### ISSUE TITLE
fork join skipping a wait task in one forked branch

### ISSUE THREAD

**Issue by ssg2526** [Netflix/conductor#1857]
I am using this DSL 
{
  "name": "forkJoinIssueTestA",
  "version": 1,
  "tasks": [
    {
      "name": "forkjoin",
      "taskReferenceName": "forkjoinref",
      "type": "FORK_JOIN",
      "forkTasks": [
          [
          {
            "name": "wait4",
            "taskReferenceName": "wait4ref",
            "type": "WAIT"
          },
          {
            "name": "wait5",
            "taskReferenceName": "wait5ref",
            "type": "WAIT"
          }
        ],
        [
          {
            "name": "wait2",
            "taskReferenceName": "wait2ref",
            "type": "WAIT"
          },
          {
            "name": "wait3",
            "taskReferenceName": "wait3ref",
            "type": "WAIT"
          }
        ]
      ]
    },
    {
      "name": "join1",
      "taskReferenceName": "join1ref",
      "type": "JOIN",
      "joinOn": [
        "wait3ref",
        "wait5ref"
      ]
    }
  ]
}

Now when I am marking wait4ref as completed then the it is not showing the wait5ref task. For the other fork branch it is working fine but at the end the join1ref task is always incomplete because i am not able see the wait5ref task for completion. Is this a issue or I am doing something wrong while defining the dsl

**Comment by elisherer** [comment]
What version are you using, and what do you do to complete the wait task?

**Comment by ssg2526** [comment]
I am using 2.24.2 version. We have created a wrapper service and we are using REST calls to that wrapper service for marking a task complete. The Wrapper service interacts with the conductor.

**Comment by kishorebanala** [comment]
@ssg2526 Can you provide a sample workflow execution in above situation please?
