### ISSUE TITLE
How to prevent workers from polling task during idle period

### ISSUE THREAD

**Issue by HenryLauu** [Netflix/conductor#1860]
I have a system which only start task between 5 pm and 6 pm, what can i do to prevent the worker from polling task when there no task? Task generated during working time should be polled in time too. This will need some mechanic like redis pub-sub

**Comment by apanicker-nflx** [comment]
@HenryLauu This is not directly supported by the worker. 
However, if you are using the java client, you could set the property `conductor.worker.paused` to `true`. This would stop the worker from polling. Setting this property would need to be an external process however, that you can schedule using a cron job or the like.
