### ISSUE TITLE
https://netflix.github.io/conductor/metrics/server/ looks broken

### ISSUE THREAD

**Issue by s50600822** [Netflix/conductor#1865]
The snippet for fluentd config on https://netflix.github.io/conductor/metrics/server/ looks broken:
![broken_doc](https://user-images.githubusercontent.com/5586453/93005568-8942a580-f595-11ea-9307-2b15c1c75c1a.PNG)

**Comment by kishorebanala** [comment]
@s50600822 Thanks for reporting this. We'll fix this asap. Please feel free to send us a PR if you can get to this before us.

**Comment by beatfreaker** [comment]
@kishorebanala Which version of `mkdocs` is used to build the docs?

**Comment by kishorebanala** [comment]
Fixed.
