### ISSUE TITLE
Cannot set the value of read-only property 'executionData' for task ':conductor-cassandra-persistence:jacocoTestReport' of type org.gradle.testing.jacoco.tasks.JacocoReport.

### ISSUE THREAD

**Issue by ravindar-tuplescale** [Netflix/conductor#1870]
While building with ES6 configuration following errors are occurring, what cloud be the problem?
branch: master

**

Configure project :
Inferred project: conductor, version: 2.30.0-SNAPSHOT

FAILURE: Build failed with an exception.

Where:
Build file 'C:\Conductor\source\conductor\build.gradle' line: 79

What went wrong:
A problem occurred evaluating root project 'conductor'.

Cannot set the value of read-only property 'executionData' for task ':conductor-cassandra-persistence:jacocoTestReport' of type org.gradle.testing.jacoco.tasks.JacocoReport.

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s**

**Comment by apanicker-nflx** [comment]
Seems odd, can you try disabling the jacoco configurations in root build.gradle to disable jacoco report generation?

**Comment by WavyPeng** [comment]
Have you solved this problem? I also met this, so sad

**Comment by apanicker-nflx** [comment]
@WavyPeng If you're new to using Conductor and want to use the es6-persistence layer, we would urge you to try out the 3.0 version, it is available in the 3.0 branch. This version uses es6 as the default indexing layer.
