### ISSUE TITLE
Input parameters and event handler

### ISSUE THREAD

**Issue by zummino** [Netflix/conductor#1879]
Hello everyone, i'm using netflix conducotor for an exam purpose, i'm a student of computer science engeering. I have a problem, i have a workflow that takes in input some data about a Movie, like the ID and the name, my idea is that the first workflow (that takes as input the ID, the name etc..) throught a task event and a event handler will wake up another workflow that has to do a HTTP Request to do a POST to write the info about the new film that i want to add..the problem is that i can't find a way to give to the second workflow the input that i give to the first workflow. I'm trying to find a way to pass this data throught the event handler that wake up the second workflow but i can't find a way. Is possibile to do want i want to do?

here is the part of the first worflow
`{
										"name": "test_start_workflow_event",
										"taskReferenceName": "start_workflow_with_event",
										"type": "EVENT",
										"sink": "conductor",										
										},
										{
										"name": "test_task_tobe_completed_by_eventHandler",
										"taskReferenceName": "test_task_tobe_completed_by_eventHandler",
										"type": "WAIT"
										},`

here we have the event handler:
`{
  "name": "test_start_workflow",
  "event": "conductor:test_workflow_for_eventHandler:start_workflow_with_event",
  "actions": [
    {
      "action": "start_workflow",
      "start_workflow": {
        "name": "test_workflow_startedBy_eventHandler",
		
        "input": {
          "sourceWorkflowId": "${workflowInstanceId}",
		   "id" : "{workflow.input.id}"
		  
        }
		
      }
    }
  ],
  "active": true
}
`

here we have the full second workflow.
`{
"ownerApp": "APB_tesina",
"createTime": 1563536825816, 
"updateTime": 0,
"createdBy": "MDL",
"name": "test_workflow_startedBy_eventHandler",
"description": "A test workflow which is started by EventHandler, and then goes on to complete task in another workflow.",
  "version": 1,
  "tasks": [
					
				{
					"name": "FilmRequest_ins",
					"taskReferenceName": "FilmRequest_ins",
					"inputParameters": {
					"sourceWorkflowId": "${workflow.input.sourceWorkflowId}",
					
					"http_request": {
						"uri": "http://172.17.0.1:9095/film/add",  
						"method": "POST",
						"contentType": "application/json", 
						"body": {
								"id": "${workflow.input.id}",
								"titolo":"${workflow.input.titolo}",
								"anno": "${workflow.input.anno}",
								"durata": "${workflow.input.durata}",
								"genere": "${workflow.input.genere}", 
								"regia": "${workflow.input.regia}"
								}
							}
						},
					
						"type": "HTTP",
						"startDelay": 0,
						"optional": false,
						"asyncComplete": false
				},
				{
					"name": "test_complete_task_event",
					"taskReferenceName": "complete_task_with_event",
					"inputParameters": {
						"sourceWorkflowId": "${workflow.input.sourceWorkflowId}"
					},
					"type": "EVENT",
					"sink": "conductor"
				}
				],
				
				
  
  "schemaVersion": 2,
		"restartable": true,
		"workflowStatusListenerEnabled": false,
"ownerEmail": "xxxxx"
}`

**Comment by kishorebanala** [comment]
@zummino You can provide the input as Event task's payload. I.e Your Event task's input in workflow1 will be passed through as event payload. You can then configure your Event handler to parse this event payload when starting workflow.

**Comment by kishorebanala** [comment]
Consider adding input parameters to this Event task definition in workflow 1:
```{ "name": "test_start_workflow_event", "taskReferenceName": "start_workflow_with_event", "type": "EVENT", "sink": "conductor", }, { "name": "test_task_tobe_completed_by_eventHandler", "taskReferenceName": "test_task_tobe_completed_by_eventHandler", "type": "WAIT" }```

https://netflix.github.io/conductor/configuration/workflowdef/#wiring-inputs-and-outputs

**Comment by zummino** [comment]
> Consider adding input parameters to this Event task definition in workflow 1:
> `{ "name": "test_start_workflow_event", "taskReferenceName": "start_workflow_with_event", "type": "EVENT", "sink": "conductor", }, { "name": "test_task_tobe_completed_by_eventHandler", "taskReferenceName": "test_task_tobe_completed_by_eventHandler", "type": "WAIT" }`
> 
> https://netflix.github.io/conductor/configuration/workflowdef/#wiring-inputs-and-outputs

thanks you i solved the problem!
