### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by ajayaks** [Netflix/conductor#189]
Hi Viren,

Would you please suggest on below:-
1. Want to add CORS support in conductor, specially X-XSRF-token, do we have any configuration for the same.
2. Any plan for updating to swagger 2.0 , currently after deploying  conductor on remote server swagger apis are working until i am repackaging the jar after changing the ip address in index.html.

Regards
Ajay

**Comment by v1r3n** [comment]
@ajayaks 

1. We do not have a configuration for this as yet - but I think you can certainly add a filter and configure it as guice module.  Conductor allows loading additional modules that are in the classpath.  So that should work.

2. swagger 2.0 - no plans yet.

**Comment by v1r3n** [comment]
Closing the issue.  Please re-open if you have further questions.
