### ISSUE TITLE
Using task output from within a Do While task

### ISSUE THREAD

**Issue by connickshields** [Netflix/conductor#1890]
Hi there! I have a problem that I can't seem to find a solution to (or maybe I am reading the docs wrong). I have a Do While task and one HTTP task inside which retrieves a status from an API call. The Do While loop condition uses the output of this task. I would also like to use the response of this task in a Decision task within the Do While, but I am having issues accessing the HTTP task's output from the Decision task.

I've tried accessing the output like this for the caseDecision:
`${loop_task[${loop_task.iteration}].get_info.response.body[0].status}` but that ends up showing like this when the workflow runs so I assume Conductor doesn't support nesting variables: `${loop_task[].get_info.response.body[0].status}`

I've also tried using the same syntax which works for the loopDecision but it didn't work for the caseDecision: `$.get_info.response.body[0].status`

Is my syntax wrong or am I just going about this the wrong way? Thanks!

**Comment by apanicker-nflx** [comment]
@manan164 / @rickfish  Could you please help with this?

**Comment by manan164** [comment]
@TheSabreSlicer If wewant to use loop over task output outside the scope of do_while then we have to append iteration also. like ```get_info__1.output.data.response.code```

**Comment by elisherer** [comment]
If you have the latest version you could define a [variable](https://netflix.github.io/conductor/configuration/systask/#set-variable-task) before the loop and change its value after each http call (based on the http output).
The loop condition could check the variable value.

**Comment by TheSabreSlicer** [comment]
@elisherer I see how variables would be useful, thanks! @manan164 do I have to make a lambda task to generate the latest task name? or what is the best way to get the latest iteration?

**Comment by ritu-p** [comment]
I have used a decision task within a do-while loop I want to access the output of a previous task within the do while loop.
The task ref names come like this taskA__1 .How do I access this in the decision task

**Comment by kishorebanala** [comment]
@ritu-p would this help? https://github.com/Netflix/conductor/issues/1890#issuecomment-701441358
