### ISSUE TITLE
Question: How can I avoid to download dependencies every time when running docker-compose build

### ISSUE THREAD

**Issue by Yingsheng-eroad** [Netflix/conductor#1898]
I am not familiar with Gradle at all. 
It keeps downloading dependencies every time when I am running `docker-compose build`. Is there a way to avoid this? 
volume?

**Comment by demichej** [comment]
Unfortunately, this is more of a Docker/Gradle question than a Conductor question. Here's a SO question that is relevant: https://stackoverflow.com/a/50467205/115694

**Comment by kishorebanala** [comment]
Closing this issue, please feel free to re-open if you have any further questions.
