### ISSUE TITLE
Apache Camel Integration?

### ISSUE THREAD

**Issue by k0105** [Netflix/conductor#190]
Hi,

if I need my orchestrator to integrate with many different systems using Enterprise Integration Patterns - can I use Apache Camel for this? What is the relationship between Camel and Conductor and if they should not directly work together - what would it take to integrate them?

Thank you in advance.

Best wishes,
Joe

**Comment by v1r3n** [comment]
@k0105 We have not tried Apache Camel, and there is no relationship between the two.
