### ISSUE TITLE
how does the worker undergo execution of a workflow?

### ISSUE THREAD

**Issue by mishika29** [Netflix/conductor#1905]
Hello,

I am trying to use conductor to execute a registered workflow.
I am struggling with how the workers work to do so.
As per my understanding until now, the worker must poll for a task for its execution, but the API call needs the task type to be passed to it.
How will the worker know the task type while polling for it?
The API we are using to poll for a task is:
http://51.79.140.163:8080/api/tasks/poll/encode - where encode is the tasktype
This gives the task details in response whereas how will the worker get the tasktype to poll for it.
 
Is there a way where conductor gives the next task to be executed without sharing its task type and just with the workflow id?

**Comment by apanicker-nflx** [comment]
@mishika29 Workers are configured to execute specific task types and are not tied to the workflow executions. Please refer to the documentation [here](https://netflix.github.io/conductor/gettingstarted/client/) for how to use the java client. This is a [sample worker implementation](https://github.com/Netflix/conductor/blob/dev/client/src/test/java/com/netflix/conductor/client/sample/SampleWorker.java) which shows how the worker is tied to a specific task (P.S. ```getTaskDefName```).  This allows the worker to keep processing tasks of a specific type across multiple workflow executions. 

The conductor server will schedule the next task within the workflow and the worker polls and executes the tasks as available from the server. The `TaskRunnerConfigurer` in the java client automates the process of polling for the task and updating the server with the result.

**Comment by shiva-moorthy** [comment]
@apanicker-nflx I could understand how this works. Does the python client behave the same way?
Also, I see that there is another possible implementation of worker. i.e, we can create a system task and call an API hosted on worker from this system task for triggering the task. The worker can then execute the task and update the conductor on status (COMPLETED, FAILED and so on) . Is this understanding correct. 
If yes, what is the best approach ? I see that polling does put some pressure on the network as it keeps on firing HTTP calls often (if I am not wrong). Your inputs would help here.

**Comment by apanicker-nflx** [comment]
@shiva-moorthy The python client is a community contribution and is maintained by the OSS community. However, I believe it does honor the same contracts as that of the java client.

>another possible implementation of worker. i.e, we can create a system task

As opposed to SIMPLE tasks which are implemented by a worker, System tasks are executed by the Conductor server. Please refer the [documentation](https://netflix.github.io/conductor/gettingstarted/basicconcepts/#system-tasks) for specifics.

>I see that polling does put some pressure on the network as it keeps on firing HTTP calls

That is correct, polling does add some extra pressure on the network, however, this can be substantially controlled on the client by setting appropriate values for poll interval and maintaining an active fleet of workers in accordance with the number of tasks.
