### ISSUE TITLE
Is there a way to start a workflow from a particular task? Say I have task1 , task2, task3, task4 can I start a workflow from task3 giving the correct workflow inputs?

### ISSUE THREAD

**Issue by ritu-p** [Netflix/conductor#1907]

**Comment by apanicker-nflx** [comment]
This is not supported. Would it help to break up your workflow into subworkflows if you only want a subset of tasks to be executed? The subworkflow (which is a separate workflow) could now be executed by itself.

**Comment by TwoUnderscorez** [comment]
@ritu-p How about [events](https://netflix.github.io/conductor/configuration/eventhandlers/#event-task)?
