### ISSUE TITLE
How to update workflow variables from a simple task ?

### ISSUE THREAD

**Issue by conductor-boot** [Netflix/conductor#1910]
Is it possible to update the value of a workflow variables from a simple task ? Without actually using a Set Variable task.

**Comment by elisherer** [comment]
No. Workers can only update tasks.
https://netflix.github.io/conductor/labs/beginner/#return-response-add-logs

It is best to use only Set Variable tasks to update the value of variables.

**Comment by conductor-boot** [comment]
Thanks
