### ISSUE TITLE
Build error in latest version

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1912]
**conductor git:(master) ./gradlew build -x test**
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Inferred project: conductor, version: 2.31.0-SNAPSHOT
Download https://jcenter.bintray.com/com/github/jknack/handlebars/maven-metadata.xml

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/yumiao3/workspace/github/conductor/server/build.gradle' line: 9

* What went wrong:
Plugin [id: 'com.github.ManifestClasspath', version: '0.1.0-RELEASE'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.ManifestClasspath:com.github.ManifestClasspath.gradle.plugin:0.1.0-RELEASE')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 25s

**Comment by kartikv11** [comment]
+1 facing the same issue.

**Comment by apanicker-nflx** [comment]
Could you please run the same command with --stacktrace and post the detailed error?
