### ISSUE TITLE
params for failureWorkflow

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#1913]
How does we pass on the parameters to the failureWorkflow? or does workflow definition support parameter for failureWorkflow？

**Comment by demichej** [comment]
I believe that the failureWorkflow has access to the input parameters to the workflow itself when starting the workflow.

**Comment by apanicker-nflx** [comment]
As noted by @james-deee , failure workflow has access to input parameters for the workflow.
[This](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L757-L776) is the complete input to the failure workflow. It includes the workflowId, status, reason, workflow input.
