### ISSUE TITLE
/api/tasks/queue/all sometimes excludes tasks belonging to task domains

### ISSUE THREAD

**Issue by tomasol** [Netflix/conductor#1914]
Since the `/api/tasks/queue/all` API is not documented here https://netflix.github.io/conductor/apispec/
I am just guessing it should be possible to obtain `PollData` for all queues. However reading https://github.com/Netflix/conductor/blob/d6b5ca91ab0e0bcc30772b9371a98286ddf87c9b/core/src/main/java/com/netflix/conductor/service/ExecutionService.java#L206 shows that queues with task domains are actively filtered out. What is the reason behind this decision?

After PR https://github.com/Netflix/conductor/pull/1885 was merged, it seems like this filtering only happens when the queueDAO is not one of Postgres, MySQL. Is this expected behavior of this API?

What is the preferred way to obtain list of `PollData`  for all queues, including those with a task domain?

**Comment by apanicker-nflx** [comment]
@tomasol We are considering refactoring the API to obtain PollData for **all** queues. From the feedback that we have collected from our users, we see that as a task owner, users are primarily interested in the PollData for specific tasks across all domains. The `/tasks/queue/polldata?taskType=<INSERT_TASK_NAME_HERE>` API satisfies this requirement and is more streamlined. 
Could you please comment on your usage of this API?
