### ISSUE TITLE
How to get DecisionTasks output with multiple tasks on a single decision case.

### ISSUE THREAD

**Issue by vamsibandarupalli** [Netflix/conductor#1917]
I looked into [EXCLUSIVE_JOIN](https://netflix.github.io/conductor/configuration/systask/#exclusive-join), it gives output of executed decision case where only single task present in each decision case.

Example: 
In Exclusive_Join it is mentioned that, 
  True: T1 -> T2 -> EJ; EJ will have T2's output.
  False: T1 -> T3 -> EJ; EJ will have T3's output.

My workflow is
 True: T1 -> T2,T3 -> EJ; I need both T2 and T3 tasks output here.
 False: T1 -> T4,T5 -> EJ; I need both T4 and T5 tasks output here.
In "True" decision case I have T2 and T3 tasks executing and in "False" decision case I have T4 and T5 tasks executing.

I tried Exclusive_Join like this
{
            "name": "simple_task",
            "taskReferenceName": "Decision1_join",
            "inputParameters": {
            },
            "type": "EXCLUSIVE_JOIN",
            "decisionCases": {},
            "defaultCase": [],
            "forkTasks": [],
            "startDelay": 0,
            "joinOn": [
				"T2",
				"T3",
				"T4",
				"T5"
			],
            "optional": false,
            "defaultExclusiveJoinTask": [],
            "asyncComplete": false,
            "loopOver": []
        }

when tried "${Decision1_join.output}" in workflow outputParameter:
   - In true decision case I was always getting T2's output.
   - In false decision case I was always getting T4's output.

How to get multiple tasks output in a single decision case?

**Comment by jkaipa** [comment]
```
"joinOn": [
"T2",
"T3",
"T4",
"T5"
```
means, all T2, T3, T4, and T5 are forked from a decision. So, your usage is not correct per what you are expecting. 
If you want the output of T2, T3 together (I assume that T3 gets executed after T2 completes) you need to pass the output of T2 to T3 and hold all the values to pass on to join. In this case, you will do joinOn only on the tasks T3 and T5 per your scenario.

**Comment by vamsibandarupalli** [comment]
> ```
> "joinOn": [
> "T2",
> "T3",
> "T4",
> "T5"
> ```
> 
> means, all T2, T3, T4, and T5 are forked from a decision. So, your usage is not correct per what you are expecting.
> If you want the output of T2, T3 together (I assume that T3 gets executed after T2 completes) you need to pass the output of T2 to T3 and hold all the values to pass on to join. In this case, you will do joinOn only on the tasks T3 and T5 per your scenario.

How to pass output of T2 to T3? If somehow we passed T2's output to T3 and reference "T3.output" in workflows outputParameter we will get both T2 and T3 whereas we are expecting only T3's output. 

> "joinOn": [
> "T2",
> "T3",
> "T4",
> "T5"

This representation may be wrong but I do need output of all the tasks that are executed in single decision case without sending one tasks output to other task.

**Comment by jkaipa** [comment]
```
I do need output of all the tasks that are executed in single decision case without sending one tasks output to other task.
```
Without passing one tasks output to another, you would not be able to get what you are looking for. Because, the total workflow execution is stateless. They are all completely distinct. Unless you piggyback the output from T2 to T3, you cant get the T2's output as part of your T3.

**Comment by apanicker-nflx** [comment]
Also, consider the [SET_VARIABLE](https://netflix.github.io/conductor/configuration/systask/#set-variable-task) system task which may be helpful to your use-case here.
