### ISSUE TITLE
Question : is conductor suitable for polling tasks that takes long time? 

### ISSUE THREAD

**Issue by timpamungkas** [Netflix/conductor#1919]
Hi, I got an (oversimplified use case). Assume I have these tasks to be arranged : 
  

1. submit data - HTTP task, call API to insert data
2. human approval, for submitted data. This should happened within 2x24 hours after data submitted, otherwise task is marked as timed out and send to "invalid" status
3. decision task - based on number 2 outcome (approved / rejected / timed out)
4. the other tasks involves calling API, update database, or publish to kafka
  
**Question**

a. On task 2, I set the `retryCount` to 48, and `retryDelaySeconds` to 3600 (1 hour). Is such settings (due to I must handle manual process) suitable for conductor?   Basically it will poll every hour for the next 48 hours, before marked as timed out. The task itself is basically querying data from system X, to see whether user already approve / reject it.
b. On task 3, can I have "time out" outcome? On my worker, I only set `approved` or `rejected`, based on data entered by user. 

  
I found [this issue](https://github.com/Netflix/conductor/issues/500), but it doesn't includes time out scenario 

Thanks

**Comment by aravindanr** [comment]
DECISION task supports as many cases as needed. https://netflix.github.io/conductor/configuration/systask/#decision, In the worker, the output of task 2 can be set as "time out" and task 3 can have a case for it. I am closing the question, but feel free to re-open if you need more information.

**Comment by timpamungkas** [comment]
The timeout should happened automatically after 48 hours. So is this long-window (48 hours) is suitable using conductor?

**Comment by aravindanr** [comment]
Yes. that should be fine. The timeout can be set to any value as the use-case demands.
