### ISSUE TITLE
Conductor UI 404 - Not Found with Exception if workflow has "/" in name

### ISSUE THREAD

**Issue by cquon** [Netflix/conductor#192]
In the Conductor UI, when monitoring the Workflow executions, you are able to click on the workflow id which leads to a page with the "Execution Flow" graph, "Task Details", "Input/Output", and "JSON" tabs.

However when my workflow name has a forward slash "/" character it appears to be throwing a no response error:

404 - Not Found
"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Error: Not Found<br> &nbsp; &nbsp;at Request.callback (/app/ui/node_modules/superagent/lib/node/index.js:698:17)<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/app/ui/node_modules/superagent/lib/node/index.js:922:12)<br> &nbsp; &nbsp;at emitNone (events.js:91:20)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:185:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:974:12)<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:80:11)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:104:9)</pre>\n</body>\n</html>\n"

I am able to use the REST API <ip>:<port>/api/workflow/<workflow_id>?includeTasks=true and query all the tasks for a workflow, but it would be nice if the UI could show it.

**Comment by v1r3n** [comment]
I would suggest avoid using '/' in the workflow names.
