### ISSUE TITLE
unable to execute function that implements task using go client 

### ISSUE THREAD

**Issue by archthegit** [Netflix/conductor#1923]
Hi I am using the go client. And as with the example I have a main.go file that starts workers for a task 
```
func main() {
	c := conductor.NewConductorWorker("http://localhost:8080/api", 1, 10)
	c.Start("task_login", HttpLoginTask, false)
```
I also have a login.go file with the task execution implementation
```
func HttpLoginTask(t *task.Task) (taskResult *task.TaskResult, err error) {
	log.Println("Executing HttpLoginTask for", t.TaskType)
	requestBody, _ := json.Marshal(t.InputData)

	response, err := http.Post("http://demo564.mockable.io/login/","application/json", bytes.NewBuffer(requestBody))

	if err != nil || response.StatusCode != http.StatusOK {
		return nil,err
	}
	bodyBytes, err := ioutil.ReadAll(response.Body)
	if err != nil {
		taskResult.Status = "FAILED"
		taskResult.OutputData = nil
		return taskResult, err
	}

	var res LoginResponse
	_ = json.Unmarshal(bodyBytes, &res)
	if err != nil {
		taskResult.Status = "FAILED"
		taskResult.OutputData = nil
		return taskResult, err
	}
	taskResult = task.NewTaskResult(t)

	var output map[string]interface{}
	temp, _ := json.Marshal(res)
	json.Unmarshal(temp, &output)

	taskResult.OutputData = output
	taskResult.Status = "COMPLETED"

	return taskResult, nil
}
````

And then I registered this task by posting the task to http://localhost:8080/api/metadata/taskdefs
```
{
    "name": "task_login",
    "ownerEmail": "test@email.com",
    "retryCount": 3,
    "retryLogic": "FIXED",
    "retryDelaySeconds": 10,
    "timeoutSeconds": 300,
    "timeoutPolicy": "TIME_OUT_WF",
    "responseTimeoutSeconds": 180
  }
````
And then I run my workflow by posting the following  workflow to /api/metadata/workflow and then to /workflow 

````
"name": "user_login_worklfow",
  "description": "login user",
  "version": 1,
  "ownerEmail":"test@email.com",
  "schemaVersion": 2,
  "tasks": [
    {
      "name": "task_login",
      "taskReferenceName": "task_login",
      "inputParameters": {
        "username":"test",
        "password":"test"
      },
      "outputParameters":{
        "AccountID": "${task_login.output.AccountID}",
        "Status":"${task_login.output.Status}"
      },
      "type": "SIMPLE"
    }
]
`````

I can see the workflow on the UI but I get no output afterwards, I think the task doesn't even execute the underlying login function, am I missing a step ?

**Comment by apanicker-nflx** [comment]
@tartale As a user and contributor to the go client, can you please help answer this question?

**Comment by tartale** [comment]
@apanicker-nflx - Hi!  I'd love to help but have moved on from the project that was working with Netflix conductor and I haven't used it in awhile, so I don't think I could help troubleshoot

**Comment by apanicker-nflx** [comment]
@anuccio1 / @djcass44 could you please help with this issue?

**Comment by djcass44** [comment]
@archthegit looks like you're using an older version of the Go client. There were some fixes introduced recently, can you try updating?

**Comment by archthegit** [comment]
Hi @djcass44 it still doesnt work with the newer version of the client, the workflow just times out still. However, when I comment out the continue in this block of code in conductorworker.go the workflow runs successfully. Am I creating my workflow wrong ?
```
_, ackErr := c.ConductorHttpClient.AckTask(parsedTask.TaskId)
		if ackErr != nil {
			log.Println("Error Acking task:", ackErr.Error())
			continue
		}
```

**Comment by djcass44** [comment]
Looks like I missed a bit when I last updated the client. @apanicker-nflx can you take a look at #1942
