### ISSUE TITLE
ES 6 index mapping issue for type: task

### ISSUE THREAD

**Issue by ketantalreja** [Netflix/conductor#1925]
Hi All, I am using Netflix conductor v2.27.2 with ES 6.4.3 configuration as below -

workflow.elasticsearch.instanceType=external

Transport address to elasticsearch
workflow.elasticsearch.url=es:9300

Name of the elasticsearch cluster
workflow.elasticsearch.index.name=conductor
workflow.elasticsearch.version=6
workflow.elasticsearch.tasklog.index.name=task

And I am getting error below when I am performing a search query on ES to get the total count for workflow executions,

ERROR com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5 - Failed to index object of type: task

Here is the mapping information I get from /conductor/_mapping
```
    "conductor": {
        "mappings": {
            "workflow": {
                "properties": {
                    "correlationId": {
                        "type": "keyword"
                    },
                    --------
                }
            }
        }
    }
}
```
However, if I use ES 5.x with netflix conductor v2.27.2, there is no problem with the ES indexing on workflow exeuctions, and I get mapping information for both types i.e. workflow and task
```
{
    "conductor": {
        "mappings": {
            "workflow": {
                "properties": {
                    "correlationId": {
                        "type": "keyword"
                    },
                    --------
                }
            },
            "task": {
              "properties": {
                    "correlationId": {
                        "type": "keyword"
                    },
                    --------
                }
            }
        }
    }
}
```

When I execute the workflow I get below error stack trace, 

```
ao-conductor          | 715766 [pool-9-thread-4] ERROR com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5  - Failed to index object of type: task
ao-conductor          | java.lang.IllegalStateException: The attempt resulted in a result, not in an exception
ao-conductor          |         at com.github.rholder.retry.Retryer$ResultAttempt.getExceptionCause(Retryer.java:233)
ao-conductor          |         at com.netflix.conductor.common.utils.RetryUtil.retryOnException(RetryUtil.java:126)
ao-conductor          |         at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.updateWithRetry(ElasticSearchDAOV5.java:571)
ao-conductor          |         at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.indexBulkRequest(ElasticSearchDAOV5.java:563)
ao-conductor          |         at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.indexObject(ElasticSearchDAOV5.java:557)
ao-conductor          |         at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.indexTask(ElasticSearchDAOV5.java:404)
ao-conductor          |         at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.lambda$asyncIndexTask$4(ElasticSearchDAOV5.java:416)
ao-conductor          |         at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
ao-conductor          |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ao-conductor          |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624
```

Could anyone help me with ES 6 index mapping issue I am facing and if I have missed anything in the configuration. As I understand, ES 6 module is already registered in netflix conductor v2.27.2 so I don't have to explicitly register in the netflix conductor.
Also, my intention is to get workflow and task executions from ES indexing via search query and parse this execution data to read some of the fields from the workflow execution 'output' property. 

Thanks, Ketan.

**Comment by ketantalreja** [comment]
@kishorebanala, @apanicker-nflx  could you please have a look into this issue, and provide your inputs? 

Thanks, 
Ketan

**Comment by apanicker-nflx** [comment]
@ketantalreja Are you using the index templates provided within the ES modules? Both es5 and es6 modules provide their own mappings for the ES indices tailored to the ES versions. These may not be cross-compatible.

**Comment by ketantalreja** [comment]
@apanicker-nflx  I am using as-is ES template provided by ES module. Basically, my requirement is to get the workflow/task execution data from ES, and since ES 6, you cannot have more than one type of mapping for same index, there is no task execution data available when you call api ``` http://<host>:<port>/conductor/_search``` in elasticsearch. Also, the other issue related to this is https://github.com/Netflix/conductor/issues/1926, do you have any thoughts on this issue? 

Also, one more thing I wanted to understand, today, how conductor-ui module is displaying the workflow and task execution metrics?  What I understand looking into this conductor-ui code is first it calls ES search api to get workflow execution data, and then it goes to call the netflix conductor api to get task execution metrics. Please advise if this understanding is wrong. 

Thanks!

**Comment by apanicker-nflx** [comment]
The UI does not directly fetch data from the ES indices. It interacts with the API which will co-ordinate fetching results from the workflow and task indices (in ES6) and forming a workflow object with all the corresponding tasks embedded within it. The `/workflow/search` API on the server does this by first fetching the documents from ES and then hydrating the data from the primary datastore.
