### ISSUE TITLE
Parse/convert invalid json output from ES search index query to valid json object 

### ISSUE THREAD

**Issue by ketantalreja** [Netflix/conductor#1926]
Hi All, I am using Netflix conductor v2.27.2 with ES 5.x configuration as below -

workflow.elasticsearch.instanceType=external

Transport address to elasticsearch
workflow.elasticsearch.url=es:9300

Name of the elasticsearch cluster
workflow.elasticsearch.index.name=conductor

And I am getting below output when performing a search query on ES 'conductor' index,

Here is the output I get from /conductor/task/_search
```
{
                "_index": "conductor",
                "_type": "task",
                "_id": "3d1cde75-b507-4d4f-ba4c-93cab2a4613b",
                "_score": 1.0,
                "_source": {
                    "workflowId": "1325db12-ced0-40a8-bb5d-541dcfa236fb",
                    "workflowType": "Workflow Mock Test",
                    "scheduledTime": "2020-10-14T15:27:53.711Z",
                    "startTime": "2020-10-14T15:27:54.478Z",
                    "updateTime": "2020-10-14T15:27:54.513Z",
                    "endTime": "2020-10-14T15:27:54.836Z",
                    "status": "COMPLETED",
                    "executionTime": 358,
                    "queueWaitTime": 0,
                    "taskDefName": "ASYNC_HTTP",
                    "taskType": "ASYNC_HTTP",
                    "input": "{uiState={inputKeys=[{variableName=taskName, defaultValue=custom_3, required=false}, {variableName=operationId, defaultValue=606e5721-6ee6-4abc-8424-47f928c431b9, required=false}], customTaskType=AsyncHttp}, executionId=aa6fce24-a131-440b-aecc-3a1b7581b89a, asyncComplete=true, concurrentExecLimit=10, http_request={headers={X-Task-Reference-Name=custom_3, X-Workflow-Instance-Id=1325db12-ced0-40a8-bb5d-541dcfa236fb, X-Operation-Id=606e5721-6ee6-4abc-8424-47f928c431b9}, method=POST, body={\"srcAeTitle\":\"\",\"port\":\"4000\",\"host\":\"x.x.x.x\",\"executionId\":\"aa6fce24-a131-440b-aecc-3a1b7581b89a\",,\"workflowExecutionId\":\"24a0fad2-7508-416a-907f-d5d8ccae2e48\"}, uri=http://host:8080/v1/abc}}",
                    "output": "{ackResponse={executionId=aa6fce24-a131-440b-aecc-3a1b7581b89a, response={headers={Date=[Wed, 14 Oct 2020 15:27:54 GMT], Content-Type=[application/json;charset=UTF-8], Transfer-Encoding=[chunked]}, body={executionId=aa6fce24-a131-440b-aecc-3a1b7581b89a, workflowExecutionId=24a0fad2-7508-416a-907f-d5d8ccae2e48, status=IN_PROGRESS, type=STORE}, statusCode=200, reasonPhrase=OK, state=SUCCESS, responseState=SUCCESS}}, asyncResponse=[{status=COMPLETED}]}",
                    "taskId": "3d1cde75-b507-4d4f-ba4c-93cab2a4613b",
                    "workflowPriority": 0
                }
            }
```   
In the above json 'output' as you can see it's outputting in a hashmap format (ES is indexing in a map like format), and I have a use case to convert this invalid 'output' json in a correct json format i.e. {"a":"b", "c":"d"} , Could anyone please suggest or advise what would be the right approach to convert this invalid json to valid json so that I can easily read its values.

Thanks, Ketan.

**Comment by apanicker-nflx** [comment]
The `output` in this ES document is being written because this is the stringified version of `outputData` from the task. This conversion is being applied [here](https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/run/TaskSummary.java#L123-L125). 

> Could anyone please suggest or advise what would be the right approach to convert this invalid json to valid json so that I can easily read its values.

If you want to write this as json instead, I would suggest implementing your own [IndexDAO](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/dao/IndexDAO.java) which does not use the stringified versions of input and output but uses expanded json versions instead in your indexed document.
