### ISSUE TITLE
Is that possible to make ES6/ES5 module configurable?

### ISSUE THREAD

**Issue by willqiao** [Netflix/conductor#1927]
Hi Conductor team,

I understand how we switch the ES6 and ES5 currently, by using the same "ElasticSearchModule" class presented in both es6 and es5 dependency jar file. Is that possible to make it configurable like how we hook up with other modules? By changing following logic a little bit, maybe using String value of a class name to create the module? 

The reason that we request this is, we are currently building conductor server in our own gradle build process by using conductor-server-all.jar It is not easy to replace an individual jar file in that server-all.jar as the server-all.jar mesh all of the classes together from all dependency jar files. 

If this is not possible, why dont we keep the ES6 as default version, why use ES5 as default? Is there any reason behind it? We want to use latest version as possible to reduce any security/performance issues. 

        if (configuration.isIndexingPersistenceEnabled())
            modules.add(new ElasticSearchModule());
        else
            modules.add(new NoopIndexModule());

**Comment by apanicker-nflx** [comment]
@willqiao The ES6 module is currently published as a shadowJar to avoid dependency conflicts with ES5 which is the default ES version in conductor 2.x 
When we upgrade Conductor to the next major version 3.x, we plan to make ES6 as the default and remove ES5.
