### ISSUE TITLE
TERMINATE workflowOutput not overriding the outputParameters in workflow.

### ISSUE THREAD

**Issue by vamsibandarupalli** [Netflix/conductor#1928]
I have a basic workflow which have one decision task, for decision when first condition is met I have TERMINATE task, on all other conditions I want to execute some other tasks.

For TERMINATE tasks "workflowOutput", I'm giving some static string output. And for workflows "outputParameters" key, I've given other tasks output.

When TERMINATE task is executed, I'm expecting just the static output that assigned to "workflowOutput" key, but I'm getting output from what I defined in "outputParameters".

Example Workflow definition:
{
    "name": "netflix_identation_terminate",
    "description": "Adds Netflix Identation to video files.",
    "version": 2,
    "schemaVersion": 2,
    "tasks": [{
            "name": "verify_if_idents_are_added",
            "taskReferenceName": "ident_verification",
            "inputParameters": {
                "contentId": "${workflow.input.contentId}"
            },
            "type": "SIMPLE"
        }, {
            "name": "decide_task",
            "taskReferenceName": "is_idents_added",
            "inputParameters": {
                "case_value_param": "${ident_verification.output.is_idents_added}"
            },
            "type": "DECISION",
            "caseValueParam": "case_value_param",
            "decisionCases": {
                "false": [{
                        "name": "add_idents",
                        "taskReferenceName": "add_idents_by_type",
                        "inputParameters": {
                            "identType": "${workflow.input.identType}",
                            "contentId": "${workflow.input.contentId}"
                        },
                        "type": "SIMPLE"
                    }
                ]
            },
            "defaultCase": [{
                    "name": "terminate",
                    "taskReferenceName": "terminate0",
                    "inputParameters": {
                        "terminationStatus": "COMPLETED",
                        "workflowOutput": "${ident_verification.output}"
                    },
                    "type": "TERMINATE",
                    "startDelay": 0,
                    "optional": false
                }
            ]
        }
    ],
    "outputParameters": {
        "result": "${ident_verification.output}",
        "add_idents_by_type": "${add_idents_by_type.output}"
    }
}

I need just the "workflowOutput" when TERMINATE task executed. Instead getting whatever I mentioned in "outputParameters"

**Comment by apanicker-nflx** [comment]
@vamsibandarupalli Thanks for reporting this. Upon initial investigation, it seems that the `outputParameters` in the workflow definition will overwrite the workflow output that was set from within the TERMINATE task.
Please feel free to submit a PR with the fix if you need this immediately, else we will fix this in a future release.
