### ISSUE TITLE
Deploying Conductor with HA and DR in mind

### ISSUE THREAD

**Issue by TwoUnderscorez** [Netflix/conductor#1934]
Hi, I'm trying to wrap my head around how one should deploy Conductor.

I would like to deploy the Conductor as active-active across 3 k8s clusters. That is, I would like to have the same amount of all workers in 3 different k8s clusters.
My 2 goals are:
1. Have the workload distributed as much as possible across 3 AZs
2. Be able to recover from an AZ failing. Not just restarting, but completely going down for an unknown amount of time. 

From my understanding, I should deploy 3 Dynomite nodes in each of those 3 k8s clusters (total of 9) and one Conductor node in each k8s cluster with the conductor's `EC2_AVAILABILITY_ZONE` setting set to that zone's name (3 total). Using a Dynomite config similar to [this](https://gist.github.com/TwoUnderscorez/ac9b7450a1968eba828017b235b1a938).

I also have a microservice similar to [Schellar](https://github.com/flaviostutz/schellar) (mentioned in `RELATED.md`) which will either need to be active-passive or active-active (and implement workload sharding) depending on whether `workflow.dyno.queue.sharding.strategy` is `roundRobin` or `localOnly`. I prefer `roundRobin` but also fine with `localOnly` as long as my 2 main goals are reached.

Assuming  `workflow.dyno.queue.sharding.strategy` is `roundRobin`:
I have read #1246 and #1278 and faced the same issues where only 1/3 of the tasks are pulled. I have read @apanicker-nflx answer [here](https://github.com/Netflix/conductor/issues/1287#issuecomment-529289190) and [here](https://github.com/Netflix/conductor/issues/1287#issuecomment-547198174) and don't seem to understand what the structure should be. Are you saying that I should deploy Dynomite, Conductor, all the workers and scheduling microservice, say in us-east-1c, then along with Dynomite in us-east-1d and us-east-1e I should have one Conductor node and then have the workers in us-east-1c poll from the Conductor in us-east-1c, us-east-1d, and us-east-1e?
Why not deploy an equal amount of workers across all 3 AZs and make the scheduling microservice active-pasive-pasive? (Goal 1)

Assuming I can deploy all the workers equally across 3 AZs and deploy the scheduling microservice as active-passive-passive, how, if at all, can I continiue executions if one AZ goes completly down (not just restarts)? (Still assuming `workflow.dyno.queue.sharding.strategy` is `roundRobin`) An important point is that my workflows don't take very long to run and I am completly fine letting them time out, after all, an entire AZ has just failed, but the next time my scheduling microservice schedules them (which it won't untill they time out thanks to [`WorkflowStatusListener`](https://netflix.github.io/conductor/extend/#workflow-status-listener)) I'll want the system to work properly, perhaps a little overloaded, but still work. (Goal 2).

Now if I can't do that, we'll assume `workflow.dyno.queue.sharding.strategy` is `localOnly`.
If I shard my workloads properly, could I deploy basically everything as stated above except my scheduling microservice is now active-active-active?
I'll also need to detect AZ failiures and reassign tokens for workload sharding to my scheduling microservice to achieve goal 2. Am I breaking anything or should I expect any problems with Conductor, Dynomite, or dyno-queues when doing that?

Thanks to anyone in advance who helps me here.

Notes:
1. I won't actually be using aws.
2. I am not using [dynomite-manager](https://github.com/Netflix/dynomite-manager), I will implement my own with similar functionallity.
3. If a Dynomite node fails and restarts (crashed, evicted by k8s, etc...) it will come back up with the same tokem configured as well as the same host name / same k8s load balancer host and port . It'll then warm up from another node with the same token from another AZ. If all other racks can't be reached (assuming they are down and the network is fine) the node will try to restore from a backup. If that fails. It'll assume this is the first ever node with this token in the system.
4. If an entire AZ fails and restart, each one of the Dynomite nodes will preform 3.

P.S.
Is there a way to not use the AWS naming scheme? What are all the relevant settings names (the equivalent of `EC2_AVAILABILITY_ZONE` for example)?

**Comment by apanicker-nflx** [comment]
>Are you saying that I should deploy Dynomite, Conductor, all the workers and scheduling microservice, say in us-east-1c, then along with Dynomite in us-east-1d and us-east-1e I should have one Conductor node and then have the workers in us-east-1c poll from the Conductor in us-east-1c, us-east-1d, and us-east-1e?

Because of the limitation imposed by dyno-queues, you would need to install dynomite in 3 AZs alongwith the Conductor server in 3 AZs. However your workers and the scheduling microservice(I assume you use this to start workflows) need not be in all of the AZs as long as the interaction between Conductor and your workers/scheduling service is done using a DNS resolver and not using instance IPs.

**Comment by TwoUnderscorez** [comment]
@apanicker-nflx assuming my scheduling microservice shards my workload properly, could I set the dyno queues to `localOnly` and basically have each AZ do 1/3 of the work? (Each AZ has it's own set of workers that'll be polling only from the local to them conductor, what I've explained above)

**Comment by marosmars** [comment]
Hey @TwoUnderscorez

We have recently been investigating HA deployment of conductor + dynomite too.
Long story short, we have decided to move away from dynomite as a primary database in favor of RDBMS  (MySQL or PSQL).
The deployment difficulties and operational aspects of dynomite were just not worth it (also considering it is no longer actively maintained). 

Comparing performance of Dynomite vs PSQL in a workflow specific to us, we have measured following throughput:
* single dynomite, single conductor with 4 workers  ==  684 WFs per minute
* single psql node, single conductor with 4 workers  ==  564 WFs per minute

So the performance hit of using PSQL was lower than expected, considering there is extensive locking going on in PSQL. And overall, the functionality and performance when using PSQL seemed totally OK.

Regarding MySQL vs PSQL: Even though the implementation in conductor is almost identical, we have found that the performance of PSQL was superior (with default configuration for MySQL and PSQL). Also, there are superior tools to deploy and manage PSQL clusters in kubernetes (https://github.com/zalando/patroni, postgres-operator) when compared to MySQL.

Right now we are developing a deployment including PSQL in kubernetes:
* PSQL : 1 active node, 2+ standby nodes (patroni managing the cluster and performing failover)
* Conductor: N active nodes, all connected to the active PSQL node
* Workers: N workers, can talk to Conductor nodes round robin

Note: We have used this patch in conductor when testing PSQL performance: https://github.com/Netflix/conductor/pull/1940
Note2: The nice thing about using RDBMS is that you should be able to use a database provided and managed by your cloud provider (which is not possible with dynomite).

**Comment by TwoUnderscorez** [comment]
@marosmars thanks for sharing!
I'll definitely check out patroni and RDBMS persistence. 
By the way, according to #1763 dynomite is still being maintained.

**Comment by marosmars** [comment]
@TwoUnderscorez thanks for sharing info regarding dynomite. But the activity in dynomite seems very low (just 3 PRs merged during 2020). And also, I believe netflix is no longer using dynomite as the backend for conductor ... at least not for the queues.
