### ISSUE TITLE
Security Policy (VDP)?

### ISSUE THREAD

**Issue by mrthankyou** [Netflix/conductor#1936]
Hi,

If security researchers discover any security vulnerabilities within the conductor application, where should the bug report be submitted to? Through Netflix's Bugcrowd program? On github? Via secure email?

Thanks!

**Comment by apanicker-nflx** [comment]
Please report security vulnerabilities through the Netflix Bugcrowd program.

**Comment by mrthankyou** [comment]
Thank you for the help!
