### ISSUE TITLE
Dyno-queues are no longer maintained

### ISSUE THREAD

**Issue by TwoUnderscorez** [Netflix/conductor#1949]
Hi,

I noticed this on [dyno-queue](https://github.com/Netflix/dyno-queues)'s README.md;

> DISCLAIMER: THIS PROJECT IS NO LONGER ACTIVELY MAINTAINED

Which is used with the Dynomite persistence layer, which is the default.
How does this affect deployment recommendations?
Will the Dynomite persistence layer become obsolete?

**Comment by kishorebanala** [comment]
@TwoUnderscorez We were working on a transition plan from dyno-queues to another default Queue implementation.

For the short term, We'll mark the dyno-queues implementation in Conductor as deprecated as well, and add a disclaimer for the same in read me. Please explore other Queueing implementations like MySQL or Postgres.

For the long term, most likely in Conductor v3, we'll port over the default queueing implementation in Conductor away from dyno-queues.

**Comment by TwoUnderscorez** [comment]
Thanks

**Comment by sureshkmit** [comment]
Is there any alternate for this project?
