### ISSUE TITLE
Switching out SQS/DB; need to eliminate AWS dependencies

### ISSUE THREAD

**Issue by kpdude7** [Netflix/conductor#195]
Has anyone had any experience switching out the default implementations for queuing and persistence? We have a need to eliminate all AWS dependencies and would like to know how involved it is to accomplish this. Exactly what interfaces need to be implemented and which classes need to be overridden? Are there issues we need to be aware of?

**Comment by v1r3n** [comment]
@kpdude7 the default implementation for queuing does not use SQS.  Dynomite is also not an AWS specific implementation.

Conductor supports SQS for events (in the contribs module), but that is optional and is not required.

Visit https://github.com/Netflix/dynomite for more details on dynomite.
