### ISSUE TITLE
WorkflowStatusListener for timed out workflow

### ISSUE THREAD

**Issue by TwoUnderscorez** [Netflix/conductor#1950]
We are using the `DynoQueueStatusPublisher` for scheduling workflows, which implements the `WorkflowStatusListener` interface, but from what I've seen, timed out workflows don't seem to trigger it. Is that on purpose? If so, would you consider to either add a method to the interface for timed out workflows or count timed out workflows as terminated?
https://github.com/Netflix/conductor/blob/d38bdd54cb6adba5ab8f2078c9cf9df3d03e59b9/core/src/main/java/com/netflix/conductor/core/execution/WorkflowStatusListener.java#L9-L12

**Comment by kishorebanala** [comment]
Hey @TwoUnderscorez, Can you provide an example where the `WorkflowStatusListener` is invoked for other terminal workflow states, but not for TIMED OUT workflow please? Looking through the execution path for WorkflowStatusListener, I couldn't trace any gaps for when this would fail to be invoked for TIMED OUT workflows.

**Comment by TwoUnderscorez** [comment]
Yes sorry, it works properly. Timed out workflows go to the terminated queue. The problem was probably  the network issues we were experiencing, which is the reason workflows were timing out in the first place.
