### ISSUE TITLE
Register multiple WorkflowStatusListeners

### ISSUE THREAD

**Issue by TwoUnderscorez** [Netflix/conductor#1951]
We are using the `DynoQueueStatusPublisher` for scheduling workflows, but we would also like to use the [Archiving Module](https://netflix.github.io/conductor/server/#1-enable-archiving-module), when enabling both of them I get an error saying that a class is already bound to `WorkflowStatusListener` either here
https://github.com/Netflix/conductor/blob/2aae31cff1a3cf4c304cf937deaf4152081cce08/contribs/src/main/java/com/netflix/conductor/contribs/DynoQueueStatusPublisherModule.java#L10
or here, depending on the order I add them to `conductor.additional.modules` in the config
https://github.com/Netflix/conductor/blob/b086bdc9c4002a45ec690d9268e5bd1063406803/contribs/src/main/java/com/netflix/conductor/contribs/ArchivingWorkflowModule.java#L28
How can I enable both?

**Comment by apanicker-nflx** [comment]
Currently, only one implementation of the WorkflowStatusListener can be plugged in. In order to enable both, you would need to create your implementation where you invoke both these listeners.

**Comment by TwoUnderscorez** [comment]
@apanicker-nflx Is it possible to enable multiple listener registrations? Is there any reason you wouldn't want to have all the status listeners be called one after the other in an order specified by the user? What is the correct/preferred pattern for implementing that? (I can open ap pr)

**Comment by apanicker-nflx** [comment]
> Is it possible to enable multiple listener registrations?

This is not supported.

> Is there any reason you wouldn't want to have all the status listeners be called one after the other in an order specified by the user?

The primary reason to not do this would be the failure scenarios that would arise from chaining multiple listener implementations. Apart from this, how failures need to be handled in each of these would be different for different use-cases. This would mean additional complexity that is introduced into the project when it could be differed to the implementer.

> What is the correct/preferred pattern for implementing that?

As mentioned earlier, I would recommend you to implement a custom listener where you would invoke both these implementations and you could also further extend this to add some other custom post processing that you may need for your use-case.
