### ISSUE TITLE
Subworkflow got COMPLETED but main workflow is still in RUNNING state

### ISSUE THREAD

**Issue by AnnsPhilip** [Netflix/conductor#1955]
We are using V2.29.0 release with Redis and Elasticsearch. We are facing issue after executing workflow. Subworkflow is completed but main workflow is still in running state. Is there any configuration to be added or am I missing anything?
![subworkflow](https://user-images.githubusercontent.com/65964511/98089771-3c9a8d00-1ea9-11eb-9e30-d7df3e85864e.PNG)
![MainWorkflow](https://user-images.githubusercontent.com/65964511/98089778-3efce700-1ea9-11eb-9c4c-2e28b97f33c5.PNG)

**Comment by james-deee** [comment]
Are you manually marking the "task" as completed in anyway? I think that if you just mark the Subworkflow task as COMPLETED, that doesn't mark the subworkflow completed in any way.

**Comment by AnnsPhilip** [comment]
No. Each subworkflow task is linked to worker and when worker completes automatically task status changes to completed.

**Comment by james-deee** [comment]
Hmmm. Alright, well we haven't experienced this yet on the latest version, sorry I don't have a better answer. You could try debugging the server.
________________________________

**Comment by AnnsPhilip** [comment]
Yes @james-deee We are trying to debug the server

**Comment by AnnsPhilip** [comment]
@james-deee Is there any Redis queue size configuration? Am getting below warning in logs
18995820 [pool-21-thread-1] WARN  com.netflix.dyno.queues.redis.RedisDynoQueue  - cannot add d728a994-4f9c-41e3-902a-12dd6ff36827 to the unack shard conductor_queues.test.UNACK._deciderQueue.c

**Comment by AnnsPhilip** [comment]
Below is the config.properties file configuration used by Netflix conductor
# Servers.
conductor.jetty.server.enabled=true
conductor.grpc.server.enabled=false

# Database persistence model.  Possible values are memory, redis, and dynomite.
# If ommitted, the persistence used is memory
#
# memory : The data is stored in memory and lost when the server dies.  Useful for testing or demo
# redis : non-Dynomite based redis instance
# dynomite : Dynomite cluster.  Use this for HA configuration.

db=redis

# Dynomite Cluster details.
# format is host:port:rack separated by semicolon
workflow.dynomite.cluster.hosts=redis:6379:us-east-1c

# Namespace for the keys stored in Dynomite/Redis
workflow.namespace.prefix=conductor

# Namespace prefix for the dyno queues
workflow.namespace.queue.prefix=conductor_queues

# No. of threads allocated to dyno-queues (optional)
queues.dynomite.threads=10

# Max connections
workflow.dynomite.connection.maxConnsPerHost=31

# Non-quorum port used to connect to local redis.  Used by dyno-queues.
# When using redis directly, set this to the same port as redis server
# For Dynomite, this is 22122 by default or the local redis-server port used by Dynomite.
queues.dynomite.nonQuorum.port=6379

# Elastic search instance type. Possible values are memory and external.
# If not specified, the instance type will be embedded in memory
#
# memory: The instance is created in memory and lost when the server dies. Useful for development and testing.
# external: Elastic search instance runs outside of the server. Data is persisted and does not get lost when
#           the server dies. Useful for more stable environments like staging or production.
workflow.elasticsearch.instanceType=external

#Worker Queue size used in executor service for async methods in IndexDao Defaults to 100
workflow.elasticsearch.async.dao.worker.queue.size=500

#Maximum thread pool size in executor service for async methods in IndexDao Defaults to 12
workflow.elasticsearch.async.dao.max.pool.size=500

#Using asynchronous indexing
async.indexing.enabled=true

# Transport address to elasticsearch
workflow.elasticsearch.url=elasticsearch:9300

# Name of the elasticsearch cluster
workflow.elasticsearch.index.name=conductor

#Mandatory check of ownerEmail while registering task and workflow
workflow.owner.email.mandatory=false

**Comment by kishorebanala** [comment]
@AnnsPhilip Can you please provide the Subworkflow and Workflow state and logs, when the subworkflow is completed. 

Upon subworkflow completion, the subworkflow task should be marked completed. And, if the subworkflow task is the last task in parent workflow, it should complete as well.

If the subworkflow task is not being updated on Subworkflow completion, it'd help to debug if there are any errors in updating the subworkflow task.

**Comment by AnnsPhilip** [comment]
@kishorebanala Attaching main workflow and subworkflow screenshots. Order_608655315960955689 is main workflow which is in RUNNING state and CREATE_SUBSCRIBER_INS is task(it is a subworkflow) which is in IN-PROGRESS state. 
We had added a trigger from subworkflow class(on IN-PROGRESS and COMPLETED/FAILED of subworkflow) to our application to update subworkflow status in our table, in logs we are able to see subworkflow start trigger but COMPLETED logs are not there(we are not receiving any trigger from Subworkflow class).
In 100 workflows 10 to 20 are getting stuck.
[NetflixLogs.txt](https://github.com/Netflix/conductor/files/5515728/NetflixLogs.txt)
![subworkflow2](https://user-images.githubusercontent.com/65964511/98646923-19b12280-235a-11eb-9489-a4e589c2fafc.PNG)
![MainWorkflow2](https://user-images.githubusercontent.com/65964511/98646928-1b7ae600-235a-11eb-9291-d84507d939e6.PNG)

**Comment by AnnsPhilip** [comment]
@kishorebanala  Any update based on my last comment?

**Comment by kishorebanala** [comment]
@AnnsPhilip From what you've mentioned, it looks like the Subworkflow's complete workflow logic is stopping [here](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L683), and thus the subsequent workflow status listener is not invoked.

I couldn't trace why the `updateParentWorkflowTask` call if failing from the logs you've provided. I'm also not sure which workflow/task this log corresponds to: 

```4789847 [system-task-worker-6] INFO  com.netflix.conductor.core.execution.WorkflowExecutor  - Task SUB_WORKFLOW/c5c2f688-0732-44d5-9d8d-422f4504c2a9 was already completed.```

Can you help trace the reason for `updateParentWorkflowTask` failure in L#863  above by checking why the update task is failing, and if possible by providing specific logs for this error, correlating it to the relevant sub workflow and task executions please. I'll try and reproduce this meanwhile.

**Comment by AnnsPhilip** [comment]
@kishorebanala Thank you for the reply. We had added IN-PROGRESS trigger to our application at end of start method and COMPLETED trigger at the end of execute method of class [this](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/tasks/SubWorkflow.java). As per our observation before IN-PROGRESS trigger completes, execute method got executed and workflowId was null, hence execute method was returning false. Attaching the logs. 
[SubworkflowLogs.txt](https://github.com/Netflix/conductor/files/5554305/SubworkflowLogs.txt)

 I suspect issue is due to the addition of IN-PROGRESS trigger code.

**Comment by kishorebanala** [comment]
> I suspect issue is due to the addition of IN-PROGRESS trigger code.

Hey @AnnsPhilip, I'm not sure I follow.. Is this any custom code / call back to Sub-workflow's `start` that get's in the way of execution?

**Comment by techyragu** [comment]
@AnnsPhilip Is this issue resolved ?

**Comment by AnnsPhilip** [comment]
@techyragu @kishorebanal Issue got solved after removing IN-PROGRESS trigger code. @kishorebanala @james-deee Thank you for the support.
Closing the issue.
