### ISSUE TITLE
Dynamic Subworkflow is getting stuck in IN_PROGRESS status and tasks won't get scheduled

### ISSUE THREAD

**Issue by nsargar** [Netflix/conductor#1964]
We have workflows with following structure,
W1 : T1....Tn
W2 : T1(W1) -> T2 [W1 is added as subworkflow]

So in batch processing we are triggering many (issue faced at 300+ calls) workflows simultaneously in 2-3 sec duration
We have found some (20-30) workflows (W1) stuck in RUNNING state 
After 3600+ secs task T1 of W2  gets TIMED_OUT and thus W2 gets TIMED_OUT, but workflow W1 is still in IN_PROGRESS

I did check the tasks of subworkflow W1 and some tasks are stuck in SCHEDULED state and some are completed but next task is not getting scheduled

So,
What could be the issue?
And will it help to add retry and timeout configuration for Task T1 of W2 workflow? say it should complete in 5 mins and if not retry 3 times
So this way we can say even if it's not getting scheduled, we will force the task to be retried

got multiple logs at server
`[WARN ] 2020-11-09 12:22:04,197 RedisDynoQueue - Cannot get the message payload 0160d380-a73a-4eeb-b022-0d058638f8fd`

and also,
`2020-11-09 17:07:44,066 RedisDynoQueue - cannot add 5aa38f20-60c6-4f34-9e6a-0e6a84169e55 to the unack shard conductor_queues.test.UNACK._deciderQueue.a stream:stdout`

Where 0160d380-a73a-4eeb-b022-0d058638f8fd AND 5aa38f20-60c6-4f34-9e6a-0e6a84169e55 are the task T1 id of W2

**Comment by AnnsPhilip** [comment]
@nsargar Is it similar to issue: https://github.com/Netflix/conductor/issues/1955

**Comment by nsargar** [comment]
Issue is with Tasks are not being picked for execution or not being updated.

@AnnsPhilip In your case subworkflow completes and parent workflow stucks, in my case it's opposite. Please confirm

**Comment by AnnsPhilip** [comment]
@nsargar Are you using worker? what is the thread count while registering task?

**Comment by nsargar** [comment]
got the logs at server 
[WARN ] 2020-11-09 12:22:04,197 RedisDynoQueue - Cannot get the message payload 0160d380-a73a-4eeb-b022-0d058638f8fd
Where 0160d380-a73a-4eeb-b022-0d058638f8fd is the task T1 id of W2

**Comment by nsargar** [comment]
> @nsargar Are you using worker? what is the thread count while registering task?

Yes 100 thread count, for 24 workers

**Comment by AnnsPhilip** [comment]
If TPS is more try increasing the threadCount. Also you can add retryCount and retryDelay while registering worker.

**Comment by nsargar** [comment]
@kishorebanala Can you please check the description

**Comment by kishorebanala** [comment]
@nsargar Having retries and timeouts on subworflow task helps, but do note that it will create a new workflow on each retry. I'd also check why the task in subworkflow is being stuck in scheduled state for a long time before doing that. It it highly likely the task message is stuck in inconsistent state in the queue, and avoiding those in queuing service would also avoid tasks being stuck in scheduled state.

**Comment by nilesh-sargar-tavisca** [comment]
Thanks @kishorebanala , any pointers where I can check task in subworkflow stuck in inconsistent state, any particular log or part of code you can point out so I can check the logs around it? I am not that much familiar with Conductor codebase, but your pointer may help me start with. Thanks again

**Comment by kishorebanala** [comment]
@nilesh-sargar-tavisca This would be a good start: https://netflix.github.io/conductor/faq/#my-workflow-is-running-and-the-task-is-scheduled-but-it-is-not-being-processed.

You could also check the task message in relevant queue directly to see the status of the message, and if there's any polling activity.
