### ISSUE TITLE
Cannot get cyrillic text from inputData

### ISSUE THREAD

**Issue by luffy1727** [Netflix/conductor#1965]
```
{
    "name": "some_workflowName",
    "version": 1,
    "input": {
        "push":{
            "subject":"C**n**s**g-c ёдаааааааааааааааааа",
            "body":{
                "amount":100000,
            },
            "categoryKey":"transaction",
            "categoryType":"income"
        }
    }
}
```
So I am providing my workflow with the data above, but my python worker cannot comprehend the cyrillic text "ёдаааааааааааааааааа" and replacing it with "?".
I have already tried encoding the task input data but it is still showing as ? both in the UI and on my CLI.
Is this a python issue or a conductor issue?

**Comment by james-deee** [comment]
@luffy1727 what's your backing datastore? Mysql? Postgres? Something else?

**Comment by luffy1727** [comment]
Currently MySQL

> @luffy1727 what's your backing datastore? Mysql? Postgres? Something else?

**Comment by james-deee** [comment]
@luffy1727 I think you'll need to ensure 2 things. By default, mysql can be using something like latin-1 for its characterset.

You can change the character set of existing DBs and tables like this
```
alter database conductor character set = utf8mb4;
ALTER TABLE event_execution CONVERT TO CHARACTER SET utf8mb4;
ALTER TABLE meta_event_handler CONVERT TO CHARACTER SET utf8mb4;
......... <do all tables>
```

Also, you need to make sure that your jdbc connection has `&characterEncoding=UTF-8` as a parameter for its connection. 

This won't fix ones already in the DB, but it should fix new ones.

**Comment by luffy1727** [comment]
Thank you, it worked
