### ISSUE TITLE
Security vulnerabilities in many of Conductor dependencies

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#1966]
Just so you know, there are security vulnerabilities in many of the Conductor dependencies. Since our company blocks the download of any that have these problems, I have got to add overrides for all of these in order to allow the build to happen. Below is the block I put in all the build.gradle files. Not all overrides are required in all modules but it is easier to use one block for all of them. Some of them I can exclude because we are not running on AWS. I also have to delete all the dependencies.lock files.

```
dependencies {
	configurations.all {
		exclude group: 'amazon', module: 'aws-java-sdk'
		exclude group: 'com.thoughtworks.xstream', module: 'xstream'
		exclude group: 'io.netty', module: 'netty-resolver-dns'
		exclude group: 'com.squareup.okhttp', module: 'okhttp'
		resolutionStrategy {
	       	       force 'net.java.dev.jna:jna:+'
		       force 'com.fasterxml.jackson.core:jackson-databind:+'
	               force "com.fasterxml.jackson.core:jackson-core:+"
	               force "com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:+"
			force 'commons-beanutils:commons-beanutils:+'
			force 'commons-collections:commons-collections:+'
			force 'io.netty:netty-common:4.1.48.Final'
			force 'io.netty:netty-transport:4.1.48.Final'
			force 'io.netty:netty-codec:4.1.48.Final'
			force 'io.netty:netty-codec-http:4.1.53.Final'
			force 'io.netty:netty-codec-http2:4.1.48.Final'
			force 'xerces:xercesImpl:2.12.0'
			force 'log4j:log4j:1.2.17-atlassian-1'
			force 'org.apache.httpcomponents:httpclient-cache:+'
			force 'net.java.dev.jna:jna-platform:+'
			force 'com.amazonaws:aws-java-sdk-sqs:+'
			force "io.swagger:swagger-jaxrs:1.6.2"
		}
	}                                                                                       
}

```

**Comment by aravindanr** [comment]
We typically fix vulnerabilities pointed out by GitHub's Dependabot alerts. In this case, it seems like your company's rules are stricter or different. Since you are already running Conductor with these dependencies, it makes sense to upgrade them in the master branch so others could benefit as well. Please create a PR with these upgrades.

**Comment by rickfish** [comment]
Unfortunately our environment is much different than Netflix as we are not using AWS or other components that you use. Testing would be impossible.
