### ISSUE TITLE
change JerseyModule to extend AbstractModule

### ISSUE THREAD

**Issue by andrasfe** [Netflix/conductor#1969]
JerseyModule currently does not extend AbstractModule. As a result, we cannot replace it with GUICE to add our custom filters (e.g. an authorization filter).

**Comment by aravindanr** [comment]
If you trace the hierarchy, `JerseyModule` does extend from `AbstractModule`. JerseyModule -> JerseyServletModule -> ServletModule -> AbstractModule.
