### ISSUE TITLE
Use workflow.createTime

### ISSUE THREAD

**Issue by leynae** [Netflix/conductor#1971]
Hi,
I need to send the creation date of my instance to a REST API via HTTP task. I have the following workflow definition:

{
  "name": "test",
  "description": "test",
  "version": 1,
  "ownerEmail": "dev@xxxx.com",
  "workflowStatusListenerEnabled": true,
  "schemaVersion": 2,
  "failureWorkflow": "workflow_error",
  "inputParameters": [
    "workunitId"
  ],
  "tasks": [
    {
      "name": "setEffectiveEndDate",
      "taskReferenceName": "setEffectiveEndDate",
      "type": "HTTP",
      "inputParameters": {
        "http_request": {
          "uri": "http://infra-zuul:8080/infra-zuul/service-workunit/workunit/${workflow.input.workunitId}",
          "method": "PUT",
          "readTimeOut": 30000,
          "connectionTimeOut": 30000,
          "body": {
            "workunitId": "${workflow.input.workunitId}",
            **"effectiveEndDate": "${workflow.createTime}"**
          }
        }
      }
    }
  ]
}

But when I execute it, I have the null value instead of the createTime of workflow instance:

{
   "asyncComplete": false,
   "http_request": {
      "method": "PUT",
      "readTimeOut": 30000,
      "body": {
         **"effectiveEndDate": null,**
         "workunitId": "376397"
      },
      "uri": "http://infra-zuul:8080/infra-zuul/service-workunit/workunit/376397",
      "connectionTimeOut": 30000
   }
}

Is it possible to retrieve workflow instance parameter ? Do I have another way via conductor to have the current system date and time ?

Thanks for your help

**Comment by aravindanr** [comment]
Unfortunately, Workflow _createTime_ is not one of the fields that is available. The available fields can be found in [ParametersUtils](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/ParametersUtils.java#L79-L93). Feel free to submit a PR to introduce a new field `createTime` whose value will be `Workflow.getStartTime()`.
