### ISSUE TITLE
UI fails to render Workflows with inline subworkflow definition

### ISSUE THREAD

**Issue by kishorebanala** [Netflix/conductor#1972]
In #1651, the ability to use inline definitions for subworkflows has been introduced. However, UI tries to fetch the workflow definition for subworkflow task, ignoring the inline definition, causing the workflow to be failed to render.

Update UI logic to ignore fetching subworkflow definition, when inline definition is used.

**Comment by beatfreaker** [comment]
@kishorebanala created PR [#1989](https://github.com/Netflix/conductor/pull/1989) to fix this issue.

**Comment by peterlau** [comment]
No longer an issue with the new UI as we don't 'expand' subworkflows and inject them in their parent graph visualization any more.
