### ISSUE TITLE
conductor 2.x redis issue

### ISSUE THREAD

**Issue by gokul-intellect** [Netflix/conductor#1977]
When I try to execute a workflow, there is one specific task which keeps executing in the while loop (because it is in SCHEDULED state) for such a long period of time.
I could see the following msg in the logs:
**cannot add (my-workflow-id) to the unack shard (namespace-prefix).(stack).UNACK._deciderQueue.c**

I doubt that I'm missing some conductor 2.x specific configuration.

And also it will be really helpful if I'm provided with some documentation of conductor 2.x specific configurations

**Comment by muralicmr** [comment]
Hi @gokul-intellect - If you are not setting up conductor in HA mode, you can try if "workflow.dyno.queue.sharding.strategy=localOnly" helps.

source: https://netflix.github.io/conductor/technicaldetails/#alternative-solution-to-distributed-decide-evaluation

**Comment by aravindanr** [comment]
@gokul-intellect Please clarify if you are using the in-memory Redis implementation or connecting to an external Redis server?

**Comment by gokul-intellect** [comment]
closing this issue as it occurred because one of my custom tasks was not registered and everything works as expected after registering it
