### ISSUE TITLE
Conductor get task from previous iteration on loop when it is combined with IF

### ISSUE THREAD

**Issue by btafarelo** [Netflix/conductor#1980]
Hi.

I did a loop task quite complex, with fork, conditions, variables, etc:

![image](https://user-images.githubusercontent.com/3848106/99995887-4f72f400-2dbb-11eb-8eee-5803217c9c5c.png)

So, when the IF (CONDITION TASK) get different paths/routes amoung the iterations, the tasks from one path from a previous iteration are available to the current iteration.

It can be checked in the interface as well, as even my condition task returning false, the true path get highlighted when the condition should take the false path.

![image](https://user-images.githubusercontent.com/3848106/99996470-138c5e80-2dbc-11eb-919e-7204f870a1e0.png)

To fix it, I added a "join" task at the end of my (condition route):

```
 {
                      "name": "SET_ServiceOfferMandatoryFilter_True",
                      "taskReferenceName": "SET_ServiceOfferMandatoryFilter_True",
                      "type": "SET_VARIABLE",
                      "inputParameters": {
                        "ServiceOfferMandatoryFilter": "${ServiceOfferMandatoryFilter.output.result}"
                      }
                    }
                  ],
                  "false": [
                    {
                      "name": "SET_ServiceOfferMandatoryFilter_False",
                      "taskReferenceName": "SET_ServiceOfferMandatoryFilter_False",
                      "type": "SET_VARIABLE",
                      "inputParameters": {
                        "ServiceOfferMandatoryFilter": null
                      }
                    }

{
                "name": "ServiceOfferMandatoryJoin",
                "taskReferenceName": "ServiceOfferMandatoryJoin",
                "type": "JSON_JQ_TRANSFORM",
                "optional": true,
                "inputParameters": {
                  "mso": "${workflow.variables.ServiceOfferMandatoryFilter}",
                  "so": "${ServiceOffer.output.response}",
                  "queryExpression": ".so + if .mso != null then .mso else [] end | unique"
                }
              },
```

**Comment by aravindanr** [comment]
Please post the workflow definition in its entirety for us to analyze it. The posted snippet does not contain a `JOIN` task. If the "false" path is highlighted when it should be "true", it most likely is a user error.

**Comment by btafarelo** [comment]
`{
  "createTime": 1598614840535,
  "name": "simulation_execution_flow_promotional",
  "description": "promotional subflow",
  "version": 1,
  "schemaVersion": 2,
  "restartable": true,
  "workflowStatusListenerEnabled": false,
  "ownerEmail": "btafarelo@gmail.com",
  "timeoutPolicy": "ALERT_ONLY",
  "timeoutSeconds": 0,
  "tasks": [
    {
      "name": "SimulationParameters",
      "taskReferenceName": "SimulationParameters",
      "type": "JSON_JQ_TRANSFORM",
      "optional": true,
      "inputParameters": {
        "sp": "${workflow.input.SimulationManager}",
        "st": "${workflow.input.simulationType}",
        "queryExpression": ".st as $st | .sp? | select(.simulationType == $st) | {(.simulationType): .}"
      }
    },
    {
      "name": "Should_Not_Run_debug",
      "taskReferenceName": "Should_Not_Run_debug",
      "type": "LAMBDA",
      "inputParameters": {
        "ispst": "${workflow.input.req.simulationParameters[0].simulationType}",
        "isp": "${workflow.input.req.simulationParameters}",
        "st": "${workflow.input.simulationType}",
        "sp": "${workflow.input.SimulationManager}",
        "scriptExpression": "return ($.ispst == $.st || $.ispst == null || $.isp == null) && $.sp != null"
      }
    },
    {
      "name": "Should_Not_Run",
      "taskReferenceName": "Should_Not_Run",
      "inputParameters": {
        "ispst": "${workflow.input.req.simulationParameters[0].simulationType}",
        "isp": "${workflow.input.req.simulationParameters}",
        "st": "${workflow.input.simulationType}",
        "sp": "${workflow.input.SimulationManager}"
      },
      "type": "DECISION",
      "caseExpression": "($.ispst == $.st || $.ispst == null || $.isp == null) && $.sp != null",
      "decisionCases": {
        "false": [
          {
            "name": "Terminate",
            "taskReferenceName": "Terminate",
            "type": "TERMINATE",
            "startDelay": 0,
            "optional": false,
            "inputParameters": {
              "terminationStatus": "FAILED",
              "workflowOutput": "${workflow.input}"
            }
          }
        ]
      }
    },
    {
      "name": "Periods",
      "taskReferenceName": "Periods",
      "type": "LAMBDA",
      "inputParameters": {
        "scriptExpression": "var n = new Date(); var t = new Date(); t.setDate(t.getDate() +1); return {\"initial\": n.toISOString().substring(0,10), \"final\": t.toISOString().substring(0,10)}"
      }
    },
    {
      "name": "FORK_OFFERS",
      "taskReferenceName": "FORK_OFFERS",
      "type": "FORK_JOIN",
      "forkTasks": [
        [
          {
            "name": "ServiceOffer",
            "taskReferenceName": "ServiceOffer",
            "type": "SUB_WORKFLOW",
            "optional": true,
            "subWorkflowParam": {
              "name": "simulation_execution_service_offer"
            },
            "inputParameters": {
              "req": "${workflow.input.req}",
              "DealershipProducts": "${workflow.input.DealershipProducts}",
              "periods": "${Periods.output.result}",
              "VehicleManager": "${workflow.input.VehicleManager}"
            }
          }
        ],
        [
          {
            "name": "InsuranceOffer",
            "taskReferenceName": "InsuranceOffer",
            "type": "SUB_WORKFLOW",
            "optional": true,
            "subWorkflowParam": {
              "name": "simulation_execution_insurance_offer"
            },
            "inputParameters": {
              "req": "${workflow.input.req}",
              "DealershipProducts": "${workflow.input.DealershipProducts}",
              "periods": "${Periods.output.result}",
              "ProductManager": "${workflow.input.ProductManager}"
            }
          }
        ]
      ]
    },
    {
      "name": "JOIN_OFFERS",
      "taskReferenceName": "JOIN_OFFERS",
      "type": "JOIN",
      "joinOn": [
        "ServiceOffer",
        "InsuranceOffer"
      ]
    },
    {
      "name": "financingProdutoApplied",
      "taskReferenceName": "financingProdutoApplied",
      "type": "JSON_JQ_TRANSFORM",
      "inputParameters": {
        "input": "${workflow.input.req.simulationParameters[0].financingProduct}",
        "sm": "${workflow.input.SimulationManager.FinancingProduct}",
        "pm": "${workflow.input.ProductManager}",
        "queryExpression": ".sm as $sm | .input as $input | [.pm[] | select(.description == $input)] | if . | length == 0 then $sm else .[0].productId end"
      }
    },
    {
      "name": "FinancingOffer",
      "taskReferenceName": "FinancingOffer",
      "type": "SUB_WORKFLOW",
      "subWorkflowParam": {
        "name": "simulation_execution_financing_offer"
      },
      "inputParameters": {
        "req": "${workflow.input.req}",
        "VehicleManager": "${workflow.input.VehicleManager}",
        "financingProdutoApplied": "${financingProdutoApplied.output.result}",
        "OfferType": "Campanha",
        "periods": "${Periods.output.result}"
      }
    },
    
    {
      "name": "LoopTask",
      "taskReferenceName": "LoopTask",
      "type": "DO_WHILE",
      "startDelay": 0,
      "optional": false,
      "inputParameters": {
        "value": "${FinancingOffer.output.result}"
      },
      "loopCondition": "$.LoopTask['iteration'] < $.value.length",
      "loopOver": [
        {
          "name": "Count",
          "taskReferenceName": "Count",
          "type": "LAMBDA",
          "inputParameters": {
            "count": "${workflow.variables.count}",
            "scriptExpression": "return $.count == null ? 0 : $.count + 1;"
          }
        },
        {
          "name": "SET_COUNT",
          "taskReferenceName": "SET_COUNT",
          "type": "SET_VARIABLE",
          "inputParameters": {
            "count": "${Count.output.result}"
          }
        },
        {
          "name": "FinancingOfferResult",
          "taskReferenceName": "FinancingOfferResult",
          "type": "LAMBDA",
          "inputParameters": {
            "count": "${workflow.variables.count}",
            "fo": "${FinancingOffer.output.result}",
            "scriptExpression": "return $.fo[$.count]"
          }
        },
        {
          "name": "FORK_VARS",
          "taskReferenceName": "FORK_VARS",
          "type": "FORK_JOIN",
          "forkTasks": [
            [
              {
                "name": "Terms",
                "taskReferenceName": "Terms",
                "type": "HTTP",
                "inputParameters": {
                  "http_request": {
                    "uri": "${workflow.input.req.url.financing-offer-product}/product/financing-offer/v1/financing-offers/${FinancingOfferResult.output.result.offerId}/terms?personType=${workflow.input.req.customer.personType}",
                    "method": "GET",
                    "connectionTimeOut": "${workflow.input.req.connectionTimeOut}",
                    "readTimeOut": "${workflow.input.req.readTimeOut}",
                    "headers": "${workflow.input.req.headers}"
                  }
                }
              },
              {
                "name": "TermApplied",
                "taskReferenceName": "TermApplied",
                "type": "LAMBDA",
                "inputParameters": {
                  "terms": "${Terms.output.response.body}",
                  "term": "${workflow.input.req.simulationParameters[0].term}",
                  "defaultTerm": "${FinancingOffer.output.result[0].defaultTerm}",
                  "maxTerm": "${FinancingOffer.output.result[0].maxTerm}",
                  "minTerm": "${FinancingOffer.output.result[0].minTerm}",
                  "scriptExpression": "for(i=0;$.terms != null && i<$.terms.length;i++) if ($.term == $.terms[i] && $.term >= $.minTerm && $.term <= $.maxTerm) return $.term; return $.defaultTerm != null ? $.defaultTerm : $.maxTerm;"
                }
              }
            ],
            [
              {
                "name": "Delays",
                "taskReferenceName": "Delays",
                "type": "HTTP",
                "inputParameters": {
                  "http_request": {
                    "uri": "${workflow.input.req.url.financing-offer-product}/product/financing-offer/v1/financing-offers/${FinancingOfferResult.output.result.offerId}/delays?personType=${workflow.input.req.customer.personType}",
                    "method": "GET",
                    "connectionTimeOut": "${workflow.input.req.connectionTimeOut}",
                    "readTimeOut": "${workflow.input.req.readTimeOut}",
                    "headers": "${workflow.input.req.headers}"
                  }
                }
              },
              {
                "name": "DelayApplied",
                "taskReferenceName": "DelayApplied",
                "type": "LAMBDA",
                "inputParameters": {
                  "id": "${workflow.input.req.simulationParameters[0].delay}",
                  "sd": "${workflow.input.SimulationManager.Delay}",
                  "exclusive": "${FinancingOffer.output.result[0].delayDefaultExclusive}",
                  "default": "${FinancingOffer.output.result[0].delayDefault}",
                  "list": "${Delays.output.response.body}",
                  "scriptExpression": "var result = $.exclusive ? $.default : $.id != null ? $.id : $.sd != null ? $.sd : 30; for(i=0; i<$.list.length; i++) if ($.list[i] == result) return result; return $.default != null ? $.default : 30;"
                }
              }
            ],
            [
              {
                "name": "Commissions",
                "taskReferenceName": "Commissions",
                "type": "HTTP",
                "inputParameters": {
                  "http_request": {
                    "uri": "${workflow.input.req.url.financing-offer-product}/product/financing-offer/v1/financing-offers/${FinancingOfferResult.output.result.offerId}/commissions?personType=${workflow.input.req.customer.personType}",
                    "method": "GET",
                    "connectionTimeOut": "${workflow.input.req.connectionTimeOut}",
                    "readTimeOut": "${workflow.input.req.readTimeOut}",
                    "headers": "${workflow.input.req.headers}"
                  }
                }
              },
              {
                "name": "CommissionApplied",
                "taskReferenceName": "CommissionApplied",
                "type": "LAMBDA",
                "inputParameters": {
                  "rc": "${workflow.input.req.simulationParameters[0].commission}",
                  "dc": "${FinancingOffer.output.result[0].defaultCommission}",
                  "sc": "${workflow.input.SimulationManager.Commission}",
                  "list": "${Commissions.output.response.body}",
                  "scriptExpression": "var r=0; for(i=0; i<$.list.length; i++) { r = Number($.list[i]) > Number(r) ? $.list[i] : r;} for(i=0; $.rc!=null && i<$.list.length; i++) if ($.list[i] == $.rc) return $.rc; return $.sc != null ? $.sc : $.dc != null ? $.dc : r;"
                }
              }
            ],
            [
              {
                "name": "Has_Mandatory_ServiceOffers",
                "taskReferenceName": "Has_Mandatory_ServiceOffers",
                "inputParameters": {
                  "mandatoryServiceOffers": "${FinancingOfferResult.output.result.mandatoryServiceOffers}"
                },
                "type": "DECISION",
                "caseExpression": "$.mandatoryServiceOffers.length > 0",
                "decisionCases": {
                  "true": [
                    {
                      "name": "ServiceOfferList",
                      "taskReferenceName": "ServiceOfferList",
                      "type": "JSON_JQ_TRANSFORM",
                      "optional": true,
                      "inputParameters": {
                        "mandatoryServiceOffers": "${FinancingOfferResult.output.result.mandatoryServiceOffers}",
                        "queryExpression": ".mandatoryServiceOffers | @csv"
                      }
                    },
                    {
                      "name": "ServiceOfferMandatory",
                      "taskReferenceName": "ServiceOfferMandatory",
                      "type": "HTTP",
                      "optional": true,
                      "inputParameters": {
                        "http_request": {
                          "uri": "${workflow.input.req.url.service-offer-product}/product/service-offer/v1/service-offers?offerIdList=${ServiceOfferList.output.result}",
                          "method": "GET",
                          "connectionTimeOut": "${workflow.input.req.connectionTimeOut}",
                          "readTimeOut": "${workflow.input.req.readTimeOut}",
                          "headers": "${workflow.input.req.headers}"
                        }
                      }
                    },
                    {
                      "name": "ServiceOfferMandatoryFilter",
                      "taskReferenceName": "ServiceOfferMandatoryFilter",
                      "type": "JSON_JQ_TRANSFORM",
                      "optional": true,
                      "inputParameters": {
                        "mso": "${ServiceOfferMandatory.output.response.body}",
                        "queryExpression": "[.mso[] | {\"offerId\": .offerId, \"description\": .description, \"amount\": .prices[0].amount, \"required\": true, \"applied\": true}]"
                      }
                    },
                    {
                      "name": "SET_ServiceOfferMandatoryFilter_True",
                      "taskReferenceName": "SET_ServiceOfferMandatoryFilter_True",
                      "type": "SET_VARIABLE",
                      "inputParameters": {
                        "ServiceOfferMandatoryFilter": "${ServiceOfferMandatoryFilter.output.result}"
                      }
                    }
                  ],
                  "false": [
                    {
                      "name": "SET_ServiceOfferMandatoryFilter_False",
                      "taskReferenceName": "SET_ServiceOfferMandatoryFilter_False",
                      "type": "SET_VARIABLE",
                      "inputParameters": {
                        "ServiceOfferMandatoryFilter": null
                      }
                    }
                  ]
                }
              },
              {
                "name": "ServiceOfferMandatoryJoin",
                "taskReferenceName": "ServiceOfferMandatoryJoin",
                "type": "JSON_JQ_TRANSFORM",
                "optional": true,
                "inputParameters": {
                  "mso": "${workflow.variables.ServiceOfferMandatoryFilter}",
                  "so": "${ServiceOffer.output.response}",
                  "queryExpression": ".so + if .mso != null then .mso else [] end | unique"
                }
              },
              {
                "name": "ServiceOfferSum",
                "taskReferenceName": "ServiceOfferSum",
                "type": "LAMBDA",
                "optional": true,
                "inputParameters": {
                  "so": "${ServiceOfferMandatoryJoin.output.result}",
                  "scriptExpression": "var sum=0; for(i=0;$.so!=null && i<$.so.length;i++) if($.so[i].applied) sum += $.so[i].amount; return sum;"
                }
              }
            ],
            [
              {
                "name": "Has_Mandatory_InsuranceOffers",
                "taskReferenceName": "Has_Mandatory_InsuranceOffers",
                "inputParameters": {
                  "mandatoryInsuranceOffers": "${FinancingOfferResult.output.result.mandatoryInsuranceOffers}"
                },
                "type": "DECISION",
                "caseExpression": "$.mandatoryInsuranceOffers != null && $.mandatoryInsuranceOffers.length > 0",
                "decisionCases": {
                  "true": [
                    {
                      "name": "InsuranceOfferList",
                      "taskReferenceName": "InsuranceOfferList",
                      "type": "JSON_JQ_TRANSFORM",
                      "optional": true,
                      "inputParameters": {
                        "mandatoryInsuranceOffers": "${FinancingOfferResult.output.result.mandatoryInsuranceOffers}",
                        "queryExpression": ".mandatoryInsuranceOffers | @csv"
                      }
                    },
                    {
                      "name": "InsuranceOfferMandatory",
                      "taskReferenceName": "InsuranceOfferMandatory",
                      "type": "HTTP",
                      "optional": true,
                      "inputParameters": {
                        "http_request": {
                          "uri": "${workflow.input.req.url.service-offer-product}/product/insurance-offer/v1/insurance-offers?offerIdList=${InsuranceOfferList.output.result}",
                          "method": "GET",
                          "connectionTimeOut": "${workflow.input.req.connectionTimeOut}",
                          "readTimeOut": "${workflow.input.req.readTimeOut}",
                          "headers": "${workflow.input.req.headers}"
                        }
                      }
                    },
                    {
                      "name": "InsuranceOfferMandatoryFilter",
                      "taskReferenceName": "InsuranceOfferMandatoryFilter",
                      "type": "JSON_JQ_TRANSFORM",
                      "optional": true,
                      "inputParameters": {
                        "mio": "${InsuranceOfferMandatory.output.response.body}",
                        "queryExpression": "[.mio[] | {\"offerId\": .offerId, \"description\": .description, \"amount\": .prices[0].amount, \"required\": true, \"applied\": true}]"
                      }
                    },
                    {
                      "name": "SET_InsuranceOfferMandatoryFilter_True",
                      "taskReferenceName": "SET_InsuranceOfferMandatoryFilter_True",
                      "type": "SET_VARIABLE",
                      "inputParameters": {
                        "InsuranceOfferMandatoryFilter": "${InsuranceOfferMandatoryFilter.output.result}"
                      }
                    }
                  ],
                  "false": [
                    {
                      "name": "SET_InsuranceOfferMandatoryFilter_False",
                      "taskReferenceName": "SET_InsuranceOfferMandatoryFilter_False",
                      "type": "SET_VARIABLE",
                      "inputParameters": {
                        "InsuranceOfferMandatoryFilter": null
                      }
                    }
                  ]
                }
              },
              {
                "name": "InsuranceOfferMandatoryJoin",
                "taskReferenceName": "InsuranceOfferMandatoryJoin",
                "type": "JSON_JQ_TRANSFORM",
                "optional": true,
                "inputParameters": {
                  "mio": "${workflow.variables.InsuranceOfferMandatoryFilter}",
                  "io": "${InsuranceOffer.output.response}",
                  "queryExpression": ".io + if .mio != null then .mio else [] end | unique"
                }
              },
              {
                "name": "InsuranceOfferSum",
                "taskReferenceName": "InsuranceOfferSum",
                "type": "LAMBDA",
                "optional": true,
                "inputParameters": {
                  "io": "${InsuranceOfferMandatoryJoin.output.result}",
                  "scriptExpression": "var sum=0; for(i=0;$.io!=null && i<$.io.length;i++) if($.io[i].applied && !$.io[i].description.contains('SPF')) sum += $.io[i].amount; return sum;"
                }
              }
            ]
          ]
        },
        {
          "name": "JOIN_VARS",
          "taskReferenceName": "JOIN_VARS",
          "type": "JOIN",
          "joinOn": [
            "TermApplied",
            "DelayApplied",
            "CommissionApplied",
            "ServiceOfferSum",
            "InsuranceOfferSum"
          ]
        },
        {
          "name": "CalcInputPercent",
          "taskReferenceName": "CalcInputPercent",
          "type": "LAMBDA",
          "inputParameters": {
            "rip": "${workflow.input.req.simulationParameters[0].inputPercent}",
            "ria": "${workflow.input.req.simulationParameters[0].inputAmount}",
            "vv": "${workflow.input.req.vehicleValue}",
            "sumSO": "${ServiceOfferSum.output.result}",
            "sumIO": "${InsuranceOfferSum.output.result}",
            "scriptExpression": "return $.rip != null ? $.rip : $.ria == null ? null : $.ria / (Number($.vv) + $.sumSO + $.sumIO);"
          }
        },
        {
          "name": "InputPercentApplied",
          "taskReferenceName": "InputPercentApplied",
          "type": "LAMBDA",
          "inputParameters": {
            "ip": "${CalcInputPercent.output.result}",
            "sip": "${workflow.input.SimulationManager.InputPercent}",
            "dip": "${FinancingOfferResult.output.result.defaultInputPercent}",
            "min": "${FinancingOfferResult.output.result.minInputPercent}",
            "max": "${FinancingOfferResult.output.result.maxInputPercent}",
            "caMin": "${workflow.input.CreditAnalysis.RangeDefault.minInputPercent}",
            "scriptExpression": "return $.ip != null && ($.ip >= $.min && $.ip <= $.max) ? Number($.ip) : $.caMin != null && ($.caMin >= $.min && $.caMin <= $.max) ? Number($.caMin) : $.sip != null && ($.sip >= $.min && $.sip <= $.max) ? Number($.sip) : $.dip != null && $.dip != '' ? Number($.dip) : Number($.min)"
          }
        },
        {
          "name": "InputAmountApplied",
          "taskReferenceName": "InputAmountApplied",
          "type": "LAMBDA",
          "inputParameters": {
            "vv": "${workflow.input.req.vehicleValue}",
            "ip": "${InputPercentApplied.output.result}",
            "sumSO": "${ServiceOfferSum.output.result}",
            "sumIO": "${InsuranceOfferSum.output.result}",
            "scriptExpression": "return ((Number($.vv) + Number($.sumSO) + Number($.sumIO)) * $.ip).toFixed(2);"
          }
        },
        {
          "name": "FinancedValueApplied",
          "taskReferenceName": "FinancedValueApplied",
          "type": "LAMBDA",
          "inputParameters": {
            "vv": "${workflow.input.req.vehicleValue}",
            "iap": "${InputAmountApplied.output.result}",
            "sumSO": "${ServiceOfferSum.output.result}",
            "sumIO": "${InsuranceOfferSum.output.result}",
            "sumTX": "${workflow.input.TaxManager.sum}",
            "scriptExpression": "return ((Number($.vv) + Number($.sumSO) + Number($.sumIO) + Number($.sumTX)) - $.iap).toFixed(2);"
          }
        },
        {
          "name": "Is_CDC_Flex",
          "taskReferenceName": "Is_CDC_Flex",
          "inputParameters": {
            "description": "${FinancingOfferResult.output.result.product.description}"
          },
          "type": "DECISION",
          "caseExpression": "$.description == 'CDC Flex'",
          "decisionCases": {
            "true": [
              {
                "name": "FinancingOfferRepackage",
                "taskReferenceName": "FinancingOfferRepackage",
                "type": "HTTP",
                "optional": "false",
                "inputParameters": {
                  "http_request": {
                    "uri": "${workflow.input.req.url.financing-offer-product}/product/financing-offer/v1/repackages/${FinancingOfferResult.output.result.repackages[0]}",
                    "method": "GET",
                    "connectionTimeOut": "${workflow.input.req.connectionTimeOut}",
                    "readTimeOut": "${workflow.input.req.readTimeOut}",
                    "headers": "${workflow.input.req.headers}"
                  }
                }
              },
              {
                "name": "RepackageResult",
                "taskReferenceName": "RepackageResult",
                "type": "JSON_JQ_TRANSFORM",
                "inputParameters": {
                  "repkg": "${FinancingOfferRepackage.output.response.body}",
                  "queryExpression": ".repkg | [{\"repackageId\": .repackageId, \"duration\": .duration, \"bankPartnerCode\": .bankPartnerCode, \"applied\": true}]"
                }
              },
              {
                "name": "RepackagePlans",
                "taskReferenceName": "RepackagePlans",
                "type": "JSON_JQ_TRANSFORM",
                "inputParameters": {
                  "repkg": "${FinancingOfferRepackage.output.response.body.repackagePlans}",
                  "queryExpression": "[.repkg |= sort_by(.installment) | .repkg[].factor]"
                }
              }
            ]
          }
        },
        {
          "name": "IsFinancedValueAppliedValid",
          "taskReferenceName": "IsFinancedValueAppliedValid",
          "type": "LAMBDA",
          "inputParameters": {
            "FinancedValueApplied": "${FinancedValueApplied.output.result}",
            "minFinancedAmount": "${FinancingOfferResult.output.result.minFinancedAmount}",
            "scriptExpression": "return $.FinancedValueApplied >= $.minFinancedAmount"
          }
        },
        {
          "name": "FinancingOfferCoefficients",
          "taskReferenceName": "FinancingOfferCoefficients",
          "type": "HTTP",
          "optional": "true",
          "inputParameters": {
            "http_request": {
              "uri": "${workflow.input.req.url.financing-offer-product}/product/financing-offer/v1/financing-offers/${FinancingOfferResult.output.result.offerId}/coefficients?personType=${workflow.input.req.customer.personType}&term=${TermApplied.output.result}&delayValue=${DelayApplied.output.result}&commission=${CommissionApplied.output.result}",
              "method": "GET",
              "connectionTimeOut": "${workflow.input.req.connectionTimeOut}",
              "readTimeOut": "${workflow.input.req.readTimeOut}",
              "headers": "${workflow.input.req.headers}"
            }
          }
        },
        {
          "name": "CoefficientApplied",
          "taskReferenceName": "CoefficientApplied",
          "type": "JSON_JQ_TRANSFORM",
          "inputParameters": {
            "c": "${FinancingOfferCoefficients.output.response.body}",
            "i": "${InputPercentApplied.output.result}",
            "queryExpression": ".i as $i | .c |= (sort_by(.inputPercent) | reverse) | [.c[] | select($i >= .inputPercent)] | if . | length > 0 then .[0] else null end"
          }
        },
        {
          "name": "Installment",
          "taskReferenceName": "Installment",
          "type": "LAMBDA",
          "inputParameters": {
            "FinancedValueApplied": "${FinancedValueApplied.output.result}",
            "c": "${CoefficientApplied.output.result.coefficient}",
            "spf": "${InsuranceOffer.output.spf}",
            "ioa": "${InsuranceOffer.output.applied}",
            "rio": "${workflow.input.req.simulationParameters[0].insuranceOffers}",
            "scriptExpression": "var wSPF=$.rio==null; for(i=0;$.rio!=null && $.ioa!=null && i<$.ioa.length;i++) if ($.ioa[i].description == 'SPF (Seguro Proteção Financeira)') {wSPF=true;break;} var v = $.FinancedValueApplied * $.c; return ($.spf != null && wSPF ? ($.spf / 100) * v : 0) + v;"
          }
        },
        {
          "name": "Installments",
          "taskReferenceName": "Installments",
          "type": "LAMBDA",
          "inputParameters": {
            "term": "${TermApplied.output.result}",
            "delay": "${DelayApplied.output.result}",
            "value": "${Installment.output.result}",
            "rpkg": "${RepackagePlans.output.result}",
            "scriptExpression": "var n=new Date(); var f = new Date(n.getFullYear(), n.getMonth()+1, n.getDate()); if (f.getMonth() - n.getMonth() >= 2) n = new Date(n.getFullYear(), n.getMonth()+1); n.setMonth(n.getMonth() + 1); n.setDate(n.getDate() + ($.delay - 30)); var r=new Array(); for(i=1;i<=$.term;i++) {r.push({\"number\": i,\"amount\": $.value * ($.rpkg != null ? $.rpkg[i-1] : 1),\"dueDate\": n.toISOString().substring(0,10)}); n.setMonth(n.getMonth() + 1)} return r;"
          }
        },
        {
          "name": "Rate",
          "taskReferenceName": "Rate",
          "type": "LAMBDA",
          "inputParameters": {
            "tax": "${CoefficientApplied.output.result.taxCoefficient}",
            "scriptExpression": "return {'monthlyInterestRate': $.tax, 'annualInterestRate': ($.tax * 12)};"
          }
        },
        {
          "name": "FinancingOfferJson",
          "taskReferenceName": "FinancingOfferJson",
          "type": "JSON_JQ_TRANSFORM",
          "inputParameters": {
            "fo": "${FinancingOfferResult.output}",
            "io": "${InsuranceOfferMandatoryJoin.output.result}",
            "so": "${ServiceOfferMandatoryJoin.output.result}",
            "taxes": "${workflow.input.TaxManager.result}",
            "terms": "${Terms.output.response.body}",
            "delays": "${Delays.output.response.body}",
            "commissions": "${Commissions.output.response.body}",
            "delayApplied": "${DelayApplied.output.result}",
            "termApplied": "${TermApplied.output.result}",
            "commissionApplied": "${CommissionApplied.output.result}",
            "coefficient": "${CoefficientApplied.output.result.coefficient}",
            "InputAmountApplied": "${InputAmountApplied.output.result}",
            "InputPercentApplied": "${InputPercentApplied.output.result}",
            "financedAmountApplied": "${FinancedValueApplied.output.result}",
            "remunerations": "${workflow.input.Remuneration.remunerations}",
            "remunerationApplied": "${workflow.input.Remuneration.remunerationApplied}",
            "rate": "${Rate.output.result}",
            "installments": "${Installments.output.result}",
            "Repackage": "${RepackageResult.output.result}",
            "queryExpression": "[{\"offerId\": .fo.result.offerId,\"description\": .fo.result.description,\"repackages\": .Repackage,\"product\": .fo.result.product,\"coefficient\": .coefficient,\"couponCodeApplied\": null,\"inputAmountApplied\": .InputAmountApplied,\"inputPercentApplied\": .InputPercentApplied,\"maxInputPercent\": .fo.result.maxInputPercent,\"minInputPercent\": .fo.result.minInputPercent,\"financedAmountApplied\": .financedAmountApplied,\"maxFinancedAmountPercent\": .fo.result.maxFinancedPercent,\"minFinancedAmountPercent\": .fo.result.minFinancedPercent,\"delays\": .delays,\"delayApplied\": .delayApplied,\"terms\": .terms,\"termApplied\": .termApplied,\"commissions\": .commissions,\"commissionApplied\": .commissionApplied,\"remunerations\": .remunerations,\"remunerationApplied\": .remunerationApplied,\"taxesApplied\": (.taxes),\"paymentPlan\": {\"monthlyInterestRate\": .rate.monthlyInterestRate,  \"annualInterestRate\": .rate.annualInterestRate,  \"installments\": (.installments | map(.))},\"serviceOffers\": .so,\"insuranceOffers\": .io,\"offerPackages\": null,\"links\": null}]"
          }
        }
      ]
    },
    {
      "name": "FORK_THIS_IS_THE_END",
      "taskReferenceName": "FORK_THIS_IS_THE_END",
      "type": "FORK_JOIN",
      "forkTasks": [
        [
          {
            "name": "SimulationPosition",
            "taskReferenceName": "SimulationPosition",
            "type": "JSON_JQ_TRANSFORM",
            "inputParameters": {
              "st": "${workflow.input.simulationType}",
              "sm": "${workflow.input.SimulationManager}",
              "queryExpression": "if .sm | type == \"array\" then .sm[0].simulationPosition else .sm.simulationPosition end"
            }
          },
          {
            "name": "FinancingOffersResponse",
            "taskReferenceName": "FinancingOffersResponse",
            "type": "JSON_JQ_TRANSFORM",
            "inputParameters": {
              "LoopTaskOutput": "${LoopTask.output}",
              "queryExpression": "[.LoopTaskOutput | map(.)[] | select(type == \"object\" and .IsFinancedValueAppliedValid.result == true)] | .[].FinancingOfferJson.result[0]"
            }
          }
        ]
      ]
    },
    {
      "name": "JOIN_THIS_IS_THE_END",
      "taskReferenceName": "JOIN_THIS_IS_THE_END",
      "type": "JOIN",
      "joinOn": [
        "FinancingOffersResponse"
      ]
    },
    {
      "name": "RootJson",
      "taskReferenceName": "RootJson",
      "type": "JSON_JQ_TRANSFORM",
      "inputParameters": {
        "st": "${workflow.input.simulationType}",
        "fos": "${FinancingOffersResponse.output.resultList}",
        "req": "${workflow.input.req}",
        "p": "${Periods.output.result}",
        "rfe": "${workflow.input.TaxManager.rfe}",
        "wfid": "${workflow.workflowId}",
        "pos": "${workflow.input.SimulationManager.simulationPosition}",
        "queryExpression": "{\"simulationId\": .wfid,\"simulationType\": .st,\"exibitionOrder\": .pos,\"initialPeriod\": .p.initial,\"finalPeriod\": .p.final,\"financingBrand\": .req.financingBrand,\"saleType\": .req.saleType, \"customer\": { \"personType\": .req.customer.personType, \"cpfCnpj\": .req.customer.cpfCnpj, \"name\": .req.customer.name, \"postalCode\": .req.customer.postalCode, \"guarantor\": .req.customer.guarantor},\"registrationFeeExemption\": .rfe,\"vehicleVersionId\": .req.vehicleVersionId,\"vehicleValue\": .req.vehicleValue,\"specialVehicleType\": .req.specialVehicleType,\"dealershipId\": .req.dealershipId,\"financingOffers\": .fos}"
      }
    }
  ]
}`
