### ISSUE TITLE
Question: Starting a workflow at a specific task

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#199]
Hello,

I have a workflow with a sequence of tasks - e.g. Task A => Task B => Task C => Task D

Is there any possiblity to start the workflow at a certain task - e.g. Task C, which means skipping Task A and Task B?

This would mean within the input to the workflow, a configuration something like "start at taskReferenceName == Task C"?

Thanks for your help.

**Comment by v1r3n** [comment]
@blueelephants there is no feature that allows skipping few tasks and start the workflow at a specific task.  

Maybe a decision task as the first task might be useful if task A & B needs to be skipped for certain conditions.

**Comment by blueelephants** [comment]
Alright - thanks for clarification
