### ISSUE TITLE
ES and Redis data migration scripts from v1 to v2

### ISSUE THREAD

**Issue by hiren-intellectdesign** [Netflix/conductor#1990]
Does Conductor provide any migration scripts for moving from v1.x to v2.x ?

Conductor v1 has already been running in our environments since long time and has created huge dataset in Redis and Elasticsearch over a period. Now, if we have to migrate to newer Conductor version (v2.x), then where can we find information/scripts about data migration to be followed? Are there any breaking change in the data structure? Any specific dataset to be modified during migration etc..etc..

**Comment by aravindanr** [comment]
There are no changes in the data structures that Redis uses. However support for ES2 was dropped in 2.x. Unfortunately, we don't provide any migration scripts. A list of changes in 2.x can be found in this [blog post](https://netflixtechblog.com/evolution-of-netflix-conductor-16600be36bca).
