### ISSUE TITLE
Conductor metrics using Prometheus

### ISSUE THREAD

**Issue by pchowdad** [Netflix/conductor#1991]
We're looking to monitor the performance of conductor servers and workers in our production environment. The documentation lists some of the metrics that are published from the servers and workers. We did check the https://netflix.github.io/conductor/metrics/server/ we don't want to over load the ES so we opt out Publish or Collect metrics. We are planing to use Prometheus for metrics. I see Conductor push metrics through syslog fluentd. Can we directly integrate Prometheus to Conductor code without fluentd?

**Comment by aravindanr** [comment]
Conductor publishes its metrics through [Spectator](https://github.com/Netflix/spectator). See [Monitors.java](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/metrics/Monitors.java#L39). We don't recommend adding Prometheus directly to the Conductor project. However, there is nothing stopping you from doing a custom build of Conductor which includes Prometheus.

**NOTE:** We are in the process of migrating [Conductor to Spring Boot](https://github.com/Netflix/conductor/tree/3.0). At some point, metrics will be published through DropWizard.
