### ISSUE TITLE
WorkflowSearch shall return Workflow instead of WorkflowSummary

### ISSUE THREAD

**Issue by ravisund** [Netflix/conductor#1992]
Currently Conductor workflow search API is returning https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/run/WorkflowSummary.java  .  The WorkflowSummary is a stripped down version of https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/run/Workflow.java .

The issues is... the data types in WorkflowSummary is different than Workflow (e.g. startTime, endTime are string , input & output are string).   This will pose further complexities on the consuming systems. (e.g.) date parsing, input can't be converted back to Map<String, Object> (because input is nothing but a toString() of Map. This form of serialization can't be converted back to Map again). 

More over, WorkflowSummary is created from Workflow. what is the real need to have WorkflowSummary class ? why don't the search API returns Workflow without tasks ?

Can we have a workflow/search/v2 API to return the Workflow instead of WorkflowSummary ?

**Comment by aravindanr** [comment]
@ravisund the current search api is consumed by the UI. It does make sense to return Workflow instead of WorkflowSummary. If it's of urgent need for you, please create a pull request with a new but similar api that returns the Workflow object.

**Comment by michaelpaliy** [comment]
This API will help us also (currently we need to convert the WorkflowSummary to Workflow and it causing some overhead ).
I will start working on it and open PR later.
