### ISSUE TITLE
PostgreSQL persistence: Unable to shard 'queue_message' table using Citus

### ISSUE THREAD

**Issue by raghavendra-bhat** [Netflix/conductor#1997]
I am using PostgreSQL and trying to shard the tables using Citus extension on PostgeSQL. I have hit a road block as I am unable to shard 'queue_message' table (which I believe is the 'queue_name' column is the table that needs to be distributed in the Postgres cluster or have I erred here?). I get the below error when I try to distribute the table

postgres=# SELECT create_distributed_table('queue_message', 'queue_name');
ERROR: cannot create constraint on "queue_message"
DETAIL: Distributed relations cannot have UNIQUE, EXCLUDE, or PRIMARY KEY constraints that do not include the partition column (with an equality operator if EXCLUDE).

It appears that Citus doesn't allow sharding on column that's not part of UNQIUE or PRIMARY key constraints. This table has "id" as primary key. It would be of great help if someone can let me know if I am on the right track and how do I go about distributing data using PostgreSQL.

**Comment by kishorebanala** [comment]
Hey @mactaggart, @marosmars Is this something you can help with? Thanks!

**Comment by mactaggart** [comment]
@raghavendra-bhat I've not used Conductor with Citus, however, I suggest trying the 'id' column instead of 'queue_name' since it's the primary key. Other tables also use 'id' as the primary key, so they could be sharded by id as well. Let me know if that works.

**Comment by raghavendra-bhat** [comment]
@mactaggart Nope, using 'id' also has the same issue as it needs to be part of unique key constraints. 

_postgres=# SELECT create_distributed_table('queue_message', 'id');
ERROR:  cannot create constraint on "queue_message"
DETAIL:  Distributed relations cannot have UNIQUE, EXCLUDE, or PRIMARY KEY constraints that do not include the partition column (with an equality operator if EXCLUDE)._
