### ISSUE TITLE
Comparison with AirFlow

### ISSUE THREAD

**Issue by asafm** [Netflix/conductor#20]
Hi,

After extensive reading it seems AirFlow only lacking feature is back pressure: the ability for a micro service to poll for tasks as opposed to submitting via rest.
Other than that AirFlow seems like a superset of Conductor - am I missing something?

**Comment by v1r3n** [comment]
I have not done a detailed comparison with AirFlow, but at high level they seem similar.  One key difference I can see is that AirFlow will take your python scripts and execute them for you.  Conductor does not execute user supplied tasks, but rather leaves that to application owners to handle it.
