### ISSUE TITLE
Workflow Execution Archival - Unexpected Behavior

### ISSUE THREAD

**Issue by conductor-boot** [Netflix/conductor#2008]
Hi,

Started Conductor with 

conductor.additional.modules | com.netflix.conductor.contribs.ArchivingWorkflowModule

I created a workflow with below definition (pasted at the end of the content). 
It has **workflowStatusListenerEnabled as true**. 
I **triggered workflow execution** and before it could complete, I terminated the execution.
Then I **archived the execution**. The execution was still shown in the execution history.
I tried to **restart the workflowexecution (that was supposed to be archived) and it restarted successfully**.
I repeated the same process till archival and this time instead of restart , I did a **retry and the workflow execution got removed from execution history**.

I have attached the entire steps followed, in screenshots below, from a management UI I developed. Please refer for clear picture of what was done, if the above explanation is not detailed enough.

![image](https://user-images.githubusercontent.com/65370343/101995263-c599b500-3cee-11eb-8d60-aa54a1216be6.png)
![1](https://user-images.githubusercontent.com/65370343/101994938-4905d700-3cec-11eb-9aa3-446c73fc5970.png)
![2](https://user-images.githubusercontent.com/65370343/101994939-4c00c780-3cec-11eb-9569-9d695570deba.png)
![3](https://user-images.githubusercontent.com/65370343/101994940-4d31f480-3cec-11eb-9eaa-b2f753a81cba.png)
![4](https://user-images.githubusercontent.com/65370343/101994942-4dca8b00-3cec-11eb-85b1-a7e06c54c84b.png)
![5](https://user-images.githubusercontent.com/65370343/101994944-4efbb800-3cec-11eb-9207-c535081b7a66.png)
![6](https://user-images.githubusercontent.com/65370343/101994945-4f944e80-3cec-11eb-861e-1c34a86a0455.png)
![7](https://user-images.githubusercontent.com/65370343/101994947-502ce500-3cec-11eb-92a1-c4c0f61e84e1.png)
![8](https://user-images.githubusercontent.com/65370343/101994949-50c57b80-3cec-11eb-813d-17e0a91c4e51.png)
![9](https://user-images.githubusercontent.com/65370343/101994950-515e1200-3cec-11eb-9f9a-1ef766223d9b.png)
![10](https://user-images.githubusercontent.com/65370343/101994951-51f6a880-3cec-11eb-9b39-d47b6621ac5c.png)
![11](https://user-images.githubusercontent.com/65370343/101994952-528f3f00-3cec-11eb-9daf-5caf1cb92366.png)
![12](https://user-images.githubusercontent.com/65370343/101994953-5327d580-3cec-11eb-91ed-863bdd70c7af.png)
![13](https://user-images.githubusercontent.com/65370343/101994954-5327d580-3cec-11eb-805e-f8a511cf1084.png)
![14](https://user-images.githubusercontent.com/65370343/101994955-53c06c00-3cec-11eb-9ef1-9253e2b93f8b.png)
![15](https://user-images.githubusercontent.com/65370343/101994956-53c06c00-3cec-11eb-98b5-a371766c7d64.png)
![16](https://user-images.githubusercontent.com/65370343/101994958-54590280-3cec-11eb-83b4-a0b3243874dd.png)
![17](https://user-images.githubusercontent.com/65370343/101994959-54f19900-3cec-11eb-9c72-9f65fc451bde.png)

Question 1 : Is an archived workflow supposed to be restured in the api response (/api/workflow/search , to be exact the api with parameters is /api/workflow/search?start=0&size=10&sort=updateTime:DESC) ?

If the answer is that the workflow execution should not get listed in api response, then please verify as it seemsto be returned.
Else if it still can be listed in api response
     Question 1.1 : Is an archived workflow restartable ?
     Question 1.2 : Why does the archived workflow disappear from the view / list in api response if a retry is tried on the archived workflow ? 

Conductor Server version : 2.30.3
Database : MySQL / MariaDB
Elasticsearch : External - Version 5.X

Workflow Def JSON : 
{"ownerApp":"Fillory UI","createTime":1600724802786,"updateTime":1601999353132,"createdBy":"Fillory UI","name":"Test Dec Case Workflow","description":"Decision Case Workflow","version":1,"tasks":[{"name":"Which Name?","taskReferenceName":"Task-1","description":"string","inputParameters":{"name":"${workflow.input.name}"},"type":"DECISION","caseValueParam":"name","decisionCases":{"Mahesh":[{"name":"Test Task","taskReferenceName":"Task-2","description":"Testing Task in Workflow","inputParameters":{"name":"${workflow.input.name}"},"type":"SIMPLE","decisionCases":{},"defaultCase":[],"forkTasks":[],"startDelay":0,"joinOn":[],"optional":false,"rateLimited":false,"defaultExclusiveJoinTask":[],"asyncComplete":false,"loopOver":[]}],"Deepthi":[{"name":"Test Task","taskReferenceName":"Task-3","description":"Testing Task in Workflow","inputParameters":{"name":"${workflow.input.name}"},"type":"SIMPLE","decisionCases":{},"defaultCase":[],"forkTasks":[],"startDelay":0,"joinOn":[],"optional":false,"rateLimited":false,"defaultExclusiveJoinTask":[],"asyncComplete":false,"loopOver":[]},{"name":"Test Task","taskReferenceName":"Task-4","description":"Testing Task in Workflow","inputParameters":{"name":"${workflow.input.name}"},"type":"SIMPLE","decisionCases":{},"defaultCase":[],"forkTasks":[],"startDelay":0,"joinOn":[],"optional":false,"rateLimited":false,"defaultExclusiveJoinTask":[],"asyncComplete":false,"loopOver":[]}],"Aishani":[{"name":"Test Task","taskReferenceName":"Task-5","description":"Testing Task in Workflow","inputParameters":{"name":"${workflow.input.name}"},"type":"SIMPLE","decisionCases":{},"defaultCase":[],"forkTasks":[],"startDelay":0,"joinOn":[],"optional":false,"rateLimited":false,"defaultExclusiveJoinTask":[],"asyncComplete":false,"loopOver":[]}]},"defaultCase":[],"forkTasks":[],"startDelay":0,"joinOn":[],"optional":false,"defaultExclusiveJoinTask":[],"asyncComplete":false,"loopOver":[]},{"name":"Test Task","taskReferenceName":"Task-6","description":"Testing Task in Workflow","inputParameters":{"name":"${workflow.input.name}"},"type":"SIMPLE","decisionCases":{},"defaultCase":[],"forkTasks":[],"startDelay":0,"joinOn":[],"optional":false,"rateLimited":false,"defaultExclusiveJoinTask":[],"asyncComplete":false,"loopOver":[]}],"inputParameters":["name"],"outputParameters":{"message":"${Task-5.output.message}"},"schemaVersion":2,"restartable":true,"workflowStatusListenerEnabled":true,"ownerEmail":"abc@gmail.com","timeoutPolicy":"ALERT_ONLY","timeoutSeconds":0,"variables":{}}
![0](https://user-images.githubusercontent.com/65370343/101995256-b581d580-3cee-11eb-9e09-c3f2374cacc5.png)

**Comment by apanicker-nflx** [comment]
@conductor-boot Archiving a workflow means that it will be removed from the primary datastore and will only be available in the secondary datastore (elasticsearch). This helps keep the primary datastore datasize in check.

Since these workflows are persisted in the ES index, these workflows will be available to be returned from the search endpoints and also for restart/retry operations.

Regarding the workflow disappearing from the list upon retry, can you please verify if you are running into any errors during archival process? Also, can you check your ES index to see if the workflow has been archived (this can be verified by checking for the rawJSON field in your document)?
