### ISSUE TITLE
Retry Mechanism in SubWorkflow

### ISSUE THREAD

**Issue by mehmet-islamoglu** [Netflix/conductor#2012]
We are using a **sub workflow** in our main workflow. When this sub workflow fails **retry mechanism** restarts it from the first task of the sub workflow. 

We want to utilize **retry mechanism** in a way so that we can **start immediately from the failed task of the subworkflow** like how it would happen in a retry mechanism in the **parent** workflow.

How can we achieve this? 

Thank you very much for your help.

@v1r3n 
@apanicker-nflx 
@kishorebanala 
@jfernandez

**Comment by kishorebanala** [comment]
Copying over my response from Gitter here:

```
@mehmet-islamoglu You're right. However, you can retry the sub workflow instead, which would do what you're expecting.

We've considered doing the same for retry from parent workflow without breaking the current usage. I.e when retried from parent, with a flag to keep the existing behavior of restarting the subworkflow vs retrying it, which would recursively evaluate the subworkflow(s) until finding the last discrete task and retrying it (For eg., in a multi-level sub workflow).

It might be a while until we can prioritize this, but if you've bandwidth, please feel free to make a contribution starting with your proposal in a Github issue for the community to follow through.
```

**Comment by mehmet-islamoglu** [comment]
Thank you for the feedback @kishorebanala 

I will go ahead and create a Pull Request with my colleagues @grkn @azb96

**Comment by mehmet-islamoglu** [comment]
I created two PRs to dev and master for this issue. 

I can't re-open the issue and move the issue to backlog->TO-DO, so checks on my PRs are failing. Can you please help me with this problem?

@v1r3n
@apanicker-nflx
@kishorebanala
@jfernandez
