### ISSUE TITLE
CONFLICT BACKEND_ERROR

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#2014]
I used the latest version v2.30.4 and use mysql as my default storage, but got error below:

[INFO ] 2020-12-21 13:09:20,426 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,450 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,466 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,483 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,506 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,523 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,541 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,563 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,579 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,598 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,620 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,636 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,654 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,676 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,683 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,692 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,712 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,733 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,749 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,769 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,789 MySQLQueueDAO - CONFLICT BACKEND_ERROR
[INFO ] 2020-12-21 13:09:20,806 MySQLQueueDAO - CONFLICT BACKEND_ERROR

**Comment by aravindanr** [comment]
MySQLQueueDAO is a contribution and we don't use or maintain it. A brief look at the code is pointing us to a SQLException when polling for a message in [MySQLBaseDAO](https://github.com/Netflix/conductor/blob/master/mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLBaseDAO.java#L209-L215). It would have been helpful if the SQLException was logged somewhere.

This is likely because of a database misconfiguration. Tagging @picaron and @mashurex as they have more context.

**Comment by andyyumiao** [comment]
this caused by the wrong mysql table structure, it fixed when i reinitializes the correct table structure

**Comment by weiwensi** [comment]
我尝试将表结构由原来的MySQL改为了Oracle启动的时候一直打印和这一样的信息，不可以Oracle吗？
