### ISSUE TITLE
Execution problems due to mandatory ownerEmail value

### ISSUE THREAD

**Issue by azb96** [Netflix/conductor#2021]
ownerEmail value in Workflow and Task objects should be optional. Otherwise it creates problems with existing workflows on master branch. @kishorebanala

**Comment by mehmet-islamoglu** [comment]
Thank you @azb96 for creating this issue. We are also facing problems in this regard.

**Comment by RileyMichael** [comment]
There is a property you can override so that it's not mandatory: https://github.com/Netflix/conductor/blob/86d3c1ee690b636b20726843d6dfa9adf822e854/core/src/main/java/com/netflix/conductor/core/config/Configuration.java#L122-L123
