### ISSUE TITLE
Retry Mechanism in SubWorkflow continued

### ISSUE THREAD

**Issue by mehmet-islamoglu** [Netflix/conductor#2026]
This is issue is continuing the following issue: #2012 

The related PRs are here:
#2025 #2024

**Comment by mehmet-islamoglu** [comment]
@apanicker-nflx 
@kishorebanala 
@v1r3n 
@jfernandez

**Comment by mehmet-islamoglu** [comment]
I created two PRs to dev and master for this issue.

I can't re-open or move the previous issue to backlog->TO-DO, so checks on my PRs are failing. 

That's why I decided to open this new issue, which is a continuation of my previous issue. 

How should I proceed with my contribution/PR at this point?


@v1r3n
@apanicker-nflx
@kishorebanala
@jfernandez

**Comment by azb96** [comment]
@apanicker-nflx @kishorebanala @aravindanr @jfernandez @mehmet-islamoglu can you please guide us forward with the process?

**Comment by mehmet-islamoglu** [comment]
@aravindanr @apanicker-nflx We will be updating the PR as requested by @kishorebanala. Could you please move this issue to backlog->TO-DO so that we can pass the PR checks?
