### ISSUE TITLE
Question: Configuration settings for Conductor with a non-Dynomite based Redis instance

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#203]
In case I want to configure a non-Dynomite based Redis instance...

What configuration settings do I need to configure?
From the documentation, I can see
- db = redis
- queues.dynomite.nonQuorum.port=22122
- workflow.namespace.prefix=conductor

But where do I have to configure the Redis host to connect?

Should it be via the field `workflow.dynomite.cluster.hosts` ?
If yes, what about the rack information - could it be populated with a dummy value?

```
# memory : The data is stored in memory and lost when the server dies.  Useful for testing or demo
# redis : non-Dynomite based redis instance
# dynomite : Dynomite cluster.  Use this for HA configuration.
db=dynomite

# Dynomite Cluster details.
# format is host:port:rack separated by semicolon
workflow.dynomite.cluster.hosts=host1:8102:us-east-1c;host2:8102:us-east-1d;host3:8102:us-east-1e

# Dynomite cluster name
workflow.dynomite.cluster.name=dyno_cluster_name

# Namespace for the keys stored in Dynomite/Redis
workflow.namespace.prefix=conductor

# Namespace prefix for the dyno queues
workflow.namespace.queue.prefix=conductor_queues

# Non-quorum port used to connect to local redis.  Used by dyno-queues.
# When using redis directly, set this to the same port as redis server
# For Dynomite, this is 22122 by default or the local redis-server port used by Dynomite.
queues.dynomite.nonQuorum.port=22122
```

Thanks for any help.

**Comment by nbraquart** [comment]
Hello,

If I can be of any help: for demo/testing purposes I have replaced Dynomite with a Redis database. What I did was setting the host in the value workflow.dynomite.cluster.hosts as you thought. For the cluster, I did not change the default ones, and it worked like a charm.

It is true that the server configuration is quite Dynomite-oriented, but I must say that looking at the server code was really helpful :)

Hope this will work for you too!

Nicolas

**Comment by ma-sir** [comment]
## Conductor with a non-Dynomite based Redis Configuration
``` 
systemProperty 'db', 'redis'
systemProperty 'workflow.dynomite.cluster.hosts', '192.168.1.21:32768:us-east-1c'
systemProperty 'workflow.namespace.prefix', 'conductor'
systemProperty 'workflow.namespace.queue.prefix', 'conductor_queues'
systemProperty 'workflow.elasticsearch.url', '192.168.1.21:32771'
systemProperty 'workflow.elasticsearch.index.name', 'conductor'
```

**Comment by blueelephants** [comment]
Thanks for your help
