### ISSUE TITLE
ES7 support

### ISSUE THREAD

**Issue by heinrichcohn** [Netflix/conductor#2030]
@apanicker-nflx 
Hi

I have implemented the ES-persistence module for ES7. 
It based on ES6 implementation with a few changes due to the significant breaking changes made in Elasticsearch from version 6 to 7.

**Main Changes:**

1. Mapping Types - Since these are now deprecated, i changed all API calls to use the new format. Templates json files were updated accordingly
2. Template API was changes to use the new Index template api.
3. Since TransportClient is now deprecated, the only transport supported is 'http' and 'https', non-rest implementation was removed from the code.

I'll create a PR and submit it for review

Thanks

**Comment by heinrichcohn** [comment]
PR create:
https://github.com/Netflix/conductor/pull/2031

**Comment by aravindanr** [comment]
@heinrichcohn Thanks for taking the time to do this PR. Would you mind creating a `es7-persistence` module for 3.0? We migrated to `es6-persistence` to 3.0 which can be seen [here](https://github.com/Netflix/conductor/tree/3.0/es6-persistence). You can follow the same procedure to migrate this for 3.0 as well. Note that 3.0 will be the future and 2.x will be deprecated soon.

**Comment by heinrichcohn** [comment]
@aravindanr  No problem, i'll create an additional PR for 3.0 branch containing es7 support. Until then can we merge  this PR to 2.x.
In another future PR i will update remaining rest calls to use the the high-level rest client only. ( I'll add those changes to 3.0 as well)

**Comment by heinrichcohn** [comment]
@aravindanr @apanicker-nflx 
Anything new regarding this PR? I have additional code i would like to add, such as: 
- ES Basic Authentication
- Extend ES indices/aliases creation  in order to facilitate integration with multiple clusters, and Cross-Cluster-Replication

Thanks

**Comment by Paxon96** [comment]
Hi @aravindanr  @apanicker-nflx
I and my team are willing to use conductor with ES7 support. When can we expect to merge this PR #2031 ? 
Soon we will have to move from ES6 to ES7 and I hope for an official solution, rather than implementing something ourselves.

Best regards!

**Comment by apanicker-nflx** [comment]
@heinrichcohn Thank you very much for the contribution. 

@Paxon96 we expect to merge this PR soon within the next couple of days.

**Comment by apanicker-nflx** [comment]
@heinrichcohn Closing this issue for now since the PR has been merged. Please create another PR for the 3.0 branch.

**Comment by autodidactic** [comment]
hi 
is there a PR for ES7 merged code for server version 3.13.3
