### ISSUE TITLE
Subworkflows in Scheduled

### ISSUE THREAD

**Issue by kdohyeon** [Netflix/conductor#2033]
Hello,
I have a question related with 'sub-workflows'.

I am running a workflow that contains a sub-workflow.
I recognized that the sub-workflow gets 'scheduled' before it gets run.
The thing is that the sub-workflow stays in the 'scheduled' state for like 30 seconds or more.

I would like to know a method that starts the sub-workflow right away.
<img width="896" alt="스크린샷 2021-01-05 오후 4 00 49" src="https://user-images.githubusercontent.com/11426140/103616283-75b9b100-4f6f-11eb-833b-3a5603d0d38b.png">
From the screenshot, the 5th one is the subworkflow (i.e., '...ommon_step_execute_workflow').
It gets 'scheduled' at 10:19:13 and starts at '10:20:04' (waited like 50 seconds or so)

Thank you in advance.

**Comment by apanicker-nflx** [comment]
@kdohyeon Could you please expand on the use case for synchronous execution of subworkflows? This design decision to asynchronously execute subworkflows was made consciously to ensure reliable execution and completion of subworkflows and the corresponding subworkflow tasks.

**Comment by HenryLauu** [comment]
I have the same situation where the subworkflow takes very long time to start, would you pls advise how to figure out what is actually happening? @apanicker-nflx 
![image](https://user-images.githubusercontent.com/35942020/118581792-c9ad8f80-b7c4-11eb-9983-1174272d2b31.png)

**Comment by HenryLauu** [comment]
> I have the same situation where the subworkflow takes very long time to start, would you pls advise how to figure out what is actually happening? @apanicker-nflx
> ![image](https://user-images.githubusercontent.com/35942020/118581792-c9ad8f80-b7c4-11eb-9983-1174272d2b31.png)

to be clear, i am using mysql as backend.

**Comment by apanicker-nflx** [comment]
@HenryLauu What version of Conductor are you using? Subworkflows are started by system task workers, could you please check how many threads you have assigned for these workers?
