### ISSUE TITLE
testWorkflowDefJson failure on dev and master branches

### ISSUE THREAD

**Issue by azb96** [Netflix/conductor#2037]
We are trying to contribute conductor project but testWorkflowDefJson test fails without interacting to our code. After running the master branch we found out that it fails either way(both on dev and master branches). Can you fix this problem? Test is on SubWorkflowParamsTest.java class.

**Comment by mehmet-islamoglu** [comment]
Thank you @azb96. This test failure is causing the build to fail.

**Comment by kishorebanala** [comment]
@mehmet-islamoglu @azb96 I couldn't reproduce this. I've also merged one of your PR's, for which the build has passed in both the branch and devint. I'm closing this, but please feel free to re-open this issue, if you continue to see this.
