### ISSUE TITLE
Pull rate limit problem

### ISSUE THREAD

**Issue by azb96** [Netflix/conductor#2039]
Hello we are trying to contribute to your project but due to  docker compose up fail we can't get a build on Travis CI.  (Pull request #2038 ) Details can be seen below. 

```
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
No stopped containers
> Task :conductor-mysql-persistence:integrationTestDockerComposeUp FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':conductor-mysql-persistence:integrationTestDockerComposeUp'.
> Exit-code 1 when calling docker-compose, stdout: N/A
```

How can we solve this issue? Can you help us with the process? @apanicker-nflx  @kishorebanala  @jfernandez @aravindanr

**Comment by aravindanr** [comment]
This is because of the new rate limits introduced by DockerHub. Retrying the build after some time should solve the problem. We will see if we can add DockerHub credentials that will reduce the likelihood of this issue.
