### ISSUE TITLE
feature: allow setting a very short (100char?) "label"/"description"/"tags" when starting a workflow

### ISSUE THREAD

**Issue by Jiehong** [Netflix/conductor#2047]
Hi,

Today, when starting many executions for the same workflow, the only way to really understand what is different between them when retrieving them, is to check what inputs were provided.

However, it would be convenient to be able to set a "tag"/"description"/"label" that could be searched for, but also as a way to quickly understand the execution with a human-readable field.

I propose to add a new field in https://github.com/Netflix/conductor/blob/dev/common/src/main/java/com/netflix/conductor/common/run/Workflow.java, allowing to add a 200 chars description.

I don't know if "label", "description" or "tags" is better, but one of them.

If you agree with this, I can make a PR to implement this.

**Comment by aravindanr** [comment]
There is already a field [correlationId](https://github.com/Netflix/conductor/blob/dev/common/src/main/java/com/netflix/conductor/common/run/Workflow.java#L94-L95) that can be used for this.

**Comment by Jiehong** [comment]
@aravindanr : I know about the correlationId, which is a unique, machine-generated element.

Here, I'm talking about a non-unique, human-generated element.

Could you please re-open this issue?

**Comment by Jiehong** [comment]
@aravindanr : ?

**Comment by Jiehong** [comment]
@aravindanr / @moustaki  / @jfernandez  / @fabiokung  hello…

**Comment by apanicker-nflx** [comment]
Re-opening to further the discussion.

@Jiehong Do you intend to use both the correlationId field and the newly proposed field? In this case, how do you propose setting the new field? And how it would differ from the correlationId since you could set this to a generic string instead of a machine generated element.

**Comment by Jiehong** [comment]
The correlationId is supposed to be unique for that workflow, right? (and it has a fixed size?)

This new "comments" field is optionally provided by the user, and allows adding comments to that workflow.

For example, if I have a workflow whose job is to setup a new user in some systems (via http calls). I might want to comment some of those workflow with "category 1" when starting those workflows.

Later, I can then decide to retrieve all workflows whose comments contains "category 1".

This tag allows to add some kind of input that is not an input (because it is not needed for the good execution of the workflow), but lets humans add a "comment" as a way to add context information they find important, and that can be queried.

Do you mean that correlation-id can be used like that? It just wasn't clear to me if that's the case.

**Comment by amisol** [comment]
Yes correlationId can be used exactly like you're describing

**Comment by Jiehong** [comment]
Alright then, thank you!
Closing this issue.
