### ISSUE TITLE
docs: Apispec sort format in documentation doesn't match the implementation

### ISSUE THREAD

**Issue by n-h** [Netflix/conductor#2050]
👋  

**Actual**
The Apispec documentation for searching workflows lists the search format as `<direction>:<field>`:
![Screen Shot 2021-01-12 at 2 54 05 PM](https://user-images.githubusercontent.com/2981255/104365512-123b0080-54e6-11eb-842d-19be94d9a6e1.png)

The implementation uses the reversed format, than what is in the docs. Implementation is here:
https://github.com/Netflix/conductor/blob/be9e74ebd8ee784abb2b5d0eeb9d4c3786fe108f/jersey/src/main/java/com/netflix/conductor/server/resources/WorkflowResource.java#L214

Note: Swagger UI already matches the implementation, so no change needed there.
![SwaggerUI](https://user-images.githubusercontent.com/2981255/104057581-654c4500-51c0-11eb-9ad0-0c7fad384368.png)

**Expected**
That the sort parameter in the docs would be the same as in the implementation.

Here is a PR to make this small update https://github.com/Netflix/conductor/pull/2042

**Comment by aravindanr** [comment]
PR has been merged.
