### ISSUE TITLE
How to get 'Task execution logs'?

### ISSUE THREAD

**Issue by WavyPeng** [Netflix/conductor#2053]
Hi, I want to get task execution logs，and I find a method in **TaskResult**. But when I call **TaskResult.getLogs()**, it returns nothing. 
Also, the Logs  of a task in our Conductor UI shows no content, like this: 
![image](https://user-images.githubusercontent.com/26155781/104595817-144fbb80-56ae-11eb-8e0a-ea28874bde8c.png)

So, how can I get 'Task execution logs'?
Thank you :)

**Comment by apanicker-nflx** [comment]
The task execution logs that are shown in the UI and part of the TaskResult object need to be explicitly added by your worker that process the tasks. 
To add to the example [here](https://github.com/Netflix/conductor/blob/master/client/src/test/java/com/netflix/conductor/client/sample/SampleWorker.java), you would need to add result.setLogs(<Insert list of task execution logs here>).
