### ISSUE TITLE
Postgres processAllUnacks does not work

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#2058]
@mactaggart I noticed a problem with the SELECT/FOR UPDATE during the poll. When the task is being updated to COMPLETED (POST /tasks), the removeMessage (i.e. DELETE FROM queue_message) method is taking a long time sometimes. It seems to be related to there being a lock on the row that it is trying to DELETE.

I tried putting in an UPDATE statement right before the DELETE to try and clear the lock but that doesn't seem to help. Sometimes these DELETE operations are taking upwards of a minute.

Will let you know if I figure out how to solve this. It might have something to do with the queue size (500k tasks for this task type) or how the polling is being done (asking for 500 at a time) that exacerbates it but not sure.

**Comment by rickfish** [comment]
Actually I think it has to do with processAllUnacks locking the rows. @mactaggart does the processAllUnacks() method work for you? I notices that the UPDATE of the rows to set popped to false returns 0 meaning no rows are ever actually updated. In my case the SELECT/FOR UPDATE statement actually returns 3 million rows because the update never actually does anything. So you can imagine what the statement 'IN' parameter looks like. I am surprised that it took this long for someone to report a problem that points back to this.

**Comment by rickfish** [comment]
So it turns out that the newest implementation of processAllUnacks() for Postgres does not work and in fact causes performance issues. It does a query to get all rows in queue_message with popped=true FOR UPDATE SKIP LOCKED. That locks all the rows. Then it does an UPDATE statement that uses a 'message id IN(?)' parameter variable that is set to a comma-delimited list of message ids. This is not valid syntax as it looks for messages that have a message id of the comma-delimited list. Obviously that does nothing. So all the rows stay locked.

This has been happening in our system since October last year so there are currently over 3 million rows in the queue_message table that have not had their popped flag set back to false.

Also, locking all those rows has caused the removeMessage() DELETE statement to wait for the lock to be released, in some cases taking over a couple of minutes. So if a worker polls, gets a task and calls the POST /tasks service to COMPLETE the task, since the removeMessage() call is the last step in that process, it times out at the HTTP server.

In any case, I am going to at some point create a pull request to change the implementation. I am thinking that I will add a LIMIT 1000 to the query that gets the unacked messages. Then I will separate the messages by queue_name and call the UPDATE statement one for each queue_name and pass in the comma-delimited list of message ids hard-coded in the query as opposed to using a variable. That way, I can call the UPDATE with the queue_name and message_id in the predicate so that the index is used.

Sorry, I should have caught this when reviewing the pull request that added locking.

**Comment by mactaggart** [comment]
@rickfish apologies for the delay. We're running an older version that doesn't include the most recent changes to processAllUnacks() so I haven't encountered this issue. Glad you found the cause. I didn't catch this when reviewing that PR either, so guilty here too. Looking at PostgresQueueDAOTest, processAllUnacks is called, but the invalid code isn't reached since there aren't any unack'd messages. I'd recommend we modify existing or add a test that covers the UPDATE queries.

I think splitting up the updates by queue name is a good approach to minimize size of SQL statements, especially with heavy workloads.  For the update, Postgres supports passing in an array for a prepared statement. So we could create an array using: Array msgIds = tx.createArrayOf("VARCHAR", messages), then update using: WHERE message_id = ANY (?) AND queue_name = ?. I think that would also use the index, but not sure.

**Comment by rickfish** [comment]
@mactaggart thanks for the tip on using an Array and a parameter. Works like a charm. I am swamped right now but will try to contribute it back shortly.

**Comment by mactaggart** [comment]
@rickfish I can help with this. Do you plan to submit a PR?

**Comment by rickfish** [comment]
@mactaggart sorry, I am swamped right now and probably will be for a while. I have been meaning to change my code from what we discussed. I happened upon PostgresExecutionDAO.getTasks() that uses Query.generateInBindings(). I think that would probably be the better way to go. It probably executes the same but that would be the more 'standard' way. What do you think?

**Comment by mactaggart** [comment]
@rickfish I doubt building a placeholder string is more efficient than passing the array in directly, but agree it may be a more "standard" especially if we're going to abstract/reuse these queries across different SQL backends eventually. SQL IN is pretty standard, not sure about SQL ANY beyond postgres.
