### ISSUE TITLE
WorkflowStatusListener requires flag enabling it on Workflow Definition

### ISSUE THREAD

**Issue by flavioschuindt** [Netflix/conductor#2064]
Hi,

I was able to implement my own custom workflow completion/termination listener. It just works. However, I noted that it is only being activated if I add the property ```"workflowStatusListenerEnabled": true``` in the workflow definition. This is required because conductor code is relying on this property in the [WorkflowExecutor](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L689) class.

I tried to check if there is any sort of global property that would allow the listener for all workflows without having to explicitely set it on the workflow definition, but no luck. This would facilitate a lot of use cases in my scenario where I don't control the workflow definitions, but I want to have control over completion of them to take some extra action upon completion, e.g., talk to another system, etc.

Is there a way to allow it somehow? Thank you.

**Comment by aravindanr** [comment]
WorkflowExecutor can be modified to look at a global property and invoke the `WorkflowStatusListener`. If you have the time, please create a pull request.
