### ISSUE TITLE
Custom concurrent execution limiting

### ISSUE THREAD

**Issue by TwoUnderscorez** [Netflix/conductor#2066]
The purpose of this issue is to discuss a new interface that would solve the problem explained in #1893.
I am planning to implement this interface, but here are some questions I have:
1. `ExecutionDAO.exceedsInProgressLiint` will do the task def limit check, then call the new interface, then rate limit check?
2. What methods should the interface have? I think only one method `exceedsLimit` that receives one `Task` as a parameter.
3. I will want to also add my implementation of the interface, which requires semaphores. Is the implementation of semaphores in #1893 acceptable, @apanicker-nflx ?

**Comment by apanicker-nflx** [comment]
@TwoUnderscorez Thanks for starting the discussion.

> ExecutionDAO.exceedsInProgressLiint will do the task def limit check, then call the new interface, then rate limit check?

I would suggest extracting out the concurrent execution limit into its own interface similar to the [RateLimitingDAO](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/dao/RateLimitingDAO.java). The interface method here would perform the in progress limit check for the tasks.

>What methods should the interface have? I think only one method exceedsLimit that receives one Task as a parameter

For starters, this interface would have the method `exceedsInProgressLimit` with the current implementation as the default provided. 

>I will want to also add my implementation of the interface, which requires semaphores. Is the implementation of semaphores in #1893 acceptable, @apanicker-nflx ?

We can review the implementation of this feature using semaphores once it has been separated out.

**Comment by TwoUnderscorez** [comment]
@apanicker-nflx Alright. There is only one problem with that.  The `exceedsInProgressLimit` methof in the redis and mysql execution daos contain code that executes queries on redis and mysql respectively, so it'd be kind of problematic to fi that. Unless implementations of this new DAO can depend on the execution dao. Then we can add that method to the execution dao interface. 

As for the semaphores, unfortunately I won't be able to separate them into a different pull request because the whole reason I'm doing this is so that I can achieve the functionality I need from the conductor. 

Also, for the functionality I want to add, I'll need to store data inside the `WorkflowTask` object.  Is that ok? If not, are there any alternatives?

Thanks

**Comment by TwoUnderscorez** [comment]
I will soon (week or two) open a pull request. We are currently running it in our environment to make sure it works properly.

**Comment by TwoUnderscorez** [comment]
I’ve also opened a PR for conductor version 3. It’s not ready yet though, so if possible can you start with version 2 and then have a look at version 3 which will hopefully be ready till then?

**Comment by TwoUnderscorez** [comment]
Hey @apanicker-nflx, when do you think someone can have a look at  #2283?
Thanks.

**Comment by TwoUnderscorez** [comment]
@apanicker-nflx Any updates? Thanks.

**Comment by aravindanr** [comment]
hi @TwoUnderscorez , sorry about the delay. I am slated to work on refactoring the concurrent execution limits. I will review your PRs by 07/13.

**Comment by TwoUnderscorez** [comment]
@aravindanr Thanks, I'll be waiting.

**Comment by aravindanr** [comment]
@TwoUnderscorez Thanks for taking the time to create the PR. The work you have done with separating the "concurrent execution limit" check into its own DAO is a welcome change. You have implemented the logic mentioned in #1893 in the 
[TaskDefAndWorkflowTaskLimitingDAO](https://github.com/Netflix/conductor/pull/2284/files#diff-6df1906ffc8a32e0831428f12bee5456ca22b7c1c2740d551753671568f79897) class. That implementation is very specific to your need and we don't think that should be part of Conductor. We don't see widespread demand for such a concurrent execution implementation. Including it as part of Conductor adds complexity to an already complex system.

We are in the process of refactoring the "concurrent execution limit" into its own contract. It should be out in the next month or so. At which point, you would be able to hook in `TaskDefAndWorkflowTaskLimitingDAO` _in your own fork of Conductor_.

**Comment by TwoUnderscorez** [comment]
@aravindanr Note taken. We'll keep everything in our internal repo.
