### ISSUE TITLE
Need suggestions on scaling Conductor 

### ISSUE THREAD

**Issue by raghavendra-bhat** [Netflix/conductor#2067]
We have been running performance tests with Conductor on Postgres and so far we managed to get the system scale upto a point of **completing** 35 workflows per second. The workflow that we ran our tests had around 20 tasks with 16 worker tasks. The env setup that we used are below:

14 Conductor pods (2 core and 3 GiB each) and single PostgreSQL instance server (64 core). 

Though there are options to scale out Postgres horizontally we didn't explore it further as we found that some of the queries (like the polling query shown below) might continue to be the bottleneck even if we did. The workflow we have defined had more number of tasks of a certain type as compared to others task types. Hence we saw skewed data in the queue_message table and the backlog for this task type building up more as compared to other tasks. 

SELECT message_id, priority, payload FROM queue_message WHERE queue_name = ? AND popped = false AND deliver_on <= (current_timestamp + (1000 ||' microseconds')::interval) ORDER BY priority DESC, deliver_on, created_on LIMIT ? FOR UPDATE SKIP LOCKED

The above query took lot of time as it needed the query results to be sorted especially for the queue that has lot of backlog. Even if we did distribute the data based on queue_name in a PG cluster we will not be able to completely avoid the ORDER BY. If we change the query to not include the order by clause the response time improved significantly. Likewise we saw another query (please see below) that was creating a bottleneck by holding lock. By changing the query to UPDATE SKIP LOCKED time spent on locking reduced. However with these two changes there is a certain amount of impact to functionality. 
UPDATE poll_data SET json_data=?, modified_on=CURRENT_TIMESTAMP WHERE queue_name=? AND domain=?

Our initial plan was to scale the system to meet 125 workflows per sec but looking at the test results that we got it is not encouraging. The amount of resources to even meet 35 workflows is on the higher side. Our future plans is to scale the system beyond 250 and more. We find that PostgreSQL might not be right technology choice to be able to scale to such requirements. I am looking for suggestions/guidance from the community on the right tech that can overcome the limitations by scaling out horizontally. Using Cassandra appears to be the next thing I can try out as I have the flexibility to scale out horizontally. I would also like to hear from the community on the experience and learnings with Cassandra as the persistence store and can it help me scale out the way I am expecting.

**Comment by aravindanr** [comment]
Postgres persistence is community contributed. Netflix uses Cassandra for persistence and Redis for queuing. Number of workflows completed per second is not a general metric that can be used to measure Conductor's throughput as that metric is not only dependent on Conductor. Workflow definitions are arbitrary and we have workflows which take anywhere from few minutes to several weeks to complete. Workflow completion could be affected by various factors like the availability of workers to process tasks, whether the workflow represents a business process that requires human intervention etc.

If you could share more details about your workflow definition, we might be able to provide more details about how Cassandra persistence scales.

**Comment by aravindanr** [comment]
Looping in @rickfish and @mactaggart who may have more context about postgres-persistence

**Comment by raghavendra-bhat** [comment]
@aravindanr Thanks for the comment. Yes, its true that the completion depends on other factors including the time it takes to complete task inside the worker. We wanted see how well the Conductor server completes workflows if there is no delay when worker completes a task. Hence we have have stubbed the client/worker and instead used jmeter to generate the load that a worker would have generated in real world. Jmeter scripts invoked poll tasks followed by update task status APIs and completed the workflows. This way, we have eliminated the delays had the task been completed inside the worker and only get the server's capability. 

It's also true that the time it takes to complete a certain task in a workflow may also vary depending on the workflow. However, with the workflow that we have designed we wanted to understand how best Conductor can be scaled. I am attaching the sample workflow that we have used for this testing. 

[doc-workflow.pdf](https://github.com/Netflix/conductor/files/5911924/doc-workflow.pdf)

**Comment by rickfish** [comment]
@raghavendra-bhat I am going to create a pull request to change the combo_queue_message index to sort by priority desc instead of asc (the default). That DRAMATICALLY increases the performance of the polling call, especially on the sweeper when it polls for _deciderQueue messages. This is critical for high-volume situations like ours where we have millions of rows in queue_message. Try that change to the index and I think you will notice a significant improvement. I am heads-down right now, when I have a chance to look up I will do the pull request.

**Comment by aravindanr** [comment]
@raghavendra-bhat Additional context helps. During task poll and update, Conductor reaches out to both the queue and the persistence layers. With C* as the persistence layer, writes might be faster although we don't have comparisons of C* vs Postgres. We are curious to know what the results of your test with C* are. 

For high throughput scenarios, redis-persistence might be a better fit. But Redis's durability is not comparable to a database like C* or Postgres

**Comment by raghavendra-bhat** [comment]
@aravindanr  Instead of using Redis persistence, we are planning to use Hazelcast as it supports distributed queuing and inbuilt clustering. I would like to hear if there are any gaps using Hazelcast like tech.

**Comment by jpcarlino-invitae** [comment]
> @aravindanr Instead of using Redis persistence, we are planning to use Hazelcast as it supports distributed queuing and inbuilt clustering. I would like to hear if there are any gaps using Hazelcast like tech.

Hi @raghavendra-bhat . Your testing scenario is useful for me in the sense you are exploring similar storage options. I would like however to confirm I'm understanding correctly:

Primary storage: PostgreSQL
Queue storage: PostgreSQL
Secondary storage: ?

Is this correct? In case my understanding is correct: any reason why you choose PostgreSQL instead of DynoQueues?
Similar question about replacing with Cassandra. My understanding is that there is no DAO for Cassandra (just did a quick search on branch 3.0) so I think I've a confusion here between "primary storage" and the task queue storage.

**Comment by raghavendra-bhat** [comment]
@jcacciatore Sorry for the delay in response. We started off using PostgreSQL as it made tech stack little lighter (no separate DynoQueue needed). Conductor has modelled queues as Postgres table. So primary and queue storage is Postgres. 

However we soon found that scaling using Postgres has its own limitation as compared to Cassandra like database. Conductor does have support for Cassandra (I see cassandra-persistence is also available in 3.0 as well). However the implementation is only partial. There are some unimplemented methods and Daos on Cassandra. One of the important Dao is the QueueDao. This is where are exploring using other tech like Hazelcast as it provides distributed priority queue implementation required for QueueDao. Since Dyno project is no longer under active maintenance we are planning to implement using Hazelcast. The underlying persistence storage for queues in Hazelcast could well be Cassandra tables. 

We are still exploring what are the options on the unimplemented methods with ExecutionDao itself. @aravindanr Any suggestions on this?

**Comment by aravindanr** [comment]
Using Cassandra for Queue is a known anti-pattern. That's why there is no QueueDao implementation backed by it.  Internally, we use Cassandra for Metadata and Executions, with QueueDao backed by an internal priority queuing system.
