### ISSUE TITLE
How to set the value of "conductor.worker.<taskDefName>.<property>"

### ISSUE THREAD

**Issue by WavyPeng** [Netflix/conductor#2072]
Hi, I need to pause worker from polling tasks, And I see a method provided in our [document](https://netflix.github.io/conductor/gettingstarted/client/) that we can set the value of conductor.worker.<taskDefName>.<property> to implement this. But I don't know how to use it. Is there any example for this? Thank you :)

**Comment by kishorebanala** [comment]
@WavyPeng `conductor.worker.<taskDefName>.<property>` is one of the configurable properties of the worker. For eg., you can set `conductor.worker.task_1.paused` property to `true` to pause a task (by task reference name) `task_1`. Also, if you don't have dynamic reload on the properties, you might have to restart your worker instance to enable this property.

I'm closing this, but feel free to reopen if you need further clarification.
