### ISSUE TITLE
the demo "kitchensink" can't initialize on docker-compose

### ISSUE THREAD

**Issue by liangguohun** [Netflix/conductor#2074]
i run by docker-compose and start ok, but the  "kitchensink" can't initialize. i don't know if the config file is ok or  not, and i can't get every task singleton.

**Comment by apanicker-nflx** [comment]
@liangguohun Can you please elaborate on ```the "kitchensink" can't initialize``` . Are you seeing an error when loading the kitchensink workflow or running it?
