### ISSUE TITLE
Is there any way to bulk delete the workflow metadata

### ISSUE THREAD

**Issue by gau31rav** [Netflix/conductor#2077]
In dynomite / redis, workflow metadata is maintained forever. We have a requirement to delete the older workflow metadata.

According to API specification https://netflix.github.io/conductor/apispec/

GET API returns 100 records at a time and in DELETE we can specify only one workflow id at a time. Which adds to the execution time.

Is there a way to bulk delete the older workflow metadata.

**Comment by aravindanr** [comment]
@gau31rav There is no API to bulk delete.
