### ISSUE TITLE
Can we manually fail the workflow

### ISSUE THREAD

**Issue by shahhuda** [Netflix/conductor#208]
I have a decision box. Here the flow gets divided for 'yes' or 'no'. For yes it can follow the normal flow. If its 'no' then I have a simple task and then I want to manually fail the workflow. Is it possible?

**Comment by sameekb** [comment]
I didn't try but worth a try:

In the 'No' path, after the SIMPLE task introduce another SIMPLE task. In the corresponding overriding execute(...) method of the Worker implementation of this newly introduced simple task, explicitly set the task result status as FAILED.

```
public TaskResult execute(Task task) {
		TaskResult result = new TaskResult(task);
                result.setStatus(Status.FAILED);
               return result;
}

```

**Comment by v1r3n** [comment]
As @smkb80 suggested, a SIMPLE "Failure" task will work as suggested above.
