### ISSUE TITLE
Mongodb integration with Conductor

### ISSUE THREAD

**Issue by guru1306** [Netflix/conductor#2088]
Hi All

We are using MongoDB in our product. We want to leverage the Mongo DB for Conductor.  Will the PR be accepted if we can contribute?

Thanks
Guru

**Comment by apanicker-nflx** [comment]
@guru1306 The persistence layer in Conductor is a plugin and can be implemented using pretty much any data store. We would welcome a contribution that would benefit the community.

Before getting started on the PR however, please outline the design and implementation plan for this persistence layer in a separate issue. Also, as with any open-source project, the buck does not stop with the contribution and we would rely on you/your team for help with maintenance and answering support requests from other users in the community who would be interested in using this module.
