### ISSUE TITLE
Licensing for conductor

### ISSUE THREAD

**Issue by venkatrangan** [Netflix/conductor#2091]
I have a question on conductor license. The entire conductor distribution is licensed under Apache license. However, one of the dependencies - javax.el downloaded from glassfish is covered by GPL, CDDL license, per maven central - https://mvnrepository.com/artifact/org.glassfish. What is the legal position for a solution that uses conductor, but the dependencies now entangle them with a stricter license?

Thanks!

**Comment by kishorebanala** [comment]
@venkatrangan We've removed this dependency in [Conductor 3.0 branch](https://github.com/Netflix/conductor/tree/3.0), which we expect to be generally available very soon. Thanks for pointing this!
