### ISSUE TITLE
batch poll with domain: NO_DOMAIN won't return default queue tasks

### ISSUE THREAD

**Issue by rakeshnarang5** [Netflix/conductor#2096]
At the time of starting a workflow,
I put the following entry in taskToDomainMap
key: "*"
value: "NO_DOMAIN"
This put all the tasks in my workflow in the default queue.
----
But, when I am batch for tasks using domain: NO_DOMAIN,
it is not returning any tasks
but if I will remove the property conductor.worker.<my-worker>.domain from application.properties
the task gets picked
what is the value to pick from default queue?

**Comment by aravindanr** [comment]
`NO_DOMAIN` is a keyword used when defining fallback domains. If you are not planning to use domains, there is no need to populate the `taskToDomainMap`. If `NO_DOMAIN` is specified during poll, Conductor looks for the task in a domain named "NO_DOMAIN". Not specifying a domain property, makes the _poll_ call look for tasks without a domain.
