### ISSUE TITLE
Sometimes, The order of execution of the tasks is not following the order of execution drawn in the definition of the workflow

### ISSUE THREAD

**Issue by mignoni** [Netflix/conductor#2106]
Sometimes, The order of execution of the tasks is not following the order of execution drawn in the definition of the workflow

You can see below 2 executions of same workflow definition, **the first worked, the second not**:

The last task in the workflow is "RootJson", in the second execution you can see that the task was not executed last.

I put workflow definition in Simulation-Promotional-def.zip. Attached too the JSON of execution, json_works.zip and json_not_works.zip.

- [Simulation-Promotional-def.zip](https://github.com/Netflix/conductor/files/6075970/Simulation-Promotional-def.zip)

- [json_works.zip](https://github.com/Netflix/conductor/files/6075971/json_works.zip)

- [json_not_works.zip](https://github.com/Netflix/conductor/files/6075973/json_not_works.zip)

**The two executions had the same input but performed differently.**

This behavior causes a difference in the final JSON. Task RootJson.

### 1 - Works:

![image](https://user-images.githubusercontent.com/484043/109533251-ca256c80-7a98-11eb-8e19-dca2057051da.png)
![image](https://user-images.githubusercontent.com/484043/109533340-e0cbc380-7a98-11eb-9696-f6813abfc009.png)

### 2 - Not Works:

![image](https://user-images.githubusercontent.com/484043/109533545-1c668d80-7a99-11eb-8ad2-6959a4ae92e0.png)
![image](https://user-images.githubusercontent.com/484043/109533688-43bd5a80-7a99-11eb-9630-63aab5508e62.png)

### Configurations Of Conductor Server

**Conductor Version: release 2.31.0**

The **Conductor** Server **runs** on **Kubernetes** (EKS) with **32 PODs** with the configuration: "**500 millicore + 1 GB of memory**" each, using **Mysql** as Persistence.

Below, the configuration file used by the driver

### Conductor Config File:

```
conductor.jetty.server.enabled=true
conductor.grpc.server.enabled=false

db=mysql

jdbc.url=jdbc:mysql://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:3306/conductor
jdbc.username=XXXXXXXXXXXX
jdbc.password=XXXXXXXXXXXX

conductor.mysql.connection.pool.size.max=40
conductor.mysql.connection.pool.idle.min=20

workflow.namespace.prefix=conductor

workflow.namespace.queue.prefix=conductor_queues

workflow.repairservice.enabled=true

workflow.elasticsearch.instanceType=external

workflow.elasticsearch.url=https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:443

workflow.elasticsearch.index.name=conductor

conductor.additional.modules=com.netflix.conductor.contribs.metrics.MetricsRegistryModule,com.netflix.conductor.contribs.metrics.LoggingMetricsModule

loadSample=false
conductor.jetty.server.enabled=true
conductor.grpc.server.enabled=false


workflow.system.task.worker.thread.count=200

conductor.additional.modules=com.netflix.conductor.contribs.metrics.MetricsRegistryModule,com.netflix.conductor.contribs.metrics.LoggingMetricsModule
com.netflix.conductor.contribs.metrics.LoggingMetricsModule.reportPeriodSeconds=15
```

**Comment by aravindanr** [comment]
@mignoni the issue does not include the attachment. Can you include the definition and the execution json? Also, please describe your setup. What is the persistence and queue implementation?

**Comment by mignoni** [comment]
@aravindanr 

I updated the issue text and attachmented the source code of workflow the definition (**Simulation-Promotional-def.zip**), JSON of execution that works (**json_works.zip**) and that not works (**json_not_works.zip**).

In section "**Configurations Of Conductor Server**" I puted the details of conductor.

**Comment by mignoni** [comment]
@apanicker-nflx Can you help us?

**Comment by apanicker-nflx** [comment]
@mignoni Thanks for reporting the issue. From the workflow execution graph that you posted above, it looks like all the tasks executed correctly but the task details were not populated? Let me look into the attachments that you have posted and get back to you.

Also, on a sidenote, I see that you are not using the workflow execution lock. This could potentially impact workflow executions. I would recommend enabling the locking mechanism to avoid any potential issues when running at scale.

**Comment by mignoni** [comment]
@apanicker-nflx I will try enable locking mechanism.
