### ISSUE TITLE
Cassandra-persistence: what are the reasons/challenges for not implementating Queue DAO

### ISSUE THREAD

**Issue by Mohit177** [Netflix/conductor#2107]
We are currently in the process of evaluating the design for implementing dynamoDB-persistence DAL for all the DAOs in conductor. Looking at the cassandra-persistence, we want to know what were the challenges or reasons for not implementing the Queue DAO?

@rickfish @apanicker-nflx

**Comment by kishorebanala** [comment]
@Mohit177 Queues in Cassandra is a long discussed topic, and is labelled an anti-pattern: https://www.datastax.com/blog/cassandra-anti-patterns-queues-and-queue-datasets.
