### ISSUE TITLE
How to update the WAIT system task as completed

### ISSUE THREAD

**Issue by sidhique91** [Netflix/conductor#2109]
Kindly help me with a sample on how to update the WAIT system task as completed

**Comment by kishorebanala** [comment]
@sidhique91 There are couple of ways to accomplish this:
1. By registering an [EventHandler](https://netflix.github.io/conductor/configuration/eventhandlers/) that completes this task. Eg: https://netflix.github.io/conductor/labs/eventhandlers/
2. By calling the TaskResource's `/update` endpoint directly.
