### ISSUE TITLE
Postgres v5, v6 DDL, getting error trying to apply them

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#2118]
@mactaggart I am finally getting around to applying the v5, v6 DDL updates for Postgres. I got an error on v5 similar to the below. I made some changes and somehow that later worked but now i am getting this error on v6, wondering if you got same or, if not, why not...seems like I will get this on every table, maybe because it is the primary key?

`org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Migration V6__update_pk.sql failed
----------------------------------
SQL State  : 2BP01
Error Code : 0
Message    : ERROR: cannot drop index unique_queue_name because constraint unique_queue_name on table queue requires it
  Hint: You can drop constraint unique_queue_name on table queue instead.
Location   : db/migration_postgres/V6__update_pk.sql (C:\Users\u447\gitrepos\conductor-dev\postgres-persistence\bin\main\db\migration_postgres\V6__update_pk.sql)
Line       : 8
Statement  : DROP INDEX IF EXISTS unique_queue_name
`

**Comment by rickfish** [comment]
@mactaggart Ah, in my Postgres database I had to drop the constraints as opposed to dropping the indexes. Apparently unique keys are considered as constraints. This wasn't the case for you?

**Comment by rickfish** [comment]
@mactaggart Never mind...I forgot...our Postgres database predates the postgres-persistence module. We had our own persistence module until this one was available. Its DDL used constraints in the create table DDL for primary keys and unique indexes. Sorry, I completely forgot about that.

**Comment by mactaggart** [comment]
@rickfish ah, ok. I think we can close this since I don't see an issue. Thanks.
