### ISSUE TITLE
Multitenancy Support for Condutor

### ISSUE THREAD

**Issue by ssg2526** [Netflix/conductor#2121]
Currently from the conductor code it seems that the conductor supports a single datasource connection. Can we have more than one datasources for the same conductor server. for example if a workflow is being created by a user then based on the tenancy the workflow will get saved in a different schema for MYSQL determined at runtime

**Comment by kishorebanala** [comment]
@ssg2526 This is not supported, however, we're also uncertain about implementing this within Conductor.

One of the ways this can be implemented is by having separate Conductor deployments and use a proxy layer (For eg: [Zuul](https://github.com/Netflix/zuul/wiki)) to direct to relevant deployment as required.
