### ISSUE TITLE
Elasticsearch index setup is called 2 times due to duplicate code in bootstrap Main.java 

### ISSUE THREAD

**Issue by saralaks** [Netflix/conductor#2123]
https://github.com/Netflix/conductor/blob/master/server/src/main/java/com/netflix/conductor/bootstrap/Main.java#L53

Same call is made in line 50 as well in the above code

**Comment by aravindanr** [comment]
Thanks for reporting it. This is addressed in our upcoming 3.0 release. Feel free to create a pull request. We will get to it as soon as we can.
