### ISSUE TITLE
queue name for userdefined task: taskType or taskDefName ?

### ISSUE THREAD

**Issue by BobWang-SIA** [Netflix/conductor#2130]
Hi, I found that the 'QueueUtils.getQueueName(Task)' used taskType to decide the queue name,
but in the client package, the TaskPollExecutor and Worker poll tasks by taskDefName.
So I'm confused. It seems that the server / worker  are not consistent with the queue strategy, so that workers can not fetch tasks
correctly?

**Comment by apanicker-nflx** [comment]
For async system tasks, the queue names are created based on taskType while for simple tasks the queue names are created based on the taskDefName. The conductor server polls for system tasks from the queues by the task types but the poll requests from the client are routed to the queue names by their task def names.

**Comment by BobWang-SIA** [comment]
I'm sorry but could you please show me where the queue names were created based on the taskDefName ?  I only found that the queue name are always decided by  the 'QueueUtils.getQueueName(Task)' , which always create queue by taskType.

**Comment by apanicker-nflx** [comment]
When a SIMPLE task is created, the type is replaced with the task def name - https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/mapper/SimpleTaskMapper.java#L77
