### ISSUE TITLE
conductor.proto.Workflow used instead of GetWorkflowStatusResponse

### ISSUE THREAD

**Issue by andra-sava** [Netflix/conductor#2131]
Hi!  :smiley:
I am trying to integrate Graph QL - Mesh with a gRPC conductor service and I am using the conductor .proto files.
In **workflow_service.proto**, I have noticed that you have used **"conductor.proto.Workflow"** as the response for the GetWorkflowStatus rpc function, even if you have declared GetWorkflowStatusResponse which is not used anywhere. Is there any reason for that, because I have troubles in generating the Graph-QL schema and I would appreciate your point of view.

![image](https://user-images.githubusercontent.com/73701528/111291758-2dde9680-8650-11eb-998d-a6a3db53ec98.png)

Thank you very much!
Best regards, 
Andra

**Comment by apanicker-nflx** [comment]
@andra-sava That looks like a bug and is certainly not expected. Please feel  free to submit a PR with the fix.
