### ISSUE TITLE
v2.31.1 v3.0  RedisClusterJedisProvider Can only get a redis cluster IP bug

### ISSUE THREAD

**Issue by ninyjun** [Netflix/conductor#2132]
//fixed Can only get a redis cluster IP  by ninyjun 462711932@qq.com 2021/03/17
        Set<HostAndPort> hosts = new HashSet<>();
        for(Host h : hostSupplier.getHosts()){
            hosts.add(new HostAndPort(h.getHostName(), h.getPort()));
        }
        //end

**Comment by kishorebanala** [comment]
@ninyjun Not sure I understand the question here. Can you add more details with the expected behavior please?

**Comment by ninyjun** [comment]
A redis(3.0+)  cluster has multiple IP addresses
like this. x.x.x.111:6379;x.x.x.222:6379;x.x.x.333:6379
A redis(3.0+)  cluster has multiple IP addresses
like this   x.x.x.111:6379;x.x.x.222:6379;x.x.x.333:6379


RedisClusterJedisProvider.java

 public RedisClusterJedisProvider(HostSupplier hostSupplier, DynomiteConfiguration configuration) {
        GenericObjectPoolConfig genericObjectPoolConfig = new GenericObjectPoolConfig();
        genericObjectPoolConfig.setMaxTotal(configuration.getMaxConnectionsPerHost());
        Host host = hostSupplier.getHosts().get(0); //////////// only get a redis cluster IP ??? bug???
        this.jedisCluster = new JedisCluster(new redis.clients.jedis.JedisCluster(new HostAndPort(host.getHostName(), host.getPort()),
                                                                                  genericObjectPoolConfig));
    }

**Comment by ninyjun** [comment]
conductor3.0               RedisClusterConfiguration.java
----------------
protected JedisCommands createJedisCommands(RedisProperties properties, ConductorProperties conductorProperties,
        HostSupplier hostSupplier, TokenMapSupplier tokenMapSupplier) {
        GenericObjectPoolConfig genericObjectPoolConfig = new GenericObjectPoolConfig();
        genericObjectPoolConfig.setMaxTotal(properties.getMaxConnectionsPerHost());
       //  Host host = hostSupplier.getHosts().get(0) ; // only get a redis cluster IP ??? bug???

     //fixed
      Set hosts = new HashSet<>();
      for(Host h : hostSupplier.getHosts()){
      hosts.add(new HostAndPort(h.getHostName(), h.getPort()));
      }
        return new JedisCluster(
            new redis.clients.jedis.JedisCluster(hosts, genericObjectPoolConfig));
    }

**Comment by apanicker-nflx** [comment]
@ninyjun Thank you for reporting this. Could you please open a PR with the fix?
