### ISSUE TITLE
About delete the primary key id of the tables

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#2139]
I found the release note `Removed id column from Postgres and MySQL tables, set primary key to existing unique index` in v2.31.0, so i have a question, why delete the primary key id of the tables? what's the reason behind it?

**Comment by mactaggart** [comment]
@andyyumiao The id column wasn't serving any purpose and was set as the PK, therefore the PK was changed to the columns used in the unique indexes.

**Comment by andyyumiao** [comment]
> @andyyumiao The initial motivation for this change was to support sharing in citus for postgres, #1997. The id column wasn't serving any purpose and was set as the PK, therefore the PK was changed to the columns used in the unique indexes.

but if someone has deployed conductor in the production environment, can this change be compatible with the previous version? and will the previous workflow and task data be affected?

**Comment by skycubed** [comment]
@andyyumiao Yes, upgrading is backward compatible. Conductor uses database migrations when upgrading. If you have a previous version of conductor deployed a migration will handle making the necessary database modifications.

**Comment by mactaggart** [comment]
@andyyumiao Yes, this update is backward compatible. Conductor uses database migrations for upgrading. If you have an older version of Conductor deployed, a database migration will make the necessary database modifications.
