### ISSUE TITLE
 Task with name 'postRelease' not found in root project 'conductor'

### ISSUE THREAD

**Issue by RobinzhangPRO** [Netflix/conductor#2140]
zf@LAPTOP-4VS2EBU4 MINGW32 /d/web/mirrors-netflix-conductor-master/netflix-conductor/server
$ ../gradlew server

> Configure project :
Git repository not found at D:\web\mirrors-netflix-conductor-master\netflix-cond
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\web\mirrors-netflix-conductor-master\netflix-conductor\build.gradle' line: 13

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '9.3.0']
> Failed to apply plugin class 'nebula.plugin.netflixossproject.publishing.PublishingPlugin'.
   > Task with name 'postRelease' not found in root project 'conductor'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s

**Comment by apanicker-nflx** [comment]
What is the gradle version that you are using? We recommend using the gradle wrapper that is packaged within the project so that it is compatible with the versions of the plugins used.

**Comment by cdzhek** [comment]
Hello @RobinzhangPRO . Were you able to solve this problem? 
If yes, could you share your solution please.

**Comment by apanicker-nflx** [comment]
@cdzhek Please ensure that you are using the gradle wrapper packaged within the project.

**Comment by oryde** [comment]
I get the same error when building docker images on Windows with `docker-compose build`. How do I specify to use the packaged gradle wrapper in this case?
```
=> ERROR [builder 4/4] RUN ./gradlew build -x test                                                               44.8s
------
 > [builder 4/4] RUN ./gradlew build -x test:
#12 0.771 Downloading https://services.gradle.org/distributions/gradle-6.8.3-bin.zip
#12 1.738 ..........10%..........20%..........30%...........40%..........50%..........60%..........70%...........80%..........90%..........100%
#12 12.33
#12 12.33 Welcome to Gradle 6.8.3!
#12 12.33
#12 12.33 Here are the highlights of this release:
#12 12.33  - Faster Kotlin DSL script compilation
#12 12.33  - Vendor selection for Java toolchains
#12 12.33  - Convenient execution of tasks in composite builds
#12 12.33  - Consistent dependency resolution
#12 12.33
#12 12.33 For more details see https://docs.gradle.org/6.8.3/release-notes.html
#12 12.33
#12 12.42 Starting a Gradle Daemon (subsequent builds will be faster)
#12 41.82
#12 41.82 > Configure project :
#12 41.82 Git repository not found at /conductor -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a different directory.
#12 42.12
#12 42.12 FAILURE: Build failed with an exception.
#12 42.12
#12 42.12 * Where:
#12 42.12 Build file '/conductor/build.gradle' line: 19
#12 42.12
#12 42.12 * What went wrong:
#12 42.12 An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '9.2.2']
#12 42.12 > Failed to apply plugin class 'nebula.plugin.netflixossproject.publishing.PublishingPlugin'.
#12 42.12    > Task with name 'postRelease' not found in root project 'conductor'.
#12 42.12
#12 42.12 * Try:
#12 42.12 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
#12 42.12
#12 42.12 * Get more help at https://help.gradle.org
#12 42.12
#12 42.12 BUILD FAILED in 41s
#12 42.22
#12 42.22 Publishing build scan...
#12 42.92 https://gradle.com/s/pqbhsb3rm6bfk
#12 42.92
------
executor failed running [/bin/sh -c ./gradlew build -x test]: exit code: 1
ERROR: Service 'conductor-server' failed to build : Build failed
```

**Comment by uakihir0** [comment]
Hi.
Have you downloaded the zip file and extracted it to build it? In my case, I did `git clone` and it built fine.

**Comment by bedo2405** [comment]
Cloning solved it for me too, thanks for the tip

**Comment by willrockss** [comment]
Cloning helps! 
But it is blowing my mind O_o Why running build from unpacked sources causes that strange issue?
