### ISSUE TITLE
JSON reshaped to k=v  

### ISSUE THREAD

**Issue by CHURLZ** [Netflix/conductor#2142]
When passing in a json object (outputted from another task), conductor reshapes my object to `k=v` such that the following input:

```json
"echo ${workflow.input.config}"
```

yields the following output:

```
data=value
```
rather than 

```json
{
  "data":"value"
}
```

The echo command is ran as part of a custom task. Is there a way to configure Conductor to retain the JSON shape of the original output?

**Comment by aravindanr** [comment]
Can you share the workflow input and the workflow definition? Conductor does not (rather should not) alter the input in any way. Also, what language is this custom task worker written in. it is possible the object representation of the "input" in that language is altering the format.

**Comment by aravindanr** [comment]
This is probably the same issue as #2071 . The JSONPath library that Conductor uses for json interpolation does not support this.

**Comment by CHURLZ** [comment]
Thanks @aravindanr ! It was indeed an issue from stringifying the payload and sending as a string command to our docker based worker.
