### ISSUE TITLE
searchObjectIds method in ES gets the whole document which is not efficient

### ISSUE THREAD

**Issue by saralaks** [Netflix/conductor#2146]
Following method can cause 'org.apache.http.ContentTooLongException' since it fetches the actual document content in addition to ids.  For error details, refer to this [article](https://stackoverflow.com/questions/51020646/org-apache-http-contenttoolongexception-entity-content-is-too-long-105539255).

https://github.com/Netflix/conductor/blob/e328b5636b06268445a68fe51de87445b23c8560/es5-persistence/src/main/java/com/netflix/conductor/dao/es5/index/ElasticSearchRestDAOV5.java#L709

**Solution**:  Use this setting to not include the source.  With this, API returns only ids.  Issue applies to both ES5 and ES6
        `searchSourceBuilder.fetchSource(false);`

**Comment by apanicker-nflx** [comment]
@saralaks Thank you very much for reporting this. This would definitely be an enhancement to the search APIs. We will look into fixing this in 3.0, which uses ES6 by default.

If you wish to use in ES5, please feel free to open a PR with the fix against the 2.31 branch and we will merge and release.
