### ISSUE TITLE
About ES Credentials issue

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#2147]
**1.ES7 certificate username and password default value**
For ElasticSearch7 module, the `DEFAULT_ELASTIC_SEARCH_BASIC_AUTH_USERNAME` and `DEFAULT_ELASTIC_SEARCH_BASIC_AUTH_PASSWORD` in class `ElasticSearchConfiguration` should be null, or else, the verification in this class `ElasticSearchRestClientBuilderProvider` will not take effect, it is judged that the certificate does not exist when username and password is null.

**2.Certificate support for ES5 and ES6**
May be the current ES5 and ES6 also need to introduce the certificate verification function, it is not available now, just by modifying these two classes `ElasticSearchConfiguration` and `ElasticSearchRestClientBuilderProvider` should be ok.

**Comment by apanicker-nflx** [comment]
@heinrichcohn Could you please help with these questions?

**Comment by andyyumiao** [comment]
> @heinrichcohn Could you please help with these questions?

@apanicker-nflx @heinrichcohn I have just submit a PR for it, pls help to evaluate and check it. [https://github.com/Netflix/conductor/pull/2204](url)
