### ISSUE TITLE
Compatibility with python 3.x

### ISSUE THREAD

**Issue by guyeng0** [Netflix/conductor#215]
At the moment the python client code is compatible with python 2.7. I've looked and it seems this is limited to adding parenthesis around print functions and replacing the thread package with the threading package in ConductorWorker.py.

If you wish I can create a pull request with the relevant changes.

**Comment by v1r3n** [comment]
@guyeng0 will be happy to review and accept the PR if you have a 3.x compatible client.

**Comment by seenureddy** [comment]
@v1r3n Will it support for python3.x?
