### ISSUE TITLE
Add task reference name to TaskSummary

### ISSUE THREAD

**Issue by hs-petko** [Netflix/conductor#2150]
Could the task reference name be added to [TaskSummary](https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/run/TaskSummary.java) returned by [task search](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/service/TaskService.java#L203)?

Our use case is that we are adding some metadata as static inputs to tasks to group them for reporting reasons and use that to get the task processing times by category at the end of the workflow. Some of the tasks and sub-workflows have large inputs/outputs though (stored externally) so we'd like to avoid retrieving those to get this metadata from there. Instead we'd like to get only the workflow definitions and the tasks' start/end times to achieve this. But currently it is not possible to uniquely identify the tasks returned by the search in the definitions as only the workflow name is returned under [workflowType](https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/run/TaskSummary.java) but not the task reference name.

**Comment by charybr** [comment]
Hi @hs-petko, how was this issue addressed ?
Was referenceTaskName attribute added?

**Comment by hs-petko** [comment]
Hi @charybr, I don't remember for sure but I think we just changed the implementation on our end, so that we don't need this.
