### ISSUE TITLE
Kafka + Netflix conductor

### ISSUE THREAD

**Issue by nicoSalsa** [Netflix/conductor#217]
Hello,

I want to know if there is an easy way to connect Kafka and Netflix Conductor?
At now, it seems to work only with Amazon SQS.
Moreover, it seems that it is only possible to make one action by task.
Is there a way to execute more than one action by task?

Thanks in advance,

**Comment by v1r3n** [comment]
@nicoSalsa 
1) Support for Kafka can be added similar to how SQS is done. 
2) Each task today runs only action -  that is by design.

**Comment by pouledodue** [comment]
@nicoSalsa did you implement it? I want Kafka + Conductor too
