### ISSUE TITLE
/api/workflow/{workflowId} endpoint not working in swagger

### ISSUE THREAD

**Issue by komatiraju032** [Netflix/conductor#2174]
**Describe the bug**
Get  the workflow by id(/api/workflow/{workflowId}) endpoint is not working 

**To Reproduce**
1. Go to 'http://<conductor_ip>:8080/swagger-ui/index.html?configUrl=/api-docs/swagger-config'
2. Click on '/api/workflow/{workflowId}' endpoint. It's not working. When I click on it page is stuck (not responding)

**Expected behavior**
It should give the response with workflow details of given workflow id.

**Screenshots**

![Screenshot (5)](https://user-images.githubusercontent.com/22415463/114668334-3cd36a00-9d1e-11eb-82ec-c7aad1e8bef3.png)

**Additional context**

**Comment by apanicker-nflx** [comment]
@komatiraju032 What type of persistence layer are you using? Do you see any errors in the server logs?

**Comment by komatiraju032** [comment]
@apanicker-nflx I am using default configuration(docker-compose.yml). And For your information endpoint is working from postman.

**Comment by maheshyaddanapudi** [comment]
No errors observed but the issue happens only in Swagger UI. I have opened a discussion thread https://github.com/Netflix/conductor/discussions/2192

**Comment by komatiraju032** [comment]
@apanicker-nflx  I have find it's not working because of this issue https://github.com/OAI/OpenAPI-Specification/issues/822

**Comment by maheshyaddanapudi** [comment]
@komatiraju032 is there any specification for a work around it different way to configure ? I couldn't directly find any in their Read Me. I'll explore too.

**Comment by komatiraju032** [comment]
@maheshyaddanapudi  I found one more related issue on stackoverflow https://stackoverflow.com/questions/35605427/swagger-ui-freezes-after-api-fetch-and-browser-crashes

**Comment by aravindanr** [comment]
@komatiraju032 we believe its because of the `com.google.protobuf.Any` type that the `inputMessage` and `outputMessage` fields in `Task` class. Excluding those fields in Swagger definition should solve the issue. We will get to it  asap.

**Comment by komatiraju032** [comment]
@aravindanr I have fixed the issue with the information you have provided. I also created a PR #2210

**Comment by aravindanr** [comment]
Thanks @komatiraju032 . I left a minor comment in the PR.
