### ISSUE TITLE
Workflow UI not showing the workflows

### ISSUE THREAD

**Issue by komatiraju032** [Netflix/conductor#2175]
**Describe the bug**
Workflow ui not showing the workflows.

**To Reproduce**
1. Start the workflow  by making a POST request to '/api/workflow' endpoint 
2. Open the conductor ui 'http://conductor_ip:5000. Now select the any category(All, Running, etc..) in **Executions** tab. It's not showing any workflows. 

**Expected behavior**
It should show all the workflows .

**Screenshots**

**Additional context**

**Comment by apanicker-nflx** [comment]
@komatiraju032 Did you enable the indexing layer? The UI needs indexing layer to display results. Can you verify if the API returns results?

**Comment by maheshyaddanapudi** [comment]
This property is not enabled by default in the docker/server/config/config.properties and hence even though the elasticsearch url is provided, the workflow execution history is not being returned by the search API.

conductor.indexing.enabled=true

Added this in the PR https://github.com/Netflix/conductor/pull/2188

Of course, the same has to be set manually while running Conductor standalone (or a non-docker setup). It can be passed in the run command "java -Dconductor.indexing.enabled=true -jar conductor-boot.jar" or through a properties file.

**Comment by komatiraju032** [comment]
@maheshyaddanapudi but it's working for conductor v2 without that property

**Comment by maheshyaddanapudi** [comment]
> @maheshyaddanapudi but it's working for conductor v2 without that property 

Yes.

There is switch from 2.X to 3.X which has many changes like Framework being used now is Spring Boot, the embedded Elasticsearch is no longer supported etc.

As a part of these changes, few properties for updated / added.

**Comment by apanicker-nflx** [comment]
@maheshyaddanapudi Thanks for the response. Your observation and workarounds are correct.

@komatiraju032 We are working on merging #2206 soon and hopefully this will alleviate any issues with getting the server up and running.

**Comment by supriya-mallikarjuna** [comment]
@sudouser777  conductor UI not showing the workflows which are running

**Comment by jegadjame** [comment]
> Of course, the same has to be set manually while running Conductor standalone (or a non-docker setup). It can be passed in the run command "java -Dconductor.indexing.enabled=true -jar conductor-boot.jar" or through a properties file.

I am running Conductor standalone (or a non-docker setup) in Windows machine. I run command "java -Dconductor.indexing.enabled=true -jar conductor-boot.jar" .. I am getting this error

![image](https://user-images.githubusercontent.com/5119603/184889328-53e38a26-8769-4a21-845b-497486e767f4.png)
