### ISSUE TITLE
Task stuck at SCHEDULED state when on redis clustering mode

### ISSUE THREAD

**Issue by hvishal44** [Netflix/conductor#2177]
I'm providing clustered redis as db, and whenever a workflow is created, tasks inside the workflow are stuck at SCHEDULED state, while syncing of tasks and workflow defs between 2 conductor instances are working fine.
Checked on polling part and seems fine for that task.

Verifying logs:
Only few logs are visible when workflow is started :

`273641 [qtp1801709229-92] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: DECISION
273641 [qtp1801709229-92] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: FORK
273642 [qtp1801709229-92] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: JOIN
273642 [qtp1801709229-92] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: EXCLUSIVE_JOIN
273642 [qtp1801709229-92] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: DO_WHILE
`

Below are the configuration for redis.

`db=redis_cluster`
`workflow.dynomite.cluster.hosts=10.0.14.42:6001:us-east-1ci;10.0.14.43:6001:us-east-1ci`
`workflow.dynomite.cluster.name=redis_cluster_custom`

Netflix conductor version : 2.29.0

**Comment by hvishal44** [comment]
I even tried redis sentinel and configured sentinel hosts in configuration, problem seems to be not solved.

**Comment by apanicker-nflx** [comment]
@hvishal44 Can you please test this out with version 3.+ ? What queueing implementation are you using?

**Comment by hvishal44** [comment]
Sure will try with 3.+, Thanks for suggestion.
We are using default queuing implementation, we have not configured or changed the queue configuration.

**Comment by franz040187** [comment]
> Sure will try with 3.+, Thanks for suggestion.
> We are using default queuing implementation, we have not configured or changed the queue configuration.

Hi @hvishal44, have you solved with new version? I have a similar issue with event handlers (they stuck in WAIT task and they cannot be resumed), i think this can be a queues issue that are not pop some events/messages. Thanks

**Comment by hi-zjh** [comment]
same problem with 3.0.1, redis cluster

**Comment by hvishal44** [comment]
Yes @franz040187 , tried with 3.+, didnt solve the problem.

**Comment by hi-zjh** [comment]
> same problem with 3.0.1, redis cluster
createSubdomain_vivoops-dns (SCHEDULED)
log：No Task available for the poll: /tasks/poll/createSubdomain_vivoops-dns?vivoops-dns-pre-10-209-10-4.v-bj-4.vivo.lan&null

**Comment by hi-zjh** [comment]
https://github.com/Netflix/conductor/issues/1287#issuecomment-529289190
this issue explain to how to solve this problem

**Comment by apanicker-nflx** [comment]
@hi-zjh thank you.
This is a limitation of dyno-queues and the linked comment above explains it.
