### ISSUE TITLE
General Multi-Task Workers, and General Task Polling?

### ISSUE THREAD

**Issue by dcompgriff** [Netflix/conductor#218]
So, most of the documentation shows each worker having its own 'task type'. Is there any way to set up workers that can handle any, or a specified subset of task types? Also, is there a way then to simply query for the next task ready for processing in the Orchestrator's queues?

The main use case I have is this:
There are (very) many services that I want the orchestration's workers to call, each of which have a different amount of running time. Instead of trying to create a worker for each service (where each service is mapped to a task), I'd like to have general workers that can handle any general task, such that tasks are distributed between all workers.

Is there some other way this might work using the current Orchestrator's setup? Or, is there any issue preventing this from being added as a feature?

**Comment by sameekb** [comment]
The project conductor-client has a class, **WorkflowTaskCoordinator** which polls for Worker input data in addition to other tasks like Task Worker thread pool management etc. Before polling for input data, the Worker instances have to be registered with the WorkflowTaskCoordinator object. Worker instance is  created by passing the unique Task Definition name to its constructor. Pls refer to the below code snippet:

```
TaskClient taskClient = new TaskClient();
taskClient.setRootURI("http://localhost:8080/api/");//Point this to the server API
int threadCount = 1; //number of threads used to execute workers. To avoid starvation, should be same or more than number of workers

Worker worker = new TaskWorker(“task_1");
Worker worker1 = new TaskWorker("task_2");
//Create WorkflowTaskCoordinator
WorkflowTaskCoordinator.Builder builder = new WorkflowTaskCoordinator.Builder();
WorkflowTaskCoordinator coordinator = builder.withWorkers(worker,worker1)
								  .withThreadCount(threadCount)
								  .withTaskClient(taskClient).build();
//Start for polling and execution of the tasks
coordinator.init(); 
```

In your case, you can create multiple instances of the same Worker class by passing different task definition names provided the single Worker class is implemented to handle the input data meant for all the tasks it has been initiated for.  

WorkflowTaskCoordinator.Builder.withWorkers accepts Varargs.
