### ISSUE TITLE
Extending conductor with cassandra.

### ISSUE THREAD

**Issue by rpdeshmukh** [Netflix/conductor#220]
I am trying to extend conductor with a cassandra backend to persist workflows and tasks. I found the "Extending Conductor" section that mentions about implements the Dao's. However, when I start the conductor server I'm not sure what the db property in conductor properties should be.

I tried to set value as cassandra but it seems to accept only memeory, redis and dynomite and I get this error.

$ java -jar -DloadSample=true conductor-server-1.7.4-all.jar gts/conductor.properties
Using gts/conductor.properties
0    [main] ERROR com.netflix.conductor.server.ConductorServer  - Invalid db name: cassandra, supported values are: redis, dynomite, memory

I found that the ConductorServer has an enum with these three values and it throws the error for any value of DB.

Is there more documentation on how this can be achieved?

**Comment by v1r3n** [comment]
@rpdeshmukh You will have to add new persistence classes to store the data into Cassandra.
After you are done with it, you can wire up the guice modules to load cassandra DAOs as opposed to Redis/Dynomite.  This will prob. need some code changes - minor though and one more condition in the property loader that validates the db name.

Hope this helps.

**Comment by manudilipshah** [comment]
@codediffusion Were you able to achieve the integration?

**Comment by codediffusion** [comment]
@manudilipshah .. no I did not carry on with it further. I was in the process of evaluating conductor. Unfortunately did not carry on further with the integration. I would let you know if I get back to it and would also be interested if you manage to get it working.

**Comment by manudilipshah** [comment]
@codediffusion I will let you know if I get it working
