### ISSUE TITLE
Detecting Change status tasks

### ISSUE THREAD

**Issue by nicoSalsa** [Netflix/conductor#221]
Hello,

I'm working about a java class which implements a workflow in Netflix Conductor.
I need to detect when the status of a task change to generate a diary.
Is there a simply interface to implement with a method like "OnChangeTask" for example?

Thanks in advance

**Comment by v1r3n** [comment]
@nicoSalsa currently, there are no events/notification on the task status change.

**Comment by kushalhalder** [comment]
@v1r3n 
Hi, are the task execution details always exported to ElasticSearch for all kinds of persistence configurations?
