### ISSUE TITLE
Dynamic name of field TaskReferenceName

### ISSUE THREAD

**Issue by nicoSalsa** [Netflix/conductor#223]
Hello,

It seems not possible to make field TaskReferenceName dynamic, which could be really helpfull.
For example, i would like something like  this:

{
  "name": "sub_workflow_claim",
  "description": "A simply wait external workflow",
  "version": 1,
  "tasks": [
    {
      "taskReferenceName": "${workflow.input.motif}_order_start",
      "name": "Order_start",
      "type": "SIMPLE",
      "startDelay": 0
    },
    {
      "taskReferenceName": "${workflow.input.motif}_order_end",
      "name": "Order_end",
      "type": "SIMPLE",
      "startDelay": 0
    }
  ],
  "schemaVersion": 2
}

Regards,

**Comment by v1r3n** [comment]
Could you provide some more context on why the reference name needs to be dynamic, can the same be achieved with static reference name?

**Comment by nicoSalsa** [comment]
If we take the example of a claim in a bank. It may concern a lot of things (problem of cash, credit card, bank transfer...)
There are a lot of cases.
For each case, i need to make an endpoint call to trigger external workflow.
This call depends on the reason of the claim and i would like to see quickly and easily, on my workflow's design, the reason of the claim.
I think that making dynamical the field "TaskReferenceName" may be a good solution.
Maybe you will say me to make a decision task but there are really too many cases to design it.

**Comment by mashurex** [comment]
Isn't `taskReferenceName` supposed to be globally unique? @v1r3n can likely correct this, but I have understood it to be the specific reference to a given step in a workflow definition. If you want to reuse the same step over and over, you'd have different `taskReferenceName` values but the same `name` value, as the `name` refers to the `TaskDef` that has the blueprint for the given task you're trying to re-use.

Sounds like you could register your own `WorkflowSystemTask` and `WorkflowTask` definition, pass the variable in as an input parameter, and have your custom `WorkflowSystemTask` run the logic for making a call to the external workflow based off your own rules.

You could then back that with a dynamic task based off the output of your custom task so it will run the correct `Order_end` task logic that you want.
