### ISSUE TITLE
[BUG]: Task acknowledgment not consumed by Conductor posted by a Custom Worker

### ISSUE THREAD

**Issue by Sujay008** [Netflix/conductor#2252]
**Bug :** Task acknowledgement triggered by custom worker (SIMPLE) was not consumed by conductor and this is observed during a simple Performance execution

**Impact of Bug** : Task remained in InProgress status and Conductor moved the workflow to Completed status.

**Pre-requisites** - Conductor version is 2.30.3.  A workflow calling a sub-workflow where sub-workflow performs custom tasks consumed and processed by Custom worker.

**To Reproduce**
1. Have a Workflow with sub-workflow, where sub-workflow will have custom tasks
2. Do run the same workflow for multiple iterations
3. In few of the iterations, Worker posted an acknowledgement to Conductor
4. Conductor ignore or missed the acknowledgement sent by Worker
5. Task is in InProgress status and workflow is in Completed status

**Comment by apanicker-nflx** [comment]
@Sujay008 There were a couple of edge cases with regards to updating the subworkflow status and subworkflow task status in parent workflow which we identified and fixed as part of the 3.0 release. These fixes were made in #2125 . 

We strongly recommend upgrading to the newest stable version which simplifies and fixes the subworkflow execution path.
