### ISSUE TITLE
[BUG]: The method waitForHealthyCluster of calss ElasticSearchRestDAOV6 causes a timeout with a stand-alone Elasticsearch

### ISSUE THREAD

**Issue by evgvain** [Netflix/conductor#2262]
**Describe the bug**
The method waitForHealthyCluster of calss ElasticSearchRestDAOV6 causes a timeout since stand-alone Elasticsearch has status "yellow". This status is expected for the  stand-alone Elasticsearch to indicate that the primary shard is allocated but replicas are not.

**To Reproduce**
config.properties is unchanged:

conductor.indexing.enabled=true
conductor.elasticsearch.url=http://es:9200
conductor.elasticsearch.indexName=conductor

restat the server docker after Elasticsearch indexes are modified

**Expected behavior**
I suggest setting default value of clusterHealthColor to "yellow" to prevent the timeout.

**Comment by kishorebanala** [comment]
@evgvain We discussed and decided not to change the default to `yellow`. However, you can override this property in your local: https://github.com/Netflix/conductor/blob/main/es6-persistence/src/main/java/com/netflix/conductor/es6/config/ElasticSearchProperties.java#L42

**Comment by lakeoffaith** [comment]
i get the same problem  two days before, so i start  es cluster on my computer.

**Comment by kishorebanala** [comment]
@whitmell Which version of Conductor are you using? In 3.x, [Conductor Properties](https://github.com/Netflix/conductor/blob/main/core/src/main/java/com/netflix/conductor/core/config/ConductorProperties.java) is a good start.
