### ISSUE TITLE
[BUG]: Modified mysql migration files cause migration failure

### ISSUE THREAD

**Issue by evgvain** [Netflix/conductor#2263]
**Describe the bug**
Modified mysql migration files cause migration failure since old files were changed. The migration process verifies the checksum of previous migration and fails in case of a mismatch.
 
**To Reproduce**
1. Configure mysql percipience
1. Build docker from v2.26.0 and run 
2. Build docker from v2.27.0 and run - migration happen for the 1st time
3. Build docker from v3.0.4 and run - migration will fail because V1__initial_schema.sql  is changed (copyright notice was added)

**Comment by michaelpaliy** [comment]
Hi,
Duplicate of #2197
You can find the solution at: https://github.com/Netflix/conductor/issues/2197#issuecomment-829519429

**Comment by aravindanr** [comment]
@evgvain Did the above comment fix the issue?

**Comment by aravindanr** [comment]
#2263 fixes this issue.
