### ISSUE TITLE
[BUG]:  http task fails with "Read timed out" or invalidMediaTypeException

### ISSUE THREAD

**Issue by mummoo** [Netflix/conductor#2269]
**Describe the bug**

HTTP task (post request) fails with    "Read timed out". 
When I add readTimeOut with a some value, it fails with another error:

"reasonForIncompletion": "Failed to invoke HTTP task due to: org.springframework.http.InvalidMediaTypeException: Invalid mime type \"application/json, application/json\": Invalid token character ',' in token \"json, application/json\",

**To Reproduce**
I just have one task in a workflow. This task is a HTTP task, and does a post call to an endpoint which is returns after few seconds.

```
Workflow Def:

{
          name: "workflow_1",
          description: "workflow_1"",
          ownerEmail: "email@A.com",
          version: 1,
          schemaVersion: 2,
          tasks: [{
            name: "task_1",
            taskReferenceName: "task_1",
            timeoutSeconds: 60000,
            responseTimeoutSeconds: 60000,
            inputParameters: {
              http_request: {
                uri: "http://localhost:5000/endpoint",
                method: "POST",
                contentType: "application/json",
                accept: "application/json",
                connectionTimeOut: 60000,
                //readTimeOut: 60000, 
                body: {
                  id: "1234"
                }
              }
            },
            type: "HTTP"
          }]

Task Def:
{
          name: "task_1",
          taskReferenceName: "task_1",
          retryCount: 0,
          retryLogic: "FIXED",
          retryDelaySeconds: 30,
          timeoutSeconds: 60000,
          timeoutPolicy: "TIME_OUT_WF",
          responseTimeoutSeconds: 60000,
          ownerEmail: "email@A.com"
}
```

**Expected behavior**

When HTTP task is executed in the workflow, either I hit "Read timed out" or ""Failed to invoke HTTP task due to: org.springframework.http.InvalidMediaTypeException: Invalid mime type \"application/json, application/json\": Invalid token character ',' in token \"json, application/json\""

I am expecting that task would wait for POST to return (takes few seconds), and finish the workflow successfully. Workflow 
status is always FAILED.

When I do a curl on this endpoint, it takes few seconds, and responds with the result. I am also new to conductor!

**Comment by aravindanr** [comment]
From the exception message, it looks like the endpoint is returning an incorrect MIME type in the `Content-Type` header, "application/json, application/json". When you run curl, you can use the `-v` flag to see the "Content-Type". Since the type is incorrect, Conductor is unable to parse the request.

**Comment by mummoo** [comment]
Yes, the curl response has a malformed header. We can close the issue. Thanks for the quick response.
