### ISSUE TITLE
How to implement/use workflowStatusListner

### ISSUE THREAD

**Issue by snoopakon** [Netflix/conductor#2281]
I'm using Netflix Conductor over Rest API. I'm able to create a workflow and run it but I would like to know how to use the WorkflowStatusListener feature.

While registering workflow definition I set workflowStatusListenerEnabled = true. Not sure how to use conductor.additional.modules for conductor-server-all-3.0.0.jar

Please note that I am using a conductor-server-all-3.0.0.jar to up the conductor.

**Comment by apanicker-nflx** [comment]
@snoopakon The documentation might be a little outdated w.r.t the current release version of Conductor. We are working on an updated version currently. 

For implementing your own WorkflowStatusListener, you can follow one of these [implementations](https://github.com/Netflix/conductor/tree/main/contribs/src/main/java/com/netflix/conductor/contribs/listener) as references. You can choose to enable either of these for your use-case using configuration or you can implement your own listener and add it to the classpath.


_PS: Please do not create issues for questions. Use the [discussion forum](https://github.com/Netflix/conductor/discussions) instead!_
