### ISSUE TITLE
[BUG]: operationIds are not unique

### ISSUE THREAD

**Issue by abrezuica** [Netflix/conductor#2292]
Some operationIds have the same name, for example:

![searchWf](https://user-images.githubusercontent.com/59456269/120986130-efef9b00-c784-11eb-8ea2-0409064b20b9.PNG)

![searchTasks](https://user-images.githubusercontent.com/59456269/120986155-f4b44f00-c784-11eb-90be-8a120f9ee607.PNG)

As far as I know, operationIds must be unique among all operations described in the API.

This issue is kind of messing with our implementation, because some endpoints are being ignored in our GraphQL schema due to duplicate operationIds and we cannot access all the data we need.

Thank you

**Comment by apanicker-nflx** [comment]
The operations Ids that you have linked above are from different routes, viz. `/workflow/search` and /tasks/search`. This does not seem like a bug
