### ISSUE TITLE
[BUG]: The Subworkflow Completes Even Though The Latest Task Is Scheduled

### ISSUE THREAD

**Issue by OguzhanUlucay** [Netflix/conductor#2297]
**Describe the bug**
We using Conductor v2.30 with Elastic Search and Redis. We encountered that the subworkflow that inside a fork joins finished even though the the latest task is in scheduled state. The minor detail in here is the latest task is fixed interval retryable task with 30 min delays. At some of time this situation occurs. The occurance seems random, sometimes it happens when this task is re-scheduled for 27th times sometimes when it re-scheduled for 141th time.

**To Reproduce**
1. Prepare a a main workflow and call a subworkflow inside the put fork join.
2. Prepare the subworkflow as described at above. A optional task, a decide task and later on a retryable task.
3. Run the master workflow. If wanted the task's retry time can be done 1 sec rather then waiting long period.

**Expected behavior**
The latest task should have continued to be executed until it successfully completed.

**Screenshots**
Main workflow:
![image](https://user-images.githubusercontent.com/20965786/121385893-321a0780-c952-11eb-937e-4a0a23c9b90b.png)

Subworkflow:
![image](https://user-images.githubusercontent.com/20965786/121387219-309d0f00-c953-11eb-80ad-69289be55b57.png)

**Additional context**
If the optional task is also retryable task but exponential one. If it completes then the retryable task is not executed. The optional task and the retryable task are kind of clone tasks. Both have got same inputs and outputs. The subworkflow excpected to have output either the optional task or the retryable task depending on which finishes.

**Comment by kishorebanala** [comment]
Please take a look at this [comment](https://github.com/Netflix/conductor/issues/2117#issuecomment-865409050) from similar issue. 

If possible, please consider upgrading to 3.x for latest changes.
