### ISSUE TITLE
Purpose of Elasticsearch as indexing backend

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#23]
Just for better understanding...

What exactly is the purpose of the Elasticsearch backend?
Is the content written to Elasticsearch in any way read again and reused by Conductor Server and its state-machine?

Or are all state-machine activities handled soleley via Dynomite? That would mean that Elasticsearch is kind of a "logging archive" for admins?

Thanks for clarification.

**Comment by v1r3n** [comment]
Elasticsearch is used to log all the workflow executions and task executions.  The main purpose is to be able to search for executions with specific string/payload details.  e.g. find all the workflows that were executed with a specific payload as input/output.

Elasticsearch is used only for the search, state machine activities are handled completely by Dynomite.

**Comment by blueelephants** [comment]
Many thanks for clarification
