### ISSUE TITLE
[BUG]: The table structure is not created automatically when starting conductor server using postgres

### ISSUE THREAD

**Issue by leissen** [Netflix/conductor#2301]
**Describe the bug**
I use postgres as the persistent store and created a database for conductor server. But the table structure is not created automatically when starting conductor server. The table structure is created automatically if I use mysql as the persistent store. 
Is there any configuration I missed? The jdbc properties are correct. Because the conductor server could start successfully after I ran the sql files to create table structure manually.

db=postgres
jdbc.url=jdbc:postgresql://localhost:5432/conductor
jdbc.username=postgres
jdbc.password=xxxxxxxx
conductor.postgres.connection.pool.size.max=10
conductor.postgres.connection.pool.idle.min=5

**Expected behavior**
The table structure should be created automatically when starting conductor server like mysql.

**Comment by aravindanr** [comment]
Please provide the Conductor version that you are using and check if `flyway.enabled` is set to `false`. Do you see any errors in the logs? If yes, include them as well.
