### ISSUE TITLE
Is there any Task status listener for Completion and Failure of system task?

### ISSUE THREAD

**Issue by User-Nikita** [Netflix/conductor#2326]
### Discussed in https://github.com/Netflix/conductor/discussions/2322

<div type='discussions-op-text'>

<sup>Originally posted by **User-Nikita** June 18, 2021</sup>
**Is there any Task status listener in Conductor just like a workflowStatusListener?** 
If yes, please guide me how to use it.
Details about my question-
In my workflow definition, **all tasks are System tasks.** 
I am using Java program for handling the workflow.
I want to **give notification to Java program** about status of each System task in workflow.
How can I solve this problem?

Thank you in advance.. </div>

**Comment by aravindanr** [comment]
Continued in #2322
