### ISSUE TITLE
[QUESTION]: In Fork if one task is failing all will fail automatically. How we can avoid it.

### ISSUE THREAD

**Issue by bhawani021** [Netflix/conductor#2337]
Fork

A.      D.    G
B.      E.    H
C.     F.      I

    JOIN -> C, F, I

Let's say task Task A,  D, G are in execution and task G failed but it will show A and D also as failed.

If G  failed then A, B, C should continue in  execution 
and D E F should also continue in execution.

**Comment by kishorebanala** [comment]
Hey @bhawani021, This is not supported today. One option is to mark all the forked tasks as optional. But, in your example above, H & I will also be executed, after G fails, if marked optional.

Another option is to put each branch in a sub workflow, and handle the failures within subworkflow, without affecting other subworkflows.

If you think Fork should handle this in a better way, please open a [discussion](https://github.com/Netflix/conductor/discussions) with your ideas. Also, please ask your questions in the [discussion forum](https://github.com/Netflix/conductor/discussions). Thanks!

**Comment by bhawani021** [comment]
@kishorebanala 
need your help in understanding if I am putting in subworkflow like

```
Fork

SubWf1                |    SubWf2                |   SubWf3
(Task: A, D, G)    |   (Task: B, E, H)      |  (Task: C, F, I)

Join (SubWf1, SubWf2, SubWf3)
```

What if sub-workflow SubWf3 failed? will SubWf1 and SubWf2 continue to execute?

**Comment by maheshyaddanapudi** [comment]
> @kishorebanala
> need your help in understanding if I am putting in subworkflow like
> 
> ```
> Fork
> 
> SubWf1                |    SubWf2                |   SubWf3
> (Task: A, D, G)    |   (Task: B, E, H)      |  (Task: C, F, I)
> 
> Join (SubWf1, SubWf2, SubWf3)
> ```
> 
> What if sub-workflow SubWf3 failed? will SubWf1 and SubWf2 continue to execute?

Ideally yes.

Could you please provide a sample workflow def ? I will try replicating the issue.

**Comment by apanicker-nflx** [comment]
Continuing discussion in #2346
