### ISSUE TITLE
[QUESTION]: I found this error when i build version 2.31

### ISSUE THREAD

**Issue by rukter** [Netflix/conductor#2359]
#12 43.58 Starting a Gradle Daemon (subsequent builds will be faster)
#12 117.3
#12 117.3 > Configure project :
#12 117.3 Git repository not found at /conductor -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a different directory.
#12 117.6
#12 117.6 FAILURE: Build failed with an exception.
#12 117.6
#12 117.6 * Where:
#12 117.6 Build file '/conductor/build.gradle' line: 15
#12 117.6
#12 117.6 * What went wrong:
#12 117.6 An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '9.1.0']
#12 117.6 > Failed to apply plugin class 'nebula.plugin.netflixossproject.publishing.PublishingPlugin'.
#12 117.6    > Task with name 'postRelease' not found in root project 'conductor'.
#12 117.6
#12 117.6 * Try:
#12 117.6 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
#12 117.6
#12 117.6 * Get more help at https://help.gradle.org
#12 117.6
#12 117.6 BUILD FAILED in 1m 56sPlease do not create issues for questions. Use the [discussion forum](https://github.com/Netflix/conductor/discussions) instead!

**Comment by apanicker-nflx** [comment]
Looks like the gradle version that is packaged as part of the project is not being used. Please try with this one.

**Comment by uakihir0** [comment]
Hi.
Have you downloaded the zip file and extracted it to build it? In my case, I did `git clone` and it built fine.
