### ISSUE TITLE
[BUG]: The tasks in the loop are scheduled concurrently

### ISSUE THREAD

**Issue by evgvain** [Netflix/conductor#2368]
The loop is a fragment of the complex workflow. The order of the iteration is broken and tasks from the next iteration are dispatched before the previous iteration is completed.
The loop body consists of 3 tasks: set_variable, simple, set_variable. The tasks are executed consecutively but the 33rd iteration is mixed up with the 34th. The task set_dec_loop_completed__33 appears scheduled twice.

Conductor version: 3.0.4

Workflow definition:
![image](https://user-images.githubusercontent.com/6605905/126495641-d0092920-3d70-470e-afc8-bb44a8a471ee.png)

Tasks Details
![image](https://user-images.githubusercontent.com/6605905/126495695-87164d3d-5349-4141-9057-148e89ef61bf.png)

**Comment by apanicker-nflx** [comment]
Hi @evgvain, is this reproducible? Could you please give us a few details about your setup? Also what conductor version are you running? 
If reproducible, please share the workflow definition that you used as well.

**Comment by evgvain** [comment]
Conductor version: 3.0.4. Unfortunately, it is not deterministic - it happens from time to time. 
Please specify what details about the setup do you need.

**Comment by apanicker-nflx** [comment]
> Please specify what details about the setup do you need.

Please provide details about the persistence layer, lock implementation and server deployment. 

Since this bug is not easily reproducible, it would take us some time to get around to it. But in the meantime, please feel free to send in a PR with the fix if you are able to get to it sooner.

**Comment by evgvain** [comment]
I am working with stand alone MySQL db persistence model and stand alone Elasticsearch instance.
I am not sure about the lock implementation - I am using the default configuration. conductor-server, conductor-ui, Elasticsearch and MySQL are running on the same platform in dockers, managed by docker-compose.

**Comment by evgvain** [comment]
This happen again. See below the tasks from the loop extracted from the Elasticsearch index conductor_task. You can see that the last task  (seq_qry_decrypt__9) is scheduled and starts before the previous (seq_qry_decrypt__8) ends. The task seq_qry_decrypt__8 even does not appear in conductor GUI. The order of 8th and 9th iteration is messed up.
`
{'workflowId': 'cf55b2ab-da00-47a8-9881-8e3e6d1c6f22', 'workflowType': 'query_hub_proxy_batch_subflow', 'scheduledTime': '2021-08-25T01:50:33.249Z', 'startTime': '2021-08-25T01:50:46.497Z', 'updateTime': '2021-08-25T01:50:46.497Z', 'endTime': '2021-08-25T01:51:03.542Z', 'status': 'COMPLETED', 'executionTime': 17045, 'queueWaitTime': 13248, 'taskDefName': 'seq_qry_decrypt', 'taskType': 'seq_qry_decrypt', 'input': '{session-aggregate-hub-results=False, session-do-name=Node4, engine_id=11667295-974b-4110-b006-3cf4ca8b517a, session-run-name=proxy_COUNT_predefined_batch, session-query-type=Cnt_Street_Num, b128=null, stop-looking=null, queries_num=3}', 'output': '{dec_completed=False}', 'taskId': '9e54d6c8-cdcc-48b2-9179-764b82dcd5ca', 'workflowPriority': 0}
{'workflowId': 'cf55b2ab-da00-47a8-9881-8e3e6d1c6f22', 'workflowType': 'query_hub_proxy_batch_subflow', 'scheduledTime': '2021-08-25T01:51:03.912Z', 'startTime': '2021-08-25T01:51:05.054Z', 'updateTime': '2021-08-25T01:51:05.054Z', 'endTime': '2021-08-25T01:51:22.203Z', 'status': 'COMPLETED', 'executionTime': 17149, 'queueWaitTime': 1142, 'taskDefName': 'seq_qry_decrypt', 'taskType': 'seq_qry_decrypt', 'input': '{session-aggregate-hub-results=False, session-do-name=Node4, engine_id=11667295-974b-4110-b006-3cf4ca8b517a, session-run-name=proxy_COUNT_predefined_batch, session-query-type=Cnt_Street_Num, b128=null, stop-looking=null, queries_num=3}', 'output': '{dec_completed=False}', 'taskId': '17196ba2-ce6a-42c9-b338-6cbd1c7c3f22', 'workflowPriority': 0}
{'workflowId': 'cf55b2ab-da00-47a8-9881-8e3e6d1c6f22', 'workflowType': 'query_hub_proxy_batch_subflow', 'scheduledTime': '2021-08-25T01:51:04.129Z', 'startTime': '2021-08-25T01:51:12.686Z', 'updateTime': '2021-08-25T01:51:12.686Z', 'endTime': '2021-08-25T01:51:23.705Z', 'status': 'COMPLETED', 'executionTime': 11019, 'queueWaitTime': 8557, 'taskDefName': 'seq_qry_decrypt', 'taskType': 'seq_qry_decrypt', 'input': '{session-aggregate-hub-results=False, session-do-name=Node4, engine_id=11667295-974b-4110-b006-3cf4ca8b517a, session-run-name=proxy_COUNT_predefined_batch, session-query-type=Cnt_Street_Num, b128=null, stop-looking=null, queries_num=3}', 'output': '{dec_completed=False, _append_=true}', 'taskId': '1f2a441f-7257-45fd-a5ee-ff050318866a', 'workflowPriority': 0}
{'workflowId': 'cf55b2ab-da00-47a8-9881-8e3e6d1c6f22', 'workflowType': 'query_hub_proxy_batch_subflow', 'scheduledTime': '2021-08-25T01:51:24.141Z', 'startTime': '2021-08-25T01:51:25.269Z', 'updateTime': '2021-08-25T01:51:25.269Z', 'endTime': '2021-08-25T01:51:42.231Z', 'status': 'COMPLETED', 'executionTime': 16962, 'queueWaitTime': 1128, 'taskDefName': 'seq_qry_decrypt', 'taskType': 'seq_qry_decrypt', 'input': '{session-aggregate-hub-results=False, session-do-name=Node4, engine_id=11667295-974b-4110-b006-3cf4ca8b517a, session-run-name=proxy_COUNT_predefined_batch, session-query-type=Cnt_Street_Num, b128=null, stop-looking=null, queries_num=3}', 'output': '{dec_completed=False}', 'taskId': 'd51d647f-7831-4ebf-9e3a-9fd35ed5262c', 'workflowPriority': 0}
{'workflowId': 'cf55b2ab-da00-47a8-9881-8e3e6d1c6f22', 'workflowType': 'query_hub_proxy_batch_subflow', 'scheduledTime': '2021-08-25T01:51:42.622Z', 'startTime': '2021-08-25T01:51:43.728Z', 'updateTime': '2021-08-25T01:51:43.728Z', 'endTime': '2021-08-25T01:51:56.529Z', 'status': 'COMPLETED', 'executionTime': 12801, 'queueWaitTime': 1106, 'taskDefName': 'seq_qry_decrypt', 'taskType': 'seq_qry_decrypt', 'input': '{session-aggregate-hub-results=False, session-do-name=Node4, engine_id=11667295-974b-4110-b006-3cf4ca8b517a, session-run-name=proxy_COUNT_predefined_batch, session-query-type=Cnt_Street_Num, b128=null, stop-looking=null, queries_num=3}', 'output': '{dec_completed=False, _append_=true}', 'taskId': '28e07c9e-ea99-4a2a-b863-63ff189ba494', 'workflowPriority': 0}
{'workflowId': 'cf55b2ab-da00-47a8-9881-8e3e6d1c6f22', 'workflowType': 'query_hub_proxy_batch_subflow', 'scheduledTime': '2021-08-25T01:51:56.936Z', 'startTime': '2021-08-25T01:51:58.068Z', 'updateTime': '2021-08-25T01:51:58.068Z', 'endTime': '2021-08-25T01:52:14.843Z', 'status': 'COMPLETED', 'executionTime': 16775, 'queueWaitTime': 1132, 'taskDefName': 'seq_qry_decrypt', 'taskType': 'seq_qry_decrypt', 'input': '{session-aggregate-hub-results=False, session-do-name=Node4, engine_id=11667295-974b-4110-b006-3cf4ca8b517a, session-run-name=proxy_COUNT_predefined_batch, session-query-type=Cnt_Street_Num, b128=null, stop-looking=null, queries_num=3}', 'output': '{dec_completed=False}', 'taskId': 'c7e52c63-57a3-4786-96c6-0732710855ff', 'workflowPriority': 0}
{'workflowId': 'cf55b2ab-da00-47a8-9881-8e3e6d1c6f22', 'workflowType': 'query_hub_proxy_batch_subflow', 'scheduledTime': '2021-08-25T01:52:15.198Z', 'startTime': '2021-08-25T01:52:16.439Z', 'updateTime': '2021-08-25T01:52:16.439Z', 'endTime': '2021-08-25T01:52:33.518Z', 'status': 'COMPLETED', 'executionTime': 17079, 'queueWaitTime': 1241, 'taskDefName': 'seq_qry_decrypt', 'taskType': 'seq_qry_decrypt', 'input': '{session-aggregate-hub-results=False, session-do-name=Node4, engine_id=11667295-974b-4110-b006-3cf4ca8b517a, session-run-name=proxy_COUNT_predefined_batch, session-query-type=Cnt_Street_Num, b128=null, stop-looking=null, queries_num=3}', 'output': '{dec_completed=False}', 'taskId': '599535a7-e88c-4f37-b9e3-6f5b9ee4371f', 'workflowPriority': 0}
{'workflowId': 'cf55b2ab-da00-47a8-9881-8e3e6d1c6f22', 'workflowType': 'query_hub_proxy_batch_subflow', 'scheduledTime': '2021-08-25T01:52:33.908Z', 'startTime': '2021-08-25T01:52:35.027Z', 'updateTime': '2021-08-25T01:52:35.027Z', 'endTime': '2021-08-25T01:52:37.137Z', 'status': 'COMPLETED', 'executionTime': 2110, 'queueWaitTime': 1119, 'taskDefName': 'seq_qry_decrypt', 'taskType': 'seq_qry_decrypt', 'input': '{session-aggregate-hub-results=False, session-do-name=Node4, engine_id=11667295-974b-4110-b006-3cf4ca8b517a, session-run-name=proxy_COUNT_predefined_batch, session-query-type=Cnt_Street_Num, b128=null, stop-looking=null, queries_num=3}', 'output': '{dec_completed=true, _append_=true}', 'taskId': 'd3323075-eb4d-4058-9795-eb07222c24a3', 'workflowPriority': 0}
{'workflowId': 'cf55b2ab-da00-47a8-9881-8e3e6d1c6f22', 'workflowType': 'query_hub_proxy_batch_subflow', 'scheduledTime': '2021-08-25T01:52:34.175Z', 'startTime': '2021-08-25T01:52:35.497Z', 'updateTime': '2021-08-25T01:52:35.497Z', 'endTime': '2021-08-25T01:52:38.027Z', 'status': 'COMPLETED', 'executionTime': 2530, 'queueWaitTime': 1322, 'taskDefName': 'seq_qry_decrypt', 'taskType': 'seq_qry_decrypt', 'input': '{session-aggregate-hub-results=False, session-do-name=Node4, engine_id=11667295-974b-4110-b006-3cf4ca8b517a, session-run-name=proxy_COUNT_predefined_batch, session-query-type=Cnt_Street_Num, b128=null, stop-looking=null, queries_num=3}', 'output': '{dec_completed=true}', 'taskId': '07c2b202-e5b3-4af0-a50f-0d2670e7dd12', 'workflowPriority': 0}

`

![image](https://user-images.githubusercontent.com/6605905/130749921-7fee67ec-93f0-46f5-9ea4-aa26b2e4fab5.png)

**Comment by evgvain** [comment]
Similar behavior was observed again after upgrade to version 3.2, even after setting conductor.app.workflowExecutionLockEnabled=true

**Comment by aravindanr** [comment]
Could you share more details about the lock implementation, that is used? Zookeeper or Redis.

**Comment by evgvain** [comment]
I am not sure. This is my configuration file. Am I need to configure something else?

`
conductor.grpc-server.enabled=false

conductor.db.type=mysql
spring.datasource.url=jdbc:mysql://mysql:3306/conductor
spring.datasource.username=uconductor
spring.datasource.password=pconductor

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

conductor.indexing.enabled=true

conductor.elasticsearch.url=http://es:9200

conductor.elasticsearch.indexName=conductor

loadSample=false

conductor.app.workflowExecutionLockEnabled=true
`

**Comment by aravindanr** [comment]
Enabling the lock is not sufficient. The lock implementation needs to be configured. Please configure it to use [Redis](https://github.com/Netflix/conductor/blob/main/CHANGELOG.md#redis-lock-module) or [Zookeeper](https://github.com/Netflix/conductor/blob/main/CHANGELOG.md#zookeeper-lock-module). Use the property values from the NEW column.

**Comment by manan164** [comment]
Hi @evgvain , Is it possible for you to share the workflow definition json? Please remove all confidential info. Also what is the frequency this behavior occurs? Like out of X executions it is appearing Y times.

**Comment by manan164** [comment]
Thanks, @evgvain, I will check and update.

**Comment by manan164** [comment]
Hi @evgvain , I am able to reproduce this locally.
Few observations while locking disabled, 
1. This occurs when there is a large number of iterations.
2. No relation with the execution store. Have seen this occurs even in-memory store.
I will try with locking enabled and update the thread.

**Comment by manan164** [comment]
Hi @evgvain , I have checked it. This is a synchronization issue. With [redis-locking,](https://github.com/Netflix/conductor/blob/main/CHANGELOG.md#redis-lock-module) this behavior does not occur. Please enabled locking.

**Comment by evgvain** [comment]
Thanks @manan164 !

**Comment by manan164** [comment]
Hi @evgvain, I am able to debug the issue with local_lock also. Will submit the fix in a few days.
