### ISSUE TITLE
Q: How do I set the status of a HTTP task to 'IN_PROGRESS' ?

### ISSUE THREAD

**Issue by erezh** [Netflix/conductor#238]
I'm trying to use Conductor to initiate a task via web service.
After that I want to poll the status of the task (again via external web service), and if the task is still pending, the workflow should wait for it's completion.
Based on the comments in #35 I'm trying to force the worker to rerun the task by returning a status of IN_PROGRESS.
How do I do that with an HTTP task ? also, where do I set the callbackAdfterSeconds value ?

**Comment by v1r3n** [comment]
HTTP task is marked as completed once the call is made successfully.  It seems you want to add another task after HTTP that essentially is polling for the status of the task and is marked as completed once done.  

Currently, HTTP task do not go into IN_PROGRESS.

**Comment by erezh** [comment]
Thank you.

Is there a way I can return the HTTP task to the worker to rerun later, based on the response body of the HTTP request ? What approach should I take if I need to keep rerunning the same task based on the response body?

**Comment by v1r3n** [comment]
Currently this is not possible, but one can extend HttpTask.java to add this behavior.
