### ISSUE TITLE
BACKEND_ERROR - HikariPool-1 - Connection is not available, request timed out after 30000ms

### ISSUE THREAD

**Issue by bhawani021** [Netflix/conductor#2385]
I am using PostgresDB with conductor version 3.0

GET /api/metadata/taskdefs

```
{
  "status": 500,
  "message": "BACKEND_ERROR - HikariPool-1 - Connection is not available, request timed out after 30000ms.",
  "instance": "cloudqbw72",
  "retryable": true
}
```

**Comment by bhawani021** [comment]
> I am using PostgresDB with conductor version 3.0
> 
> GET /api/metadata/taskdefs
> 
> ```
> {
>   "status": 500,
>   "message": "BACKEND_ERROR - HikariPool-1 - Connection is not available, request timed out after 30000ms.",
>   "instance": "cloudqbw72",
>   "retryable": true
> }
> ```

**Comment by aravindanr** [comment]
Please check if Conductor can connect to your PostgresDB
