### ISSUE TITLE
[BUG]: Workflow tasks are not accessable when using workflow archiving with TTL - Redis DAO specific

### ISSUE THREAD

**Issue by heinrichcohn** [Netflix/conductor#2398]
**Describe the bug**
When archiving workflows using archiving with TTL status listener, their task are not reachable causing the getWorkflow API return Workflows summary with no tasks.  The root cause of this problem is that the WORKFLOW_TO_TASKS mapping is deleted with no TTL during the archiving what leads to a situation in which you have workflows and tasks data ( they have a TTL > 0) but no mapping between them because no TTL was set for the mapping.
Once the TTL expires, Conductor will start retrieving the workflows and their tasks from ES and the problem disappears
Longer the TTL ,  more noticeable the issue will be.

**Details**
Conductor version:3.x
Configuration:
conductor.workflow-status-listener.archival.ttlDuration=3600s
conductor.workflow-status-listener.type=archive

**To Reproduce**
1. Run Conductor with "archive" with TTL enabled. Set a long TTL
2. Run a workflow
3. Right after the workflow finishes, call the api **http://[conductor-endpoint]/api/workflow/[your_workflow_id]?includeTasks=true**
4. The response will contain no tasks data in the 'tasks' field

**Expected behavior**
After running a workflow and calling the getWorkflow API (http://[conductor-endpoint]/api/workflow/[your_workflow_id]?includeTasks=true**), the API should return the tasks data in the 'tasks' field

**Additional context**
This problem is relevant when using Redis Execution DAO + Archive with TTL

**Comment by apanicker-nflx** [comment]
Closing since #2399 is merged
