### ISSUE TITLE
Deploying Dynomite cluster and elastisearch in aws

### ISSUE THREAD

**Issue by sk523** [Netflix/conductor#241]
We are trying to use Conductor as part of our project with workflows containing HTTP tasks. Can you please share us on how to deploy conductor in AWS with HA behind an ELB with following information?

-Deploying Dynomite cluster with multi AZ
-Deploying Elasticsearch instance (can we use AWS elasticsearch 5.3 version ?)
-Deploying Conductor behind an ELB with multiple instances running across AZs.

**Comment by ipapapa** [comment]
There is some information about a similar setup in https://github.com/Netflix/conductor/issues/230
For Dynomite, you can see some exemplary configurations under the [conf folder](https://github.com/Netflix/dynomite/tree/dev/conf).
