### ISSUE TITLE
[BUG]: Not able to utilise simple task output value in DO_WHILE task loop condition

### ISSUE THREAD

**Issue by shriram-apps** [Netflix/conductor#2418]
**Describe the bug**
In my current workflow i have created on  DO_WHILE task which has multiple simple task inside the loopvars. I want to utilise couple of the simple task output values in the loopCondition which will help the workflow to process in loop to execute the simple task till the required data is received

**Example:** 
i have 2 simple tasks TASK A & TASK B both the tasks return the status value in OUTPUT which i am not able to access in loopcondition

**Below is the workflow**
curl -X POST http://localhost:8080/api/metadata/workflow -H 'Content-Type: application/json' -d '{
    "name": "kotak_user_flow_loop",
    "description": "Kotak user flow loop",
    "version": 67,
    "schemaVersion": 2,
    "tasks": [
		{
			"name": "loop_task",
			"taskReferenceName": "LoopTask",
			"type": "DO_WHILE",
			"inputParameters": {
			  "value": "${workflow.input.userId}"
			},
			"loopCondition": "if ( ($.kotak_nfdl_check_parallel.output.status === 'success' &&  $.kotak_ncif_check_parallel.output.status === 'success')) { true; } else { false; }",
			"loopOver": [
							{
								"name": "fetch_user_details",
								"taskReferenceName": "user_details",
								"inputParameters": {
									"userId": "${workflow.input.userId}"
								},
								"type": "SIMPLE"
							},
							{
								"name": "parallel_process_nfcl_ncif",
								"taskReferenceName": "parallel_nfcl_ncif",
								"type": "FORK_JOIN",
								"forkTasks": [
									[
										{
										  "name": "kotak_nfdl_check_new",
										  "taskReferenceName": "kotak_nfdl_check_parallel",
										  "inputParameters": {
											"userId": "${user_details.output.panId}"
										  },
										  "type": "SIMPLE"
										}
									],
									[
										{
										  "name": "kotak_ncif_check",
										  "taskReferenceName": "kotak_ncif_check_parallel",
										  "inputParameters": {
											"userId": "${user_details.output.pinCode}"
										  },
										  "type": "SIMPLE"
										}
									]
								]
							},
							{
								"name": "join_nfcl_ncif",
								"taskReferenceName": "process_join_nfcl_ncif",
								"type": "JOIN",
								"joinOn": [
								  "kotak_nfdl_check_parallel",
								  "kotak_ncif_check_parallel"
								]
							},
							{
								"name": "kotak_user_dedupe_check",
								"taskReferenceName": "kotak_user_dedupe",
								"inputParameters": {
									"nfdlStatus": "${kotak_nfdl_check_parallel.output.status}",
									"ncifStatus": "${kotak_ncif_check_parallel.output.status}",
									"userId": "${workflow.input.userId}",
								},
								"type": "SIMPLE"
							}
			],
			"startDelay": 0,
			"optional": false
		}
    ]
}'

Note : i have also tried creating VARIABLE TASK and accessed it but no luck

Guide me how to access the task variable in DO_WHILE loop condition

**Comment by manan164** [comment]
Hi @shriram-apps , I have changed the workflow definition a little bit. Here is what I am trying and I found it is working.
{
    "createTime": 1644342705547,
    "name": "query_hub_proxy_batch_subflow",
    "version": 4,
    "tasks": [
        {
            "name": "comp_loop_loop",
            "taskReferenceName": "comp_loop_loop",
            "type": "DO_WHILE",
            "decisionCases": {},
            "defaultCase": [],
            "forkTasks": [],
            "startDelay": 0,
            "joinOn": [],
            "optional": false,
            "defaultExclusiveJoinTask": [],
            "asyncComplete": false,
            "loopCondition": "if ($.res_to_hub_final['oddEven'] == 1) { false; } else { true; }",
            "loopOver": [
                {
                    "name": "gc_objects_sync_2",
                    "taskReferenceName": "res_to_hub_final",
                    "inputParameters": {},
                    "type": "SIMPLE",
                    "decisionCases": {},
                    "defaultCase": [],
                    "forkTasks": [],
                    "startDelay": 0,
                    "joinOn": [],
                    "optional": false,
                    "defaultExclusiveJoinTask": [],
                    "asyncComplete": false,
                    "loopOver": []
                }
            ]
        }
    ],
    "inputParameters": [],
    "outputParameters": {},
    "schemaVersion": 2,
    "restartable": true,
    "workflowStatusListenerEnabled": true,
    "ownerEmail": "noone@nowhere.com",
    "timeoutPolicy": "ALERT_ONLY",
    "timeoutSeconds": 0,
    "variables": {},
    "inputTemplate": {}
}
Here is [worker definition](https://github.com/Netflix/conductor/blob/main/client/src/test/java/com/netflix/conductor/client/sample/SampleWorker.java#L35) Since the task output will be a json map, [] has to be used. More information regarding it at, [Do While](https://netflix.github.io/conductor/configuration/systask/#do-while-task)
