### ISSUE TITLE
[BUG]: PoolOfflineException after some time when service started

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [Netflix/conductor#2427]
Hello everyone.

I have deployed Conducor about year ago into my dedicated server. I use redis as data storage and created configs like this:
     
    db=redis
     
    workflow.dynomite.cluster.hosts=localhost:6379:us-east-1e
    workflow.dynomite.connection.maxConnsPerHost=31
    EC2_AVAILABILITY_ZONE=us-east-1e
    queues.dynomite.nonQuorum.port=6379

Last two days, Conductor started crash with these exception messsages:

    ava.lang.RuntimeException: com.netflix.dyno.connectionpool.exception.PoolOfflineException: PoolOfflineException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down, hashtag=null, password=null], latency=0(0), attempts=0]host pool is offline and no Racks available for fallback
        at com.netflix.dyno.queues.redis.RedisDynoQueue.pop(RedisDynoQueue.java:343)
        at com.netflix.conductor.dao.dynomite.queue.DynoQueueDAO.pop(DynoQueueDAO.java:192)

Like it forgets the addresses of redis. This happens after long time when this service starts. I thought that my Disk space is full, but it shows me this:

    Filesystem                         Size  Used Avail Use% Mounted on
    udev                               1.9G     0  1.9G   0% /dev
    tmpfs                              395M  1.4M  394M   1% /run
    /dev/mapper/ubuntu--vg-ubuntu--lv   49G  6.3G   40G  14% /
    tmpfs                              2.0G     0  2.0G   0% /dev/shm
    tmpfs                              5.0M     0  5.0M   0% /run/lock
    tmpfs                              2.0G     0  2.0G   0% /sys/fs/cgroup
    /dev/sda2                          976M  218M  692M  24% /boot
    tmpfs                              395M     0  395M   0% /run/user/1000
    /dev/loop1                         100M  100M     0 100% /snap/core/11420
    /dev/loop2                         100M  100M     0 100% /snap/core/11606

Which shows me that it has plenty of space. Why it is happening?

My specs:

    Ubuntu 18.04
    Conductor  2.29
    JDK 8
    Redis server v=4.0.9

**Comment by kishorebanala** [comment]
@SuperMasterBlasterLaser This seems more of a Dynomite / Dyno-queues issue, do you mind checking there please? https://github.com/Netflix/dynomite

**Comment by SuperMasterBlasterLaser** [comment]
@kishorebanala I have increased RAM of my VM from 4 GB to 16 GB and it started to work stable.
