### ISSUE TITLE
[BUG]: protogen-annotations:1.0.0. module not found

### ISSUE THREAD

**Issue by UDragon-CK** [Netflix/conductor#2428]
**Describe the bug**
I was building the netflix conductor worker project.
I put 2 gradle dependencies below.

implementation group: 'com.netflix.conductor', name: 'conductor-common', version: '3.1.0'
implementation 'com.netflix.conductor:conductor-client-spring:3.1.0'

Then I proceeded with the gradle build, but an error occurred and the build kept failing.
The build error is

========================gradle build error======================
Execution failed for task ':bootJarMainClassName'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find com.github.vmg.protogen:protogen-annotations:1.0.0.
     Required by:
         project : > com.netflix.conductor:conductor-common:3.1.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
===========================================================

For reference, the server runs normally with Spring boot.

gradle version: gradle-6.8.3
jdk version: 1.8.0_271
I'll upload the full source too help me please ㅠ_ㅠ
[creturns-conductor.zip](https://github.com/Netflix/conductor/files/7046629/creturns-conductor.zip)

![스크린샷 2021-08-25 오후 8 34 17](https://user-images.githubusercontent.com/56381499/130784064-a0937a3e-57b5-4bd7-9108-908d27f7e242.png)

**Comment by apanicker-nflx** [comment]
The dependency is available [here](https://mvnrepository.com/artifact/com.github.vmg.protogen/protogen-annotations?repo=jcenter), could you try adding `jcenter` to your repositories as well.

**Comment by UDragon-CK** [comment]
I'm added this dependency, but the problem is the same.
implementation group: 'com.github.vmg.protogen', name: 'protogen-annotations', version: '1.0.0'


Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.github.vmg.protogen:protogen-annotations:1.0.0.
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
