### ISSUE TITLE
 DELETE /workflow/{workflowId}/remove

### ISSUE THREAD

**Issue by zhangzening** [Netflix/conductor#243]
why I can not delete workflow when I used api " DELETE /workflow/{workflowId}/remove" ,return 204 not context,but when I  search all , it is exist.

**Comment by clari-akhilesh** [comment]
This is because the workflow is archived in elasticsearch and the search functionality looks up the workflows in the archive as well. I've a PR which makes archiving optional. Please refer to https://github.com/Netflix/conductor/pull/381 for additional details
