### ISSUE TITLE
[BUG]: The workflow is stuck on join

### ISSUE THREAD

**Issue by evgvain** [Netflix/conductor#2455]
Dynamic fork runs 3 sub_workflows. When all sub_workflows are completed the workflow is stuck on join task.

Conductor version: 3.2
Database persistence type: conductor.db.type=dynomite
(using default config.properties)

![bug2](https://user-images.githubusercontent.com/6605905/132893384-9c4da07b-b1c4-4ceb-9a84-e917d764e138.png)

![bug1](https://user-images.githubusercontent.com/6605905/132893471-7bbce9e4-96e6-4916-b04a-d327302eee46.png)

![bug0](https://user-images.githubusercontent.com/6605905/132893429-9103a057-c735-4e7a-9b2c-a2201de23286.png)

When I looking on the tasks in the queue (API /api/tasks/queue/all), the task "_deciderQueue": has value 1. All other tasks have value 0

**Comment by evgvain** [comment]
The issue disappear after I changed the Database persistence type to mysql. When using dynomite, the workflow suck in ~10% of runs (out of ~100 runs). When using mysql - issue wasn't recreated in more than 300 runs.

**Comment by aravindanr** [comment]
@evgvain We have had such issues with Dynomite internally and switched Cassandra for persistence and Redis for queues. We will be replacing with a pure [Redis implementation](https://github.com/Netflix/conductor/wiki/Roadmap#usability).

**Comment by v1r3n** [comment]
@aravindanr is the issue related to Dynomite? Does using lock fix this issue?
