### ISSUE TITLE
[BUG]: The Subworkflow Completes Even Though The Latest Task Is Scheduled When Optional Task Included

### ISSUE THREAD

**Issue by OguzhanUlucay** [Netflix/conductor#2459]
**Describe the bug**
Hello, I have had opened a issue earlier #2297 and we got recommendation to update conductor version from v2.30 to the 3.x since some fixes related to problem are entered. 

We have updated the our conductor and encountered same issue again. 

To desribe issue again, the subworkflow which has two retryable(one is optional) task and also fired under fork-join is getting marked as completed even though the latest task is still scheduled.

We have programmed both task to be never completed, so there is no chance that tasks are indeed completed but they marked as scheduled. ​The occurance seems random and happens even under light load of conductor. For example, I have started 4 exact workflow and bug occured.

It's seems that Conductor V3.x resolved the most of the issue but there is edge case with optional tasks.

**Details**
You can reproduce the bug by using these definitions. You may need to run couple of workflow and wait at least 2-3 hours until bug occurs. Please note that it may take more time.

Conductor version: Conductor v3.06. We are using it with Elastic Search and Redis

Workflow definition: 
[conductor_bug_test_main.txt](https://github.com/Netflix/conductor/files/7162292/conductor_bug_test_main.txt)
[conductor_bug_subworkflow_test.txt](https://github.com/Netflix/conductor/files/7162297/conductor_bug_subworkflow_test.txt)

Task definition: 
[conductor_bug_tasks.txt](https://github.com/Netflix/conductor/files/7162300/conductor_bug_tasks.txt)

Execution Jsons:
Main workflow:  [conductor_bug_test_main_workflow_exec.txt](https://github.com/Netflix/conductor/files/7242609/conductor_bug_test_main_workflow_exec.txt)
Subworkflow: [conductor_bug_sub_workflow_exec.txt](https://github.com/Netflix/conductor/files/7242611/conductor_bug_sub_workflow_exec.txt)

**Expected behavior**
The latest task should have continued to be executed.

**Screenshots**
Main workflow:
![image](https://user-images.githubusercontent.com/20965786/133266224-bf95570a-1f3d-46a4-b328-283a581eda24.png)

Subworkflow:
![Inked133268834-23519edf-4923-48bd-a501-62f84dd65ebd_LI](https://user-images.githubusercontent.com/20965786/133269502-ea6a275e-16d9-47d2-9209-485012f2ab92.jpg)

Task Detail page of Subworkflow:
![image](https://user-images.githubusercontent.com/20965786/133266879-00eb97c7-3438-4962-9efe-05dff0729dce.png)

**Comment by mashary** [comment]
+1

**Comment by azb96** [comment]
+1

**Comment by CHURLZ** [comment]
Add a Join task, according to the docs it might allow the tasks to finish.

**Comment by OguzhanUlucay** [comment]
@CHURLZ Can you explain to put the join task where? I guess you are saying to put a join task to end of decision case but I couldn't find any info about that in conductor doc. By the way, we have already a join task after fork join.

**Comment by aravindanr** [comment]
@OguzhanUlucay We are trying to reproduce this on our end. In the meantime, could you also post the workflow execution json for both the main and the sub workflow?

**Comment by OguzhanUlucay** [comment]
@aravindanr I have now uploaded workflow execution jsons to details section of my main comment; https://github.com/Netflix/conductor/issues/2459#issue-996043851

**Comment by OguzhanUlucay** [comment]
@aravindanr Hello, is there any update about issue?

**Comment by aravindanr** [comment]
@OguzhanUlucay I am not able to reproduce the bug by running the workflow manually several times. I am working on an automation script to run the workflow periodically to check if its reproducible.

While analyzing the code, i see possibilities of workflow state becoming unpredictable if there "locking" is not enabled. Do you have it enabled? If yes, is it zookeeper or redis?

**Comment by OguzhanUlucay** [comment]
@aravindanr No, We have not enabled the locking. Would you propose to open it? We may open it via redis.
