### ISSUE TITLE
[QUESTION]:  ERROR [2/6] RUN apk update && apk add python make g++ 

### ISSUE THREAD

**Issue by dzx2018** [Netflix/conductor#2481]
=> ERROR [2/6] RUN apk update && apk add python make g++                                                                                                              1.8s
------                                                                                                                                                                      
 > [2/6] RUN apk update && apk add python make g++:                                                                                                                         
#5 0.427 fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/aarch64/APKINDEX.tar.gz                                                                                      
#5 1.172 fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/aarch64/APKINDEX.tar.gz
#5 1.172 ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/main: Protocol error
#5 1.172 WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/main: No such file or directory
#5 1.756 ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/community: Protocol error
#5 1.756 WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/community: No such file or directory
#5 1.757 2 errors; 16 distinct packages available
------
executor failed running [/bin/sh -c apk update && apk add python make g++]: exit code: 2

**Comment by aravindanr** [comment]
Can you be more specific with the question? This does not seem to be related to Conductor.
