### ISSUE TITLE
Task Logger Framework

### ISSUE THREAD

**Issue by v1r3n** [Netflix/conductor#25]
Provide a framework for tasks to log execution context and additional information.
The feature can be used for task workers to log details of task failures (e.g. stack trace) or execution logs.

The data is stored in a persisted store and is made viewable from the UI.  The data is purely informational and will not be passed around the tasks.

**Comment by picaron** [comment]
@v1r3n 
I saw this was removed from the 2017 Q1 milestone. Do you have any plans to build this soon?

I would be happy to contribute if my help is welcome.

**Comment by v1r3n** [comment]
@picaron yes, we are planning for Q2, not started the work yet.
