### ISSUE TITLE
[BUG]: Vulnerability in Conductor Server

### ISSUE THREAD

**Issue by taojwmware** [Netflix/conductor#2505]
**Describe the bug**

**Details**
Conductor version: latest main branch
Workflow definition:
Task definition:
Event handler definition:

**To Reproduce**
Build conductor from main branch and perform black duck analysis on the jar file.

**Expected behavior**
Some critical vulnerabilities exist in xstream component used in Conductor.

**Screenshots**

![Screen Shot 2021-10-07 at 3 53 41 PM](https://user-images.githubusercontent.com/25186652/136461176-17cbd46f-5496-4e4e-9eac-6d6a1f7bd6a2.png)

**Additional context**

Run Black Duck Binary Analysis. Found some Vulnerabilities and it can be fixed by an update to the latest version.
[conductor-server-340-snapshot-bootjar-components.csv](https://github.com/Netflix/conductor/files/7306926/conductor-server-340-snapshot-bootjar-components.csv)

**Comment by taojwmware** [comment]
Looks like it comes from :conductor-redis-persistence
```
+--- project :conductor-redis-persistence
|    +--- com.netflix.dyno-queues:dyno-queues-redis:2.0.20
|    |    +--- com.netflix.dyno:dyno-jedis:1.7.2-rc2
|    |    |    +--- com.netflix.dyno:dyno-contrib:1.7.2-rc2
|    |    |    |    +--- com.netflix.eureka:eureka-client:1.8.6
|    |    |    |    |    +--- com.thoughtworks.xstream:xstream:1.4.10
```

**Comment by aravindanr** [comment]
@taojwmware if you would like to upgrade the xstream library, please submit a PR.
