### ISSUE TITLE
Python client does not fail the task when catching an exception

### ISSUE THREAD

**Issue by guyeng0** [Netflix/conductor#251]
When an exception is caught by the python client the task remains in the IN_PROCESSING state.

Seems to me that the task should fail  otherwise it will continue to retry indefinitely.

I can do a PR to fix this if needed.

**Comment by v1r3n** [comment]
@guyeng0 happy to review and merge the PR.

**Comment by v1r3n** [comment]
Closing the issue in the meantime. @guyeng0 feel free to send the PR
