### ISSUE TITLE
The workflow suspended , which contains 3,253 tasks.

### ISSUE THREAD

**Issue by xiaowei582648206** [Netflix/conductor#2515]
**Describe the bug**
I create a workflow which contains 3,253 tasks: 1,627 **SUB_WORKFLOW** task and 1,626 **SIMPLE** task ,  each **SUB_WORKFLOW** task followed by  a **SIMPLE** task.  When the **SUB_WORKFLOW** task:  **sub_wf_334** executed completely, the workflow just suspended , the status of workflow is still "RUNNING",  but the rest task are never scheduled.

**Details**
Conductor version: conductor-2.30.1
Workflow definition: `{
    "ownerApp": "jmr",
    "createdBy": "lixiaoran",
    "name": "jmr_parent_workflow",
    "description": "hdfs_datanode升级_2.100.60-2_持续发布_详情",
    "version": 1,
    "tasks": [
      {
        "name": "sub_wf_1",
        "taskReferenceName": "sub_wf_1",
        "inputParameters": {
          "server": "datanode",
          "withMissing": "false",
          "taskTimeout": "600",
          "auth": "755",
          "failedPolicy": "skipFailed",
          "softdir": "hadoop-2.7.1",
          "clusterCode": "hope",
          "run_type": "update",
          "runMode": "auto",
          "pkgUrl": "http://172.28.174.157/hadoop/hadoop_2.100.60_2021100615_NN-20211006151154-2b857ef8-jdk11.tar.gz",
          "versionId": "151",
          "pkgName": "hadoop_2.100.60_2021100615_NN-20211006151154-2b857ef8-jdk11.tar.gz",
          "handleMode": "manual",
          "simpleTimeout": "60",
          "acctKey": "lixiaoran",
          "target_dir": "/tmp/hdfs/",
          "pkgTag": "hadoop_2.100.60_2021100615_NN-20211006151154-2b857ef8-jdk11",
          "user": "hadp",
          "ipList": "10.198.146.66,10.198.146.67,10.198.146.68,10.198.146.69,10.198.146.70,10.198.146.71,10.198.146.72,10.198.146.73,10.198.146.74",
          "group": "hadoop"
        },
        "type": "SUB_WORKFLOW",
        "decisionCases": {},
        "defaultCase": [],
        "forkTasks": [],
        "startDelay": 0,
        "subWorkflowParam": {
          "name": "change_hadooppkg",
          "version": 1
        },
        "joinOn": [],
        "optional": false,
        "taskDefinition": {
          "name": "sub_wf_1",
          "retryCount": 0,
          "timeoutSeconds": 0,
          "inputKeys": [],
          "outputKeys": [],
          "timeoutPolicy": "TIME_OUT_WF",
          "retryLogic": "FIXED",
          "retryDelaySeconds": 0,
          "responseTimeoutSeconds": 0,
          "inputTemplate": {},
          "rateLimitPerFrequency": 0,
          "rateLimitFrequencyInSeconds": 1
        },
        "defaultExclusiveJoinTask": [],
        "asyncComplete": false,
        "loopOver": []
      },
      {
        "name": "simple_sleep_task",
        "taskReferenceName": "simple_sleep_task_1",
        "inputParameters": {
          "simpleTimeout": 60
        },
        "type": "SIMPLE",
        "decisionCases": {},
        "defaultCase": [],
        "forkTasks": [],
        "startDelay": 0,
        "joinOn": [],
        "optional": false,
        "taskDefinition": {
          "createTime": 1616586701097,
          "createdBy": "",
          "name": "simple_sleep_task",
          "retryCount": 3,
          "timeoutSeconds": 0,
          "inputKeys": [
            "simpleTimeout"
          ],
          "outputKeys": [
            "result"
          ],
          "timeoutPolicy": "RETRY",
          "retryLogic": "FIXED",
          "retryDelaySeconds": 60,
          "responseTimeoutSeconds": 86400,
          "concurrentExecLimit": 100,
          "inputTemplate": {},
          "rateLimitPerFrequency": 50,
          "rateLimitFrequencyInSeconds": 60,
          "ownerEmail": "lookstorm@163.com"
        },
        "defaultExclusiveJoinTask": [],
        "asyncComplete": false,
        "loopOver": []
      },
   ...
    ]
    "inputParameters": [],
    "outputParameters": {},
    "schemaVersion": 2,
    "restartable": true,
    "workflowStatusListenerEnabled": true,
    "ownerEmail": "lixiaoran@jd.com",
    "timeoutPolicy": "ALERT_ONLY",
    "timeoutSeconds": 0,
    "variables": {}
}
`

**Screenshots**
the 'sub_wf_334' task has been exceuted completely,  but the followed task : 'simple_sleep_task_334' never schedule!
![image](https://user-images.githubusercontent.com/5030860/137280883-73959e98-efd4-4b5d-a20a-968b67ebaf57.png)

the whole workflow is still "RUNNING"
![image](https://user-images.githubusercontent.com/5030860/137281108-534f6d16-b865-48d8-b2d8-20a7e8339059.png)

Thank you very much for your help.

@v1r3n
@apanicker-nflx
@kishorebanala
@jfernandez

**Comment by aravindanr** [comment]
Could you also share details about your conductor setup? It would help to know,

1. Persistence implementation.
2. Queue implementation.
3. Whether locking is enabled, if yes, Redis or Zookeeper?
