### ISSUE TITLE
Support for Jersey 2/HK2

### ISSUE THREAD

**Issue by sebukoleth** [Netflix/conductor#253]
Conductor uses Jersey 1.x and Guice. All later application servers have Jersey 2.x in their root classpath. This makes it difficult to embed Conductor as a web application in any of them. Also Guice does not play nice with Jersey 2.x. Conductor will probably need to switch to HK2.

**Comment by v1r3n** [comment]
Yes, for Jersey 2.x, we need to switch from Guice to HK2.  We currently do not have plans for moving to Jersey 2.x.
