### ISSUE TITLE
[DOC]: 'ownerEmail' mandatory field missing   

### ISSUE THREAD

**Issue by altafalam21** [Netflix/conductor#2542]
## What are you missing in the docs
"ownerEmail" field while creating Workflow definition has been made mandatory in latest releases of conductor, which is yet to be
updated in docs.

## Proposed text
"ownerEmail" : Mandatory Field

**Comment by aravindanr** [comment]
Hello, thanks for reporting it. If you know where the update is needed in the documentation, please create a pull request with the update.

**Comment by jmigueprieto** [comment]
I'm just getting started with conductor and I noticed this issue while using the sample payloads in the docs to create tasks and workflow in my dev environment.

I believe this PR https://github.com/Netflix/conductor/pull/2598 addresses the issue but there might be other docs that need to be updated.

**Comment by apanicker-nflx** [comment]
Merged #2598
