### ISSUE TITLE
[FEATURE]: [UI] Adjustable width task panel

### ISSUE THREAD

**Issue by peterlau** [Netflix/conductor#2548]
Please read our [contributor guide](https://github.com/Netflix/conductor/blob/main/CONTRIBUTING.md) before creating an issue.   
Also consider discussing your idea on the [discussion forum](https://github.com/Netflix/conductor/discussions) first.

## Describe the Feature Request
The task panel is currently fixed width. While this works well in most cases, on small screens it would be advantageous to be able to expand the panel.

## Describe Preferred Solution
List of potential improvements in order of ease of implementation:
* Add a vertical slider handle to the existing panel so that the task panel width can be interactively adjusted
* Provide a toggle so that the panel can be 'maximized' most of the way and retracted back to the 'split' width.
* The panel is currently 'docked'. That is, as the task panel expands, the main workflow panel shrinks. Provide a toggle so that users may optionally 'undock' the task panel such that it overlays over the workflow panel.

## Describe Alternatives
Separate task details page. This would require flipping back and forth between the workflow view and tasks disrupting the user experience and making it impossible to browse through a workflow execution smoothly.

**Comment by boney9** [comment]
@peterlau - As we discussed - we can own this task. You can assign it to us.
