### ISSUE TITLE
Execution error when start ui in latest version

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#2552]
**Describe the bug**
when start ui program with 'yarn run start', i got the errors below:
**Failed to compile.

src/components/KeyValueTable.jsx
  Line 63:62:  'value' is not defined  no-undef

Search for the keywords to learn more about each error.**

**Details**
Conductor version:
Persistence implementation: MySQL
Queue implementation: MySQL
Lock: no lock
Workflow definition:
Task definition:
Event handler definition:

**To Reproduce**
1. Go to ../ui
2. execute the cmd: yarn run start'
3. wait for a moment
4. then get the error: 
 **Failed to compile.

src/components/KeyValueTable.jsx
  Line 63:62:  'value' is not defined  no-undef

Search for the keywords to learn more about each error.**

**Comment by andyyumiao** [comment]
So I think it was introduced from a later version

**Comment by peterlau** [comment]
Thanks for the report. 3.3.4 was released to patch this. Please give that a try.

**Comment by andyyumiao** [comment]
> Thanks for the report. 3.3.4 was released to patch this. Please give that a try.

Great, the latest version is fine!!
