### ISSUE TITLE
Server fails to start with ES connection error if workflow.elasticsearch.cluster.health.color=yellow is not set 

### ISSUE THREAD

**Issue by shubham-prasad** [Netflix/conductor#2567]
**Describe the bug**
I'm using prebuild jars in a personal project to run conductor with custom WorkflowStatusListener implementation. 
I've observed that if I don't set workflow.elasticsearch.cluster.health.color=yellow, the ElasticSearchRestDAOV5 throws timeout error. Same happens for TransportClient, the error thrown is NoNodeAvailableException. 
I have also seen that docker/server/config/config.properties doesn't contain this and when I build the container and run using compose this issue doesn't come up.

**Details**
Conductor version: 2.31.5
Persistence implementation: redis_cluster
Queue implementation:  Dynoqueues 
Lock: Redis or Zookeeper? none
Workflow definition: NA
Task definition: NA
Event handler definition: NA

**To Reproduce**
1. Download the repo, switch to 2.31
2. Run gradle build
3. Modify docker/server/config/config.properties, point es to local server or somewhere where cluster health is yellow
4. Run jar, using the above config file

**Expected behavior**
The server should run without any error

**Screenshots**
---------
With tcp
![image](https://user-images.githubusercontent.com/6239536/140993602-4fc8681b-0021-4cab-a956-daf55220a535.png)

---------
with http
![image](https://user-images.githubusercontent.com/6239536/140993617-b3419577-d63e-48e0-b1a2-af40582d4ef7.png)

**Additional context**

I have verified that ES is up and accessible. I have also verified this on windows and ubuntu to rule out any firewall related issue.

**Comment by jxu-nflx** [comment]
Hello @shubham-prasad, where did you get the es5-psersistent module? Also how did you launch ES, it it via docker container? By default, conductor.elasticsearch.clusterHealthColor=green, so it will wait for the ES cluster to become green: https://github.com/Netflix/conductor/blob/main/es6-persistence/src/main/java/com/netflix/conductor/es6/dao/index/ElasticSearchRestDAOV6.java#L337 You can check the ElasticSearchRestDaoV5 implementation to see how it does the checks

**Comment by aravindanr** [comment]
> Modify docker/server/config/config.properties, point es to local server or somewhere where cluster health is yellow

@shubham-prasad as part of the above step, are you setting `workflow.elasticsearch.cluster.health.color=yellow`? The default value is `green`.

**Comment by shubham-prasad** [comment]
Thanks @aravindanr for the clarification. We should add this in property in the docs.
