### ISSUE TITLE
FAILED task does not immediately fail workflow

### ISSUE THREAD

**Issue by kpdude7** [Netflix/conductor#257]
When one of our tasks in a workflow fails, the workflow status remains "RUNNING" for an unspecified amount of time; if we stop/restart the app (SpringBoot), that task picks up whatever is left on the queue from this previous run; this is undesirable. Is the amount of time that a workflow waits to fail configurable?

**Comment by v1r3n** [comment]
@kpdude7 are there any retries set the tasks?  If there are retries, the workflow will not fail and task will be retried after the delay.
