### ISSUE TITLE
3.3.4 UI Bug.   Task Details tab doesn`t show with javascript error.

### ISSUE THREAD

**Issue by vfmuniz** [Netflix/conductor#2573]
Hi. I just upgraded to 3.3.4 UI and I noticed that task details tab does not show when you click on it any task. Issue happens both on production mode (when I copy the build result from yarn build command to the server resources folder and access all the pages as static files) and on development mode.

Details
Conductor version:
Persistence implementation: Oracle, Elastic 7
Queue implementation: Dynoqueues, RabbitMQ etc
Lock: Redis or Zookeeper? NO lockin
Workflow definition: Any
Task definition: Any
Event handler definition: Any

To Reproduce

Go to UI homescreen
Click on Search button
Scroll down to any workflow that is COMPLETE or RUNNING or any other state
Once the workflow details screen opens, click on any Task

Expected behavior
The task details tab should open so user can see Input, Output, Logs and so on. Instead, a javascript error happens. 

Screenshot:
![image](https://user-images.githubusercontent.com/32685867/141684095-babc77c5-5568-40f5-a755-579bf17055c7.png)

**Comment by peterlau** [comment]
Looks to be caused by a workflow execution returning no 'taskToDomain' field.

**Comment by vfmuniz** [comment]
Thank you :)
