### ISSUE TITLE
[UI] Dockerfile apk command error

### ISSUE THREAD

**Issue by peterlau** [Netflix/conductor#2576]
### Discussed in https://github.com/Netflix/conductor/discussions/2490

<div type='discussions-op-text'>

<sup>Originally posted by **dzx2018** September 24, 2021</sup>
 => ERROR [2/6] RUN apk update && apk add python make g++                                                                                                              1.8s
------                                                                                                                                                                      
 > [2/6] RUN apk update && apk add python make g++:                                                                                                                         
#5 0.427 fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/aarch64/APKINDEX.tar.gz                                                                                      
#5 1.172 fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/aarch64/APKINDEX.tar.gz
#5 1.172 ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/main: Protocol error
#5 1.172 WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/main: No such file or directory
#5 1.756 ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/community: Protocol error
#5 1.756 WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/community: No such file or directory
#5 1.757 2 errors; 16 distinct packages available
------
executor failed running [/bin/sh -c apk update && apk add python make g++]: exit code: 2
</div>

**Comment by fooozhe** [comment]
same here
