### ISSUE TITLE
UI Bug with v3.3.6 - TypeError: data is not iterable

### ISSUE THREAD

**Issue by FlorianKuckelkorn** [Netflix/conductor#2588]
**Describe the bug**
By calling the start page of the UI, the UI crashes instantly with the Error Message described below

**Details**
Conductor version: 3.3.6
Persistence implementation: Dynomite
Queue implementation: Dynoqueues
Lock: Redis
Workflow definition: none
Task definition: none
Event handler definition: none

**To Reproduce**
1. Go to 'conductor ui' on port 5000
2. See error

**Expected behavior**
The default UI should be presented

**Screenshots**
![image](https://user-images.githubusercontent.com/39465158/142918411-77595eba-1eca-47f7-b7a5-7e587fe60c7b.png)

**Additional context**
Deploying is done via Docker

**Comment by peterlau** [comment]
This looks to be a symptom of the backend not being up. Please verify that the conductor backend is accessible at `localhost:8080`.

**Comment by FlorianKuckelkorn** [comment]
Hi, i just tried it and the backend is fully available

**Comment by peterlau** [comment]
This is expected. The UI (via create-react-app or nginx) proxies the entire backed to the UI port (5000) to avoid browser 
cross-origin complications.

**Comment by muthurajr** [comment]
@FlorianKuckelkorn What is the value of WF_SERVER passed to the ui container?
I faced similar issue when upgrading from 3.2 to 3.3. May be it can help you.
in 3.2 WF_SERVER=http://conductor-server:8080/api/
in 3.3 onwards with the react app, WF_SERVER=http://conductor-server:8080
