### ISSUE TITLE
Docker ElasticSearch misconfiguration

### ISSUE THREAD

**Issue by javiercanillas** [Netflix/conductor#2589]
**Describe the bug**
When running using the docker image ([explained here](https://netflix.github.io/conductor/server/#3-use-the-pre-configured-docker-image)),  indexes configuration on ElasticSearch includes one replica. Since ES instance is only one, this statemente cannot be fulfilled correctly, so ES health will always be yellow, instead of green.

Since ES health can only achieve yellow status, only first `docker-compose up` execution results on successful conductor server start, but further restarts will only result on failure due to unhealthy ES status.

**Details**
Conductor version: main branch
Persistence implementation: 
Queue implementation: 
Lock: 
Workflow definition:
Task definition:
Event handler definition:

**To Reproduce**
1. follow (Use the pre-configured Docker image)[https://netflix.github.io/conductor/server/#3-use-the-pre-configured-docker-image] instructions and setup for the first time your docker image, even call the `docker-compose up` to start your server for the first time.
2. After conductor is up and running, control the ElasticSearch instance health by navigating to: `http://localhost:9200/_cluster/health`, you will probably get something like:
```json
{
"cluster_name": "docker-cluster",
"status": "yellow",
"timed_out": false,
"number_of_nodes": 1,
"number_of_data_nodes": 1,
"active_primary_shards": 25,
"active_shards": 50,
"relocating_shards": 0,
"initializing_shards": 0,
"unassigned_shards": 25,
"delayed_unassigned_shards": 0,
"number_of_pending_tasks": 0,
"number_of_in_flight_fetch": 0,
"task_max_waiting_in_queue_millis": 0,
"active_shards_percent_as_number": 100
}
```
So, cluster status is yellow since the replica shards required by conductor when creating the indexes cannot be assigned.
3. Now stop the `docker_conductor-server_1` server from docker and restart it. 
4. See `docker_conductor-server_1` logs by login into the instance and doing: 
```bash
# tail -f app/logs/server.log
```
You may need to wait till 30 seconds to see the exception thrown from conductor server about a timeout waiting for ES's health status.

**Expected behavior**
Docker image out of the box should configure indexes without replica shards since only 1 ES instance is started.

**Additional context**
I will attempt to update the issue with a potential fixing commit.

**Comment by apanicker-nflx** [comment]
Closed by #2590
