### ISSUE TITLE
Conductor Java SDK fails to update the task output

### ISSUE THREAD

**Issue by flavioschuindt** [Netflix/conductor#2594]
**Describe the bug**
I have a workflow that has a SIMPLE task. I have a custom worker implementation that is responsible to:

* Call an async downstream service;
* Update the task output with some acknowledge content:

```json
{
  "ackResponse": "SOME_CONTENT_HERE"
}
```

Just FYI, later on the downstream service will resume the task in the workflow with more content in the task output, but this is not part of this discussion here.

This works fine for 99% of the cases. However, in some cases the conductor sdk is not updating the task output. The only update that always work is the one that the downstream services does later on.

Looking at conductor code, it seems that worker can configure some parameters for the task update resiliency from the workers like **updateRetryCount** and **sleepWhenRetry**. I already played with those parameters by changing updateRetryCount to 6 (3 is the default) and sleepWhenRetry to 3000ms (500ms is the default) and no luck as well.

I enabled full log in conductor as well and sometimes I see a message like this: ```"Attempt # 1, XX millis since first attempt"```. This comes from the ```RetryUtil```. Initially I thought this was indicating me something, but I do see this message even in the cases that works. So, I am not sure...

I can't share the full code of my worker here due to PI, but in a nutshell:

```java
public abstract class AbstractAsyncWorker<T extends IRequest, S extends IResponse> implements Worker{

    @Override
    public TaskResult execute( Task task ) {
         // Some validation...
         // Call downstream service
         S response = remoteService.execute( input.getRequest(), taskMetadata );
         // Update task output with ackResponse key and some content
         result.addOutputData( ACK_RESPONSE_OUTPUT_KEY, mapper.convertValue( output, Map.class ) );
         // Final return. From this point on, java conductor sdk will update the task in the workflow with the above content. This is failing for some executions and that is the issue.
         return result;
      }
}
```

**Details**
Conductor version: **2.30.3**
Conductor Java SDK Client: **2.10.2**, **2.30.3** and **2.31.5** (Tried all those versions and see this issue in all of them).
Persistence implementation: **Postgres**
Queue implementation: **Postgres**
Lock: Redis or Zookeeper?
Workflow definition: **Can't share due to PI.**
Task definition: **Can't share due to PI.**
Event handler definition:

**Expected behavior**
All updates in the task output done by SDK should be honored. I expect all the time the update containing the **ackResponse** above to happen.

**Comment by aravindanr** [comment]
This _may be_ a timing issue. Its possible that the downstream service updates the task output and sets the task to a terminal state (COMPLETED, FAILED etc) before the worker does it. If the task reaches a terminal state, all updates from there on will be ignored by conductor.
