### ISSUE TITLE
[QUESTION]: EventServiceGrpc don't have found

### ISSUE THREAD

**Issue by weiwensi** [Netflix/conductor#2599]
I pull the master branch to my loacl,inthe  grpc-client and the grpc-server can't found the class EventServiceGrpc what should I do?

**Comment by apanicker-nflx** [comment]
EventClient is part of the grpc-client module [here](https://github.com/Netflix/conductor/blob/main/grpc-client/src/main/java/com/netflix/conductor/client/grpc/EventClient.java) and also the EventService is part of grpc-server [here](https://github.com/Netflix/conductor/blob/main/grpc-server/src/main/java/com/netflix/conductor/grpc/server/service/EventServiceImpl.java)
