### ISSUE TITLE
How to disable retries for a taskdef

### ISSUE THREAD

**Issue by kpdude7** [Netflix/conductor#260]
On version 1.7.2, I'm trying to create a taskdef with retry-count=0 (I've also tried eliminating retry-count altogether from the json). The PUT will accept my request, but when I do a GET on all taskdefs, mine was created with the default retry-count=3. Is there any way to totally disable retry logic for a taskdef? (The reason I want this is because the internals of the related service already has embedded retry logic.)

**Comment by smkb80** [comment]
Please refer to the below link:
[Task Definition](https://netflix.github.io/conductor/metadata/#task-definition)

**Comment by kpdude7** [comment]
@smkb80 I am quite familiar with the documentation, thank you. Maybe an example would help me get a meaningful response. When I Post the following taskdef definition:

**Comment by smkb80** [comment]
I don't know the version of Conductor you are working with but it worked as expected with **1.8.0-SNAPSHOT**. I registered the following Taskdef JSON (same as yours but within a Arraylist) using /metadata/taskdefs API.

```
[{
	"name": "some_task",
	"retryCount": 0,
	"retryLogic": "FIXED",
	"timeoutSeconds": 1800,
	"timeoutPolicy": "TIME_OUT_WF",
	"retryDelaySeconds": 0,
	"responseTimeoutSeconds": 0,
	"inputKeys": [
		"configs"
	],
	"outputKeys": [
		"configs"
	]
}]
```

Got back the following JSON using /metadata/taskdefs/{tasktype} API:
![untitled](https://user-images.githubusercontent.com/26455103/28151781-72a622a0-67ba-11e7-8887-9e4b3a711136.jpg)

**Comment by kpdude7** [comment]
@smkb80  Thanks for the response. We are currently using 1.7.2 as per my initial post; I tried changing my dependency version to 1.8.0-SNAPSHOT, but the dependency could not be resolved. (Besides, it is against our company policy to use SNAPSHOT builds) Then I tried 1.7.6, which did resolve, but did not fix this issue. When will the next release be published? @v1r3n

**Comment by smkb80** [comment]
@kpdude7 Not sure if I understand when you say - 

> which did resolve, but did not fix this issue.

 Do you mean that the task is still being retried by Conductor even tough retryCount is 0?

**Comment by kpdude7** [comment]
@smkb80 No, what I meant was that when I change my dependency to point to version 1.8.0-SNAPSHOT, gradle build says:

**Comment by kpdude7** [comment]
@smk80 @v1r3n  When I say above that "the retryCount issue does not work", what I mean is that it still saves my change when I post "retryCount:0" to overwrite it automatically to "retryCount:3".

**Comment by v1r3n** [comment]
@kpdude7 This a  bug.  I have marked the issue as a bug to address in the next release.

**Comment by kpdude7** [comment]
Thanks @v1r3n .  When can we expect the next version with the bug fix to be released?

**Comment by kpdude7** [comment]
@v1r3n We just installed v1.8.0. The above issue was NOT fixed; i.e. when I try to update a taskdef via swagger and set retry_count to 0, it forces the value to 3 upon saving. The best I can do is set it to 1, which is honored.

**Comment by apanicker-nflx** [comment]
@kpdude7 The latest release versions do not have this issue. Please reopen if you are still seeing this issue on your end.
