### ISSUE TITLE
Conductor Docker Java Certs Error

### ISSUE THREAD

**Issue by dcompgriff** [Netflix/conductor#261]
Hey. So, I've been trying to change the docker file configurations to work behind a network proxy, and have run into some other issues. I keep getting an ssl cert error when the build.gradle file is used, shown below 

`Build file '/conductor/build.gradle' line: 13

* What went wrong:
Error resolving plugin [id: 'nebula.netflixoss', version: '3.6.0']
> Could not GET 'https://plugins.gradle.org/api/gradle/3.1/plugin/use/nebula.netflixoss/3.6.0'.
   > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`
I'm wondering if there is some extra configuration that is required for the docker image to be able to access the gradle plugins for building within the docker file.

**Comment by sah2ed** [comment]
Sounds like the JDK which you are using to connect outside of your network does not have the CA in its trust store so it is unable to verify the certificate chain for the SSL used by https://plugins.gradle.org.

Please see if this [article](https://confluence.atlassian.com/kb/unable-to-connect-to-ssl-services-due-to-pkix-path-building-failed-779355358.html) can resolve your issue.

**Comment by dcompgriff** [comment]
I figured this was the case. However, the docker container that is configured for the conductor uses the base image "java:8-jdk", which has a pre-installed java 8 jdk. So, I was wondering if anyone else was having this issue when they tried a straight docker build, or docker compose with the current docker files.

**Comment by dcompgriff** [comment]
I figured out the issue. I was missing a .pem cert file necessary to get through my corporate proxy.
