### ISSUE TITLE
Help to install the visual workflow UI

### ISSUE THREAD

**Issue by laxmikantb** [Netflix/conductor#2616]
### Discussed in https://github.com/Netflix/conductor/discussions/2615

<div type='discussions-op-text'>

<sup>Originally posted by **alawth** November 30, 2021</sup>
I have tried to start the conductor server from source (https://github.com/Netflix/conductor) and executed the following.

./gradlew server

/ui/ -> yarn run start

And I'm getting this UI [here](https://ibb.co/yhMf1fv) and not the workflow visual UI that I'm expecting to have [here](https://user-images.githubusercontent.com/3489862/55858537-237d0d80-5b9a-11e9-9e62-0d98d1b5c780.png) . 

Any idea on how can I install or enable the visual workflow UI?

Thanks.</div>

**Comment by laxmikantb** [comment]
I started server as below  (on windows 10)

cd conductor
gradlew server

from another cmd termincal
cd conductor/ui
yarn run start

but I am getting 

Usage Error: Couldn't find a script named "start".

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...

any idea ,  where i can find start script?

Thanks.

**Comment by debapi94** [comment]
shell 1
$ cd conductor
conductor$ cd server
server$ ../gradlew bootRun
//access the APIs at: http://localhost:8080/swagger-ui/index.html?configUrl=/api-docs/swagger-config

shell 2
$ cd conductor
conductor$ cd ui
conductor/ui$ yarn install
conductor/ui$ WF_SERVER=http://localhost:8080/ yarn run start

**Comment by laxmikantb** [comment]
I tried same steps - I am running on windows.
here are the steps i ran -
npm i -g corepack
yarn init -2
yarn set version stable
yarn set version from sources

ran server gradlew server - it came up w/o issues
i see the api with swagger

then 

cd ui
yarn install
yarn run start

D:\software\conductor\ui>yarn run start
     **Usage Error: Couldn't find a script named "start".**

**Comment by boney9** [comment]
Hey @laxmikantb - The UI has been upgraded to the new look that you see. The start command is there. You can look at the package.json to confirm. Make sure you have the latest code base or one of the release code base.

**Comment by laxmikantb** [comment]
Thanks , I am able to start it , as I took latest package json from repo. I am able to see workflow and task definitions with directed graph. But I am not able to get execution graph , is any anything missing on settings?
