### ISSUE TITLE
 taskReferenceName needs to be unique within a workflow

### ISSUE THREAD

**Issue by shahnaresh41** [Netflix/conductor#2635]
Moving from conductor-2.30.0 to 3.3.4 and trying to import old workflow definition to conductor-3.3.4 
but it is throwing error that taskReferenceName needs to be unique within a workflow. 
Is there any solution to this so that we do not have to change the taskReferenceNamewithin workflow.

Error :
------------------
{
    "status": 400,
    "message": "Validation failed, check below errors for detail.",
    "retryable": false,
	"validationErrors": [
			{
				"path": "updateWorkflowDef.workflowDefList[0]",
				"message": "taskReferenceName: ABC_taskReferenceName1 should be unique across tasks for a given workflowDefinition: MyWorkflow"
			}
	]	
}

**Comment by apanicker-nflx** [comment]
@shahnaresh41 Please do not create issues for questions. Use the [discussion forum](https://github.com/Netflix/conductor/discussions) instead!
