### ISSUE TITLE
Task timeout is not happening for async tasks

### ISSUE THREAD

**Issue by pavansharma30** [Netflix/conductor#2650]
Describe the bug
Task timeout is not happening for async tasks even after task timeout is exceeded and no body invoked the pending task

**Details**
Conductor version: 3.10
Persistence implementation: Cassandra, Postgres, MySQL, Dynomite etc
Queue implementation: Postgres, MySQL, Dynoqueues etc
Lock: Redis or Zookeeper?
Workflow definition:
Task definition:
Event handler definition:

**Expected behavior**
time out should happen 

Payload : 
{
  "workflowDefinition": {
    "createTime": 1639566272191,
    "name": "testTask",
    "description": "moveTaskInternalV1",
    "version": 1,
    "tasks": [
      {
        "name": "task_1",
        "taskReferenceName": "task_1",
        "inputParameters": {
          "http_request": {
            "uri": http://test-url:8445/move,
            "method": "POST",
            "headers": {
              "X-Workflow-Instance-Id": "${workflow.workflowId}",
              "X-Task-Reference-Name": "task_1"
            },
            "connectionTimeOut": "7200",
            "readTimeOut": "7200",
            "body": {
              "srcAeTitle": "${workflow.input.device.configuration.aeTitle}",
              "port": "${workflow.input.device.xxxx}",
              "host": "${workflow.input.device.xxxx}",
              "executionId": "${workflow.input.xxxId}",
              "studyInstanceUID": "${workflow.input.study.studyInstanceUID}",
              "workflowExecutionId": "${workflow.input.xxxxId}"
            }
          },
          "asyncComplete": true
        },
        "type": "HTTP",
        "decisionCases": {},
        "defaultCase": [],
        "forkTasks": [],
        "startDelay": 0,
        "joinOn": [],
        "optional": false,
        "taskDefinition": {
          "name": "task_1",
          "retryCount": 1,
          "timeoutSeconds": 10000,
          "inputKeys": [],
          "outputKeys": [],
          "timeoutPolicy": "TIME_OUT_WF",
          "retryLogic": "FIXED",
          "retryDelaySeconds": 0,
          "responseTimeoutSeconds": 3600,
          "inputTemplate": {},
          "rateLimitPerFrequency": 0,
          "rateLimitFrequencyInSeconds": 1
        },
        "defaultExclusiveJoinTask": [],
        "asyncComplete": true,
        "loopOver": []
      }
    ],
    "inputParameters": [],
    "outputParameters": {},
    "schemaVersion": 2,
    "restartable": true,
    "workflowStatusListenerEnabled": true,
    "timeoutPolicy": "ALERT_ONLY",
    "timeoutSeconds": 0,
    "variables": {}
  },
  "taskToDomain": {},
  "tasks": [
    {
      "taskId": "a30c3ec4-5b96-4836-b9cb-c9f31ae6b2e9",
      "workflowInstanceId": "9e738df2-2cb5-49d8-9758-ef7a36655eca",
      "callbackAfterSeconds": 0,
      "outputData": {},
      "status": "SCHEDULED",
      "referenceTaskName": "task_1",
      "id": "a30c3ec4-5b9x-483x-b9cx-c9f31ae6b2ex",
      "taskType": "HTTP",
      "inputData": {
        "asyncComplete": true,
        "http_request": {
          "headers": {
            "X-Task-Reference-Name": "task_1",
            "X-Workflow-Instance-Id": "9e738df2-2cb5-49d8-9758-ef7a36655eca"
          },
          "method": "POST",
          "readTimeOut": "7200",
          "body": {
            "executionId": "562f4a14-6857-43c2-8cef-5f82f0563610",
            "port": 1xx,
            "studyInstanceUID": "1.2.840.113696.316208.500.1174978.010.04.02",
            "host": "1x.8x.xxx.xxx",
            "workflowExecutionId": "4a49bbd9-7bfa-4e80-b794-a67a1c5ff37b",
            "srcAeTitle": "test"
          },
          "uri": http://test-url/,
          "connectionTimeOut": "7200"
        }
      },
      "retryCount": 0,
      "seq": 1,
      "pollCount": 0,
      "taskDefName": "task_1",
      "scheduledTime": 1639566325657,
      "startTime": 0,
      "endTime": 0,
      "updateTime": 0,
      "startDelayInSeconds": 0,
      "retried": false,
     "executed": false,
      "callbackFromWorker": true,
      "responseTimeoutSeconds": 0,
      "workflowType": "moveTaskV1",
      "workflowTask": {
        "name": "task_1",
        "taskReferenceName": "task_1",
        "inputParameters": {
          "http_request": {
            "uri": http://test-url,
            "method": "POST",
            "headers": {
              "X-Workflow-Instance-Id": "${workflow.workflowId}",
              "X-Task-Reference-Name": "task_1"
            },
            "connectionTimeOut": "7200",
            "readTimeOut": "7200",
            "body": {
              "srcAeTitle": "${workflow.input.device.configuration.aeTitle}",
              "port": "${workflow.input.port}",
              "host": "${workflow.input.host}",
              "executionId": "${workflow.input}",
              "studyInstanceUID": "${workflow.input.study}",
              "workflowExecutionId": "${workflow.input}"
            }
          },
          "asyncComplete": true
        },
        "type": "HTTP",
        "decisionCases": {},
        "defaultCase": [],
        "forkTasks": [],
        "startDelay": 0,
        "joinOn": [],
        "optional": false,
        "taskDefinition": {
          "name": "task_1",
          "retryCount": 1,
          "timeoutSeconds": 10000,
          "inputKeys": [],
          "outputKeys": [],
          "timeoutPolicy": "TIME_OUT_WF",
          "retryLogic": "FIXED",
          "retryDelaySeconds": 0,
          "responseTimeoutSeconds": 3600,
          "inputTemplate": {},
          "rateLimitPerFrequency": 0,
          "rateLimitFrequencyInSeconds": 1
        },
        "defaultExclusiveJoinTask": [],
        "asyncComplete": true,
        "loopOver": []
      },
      "rateLimitPerFrequency": 0,
      "rateLimitFrequencyInSeconds": 1,
      "workflowPriority": 0,
      "iteration": 0,
      "subworkflowChanged": false,
      "loopOverTask": false,
      "queueWaitTime": 0,
      "taskDefinition": {
        "name": "task_1",
        "retryCount": 1,
        "timeoutSeconds": 10000,
        "inputKeys": [],
        "outputKeys": [],
        "timeoutPolicy": "TIME_OUT_WF",
        "retryLogic": "FIXED",
        "retryDelaySeconds": 0,
        "responseTimeoutSeconds": 3600,
        "inputTemplate": {},
        "rateLimitPerFrequency": 0,
        "rateLimitFrequencyInSeconds": 1
      }
    }
  ],
  "terminalState": false,
  "state": "RUNNING",
  "ownerApp": "",
  "createTime": 1639566325268,
  "updateTime": 1639566325550,
  "endTime": 0,
  "workflowId": "9e738df2-2cb5-49d8-9758-ef7a36655ecb",
  "output": {},
  "failedReferenceTaskNames": [],
  "variables": {},
  "lastRetriedTime": 0,
  "startTime": 1639566325268,
  "workflowVersion": 1,
  "workflowName": "moveTaskV1"
}

**Comment by aravindanr** [comment]
Could you clarify which task has the `timeoutSeconds` set and also which "pending" task should be invoked on the timeout? Note that `responseTimeoutSeconds` and `timeoutSeconds` have different meaning. https://netflix.github.io/conductor/configuration/taskdef/

**Comment by pavansharma30** [comment]
Thanks Aravindan for your response 

We are not setting any timeoutSeconds explicitly, expecting default timeout should happened. This used to work fine for previous version of Conductor: 3.10

**Comment by aravindanr** [comment]
The default `timeoutSeconds` is set as 0, which means the task has no timeout and can run indefinitely. The value of `timeoutSeconds` has not been changed between releases.
