### ISSUE TITLE
After Version 2.30.2 you can no longer reuse taskReferenceName in a single workflow

### ISSUE THREAD

**Issue by headibr** [Netflix/conductor#2652]
After Version 2.30.2 you can no longer reuse taskReferenceName in a single workflow, and now requires each to be uniquely named. This is causing a lot of rework for workflows used in previous versions when upgrading to any version passed 2.30.2.

We should be able to reuse taskReferenceNames throughout a single workflow for simplicity, streamlined workflow visualization, and unifying the workflow output into other sub workflows.

Seems as though this was a bug, and was patched in v2.30.2, but this functionality is needing to be reinstated.

**Comment by aravindanr** [comment]
Please see the [response](https://github.com/Netflix/conductor/discussions/2662#discussioncomment-1849945) in #2662.
