### ISSUE TITLE
conductor.elasticsearch.url not working without http, in the format  'localhost:9200' with tcp protocol(Screenshots attached)

### ISSUE THREAD

**Issue by deoramanas** [Netflix/conductor#2678]
**Describe the bug**
Using ES6,
When you give URL in the format- "**localhost:9200**", you will be getting error, 
_java.lang.IllegalArgumentException: tcp://localhost:9200can not be converted to java.net.URL_ 
**Details**
Conductor version: v3.3.2
Persistence implementation: mysql
Lock: Redis
Workflow definition: Not required
Task definition:  Not required
Event handler definition:  Not required

**To Reproduce**
1. Go to application.properties
2. Set conductor.elasticsearch.url=localhost:9200 (works fine for http://localhost:9200)
3. Use es6
4. In console, you will be getting _java.lang.IllegalArgumentException: tcp://localhost:9200can not be converted to java.net.URL_ 

**Expected behavior**
Should have worked fine as it used to in previous versions. 
However, it was converted to **URI** and not _URL_ in previous builds. 

**Screenshots**
There are comments added on the screenshots itself, to help you better understand the problem statement.

<img width="945" alt="Screenshot 2021-12-21 at 6 17 14 PM" src="https://user-images.githubusercontent.com/30143119/147482537-866b3d13-81ee-4914-b5d3-384a3ae25c1b.png">
ElasticSearchProperties.java

On doing further RCA in java.net.URL, 
it doesn't support handler for **TCP** protocol. 
It internally creates handler, if not already present.For eg: ftp,http,https,war,jar,jmod,etc. Following type of handler are present as given in the screenshots below:
![image](https://user-images.githubusercontent.com/30143119/147482940-ff5c36e1-ef7f-4b7d-a986-cfe147f03505.png)

TCP protocol is not supported by the above Handler.
In the below code, it appends the prefix (""sun.net.www.protocol"") and creates instances of the supported handlers. 
Since, tcp protocol is not amongst the supported protocols for handler, in this case, it throws runtime exception.

![image](https://user-images.githubusercontent.com/30143119/147483238-08deeb02-d935-4267-88c8-7129180bd153.png)

**Additional context**
I have written comments on screenshots itself that might help you to understand the problem statement in a better way.
Please find some time and let me know of the solution.

**Comment by apanicker-nflx** [comment]
@deoramanas Thanks for the detailed bug report and RCA.

This seems to have been introduced when we upgraded to 3.0 Is this a fix that you would be interested in contributing to the project? 
Please note that this would only be applicable in ES6 (not ES7 +) since transport client has been removed in newer ES versions.

**Comment by deoramanas** [comment]
@apanicker-nflx  I will like to contribute the fix and will share the PR as soon as it is ready.

**Comment by aravindanr** [comment]
@deoramanas We are trying to gather more information about who's using Conductor. If you can,  please create a PR with your company information to WHOSUSING.md

**Comment by deoramanas** [comment]
Sure @aravindanr . I'll raise one
