### ISSUE TITLE
Using Swagger api for /api/tasks causes browser to freeze

### ISSUE THREAD

**Issue by odedlevy02** [Netflix/conductor#2694]
I am running conductor as a docker image on my local machine.
Then I am doing the following:
1. opening conductor server swagger on http://localhost:8080/ and selecting Swagger Documentation 
2. I try to expand api [post] /api/tasks 
This causes the browser to freeze and will require to kill the browser
I tried doing this on both chrome and edge browsers with the same result

**Comment by aravindanr** [comment]
Thanks for reporting it. Will include the fix in the next release.
