### ISSUE TITLE
Unifying Accept/Content-Type headers

### ISSUE THREAD

**Issue by jcantosz** [Netflix/conductor#27]
I would like to construct all messages to and parse all messages from the conductor in the same fashion. Can we make all `Accept` and `Content-Type` headers accept `application/json`? Some responses are of type `text/plain` which means I must do extra work (or have a good memory) to create my microservices

**Comment by v1r3n** [comment]
Good suggestions.  However, if you are using REST client libraries like Spring or Jersey, they take care of it automatically - without additional work required.
