### ISSUE TITLE
Conductor UI Task Logs tab does not show log messages

### ISSUE THREAD

**Issue by eransagi1** [Netflix/conductor#2703]
**Describe the bug**
Conductor UI Task Logs tab does not show log messages

**Details**
Conductor UI Task Logs tab does not show log messages.

The problem is - the UI try to get the logs from the following URL - pay attention that "api" appear twice in the URL.
http://my-host:port/api/api/tasks/bd81fae3-d514-42e5-8fbb-3e5bc5433d8b/log

![image](https://user-images.githubusercontent.com/7852785/149775370-d398f47b-3be0-4b0c-8061-c304df684cc9.png)

**To Reproduce**
Go to executions and click on some workflow execution.
Click on some task at the diagram. Then click the task's logs tab on the right side.
The logs tab is empty.

**Expected behavior**
Show log messages added to task by worker

**Comment by howaric** [comment]
Hi @eransagi1 , thanks for your report, this issue has been fixed, please refer to #2692  and #2630
