### ISSUE TITLE
java.lang.NoClassDefFoundError: org/glassfish/jersey/uri/internal/UriTemplateParser

### ISSUE THREAD

**Issue by icecreamwala12** [Netflix/conductor#2708]
i have deployed my conductor on weblogic.

somehow i am facing this bug:
java.lang.NoClassDefFoundError: org/glassfish/jersey/uri/internal/UriTemplateParser rooting from clientbase class of conductor.
stack trace is as follows
![image](https://user-images.githubusercontent.com/3677867/150145150-f2facb65-8978-4963-8de9-499b7bfcfdf5.png)

**Comment by jxu-nflx** [comment]
@icecreamwala12 what version of conductor are you trying to deploy? And what version of weblogic is it?
