### ISSUE TITLE
Python conductor client not found in PyPI

### ISSUE THREAD

**Issue by msakauye** [Netflix/conductor#273]
I'm trying to install the python client for conductor through pip as stated in the readme (https://github.com/Netflix/conductor/tree/master/client/python), and am getting a package not found error.
```
$ pip install conductor
Collecting conductor
  Could not find a version that satisfies the requirement conductor (from versions: )
No matching distribution found for conductor
```

Using pip 9.0.1 and Python 2.7.13. It doesn't seem to be registered in PyPI: https://pypi.python.org/pypi?%3Aaction=search&term=conductor&submit=search

**Comment by v1r3n** [comment]
We do not publish to pypi.  You want to checkout the code and build the python client and install locally.
