### ISSUE TITLE
Elasticsearch 7 build fails

### ISSUE THREAD

**Issue by astelmashenko** [Netflix/conductor#2740]
**Describe the bug**
I follow elasticsearch7 extension [build steps](https://github.com/Netflix/conductor/tree/main/es7-persistence#build) and it fails to build.

**Details**
Conductor version: 3.4.1

**To Reproduce**
1. Go to /build.gradle
2. change ext['elasticsearch.version'] from revElasticSearch6 to revElasticSearch7
3. /server/src/main/resources/application.properties
4. change conductor.elasticsearch.version from 6 to 7
5. execute ./gradlew generateLock updateLock saveLock
6. ./gradlew build -x test --stacktrace

**Actual behavior**
Observing errors related to absense of jackson library for ex6-persistence:
```
conductor/es6-persistence/src/main/java/com/netflix/conductor/es6/dao/index/ElasticSearchRestDAOV6.java:16: error: package com.fasterxml.jackson.databind does not exist
import com.fasterxml.jackson.databind.JsonNode;
...
```

**Expected behavior**
Build successful with es7 indexing.

I can hack build.gradle file to try to exclude es6-persistence but I'd like to make it upgradable. I can spend some time and provide PR, may be I'm missing something?

**Comment by apanicker-nflx** [comment]
I believe you may be missing the second part of the steps detailed [here](https://github.com/Netflix/conductor/tree/main/es7-persistence#build) starting from
 >To use the ES7 for all modules include test-harness, you must change also the following files:

This is because `./gradlew build -x test --stacktrace` builds all modules and `test-harness` is one of the modules that would be built as part of this command. Since this module depends on `es6-persistence` the build would fail with the above mentioned error.

**Comment by astelmashenko** [comment]
It fails even after I apply all steps including ```test-harness``` steps. Build fails even if I exclude ```test-harness``` from ```settings.gradle```. To build it successfully I did following:

- comment ```//include 'es6-persistence'``` in settings.gradle
- comment ```//include 'test-harness'``` in settings.gradle
- change ```server/build.gradle```
```
    implementation project(':conductor-es7-persistence')
//    implementation project(':conductor-es6-persistence')
//    implementation(project(path: ':conductor-es7-persistence', configuration: 'shadow'))
```

after these additional steps I was able to build it.

**Comment by apanicker-nflx** [comment]
Yes, you would need to remove(or comment out) the es6-persistence modules in your gradle files. Please note that the steps state that the modules need to be changed from es6 to es7. Both the modules cannot co-exist. 

I think we can improve the documentation here to make this more explicit. Apologies if this was confusing to you.

**Comment by apanicker-nflx** [comment]
Closing this issue for now since the build was successful, we will update the documentation to better reflect the steps in this process.
