### ISSUE TITLE
Build is broken with Bintray

### ISSUE THREAD

**Issue by james-deee** [Netflix/conductor#2744]
We are currently unable to build on `master` in Conductor due to Bintray not being available. I think that Jcenter has been deprecated,.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':conductor-server'.
> Could not resolve all dependencies for configuration ':conductor-server:runtimeCopy'.
   > Could not resolve com.netflix.runtime:health-guice:1.1.+.
     Required by:
         project :conductor-server
      > Failed to list versions for com.netflix.runtime:health-guice.
         > Unable to load Maven meta-data from https://dl.bintray.com/netflixoss/oss-candidate/com/netflix/runtime/health-guice/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/netflixoss/oss-candidate/com/netflix/runtime/health-guice/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/netflixoss/oss-candidate/com/netflix/runtime/health-guice/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

```

**Comment by aravindanr** [comment]
@james-deee the repo does not have a `master` branch. Are you building in `main` or `2.31`?

**Comment by james-deee** [comment]
Whoa boy, my local checkout still has a `master` branch, but that appears to be way out of date! It looks like if i go here: `https://github.com/Netflix/conductor/tree/master` it redirects me to 2.31! So that must be it. 

Sorry for the confusion.

**Comment by james-deee** [comment]
Actually @aravindanr Does this mean that `2.31` is broken? I know that y'all said it wont be supported, but at the very least `2.31` needs to be able to build. What's needed to get that to work?

**Comment by james-deee** [comment]
Man, nevermind. I think I just am on a really old version by using `master`. My cloned copy must be super old. Sorry about that! It looks like 2.31 is building fine now.
