### ISSUE TITLE
Docker-compose build failing

### ISSUE THREAD

**Issue by Germs31** [Netflix/conductor#2753]
HI my build keeps failing and im not totally sure why. Im very new to this. forgive my noobiness. From what i read this was already corrected but im still getting this error. 

` => ERROR [conductor:ui 2/6] RUN apk update && apk add --no-cache python3 py3-pip make g++                                                                                                                                                                               0.9s`

To Recreate: (I was following the steps in the documentation)
* git clone https://github.com/Netflix/conductor.git
* cd Docker
* docker-compose build

**Comment by jxu-nflx** [comment]
Hello @Germs31 I just followed the exact steps and didn't encounter any issues. What is the exact error messages you get for that step?

**Comment by Germs31** [comment]
@jxu-nflx  😓  It was being blocked. its fixed now. Thank you!!!
