### ISSUE TITLE
Illegal character in path

### ISSUE THREAD

**Issue by sankalppande** [Netflix/conductor#276]
I am new to using conductor so apologies if I am missing something obvious. 
I have a work flow defined with two http tasks. 

Task 1: Returns a Jason Object 
Task 2 : Uses one of the Output fields  of the JSON Object of the first task  as an Input Parameter . 

So in essence 

```
[
    {
      "name": "tsk_1",
      "taskReferenceName": "tsk_1",
      "type": "HTTP",
      "startDelay": 0,
      "inputParameters": {
        "http_request": { "uri":"http://mysite/Method1/${workflow.input.clientId}",
          "method": "GET"
        }
      }
    },
    {
      "name": "tsk_2",
      "taskReferenceName": "tsk_2",
      "type": "HTTP",
      "startDelay": 0,
      "inputParameters": {
        "http_request": {
          "uri": "http://mysite/Method2/${workflow.input.clientId}/${tsk_1.output..Field1}",
           "method": "GET"
        }
      }
    }
  ] 

```

tsk_1 works and executes correctly  , but for  tsk_2 the input gets parsed as :
```

   "http_request": {
      "uri": "http://mysite/Method2/1/[1,2,3,4]",
   "method": "GET"
   }
}
```

And get the Output as 

```
{
   "response": "Illegal character in path at index :26 http://mysite/Method2/1/[1,2,3,4]
}


```
I am guessing the issue is because of the “[” and “]” brackets. 
Posting “`http://mysite/Method2/1/[1,2,3,4]`” directly on the browser works as expected returning the expected JSON Output .

Not sure what I am missing here ?

**Comment by v1r3n** [comment]
What is the clientId passed as when starting the workflow?
