### ISSUE TITLE
JS arrays in INLINE_TASK are converted into objects by Nashorn

### ISSUE THREAD

**Issue by marcocrasso** [Netflix/conductor#2770]
**Describe the bug**
I am trying to fill a JSON array `dynamicTasksJSON` of a FORK_JOIN_DYNAMIC task, using an IN_LINE_TASK. However the array of tasks is converted onto an object. This can be reproduced for any array in general.

The next task definition:
```
{
      "name": "INLINE_TASK",
      "taskReferenceName": "inline_test",
      "type": "INLINE",
      "inputParameters": {
        "evaluatorType": "javascript",
        "expression": "function scriptFun() { return [ 6, 7, 8] } scriptFun();"
      }
    },
```
Produces:
```
{
  "result": {
    "0": 6,
    "1": 7,
    "2": 8
  }
}
```
The expected result was:
```
{
  "result": [ 6, 7, 8 ]
}
```

**Details**
Conductor version: [main](https://github.com/Netflix/conductor/commit/16c634265086bff1dba5eabffa068c8352dc8654) branch at the moment of writing this ticket.

Persistence implementation: memory
Queue implementation: dynoqueue
Lock: noop
Workflow definition: 
```

{
  "name": "test_js",
  "ownerEmail": "mcrasso@marsie.io",
  "description": "Test",
  "version": 1,
  "tasks": [
    {
      "name": "INLINE_TASK",
      "taskReferenceName": "inline_test",
      "type": "INLINE",
      "inputParameters": {
        "evaluatorType": "javascript",
        "expression": "function scriptFun() { return [ 6, 7, 8] } scriptFun();"
      }
    }
  ],
  "restartable": true,
  "workflowStatusListenerEnabled": false,
  "schemaVersion": 2
}

```

**To Reproduce**
1. register the workflow
2. start an instance
3. check the results

**Expected behavior**

```
{
  "result": [ 6, 7, 8 ]
}
```

**Screenshots**

**Additional context**

When trying to format the obtained result with a JQ task, I got a similar problem.

**Comment by dcore94** [comment]
I don't know whether you can consider this a bug... it's an infortunate behaviour of nashorn. You have to cast the Array to Java arraylist. I usually do smth like "return {tasks: Java.to(tasks, 'java.util.Map[]')" when having to return Arrays of objects. Replace with java.lang.string or the type you need. 
I was hoping that inline with javascript was not nashorn any longer btw...🙄

**Comment by marcocrasso** [comment]
You are right is not a Conductor issue, is a dependency limitation. I am closing the ticket.  BTW your suggestion seems to work for me, and now I can feed DYN_FORK with a the of output of an INLINE task. Thank you
