### ISSUE TITLE
Found bug where the workflow status is maintained as RUNNING.

### ISSUE THREAD

**Issue by UDragon-CK** [Netflix/conductor#2773]
Hi

netflix conductor build version: 2.31
db: mysql 8.x

Workflow is over, but it's status still running.
It was useless to add Terminate Task at the end.
Terminate Task document url: https://netflix.github.io/conductor/configuration/systask/#Terminate%20Task 
(Terminate Task)

Is there any solution?
I need help.

![screencapture-nrp-workflow-ui-coupang-net-2022-02-14-10_42_17](https://user-images.githubusercontent.com/56381499/153787306-13d846e1-0bb8-4d24-9692-1dfabdcc9b31.png)

![스크린샷 2022-02-14 오전 10 43 16](https://user-images.githubusercontent.com/56381499/153787162-8e033f46-f0c2-4de3-8d67-95b8bf1eab32.png)

![스크린샷 2022-02-14 오전 11 00 14](https://user-images.githubusercontent.com/56381499/153787432-cf4dc08d-fff4-495f-9f64-903a0ff845d9.png)

**Comment by jxu-nflx** [comment]
Hello @UDragon-CK Do you have lock enabled for the workflow exeuction in your property file? As by default, it is disabled, and that could cause the risk condition for issues like what you saw.

> #enable locking during workflow execution
> workflow.decider.locking.enabled=false

BTW, we no longer support 2.31, and users are encouraged to migrate to 3.x

https://github.com/Netflix/conductor/discussions/2734

> [2.31.8](https://github.com/Netflix/conductor/releases/tag/v2.31.8) is the final release of 2.31 branch. As of Feb 2022, 1.x & 2.x versions are no longer supported.

**Comment by UDragon-CK** [comment]
@jxu-nflx 
workflow.decider.locking.enabled
I didn't set this property.

very tired

I think the workflow status status status is being managed by ElasticSearch But I don't think it's synchronized.
Does it have anything to do with mysql?

**Comment by UDragon-CK** [comment]
@jxu-nflx  ~hi
I solved it by creating a scheduler in the next ui area that changes the nodejs-based RUNNING state to COMPLETED.
I'll show you the source code, too. I hope we can be of help each other.
There's only one file, and the js file itself doesn't go up, so I'll compress it into zip.

I used two api to solve the problem.
 - /api/wfe/bulk/pause
 - /api/wfe/bulk/resume

[nrpWorkflowStatusUpdateScheduler.js.zip](https://github.com/Netflix/conductor/files/8076996/nrpWorkflowStatusUpdateScheduler.js.zip)

I hope you'll always be healthy. Thank you.

**Comment by jxu-nflx** [comment]
Hello @UDragon-CK I am not sure I follow your solutions there. To clarify, you are using Elasticsearch as indexing server and mysql as the persistent storage, and you are not using locks, right?
my suggestion would be to enable locks so you don't end up in any inconsistent states, and if you supect there is lag/sync errors with Elasticsearch, then maybe look into that as well. As the UI is just using the search API of conductor, which does search Elasticsearch.
