### ISSUE TITLE
conductor version # 3.4.1 and getting below critical Vulnerability issue

### ISSUE THREAD

**Issue by trivedishalini** [Netflix/conductor#2779]
**Describe the bug**
I am using conductor version # 3.4.1 and getting below critical Vulnerability issue .

Is there any other conductor version which has resolution of these issue ??

**Details**
Conductor version: 3.4.1

<img width="812" alt="image" src="https://user-images.githubusercontent.com/92401531/155016454-37590ba2-de9d-4799-84c1-4821e5f42265.png">

**Comment by aravindanr** [comment]
The latest version 3.5.2 uses `4.1.65.Final`, from the attached screenshot, that may not address your issue. If you are using a custom build of Conductor, you can override the version in the corresponding build.gradle file. If not, our releases include frequent dependency updates. You should get the desired version in one of the upcoming releases.

**Comment by trivedishalini** [comment]
We decided  not to go with custom build of conductor .And waiting for future conductor release with resolution of high vulnerability issue as well .

Thanks for update

**Comment by aravindanr** [comment]
The next version 3.5.3 should have these dependencies upgraded. I expect the release to happen the latest by next week.
