### ISSUE TITLE
How do someone know if a workflow is completed, and get the output?

### ISSUE THREAD

**Issue by suxiaoyuv** [Netflix/conductor#28]
I have two questions

1. how to save workflows definition and tasks definition and history? now when server restart, it will be clean.
2. how do workers know if a workflow is completed?  poll all workflow status or make a end task to poll end task or others, which one do you recommend usage?

thanks!

**Comment by v1r3n** [comment]
* I am guessing you are referring to the test-harness server, which is purely in memory and meant for a quick demo.  It does not save any history.  You will need a backend Dynomite server for it to preserve the history.  We are working on a self contained server with a single node Dynomite image that can be used for such purpose.  Keep watching this space.
* Workers need not know anything about the workflow status.  They are supposed to be (ideally) idempotent workers that takes input and after producing the work provides an output.  A worker can be executing tasks which can be part of multiple workflows too (as you can share the task definitions across workflows).

**Comment by suxiaoyuv** [comment]
ok, thanks Viren!
I get it, workers need not know anything about the workflow status. when a workflow convert to completed, it must be start another workflow or task to call some one want to know this status change.
