### ISSUE TITLE
3.4.0 build.gradle-"options.release = 8" is wrong

### ISSUE THREAD

**Issue by wpz850398226** [Netflix/conductor#2800]
![image](https://user-images.githubusercontent.com/41596989/156136626-8a1dbc5b-9080-4cbf-910d-7a82cadd448b.png)
options.release should be 11,otherwise it will report "invalid mark : -release"

**Comment by apanicker-nflx** [comment]
These are libraries that are intended to be pulled into user applications. Compiling these into java8 bytecode allows upgrading the conductor server to java11 while maintaining compatibility with user applications that may be using java8.
