### ISSUE TITLE
what is the reason for such a large memory usage as the amount of data grows?

### ISSUE THREAD

**Issue by andyyumiao** [Netflix/conductor#2817]
**Describe the bug**
We have 55745 workflows and 310,000 tasks, and now the jvm heap memory reached 5g, and as the workflow grows, the conductor use more and more memory. To be clear, at the time I write this question, all our current workflows have been completed, there are no running workflows。
So, what is the reason for such a large memory usage as the amount of data grows?

**Details**
Conductor version: v3.3
Persistence implementation: MySQL
Queue implementation: MySQL
Lock: Redis

**Screenshots**
<img width="1066" alt="20220307095127569" src="https://user-images.githubusercontent.com/11346379/156954408-70c7d6a9-d62e-4e75-be97-7d576ea0273e.png">

**Comment by aravindanr** [comment]
Link #2792

**Comment by aravindanr** [comment]
@andyyumiao We don't think this is a bug in Conductor. JVM memory usage is dependent on settings used with the JVM is run. We have upwards of 700K workflows in RUNNING state for weeks at a time and our JVM memory usage is around 3GB.

![image](https://user-images.githubusercontent.com/1028385/157130554-385daf60-6b2a-421e-b7cf-0cff35dbb59b.png)
![image](https://user-images.githubusercontent.com/1028385/157130678-231feea9-a693-4d34-9fb3-72bf1756a437.png)

**Comment by manan164** [comment]
Hi @andyyumiao , Please tell us more about the infra setup. Which type of instances are being used so that we can reproduce this at our end. Ideally, if there are no running workflows then memory usage should be very less.

**Comment by andyyumiao** [comment]
> Hi @andyyumiao , Please tell us more about the infra setup. Which type of instances are being used so that we can reproduce this at our end. Ideally, if there are no running workflows then memory usage should be very less.

@manan164 @aravindanr thanks for the reply, I'll close the question first and look for other factors that may cause memory usage
