### ISSUE TITLE
configurable task timeout

### ISSUE THREAD

**Issue by SebastienDorgan** [Netflix/conductor#282]
Hi,
The timeout of a task is defined definition level, but the execution time of a task can very be variable depending on input parameter. Don't you think it could be interresting to define/orverload it a workflow level, or even better to define/overload it dynamically.
Regards,
Sébastien

**Comment by v1r3n** [comment]
Hi,

yes, this is indeed quite helpful, and something we have it in mind longer term.  Not supported at the moment though.

**Comment by josephrjd** [comment]
Hi,

Is this still in road map, I am finding this very useful while designing generic workflows and sub-workflows.
If there is any workaround for timeout parameter, let the thread know, I am trying to use something similar

Regards,
Joseph Joshy

**Comment by kishorebanala** [comment]
@josephrjd We couldn't get to prioritizing this over other features in Conductor 2.0 or 3.0; If you have bandwidth to help with this, Please feel free to open a Github issue with a proposal to get the ball rolling. Thanks!
