### ISSUE TITLE
Dynamic Fork Issue

### ISSUE THREAD

**Issue by dcompgriff** [Netflix/conductor#287]
So, it looks like maybe this is an issue with the documentation, but I had a few head aches before I actually figured out how to fix this problem. So the dynamic fork documentation on this page: https://netflix.github.io/conductor/metadata/systask/#dynamic-fork, specifies and example task definition as follows:

```
{
  "dynamicTasks": "${taskA.output.dynamicTasksJSON}",
  "dynamicTasksInput": "${taskA.output.dynamicTasksInputJSON}",
  "type": "FORK_JOIN_DYNAMIC",
  "dynamicForkTasksParam": "dynamicTasks",
  "dynamicForkTasksInputParamName": "dynamicTasksInput"
}
```

When using this form of dynamic fork task definition, the conductor kept returning the following error: 
'Netflix conductor "Input to the dynamically forked tasks is not a map"'

I then looked at the kitchen sink workflow, and found the following code:

```
{
        "name": "dynamic_fanout",
        "taskReferenceName": "fanout1",
        "inputParameters": {
          "dynamicTasks": "${task_4.output.dynamicTasks}",
          "input": "${task_4.output.inputs}"
        },
        "type": "FORK_JOIN_DYNAMIC",
        "dynamicForkTasksParam": "dynamicTasks",
        "dynamicForkTasksInputParamName": "input",
        "startDelay": 0
}
```

So, I then use the following task definition, and the flow started working:
```
{
  "inputParameters": {
          "dynamicTasks": "${taskA.output.dynamicTasksJSON},
          "dynamicTasksInput":  "${taskA.output.dynamicTasksInputJSON}"
  },
  "dynamicTasks": "${taskA.output.dynamicTasksJSON}",
  "dynamicTasksInput": "${taskA.output.dynamicTasksInputJSON}",
  "type": "FORK_JOIN_DYNAMIC",
  "dynamicForkTasksParam": "dynamicTasks",
  "dynamicForkTasksInputParamName": "dynamicTasksInput"
}
```

So, maybe this is expected behavior and the documentation should be updated, or this is a bug, and the conductor code should be updated.

**Comment by apanicker-nflx** [comment]
Thanks for the feedback. The documentation has been updated to use the correct format.
