### ISSUE TITLE
Conductor UI - Search with workflowType , Status not returning any results.

### ISSUE THREAD

**Issue by sukruthiarjula** [Netflix/conductor#2875]
### Discussed in https://github.com/Netflix/conductor/discussions/2871

<div type='discussions-op-text'>

<sup>Originally posted by **sukruthiarjula** March 23, 2022</sup>
We are upgrading to v3.6.0 with ES7 , build is successful and while testing in Conductor UI search with workflowType and Status not returning any result. Search with workflowId is working fine. May I know what would be the reason for this??</div>

**Comment by manan164** [comment]
Hi @sukruthiarjula , Can you please check whether this [property ](https://github.com/Netflix/conductor/blob/main/server/src/main/resources/application.properties#L19)is enabled or not?

**Comment by sukruthiarjula** [comment]
Yes the property is enabled conductor.indexing.enabled=true

**Comment by manan164** [comment]
Hi @sukruthiarjula , If that is enabled then the only possibility is indexing calls may be failing. Can you please check and share logs?

**Comment by sukruthiarjula** [comment]
I don't see any errors in the logs, just the below log.

conductor-auth      | 172.18.0.1 - superglue [24/Mar/2022:17:30:54 +0000] "GET /api/workflow/search?start=0&size=15&sort=startTime%3ADESC&freeText=%2A&query=status%20IN%20%28COMPLETED%29 HTTP/1.1" 200 61 "http://localhost/?status=COMPLETED" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36" "-"

**Comment by sukruthiarjula** [comment]
@maheshyaddanapudi Can you help me out if you can replicate this issue on your side, I tried with 3.x with ES6 & 7. I get the same issue, search with workflowType is not returning no records and also search with status.

**Comment by maheshyaddanapudi** [comment]
Hi @sukruthiarjula 

Please help with the error you see on screen. If no error appears and the page just goes blank? I suspect the API calls are either not returning data or the JSON format changed and may be page is not about to render (which should not be the case). 

Please pass along the properties file you are using as well, I will spin up the setup in my local and debug and get back to you.

**Comment by erikbrgr** [comment]
Have you tried just appending `/api/workflow/search?start=0&size=15&sort=startTime%3ADESC&freeText=%2A&query=status%20IN%20%28COMPLETED%29` to the Conductor UI url? Like, when on localhost: http://localhost:5000/api/workflow/search?start=0&size=15&sort=startTime%3ADESC&freeText=%2A&query=status%20IN%20%28COMPLETED%29

What does that return? I expect something like:
![image](https://user-images.githubusercontent.com/19207888/161430467-76e3492b-9110-4773-a76d-6ede7d34dc70.png)

This is on 3.5.1.

**Comment by erikbrgr** [comment]
@sukruthiarjula I left some comments on the original discussion #2871. We probably want to continue the discussion, here, in the issue, but I thought I'd mention it, just in case :)

**Comment by sukruthiarjula** [comment]
@erikbrgr Thanks for your response

This is my UI screen, I have two workflows in the COMPLETED Status. 
![image](https://user-images.githubusercontent.com/72470104/161584206-4331b28a-1b9c-4525-949a-51d3e5bfed99.png)

The result by appending /api/workflow/search?start=0&size=15&sort=startTime%3ADESC&freeText=%2A&query=status%20IN%20%28COMPLETED%29 to the URL is below

{
"totalHits": 0,
"results": []
}

The above is for v3.6.0 and ES7. I will try to setup  v3.5.1 as you mentioned and get back to you.

**Comment by sukruthiarjula** [comment]
Workflows are executing  properly with v3.6.1/ES6, the only issue is  **search with workflowType and also with Status returning no results in Conductor UI. The search with workflowId is working fine.** 

As v3.x doesn't support embedded Elastic Search I have been running Elastic search locally, is that the issue with mappings??
