### ISSUE TITLE
Is it possible to check empty input values and change them with default within the ${} expression?

### ISSUE THREAD

**Issue by AliakseiBuhakou** [Netflix/conductor#2884]
### Discussed in https://github.com/Netflix/conductor/discussions/2878

<div type='discussions-op-text'>

<sup>Originally posted by **AliakseiBuhakou** March 28, 2022</sup>
Hello. Could you please guide me with following question.
There is an workflow example.
`{
			"name": "task1",
			"taskReferenceName": "task1",
			"inputParameters": {
				"http_request": {
					"uri": "some_uri",
					"method": "POST",
					"body": { some_body
					},
					"connectionTimeOut": "600000",
					"readTimeOut": "600000",
					"headers": {
						"header1": "${workflow.input.header1}"
					}
				}
			}`

The value for "header1": "${workflow.input.header1}" is optional. Is it possible to check the value and change it with some default string? It can be solved with some JSON_JQ_TRANSFORM probably, is there a way to do this without lambda? The reason of the question is that on Conductor v3+ it fails with NPE if value is not provided, Conductor v2+ works fine</div>

**Comment by jxu-nflx** [comment]
Duplicate in thread: https://github.com/Netflix/conductor/discussions/2878 So close this one
