### ISSUE TITLE
Tasks saving in DAO

### ISSUE THREAD

**Issue by fthankac** [Netflix/conductor#2893]
**Describe the bug**
During schedule task (Method Name : scheduleTask) in WorkflowExecutor (core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java) line number 1718 doesn't return the taskmodel after saving the tasks in the DAO.

executionDAOFacade.createTasks(tasks);

Previously it used to return only saved tasks. The saved tasks are used for further processing.

Now the input passed (i.e All the tasks) to createTasks are used for further processing. Also the local variable 'createdTasks' is not used anywhere.

Example:-

// Save the tasks in the DAO
executionDAOFacade.createTasks(tasks);
List systemTasks =
tasks.stream()
.filter(task -> systemTaskRegistry.isSystemTask(task.getTaskType()))
.collect(Collectors.toList());

**Comment by apanicker-nflx** [comment]
Responed in #2888
