### ISSUE TITLE
[DOC]: Dead link for installing and running conductor in production

### ISSUE THREAD

**Issue by ProjectFrank** [Netflix/conductor#2913]
## What are you missing in the docs
<img width="731" alt="image" src="https://user-images.githubusercontent.com/8015872/162751794-48b1a38c-ca40-4d74-8e52-7521800826b7.png">

The above link on the [architecture page](https://netflix.github.io/conductor/architecture/) is dead and leads to a 404 page. Looking through the docs files, it's not clear whether the source for this page actually exists.

## Proposed text
It would be fantastic to have some documentation about running conductor in production, in addition to the existing instructions for running the in-memory version to try it out.

**Comment by apanicker-nflx** [comment]
Thanks for bringing this to our attention. We are currently working on improving our documentation and will update this section soon.

**Comment by peterlau** [comment]
Should be fixed with docsite update.
