### ISSUE TITLE
Conductor does not start up when configured with multiple dynomite hosts.

### ISSUE THREAD

**Issue by roberto-goncalves** [Netflix/conductor#292]
Hi, I'm having the following issue, after configuring correctly the dynomite cluster, and setting my server.properties file like:
`db=dynomite
workflow.dynomite.cluster.hosts=172.30.0.69:8102:us-east-1a;172.30.0.236:8102:us-east-1a`

It works well, because both 69 and 236 have redis and dynomite running. Like it should be, just for details, 69 is configured as a data-center1 and 236 is configured as data-center2, and it is replicating normally, there is no problem in the dynomite cluster configuration. But, the interesting part comes now, when I kill redis-server on 69, Conductor does not accept any requests, with the no hosts exception:

`{code=INTERNAL_ERROR, message=INTERNAL_ERROR - FatalConnectionException: [host=Host [hostname=UNKNOWN, ipAddress=UNKNOWN, port=0, rack: UNKNOWN, datacenter: UNKNOW, status: Down], latency=0(0), attempts=1]redis.clients.jedis.exceptions.JedisDataException: ERR Storage: Dynomite's current state does not allow this request, instance=ip-172-30-0-97}`

My question is, since conductor allow multiple hosts, when 69 is down, conductor have to stay up and redirect requests for 236? Another test put me in the same case, changing the 69 with 236, Conductor worked fine, so, seems that he works only if the first host is up.
Another test, when conductor-server is down and just 236 is running and 69 is down, Conductor does not start, it gives the same error. Is there something I am missing? Thank you.

**Comment by v1r3n** [comment]
@roberto-goncalves Conductor uses a quorum connections with dynomite. If you set it up with 2 nodes and one node goes down, it will not be able to achieve quorum for reads/writes and fail the requests.  For HA, you need at-least 3 node dynomite cluster.

@ipapapa for further comments on Dynomite configurations.

**Comment by ipapapa** [comment]
The two Dynomite/Redis nodes are both deployed in the same AZ. You probably want to deploy them in different AZs. @v1r3n comments still hold about quorum.

**Comment by roberto-goncalves** [comment]
@v1r3n @ipapapa Thank you for replying. So, what is an AZ? Amazon Zone? I can't find the meaning on the documentation.

**Comment by ipapapa** [comment]
@roberto-goncalves it is Availability Zone. More information: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html

**Comment by roberto-goncalves** [comment]
@ipapapa Thank you! I will try it and close this.

**Comment by roberto-goncalves** [comment]
Do you think it would be interesting put a hint about this on the documentation?

**Comment by roberto-goncalves** [comment]
Well, I've tried deploying on different AZs. Like this:

`workflow.dynomite.cluster.hosts=172.30.0.69:8102:us-east-1a;172.30.1.233:8102:us-east-1b`

And still it is just considering the first. Even if I switch them:

`workflow.dynomite.cluster.hosts=172.30.1.233:8102:us-east-1b;172.30.0.69:8102:us-east-1a`

Any ideas?

**Comment by ipapapa** [comment]
Did you try using 3 AZs for at least to make sure that the quorum request from Conductor is satisfied?

**Comment by roberto-goncalves** [comment]
Yes, I've built this configuration now:

`workflow.dynomite.cluster.hosts=172.30.0.69:8102:us-east-1a;172.30.1.233:8102:us-east-1b;172.30.2.88:8102:us-east-1c`

It says everything its fine:

```
50   [pool-3-thread-2] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 3 of 3 to Host [hostname=172.30.2.88, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up]
52   [pool-3-thread-3] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 3 of 3 to Host [hostname=172.30.1.233, ipAddress=null, port=8102, rack: us-east-1b, datacenter: us-east-1, status: Up]
52   [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 3 of 3 to Host [hostname=172.30.0.69, ipAddress=null, port=8102, rack: us-east-1a, datacenter: us-east-1, status: Up]
```
When I remove the redis-server job from 69, it says:

`ERROR com.netflix.dyno.connectionpool.impl.health.ConnectionPoolHealthTracker  - Attempting to reconnect pool to host PoolExhaustedException: [host=Host [hostname=172.30.0.69, ipAddress=null, port=8102, rack: us-east-1a, datacenter: us-east-1, status: Up], latency=0(0), attempts=0]Fast fail - NO ACTIVE CONNECTIONS in pool due to PoolExhaustedException: 172.30.0.69`

The same error with one or two Dynomite/Redis cluster.

**Comment by ipapapa** [comment]
@roberto-goncalves the error that conductor provides is a marshaled error from what Dynomite would provide, so I am not fully aware of the issue. @v1r3n can help with that. Having said that, if you stop Redis in 1/3 instances, then Dyno should work fine because 2/3 instances are fine (as long as there is no entropy in the cluster). If you stop Redis in 1/2 instance, then Dynomite would create an exception that Quorum has not been achieved. I am assuming that exception is what Dyno-queues is marshaling as `Dynomite's current state does not allow this request`.

It also seems that the errors you see in the last post are not the same as the errors you were seeing in the first post. So you have done some progress in resolving the aforementioned issue. The issue you are having is because Dyno does not understand that Dynomite is down. @v1r3n how does OSS Conductor notifies Dyno that a node is down (in this case because of Redis) without Eureka?

**Comment by gauravmishrakec** [comment]
@roberto-goncalves : Any update on this, I am facing same issue.
