### ISSUE TITLE
Latest build fails on JDK 17 with 'No such property' error

### ISSUE THREAD

**Issue by rickfish** [Netflix/conductor#2925]
Trying to build the latest release (3.7.2) on JDK 17.0.2 fails with this exception: 
> Task :conductor-es7-persistence:shadowJar FAILED
ex
groovy.lang.MissingPropertyException: No such property: count for class: com.github.jengelman.gradle.plugins.shadow.transformers.ServiceFileTransformer

Using JDK 11 the build works fine.

**Comment by aravindanr** [comment]
Thanks for bringing this up. The build is not verified on JDK 17. We don't have any immediate plans to verify and support it.
