### ISSUE TITLE
[DOC]: vipAddress in Httptask list

### ISSUE THREAD

**Issue by npk1994** [Netflix/conductor#2939]
Greetings everyone.
We are looking for proper documentation on usage of vipAddress in https tasks.

We have Kuberenetes setup where conductor-server is running as a pod along with our application services. We are trying to use the service name for the discovery and want to provide the name in vipAddress(if possible) instead of providing the complete uri endpoints.

Really appreciate your response.

Thank you in Advance!

**Comment by npk1994** [comment]
Hi Team,
 We are looking for any examples on how to use this vipAddress.

**Comment by jxu-nflx** [comment]
Hello @npk1994, when use `vipAddress`, the domain part can be left out in the `URI` field. See [this](https://github.com/Netflix/conductor/blob/main/core/src/test/resources/completed.json#L516) for an example.
