### ISSUE TITLE
Does conductor work only in the cloud ?

### ISSUE THREAD

**Issue by smilejinho** [Netflix/conductor#294]
I am new to here and want to test "Conductor", but I am having troble to install... I am trying ...
I have a question about "Conductor".
I can see "Conductor is an orchestration engine that runs in the cloud."
Dose conductor work only in the cloud ? I want to use conductor on bare metal linux servers.

**Comment by v1r3n** [comment]
@smilejinho conductor can run on bare metal linux too.  There is nothing specific about cloud.
