### ISSUE TITLE
UI Workflow Executions Grid not loading

### ISSUE THREAD

**Issue by jegadjame** [Netflix/conductor#2942]
Hi ,
I am using node-v16.14.2-x64 , jdk11, conductor-server-3.3.4-boot and downloaded latest code. When i trigger workflow, I am not seeing any data in Workflow Executions Grid. But records are getting processed. I can see data in Task Queue.

Please let me know if anything i am missing.

![image](https://user-images.githubusercontent.com/5119603/164649237-3edf6120-e427-47d2-b8b9-5cf209765501.png)

Thanks,
Jegadeesh

**Comment by jxu-nflx** [comment]
Hello @jegadjame when that page load, it will try to call this api `/workflow/search?start=0&size=15&sort=startTime:DESC&freeText=*&query=`. Can you try run that API directly to see whether you are getting any response back? Also, the workflow execution search requires ES for indexing, do you have that enabled?

**Comment by manishkushwaha1412** [comment]
I am also facing this issue, tried calling API it seems API itself is not returning response. I tried it through swagger by same input provided in the browser network tab. 
Through UI - http://localhost:5000/api/workflow/search?start=0&size=15&sort=startTime%3ADESC&freeText=%2A&query=
Through Swagger - http://localhost:8080/api/workflow/search?start=0&size=100
swagger search i did open without any condition to get at least some result. However, I didn't get the same.

Do you have any update on this? Appreciate your response.

**Comment by jegadjame** [comment]
> I am also facing this issue, tried calling API it seems API itself is not returning response. I tried it through swagger by same input provided in the browser network tab. Through UI - http://localhost:5000/api/workflow/search?start=0&size=15&sort=startTime%3ADESC&freeText=%2A&query= Through Swagger - http://localhost:8080/api/workflow/search?start=0&size=100 swagger search i did open without any condition to get at least some result. However, I didn't get the same.
> 
> Do you have any update on this? Appreciate your response.

I am not getting any response
{
  "totalHits": 0,
  "results": []
}

**Comment by aravindanr** [comment]
Related to #2959

**Comment by jxu-nflx** [comment]
@jegadjame Can you check your config to make sure the es index is enabled: https://github.com/Netflix/conductor/blob/main/server/src/main/resources/application.properties#L19 Also if you are running it locally, please make sure you have the ES docker container up running as well

**Comment by manishkushwaha1412** [comment]
@jxu-nflx in below file, do you want to change false to true and give it a try ? when i did that I started getting some another exception. Server is getting started but UI is not able to call service exposed to 8080 port.
https://github.com/Netflix/conductor/blob/main/server/src/main/resources/application.properties#L19

**Comment by jxu-nflx** [comment]
@manishkushwaha1412 if you don't have that config set to true, then basically means your UI search function will be broken, i.e. you couldn't search any workflow executions in UI. 

> Server is getting started but UI is not able to call service exposed to 8080 port.
What is the error you are seeing? Are you able to call any server api at all?

**Comment by edoang** [comment]
Hi @jxu-nflx , today i've cloned the latest release. 
docker-compose build and docker-compose up. 
i have the same behaviour, elastic is up on localhost 9200.

docker/server/config/config.properties  : 

conductor.indexing.enabled=true
conductor.elasticsearch.url=http://es:9200

can you help me find the problem?

**Comment by edoang** [comment]
@jxu-nflx oh so simple :) thank you very much!

**Comment by manishkushwaha1412** [comment]
@jxu-nflx 
I am not able to build it locally even through docker-compose as well. Its giving.

**Comment by jxu-nflx** [comment]
> @jxu-nflx I am not able to build it locally even through docker-compose as well. Its giving.

what is the docker-compose command you use? And what is the error message?
