### ISSUE TITLE
[QUESTION]: how to update workflow parameter value with a task output?

### ISSUE THREAD

**Issue by ladenjet** [Netflix/conductor#2967]
I have such requirements: 
1.  at the start of the workflow, I need to  put some common parameters (such as journal number, current timestamp, etc) into workflow parameters.  These workflow parameters should be generated by program fraction,  not from input. 

2. Maybe some workflow parameter should be updated by some tasks in some cases .

Can somebody please help to tell me how to make above happen?

Thanks in advance.

**Comment by manan164** [comment]
Hi @ladenjet ,
For 1. The workflow input can be in the form JSON and that JSON can be dynamic. So we can add dynamic attributes.
For 2. Since tasks are updating these params we can have task output to generate these params and all subsequent tasks can use these params.

**Comment by ladenjet** [comment]
> Hi @ladenjet , For 1. The workflow input can be in the form JSON and that JSON can be dynamic. So we can add dynamic attributes. For 2. Since tasks are updating these params we can have task output to generate these params and all subsequent tasks can use these params.

Thanks for your reply. 
But my point is :
1. how to add workflow parameters by program, not by input?
2. how to update workflow parameter value by a task?

**Comment by dcore94** [comment]
You could use set_variable task for this. Instead of setting workflow inputs you set workflow.variables and then access it in future steps.

https://netflix.github.io/conductor/reference-docs/set-variable-task/

**Comment by ladenjet** [comment]
> You could use set_variable task for this. Instead of setting workflow inputs you set workflow.variables and then access it in future steps.
> 
> https://netflix.github.io/conductor/reference-docs/set-variable-task/

Thanks.  I have read it.
 but take the following task definition for example, 
the task set the value 'Orkes' directily to key 'name',  but in most cases, value should be generated by program, not from definition.
I mean, how to compose the variable set logic program....
```
{
      "name": "Set_Name",
      "taskReferenceName": "Set_Name",
      "type": "SET_VARIABLE",
      "inputParameters": {
        "name": "Orkes"
      }
    }
```

**Comment by dcore94** [comment]
{
      "name": "Set_Name",
      "taskReferenceName": "Set_Name",
      "type": "SET_VARIABLE",
      "inputParameters": {
        "name": "${othertask.output.mycomputedparam}"
      }
    }

**Comment by ladenjet** [comment]
Thank you all.
