### ISSUE TITLE
conductor-ui: Error from chokidar: Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by meilinkm** [Netflix/conductor#2984]
When running conductor-ui, many errors from chokidar can be observed, indicating that the system limit for number of file watchers has been reached, for example:

`# docker logs d52333e094fa
yarn run v1.22.17
$ react-scripts start
[HPM] Proxy created: /  -> http://conductor-server:8080
ℹ ｢wds｣: Project is running at http://172.25.0.5/
ℹ ｢wds｣: webpack output is served from
ℹ ｢wds｣: Content not from webpack is served from /usr/src/app/public
ℹ ｢wds｣: 404s will fallback to /
Starting the development server...

Compiled successfully!

You can now view client in the browser.

  Local:            http://localhost:5000
  On Your Network:  http://172.25.0.5:5000

Note that the development build is not optimized.
To create a production build, use yarn build.

Error from chokidar (/usr/src/app/node_modules/@emotion/memoize/dist): Error: ENOSPC: System limit for number of file watchers reached, watch '/usr/src/app/node_modules/@emotion/memoize/dist'
Error from chokidar (/usr/src/app/node_modules/@material-ui/core/esm/AccordionActions): Error: ENOSPC: System limit for number of file watchers reached, watch '/usr/src/app/node_modules/@material-ui/core/esm/AccordionActions'
Error from chokidar (/usr/src/app/node_modules/@material-ui/core/esm/Avatar): Error: ENOSPC: System limit for number of file watchers reached, watch '/usr/src/app/node_modules/@material-ui/core/esm/Avatar'`

I know I can avoid these settings, by running this:

sysctl -w fs.inotify.max_user_watches = 16384

The default setting on Linux is 8192. 

These errors indicate that more than 8192 files are being watched, and thus the system runs out of available inodes, and the limit needs to be increased.

This page about chokidar: https://github.com/paulmillr/chokidar, indicates that one should be judicious about not wasting system resources by watching much more than needed. Watching over 8192 files seems excessive.

Is it possible to limit and/or disable the file watching for conductor-ui, so that these alerts  no longer show up in the log?

**Comment by peterlau** [comment]
Unfortunately, this is a side effect of the `react-scripts` dev server which watches all files for changes including those in  `node_modules`, and affects all use cases of `create-react-app`. See https://github.com/facebook/create-react-app/issues/7612

Unless you're developing the UI actively, you can run the built assets rather than using the dev server.  (assuming the backend is already running on port 8080)

```
cd ui
yarn run build
yarn add -g serve http-proxy-cli

serve build
http-proxy -p 5000 localhost:3000 /api=localhost:8080/api
```
This hosts the static built assets at `localhost:3000` and proxies, that, and the api to port 5000.
The website should be accessible at `localhost:5000`.
