### ISSUE TITLE
Go client package out of date

### ISSUE THREAD

**Issue by LemonDevv** [Netflix/conductor#2985]
I am using the go client in my worker. I followed the instructions on how to get this client.

`go get github.com/netflix/conductor/client/go`

When I tried to use it I was getting a 404 due to it trying to call an ack end point that doesn't exist. A little bit of research shows that the actual code base in git for the go client has changed but the package has not been updated resulting in my worker using an out of date client. 

What can I do?

**Comment by apanicker-nflx** [comment]
@LemonDevv Please use the go client from https://github.com/conductor-sdk/conductor-go instead. This golang client and sdk is actively maintained and we will be deprecating the client published from polyglot-clients.
