### ISSUE TITLE
Not able to connect cassandra BD in netflix conductor-v3.8.0

### ISSUE THREAD

**Issue by 9769776073** [Netflix/conductor#2991]
Source Code : https://github.com/Netflix/conductor/tree/v3.8.0

Default set up is running with Redis in memory DB. 

I want to connect cassandra DB running in my local-system. I have done some application.properties change
**conductor.db.type=cassandra**

After that I am able to connect local cassandra BD , please check below screen-shot : 
![image](https://user-images.githubusercontent.com/105768261/168959419-ad8e117c-3ebd-496a-aee8-68fd3cc6ccec.png)

After that It is throwing bean dependency error : Parameter 0 of constructor in com.netflix.conductor.core.events.queue.ConductorEventQueueProvider required a bean of type 'com.netflix.conductor.dao.QueueDAO' that could not be found.

Please check below screenshot : 
![image](https://user-images.githubusercontent.com/105768261/168959649-0db0defd-23b4-4514-9be4-3c5fad6df024.png)

Could you please provide the configuration details to connect cassandra DB.

**Comment by apanicker-nflx** [comment]
The cassandra persistence layer does not provide an implementation of the queueing layer (QueueDAO). All other DAO implementations are provided however.

You would need to wire up another queue dao implementation (Redis,Postgres,MySQL etc) or roll your own custom queue implementation if you choose to.
