### ISSUE TITLE
Installation and admin guide

### ISSUE THREAD

**Issue by sushena** [Netflix/conductor#301]
Hi Team,

am looking for conductor installation admin and kickoff guide. Can someone please assists me on this?

**Comment by v1r3n** [comment]
@sushena https://netflix.github.io/conductor/ should help you.

**Comment by smilejinho** [comment]
Hi Team~
First, thanks for sharing really nice module.

I also having troble to install.  And, I have already read https://netflix.github.io/conductor/ install guide,
but I think I need more detail installation step guide.
I am not familiar with dynomite, elasticsearch. So, if there is any configuration steps after install redis, dynomite, elasticsearch, these configuration guide is also needed.

I am trying using my centos 7 linux server. But when I build. it stops on below line.
---------------------------------------------------------------------------------------------
10266 [main] INFO  com.netflix.conductor.server.ConductorServer  - Kitchen sink workflows are created!
> Building 96% > :conductor-server:server

Please help us...

**Comment by v1r3n** [comment]
Closing this - please reopen if you need further help.
