### ISSUE TITLE
PostgreSql database

### ISSUE THREAD

**Issue by LemonDevv** [Netflix/conductor#3016]
I have set up my conductor-server to make use of the Postgres db type.

Both an instance of postgres and conductor-server are deployed to k8s. However on the start-up of the conductor-server i am getting the below errors:

`Parameter 2 of constructor in com.netflix.conductor.core.execution.DeciderService required a bean of type 'com.netflix.conductor.dao.MetadataDAO' that could not be found.`

`org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.conductor.dao.MetadataDAO' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}`

The conductor-server and postgres instance are deployed to the same cluster + namespace in k8s and i reference the host by using the service name of the postgres instance.

I'm not sure why i am getting the above error - is this because i need to implement something?

**Comment by LemonDevv** [comment]
Can close this. Found out I have to pull dependencies from the conductor-communjty for postgres. Bit weird as in the statement of their readme it says that conductor server pulls in the dependencies.

**Comment by ZergRushJoe** [comment]
@LemonDevv what did you have to do, I having the same error on 3.8.3 but not on 3.5

**Comment by LemonDevv** [comment]
@ZergRushJoe 

You have to add the below for 3.8.3 to the build dependencies. You get it maven repository


`
runtimeOnly group: 'com.netflix.conductor', name: 'conductor-postgres-persistence', version: '3.8.3'  `
