### ISSUE TITLE
Docker Conductor UI: "## There is an issue with `node-fibers` ##"

### ISSUE THREAD

**Issue by mhdiiilham** [Netflix/conductor#3026]
**Describe the bug**
Hi, I currently trying Netflix Conductor using the `docker-compose.yaml`. When I ran `docker compos up`, the service conductor-ui_1 sent these logs

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/54275113/171673714-308dd9e6-c0da-42b3-9d89-1878cb9c87d8.png">

**Details**
I run it on Mac M1

**To Reproduce**
1. git clone https://github.com/Netflix/conductor.git
2. Change the elasticsearch image to `docker.elastic.co/elasticsearch/elasticsearch:7.10.2` (due to incompatibility with m1)
3. run `docker compose build`
4. run `docker compose up`
5. See the error

Are there any steps that I missing? I also have looked at this Issue https://github.com/Netflix/conductor/issues/1707 but I this it not relevant anymore with the current git version. Thank you in advance 🙇‍♂️

**Comment by jxu-nflx** [comment]
Hello @mhdiiilham This is a known issue, please also check this thread: https://github.com/Netflix/conductor/issues/2975. Feel free to submit a PR after you figure it out.

**Comment by jxu-nflx** [comment]
@peterlau Could you help to take a look at this?

**Comment by Prebiusta** [comment]
I am using *M1 Max* and having the same problem. It is not possible to spin up Conductor UI on new silicon (*arm64*) Mac processor, due to above mentioned error

**Comment by Prebiusta** [comment]
This does not seem to be a problem anymore, I have successfully run UI on the M1 Max chip. @peterlau
