### ISSUE TITLE
server run error : java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by smilejinho** [Netflix/conductor#303]
Hi

I have downloaded conductor-server-1.8.0-all.jar from maven central and run,
but returns Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2.

I have run as
java -jar conductor-server-1.8.0-all.jar ./server.properties ./log4j.properties

Using ./server.properties
Using log4j config ./log4j.properties
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
        at com.netflix.conductor.server.ConductorServer.<init>(ConductorServer.java:105)
        at com.netflix.conductor.server.Main.main(Main.java:52)

with server.properties as

db=dynomite
workflow.dynomite.cluster.hosts=127.0.0.1:8102
workflow.dynomite.cluster.name=dyno_cluster_name
workflow.namespace.prefix=conductor
workflow.namespace.queue.prefix=conductor_queues
queues.dynomite.threads=10
queues.dynomite.nonQuorum.port=22122
workflow.elasticsearch.url=localhost:9300
workflow.elasticsearch.index.name=conductor
conductor.additional.modules=class_extending_com.google.inject.AbstractModule

and, log4j.properties as

log4j.rootLogger=INFO, A1
log4j.appender.A1=org.apache.log4j.ConsoleAppender
log4j.appender.A1.layout=org.apache.log4j.PatternLayout
log4j.appender.A1.layout.ConversionPattern=%-4r [%t] %-5p %c %x - %m%n

**Comment by v1r3n** [comment]
@smilejinho do you have the full stacktrace you can share?

**Comment by smilejinho** [comment]
This is all I can see...

java -jar conductor-server-1.8.0-all.jar ./server.properties ./log4j.properties
Using ./server.properties
Using log4j config ./log4j.properties
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
        at com.netflix.conductor.server.ConductorServer.<init>(ConductorServer.java:105)
        at com.netflix.conductor.server.Main.main(Main.java:52)

**Comment by smkb80** [comment]
The expected format of **workflow.dynomite.cluster.hosts** in server.properties is **host:port:rack** but in your case its **host:port**. The rack should be same as that mentioned in dynomite configuration yml

The ConductorServer constructor splits the above property on ':' . Since split is returning only 2 element array (instead of 3 elements) in your case, the constructor is throwing ArrayIndexOutOfBoundsException: 2

**Comment by v1r3n** [comment]
@smilejinho The suggestion above should resolve the issue.  Please close the issue if so.

**Comment by smilejinho** [comment]
Thanks. 
I changed the server.properties as
>
db=dynomite
workflow.dynomite.cluster.hosts=127.0.0.1:8102:rack1
workflow.dynomite.cluster.name=dyno_cluster_name
workflow.namespace.prefix=conductor
workflow.namespace.queue.prefix=conductor_queues
queues.dynomite.threads=10
queues.dynomite.nonQuorum.port=22122
workflow.elasticsearch.url=localhost:9300
workflow.elasticsearch.index.name=conductor
conductor.additional.modules=class_extending_com.google.inject.AbstractModule

But, I have another error

root@bootstrap:/data> java -jar conductor-server-1.8.0-all.jar ./server.properties ./log4j.properties
Using ./server.properties
Using log4j config ./log4j.properties
0    [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
8    [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Adding host connection pool for host: Host [hostname=127.0.0.1, ipAddress=null, port=8102, rack: rack1, datacenter: rack, status: Up]
9    [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Priming connection pool for host:Host [hostname=127.0.0.1, ipAddress=null, port=8102, rack: rack1, datacenter: rack, status: Up], with conns:3
54   [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 3 of 3 to Host [hostname=127.0.0.1, ipAddress=null, port=8102, rack: rack1, datacenter: rack, status: Up]
Exception in thread "main" java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 0
        at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:3383)
        at com.netflix.dyno.jedis.DynoJedisClient$Builder.buildDynoJedisClient(DynoJedisClient.java:3352)
        at com.netflix.dyno.jedis.DynoJedisClient$Builder.build(DynoJedisClient.java:3271)
        at com.netflix.conductor.server.ConductorServer.init(ConductorServer.java:152)
        at com.netflix.conductor.server.ConductorServer.<init>(ConductorServer.java:115)
        at com.netflix.conductor.server.Main.main(Main.java:52)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.calculateReplicationFactor(HostSelectionWithFallback.java:394)
        at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.initWithHosts(HostSelectionWithFallback.java:351)
        at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.initSelectionStrategy(ConnectionPoolImpl.java:627)
        at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.start(ConnectionPoolImpl.java:526)
        at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:3366)
        ... 5 more


dynomite.yml is
dyn_o_mite:
  listen: 127.0.0.1:8102
  dyn_listen: 127.0.0.1:8101
  tokens: '101134286'
  servers:
  - 127.0.0.1:22122:1
  data_store: 0
  mbuf_size: 16384
  max_msgs: 300000

**Comment by smkb80** [comment]
In Dynomite configuration yml introduce 2 new properties viz. **datacenter** and **rack** and restart dynomite followed by conductor. In your case the entries should look like:
```
rack: rack1
datacenter: rack
```
Since I didn't try these in my local setup, I am not sure this will fix your problem. Maybe @v1r3n can confirm.

**Comment by esidorov** [comment]
I seem to have exactly the same issue trying to run conductor in a non-dynamite redis mode.

i.e.

```
db=redis
workflow.dynomite.cluster.hosts=192.168.99.100:22122

```

As well as dyno mode with the config


```
db=dynomite

#Dynomite Cluster details.
#format is host:port:rack separated by semicolon  
workflow.dynomite.cluster.hosts=192.168.99.100:22122:rack1

#namespace for the keys stored in Dynomite/Redis 
workflow.namespace.prefix=conductor

#namespace prefix for the dyno queues
workflow.namespace.queue.prefix=conductor

#no. of threads allocated to dyno-queues
queues.dynomite.threads=10

#non-quorum port used to connect to local redis.  Used by dyno-queues 
queues.dynomite.nonQuorum.port=22122

Transport address to elasticsearch
workflow.elasticsearch.url=localhost:9200

#Name of the elasticsearch cluster
workflow.elasticsearch.index.name=elasticsearch_test

# For a single node dynomite or redis server, make sure the value below is set to same as rack specified in the "workflow.dynomite.cluster.hosts" property.
EC2_AVAILABILTY_ZONE=rack1

```

And I dynomite config

```

dyn_o_mite:
  dyn_listen: 0.0.0.0:8101
  data_store: 0
  listen: 0.0.0.0:8102
  dyn_seed_provider: simple_provider
  servers:
  - 127.0.0.1:22122:1
  tokens: 437425602
  stats_listen: 0.0.0.0:22222
  rack: rack1
  datacenter: rack


```
I'm getting

> 
> 1088 [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
> 1091 [pool-5-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Adding host connection pool for host: Host [hostname=192.168.99.100, ipAddress=null, port=22122, rack: rack1, datacenter: rack, status: Up]
> 1091 [pool-5-thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Priming connection pool for host:Host [hostname=192.168.99.100, ipAddress=null, port=22122, rack: rack1, datacenter: rack, status: Up], with conns:3
> 1110 [pool-5-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 3 of 3 to Host [hostname=192.168.99.100, ipAddress=null, port=22122, rack: rack1, datacenter: rack, status: Up]
> Exception in thread "main" java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 0
> 	at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:3383)
> 	at com.netflix.dyno.jedis.DynoJedisClient$Builder.buildDynoJedisClient(DynoJedisClient.java:3352)
> 	at com.netflix.dyno.jedis.DynoJedisClient$Builder.build(DynoJedisClient.java:3271)
> 	at com.netflix.conductor.server.ConductorServer.init(ConductorServer.java:158)
> 	at com.netflix.conductor.server.ConductorServer.<init>(ConductorServer.java:120)
> 	at com.netflix.conductor.server.Main.main(Main.java:52)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
> 	at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.calculateReplicationFactor(HostSelectionWithFallback.java:394)
> 	at com.netflix.dyno.connectionpool.impl.lb.HostSelectionWithFallback.initWithHosts(HostSelectionWithFallback.java:351)
> 	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.initSelectionStrategy(ConnectionPoolImpl.java:627)
> 	at com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl.start(ConnectionPoolImpl.java:526)
> 	at com.netflix.dyno.jedis.DynoJedisClient$Builder.startConnectionPool(DynoJedisClient.java:3366)
> 	... 10 more
> 
> 

Help appreciated, thank you!

**Comment by v1r3n** [comment]
Take a look at the docs here for the configuration required for a standalone redis/elasticache.

https://netflix.github.io/conductor/server/#using-standalone-redis-elasticache

**Comment by esidorov** [comment]
@v1r3n Oh, somehow I missed that part of documentation, thanks for pointing me to it!
