### ISSUE TITLE
Query all "SCHEDULED" tasks

### ISSUE THREAD

**Issue by cquon** [Netflix/conductor#305]
Hi,

I have a use case where I would like to query for all the scheduled tasks (of any type) instead of polling for scheduled tasks of a specific tasktype.  Currently I have tried the task search API and with status="SCHEDULED" and it seems to be working, but I know this goes through elasticsearch to find the tasks in this state.  Would there be a way to do this without having to go through elasticsearch as I would prefer to eliminate the dependency on elasticsearch if possible.

Thanks.

**Comment by v1r3n** [comment]
@cquon without ES this does not exist today.
