### ISSUE TITLE
[FEATURE]: Netflix Conductor support for JDK 17

### ISSUE THREAD

**Issue by shyamsundarsekhar** [Netflix/conductor#3051]
Please read our [contributor guide](https://github.com/Netflix/conductor/blob/main/CONTRIBUTING.md) before creating an issue.   
Also consider discussing your idea on the [discussion forum](https://github.com/Netflix/conductor/discussions) first.

## Describe the Feature Request
Currently, Netflix Conductor supports JDK 11. Feature request to support JDK 17.

## Describe Preferred Solution
Compatibility with JDK17 to build and deploy with Java 17 Runtime

## Describe Alternatives
Currently there are no alternatives to build and utilise with latest Java 17 Runtime. There was an issue raised earlier where there was confirmation provided that there are no immediate dates / timelines to support JDK 17: https://github.com/Netflix/conductor/issues/2925

Please confirm the roadmap to support latest Java release versions.

**Comment by v1r3n** [comment]
The current blocker to move on to JDK 17 is the use of Nashorn javascript runtime that was removed post JDK 11 releases.  We are currently looking to replace that with an alternative Javascript engine which should enable the path to JDK 17.

**Comment by shyamsundarsekhar** [comment]
@v1r3n  Thank you for the response. Do you have a tentative ETA based on the roadmap on when Conductor would start supporting JDK 17.

**Comment by v1r3n** [comment]
We are expecting to work on this in Q3 of this year.

**Comment by shyamsundarsekhar** [comment]
Thanks @v1r3n  Looking forward to the snapshot with support for JDK 17 in Q3 2022.
