### ISSUE TITLE
Docker Server build seems to boot 2 conductor instances in container

### ISSUE THREAD

**Issue by ZergRushJoe** [Netflix/conductor#3057]
**Describe the bug**
![image](https://user-images.githubusercontent.com/7153267/175044116-7ad2fc3a-89af-4513-bfd9-d504f12774ab.png)
seems on latest 3.9.0-rc it seems to start 2 times in the dockerfile. we upgraded from 3.5.3 before we started see this. We were using postgres and es6 before we moved to the newer version. Also found a oddity that clusterName has to be set for redis sentinel and gets used as the master name. 

**Details**
Conductor version: 3.9.0-rc
Persistence implementation: redis
Queue implementation: redis
Lock: Redis 
![image](https://user-images.githubusercontent.com/7153267/175044742-7046c36f-6101-4860-b667-6ed4f8ec22f1.png)

**To Reproduce**
1. build server docker file and run a non in memory version

**Expected behavior**
to see only one logo on start up

**Screenshots**

**Additional context**
we use a helm chart we made to setup conductor in a kubenetes cluster.  are settings used to be this before
```     # Servers.
    conductor.grpc-server.enabled=false

    # Database persistence type.
    conductor.db.type=postgres

    spring.datasource.url=jdbc:postgresql://{{ .Release.Name }}-db.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.services.database.exposedPort }}/conductor
    spring.datasource.username={{ .Values.db.username }}
    spring.datasource.password={{ .Values.db.password }}

    # Hikari pool sizes are -1 by default and prevent startup
    spring.datasource.hikari.maximum-pool-size=10
    spring.datasource.hikari.minimum-idle=2

    # Elastic search instance indexing is enabled.
    conductor.indexing.enabled=true

    # Transport address to elasticsearch
    conductor.elasticsearch.url=http://{{ .Release.Name }}-elasticsearch.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.services.cache.exposedPort }}

    # Name of the elasticsearch cluster
    conductor.elasticsearch.indexName=conductor

    # Yellow is main cluster node is up and running for elasticsearch
    conductor.elasticsearch.clusterHealthColor=yellow
```

**Comment by ZergRushJoe** [comment]
Additional findings, I have revered back to 3.5.3 and still have the same problem. I looking into my configuration to see what could be causing it.

**Comment by CherishSantoshi** [comment]
@v1r3n @boney9 FYI

**Comment by ZergRushJoe** [comment]
I found my issue with the double start. in my deployment I took from another thread I found the bootstrapping sh along with the cmd in dockerfile was cause it to do run it 2 times
![image](https://user-images.githubusercontent.com/7153267/175064080-a1aecc79-3fc1-4158-a20d-a79497dafbd0.png)
