### ISSUE TITLE
Event task callback

### ISSUE THREAD

**Issue by sangeetanadgir** [Netflix/conductor#306]
Hi,

I have created an event handler which starts a subflow...I want to trigger the same event with some delay of 5 mins based on some condition.Is there any property to set the delay for callback or any way to do this?

Thank you

**Comment by apanicker-nflx** [comment]
This is not currently supported. You could generate the same message on the queue after a delay so that the event handler action is executed again. 
If you wish to implement this enhancement within conductor, we would be happy to review and merge.
