### ISSUE TITLE
[FEATURE]: Add support for OpenTelemetry

### ISSUE THREAD

**Issue by AvitalOfstein** [Netflix/conductor#3068]
Please read our [contributor guide](https://github.com/Netflix/conductor/blob/main/CONTRIBUTING.md) before creating an issue.   
Also consider discussing your idea on the [discussion forum](https://github.com/Netflix/conductor/discussions) first.

## Describe the Feature Request
Integrate OpenTelemetry with Conductor in order to improve observability

## Describe Preferred Solution
Support injection of OpenTelemetry parameters (TraceId, ParentId, SpanId and DateTime) in various use cases (e.g. external http calls, events etc.).

## Describe Alternatives
N/A

**Comment by VerstraeteBert** [comment]
Would still love to see this.
