### ISSUE TITLE
Add persistence support for a MySQL backend

### ISSUE THREAD

**Issue by picaron** [Netflix/conductor#307]
Hi !

We require using our existing MySQL infrastructure as the backend for our conductor instance.

We also would like to avoid to fork our own branch of the project so we are considering submitting a PR in the `contribs` package.

I would just like to make sure that we will have your approval on getting this feature merged so we don't waste our efforts for nothing.

**Comment by v1r3n** [comment]
@picaron I would suggest create a separate module similar to es5-persistence so it can be added in the package build based on the requirements.

**Comment by picaron** [comment]
ok understood, a separate `mysql-persistence` makes more sense indeed

**Comment by v1r3n** [comment]
how do you plan on adding the support for queues?  currently, the queues are implemented using the redis based queue recipe - will you implement the equivalent using mysql?

**Comment by picaron** [comment]
I see. We are trying to figure out how to do this.

We want to use only one backend and re-use our existing MySQL cluster so yes we are considering implementing everything on top of MySQL (except maybe we would reuse the embedded Elasticsearch if the index can be reconstructed every time the app starts). Do you see any major issues in trying to do this?

I'm guessing we are not the only ones who would benefit from a lighter setup using only MySQL ...

Another alternative would be to use RabbitMQ for the queuing, which is already deployed in our environment but ideally we'd like to keep it as simple as possible and use only one backend.

**Comment by picaron** [comment]
Also, I was looking at the `ConductorServer` bootstrap, it seems we will need to add some logic in there to support the new mysql backend right?

**Comment by v1r3n** [comment]
You will have to change the server module to bind the interfaces to your implementation.
For the queueing either you can build a lightweight queuing support using MySQL by implementing [QueueDAO.java](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/dao/QueueDAO.java) or supporting RabbitMQ is also an option - but then I would go with a separate module for that providing flexibility on queues.

+1 to supporting MySQL
