### ISSUE TITLE
Worker count vs thread count

### ISSUE THREAD

**Issue by kpdude7** [Netflix/conductor#308]
Our current configuration is creating one conductor worker for each taskdef, with multiple threads (15); e.g.:

ConductorWorkflowTaskCoordinator coordinator = builder.withWorkers(<list with one worker in it>).withThreadCount(15).withTaskClient(taskClient).build(); 

Is this a valid configuration, or should we be creating multiple workers for the same taskdef, up to the threadCount value? Is it always one thread per worker? Let's say we created 2 workers; how many threads would be assigned to each worker?

**Comment by v1r3n** [comment]
@kpdude7 you should have at-least one thread per worker / taskdef (unless there is a use case not to do).  You can add more threads per workers which will allow processing multiple workers in a single JVM.

**Comment by apanicker-nflx** [comment]
Please follow the documentation [here](https://netflix.github.io/conductor/gettingstarted/client/#workflowtaskcoordinator) on configuring the WorkflowTaskCoordinator.
Multiple workers for the same taskDef would mean that multiple tasks of the same taskDef can be executed at the same time.
>  how many threads would be assigned to each worker?

Currently, threads are not assigned to workers, rather idle workers utilize available threads from the thread pool.
