### ISSUE TITLE
[FEATURE]: Netflix conductor Task gRPC

### ISSUE THREAD

**Issue by chinhbk** [Netflix/conductor#3087]
Hi I'm using Netflix conductor server/ui. I know that conductor support for HTTP Task

However, I have different back-end services exposed as gRPC call. How to set up conductor gRPC task that call to external service. Any example to follow

Thanks

**Comment by jxu-nflx** [comment]
Hello @chinhbk HTTP task doesn't support gRPC calls. If you'd like to make gRPC call to a backend service, you can use Simple task, and make that call in the task worker: https://conductor.netflix.com/how-tos/Workers/build-a-java-task-worker.html

**Comment by chinhbk** [comment]
Thanks @jxu-nflx. Got info
