### ISSUE TITLE
High Availability Configuration of Conductor Server 

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#31]
Is Condcutor possible (or are there plans) to run in a HA configuration - i.e. multiple Conductor Servers are running and using the same Dynamite/DynoQueues backend?

Many thanks for your advice.

**Comment by v1r3n** [comment]
Yes, we do actually run it that way.  Conductor servers can scale up by adding more servers and sharing the same instance of Dynomite.

**Comment by blueelephants** [comment]
Thanks for clarification

**Comment by cquon** [comment]
@v1r3n a quick question on this.  Is the scaling stateless or is it more of a cluster?  Is there any notion of primary/slaves or all work as standalone servers with same database.

Also is there any special handling that needs to be taken for potential race conditions with a scaled architecture?

**Comment by v1r3n** [comment]
@cquon the scaling is stateless and follows peer to peer architecture and not master/slave.  Each server in the cluster is capable of serving the requests.  The cluster is identified by the group  of servers talking to the same underlying Dynomite database.

Conductor takes care of any race conditions so no special care has to be taken.

**Comment by akashbhunchal** [comment]
Is this applicable even for redis (not dynomite) ? I am facing race conditions when I try to run more than conductor servers with one redis instance as the datastore. I have raised an issue with my observations on synchronized block in the ReqisQueue implemetation of pop()
