### ISSUE TITLE
Only one worker showed on UI

### ISSUE THREAD

**Issue by BrandonDotLin** [Netflix/conductor#3104]
**Describe the bug**
I have four workers that poll task from same TaskType, only one worker show on TaskQueues menu on UI

**Comment by peterlau** [comment]
The Task Queues interface does not show the number of workers - only the most recently polling worker for a given task and domain. The verbiage around that page has been updated recently to avoid confusion.

**Comment by BrandonDotLin** [comment]
Thanks for your clarification. IMO, showing all current active workers is also helpful.
