### ISSUE TITLE
When trying to run netflix conductor docker with postgres, getting this exception

### ISSUE THREAD

**Issue by hchepey-clari** [Netflix/conductor#3112]
docker-conductor-server-1  | 
docker-conductor-server-1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
docker-conductor-server-1  | 5328 [main] ERROR org.springframework.boot.SpringApplication [] - Application run failed
docker-conductor-server-1  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowResource' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-rest-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/rest/controllers/WorkflowResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/service/WorkflowServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'deciderService' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/DeciderService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'postgresMetadataDAO' defined in class path resource [com/netflix/conductor/postgres/config/PostgresConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.conductor.postgres.dao.PostgresMetadataDAO]: Factory method 'postgresMetadataDAO' threw exception; nested exception is java.lang.NoClassDefFoundError: com/netflix/conductor/core/exception/ApplicationException
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.7.jar!/:2.6.7]
docker-conductor-server-1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) [spring-boot-2.6.7.jar!/:2.6.7]
docker-conductor-server-1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) [spring-boot-2.6.7.jar!/:2.6.7]
docker-conductor-server-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-2.6.7.jar!/:2.6.7]
docker-conductor-server-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) [spring-boot-2.6.7.jar!/:2.6.7]
docker-conductor-server-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) [spring-boot-2.6.7.jar!/:2.6.7]
docker-conductor-server-1  | 	at com.netflix.conductor.Conductor.main(Conductor.java:37) [classes!/:3.11.0-SNAPSHOT]
docker-conductor-server-1  | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
docker-conductor-server-1  | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
docker-conductor-server-1  | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
docker-conductor-server-1  | 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
docker-conductor-server-1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [conductor-server-3.11.0-SNAPSHOT-boot.jar:3.11.0-SNAPSHOT]
docker-conductor-server-1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [conductor-server-3.11.0-SNAPSHOT-boot.jar:3.11.0-SNAPSHOT]
docker-conductor-server-1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [conductor-server-3.11.0-SNAPSHOT-boot.jar:3.11.0-SNAPSHOT]
docker-conductor-server-1  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [conductor-server-3.11.0-SNAPSHOT-boot.jar:3.11.0-SNAPSHOT]
docker-conductor-server-1  | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/service/WorkflowServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'deciderService' defined in URL [jar:file:/app/libs/conductor-server-3.11.0-SNAPSHOT-boot.jar!/BOOT-INF/lib/conductor-core-3.11.0-SNAPSHOT.jar!/com/netflix/conductor/core/execution/DeciderService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'postgresMetadataDAO' defined in class path resource [com/netflix/conductor/postgres/config/PostgresConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.conductor.postgres.dao.PostgresMetadataDAO]: Factory method 'postgresMetadataDAO' threw exception; nested exception is java.lang.NoClassDefFoundError: com/netflix/conductor/core/exception/ApplicationException
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.19.jar!/:5.3.19]
docker-conductor-server-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.19.jar!/:5.3.19]

**Comment by hchepey-clari** [comment]
Moving this bug to conductor-community. Hence closing it here.

**Comment by sumba101** [comment]
Hey, I am facing this same issue, could you provide a link to where this bug has been moved to please?

**Comment by hchepey-clari** [comment]
> Hey, I am facing this same issue, could you provide a link to where this bug has been moved to please?

https://github.com/Netflix/conductor-community/issues/83
