### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by JamieSlome** [Netflix/conductor#3113]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@7h3h4ckv157) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by aravindanr** [comment]
@JamieSlome Thanks for reaching out, please check, https://github.com/Netflix/conductor/security/policy

**Comment by JamieSlome** [comment]
Thanks, @aravindanr 👍 

I've sent further details to the e-mail address :) Just for reference, the report can be found directly here:
https://huntr.dev/bounties/11b70ec2-95ea-4f4a-bc9d-eefd15fbe76e/

It is private and only accessible to maintainers with repository write permissions 👍
