### ISSUE TITLE
how to find the version of current code?

### ISSUE THREAD

**Issue by qiuguo0205** [Netflix/conductor#3119]
how to find or set the version of current conductor project when checkout, thanks

**Comment by apanicker-nflx** [comment]
The current version is always updated here - https://github.com/Netflix/conductor#releases

**Comment by apanicker-nflx** [comment]
For this case, I would recommend checking out the specific git tag for the version that you are interested in and building the artifact from the tag. Please refer: https://docs.github.com/en/rest/git/tags
