### ISSUE TITLE
 get /tasks/poll/{tasktype}  problem

### ISSUE THREAD

**Issue by lfozvye** [Netflix/conductor#313]
*environment：
es
dynomite
redis

*The detail workflow
taskdefs
[
  {    
    "name": "test",
    "retryCount": 1,
    "timeoutSeconds": 120,
    "inputKeys": [
        "build_input"
    ],
    "outputKeys": [
        "data",
        "error",
        "msg",
        "status"
    ],
    "timeoutPolicy": "TIME_OUT_WF",
    "retryLogic": "FIXED",
    "retryDelaySeconds": 0,
    "responseTimeoutSeconds": 360
  }
]

metadata/workflow
{
    "name": "test",
    "description": "my workflow for ci flow",
    "version": 1,
    "tasks": [
        {
            "name": "test",
            "taskReferenceName": "node1",
            "inputParameters": {
                "build_input": "${workflow.input.build_input}"
            },
            "type": "SIMPLE",
            "startDelay": 0
        }
    ],
    "outputParameters": {
        "build_data": "${node1.output.data}",
        "build_error": "${node1.output.error}",
        "build_status": "${node1.output.status}",
        "build_msg": "${node1.output.msg}"
    },
    "schemaVersion": 2
}

[workflow name]
{}  

[exec task]
![image](https://user-images.githubusercontent.com/6927559/29814040-8a89f20e-8cde-11e7-9a87-b2ba24fa37ff.png)

[conductor output]
289400 [qtp1701436909-32] DEBUG org.eclipse.jetty.io.ChannelEndPoint  - filled 0 SelectChannelEndPoint@157ef56f{/10.200.0.181:59151<->8080,Open,in,out,-,-,0/30000,HttpConnection@61662ab2}{io=0/0,kio=0,kro=1}
289401 [qtp1701436909-32] DEBUG org.eclipse.jetty.io.ChannelEndPoint  - filled 0 SelectChannelEndPoint@157ef56f{/10.200.0.181:59151<->8080,Open,in,out,-,-,0/30000,HttpConnection@61662ab2}{io=0/0,kio=0,kro=1}
289401 [qtp1701436909-32] DEBUG org.eclipse.jetty.server.HttpConnection  - HttpConnection@61662ab2[SelectChannelEndPoint@157ef56f{/10.200.0.181:59151<->8080,Open,in,out,-,-,1/30000,HttpConnection@61662ab2}{io=0/0,kio=0,kro=1}][p=HttpParser{s=START,0 of -1},g=HttpGenerator@3516e7c{s=START},c=HttpChannelOverHttp@507c79a4{r=6,c=false,a=IDLE,uri=null}] filled 0 HeapByteBuffer@132a1496[p=0,l=0,c=8192,r=0]={<<<>>>HTTP/1.1 500 Inte...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
289401 [qtp1701436909-32] DEBUG org.eclipse.jetty.server.HttpConnection  - HttpConnection@61662ab2[SelectChannelEndPoint@157ef56f{/10.200.0.181:59151<->8080,Open,in,out,-,-,1/30000,HttpConnection@61662ab2}{io=0/0,kio=0,kro=1}][p=HttpParser{s=START,0 of -1},g=HttpGenerator@3516e7c{s=START},c=HttpChannelOverHttp@507c79a4{r=6,c=false,a=IDLE,uri=null}] parse HeapByteBuffer@132a1496[p=0,l=0,c=8192,r=0]={<<<>>>HTTP/1.1 500 Inte...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} {}
289401 [qtp1701436909-32] DEBUG org.eclipse.jetty.http.HttpParser  - parseNext s=START HeapByteBuffer@132a1496[p=0,l=0,c=8192,r=0]={<<<>>>HTTP/1.1 500 Inte...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
289401 [qtp1701436909-32] DEBUG org.eclipse.jetty.server.HttpConnection  - HttpConnection@61662ab2[SelectChannelEndPoint@157ef56f{/10.200.0.181:59151<->8080,Open,in,out,-,-,1/30000,HttpConnection@61662ab2}{io=0/0,kio=0,kro=1}][p=HttpParser{s=START,0 of -1},g=HttpGenerator@3516e7c{s=START},c=HttpChannelOverHttp@507c79a4{r=6,c=false,a=IDLE,uri=null}] parsed false HttpParser{s=START,0 of -1}
289401 [qtp1701436909-32] DEBUG org.eclipse.jetty.server.HttpConnection  - releaseRequestBuffer HttpConnection@61662ab2[SelectChannelEndPoint@157ef56f{/10.200.0.181:59151<->8080,Open,in,out,-,-,1/30000,HttpConnection@61662ab2}{io=0/0,kio=0,kro=1}][p=HttpParser{s=START,0 of -1},g=HttpGenerator@3516e7c{s=START},c=HttpChannelOverHttp@507c79a4{r=6,c=false,a=IDLE,uri=null}]
289401 [qtp1701436909-32] DEBUG org.eclipse.jetty.io.AbstractConnection  - fillInterested HttpConnection@61662ab2[SelectChannelEndPoint@157ef56f{/10.200.0.181:59151<->8080,Open,in,out,-,-,1/30000,HttpConnection@61662ab2}{io=0/0,kio=0,kro=1}][p=HttpParser{s=START,0 of -1},g=HttpGenerator@3516e7c{s=START},c=HttpChannelOverHttp@507c79a4{r=6,c=false,a=IDLE,uri=null}]
289402 [qtp1701436909-32] DEBUG org.eclipse.jetty.io.FillInterest  - FillInterest@305386eb{true,AC.ReadCB@61662ab2{HttpConnection@61662ab2[SelectChannelEndPoint@157ef56f{/10.200.0.181:59151<->8080,Open,in,out,FI,-,0/30000,HttpConnection@61662ab2}{io=0/0,kio=0,kro=1}][p=HttpParser{s=START,0 of -1},g=HttpGenerator@3516e7c{s=START},c=HttpChannelOverHttp@507c79a4{r=6,c=false,a=IDLE,uri=null}]}} register AC.ReadCB@61662ab2{HttpConnection@61662ab2[SelectChannelEndPoint@157ef56f{/10.200.0.181:59151<->8080,Open,in,out,FI,-,1/30000,HttpConnection@61662ab2}{io=0/0,kio=0,kro=1}][p=HttpParser{s=START,0 of -1},g=HttpGenerator@3516e7c{s=START},c=HttpChannelOverHttp@507c79a4{r=6,c=false,a=IDLE,uri=null}]}
289416 [qtp1701436909-32] DEBUG org.eclipse.jetty.io.FillInterest  - FillInterest@305386eb{true,AC.ReadCB@61662ab2{HttpConnection@61662ab2[SelectChannelEndPoint@157ef56f{/10.200.0.181:59151<->8080,Open,in,out,FI,-,15/30000,HttpConnection@61662ab2}{io=0/0,kio=0,kro=1}][p=HttpParser{s=START,0 of -1},g=HttpGenerator@3516e7c{s=START},c=HttpChannelOverHttp@507c79a4{r=6,c=false,a=IDLE,uri=null}]}} register AC.ReadCB@61662ab2{HttpConnection@61662ab2[SelectChannelEndPoint@157ef56f{/10.200.0.181:59151<->8080,Open,in,out,FI,-,15/30000,HttpConnection@61662ab2}{io=0/0,kio=0,kro=1}][p=HttpParser{s=START,0 of -1},g=HttpGenerator@3516e7c{s=START},c=HttpChannelOverHttp@507c79a4{r=6,c=false,a=IDLE,uri=null}]}

Error where is no clear cause, it is difficult to analyze, trouble to help take a look at this problem, thank you

**Comment by v1r3n** [comment]
@lfozvye take the latest snapshot from `dev` branch.  The dyno-jedis client was downgraded to 1.4.7 version causing this.

Or you can update the dependencies in your build to use dyno-jedis version 1.5.9 and it should fix the issue.

**Comment by lfozvye** [comment]
As you said, I have already solved the problem, thank you
