### ISSUE TITLE
My workflow is running and the task is SCHEDULED but it is not being processed

### ISSUE THREAD

**Issue by lianjunwei** [Netflix/conductor#3136]
一.description.

- Conductor version: v3.10.1
- Persistence implementation: Postgress
   conductor.db.type=postgres
   spring.datasource.url=jdbc:postgresql://127.0.0.1:8002/conductor
   spring.datasource.username=test
   spring.datasource.password=test123
   spring.datasource.hikari.maximum-pool-size=10
   spring.datasource.hikari.minimum-idle=2
- Lock: Redis
    Conductor server: application.properties is as follows:
    conductor.app.workflowExecutionLockEnabled=true
    conductor.workflow-execution-lock.type=noop_lock
    conductor.redis-lock.serverType=single
    conductor.redis-lock.serverAddress=redis://127.0.0.1:6379
    conductor.redis-lock.namespace=conductor

1. I have deployed two conductor servers. They are 10.190.32.157:8080 and 10.190.32.158:8080 respectively.
2. My springboot project is configured as follows:
![image](https://user-images.githubusercontent.com/13819823/181600446-62390127-f605-4ae9-bed3-49e19ff0b7c2.png)

3.If I trigger the workflow in "10.190.32.157:8080", everything is normal.However, when the workflow is triggered in "10.190.32.158:8080", it is not executed.

4.The tasks of workflow are as follows:

![image](https://user-images.githubusercontent.com/13819823/181598990-9dda9b43-664b-4441-afb3-11cb9e4613d1.png)
![image](https://user-images.githubusercontent.com/13819823/181599170-87bba8c7-f464-4e78-9525-95490e56cd81.png)

5.it is not being processed

![image](https://user-images.githubusercontent.com/13819823/181598919-8bd1bf11-c23c-4d62-8549-ed24aec892cf.png)

6.It has been ensured that the "last polling time" of this task is the current time.

![image](https://user-images.githubusercontent.com/13819823/181599258-b18f36b0-5aa5-463f-9db3-2952b4a41d62.png)

二.expect
If I trigger the workflow in "10.190.32.158:8080", the task is executed.

三.Supplementary notes:
Screenshot from: https://conductor.netflix.com/faq.html
![image](https://user-images.githubusercontent.com/13819823/181601543-b925734f-f441-4352-a1fa-12f3526eef78.png)

I don't understand the passage in the red circle. Is the bug related to this?Hope to get help.

**Comment by jxu-nflx** [comment]
Hello @lianjunwei how is your worker configed to poll tasks: https://github.com/Netflix/conductor/blob/main/client/src/main/java/com/netflix/conductor/client/automator/TaskRunnerConfigurer.java#L174? Seemed to me that it is just polling from that specific instance? You might want to check your server setup to make sure all instances are discoverable.

 BTW, you are using noop lock
```conductor.workflow-execution-lock.type=noop_lock```.

**Comment by lianjunwei** [comment]
> Hello @lianjunwei how is your worker configed to poll tasks: https://github.com/Netflix/conductor/blob/main/client/src/main/java/com/netflix/conductor/client/automator/TaskRunnerConfigurer.java#L174? Seemed to me that it is just polling from that specific instance? You might want to check your server setup to make sure all instances are discoverable.
> 
> BTW, you are using noop lock `conductor.workflow-execution-lock.type=noop_lock`.

1.I have changed the distributed lock to redis.
2.The worker configuration is as follows:
    `conductor:
  client:
    rootUri: http://10.190.32.157:9195/conductor/n/api/
    threadCount: 2
  worker:
    pollingInterval: 2`
   
worker code is as follows:
![image](https://user-images.githubusercontent.com/13819823/182895882-8092e9a6-9d89-475b-800d-9ab4432cff1a.png)

**Comment by v1r3n** [comment]
@lianjunwei happy to help. Maybe we can jump on a call and debug this further.

**Comment by BrandonDotLin** [comment]
seems the same issue as #3089

**Comment by jxu-nflx** [comment]
@lianjunwei I am looking for your setting for https://github.com/Netflix/conductor/blob/main/client/src/main/java/com/netflix/conductor/client/automator/TaskRunnerConfigurer.java#L174?

>> According to your guess, if my conductor server deploys 10 instances, it will take 10 rounds of training to get the task, which is obviously unreasonable.
I think the task queues among instances should be shared. How to share? I don't know how to configure it. Does conductor support it?

What queue solution are you using? If it's in-memory one, then it won't be shared among instances. Conductor simply just poll messages from your queue solutions.

**Comment by lianjunwei** [comment]
>  @jxu-nflx postgres

**Comment by lianjunwei** [comment]
> @lianjunwei I am looking for your setting for https://github.com/Netflix/conductor/blob/main/client/src/main/java/com/netflix/conductor/client/automator/TaskRunnerConfigurer.java#L174?
> 
> > > According to your guess, if my conductor server deploys 10 instances, it will take 10 rounds of training to get the task, which is obviously unreasonable.
> > > I think the task queues among instances should be shared. How to share? I don't know how to configure it. Does conductor support it?
> 
> What queue solution are you using? If it's in-memory one, then it won't be shared among instances. Conductor simply just poll messages from your queue solutions.

Looks like it's postgres, but I'm not sure, how to set up my queue which is which. I am using postgres as persistent storage.

**Comment by aravindanr** [comment]
@lianjunwei based on the screenshot in your initial question, `conductor.client.rootUri=10.190.32.157:8080`. You have configured the client to poll from only one instance of your cluster. Please ensure that both instances point to the same datastore.
