### ISSUE TITLE
Unable to change the conductor server tomcat port using external application.properties

### ISSUE THREAD

**Issue by indranil1741997** [Netflix/conductor#3147]
**Describe the bug**
Unable to change the conductor server tomcat port using external application.properties.
There is no parameter available to pass the tomcat server port in application.properties in ChangeLog ()https://github.com/Netflix/conductor/blob/main/CHANGELOG.md for conductor-server-boot-3.9.1.jar

**Details**
Conductor version: conductor-server-boot-3.9.1.jar

**To Reproduce**
1. Run java -jar conductor-server-boot-3.9.1.jar  spring.config.import-file:application.properties
2. See the logs: conductor running on tomcat with port:8080

**Expected behavior**
Needs to start the conductor on the port given by application.properties

**Comment by apanicker-nflx** [comment]
Conductor 3.0 is a SpringBoot app, so the port can be changed using the `server.port` property. [Documentation](https://docs.spring.io/spring-boot/docs/1.3.0.RELEASE/reference/html/howto-properties-and-configuration.html)

Also, please refer to the [spring docs](https://docs.spring.io/spring-boot/docs/2.4.x/reference/htmlsingle/#boot-features-external-config-files-importing) for importing additional data.
