### ISSUE TITLE
UI cannot search any data

### ISSUE THREAD

**Issue by Sunyelw** [Netflix/conductor#3157]
## CASE background

Conductor version: v3.11.0-SNAPSHOT
Deployment Type: docker-compose ( In memory )

Deployment Result
```
❯ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED       STATUS                 PORTS                                            NAMES
76dbcce325a2   conductor:ui           "docker-entrypoint.s…"   2 hours ago   Up 2 hours             0.0.0.0:5000->5000/tcp                           docker_conductor-ui_1
10bf1d9bc705   conductor:server       "/bin/sh /app/startu…"   2 hours ago   Up 2 hours (healthy)   0.0.0.0:8080->8080/tcp                           docker_conductor-server_1
98bece5e4fbd   elasticsearch:6.8.15   "/usr/local/bin/dock…"   2 hours ago   Up 2 hours (healthy)   0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   docker_elasticsearch_1
```

### 1. Task Definition
```
{
  "name": "leaderRatify",
  "description": "leader task",
  "taskReferenceName": "node1",
  "inputParameters": {
    "staffName": "${workflow.input.staffName}",
    "staffDepartment": "${workflow.input.staffDepartment}"
  },
  "type": "SIMPLE",
  "ownerEmail": "one@email.com"
}
```
```
{
  "name": "managerRatify",
  "description": "manager task",
  "taskReferenceName": "node2",
  "inputParameters": {
    "managerName": "${node1.output.leaderName}",
    "managerDepartment": "${node1.output.leaderDepartment}"
  },
  "type": "SIMPLE",
  "ownerEmail": "one@email.com"
}
```

### 2. Workflow Definition
```
{
  "name": "leave_process",
  "description": "a demo for workflow",
  "tasks": [
    {
      "name": "leaderRatify",
      "taskReferenceName": "node1",
      "inputParameters": {
        "staffName": "${workflow.input.staffName}",
        "staffDepartment": "${workflow.input.staffDepartment}"
      },
      "type": "SIMPLE",
      "ownerEmail": "one@email.com"
    },
    {
      "name": "managerRatify",
      "taskReferenceName": "node2",
      "inputParameters": {
        "managerName": "${node1.output.leaderName}",
        "managerDepartment": "${node1.output.leaderDepartment}"
      },
      "type": "SIMPLE",
      "ownerEmail": "one@email.com"
    }
  ],
  "outputParameters": {
    "leaderName": "${node1.output.leaderName}",
    "leaderDepartment": "${node1.output.leaderDepartment}",
    "managerAgree": "${node2.output.managerAgree}",
    "managerDisagree": "${node2.output.managerDisagree}"
  },
  "restartable": true,
  "ownerEmail": "one@email.com",
  "schemaVersion": "1",
  "version": 2
}
```

### 3. Execute Workflow
```
curl -X 'POST' \
  'http://localhost:8080/api/workflow/leave_process?priority=0' \
  -H 'accept: text/plain' \
  -H 'Content-Type: application/json' \
  -d '{
  "staffName": "hello",
  "staffDepartment": "world"
}'
```

### 4. Search workflowId by cURL or Swagger UI 
![image](https://user-images.githubusercontent.com/31758533/183281921-bfbea11d-fb27-4b07-9441-b12f8e3eced1.png)

It works well now.

### 5. Search by Conductor UI

![image](https://user-images.githubusercontent.com/31758533/183281959-94498130-4bfa-4fbf-9f2e-9a306a898aff.png)
![image](https://user-images.githubusercontent.com/31758533/183281966-dcfaf55e-8b2c-49c6-b32f-389966c1f524.png)

It dose not work.

Any suggestion? thx a lot.

**Comment by Sunyelw** [comment]
fix: Conductor version is v3.11.0-SNAPSHOT

**Comment by Sunyelw** [comment]
> fix: Conductor version is v3.11.0-SNAPSHOT

and conductor client is 3.3.4

**Comment by jxu-nflx** [comment]
@Sunyelw do you have ES indexing enabled?
```conductor.indexing.enabled=true`

**Comment by Sunyelw** [comment]
@jxu-nflx  Yeah, and what does this dynomite do? Does it necessary for UI searching?

**Comment by apanicker-nflx** [comment]
same as https://github.com/Netflix/conductor/issues/3106#issuecomment-1215879384

**Comment by jianbo** [comment]
Hi, I'm having similar issue with taskLog searching, my es6 and workflow searching works. Is it normal normal to see "No logs available"?  

Here is the default workflow, and es indexing is enabled

```{
  "name": "get_population_data",
  "taskReferenceName": "get_population_data",
  "inputParameters": {
    "http_request": {
      "uri": "https://datausa.io/api/data?drilldowns=Nation&measures=Population",
      "method": "GET"
    },
    "asyncComplete": false
  },
  "type": "HTTP",
  "startDelay": 0,
  "optional": false,
  "asyncComplete": false
}
```

![Screen Shot 2022-08-20 at 8 48 15 pm](https://user-images.githubusercontent.com/209831/185742539-682cb461-b499-4baf-ad3c-4ab1696b3a80.png)

**Comment by Sunyelw** [comment]
@jianbo  When I tried `HTTP` type task, it works well. Maybe you should check conductor-server started and healthy first. ( UI dependents on Server )

**Comment by apanicker-nflx** [comment]
@jianbo The logs tab in the task view displays the task execution logs for each task. These logs need to be explicitly written by the worker in the [TaskResult](https://github.com/Netflix/conductor/blob/main/common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskResult.java#L70) when updating a task or can be added async using the [API](https://github.com/Netflix/conductor/blob/main/rest/src/main/java/com/netflix/conductor/rest/controllers/TaskResource.java#L86)

**Comment by danteoh** [comment]
@apanicker-nflx I'm also running into no search results.  Fresh docker install, but on an M1 Macbook so the only modification I made was to make ES use the AMD64 flags.

My ES container is running, though.
<img width="997" alt="Screen Shot 2022-08-23 at 11 53 12 AM" src="https://user-images.githubusercontent.com/1686515/186204584-654fa55e-dc25-406f-ab36-a50d72c83f49.png">

**Comment by danteoh** [comment]
I take back my previous comment... setting conductor.indexing.enabled=true worked.
