### ISSUE TITLE
Documentation : How to run conductor server with single Redis instance

### ISSUE THREAD

**Issue by picaron** [Netflix/conductor#317]
Hi,

I see in the config file for Conductor that it's possible to run with a standalone redis instance (ex: `db=redis`)

However, I cannot find any documentation explaining how to do so and looking at the code it's not immediately intuitive how to configure everything/which parameters are required and which aren't.

For a single redis, I have to set `workflow.dynomite.cluster.hosts` ... do I need to specify a rack or can I just specify the redis host:port ?

As for the other parameters, which of these are required? : 
- workflow.namespace.prefix=conductor
- workflow.namespace.queue.prefix=conductor_queues
- queues.dynomite.threads=10
- queues.dynomite.nonQuorum.port=22122

Could you please provide me with the rough instructions for running with a single redis instance (without dynomite)?

In exchange I can update the markdown documentation  :)

**Comment by v1r3n** [comment]
@picaron prefix and thread configs are required.  the nonQuorum port MUST match the port number for the redis server.  I am going to update the documentation and publish.

**Comment by v1r3n** [comment]
The updated documentation is available now:
https://netflix.github.io/conductor/server/#using-standalone-redis-elasticache

**Comment by picaron** [comment]
fantastic, thanks @v1r3n 

closing issue
