### ISSUE TITLE
Workflow UI not showing the workflows

### ISSUE THREAD

**Issue by jegadjame** [Netflix/conductor#3184]
Workflow UI not showing the workflows when i run "java -jar conductor-server-3.9.2-boot.jar"

Now , I am running Conductor standalone (or a non-docker setup) in Windows machine. I run command "java -Dconductor.indexing.enabled=true -jar conductor-boot.jar" .. I am getting this error... Please help me in fixing the issue

image

**Comment by apanicker-nflx** [comment]
Can you provide more details about how you are starting up the UI?

**Comment by jegadjame** [comment]
> Can you provide more details about how you are starting up the UI?

I am using "yarn run start" from Visual studio code

**Comment by jegadjame** [comment]
Now i am running through docker. 
Change conductor.indexing.enabled=true in \conductor\docker\server\config\config-local.properties and \conductor\server\src\main\resources\application.properties. Now i can see the data in workflow execution
