### ISSUE TITLE
Elastic search SocketTimeoutException while upgrading  from conductor 2.30.3 to conductor 3.4.1

### ISSUE THREAD

**Issue by trivedishalini** [Netflix/conductor#3189]
**Describe the bug**
I am trying to upgrade from conductor 2.30.3 to conductor 3.4.1 and getting below issue for elastic search.

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-08-19 01:48:02.867 [main] ERROR org.springframework.boot.SpringApplication [] - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowBulkResource' defined in URL [jar:file:/app/libs/conductor-server-3.4.1-boot.jar!/BOOT-INF/lib/conductor-rest-3.4.1.jar!/com/netflix/conductor/rest/controllers/WorkflowBulkResource.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowBulkServiceImpl' defined in URL [jar:file:/app/libs/conductor-server-3.4.1-boot.jar!/BOOT-INF/lib/conductor-core-3.4.1.jar!/com/netflix/conductor/service/WorkflowBulkServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'workflowExecutor' defined in URL [jar:file:/app/libs/conductor-server-3.4.1-boot.jar!/BOOT-INF/lib/conductor-core-3.4.1.jar!/com/netflix/conductor/core/execution/WorkflowExecutor.class]: Unsatisfied dependency expressed through constructor parameter 5; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'executionDAOFacade' defined in URL [jar:file:/app/libs/conductor-server-3.4.1-boot.jar!/BOOT-INF/lib/conductor-core-3.4.1.jar!/com/netflix/conductor/core/orchestration/ExecutionDAOFacade.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'es6IndexDAO': Invocation of init method failed; nested exception is java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]
	at org.spr

**Details**
Conductor version: 2.30.3
Persistence implementation: Postgress
Queue implementation: Postgres
Lock: Redis
Workflow definition: N/A
Task definition: N/A
Event handler definition: N/A

**Additional context**
 conductor running in a Kubernetes cluster.

**Comment by aravindanr** [comment]
@trivedishalini looks like Conductor is not able to connect to the Elasticsearch cluster. Can you check the connection settings like hostname, port etc or the firewall settings if connection from Conductor to Elasticsearch is allowed?

>  java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-0 [ACTIVE]

**Comment by trivedishalini** [comment]
@aravindanr ,yes all properties are fine . Actually we already have conductor 2.30.3 and elastic search up and running on my client machine and everything working fine with that But Now I have to upgrade this cluster with conductor 3 .
Conductor 3 and elastic search fresh installation is working fine But I have to do upgrade on client machine from conductor 2 to conductor 3 to avoid data loss .
And upgrade path where conductor 3 and elastic search communication breaking.
Any idea ?

**Comment by unfazed151** [comment]
@trivedishalini  2.30.3 depend on  elasticsearch 5.x, but Conductor 3 depnd on elasticsearch 6.x, and docker-compose.yaml use the same volume path. try `docker compose -f docker-compose.yaml down --volumes` remove es volume.

**Comment by trivedishalini** [comment]
Conductor3.X checking es health by adding default color status filter as green always and my ES status yellow somehow but as of now its . Thats why it got break when I upgrade from conductor2.X to conductor 3.X .
**Solution:**
There is property name 'conductor.elasticsearch.clusterHealthColor' in conductor 3.X , I was able to override status color to yellow from green and got it working.  
Which is short term solution but I need to improved my elastic search or green status still.

Closing this issue and got it working now
