### ISSUE TITLE
[DOC]: AirPlay listener can cause startup issues for Conductor UI on Macs

### ISSUE THREAD

**Issue by danteoh** [Netflix/conductor#3194]
## What are you missing in the docs

Anyone wanting to run via the docker documents (where Conductor UI starts on 5000) may run into issues with AirPlay already listening on port 5000.

## Proposed text

Notice for Mac users:  AirPlay often listens on port 5000, so you may need to change the conductor-ui port from 5000 to 5001 (or your port of choice).

**Comment by apanicker-nflx** [comment]
Thanks for reporting this.
@peterlau Can you please add this to the documentation for the UI?
