### ISSUE TITLE
How to use the default persistence with Dynomite?

### ISSUE THREAD

**Issue by suxiaoyuv** [Netflix/conductor#32]
Is the test-hardness with some simple config to use dynomite for persistance?

thanks!

**Comment by v1r3n** [comment]
I am working on a server module that can be used for this.  Stay tuned.

**Comment by v1r3n** [comment]
Check out the server module and its[documentation here:
https://netflix.github.io/conductor/server/

The server module and its config is still under the RC version, so I will not consider them production ready.

**Comment by suxiaoyuv** [comment]
Many thanks!
