### ISSUE TITLE
Building Docker Server Container Hangs on Gradle Build step

### ISSUE THREAD

**Issue by michael-rivera-florencehc-com** [Netflix/conductor#3205]
**Describe the bug**
When running the command to build the conductor server container the Gradle steps just hangs and does not move foward:
docker build --no-cache --platform=linux/amd64 --progress plain -t conductor-server -f server/Dockerfile ../

**Details**
Conductor version: Current

**To Reproduce**
type the command 
docker build --no-cache --platform=linux/amd64 --progress plain -t conductor-server -f server/Dockerfile ../ 

**Expected behavior**
The build to complete

**Screenshots**
![image](https://user-images.githubusercontent.com/94843926/186949305-9ef8d1ba-5756-437e-98e1-5400c9157e0f.png)

**Additional context**
I am running an Apple M1
I have waited as long as 90 minutes but no progress
The same problem exists if I try to build the docker image on an Amazon Linux 2 VM. 
For my local system, I was able to build locally using the changes that are documented for the ARM processor. 
Also, I was also able to do a docker image build if the ARM processor changes is in place on my local system.

**Comment by aravindanr** [comment]
@boney9 if you have any insights about building Conductor in Apple M1, please share.
