### ISSUE TITLE
Execution is extremely slow.Is the conductor suitable for real-time scenarios?

### ISSUE THREAD

**Issue by lianjunwei** [Netflix/conductor#3206]
**Describe the bug**
Running the workflow takes too long. Is the conductor suitable for real-time scenarios?I hope to get guidance from friends in the community.
Mine has an api that turned out to take 5~6 seconds. After I changed the workflow execution it took up to 1 minute and 25 seconds.

**Details**
Conductor version: 3.10.3
Persistence implementation: Postgres
Queue implementation: Postgres
Lock: Redis
Workflow definition:
Task definition:
Event handler definition:

**To Reproduce**

1. An example of a very slow factor:：
   a.the switch decision takes 1 to 2 seconds.
   b.There is a simple task. The worker actually takes 102 ms, but the conductor takes 577 ms (Screenshot below.).

2. contions:
  My workflow has 8 simple workers with 7 sub-workflows.

**Expected behavior**
How to reduce the execution time of workflows and tasks. I hope friends in the community can give some suggestions.

**Screensh
![subworkflow](https://user-images.githubusercontent.com/13819823/187022466-41cf6588-db0f-48ce-ba7a-aa7948aef711.png)
ots**
![total_costtime](https://user-images.githubusercontent.com/13819823/187022476-66be268f-dc1a-480e-b202-1a5d4e336e61.png)

![handshake_costtime](https://user-images.githubusercontent.com/13819823/187022492-97e0dd50-d70d-4f69-8068-2d9c0a826756.png)
![handshake_costtime_long](https://user-images.githubusercontent.com/13819823/187022498-b5a94c4f-eb99-4024-84a2-fa35764b80e7.png)

**Additional context**
1. start WorkFlow codes:
```
public void startWorkFlow(ControlInstruction control) {
        String conductorServerURL = "http://10.190.X.X:8080/api/";
        WorkflowExecutor executor = new WorkflowExecutor(conductorServerURL, 2);
        executor.initWorkers(InstructionFlowService.class.getPackageName());
        ConductorWorkflow<Object> workflow = this.buildExecuteCommandFlow(executor);
        try {
            CompletableFuture<Workflow> executionFuture = workflow.execute(control);
            Workflow run = executionFuture.get(60, TimeUnit.SECONDS);

            log.info("Workflow Id: " + run.getWorkflowId());
            log.info("Workflow Status: " + run.getStatus());
            log.info("Workflow Output: " + run.getOutput());
        } catch (Exception e) {
            e.printStackTrace();
        }
        log.info("Done");
    }
```
2. pom.xml is configured as follows:
```
<dependency>
    <groupId>com.netflix.conductor</groupId>
    <artifactId>conductor-client-spring</artifactId>
    <version>3.10.3</version>
</dependency>

 <dependency>
    <groupId>com.netflix.conductor</groupId>
    <artifactId>conductor-java-sdk</artifactId>
    <version>3.10.3</version>
 </dependency>  
```
3.The yml file configuration of the microservice where the worker is located is as follows:
```
conductor:
  client:
    rootUri: http://10.190.X.X:8080/api/
    threadCount: 20
  worker:
    pollingInterval: 1
```
4. Other similar feedback, see #3034  and #3162 . It doesn't seem to be resolved.

**Comment by aravindanr** [comment]
Conductor in its current form is not built with real-time scenarios. However, in this case, i would check your connectivity from Conductor -> Postgres and see if there are delays there. We can't see a scenario where a SWITCH task is slower than a SIMPLE task. SWITCH tasks in our deployment is executed in the order of few milliseconds.

**Comment by garathi** [comment]
Hello @lianjunwei 
Are you able to resolve the issue ?
