### ISSUE TITLE
Running a "notification worker task" on each task or workflow error

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#321]
Hello,

I have a notification worker microservice to send emails and create incidents in other systems.

My goal is to call this notification microservice whenever a task or workflow fails (providing the workflow-name, workflow-id, task-reference-name and task-id as input parameters).

I know I could periodically poll Conductor Server's or Elastic's API to find out all failed workflows, but is there a more "elegant" way to do that from within a workflow? 

Is there a way to configure an "onError-Task" within a workflow definition or task definition? 

Or, what other options might be possible to do that?

Many thanks

**Comment by cocodee** [comment]
This is a very useful feature.

**Comment by apanicker-nflx** [comment]
@blueelephants You can implement the [WorkflowStatusListener](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowStatusListener.java) interface to configure this functionality.
