### ISSUE TITLE
Variables are cleared once the WAIT task is started

### ISSUE THREAD

**Issue by vzubyk** [Netflix/conductor#3211]
**Bug description:**
`Variables` are cleared once the `WAIT` task is started.

**Details:**
Conductor version: 3.11.0
Workflow definition:
```
{
  "name": "Set_Variable_Workflow",
  "description": "Set a value to a variable and wait",
  "version": 1,
  "tasks": [
    {
      "name": "Set_Name",
      "taskReferenceName": "Set_Name",
      "type": "SET_VARIABLE",
      "inputParameters": {
        "name": "Foo"
      }
    },
    {
      "name": "Test_Wait",
      "taskReferenceName": "Test_Wait",
      "type": "WAIT",
      "inputParameters": {
        "duration": "30 s"  
      } 
    }
  ],
  "restartable": true,
  "ownerEmail":"abc@example.com",
  "workflowStatusListenerEnabled": true,
  "schemaVersion": 2
}
```

**Steps to reproduce the behavior:**
1. Create provided above workflow definition
2. Start a new workflow for the `Set_Variable_Workflow` definition
3. Open the workflow execution page
4. Check the `Variables`

**Actual behavior:**
No variables exist.

**Expected behavior:**
The variable `name` with the value `Foo`, created by the `Set_Name` task exists.

----------
**Screenshots:**
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/65384250/187446059-067b316f-32fc-43fe-9895-a98b116f4f28.png">
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/65384250/187446213-f77dd0be-33fd-4cd7-8b0e-38af8b36c21f.png">

**Comment by manan164** [comment]
Hi @vzubyk , Thanks for reporting this. I am able to reproduce this. We will raise a fix for this.

**Comment by manan164** [comment]
HI @vzubyk , PR for the fix https://github.com/Netflix/conductor/pull/3221
