### ISSUE TITLE
Deploy Conductor Server and UI - Change URLS

### ISSUE THREAD

**Issue by LexiPow** [Netflix/conductor#3217]
### Discussed in https://github.com/Netflix/conductor/discussions/3210

<div type='discussions-op-text'>

<sup>Originally posted by **LexiPow** August 30, 2022</sup>
Good Day 

Could you kindly advise on how I can deploy the conductor server and the UI to a local server and be able to change the urls from http://localhost to something else.

</div>

**Comment by LexiPow** [comment]
@apanicker-nflx could you kindly provide some feedback?

**Comment by boney9** [comment]
@LexiPow - for local testing you can add a host record on your local hosts file if you want to use anything other than localhost.
