### ISSUE TITLE
Change Docker URLS

### ISSUE THREAD

**Issue by LexiPow** [Netflix/conductor#3220]
Please provide guidance on how to configure conductor with a url i.e https://test.com (changing from localhost) to run on port 443.

**Comment by boney9** [comment]
Hi @LexiPow - How are you running Conductor? Is it on a K8s cluster? If yes - you can add an ingress controller such as Nginx. Once you do, depending on the cloud provider you are on, you can add an `A record` pointing to the Nginx controller load balancer and add an `Ingress` record for the URL. You have multiple options to enable TLS when you are using an ingress controller.

**Comment by LexiPow** [comment]
Good day.

I am following the steps as outlined by the official documentation on the website and docker containers with postgres.

Could you kindly provide me with some steps or guidance

**Comment by LexiPow** [comment]
Hi @boney9 could you kindly confirm what the steps are to change the url for docker containers.

Kind Regards

**Comment by boney9** [comment]
Hi @LexiPow - ping me on [slack](https://join.slack.com/t/orkes-conductor/shared_invite/zt-xyxqyseb-YZ3hwwAgHJH97bsrYRnSZg) if you can. I don't think I fully understood what you are stuck at. It looks like you are running this in your local machine, is that correct?
