### ISSUE TITLE
Now dynoqueue is no longer maintained what are the options?

### ISSUE THREAD

**Issue by voycey** [Netflix/conductor#3223]
Hi - we are evaluating conductor, I notice that [Netflix ](https://github.com/Netflix/dyno-queues) is no longer maintained, does this mean that it will eventually be replaced within conductor?

I can see that there are options for SQS but what state does this leave the internal queueing system in?

Thanks

**Comment by v1r3n** [comment]
Hi @voycey we plan to open source the queue implementation we use at Orkes in the next few days.  I will update this thread as we do.  Watch out for this space. ETA is sometime this week.

**Comment by v1r3n** [comment]
Hi @voycey check out https://github.com/orkes-io/orkes-queues that we have been using at Orkes
