### ISSUE TITLE
Task not timing out after responseTimeout elapsed

### ISSUE THREAD

**Issue by roversnord** [Netflix/conductor#3227]
Describe the bug:
responseTimeoutSeconds not being honored for simple task.

Details:
Conductor version 3.7.3
Task Definitoin: `{
    "name": "simple_job",
    "taskReferenceName": "simple_job",
    "inputParameters": {},
    "type": "SIMPLE",
    "decisionCases": {},
    "defaultCase": [],
    "forkTasks": [],
    "startDelay": 0,
    "joinOn": [],
    "optional": false,
    "taskDefinition": {
        "name": "simple_job",
        "retryCount": 0,
        "timeoutSeconds": 120,
        "inputKeys": [],
        "outputKeys": [],
        "timeoutPolicy": "TIME_OUT_WF",
        "retryLogic": "FIXED",
        "retryDelaySeconds": 0,
        "responseTimeoutSeconds": 60,
        "inputTemplate": {},
        "rateLimitPerFrequency": 0,
        "rateLimitFrequencyInSeconds": 1,
        "backoffScaleFactor": 1
    },
    "defaultExclusiveJoinTask": [],
    "asyncComplete": true,
    "loopOver": []
}`

Expected Behavior:
After the responseTimeoutSeconds has elapsed, the task should be in a TIMED_OUT status because of the amount of time elapsed and the timeoutPolicy.

Actual Behavior:
Even after the responseTimeoutSeconds has elapsed, the task is in in_progress status and available for the worker to pick up from the queue and reprocess.

Have a simple task with responseTimeoutSeconds of 60 seconds and timeoutSeconds of 120. When the custom worker picks up the tasks, it updates the status to in_progress and the sets the callbackAfterSeconds to the same amount as timeoutSeconds so it won't be picked up right away. What we are noticing is after the responseTimeoutSeconds has passed, the task is still in the queue with the status in_progress and when the callbackAfterSeconds has elapsed the worker is reprocessing the task. Based on the documentation, I would have expected that after responseTimeoutSeconds the task would be updated to TIMED_OUT. Since the task is configured with a timeoutPolicy of TIME_OUT_WF, the task should be in a terminal state of TIMED_OUT and not available to be picked up by workers.

**Comment by jxu-nflx** [comment]
Hello please take a look at the responsetimeout section of this doc: https://conductor.netflix.com/architecture/tasklifecycle.html
Response timeout is the time within which the worker must respond to the server with an update for the task, else the task will be marked as TIMED_OUT.

as long as your worker has sent a update status to the server within the responsetimeout, it will not mark the task as timed_out
