### ISSUE TITLE
[FEATURE]: Datastax V4 Driver Upgrade?

### ISSUE THREAD

**Issue by james-deee** [Netflix/conductor#3243]
Hi! Just wanted to see if an upgrade to Datastax's V4 Cassandra Driver is on the horizon at all. It's not clear to me how much of a change that requires, and I know that Netflix uses Cassandra so would probably need them to ensure everything works with the upgrade.

Thanks!

**Comment by ab48917** [comment]
@apanicker-nflx @v1r3n   @manan164  do we have an update on this? 

I was trying using the cassandra and end up with an error - 

com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [/127.0.0.1:9042] Cannot connect))


I am using cassandra 4.1.0 and tried upgrading the datastax to 3.11.3 

conductor-server_1  | 9645 [main] INFO  com.datastax.driver.core [] - DataStax Java driver 3.11.3 for Apache Cassandra

Still unable to connect with cassandra db from conductor. 
Note - I have added the below service in docker-compose to bring up cassandra in same network. 

  cassandra:
    image: cassandra
    ports:
      - '9042:9042'
    networks:
      - internal
    volumes:
      - cassandra-conductor:/var/lib/cassandra/data

**Comment by ab48917** [comment]
updated the cluster creation also to use same protocol version and ignoring the jmxreporting as its throwing error like class not found.

cluster = Cluster.builder().withoutJMXReporting().
                     withProtocolVersion(ProtocolVersion.V3)
                     .addContactPoint(host).withPort(port)
            .build();

**Comment by ab48917** [comment]
conductor.cassandra.hostAddress=127.0.0.1
conductor.cassandra.port=9042
conductor.cassandra.keyspace=conductor
