### ISSUE TITLE
[DOC]:  How to directly use fork and join

### ISSUE THREAD

**Issue by ishallbethat** [Netflix/conductor#3244]
## What are you missing in the docs
I see in docs lots of them describe to use fork_join with decision or switch.  
Is there anyway I can use directly use fork_join task and join to make my tasks run parallel.

what I want to accomplish is: 
I have a - (b, c, d) 
workflow starts with task a then b, c,d runs in parallel. There's no decision-making or switch scenario, so I avoid using switch and decision. 
I tried use fork_join task and join task alone. Conductor complaint with validation error.

Can anyone help me with this workflow  definition example. Thanks

**Comment by v1r3n** [comment]
Hi @ishallbethat take a look at this:
https://play.orkes.io/workflowDef/fork_join_example
