### ISSUE TITLE
[DOC]: Does fork_join task support deep nested fork_join task

### ISSUE THREAD

**Issue by ishallbethat** [Netflix/conductor#3245]
## What are you missing in the docs
I have a situation.
a -> (1 -> ( 3 -> (5 -> (7, 8), 6), 4), 2) -> b 

Task a has a fork_join task 1 and 1 has fork_join task 3, 3 has fork_join task 5.
It's just an example. Actually  my situation is more deep nested fork_join then this. You can take it as 10+. 

Does conductor suits with this situation ?  I tried a fork_join with a fork_join, it just doesn't work. Validation shows error.
If this is possible, could you show me the workflow definition example. Thanks

**Comment by ishallbethat** [comment]
I created this one 
https://play.orkes.io/workflowDef/fork_join_nested_example/1

still doubt how deep the nested fork_join could go.

**Comment by aravindanr** [comment]
Conductor supports Nested Fork_Join. This [test](https://github.com/Netflix/conductor/blob/main/test-harness/src/test/groovy/com/netflix/conductor/test/integration/NestedForkJoinSubWorkflowSpec.groovy) validates it.
