### ISSUE TITLE
[DOC]: how to make conductor deployment production ready

### ISSUE THREAD

**Issue by ishallbethat** [Netflix/conductor#3248]
## What are you missing in the docs
I'd like to know how to make conductor deployment production ready.
in production ready environment it needs at least automatic failover, autoscaling, high availability. 
Is there any documention on this ?

**Comment by v1r3n** [comment]
Hi @ishallbethat when we deploy conductor in prod here is what we ensure we have:

1. setup for failover - we use redis cluster or setup that has primary and replica that can be promoted to primary in case of failures
2. Automated backups of databases
3. We use k8s for deployments and use metrics for servers and workers to decide on scaling policies (CPU for conductor servers and queue depths for workers to autoscale)
4. Metrics setup - we use prometheus and grafana to monitor various metrics and configuring alerts
