### ISSUE TITLE
Java Client Poll scheduler not work as expected

### ISSUE THREAD

**Issue by BrandonDotLin** [Netflix/conductor#3252]
**Describe the bug**
I have more than 100 workers in an application which poll task from conductor server every 10ms. Some tasks never polled for a long time. It seems ScheduledThreadPoolExecutor with 100+ threads can handle properly.

any suggestion to improve the polling performance?

@apanicker-nflx

**Comment by aravindanr** [comment]
@BrandonDotLin can you provide details about your client configuration? A code snippet of how you build TaskRunnerConfigurer would also help.
