### ISSUE TITLE
Using Cassandra

### ISSUE THREAD

**Issue by sks1995** [Netflix/conductor#3269]
## What are you missing in the docs
<img width="840" alt="image" src="https://user-images.githubusercontent.com/17801041/193813018-c45e71a0-db92-4acc-a190-da592b282b71.png">
The doc mentions that cassandra does not provides implementation of QueueDAO and MetadataDAO
This module also does not provide implementations for QueueDAO, PollDataDAO and RateLimitingDAO

## Proposed text
This module also does not provide implementations for QueueDAO, PollDataDAO and RateLimitingDAO

Raised PR to correct https://github.com/Netflix/conductor/pull/3270 

@kishorebanala @aravindanr

**Comment by apanicker-nflx** [comment]
Closed by #3270
