### ISSUE TITLE
[FEATURE]: Pause the workflow after given task finished

### ISSUE THREAD

**Issue by BrandonDotLin** [Netflix/conductor#3294]
In my recent project, I need the workflow to be paused after a specific task finished,  say I have a workflow with task1, task2, task3. What i want is pause the workflow after task2 finished.

**Comment by v1r3n** [comment]
What will be the trigger to resume the workflow?

**Comment by BrandonDotLin** [comment]
> What will be the trigger to resume the workflow?

will be resumed manually. Technically, WAIT or HUMAN task can be used to achieve this purpose. But the operation stuff need the workflow status to be "PAUSED", not "RUNNING". 
Currently, I write a simple worker which will call workflow/pause api to pause the containing workflow. It works somehow, though not elegantly enough.

**Comment by aravindanr** [comment]
If a workflow is PAUSED, then the task and workflow timeouts will not be honored. This requirement seems to be very specific to your use-case. We recommend that you continue leveraging your simple task for this.
