### ISSUE TITLE
 .NET 6.0 - 403 error

### ISSUE THREAD

**Issue by jegadjame** [Netflix/conductor#3296]
Hi,
I am able to access API (http://localhost:8080/api/tasks/queue/all) from C# code when I use Target Framework as .NET core 3.1).

Now, When I upgrade the .NET framework to .NET 6.0, I am getting 403 error.
StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
Date: Fri, 14 Oct 2022 16:42:51 GMT
Connection: keep-alive
Via: HTTP/1.1 m_proxy_mum1
Content-Length: 0
} 

If anyone faced the issue, Please let me know

Thanks in advance.

**Comment by aravindanr** [comment]
This does not seem like an issue with Conductor. Removed the bug label. We operate Conductor in a Linux/Java environment and are not familiar with .NET. This issue seems to be related to the framework than Conductor itself.

**Comment by jegadjame** [comment]
It is working now.. It was Proxy Issue in my system.. 

Thanks,
Jegadeesh
