### ISSUE TITLE
Bind WorkflowSweeper as eager singleton by default

### ISSUE THREAD

**Issue by yamingwa** [Netflix/conductor#333]
Hi there,

I found by default `WorkflowSweeper.class` was not instantiated. Could we bind it as eager singleton to instantiate it? Thanks.

**Comment by yamingwa** [comment]
Ping @v1r3n 

Is there any unexpected result if we bind this by default? Thanks in advance.

**Comment by v1r3n** [comment]
Yes that should be OK.

**Comment by yamingwa** [comment]
Is it cool for me to send a PR for this?

 I think this is helpful for someone who wants to figure out the system logic, even though only one-line code needs to be added. :) @v1r3n

**Comment by cquon** [comment]
@yamingwa Did this automatically trigger workflow decisions (and thus timeouts) for you?

Thanks,
Corey

**Comment by yamingwa** [comment]
@cquon Yeah, it will do.

**Comment by cquon** [comment]
Thanks @yamingwa .  @v1r3n Was there a reason this is not enabled by default? (Performance, etc)

**Comment by LiranBri** [comment]
+1

**Comment by cyzhao** [comment]
@apanicker-nflx @kishorebanala please follow up on this, let's enable it by default unless there is a strong reason for not doing this (in which case documentation needs to be updated to cover it).

**Comment by apanicker-nflx** [comment]
Fixed in #1001.
