### ISSUE TITLE
[DOC]: why requirement: dyno-queue repo NO LONGER ACTIVELY MAINTAINED?

### ISSUE THREAD

**Issue by erlangparasu** [Netflix/conductor#3359]
## What are you missing in the docs
why requirement: dyno-queue repo NO LONGER ACTIVELY MAINTAINED?

**Comment by v1r3n** [comment]
Dyno-queues is in the maintenance mode with https://github.com/orkes-io/orkes-queues as the replacement for the same.
orkes-queues has better support for Redis, compared to dyno-queues that were designed for Dynomite.
