### ISSUE TITLE
unable to pass workflow input parameter

### ISSUE THREAD

**Issue by soumita9** [Netflix/conductor#337]
Downloaded the code from master branch. 
I created a sample workflow with one one task. The task should accept one input parameter from workflow. Below is my sample request.
[
  {
    "name": "workflow1",
    "description": "workflow1",
    "version": 0,
    "tasks": [
      {
        "name": "test",
        "taskReferenceName": "test",
        "description": "test",
        "inputParameters": {
        	"mod":"${workflow.input.mod}"
        	},
        "type": "SIMPLE"
       }
    ]
    
    }
]

when the workflow is saved I do not see the input paramour value getting saved.
Below is the snapshot after saving of the workflow.
{
  "updateTime": 1507110360391,
  "name": "workflow1",
  "description": "workflow1",
  "version": 0,
  "tasks": [
    {
      "name": "test",
      "taskReferenceName": "test",
      "description": "test",
      "inputParameters": {
        "mod": ""
      },
      "type": "SIMPLE",
      "startDelay": 0
    }
  ],
  "schemaVersion": 1
}

please let me know why is the input parameter not getting saved in workflow.

**Comment by copierrj** [comment]
Try adding "schemaVersion": 2 to your workflow definition. I ran into the same issue and this proved to be the solution. Unfortunately I don't know why this the necessary.

**Comment by apanicker-nflx** [comment]
@soumita9 As @copierrj mentioned, please use `schemaVersion:2` , schema version 1 is deprecated and will be removed in a future version soon.
