### ISSUE TITLE
Q: How can I retrieve output and state of workflow execution?

### ISSUE THREAD

**Issue by rmohta** [Netflix/conductor#338]
I have performed the below steps.  Couple of questions

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: text/plain' 'http://localhost:8080/api/workflow/sub_flow_1' -d '{ "input" : "something"}'

$376521dc-d202-4ab7-8b52-5ca7b08c7282

```

- How can I query the state of my workflow ID  (not via UI)?  
I have tried `http://localhost:8080/api/workflow/376521dc-d202-4ab7-8b52-5ca7b08c7282`. No joy as  response body is empty.

- How can I get the output of workflow? If a client initiates a workflow, how can I send back the response? Should there be a worker task at the end of the workflow to send back the response? Or can I configure a system task that makes a HTTP POST request to send back the response? Or client should poll API with workflow ID and extract  *output*, as shown in UI. What do you recommend?

**Comment by saidatta** [comment]
It works for me. 
http://<IP-ADDRESS>:8080/api/workflow/fbb40288-1c6e-4a28-a60a-80cc20a8ae5b

**Comment by apanicker-nflx** [comment]
@rmohta The `GET /workflow/{workflowId}` API can be used to get the output and status of a workflow execution as mentioned by @saidatta above.
