### ISSUE TITLE
Do While task is throwing exception

### ISSUE THREAD

**Issue by srp-asach** [Netflix/conductor#3382]
**Describe the bug**
Do While throwing exception Cannot invoke "javax.script.ScriptEngine.createBindings()" because "com.netflix.conductor.core.events.ScriptEvaluator.engine" is null

**Details**
Conductor version: v3.13.2
Persistence implementation: Dynomite (Note- I have used the default one given by Conductor)
Queue implementation: Dynoqueues (Note- I have used the default one given by Conductor)
Lock: Redis(Note- I have used the default one given by Conductor)
Workflow definition:
Task definition:
Event handler definition:

**Screenshots**
Please find attached error screenshot

![image](https://user-images.githubusercontent.com/120100735/206436497-7990f683-dc5b-4449-8527-21b3d8ebd787.png)

**Comment by v1r3n** [comment]
@srp-asach what is the version of Java are you using? Conductor uses Nashorn  at the moment as javascript engine and needs to run on JDK 11.

**Comment by srp-asach** [comment]
I am using openjdk version "17.0.2"

**Comment by srp-asach** [comment]
With JDK 11 this issue is resolved. Thanks.

**Comment by klimenttoshkov** [comment]
Hi, is there any way to run the precompiled jar on current JDK (20) while using the ScriptEvaluator?
