### ISSUE TITLE
Use AmazonSQS instead of AmazonSQSClient 

### ISSUE THREAD

**Issue by ctlove0523** [Netflix/conductor#3390]
`AmazonSQSClient` constructor are all deprecated,use `AmazonSQS` is more suitable.

**Comment by v1r3n** [comment]
Hi @ctlove0523 thanks for sending the PR.

**Comment by ctlove0523** [comment]
你好，你的邮件我已经收到，每天会在晚上查看邮件并回复。急事请打电话
