### ISSUE TITLE
How to restart list of tasks?

### ISSUE THREAD

**Issue by tshubham7** [Netflix/conductor#3392]
I am looking for a way to restart some sets of tasks, it does not matter if the workflow is completed or not we want this to make this happen at any time.

Our use case:
We are thinking of having a workflow for our customer onboarding journey, we have more than 8 pages which gathers customer's info. 
During the journey we may want the user to resubmit or revisit some pages that they have submitted.
`journey_workflow:
    task_page1
    task_page2
    task_page3
    task_page4
    task_page5
    task_page6
    task_page7`
in this example, we want our user to revisit task_page2 after completion of task_page6 or after completion whole workflow, can be anything.

**Comment by manan164** [comment]
Hi @tshubham7 , We can use a [loop](https://conductor.netflix.com/reference-docs/do-while-task.html) task to execute a single task multiple times. Now in a use case where tasks are completely dynamic, we can use [dynamic fork](https://conductor.netflix.com/reference-docs/dynamic-fork-task.html) tasks where we can specify the list of tasks to e executed at run time. Can you please describe the use case in more detail? Like how frequently on boarding process changes. How the list of on boarding pages the user needs to visit is determined?

**Comment by tshubham7** [comment]
Hi @manan164, thanks for the response.
So our journey contains varieties of user information personal details, employment details, kyc, selfie, mandates etc...
We gather these informations in several forms which i have mentioned as pages(we call them modules).
So let's say user started his journey he will submit modules in the following manner.
- Pan
- KYC
- Personal details
- Employment details
- Bank Details
- Selfie
- Mandates

assume as he has done till Bank Details and our system resets KYC module and we want the user to resubmit it so the get time user/client asks for next module the system should be able to return with KYC module and then Selfie module.

- KYC module can be reset when its background checks(validation) fails.
- It does not matter if journey is completed or not.
Thanks

**Comment by v1r3n** [comment]
Hi @tshubham7 we plan to send a PR to add this in the upcoming release.  FYI.
