### ISSUE TITLE
Error running docker-compose build on Windows 10

### ISSUE THREAD

**Issue by ikshvakoo** [Netflix/conductor#3400]
I downloaded conductor and trying to run it on my windows machine. At the docker-compose build command, I ran into this error - 

#0 184.8 FAILURE: Build failed with an exception.
#0 184.8
#0 184.8 * What went wrong:
#0 184.8 Execution failed for task ':conductor-annotations:spotlessJavaCheck'.
#0 184.8 > The following files had format violations:
#0 184.8       src/main/java/com/netflix/conductor/annotations/protogen/ProtoEnum.java
#0 184.8           @@ -1,26 +1,26 @@
#0 184.8           -/*\r\n
#0 184.8           - * Copyright 2022 Netflix, Inc.\r\n
#0 184.8           - * <p>\r\n
#0 184.8           - * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with\r\n
#0 184.8           - * the License. You may obtain a copy of the License at\r\n
#0 184.8           - * <p>\r\n
#0 184.8           - * http://www.apache.org/licenses/LICENSE-2.0\r\n
#0 184.8           - * <p>\r\n
#0 184.8           - * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on\r\n
#0 184.8           - * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the\r\n
#0 184.8           - * specific language governing permissions and limitations under the License.\r\n
#0 184.8           - */\r\n
#0 184.8           -package com.netflix.conductor.annotations.protogen;\r\n
#0 184.8           -\r\n
#0 184.8           -import java.lang.annotation.ElementType;\r\n
#0 184.8           -import java.lang.annotation.Retention;\r\n
#0 184.8           -import java.lang.annotation.RetentionPolicy;\r\n
#0 184.8           -import java.lang.annotation.Target;\r\n
#0 184.8           -\r\n
#0 184.8           -/**\r\n
#0 184.8           - * ProtoEnum annotates an enum type that will be exposed via the GRPC API as a native Protocol\r\n
#0 184.8           - * Buffers enum.\r\n
#0 184.8           - */\r\n
#0 184.8           -@Retention(RetentionPolicy.RUNTIME)\r\n
#0 184.8           -@Target(ElementType.TYPE)\r\n
#0 184.8           -public @interface ProtoEnum {}\r\n
#0 184.8           +/*\n
#0 184.8           + * Copyright 2022 Netflix, Inc.\n
#0 184.8           + * <p>\n
#0 184.8           + * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with\n
#0 184.8           + * the License. You may obtain a copy of the License at\n
#0 184.8           + * <p>\n
#0 184.8           + * http://www.apache.org/licenses/LICENSE-2.0\n
#0 184.8           + * <p>\n
#0 184.8           + * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on\n
#0 184.8           + * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the\n
#0 184.8           + * specific language governing permissions and limitations under the License.\n
#0 184.8           + */\n
#0 184.8           +package com.netflix.conductor.annotations.protogen;\n
#0 184.8           +\n
#0 184.8           +import java.lang.annotation.ElementType;\n
#0 184.8           +import java.lang.annotation.Retention;\n
#0 184.8           +import java.lang.annotation.RetentionPolicy;\n
#0 184.8           +import java.lang.annotation.Target;\n
#0 184.8           +\n
#0 184.8           +/**\n
#0 184.8           + * ProtoEnum annotates an enum type that will be exposed via the GRPC API as a native Protocol\n
#0 184.8           + * Buffers enum.\n
#0 184.8       ... (4 more lines that didn't fit)
#0 184.8   Violations also present in:
#0 184.8       src/main/java/com/netflix/conductor/annotations/protogen/ProtoField.java
#0 184.8       src/main/java/com/netflix/conductor/annotations/protogen/ProtoMessage.java
#0 184.8   Run './gradlew :conductor-annotations:spotlessApply' to fix these violations.
#0 184.8
#0 184.8 * Try:
#0 184.8 > Run with --info or --debug option to get more log output.
#0 184.8
#0 184.8 * Exception is:
#0 184.8 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':conductor-annotations:spotlessJavaCheck'.#0 184.8        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
#0 184.8        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
#0 184.8        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
#0 184.8        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
#0 184.8        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
#0 184.8        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
#0 184.8        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
#0 184.8        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
#0 184.8        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:57)
#0 184.8        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
#0 184.8        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
#0 184.8        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
#0 184.8        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
#0 184.8        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
#0 184.8        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
#0 184.8        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
#0 184.8        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
#0 184.8        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)#0 184.8        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
#0 184.8        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
#0 184.8        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)#0 184.8        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)#0 184.8        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
#0 184.8        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:322)
#0 184.8        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:309)
#0 184.8        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:302)
#0 184.8        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:288)
#0 184.8        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:462)
#0 184.8        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:379)
#0 184.8        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
#0 184.8        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
#0 184.8 Caused by: org.gradle.api.GradleException: The following files had format violations:
#0 184.8     src/main/java/com/netflix/conductor/annotations/protogen/ProtoEnum.java
#0 184.8         @@ -1,26 +1,26 @@
#0 184.8         -/*\r\n
#0 184.8         - * Copyright 2022 Netflix, Inc.\r\n
#0 184.8         - * <p>\r\n
#0 184.8         - * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with\r\n
#0 184.8         - * the License. You may obtain a copy of the License at\r\n
#0 184.8         - * <p>\r\n
#0 184.8         - * http://www.apache.org/licenses/LICENSE-2.0\r\n
#0 184.8         - * <p>\r\n
#0 184.8         - * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on\r\n
#0 184.8         - * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the\r\n
#0 184.8         - * specific language governing permissions and limitations under the License.\r\n
#0 184.8         - */\r\n
#0 184.8         -package com.netflix.conductor.annotations.protogen;\r\n
#0 184.8         -\r\n
#0 184.8         -import java.lang.annotation.ElementType;\r\n
#0 184.8         -import java.lang.annotation.Retention;\r\n
#0 184.8         -import java.lang.annotation.RetentionPolicy;\r\n
#0 184.8         -import java.lang.annotation.Target;\r\n
#0 184.8         -\r\n
#0 184.8         -/**\r\n
#0 184.8         - * ProtoEnum annotates an enum type that will be exposed via the GRPC API as a native Protocol\r\n
#0 184.8         - * Buffers enum.\r\n
#0 184.8         - */\r\n
#0 184.8         -@Retention(RetentionPolicy.RUNTIME)\r\n
#0 184.8         -@Target(ElementType.TYPE)\r\n
#0 184.8         -public @interface ProtoEnum {}\r\n
#0 184.8         +/*\n
#0 184.8         + * Copyright 2022 Netflix, Inc.\n
#0 184.8         + * <p>\n
#0 184.8         + * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with\n
#0 184.8         + * the License. You may obtain a copy of the License at\n
#0 184.8         + * <p>\n
#0 184.8         + * http://www.apache.org/licenses/LICENSE-2.0\n
#0 184.8         + * <p>\n
#0 184.8         + * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on\n
#0 184.8         + * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the\n
#0 184.8         + * specific language governing permissions and limitations under the License.\n
#0 184.8         + */\n
#0 184.8         +package com.netflix.conductor.annotations.protogen;\n
#0 184.8         +\n
#0 184.8         +import java.lang.annotation.ElementType;\n
#0 184.8         +import java.lang.annotation.Retention;\n
#0 184.8         +import java.lang.annotation.RetentionPolicy;\n
#0 184.8         +import java.lang.annotation.Target;\n
#0 184.8         +\n
#0 184.8         +/**\n
#0 184.8         + * ProtoEnum annotates an enum type that will be exposed via the GRPC API as a native Protocol\n
#0 184.8         + * Buffers enum.\n
#0 184.8     ... (4 more lines that didn't fit)
#0 184.9 Violations also present in:
#0 184.9     src/main/java/com/netflix/conductor/annotations/protogen/ProtoField.java
#0 184.9     src/main/java/com/netflix/conductor/annotations/protogen/ProtoMessage.java
#0 184.9 Run './gradlew :conductor-annotations:spotlessApply' to fix these violations.
#0 184.9        at com.diffplug.gradle.spotless.SpotlessCheck.performAction(SpotlessCheck.java:111)
#0 184.9        at com.diffplug.gradle.spotless.SpotlessCheck.performAction(SpotlessCheck.java:53)
#0 184.9        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#0 184.9        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
#0 184.9        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)#0 184.9        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
#0 184.9        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
#0 184.9        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
#0 184.9        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
#0 184.9        at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:236)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
#0 184.9        at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:221)
#0 184.9        at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:204)
#0 184.9        at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:187)
#0 184.9        at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:165)
#0 184.9        at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:89)
#0 184.9        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:40)
#0 184.9        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:53)
#0 184.9        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)#0 184.9        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:50)
#0 184.9        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:40)
#0 184.9        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)#0 184.9        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)#0 184.9        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
#0 184.9        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
#0 184.9        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
#0 184.9        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
#0 184.9        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:29)
#0 184.9        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:124)
#0 184.9        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:80)
#0 184.9        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:58)
#0 184.9        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
#0 184.9        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:36)
#0 184.9        at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:181)
#0 184.9        at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:71)
#0 184.9        at org.gradle.internal.Either$Right.fold(Either.java:175)
#0 184.9        at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
#0 184.9        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:69)
#0 184.9        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:47)
#0 184.9        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
#0 184.9        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
#0 184.9        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
#0 184.9        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
#0 184.9        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:110)
#0 184.9        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:56)
#0 184.9        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:56)
#0 184.9        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
#0 184.9        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:73)
#0 184.9        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:44)
#0 184.9        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
#0 184.9        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
#0 184.9        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:89)
#0 184.9        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:50)
#0 184.9        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:102)
#0 184.9        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:57)
#0 184.9        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:76)
#0 184.9        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:50)
#0 184.9        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNoEmptySources(SkipEmptyWorkStep.java:254)
#0 184.9        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:91)
#0 184.9        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:56)
#0 184.9        at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
#0 184.9        at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
#0 184.9        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
#0 184.9        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:43)
#0 184.9        at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)
#0 184.9        at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
#0 184.9        at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:281)
#0 184.9        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
#0 184.9        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
#0 184.9        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
#0 184.9        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
#0 184.9        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)
#0 184.9        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)
#0 184.9        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)
#0 184.9        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:139)
#0 184.9        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:128)
#0 184.9        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
#0 184.9        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
#0 184.9        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
#0 184.9        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
#0 184.9        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:57)
#0 184.9        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
#0 184.9        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
#0 184.9        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
#0 184.9        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
#0 184.9        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)#0 184.9        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)#0 184.9        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:69)
#0 184.9        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:322)
#0 184.9        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:309)
#0 184.9        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:302)
#0 184.9        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:288)
#0 184.9        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:462)
#0 184.9        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:379)
#0 184.9        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
#0 184.9        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
#0 184.9
#0 184.9
#0 184.9 * Get more help at https://help.gradle.org
#0 184.9
#0 184.9 Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
#0 184.9
#0 184.9 You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
#0 184.9
#0 184.9 See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings
#0 184.9
#0 184.9 Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
#0 184.9 Please consult deprecation warnings for more details.
#0 184.9 164 actionable tasks: 163 executed, 1 up-to-date
#0 184.9
#0 184.9 BUILD FAILED in 3m 4s
#0 185.0
#0 185.0 Publishing build scan...
#0 185.5 https://gradle.com/s/ryxfhmz7l4mvg
#0 185.5
------
#failed to solve: executor failed running [/bin/sh -c ./gradlew build -x test --stacktrace]: exit code: 1**

**

Can anyone please help me resolve this issue? What am I missing here?

**Comment by manan164** [comment]
Hi @ikshvakoo , Which version of the conductor you are trying to build?
I tried the same command with the latest conductor and it seems to be working fine.
Configuration,
1. Windows 10
2. openjdk version "11.0.14.1" 2022-02-08 LTS
3. Docker Desktop 4.7.0
Let me know if this works, or we can chat [here](https://join.slack.com/t/orkes-conductor/shared_invite/zt-xyxqyseb-YZ3hwwAgHJH97bsrYRnSZg) for more realtime collaboration.

**Comment by ikshvakoo** [comment]
Hi @manan164, Thanks for your response. Here's my configuration:

1. Windows 10
2. java version "19.0.1" 2022-10-18
   Java(TM) SE Runtime Environment (build 19.0.1+10-21)
   Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)
3. Docker Desktop - 4.15.0
4. Docker Version - 20.10.21, build baeda1f
5. Conductor version - 2.31.8

**Comment by dust63** [comment]
It's a problem of line ending style on the graddle file when you checkout the repo on windows.
It's work if you do all task into WSL distro.

**Comment by manan164** [comment]
Hi @ikshvakoo ,
Please follow the steps,
1. Delete your current conductor folder
2. Run **git config --global core.autocrlf false**; 
3. Run **git config --global core.eol lf**; (Small L and f)
4. Clone conductor repo again
5. Check if end of lines shows as CRLF via NotePad++ by opening a DockerFile, e.g. => conductor/docker/server/DockerFile
6. Run docker-compose up on conductor/docker

**Comment by ikshvakoo** [comment]
That was it. Works for me now. Thanks @manan164.

**Comment by Robban1980** [comment]
If on windows you do not want to change the global configuration as it will likely break other repositories on your machine.

Do what is described here instead.
https://github.com/Netflix/conductor/pull/3742#issuecomment-1696588180
