### ISSUE TITLE
Wait takes much longer than expected

### ISSUE THREAD

**Issue by Nostras** [Netflix/conductor#3403]
**Describe the bug**
Wait duration is precise, but highly inaccurate. Setting a duration of 3 seconds actually results in a delay of 30 seconds. A delay of 30 seconds is actually 115 seconds. These results are consistent.

**Details**
Conductor version: 3.13.2
Persistence implementation: Postgres
Queue implementation: NA (stock or postgres)
Lock: NA (stock)
`
    {
      "name": "Internal wait",
      "taskReferenceName": "Internal_wait",
      "inputParameters": {
        "duration": "30 seconds"
      },
      "type": "WAIT",
      "startDelay": 0,
      "optional": false,
      "asyncComplete": false
    },
`

**To Reproduce**
Just create a workflow with a WAIT type and see it take longer than expected.

**Expected behavior**
The behaviour matches the duration specified.

**Screenshots**
30 seconds:
![image](https://user-images.githubusercontent.com/4203238/207400571-1132ff45-70d7-467a-9c8a-aa1ffd016f76.png)
Actual duration:
![image](https://user-images.githubusercontent.com/4203238/207400621-dad9389b-41e7-41b2-ad13-5aec054c5363.png)

I'm also having an issue where this WAIT is ignored while in a DO_WHILE loop, but I'm not sure if this is related or an issue at all. Still trying to identify it. 
![image](https://user-images.githubusercontent.com/4203238/207400863-6745a072-2d1d-4ba1-9a62-ccc08d564eba.png)

**Comment by boney9** [comment]
cc: @v1r3n

**Comment by boney9** [comment]
Hi @Nostras - this is sort of by design. The WAIT tasks are completed by the decision queues, which is scheduled once every 30 seconds with the default configurations. There is an improvement coming for this, but it's not out yet.  cc: @v1r3n

**Comment by Nostras** [comment]
> Hi @Nostras - this is sort of by design. The WAIT tasks are completed by the decision queues, which is scheduled once every 30 seconds with the default configurations. There is an improvement coming for this, but it's not out yet. cc: @v1r3n

Hi Boney, could you please point out where to change this? If need be I can edit the source code too.
To add to the issue with the wait in switch, it seems that the switch is spawning a WAIT which is then orphaned and ignored (except that it shows up in the task list). Adding a join outside of the switch resolves this, but this breaks pretty badly as the join spins infinitely if the wait was not executed/created, which defeats the purpose.
A solution for this is to make the switch decide on what timeout to set and then always execute the timeout. If we do not want to WAIT we just set it to 0 seconds, else we use the value as passed to the flow. A WAIT outside of the switch works as expected and requires no join.

The issue with the wait still remains as described in the starting post.
For reference, with this "new" flow as just described I got a timeout 29s, 2m15s and 1m57 where 3 seconds was set. The 29s is explained with the decision queue to run every 30 seconds, but the second and the latter are quite problematic.

**Comment by bjpirt** [comment]
@Nostras We had a similar sounding issue with JOIN tasks taking 30s to complete. Modifying the property `conductor.app.systemTaskWorkerCallbackDuration` enabled us to reduce this.

@boney9 I'd be interested to know if there are any major implications of reducing this - we've got it to set to 1s and it's working well but I guess it depends on your specific workload

**Comment by sounddroid** [comment]
Hi @bjpirt . What file do you actually set `conductor.app.systemTaskWorkerCallbackDuration` in?

**Comment by DukeDai** [comment]
While decision queue is scheduled once every 30 seconds, duration of WAIT task is far more longer than the expected_duraition+2*schedule_interval. 
Could be other factors?

**Comment by manan164** [comment]
Hi @dpozinen , @DukeDai , there is a property called `conductor.app.workflowOffsetTimeout` which is set to 30 seconds by default. It means that every 30 seconds workflow will be evaluated for any state change. In case you want to complete the wait task before 30 seconds please set it to a lower value like `5s` or `10s`. But please note that decreasing that value will also imply that workflows will be evaluated at a much faster rate.

**Comment by Nostras** [comment]
This, however, does not solve the issue with extreme unreliability however. If _at worst_ wait for 30 seconds that's something I could accept. I don't need that granularity, but I do want consistency.

If I ask for an X second timeout I expect the timeout to be max X+workflowOffsetTimeout timeout, not X+workflowOffsetTimeout+whatever_conductor_is_feeling_like.

I'm not sure if some others in this issue thread are describing the same issue as I'm having.

That said, we haven't updated for some time so if there's any indication that this may have approved then do let me know and I'll update and check again.

**Comment by manan164** [comment]
Hi @Nostras , There is still a way we can reduce the latency by either increasing the number of sweeper threads or decreasing sweeper poll frequency. That way the overhead conductor add will be minimal.

**Comment by Nostras** [comment]
> Hi @Nostras , There is still a way we can reduce the latency by either increasing the number of sweeper threads or decreasing sweeper poll frequency. That way the overhead conductor add will be minimal.

Do you have some instructions on how to do so or some documentation I can check on how to do this?

**Comment by manan164** [comment]
For sweeper thread count check [property](https://github.com/Netflix/conductor/blob/main/core/src/main/java/com/netflix/conductor/core/config/ConductorProperties.java#L46)
And sweep frequency check [property](https://github.com/Netflix/conductor/blob/main/core/src/main/java/com/netflix/conductor/core/reconciliation/WorkflowReconciler.java#L62). 
Please join the [community](https://join.slack.com/t/orkes-conductor/shared_invite/zt-xyxqyseb-YZ3hwwAgHJH97bsrYRnSZg) so that we can chat real time.

**Comment by dpozinen** [comment]
hi @manan164 we have around 500 messages in the decider queue. We used the defaults (2 pods, 2 threads, 500ms delay, 30s timeout) and faced this issue. So, we scaled conductor to 4 pods each with 10 threads, still 500ms delay and `conductor.app.workflowOffsetTimeout` is set to 1 second. We are still facing the same issue with no changes in workloads and no delay decrease. 

Right now it's just the development stage, so 500 will probably become around 5000 and i expect this task finish delay will only increase. Is there a recommended configuration?

**Comment by manan164** [comment]
Hi @dpozinen , @Nostras , We have fixed this issue in https://github.com/Netflix/conductor/pull/3775. We have made the wait task async so it does not have to rely on the sweeper to mark the task completed. It will provide better granularity without adding much overhead.

**Comment by Nostras** [comment]
Thanks @manan164 , once a new release containing this fix has been released I'll be sure to check it and report back if it does what we expect.

**Comment by Dyson-Ido** [comment]
I tried the wait task with duration parameters set as 30s, 36s, 40s, 60s respectively and actually they turned out as 33s, 39s, 41s, 62s  respectively.
@manan164 , could you explain the minor difference? And whether you recommend Wait Task to do the precise waiting ?

**Comment by manan164** [comment]
Hi @Dyson-Ido , Can you please try with the release [3.14.0](https://github.com/Netflix/conductor/releases/tag/v3.14.0)? It should solve the latency issue for the wait task.

**Comment by Dyson-Ido** [comment]
> Hi @Dyson-Ido , Can you please try with the release [3.14.0](https://github.com/Netflix/conductor/releases/tag/v3.14.0)? It should solve the latency issue for the wait task.

@manan164 , Here is my testing result with the release 3.14.0: 
![ScreenClip](https://github.com/Netflix/conductor/assets/22881565/5c46ceb1-34d2-4cd0-9e6e-b70b4a496640)
From the testing result , when it's  below 5 seconds, the actual waiting duration is not accurate anymore.

**Comment by manan164** [comment]
Hi @Dyson-Ido , Can you please share the configuration? We can increase the [systemTaskWorkerThreadCount](https://github.com/Netflix/conductor/blob/main/core/src/main/java/com/netflix/conductor/core/config/ConductorProperties.java#L91) if we are running in relatively low cpu instance.

**Comment by Nostras** [comment]
Hi guys,

Sorry for taking so long.
I've tested it about a week ago and can confirm that the problem is working as expected.
We don't particularly care about accuracy as long as it's "close enough" to the set timeout.
I'm closing this issue.

@Dyson-Ido please create a new issue.
