### ISSUE TITLE
[FEATURE]: We are trying to integrate conductor with oracle nosql/mongo db, Is it already done by  someone OR if you can refer some articles on same

### ISSUE THREAD

**Issue by Viky-Viky** [Netflix/conductor#3419]
Please read our [contributor guide](https://github.com/Netflix/conductor/blob/main/CONTRIBUTING.md) before creating an issue.   
Also consider discussing your idea on the [discussion forum](https://github.com/Netflix/conductor/discussions) first.

## Describe the Feature Request
_A clear and concise description of what the feature request is._

## Describe Preferred Solution
_A clear and concise description of what you want to happen._

## Describe Alternatives
_A clear and concise description of any alternative solutions or features you've considered._

**Comment by v1r3n** [comment]
@Viky-Viky its possible, check the implementations for mysql or postgres.  However, mongo might not be the best backend for Conductor - We use Redis + Postgres for some of hour high performance low latency installations.  Happy to chat [more](https://join.slack.com/t/orkes-conductor/shared_invite/zt-xyxqyseb-YZ3hwwAgHJH97bsrYRnSZg).
