### ISSUE TITLE
[FEATURE]: Add docker image on docker Hub

### ISSUE THREAD

**Issue by dust63** [Netflix/conductor#3428]
Can you provide an official docker image on the docker hub, It can be more easy for developer to test your product.
Should be nice to automate the delevery process when you create a new release.

**Comment by jimmyruan-tpg** [comment]
Are there any update on this?

**Comment by geokal** [comment]
This is major cause the build process of docker images takes forever especially for the combined UI & Server.  Would be  very handy to have some official images published in docker hub.
