### ISSUE TITLE
How many standard system task types are there in conductor?

### ISSUE THREAD

**Issue by youngledo** [Netflix/conductor#3449]
## What are you missing in the docs

When learning the use of Conductor, we found these system tasks ([system tasks](https://conductor.netflix.com/configuration/systask.html)). However, these types are found in the actual use process([sysoperator](https://conductor.netflix.com/configuration/sysoperator.html)).
 But there is no more detailed introduction in the document. I am very confused.

## Proposed text
I would like to know how to better use these types. I hope there will be more detailed documentation.

**Comment by nittamathew** [comment]
Hi @youngledo.  You can refer to the link https://orkes.io/content/docs/getting-started/concepts/system-tasks for more info on system tasks.
