### ISSUE TITLE
Out of the box build fails with new install

### ISSUE THREAD

**Issue by michael-rivera-florencehc-com** [Netflix/conductor#3469]
**Describe the bug**
When downloading the repo and running docker compose

**Details**
Conductor version: Latest
AMQP
POSTGRES SQL
ELASTIC SEARCH 
Everything else default

** bug **
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
conductor-server_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
conductor-server_1  | 	at java.lang.Thread.run(Unknown Source) ~[?:?]
conductor-server_1  | Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
conductor-server_1  | 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[HikariCP-4.0.3.jar!/:?]
conductor-server_1  | 	at com.netflix.conductor.postgres.dao.PostgresBaseDAO.getWithTransaction(PostgresBaseDAO.java:119) ~[conductor-postgres-persistence-3.9.1.jar!/:3.9.1]
conductor-server_1  | 	... 12 more
conductor-server_1  | 129271 [pool-2-thread-1] ERROR com.netflix.conductor.postgres.dao.PostgresMetadataDAO [] - refresh TaskDefs failed 
conductor-server_1  | com.netflix.conductor.core.exception.ApplicationException: BACKEND_ERROR - HikariDataSource HikariDataSource (HikariPool-1) has been closed.
conductor-server_1  | 	at com.netflix.conductor.postgres.dao.PostgresBaseDAO.getWithTransaction(PostgresBaseDAO.java:136) ~[conductor-postgres-persistence-3.9.1.jar!/:3.9.1]
conductor-server_1  | 	at com.netflix.conductor.postgres.dao.PostgresBaseDAO.lambda$getWithRetriedTransactions$3(PostgresBaseDAO.java:147) ~[conductor-postgres-persistence-3.9.1.jar!/:3.9.1]
conductor-server_1  | 	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329) ~[spring-retry-1.3.3.jar!/:?]
conductor-server_1  | 	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209) ~[spring-retry-1.3.3.jar!/:?]
conductor-server_1  | 	at com.netflix.conductor.postgres.dao.PostgresBaseDAO.getWithRetriedTransactions(PostgresBaseDAO.java:147) ~[conductor-postgres-persistence-3.9.1.jar!/:3.9.1]
conductor-server_1  | 	at com.netflix.conductor.postgres.dao.PostgresBaseDAO.withTransaction(PostgresBaseDAO.java:194) ~[conductor-postgres-persistence-3.9.1.jar!/:3.9.1]
conductor-server_1  | 	at com.netflix.conductor.postgres.dao.PostgresMetadataDAO.refreshTaskDefs(PostgresMetadataDAO.java:472) ~[conductor-postgres-persistence-3.9.1.jar!/:3.9.1]
conductor-server_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
conductor-server_1  | 	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[?:?]
conductor-server_1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
conductor-server_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
conductor-server_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
conductor-server_1  | 	at java.lang.Thread.run(Unknown Source) ~[?:?]
conductor-server_1  | Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
conductor-server_1  | 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96) ~[HikariCP-4.0.3.jar!/:?]
conductor-server_1  | 	at com.netflix.conductor.postgres.dao.PostgresBaseDAO.getWithTransaction(PostgresBaseDAO.java:119) ~[conductor-postgres-persistence-3.9.1.jar!/:3.9.1]
conductor-server_1  | 	... 12 more

Tried to apply fixes for  two issues:
Found this was related to two issues:
Ran into this issue. conductor-server_1 | *************************** conductor-server_1 | APPLICATION FAILED TO START conductor-server_1 | *************************** conductor-server_1 | conductor-server_1 | Description: conductor-server_1 | conductor-server_1 | Parameter 2 of constructor in com.netflix.conductor.core.execution.DeciderService required a bean of type 'com.netflix.conductor.dao.MetadataDAO' that could not be found. conductor-server_1 | conductor-server_1 | conductor-server_1 | Action: conductor-server_1 | conductor-server_1 | Consider defining a bean of type 'com.netflix.conductor.dao.MetadataDAO' in your configuration. conductor-server_1 |
Had to update server/build.gradle runtimeOnly group: 'com.netflix.conductor', name: 'conductor-postgres-persistence', version: '3.9.1'
Issue [Netflix/conductor-community#83](https://github.com/Netflix/conductor-community/issues/83) Have to add a new file in the dir core/src/main/java/com/netflix/conductor/core/exception/ApplicationException.java
Source https://raw.githubusercontent.com/Netflix/conductor/v3.9.1-rc.1/core/src/main/java/com/netflix/conductor/core/exception/ApplicationException.java

Still have the error above

**To Reproduce**
git clone https://github.com/Netflix/conductor.git
git clone https://github.com/Netflix/conductor-community.git
modify application.properties with amqp values
Update server/build.gradle dependencies with the following line
runtimeOnly group: 'com.netflix.conductor', name: 'conductor-postgres-persistence', version: '3.9.1'
cd conductor/docker
docker-compose -f docker-compose.yaml -f docker-compose-postgres.yaml up

**Expected behavior**
Servers Up and running

Running on Amazon Linux 2

**Comment by thxmike** [comment]
Found this was related to two issues:


Ran into this issue. 
conductor-server_1  | ***************************
conductor-server_1  | APPLICATION FAILED TO START
conductor-server_1  | ***************************
conductor-server_1  |
conductor-server_1  | Description:
conductor-server_1  |
conductor-server_1  | Parameter 2 of constructor in com.netflix.conductor.core.execution.DeciderService required a bean of type 'com.netflix.conductor.dao.MetadataDAO' that could not be found.
conductor-server_1  |
conductor-server_1  |
conductor-server_1  | Action:
conductor-server_1  |
conductor-server_1  | Consider defining a bean of type 'com.netflix.conductor.dao.MetadataDAO' in your configuration.
conductor-server_1  |

Had to update server/build.gradle
runtimeOnly group: 'com.netflix.conductor', name: 'conductor-postgres-persistence', version: '3.9.1'


Issue https://github.com/Netflix/conductor-community/issues/83
Have to add a new file in the dir
core/src/main/java/com/netflix/conductor/core/exception/ApplicationException.java

Source
https://raw.githubusercontent.com/Netflix/conductor/v3.9.1-rc.1/core/src/main/java/com/netflix/conductor/core/exception/ApplicationException.java

After application the server came up

**Comment by michael-rivera-florencehc-com** [comment]
After days of digging around I was able to figure out the following:

There is a missing package that needs to be added to the path server/build.gradle file:
"runtimeOnly group: 'com.netflix.conductor', name: 'conductor-postgres-persistence', version: '3.13.3'"
Place it next to the existing line where it indicated runtimeOnly.
Also note the version number of conductor, this string above will require the same version for the package placed in the string. 

Make sure when you make a change you do a docker-compose rebuild. While in some cases it will pick up the change on a restart some of the files do not get replaced. The docker-compose rebuild is key.

Lessons learned:
While you can us postgres in this version of the server in this repo, it is a package, so if you need to make changes it has to be in the conduction-community repo via a PR.
