### ISSUE TITLE
Is there any Support for DynamoDB

### ISSUE THREAD

**Issue by Kumar-Saurabh-acko** [Netflix/conductor#3474]
We are considering to use conductor for workflow management. Could not find any support for DynamoDB. 

@apanicker-nflx

**Comment by v1r3n** [comment]
Hi @Kumar-Saurabh-acko there isn't any support for DynamoDB.   The currently supported backends are:
1. Redis
2. Cassandra
3. Potgres
4. Mysql

Are you considering DynamoDB for high volume use cases?  At Orkes we also use S3 for longer term storage along with Redis for running workflows achieving the scale and performance.
