### ISSUE TITLE
Can workers communicate with the Conductor server via gRPC or some other transport more efficient than HTTP?

### ISSUE THREAD

**Issue by pjohnmeyer** [Netflix/conductor#348]
I have spent some time evaluating Conductor for a task of mine, including starting work on implementing a Kafka-based queue provider. I am impressed with what I have found so far, but there is something in the documentation that is confusing me.

From the "Motivation":
> We built Conductor to help us orchestrate microservices based process flows at Netflix with the following features:
> <...snip...>
> * Be able to operate on HTTP or other transports e.g. gRPC.

Then, from the "FAQ":
> **Can I use conductor with Ruby / Go / Python?**
> Yes. Workers can be written any language as long as they can poll and update the task results via HTTP endpoints. <...snip...>

The former implies that gRPC might be a usable option; the latter implies HTTP-only. Looking through the code and the documentation, I cannot find any existing code / configuration / extensions to utilize gRPC for communication in Conductor. Am I missing something, or am I right in my determination that it does not _yet_ support other transports? Or, if it does, is there some additional piece of software to run on my server that bridges the gap?

Thank you for your help.

**Comment by v1r3n** [comment]
@pjohnmeyer are you looking for endpoints from conductor server to be over gRPC or orchestrate tasks that are exposed via gRPC?

For the conductor server to make its APIs available over gRPC, one needs to implement the https://github.com/Netflix/conductor/tree/master/jersey equivalent module for gRPC.

For task communication, look at https://github.com/Netflix/conductor/blob/master/contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java implementation.  One can implement a generic gRPC task (not sure if that is possible) and orchestrate services.
