### ISSUE TITLE
Issue with sub_workflow and workflow handling status

### ISSUE THREAD

**Issue by mhorbatenko** [Netflix/conductor#3481]
**Describe the bug**
Parent Workflow not completed if sub workflow completed.

**Details**
Conductor version: v3.13.3
Persistence implementation: in memory
Queue implementation: None
Lock: None
Workflow definitions:
Subworkflow: 
```
{
  "createTime": 1675690514023,
  "updateTime": 1675693982783,
  "accessPolicy": {},
  "name": "subLogic",
  "description": "Simple Workflow",
  "version": 1,
  "tasks": [
    {
      "name": "foo",
      "taskReferenceName": "fooRef",
      "inputParameters": {},
      "type": "SIMPLE",
      "startDelay": 0,
      "optional": false,
      "asyncComplete": false
    }
  ],
  "inputParameters": [],
  "outputParameters": {},
  "schemaVersion": 2,
  "restartable": true,
  "workflowStatusListenerEnabled": false,
  "ownerEmail": "some_email@gmail.com",
  "timeoutPolicy": "ALERT_ONLY",
  "timeoutSeconds": 0,
  "variables": {},
  "inputTemplate": {}
}
```
Workflow:
```
{
  "createTime": 1675690530804,
  "updateTime": 1675693978528,
  "accessPolicy": {},
  "name": "logic",
  "description": "Parent Workflow",
  "version": 1,
  "tasks": [
    {
      "name": "sub",
      "taskReferenceName": "subRef",
      "inputParameters": {},
      "type": "SUB_WORKFLOW",
      "startDelay": 0,
      "subWorkflowParam": {
        "name": "subLogic",
        "version": 1
      },
      "optional": false,
      "asyncComplete": false
    }
  ],
  "inputParameters": [],
  "outputParameters": {},
  "schemaVersion": 2,
  "restartable": true,
  "workflowStatusListenerEnabled": false,
  "ownerEmail": "some_email@gmail.com",
  "timeoutPolicy": "ALERT_ONLY",
  "timeoutSeconds": 0,
  "variables": {},
  "inputTemplate": {}
}
```

**To Reproduce**
1) Upload 2 worflows to conductor(copy/paste or via API not matter)
2) Run via rest or UI 

**Expected behavior**
Workflow with name `logic` should be in COMPLETED (or FAILED) status when workflow with name `subLogic` completed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/24190726/217002386-27571671-8f18-49b2-bf49-4d7836ea63a7.png)
![image](https://user-images.githubusercontent.com/24190726/217002470-83a2de2f-4b58-444e-be85-03339c177277.png)

Set task status as completed in subWorkflow
```
curl -X POST localhost:8080/api/tasks -H "Content-Type:application/json"  -d '{"taskId": "5dabedeb-2e17-463a-bfee-912c70ef5ea2", "workflowInstanceId": "8bc92b74-4546-4a89-99da-8a89f0b192d2", "status": "COMPLETED"}'
```
Completed subWorkflow:
![image](https://user-images.githubusercontent.com/24190726/217004089-e9d2ca0f-79ab-49be-9c08-e85c29d96072.png)

"Stucked" parent workflow
![image](https://user-images.githubusercontent.com/24190726/217004148-e7ca8c11-6a56-40d0-befa-40884945b17e.png)

**Additional context**
Simple task in workflow `subLogic` updated via api 
```
curl -X POST localhost:8080/api/tasks -H "Content-Type:application/json"  -d '{"taskId": "$taskId", "workflowInstanceId": "$workflowId", "status": "COMPLETED"}
```

**Comment by manan164** [comment]
Hi @mhorbatenko , Can you please describe the scenario in detail? I tried a number of times but I do see parent workflow is completed. We can chat [here](https://join.slack.com/t/orkes-conductor/shared_invite/zt-xyxqyseb-YZ3hwwAgHJH97bsrYRnSZg) for more realtime collaboration.

**Comment by mhorbatenko** [comment]
Hello, @manan164, thx for your respond. 
"Like how frequently this happens? " - i've read the [docs](https://conductor.netflix.com/reference-docs/sub-workflow-task.html) and tried to implement.
And parent workflow doesn't change status when sub-workflow in status `COMPLETED`. 

"Can you please describe the scenario in detail" - Just 1 workflow with simple task. And worflow with task type `SUB_WORKFLOW`, which "trigger" the another workflow, as i've posted above.

**Comment by manan164** [comment]
Hi @mhorbatenko , the in-memory implementation is not suited for production use cases. However, We can chat [here](https://join.slack.com/t/orkes-conductor/shared_invite/zt-xyxqyseb-YZ3hwwAgHJH97bsrYRnSZg) for more realtime collaboration.

**Comment by v1r3n** [comment]
Closing this issue, @mhorbatenko I suggest try this with a redis instance, and please re-open if the issue persists.
