### ISSUE TITLE
Questions related to "Running Workflow"

### ISSUE THREAD

**Issue by smilesj** [Netflix/conductor#349]
Hello.

I run workflow using " conductor server ".
Another external server is managed using the " WorkflowTaskCoordinator " on another external server.

Q1. I know how to inject parameters when starting the workflow.
But I'd like to inject parameter value into the ' User Task ' when workflow is running. Is there any way?

Q2. Here's another question.
Is there any way to learn from external servers when workflow fails or finished? 
Except for checking the status of " workflow " to " conductor server " regularly.

**Comment by apanicker-nflx** [comment]
1. Parameter values cannot be injected into a task after starting the workflow and it is in RUNNING state.
2. You can add an implementation of [WorkflowStatusListener](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowStatusListener.java) to notify you once the workflow fails or completes successfully.

**Comment by MaksimRT** [comment]
@smilesj Could you how an example how to use [WorkflowStatusListener] to notify once the workflow fails or completes successfully? 
Thanks in advance!
