### ISSUE TITLE
[DOC]: swagger-ui url is error

### ISSUE THREAD

**Issue by HQCND** [Netflix/conductor#3496]
URL：https://conductor.netflix.com/devguide/running/source.html

<img width="999" alt="image" src="https://user-images.githubusercontent.com/76543659/219636973-346499e6-31de-4e56-ad40-3bd92cb520e8.png">

**Comment by DarkSharkAsh** [comment]
The

**Comment by yasir-tasleem** [comment]
> URL：https://conductor.netflix.com/devguide/running/source.html
> 
> <img alt="image" width="999" src="https://user-images.githubusercontent.com/76543659/219636973-346499e6-31de-4e56-ad40-3bd92cb520e8.png">

Please assign this to me
