### ISSUE TITLE
Question (or bug?) regarding "Poll Count" information for a task

### ISSUE THREAD

**Issue by picaron** [Netflix/conductor#353]
When looking at a workflow execution, I see different values for `Poll Count` on each task in the workflow

Example, this task has a poll count of 4: 

<img width="599" src="https://user-images.githubusercontent.com/507577/32070822-79216a42-ba5b-11e7-9a93-b5cfb10508fe.png">

And in the logs of the service hosting the HTTP task, I can see the API is called 5 times in total, even though it works on the first attempt.

I am trying to understand why this is happening. Any explanation on the poll count would be appreciated :)

Thanks

**Comment by muralicmr** [comment]
Hi @picaron - did you figure out what is poll count and if its possible to configure this/limit this to 1?

**Comment by picaron** [comment]
Hi @muralicmr 
no sorry I havent used Conductor in 2 years
maybe you should open a new issue

**Comment by sanyamsidana** [comment]
We are also facing this issue, @muralicmr - did you figure out something?

**Comment by muralicmr** [comment]
we observed that there is a workflow sweeper which increaments the poll_count based on workflow_sweeper_thread_count and decider_sweep_frequency_seconds. We did not need this functionality hence we set decider_sweep_disable to true. After this the poll count was always 1.
