### ISSUE TITLE
[FEATURE]: Replace Elastic Search with Open Search for better M1 Mac compatibility

### ISSUE THREAD

**Issue by sandeep540** [Netflix/conductor#3556]
Please read our [contributor guide](https://github.com/Netflix/conductor/blob/main/CONTRIBUTING.md) before creating an issue.   
Also consider discussing your idea on the [discussion forum](https://github.com/Netflix/conductor/discussions) first.

## Describe the Feature Request
 Replace Elastic Search with Open Search for better M1 Mac compatibility

## Describe Preferred Solution
use - https://hub.docker.com/r/opensearchproject/opensearch

**Comment by v1r3n** [comment]
Hi @sandeep540 does it support ES6?
