### ISSUE TITLE
unauthorized: incorrect username or password - CassandraEventHandlerDAOSpec

### ISSUE THREAD

**Issue by jkaipa** [Netflix/conductor#3569]
I am seeing the following error when I try to do gradle build on my windows box which has Java 17 on it. Any one faced this issue?
`
22:11:39.841 [docker-java-stream--831761403] ERROR com.github.dockerjava.api.async.ResultCallbackTemplate - Error during callback
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Head \"https://registry-1.docker.io/v2/testcontainers/ryuk/manifests/0.3.1\": unauthorized: incorrect username or password"}
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.15.3.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by v1r3n** [comment]
Hi @jkaipa 

The error is coming when trying to pull the docker image for the test containers.  I would check a few things to see if my docker desktop is on the latest version and if you can manually pull `testcontainers` image from docker hub.

Also, Conductor required JDK 11 so you will have to use that.

**Comment by jkaipa** [comment]
@v1r3n I understand that conductor requires JDK 11, but how does the groovy test authenticate docker registry? Do we configure credentials somewhere?

**Comment by jkaipa** [comment]
Ok. The solution is to sign out from docker through system tray of windows and manually login in using docker login --username <username> from a cmd shell and rerun tests.
