### ISSUE TITLE
Can conductor workflow return actual response instead of workflow id in synchrounous way?

### ISSUE THREAD

**Issue by kiranvpawar** [Netflix/conductor#3574]
Can conductor workflow return actual response instead of workflow id in synchronous way? Caller will wait until response is received.

**Comment by BradenEads** [comment]
To my knowledge Netflix Conductor does not natively support returning the actual response in a synchronous manner. Conductor is designed for orchestrating asynchronous workflows and microservices, and it returns a workflow ID upon execution to allow tracking and management of the running workflow.

However, check out Orkes.io. It should be able to accomplish this. You can play around with this at https://play.orkes.io/.
