### ISSUE TITLE
[DOC]: build failed via Docker

### ISSUE THREAD

**Issue by l646505418** [Netflix/conductor#3586]
Hi，Team,I am using the Docker to run Conductor and I follow this https://conductor.netflix.com/devguide/running/docker.html instruction ,but there is a issue happend
![image](https://user-images.githubusercontent.com/50475131/233097309-ba8145e5-ee94-462b-97de-5ef9c4d6ebc3.png)

**Comment by manan164** [comment]
Hi @l646505418 , 
Can you please follow this [steps](https://github.com/Netflix/conductor/discussions/3307#discussioncomment-4612132)?

**Comment by l646505418** [comment]
Thanks @manan164

**Comment by l646505418** [comment]
Build successfully
