### ISSUE TITLE
InputData passed as String in the Workflow

### ISSUE THREAD

**Issue by salvatorevicari** [Netflix/conductor#360]
Hi Team,
Using the Java API, I created a new workflow definition, below the JSON

{
  "updateTime": 1510138061672,
  "name": "PostmanInstance",
  "version": 1,
  "tasks": [
    {
      "name": "postman_echo",
      "taskReferenceName": "postman_echo",
      "description": "PostMan Echo Service",
      "inputParameters": {
        "data": {
          "input1": 1,
          "input2": "ciao"
        }
      },
      "type": "SIMPLE",
      "startDelay": 0
    }
  ],
  "schemaVersion": 2
}

As you can see the inputParameters are composed by a JSON which contains an integer value and a String value. But when I run the workflow the whole inputParameters are passed in inputData variable as String , below the resulting workflow JSON.

"workflowId": "d37c736e-8b55-450e-bd0c-ab8e5297f801",
   "tasks": [
      {
         "taskType": "postman_echo",
         "status": "FAILED",
         "inputData": {
            "data": {
               "input1": "1",
               "input2": "ciao"
            }
         },
         "referenceTaskName": "postman_echo",
         "retryCount": 0,
         "seq": 1,
         .........
         "workerId": "salvatorevicari-Satellite-Pro-R50-B",
         "workflowTask": {
            "name": "postman_echo",
            "taskReferenceName": "postman_echo",
            "description": "PostMan Echo Service",
            "inputParameters": {
               "data": {
                  "input1": 1,
                  "input2": "ciao"
               }
            },
.....
In general, each inputParameter passed as Integer or Boolean seems to be converted as String value within the workflow execution.
Is there a way to pass inputData as it was defined in inputParameters?

**Comment by copierrj** [comment]
Are you sure you also observed this behavior for boolean input parameters and not just for numbers?

**Comment by salvatorevicari** [comment]
Hi copierrj,

you are right, the issue is related just for numbers, the boolean values work correctly.
Thank you.

**Comment by andrea11** [comment]
Hello everybody,
do you have any news about this issue? Otherwise, someone with more experience on conductor has an idea where the issue could come from?
Thank you

**Comment by cyzhao** [comment]
@andrea11 @salvatorevicari we will look into this, send us a PR if you like.

**Comment by salvatorevicari** [comment]
Hi @cyzhao , @andrea11 
The issue seems to be fixed in the newer version.

**Comment by salvatorevicari** [comment]
Hi @andrea11,
if I'm not wrong from 1.9.5 version

**Comment by andrea11** [comment]
Well, we upgraded recently to 1.10.17 and the issue seems to be still there...

**Comment by salvatorevicari** [comment]
Hi @andrea11 ,
You are right. Recently I upgraded my version to 1.12.2 and the issue is again there.

**Comment by salvatorevicari** [comment]
Hi @andrea11 , yes #809 fix the issue.
