### ISSUE TITLE
Request - provide config to turn off Elasticsearch

### ISSUE THREAD

**Issue by kpdude7** [Netflix/conductor#361]
Instead of requiring a change to the source code just to turn Elasticsearch off, can't this be done easily via a configuration in the conductor.yml (e.g. modify the appropriate base DAO to do nothing if the config is off)? I can imagine that a lot of companies that would like to use this product (including mine) frown on having to manually change 3rd party source code under any circumstances, especially for a basic function such as this. And because we don't want to change source code, we have to set up a dummy Elasticsearch instance in AWS and configure it just so our Conductor logs don't fill up with meaningless Elasticsearch errors.

**Comment by mudit3774** [comment]
@kpdude7 : If you go through the codebase carefully. It is not easy to remove dependencies on elastic search. For instance, some apis completely depend on ES like get workflows by corelation id. 

Maybe if we can clean up the dependency and write small abstractions for archival, we can go ahead with the a config like flag. You can track the following issue if you are interested : https://github.com/Netflix/conductor/issues/677

**Comment by kishorebanala** [comment]
https://github.com/Netflix/conductor/pull/858

This PR has removed IndexDAO from primary DAO's. I'm closing this issue as there isn't much activity for a while. If this doesn't address your concern, please open another issue.
