### ISSUE TITLE
[DOC]: Example for extending the conductor to get workflow status listener

### ISSUE THREAD

**Issue by karanbhola** [Netflix/conductor#3613]
## What are you missing in the docs
No Documentation is available that shows how can we extend conductor and use its listeners. I want to extend the conductor for Workflow Status Listener
## Proposed text
Need proper documentation and an example on how conductor can be extended and custom code can be send with conductor deployment

**Comment by manan164** [comment]
Hi @karanbhola , We will update the documentation for this. however, in the meantime, we always welcome community contribution. These are the high-level steps to extend the workflow status listener.
1.  Implement the interface [WorkflowStatusListener](https://github.com/Netflix/conductor/blob/main/core/src/main/java/com/netflix/conductor/core/listener/WorkflowStatusListener.java) in the conductor-community.
2. These are some of the samples from the [community](https://github.com/Netflix/conductor-community/tree/main/workflow-event-listener/src/main/java/com/netflix/conductor/contribs/listener/archive),
