### ISSUE TITLE
HTTP/2 Support?

### ISSUE THREAD

**Issue by rmohta** [Netflix/conductor#363]
We're thinking to use Conductor within our organization. And we'd like to use HTTP/2. What do you think about it? Is anyone working on it? If not, are you guys open to received PR for this?

**Comment by v1r3n** [comment]
@rmohta we are not working on the HTTP/2 support, but PR will be welcome.

**Comment by rmohta** [comment]
@v1r3n Cool. We'll work on that and send a PR when we're ready.
