### ISSUE TITLE
[FEATURE]: Provide feature to identify a specific client to execute the task

### ISSUE THREAD

**Issue by missioncoding** [Netflix/conductor#3646]
I am looking for a feature where i want to make sure my task will be executed by a particular client.
If there is already a feature for this i would be happy to know.

I am having some tasks that need to be performed on a private network which only some conductor clients running will have access.

If i submit a workflow/task currently i see any available client will start executing which may result in failure. hence i want to my task to be executed by some dedicated clients

This feature i need with priority.. can you please provide some inputs if we already some mechanism like this.

Thanks

**Comment by dcore94** [comment]
Are task domains useful? https://conductor.netflix.com/documentation/api/taskdomains.html

**Comment by missioncoding** [comment]
Thanks Task domain worked my purpose.
