### ISSUE TITLE
[FEATURE]: Publish a snapshot of most recent merged PRs.

### ISSUE THREAD

**Issue by alexmay48** [Netflix/conductor#3694]
Please read our [contributor guide](https://github.com/Netflix/conductor/blob/main/CONTRIBUTING.md) before creating an issue.   
Also consider discussing your idea on the [discussion forum](https://github.com/Netflix/conductor/discussions) first.

## Describe the Feature Request
_A clear and concise description of what the feature request is._

As part of the PR pipeline, we should automatically publish to a snapshot version when a PR is merged. This way way we can pull that published version into conductor community or even our personal repos to speed up development in the conductor community repo, as well as our own implementations to start testing and validation even sooner.

## Describe Preferred Solution
_A clear and concise description of what you want to happen._

When a new PR is merged, we auto-publish a snapshot with a version bump. At the time of writing this, the release version is 3.13.7. When a PR is merged, it can auto publish a snapshot of 3.13.8-SNAPSHOT. For breaking changes or large version changes, we can create different branches or have a version file we can change to 3.14.0, and it will automatically publish 3.14.0-SNAPSHOT. (This is similar to other large open source platforms like Spring).

## Describe Alternatives
_A clear and concise description of any alternative solutions or features you've considered._
N/A

**Comment by v1r3n** [comment]
cc: @apanicker-nflx
