### ISSUE TITLE
Gradle Build failure. Why does it point to a conductor-master directory which doesn't exist

### ISSUE THREAD

**Issue by jzkisscod** [Netflix/conductor#371]
Project directory: 
/Users/xxxx931/Projects/netflix/conductor
Run Build under directory
/Users/xxxx931/Projects/netflix/conductor/sever

> Configure project : 
Inferred project: conductor, version: 1.8.2-SNAPSHOT

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/xxxx931/Projects/netflix/conductor-master/build.gradle' line: 13

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '3.6.0']
> Failed to apply plugin [class 'nebula.plugin.info.dependencies.DependenciesInfoPlugin']
   > Could not create plugin of type 'DependenciesInfoPlugin'.
      > No signature of method: org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.DefaultVersionComparator.asStringComparator() is applicable for argument types: () values: []
        Possible solutions: asVersionComparator()

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by eric-lee-ltk** [comment]
@jzkisscod It works fine when using gradle 3.5.1 but fails as what you described when using gradle 4.3.1.

**Comment by jzkisscod** [comment]
@eric-lee-ltk 
My gradle version is:
Gradle 4.3
Build time:   2017-10-30 15:43:29 UTC
Revision:     c684c202534c4138b51033b52d871939b8d38d72

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_77 (Oracle Corporation 25.77-b03)
OS:           Mac OS X 10.12.6 x86_64

It is not working

**Comment by kishorebanala** [comment]
Closing this as this is outdated. Please open another issue if it still happens.
