### ISSUE TITLE
[FEATURE]: Support GOTO/move back previous Task

### ISSUE THREAD

**Issue by DiyuanZhang** [Netflix/conductor#3710]
## Feature Request
Allow the workflow to back to the previous task.
 
#### My Workflow Definition
My workflow is like **task A -> task B -> task C -> task D -> task E** -> ...

#### My Business Requirement
The requirement is when **task D** is **IN_PROGRESS**. The user can select to move the workflow back to **task B**.

#### My Current Solution
My current solution is when the user selects move back. Our system will call the **Terminate Workflow API** first and then the **Rerun Completed Workflow API**(with the reRunFromTaskId being task B).

This solution can work but it will clear previous task B and task C related history from **Task List**. 

## Preferred Solution
The conductor can provide an API to allow the workflow to go to the previous task.

**Comment by egandro** [comment]
I am no expert - but that sounds like a

```
task_a();


variable a = 0

while( a == 0 ) {
  task_b();
  task_c();
  task_d();
  if(!something(user))  {
    a = 1;
  }
}

task_e();
```
