### ISSUE TITLE
[Q] Performance

### ISSUE THREAD

**Issue by cheveyo20** [Netflix/conductor#373]
Hi,

from your experience, how is the performance, flow rate of conductor and with which hardware settings?
How many Workflows per hour?
How many Workers per hour etc?
How many downtimes? Did you manually fix things?
What are your hardware settings (How many dynomite DCs, Racks, Nodes? How many ES Nodes? How many Conductor Instances)?

vg Che

**Comment by saidatta** [comment]
Stats from 2016 @ Netflix

[Stats](https://cdn-images-1.medium.com/max/2000/1*HHdCGIAeDaU6PNWd7YTQxA.png)

https://medium.com/netflix-techblog/introducing-dynomite-making-non-distributed-databases-distributed-c7bce3d89404
