### ISSUE TITLE
Console output with a large number of null pointer exceptions

### ISSUE THREAD

**Issue by youngledo** [Netflix/conductor#3746]
**Details**
Conductor version: 3.13.7
Persistence implementation: Postgres
Queue implementation: Dynoqueues
Lock: Redis

**Screenshots**
<img width="1279" alt="image" src="https://github.com/Netflix/conductor/assets/68590897/d3015579-04d9-42b0-8018-2a924f5310f5">

**Comment by prajwalbandak** [comment]
Hey @youngledo , will love to work on this issue, Can you assign this one to me?

**Comment by youngledo** [comment]
Sorry, I forgot to pay attention to the issue. As the problem was discovered temporarily, not much information was recorded.
