### ISSUE TITLE
[DOC]: Inoffical docker containers and docker compose files

### ISSUE THREAD

**Issue by egandro** [Netflix/conductor#3749]
## Proposed text

Inoffical docker containers and docker compose files are available here - https://github.com/egandro/conductor-containers

**Comment by AHB102** [comment]
Is this issue still open ? I would like to contribute

**Comment by egandro** [comment]
I am out of Conductor. 

Jumped to n8n because of lack of upstream to patch things.

I suggest have a look at n8n. This is one of the most productive System I ever had in my life.
