### ISSUE TITLE
conductor-server failed to start

### ISSUE THREAD

**Issue by amid0** [Netflix/conductor#3795]
**Describe the bug**
Going through the instructions from here https://conductor.netflix.com/devguide/running/docker.html 
On docker-compose-up conductor-server failed to start.

**Details**
Nothing special. Just trying to launch a simple default configuration 

**To Reproduce**
Execute the next commands in CLI:
1. git clone https://github.com/Netflix/conductor.git
2. cd conductor/docker
3. docker-compose build
4. docker-compose up
5. conductor-server container exited with the code 2
6. output is:
: not found10:14:09 /app/startup.sh: line 14: 
: not found10:14:09 /app/startup.sh: line 16: 
: not found10:14:09 /app/startup.sh: line 18: 
: not found10:14:09 /app/startup.sh: line 21: nginx
: not found10:14:09 /app/startup.sh: line 22: 
: No such file or directoryartup.sh: cd: line 24: can't cd to /app/libs
: not found10:14:09 /app/startup.sh: line 28: 
2023-10-07 10:14:09 /app/startup.sh: line 41: syntax error: unexpected end of file (expecting "then")
2023-10-07 10:14:09 Starting Conductor server
2023-10-07 10:14:09 Running Nginx in background
2023-10-07 10:14:09 Property file: config-redis.properties
2023-10-07 10:14:09 config-redis.properties

**Expected behavior**
conductor-server container started successfully.

**Screenshots**
-

**Additional context**
Doing this on Windows 10
Docker Desktop 4.24.1 (123237)

**Comment by Robban1980** [comment]
@amid0 its related to the .gitattributes file included in the repo.
change your steps to this

1. git init (in your working folder)
2. Add a .gitattributes file with the following in it 
```
gradlew eol=lf
*.gradle eol=lf
*.java eol=lf
*.groovy eol=lf
spring.factories eol=lf
*.sh eol=lf
```
3. git add *
4. git commit -m 'git attributes'
5. git pull --allow-unrelated-histories https://github.com/Netflix/conductor.git
6. cd conductor/docker
7. docker compose build
8. docker-compose up

The important part is the .gitattributes file, it leaves the line endings of the files as unchanged when pulling the source.

**Comment by amid0** [comment]
@Robban1980  Thank you a lot.

In such a way, I'm able to run conductor.

I think It is better to add such information to the installation documentation.
