### ISSUE TITLE
ERROR:  No source files were specified  during build

### ISSUE THREAD

**Issue by gaoqichao021** [Netflix/conductor#380]
Building conductor-server
Step 1/10 : FROM java:8-jre-alpine
8-jre-alpine: Pulling from library/java
709515475419: Pull complete
38a1c0aaa6fd: Pull complete
cd134db5e982: Pull complete
Digest: sha256:6a8cbe4335d1a5711a52912b684e30d6dbfab681a6733440ff7241b05a5deefd
Status: Downloaded newer image for java:8-jre-alpine
 ---> fdc893b19a14
Step 2/10 : MAINTAINER Netflix OSS <conductor@netflix.com>
 ---> Running in 07bcf6bd725b
 ---> 2dabf04968b6
Removing intermediate container 07bcf6bd725b
Step 3/10 : RUN mkdir -p /app/config /app/logs /app/libs
 ---> Running in 7065b6a4ac4f
 ---> b8fb1bcddc6a
Removing intermediate container 7065b6a4ac4f
Step 4/10 : COPY ./docker/server/bin /app
 ---> c5e9263d2c0f
Removing intermediate container 79cc0ca4ebbc
Step 5/10 : COPY ./docker/server/config /app/config
 ---> a1718b208fde
Removing intermediate container 3528e333051d
Step 6/10 : COPY ./server/build/libs/conductor-server-*-all.jar /app/libs
ERROR: Service 'conductor-server' failed to build: No source files were specified

**Comment by saidatta** [comment]
you will have to do from the conductor repo's root directory.

```
cd conductor
cd server
../gradlew build
```

This will build the appropriate jar file in the build directory.

**Comment by rangabarath** [comment]
it works, thank you

**Comment by danielsitnik** [comment]
Indeed it works, perhaps it should be mentioned in the documentation at https://netflix.github.io/conductor/intro/
