### ISSUE TITLE
Separate docker images for UI/backend

### ISSUE THREAD

**Issue by jcantosz** [Netflix/conductor#39]
It would be useful to create separate docker images for the UI and for the backend. This would allow for custom UI implementation without modifying the server image. The can be tagged something like: conductor:ui and conductor:server. A third tag for the combined image could also be added (and may be the default for conductor:latest)

**Comment by jcantosz** [comment]
Will begin work, and track item here. 
Structure for changes will be as follows:
  /docker/UI -folder which will house docker node frontend
  /docker/server - folder which will house conductor server dockerfile
  /docker/serverAndUI - folder which will house the current image (server and ui in one)
Compose will be converted to use the two images to allow users more control.

**Comment by blueelephants** [comment]
Very good idea -  so in conjunction with the Dynomite image of @ipapapa (https://github.com/Netflix/dynomite/blob/dev/docker/Dockerfile) and the official ElasticSearch image, the solution could be completely scaled out using a bunch of Docker containers

**Comment by jcantosz** [comment]
Made changes suggested in issue #43.
Opened PR #45 for these changes.

**Comment by jcantosz** [comment]
Changes merged
