### ISSUE TITLE
What is the difference between v1r3n's dynamoDB image and the official one?

### ISSUE THREAD

**Issue by saidatta** [Netflix/conductor#393]
Can we use the existing docker-compose's images of dynamoDB and elasticsearch in production?

**Comment by saidatta** [comment]
After researching from the issues, From my understanding, v1r3n's DynamoDB image is meant for demo purposes only, to keep up with the latest changes, it is recommended to use the official one.

Correct me if I am wrong.

**Comment by v1r3n** [comment]
@saidatta that is correct.
