### ISSUE TITLE
JavaDoc Missing

### ISSUE THREAD

**Issue by marc-christian-schulze** [Netflix/conductor#395]
It's hard to believe that Conductor is used productive when there is almost no JavaDoc provided. Only a very few number of methods contain JavaDoc documentation.

Please add JavaDoc documentation at least for the DAO interfaces.

**Comment by saidatta** [comment]
I agree. That writing Java code for some of the features is un-necessarily non-trivial.

**Comment by saidatta** [comment]
I agree. Wish there was more documentation on JavaDoc.

**Comment by saidatta** [comment]
I agree. I had to look into IntegrationTests, JUnits to figure out some of the missing info. It would be greatly appreciated. 
I'll suggest we add them wherever is needed as well.

**Comment by v1r3n** [comment]
Thanks for the feedback.  We will address this in the future commits.

@pctreddy
