### ISSUE TITLE
Workflow Data Retention

### ISSUE THREAD

**Issue by cheveyo20** [Netflix/conductor#396]
Hi,

how is the data life cylce in conductor?
I encounter the issue that my dynomite / redis keeps everything forever :)
What can i do about that? Is there are setting or is there even a data strategy implemented?

greets

**Comment by saidatta** [comment]
I am curious. Can you elaborate on your issue?

**Comment by cheveyo20** [comment]
Yep :) For example if i start workflows and they are executed successfully, then there is still the information in the redis database like the keys with WORKFLOW_TO_TASK, CORR_ID_TO_WORKFLOWS and so on. So if i progress now a lot of Workflows in the end i do have more than 10 million keys and keeps rising xD So when is a completed workflow deleted from dynomite/redis after execution?

**Comment by saidatta** [comment]
I think this might be what you are looking for.

https://github.com/Netflix/conductor/issues/240

> currently there is no delete on the workflow. However, you can either overwrite the existing definition or create a new one. There is no additional overhead. We do plan to prioritize this for the coming quarter though.

**Comment by cheveyo20** [comment]
I think this refers to the workflow metadata (the dsl definition), not to an workflow instance

**Comment by SlanginBits** [comment]
@cheveyo20 

Is this what you're looking for?

`curl -X DELETE --header 'Accept: application/json' 'http://{host}:{port}/api/workflow/{workflowid}/remove?archiveWorkflow=false'`

**Comment by apanicker-nflx** [comment]
You should be able to delete completed workflows using the API mentioned in the previous comment.

**Comment by pitumalkani** [comment]
Hi, 
I can see that the /api/workflow/{workflowid}/remove gives you 204, but when we hit  GET /workflow-api/api/workflow/{workflowid} we get the workflow execution details.

**Comment by apanicker-nflx** [comment]
@pitumalkani Please ensure that you set the query param `archiveWorkflow` to false when removing the workflow, else this workflow is archived and will be available to be queried.
