### ISSUE TITLE
Response from POST /workflow/{name}

### ISSUE THREAD

**Issue by atom-x** [Netflix/conductor#397]
Is it correct understanding that conductor doesn't return the result of flow execution?
So if I have workflow which has 1 task to call some service and this service responds with some payload, this payload cannot be return to to client of conductor?

**Comment by saidatta** [comment]
What do you mean by client of conductor? Do you mean the Conductor's Client code? or the UI?

**Comment by atom-x** [comment]
http client that does POST /workflow/{name}

**Comment by atom-x** [comment]
basically, the question is - does conductor support sync executing of the flow and returning the result of the flow to the client that initiated the flow?

**Comment by saidatta** [comment]
Let me know if my understanding is skewed. 

> if a client initiates a workflow, how can I send back the response once the workflow succeeds or failed?

What we do is that client should poll API with workflow ID and _extract_ output, as shown in UI

**Comment by pctreddy** [comment]
@atom-x , I am closing this issue since @saidatta already answered your question.
