### ISSUE TITLE
The http DELETE&PUT action not works from non-docker-host server

### ISSUE THREAD

**Issue by chunchill** [Netflix/conductor#398]
We run into a quite strange problem：We  are launching the conductor sever with docker container.  now the API calls of all HTTP actions (e.g. POST,GET,PUT,DELETE) work fine on the docker host，however, all of the APIs of DELETE and PUT actions are not working if we try a 'curl' outside the docker host (we just call it 'non-docker-host server').
The following curl action works fine on the docker host, but it does not work on another server.
`curl -X DELETE --header 'Accept: application/json' 'http://SERVER_IP:PORT/api/metadata/taskdefs/tiandi_dd'`

The following curl action works fine on both docker host and another server:
`
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '[
 {
   "name": "tiandi_dd",
   "retryCount": 3,
   "timeoutSeconds": 1200,
   "outputKeys": [
     "status"
   ],
   "timeoutPolicy": "TIME_OUT_WF",
   "retryLogic": "FIXED",
   "retryDelaySeconds": 600,
   "responseTimeoutSeconds": 3600
 }
]' http://SERVER_IP:PORT/api/metadata/taskdefs'
`

Have anyone ever met this problem？

**Comment by saidatta** [comment]
hmm. It works fine for me.

I tested where I have a EC2 instance with docker & i did a curl command from another machine.

**Comment by chunchill** [comment]
@saidatta Thank you ! we have tried installing the same environments on public clouds, it works now!
I'd like to close this issue! thanks again!
