### ISSUE TITLE
BUG - MySqlQueueDAO::pollMessages always fails

### ISSUE THREAD

**Issue by marc-christian-schulze** [Netflix/conductor#399]
The method pollMessages of the MySQLQueueDAO always fails with an Exception.
Looking at the Implementation https://github.com/Netflix/conductor/blob/master/mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLQueueDAO.java#L72 the method first calls pop() which calls popMessages() which marks all messages returned as popped. The following readMessages() call will try to find messages with the given ids but not marked as popped which finally fails.

The only use case for this broken method is currently in the DynoQueue implementation.

**Comment by v1r3n** [comment]
@marc-christian-schulze #417 should have fixed this.  Closing this, but please reopen if the issue still exists.  Will create an RC or you can use the latest snapshot to verify the changes.
