### ISSUE TITLE
Update server-all jar name

### ISSUE THREAD

**Issue by jcantosz** [Netflix/conductor#40]
The docs, here: [https://netflix.github.io/conductor/server/](https://netflix.github.io/conductor/server/) show that the conductor-server-all jar should be named as such: ```java -jar conductor-server-all-VERSION.jar```

The gradle build creates the following jar:
```.//server/build/libs/conductor-server-1.6.0-SNAPSHOT-all.jar```

I would like it to be renamed as shown in the docs (*all* before version)

**Comment by v1r3n** [comment]
Updated the documentation.
