### ISSUE TITLE
Setting priority on the task

### ISSUE THREAD

**Issue by jansonz** [Netflix/conductor#401]
Hi Netflix team,

Is there a way to set a priority when creating a task? We see some references in the code that the concept might be supported on the backend data model however see no mentioning of this in the documentation.

Thank you,
Regards,
J

**Comment by v1r3n** [comment]
This is not available currently, but we might consider adding this in future.
Addition of priorities require support for priority queues in `dyno-queues`.

**Comment by v1r3n** [comment]
Closing the issue.  Please reopen if required.
