### ISSUE TITLE
Paused subworkflow allows join task to continue

### ISSUE THREAD

**Issue by amazinglyemma** [Netflix/conductor#402]
I have a workflow with a dynamic fork, which generates sub workflows. I have it followed by the dynamic join. If I set one of the sub workflows to pause, conductor counts it as being complete and allows the join to finish, moving onto the next step in the main workflow. 

Is this a bug or how it is supposed to work? Is there anyway I can get it to wait for all the dynamic task sub workflows to be fully complete before continuing?

**Comment by v1r3n** [comment]
@amazinglyemma this is not an expected behavior.  Tagging as bug.
