### ISSUE TITLE
Not able to build release 1.8.1 

### ISSUE THREAD

**Issue by akashbhunchal** [Netflix/conductor#404]
I am able to gradle build the repo if I GIT clone it. But when I download and build the 1.8.1 release tar.gz I am getting this eror:

> XXXXX> ../gradlew server
> Git repository not found at /XXXXX/conductor-1.8.1 -- nebula-release tasks will not be available. Use the git.root Gradle property to specify a different directory.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: nebula/plugin/dependencylock/DependencyLockPlugin$LockVersionConstaint
> > java.lang.NoClassDefFoundError: nebula/plugin/dependencylock/DependencyLockPlugin$LockVersionConstaint

I believe this is due to the absence of .git folder. I am not sure what to do here as I do not have a git.root ?

**Comment by saidatta** [comment]
Is there a reason why wouldn't want to clone it? 

You could technically download the jar file from maven central and pass the configurations as specified.

https://netflix.github.io/conductor/server/

**Comment by akashbhunchal** [comment]
Thanks! Will do that . I just wanted to take one of the releases and not work on the head as I am planning to use this in production and would not be contributing to it right now. 

I want to use a release, so that I can document this fact in our internal documentation.

**Comment by cquon** [comment]
In the root directory, for me:

./gradlew build works.
but
gradle build fails.

```
[cquon@localhost conductor]$ ./gradlew build
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

> Configure project :
Inferred project: conductor, version: 1.8.2-SNAPSHOT

> Configure project :conductor-server
A constructor for `org.gradle.api.internal.java.JavaLibrary` is used by Shadow plugin v1.2.x, and has been preserved for compatibility. This has been deprecated and is scheduled to be removed in Gradle 5.0. If you're using the Shadow plugin, try upgrading to v2.x.

Publication nebula not found in project :.
[buildinfo] Not using buildInfo properties file for this build.
Publication named 'nebula' does not exist for project ':' in task ':artifactoryPublish'.

BUILD SUCCESSFUL in 56s
78 actionable tasks: 13 executed, 65 up-to-date
[cquon@localhost conductor]$
[cquon@localhost conductor]$ gradle build
Inferred project: conductor, version: 1.8.2-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: nebula/plugin/dependencylock/DependencyLockPlugin$LockVersionConstaint
> java.lang.NoClassDefFoundError: nebula/plugin/dependencylock/DependencyLockPlugin$LockVersionConstaint

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Any clue why?

Documentation says both should work (https://netflix.github.io/conductor/server/)

**Comment by rkrsingh** [comment]
try changing the version of nebula in build.gradle to 4.0.2 or 5.0.0

example:
plugins {
    id 'nebula.netflixoss' version '4.0.2'
}
