### ISSUE TITLE
Worker does not execute task

### ISSUE THREAD

**Issue by lucas-pinheiro-ipremios** [Netflix/conductor#405]
I've noticed that when Netflix Conductor has a large number of workflows running at the same time, the request /api/tasks/poll/{tasktype} returns nothing, even with hundreds of tasks scheduled.

So, when I open the Conductor UI (running at port 5000), it shows hundreds of running workflows (which will never reach the "complete" status), each of them stuck in some "scheduled" task, waiting for its execution, even the workers working at full. Everything is in a single machine, and the workers always make localhost requests at http://localhost:8080/api/

So, how can I solve it?

**Comment by saidatta** [comment]
Out of curiosity, are you running the server with in memory database, redis or dynomite? If running dynomite, what is the cluster size?

**Comment by saidatta** [comment]
I think this might be helpful regarding the Timed_out 

https://github.com/Netflix/conductor/issues/362

For Timed-out feature, You need to leverage the `WorkflowSweeper` which is apparently disabled by default.

**Comment by lucas-pinheiro-ipremios** [comment]
Oh man, now it works! Thank you very much!

**Comment by v1r3n** [comment]
@lucas-pinheiro-ipremios closing the issue.  Please re-open if required.

**Comment by jansonz** [comment]
Can you share any details on how you solved the "waiting forever tasks"? I have the same issue... no errors in logs... :(

**Comment by dskarataev** [comment]
@lucas-pinheiro-ipremios I have the same issue please share how to solve it :)

**Comment by Kristin0** [comment]
@lucas-pinheiro-ipremios hey, we need your help :(

**Comment by Kristin0** [comment]
@jansonz @dskarataev did you find the solution?

**Comment by Kristin0** [comment]
@v1r3n do i need to specify it? i just have a
```
  - name: db
     value: "redis_cluster" # options: redis, redis_cluster, redis_sentinel, dynomite, memory
  - name: workflow_dynomite_cluster_hosts
     value: "$(ELASTICACHE_ENDPOINT):6379:eu-central-1"
```

**Comment by v1r3n** [comment]
You will need `availabilityZone` property that matches with the connection string for redis cluster `conductor.redis.hosts`.

The connection string for redis will be of the for `host:post:availability_zone` and the availability_zone part should match with the `availabilityZone` property.

**Comment by Kristin0** [comment]
and what if i have 3 zones ?

**Comment by v1r3n** [comment]
`availabilityZone` property is used for sharding across multiple zones when using Dynomite.  If you have multiple  zones, you can just pick one and set that as the `availabilityZone` property for all the deployment.  This property is meaningful only when using Dynomite, where all the connections are zone aware and we use it as a proxy to create the shards for queues.

For the redis cluster, you can just set availabilityZone to one of them, or even something static like `abcd` - it does not impact.

**Comment by Kristin0** [comment]
yes it helps, thanks !! @v1r3n
