### ISSUE TITLE
Task never polled by worker and timeout

### ISSUE THREAD

**Issue by nbraquart** [Netflix/conductor#407]
Hello,

I would have thought the timeoutSeconds attribute set at task definition level would start from the moment the task goes in SCHEDULED state. However, it appears that the timeout runs from the time task has been changed to IN_PROGRESS status.

Thus, if a task definition has no corresponding worker, or if the worker has stopped polling for any reason, the workflows relying on this task will be stuck forever.

The documentation is clear on this point, so I believe this is expected. I was just wondering what were the rationale behind this? And could we maybe imagine a way to handle the case explained above?

Thanks!

**Comment by lucas-pinheiro-ipremios** [comment]
Same problem here

**Comment by v1r3n** [comment]
@nbraquart @lucas-pinheiro-ipremios The solution will be to introduce `poll timeout`.  This should be configurable in Task Definition.  If the task is not polled within the timeout specified, it would get timed out.

We have plans to implement this not prioritized.  Happy to accept a PR if you think you can contribute this.

**Comment by nbraquart** [comment]
Hello @apanicker-nflx or @kishorebanala ,

Do you think this issue could be reopened? I am not sure to understand why it was closed by Viren. Or is there another way to track this potential feature?

Thanks!
