### ISSUE TITLE
Metadata Management - Deleting an existing Workflow

### ISSUE THREAD

**Issue by blueelephants** [Netflix/conductor#41]
In the swagger UI, I can find a way to delete task-definitions.

However, I cannot find a way to delete an existing workflow.

Is there no way currently to delete an existing workflow?

I tried to construct something like this, but without success:
<pre>
curl -X DELETE --header 'Accept: application/json' 'http://my_host:my_port/api/metadata/workflow/main_workflow'
</pre>

**Comment by v1r3n** [comment]
We haven't exposed API for deleting workflows yet.  The reason being that, it could cause issues with running workflows and makes it harder to visualize the previously completed flows.

The idea is to be able to do that, but with a soft delete.

**Comment by blueelephants** [comment]
Thanks for clarification - a soft delete would be great.
