### ISSUE TITLE
 ConductorServer and mysql connection

### ISSUE THREAD

**Issue by prajithasasidar** [Netflix/conductor#413]
1)In ConductorServer .java at line number 163 it is written as given below, how do we connect to mysql in this case ?
case mysql:
			logger.info("Starting conductor server using MySQL data store", db);
			break;
2) We have used the EmbeddedElasticSearch.start(); same as in memory and it is working
But the event hanbdlers and callback afterseconds are not working for us when connected to mysql .Is the above code breaking this functionality ?

3) Is there any way to give time out for workflows a part from task time out ?

**Comment by v1r3n** [comment]
@picaron do you have any thoughts on the above?

**Comment by picaron** [comment]
@prajithasasidar  you simply need to set the appropriate db type and JDBC parameters in your `config.properties` :

```
db=mysql
jdbc.url=jdbc:mysql://host:3306/database
jdbc.username=username
jdbc.password=password
```

**Comment by prajithasasidar** [comment]
Thanks for the reply , but we are not using docker

**Comment by BhuhanJ** [comment]
@picaron  - can you please tell me the complete steps to integrate it with mysql without docker.

Any help will be appreciated.
