### ISSUE TITLE
Kafka Event Task

### ISSUE THREAD

**Issue by timwu** [Netflix/conductor#414]
We would like to include event emissions to a kafka topic in our conductor workflows. Is there any effort going on that introduce Kafka as a possible event sink type? Is this otherwise open for contributions?

**Comment by timwu** [comment]
Looking at implementing this myself, I thought of doing this as a module to be loaded in at runtime. However this doesn't seem to be doable due to the [QueueType](https://github.com/Netflix/conductor/blob/ff3298b8cf6160431428f19bd89fce95c5f2a5e7/core/src/main/java/com/netflix/conductor/core/events/EventQueues.java#L42) enum. 

Any opinions on loosening the queue type to be a `String`? I think that would allow `EventQueueProviders` to be registered on startup via a guice module. 

AFAICT, this wouldn't cause a loss in runtime safety since the [QueueType.valueOf()](https://github.com/Netflix/conductor/blob/ff3298b8cf6160431428f19bd89fce95c5f2a5e7/core/src/main/java/com/netflix/conductor/core/events/EventQueues.java#L64) call would have failed at runtime anyways. This would replace that with a check against available queue types in the `providers` map.

**Comment by timwu** [comment]
Submitted #418 in reference to the above comment.

**Comment by v1r3n** [comment]
@timwu merged the PR to the dev.  Happy to accept the PR against `dev` branch for the kafka support.
