### ISSUE TITLE
[Suggestion] Task logs within the TaskDetails tab

### ISSUE THREAD

**Issue by saidatta** [Netflix/conductor#416]
Hello,

Is there any way to view the task logs within the Task Details tab? if not, then that feature would be quite beneficial for a huge workflow.

E.g., if we have a 700 parallel dynamic tasks within a workflow and want to easily navigate between tasks. it would appears to be much easier to navigate it in `Task Details` tab than the Execution Flow tab.

**Comment by v1r3n** [comment]
@saidatta it is not possible in the current UI.  However, it is possible to add - and we can consider this for future iterations.

@pctreddy
