### ISSUE TITLE
Multipart/Related Request - Question

### ISSUE THREAD

**Issue by harshkumar1** [Netflix/conductor#420]
This is a question and not an issue as such.
Wanted to check on how can we create a multipart/related request workflow to be processed by the server. I was actually not able to find a way to provide the form-data

**Comment by v1r3n** [comment]
to start the workflow the inputs are always in JSON.  multiplart or form-data is not supported.
You can probably write a proxy that reads the multipart data from a form submission, parses into JSON and starts a workflow.
