### ISSUE TITLE
How to build jar with name as conductor-server-all-VERSION.jar 

### ISSUE THREAD

**Issue by rkrsingh** [Netflix/conductor#422]
I tried following : 
1) taking the latest code from master on windows using command "gradlew build," I found **conductor-server-0.1.0-dev.0.uncommitted-all.jar**
2) taking the stable release 1.8.1 and build on windows using command "gradlew build," I found **conductor-server-0.1.0-dev.0.uncommitted-all.jar**

3) taking the stable release 1.8.1 and build on **unix** using command "./gradlew build," I found **conductor-server-0.1.0-dev.0.uncommitted-all.jar**

How do I build a jar with name like conductor-server-all-VERSION.jar as suggested by https://netflix.github.io/conductor/server/    ?

**Comment by v1r3n** [comment]
VERSION --> is the placeholder for the actual version or the one you see based on the branch/fork name.

**Comment by rkrsingh** [comment]
I think you mean after building generated jar name will be 
conductor-server-VERSION**-all**.jar
instead of 
conductor-server-**all-**VERSION.jar
