### ISSUE TITLE
One-time tasks support

### ISSUE THREAD

**Issue by LiranBri** [Netflix/conductor#425]
Hello,
Is it possible to define a task which is not based on some 24/7 microservice?

for example, If I want to trigger once a day at 00:00UTC a shell script, execute some long-running node script (lets say 4 hours), or to start some Docker container.
all those examples are tasks which are not hosted on some service which is alive all the time and can poll the tasks queue and figure out it should start

thank you

**Comment by v1r3n** [comment]
@LiranBri This is not supported today.  Essentially you want to execute a workflow or task at a schedule time.  A proper scheduling framework might be a better solution for that as opposed to Conductor.

**Comment by LiranBri** [comment]
@v1r3n thank you
Can you give examples of such frameworks if you are aware of any that support my requirements?
