### ISSUE TITLE
I'm working on a new python3 client

### ISSUE THREAD

**Issue by bioslikk** [Netflix/conductor#427]
Hello Contributors,
I'm using **Conductor** to orchestrate data science micro services for my Mater's thesis.
Since I'm a python fan, I'm working on a python3 worker lib that I named **condu3**.

Here is a sample of **condu3**

![condu3_sample_worker](https://user-images.githubusercontent.com/13501228/36234333-5a10914e-11e2-11e8-822e-62481097d4f6.png)

What do you think ?

**Comment by v1r3n** [comment]
@bioslikk there is a python client in the client module.  Do you want to take a look at it and if there are any improvements, maybe send a PR against that module?

**Comment by bioslikk** [comment]
Hello @v1r3n. Yes I saw the conductor.conductor.py that you wrote. It's awesome! I converted it to python3, made some minor changes and I'm using it.
With condu3 is like conductor.ConductorWorker.py file with added functionalities and the representation of tasks, workflows, etc... with python objects. I'm doing this because I want to programmatically define new tasks and workflows in the quickest way possible:
![condu3_example_define task](https://user-images.githubusercontent.com/13501228/36291526-5e546c4e-12c3-11e8-9b51-5c6a004da75d.png)
(example in how to define a task)

 Also in the future I plan on creating a tool that allows the users to define workflows using a browser ui. Do you have any recommendations on doing that ?

**Comment by v1r3n** [comment]
@bioslikk It will be a great feature if you can update the UI to also being able to define workflows.
Checkout the `ui` submodule on the existing UI and I suggest use the same framework for the workflow creation UI.
