### ISSUE TITLE
Task timeout seconds

### ISSUE THREAD

**Issue by bioslikk** [Netflix/conductor#429]
I have long running tasks that can take 1 minute or 1 day to execute depending on the inputs. Is there a way to extend the timeout of a IN_PROGRESS task? For instance the worker could send a request saying that is still working on that task making that task not go to TIMED_OUT as long as he keeps sending those requests at at least **timeoutSeconds** intervals.

Could **responseTimeoutSeconds** be used to achieve this ?

**Comment by v1r3n** [comment]
timeout set at the task definition is fixed.  You want to set the timeout at the task definition to the max possible time it can take to run. e.g. in your case 1+ day.

**Comment by bioslikk** [comment]
Thanks @v1r3n . Will do.

**Comment by leikao** [comment]
Hi @v1r3n @cyzhao , I have the same problem. The long running task may not complete in `responseTimeoutSeconds`, so the worker will not send any response to conductor; then the task will be re-scheduled, and another worker may poll this task. Is there any way to send a response to conductor server saying *the task is still executing by me, please wait more time*?

**Comment by cyzhao** [comment]
@leikao what you ask for is a renew lease feature which I don't think is supported, @kishorebanala @apanicker-nflx please confirm. @leikao you are welcome to contribute, just work with us on the approach before work on the PR.

**Comment by leikao** [comment]
Thanks for your quick replay @cyzhao , I think this is a useful feature, especially for tasks that we could not estimate the execution duration, and I'm happy to work with you to complete this feature.
