### ISSUE TITLE
Separated UI not connecting to API

### ISSUE THREAD

**Issue by jcantosz** [Netflix/conductor#43]
I have a docker-compose that has the UI in a different container than the API:
[https://github.com/jcantosz/conductor/blob/docker-split/docker/docker-compose.yaml](https://github.com/jcantosz/conductor/blob/docker-split/docker/docker-compose.yaml). I can reach my UI at localhost:3000 and the API at localhost:8080

My UI instance pulls up but does not display any tasks or workflows. I believe I have missed a configuration for the UI. 

If I `docker exec -it <conductor:ui ID> bash` I can ping docker-server, and curl the API endpoints.

My compose pulls up with the following message 
```
conductor-ui_1      | {"name":"Conductor UI","hostname":"6a8fbf1a96a7","pid":42,"level":30,"msg":"Serving static /ui/dist","time":"2017-01-23T16:03:52.343Z","src":{"file":"/ui/dist/webpack:/src/server.js","line":13,"func":"canUseDOM"},"v":0}
conductor-ui_1      | {"name":"Conductor UI","hostname":"6a8fbf1a96a7","pid":42,"level":30,"msg":"Workflow UI listening at http://:::5000","time":"2017-01-23T16:03:52.418Z","src":{"file":"/ui/dist/webpack:/src/server.js","line":22},"v":0}
```

I haven't gotten a chance to do too much tracing, but the following files may be worth investigating:
ui/gulpfile.babel.js (gulp.task('browserSync'... )
ui/core/HttpClient.js (getURL function -- process.env.WEBSITE_HOSTNAME)
ui/api/sys.js (process.env.WF_SERVER is being used)

Note about the compose: it seems if I do not specify ipv4_address or the ipam information in the compose the UI does not pull up for me. Investigating why this is. I need to confirm that this was not due to other changes.

**Comment by v1r3n** [comment]
@jcantosz take a look at the updated docker file and docker-compose.  I have made some changes and was able to get it working on docker-compose.

**Comment by jcantosz** [comment]
Thanks @v1r3n I will take a look at that and roll it into my changes. Hopefully that fixes the issue.

**Comment by jcantosz** [comment]
Those changes allowed my docker-compose restructuring to work!
