### ISSUE TITLE
Is Expression supported in Decision System task?

### ISSUE THREAD

**Issue by ReddySrini** [Netflix/conductor#430]
Hi @v1r3n ,
             Can you let me know if the expression support is added in Decision Task? Something like ${workflow.input.number}%2=0
(This may be a continuation to defect https://github.com/Netflix/conductor/issues/161 )

Thanks.

**Comment by v1r3n** [comment]
@ReddySrini Yes.  You can use `caseExpression` with a javascript to achieve this.
The output of the expression evaluation should be the case branches.

**Comment by jagadeeshb22** [comment]
@ReddySrini ,
Can you please give an example using the caseExpression with javascript to achieve this.

**Comment by patrickbadley** [comment]
@jagadeeshb22 In case you hadn't found an example yet, here's one I'm using:
```
{
            "name": "verifyCreditDecision",
            "taskReferenceName": "verifyCreditDecision",
            "inputParameters": {
              "taskStatus": "${Get_Workflow_Details.output.response.body.tasks[?(@.referenceTaskName == 'Verify_Credit' && @.status == 'COMPLETED')].status}"
            },
            "type": "DECISION",
            "caseValueParam": "taskStatus",
            "caseExpression": "$.taskStatus.length > 0 ? 'Task Completed' : 'Task Not Completed'",
            "defaultCase": [
              {
                "name": "verifyCreditNotExecutedSoNotCompensating",
                "taskReferenceName": "verifyCreditNotExecuted",
                "inputParameters": {
                },
                "type": "EVENT",
                "sink": "conductor"
              }
            ],
            "decisionCases": {
              "Task Completed": [
                {...
```

**Comment by jagadeeshb22** [comment]
@patrickbadley  -- Awesome. Thank you..!
How can we get the output of the 'Task Completed' case.
Do we need to use it's task reference name in the output?
It could be great if you provide that information as well. 
Thanks in Advance..  :)

**Comment by ivoribeiro** [comment]
+1

**Comment by sev7nf** [comment]
@jagadeeshb22 is there any resolution?

**Comment by jagadeeshb22** [comment]
@sev7nf -
Yes, there is a solution to get the executed output. For that we need to remove the "outputParameters" field in workflow definition. so that, the output will come from the last executed task automatically as per the netflix documentation -- https://netflix.github.io/conductor/metadata/
