### ISSUE TITLE
Understanding of the /poll endpoint

### ISSUE THREAD

**Issue by fozboz** [Netflix/conductor#435]
Please confirm what the `/tasks/poll/{tasktype}` endpoint is used for. I have a workflow which currently has a SCHEDULED task. I can see this using the `/tasks/in_progress/{tasktype}` endpoint.

`[
  {
    "taskType": "task1",
    "status": "SCHEDULED",
    "inputData": {
      "task1in1": "input_number1",
      "task1in2": "input_number2"
    },
    "referenceTaskName": "wf1task1",
    "retryCount": 0,
    "seq": 1,
    "pollCount": 0,
    "taskDefName": "task1",
    "scheduledTime": 1519673773879,
    "startTime": 0,
    "endTime": 0,
    "updateTime": 1519673773881,
    "startDelayInSeconds": 0,
    "retried": false,
    "callbackFromWorker": true,
    "responseTimeoutSeconds": 0,
    "workflowInstanceId": "db837161-512b-460d-9f30-539f6b038e23",
    "taskId": "6d85e80a-557a-4f82-bbbd-3565f1ebf79a",
    "callbackAfterSeconds": 0,
    "workflowTask": {
      "name": "task1",
      "taskReferenceName": "wf1task1",
      "inputParameters": {
        "task1in1": "${workflow.input.wfin1}",
        "task1in2": "${workflow.input.wfin2}"
      },
      "type": "SIMPLE",
      "startDelay": 0
    },
    "queueWaitTime": 0,
    "taskStatus": "SCHEDULED"
  }
]`

But when polling this task type, I receive nothing.

`curl -X GET --header 'Accept: application/json' 'http://localhost:8080/api/tasks/poll/task1'`

I also receive nothing if I change the task to IN_PROGRESS. Is this correct behaviour?

**Comment by fozboz** [comment]
Yes indeed, it was related, because the polling of the task populates the `startTime` field. Read through some other issues and found that adding `EC2_AVAILABILITY_ZONE=us-east-1b` fixes this issue.

But I do still have an outstanding question. My dynomite config is as such:

`db=dynomite

# Dynomite Cluster details.
# format is host:port:rack separated by semicolon
workflow.dynomite.cluster.hosts=172.27.20.159:8102:us-east-1a;172.27.20.160:8102:us-east-1a;172.27.90.34:8102:us-east-1b;172.27.90.71:8102:us-east-1b

# Dynomite cluster name
workflow.dynomite.cluster.name=dyno_cluster

# Maximum connections to redis/dynomite
workflow.dynomite.connection.maxConnsPerHost=31

# Namespace for the keys stored in Dynomite/Redis
workflow.namespace.prefix=conductor

# Namespace prefix for the dyno queues
workflow.namespace.queue.prefix=conductor_queues

# No. of threads allocated to dyno-queues (optional)
queues.dynomite.threads=10

# Non-quorum port used to connect to local redis.  Used by dyno-queues.
# When using redis directly, set this to the same port as redis server
# For Dynomite, this is 22122 by default or the local redis-server port used by Dynomite.
queues.dynomite.nonQuorum.port=6379

# Transport address to elasticsearch
workflow.elasticsearch.url=es-url.domain.com:9300

# Name of the elasticsearch index
workflow.elasticsearch.index.name=conductor

EC2_AVAILABILITY_ZONE=us-east-1b`

The polling of queues does not work, however, if I change to `EC2_AVAILABILITY_ZONE=us-east-1a`. I don't understand why. The two racks, which are specified here, both contain the same data. Replication and distribution are working correctly.

Also, if I have it set to `EC2_AVAILABILITY_ZONE=us-east-1b` do all of the dynomite transactions occur on that rack with no load balancing?

**Comment by fozboz** [comment]
I spoke too soon!

Scheduled another task and I can't poll for it again. Changed to `EC2_AVAILABILITY_ZONE=us-east-1a`, restarted Conductor and I can now poll the task.

What is correct config for my scenario?

**Comment by fozboz** [comment]
So I _think_ I've been looking at this the wrong way.

My Dynomite topology is

![dynomite topology - page 1](https://user-images.githubusercontent.com/20321962/36907419-9fde3b6a-1e06-11e8-939c-74834fc1733f.png)

(Not AWS, and my racks/nodes are named as per the diagram).

I've been trying to replicate this topology in the Conductor config, telling it which rack a node is in. But when a token is sent to Dynomite, it's Dynomite's job to figure out where that token should go. This information is irrelevant to Conductor.

I've changed Conductor config so that all my hosts are in the same 'rack' and set the availability zone to match. Now I only have one queue and polls always work.

So I guess the idea behind declaring multiple zones for `workflow.dynomite.cluster.hosts` is that I have _another_ Conductor instance, which points to the other availability zone. Then when a workflow is triggered on either one, Conductor places it in either queue (round-robin?) which are then picked up by whichever worker is polling that particular queue (or whenever a load-balancer happens to redirect a poll to that Conductor instance).

Am I understanding correctly?

**Comment by fozboz** [comment]
Testing HA: Conductor has a fit when I take down one of the Dynomite hosts. The Conductor log will grow in size by 10MB every minute!

@v1r3n any help greatly appreciated!

**Comment by saidatta** [comment]
For now, I use Docker and specify a logging size limit. Say, logging size cannot exceed 500MB.

**Comment by fozboz** [comment]
Thanks @saidatta for the suggestion, which will certainly help with the log growth.
It's not just the log size that's the issue, though, HA isn't working at all.
