### ISSUE TITLE
How to fetch variable from workflow in eventHandler?

### ISSUE THREAD

**Issue by ReddySrini** [Netflix/conductor#438]
I have a workflow with below eventTask:
{
            "name": "task_2",
            "taskReferenceName": "task_2",
            "inputParameters": {
                "sink": "conductor",
                "ref_workflow": "${workflow.input.ref_flow1}"
            },
            "sink": "conductor",
            "type": "EVENT",
            "startDelay": 0
        }

And I have an eventHandler defined as : 
{
    "name": "event_handlerDef_completeTask",
    "event": "conductor:wf_eventEmitter:task_2",
    "actions": [
        {
            "action": "complete_task",
            "complete_task": {
			  "workflowId": "${workflow.input.ref_workflow}",
			  "taskRefName": "task_10",
			  "output": {
				"response": "${source.result}"
			  }
			},
            "expandInlineJSON": true
        }
    ],
    "active": true
}

I am not able to pass the value of param - "ref_workflow"(present in worklow) to eventHandler's workflowId variable. Can you let me know how to achieve this?

**Comment by dechykong** [comment]
I want help too!  Is there any demo to show how to use event ?

**Comment by saidatta** [comment]
I am not familiar with Event Handlers. But for variable inter-exchange between tasks, 
Can you try `task_2 .output.ref_workflow`?
