### ISSUE TITLE
Examples in documentation for HttpTask's headers parameter does not match code and will throw exception if used

### ISSUE THREAD

**Issue by oddperfect** [Netflix/conductor#44]
Documentation for HttpTask shows for headers to use:
```
    "headers": [
      {
        "Accept": "application/json"
      },
      {
        "Content-Type": "application/json"
      }
    ]
```
Declaration for headers in HttpTask.Input class in 'HttpTask.java' is:
`private Map<String, Object> headers = new HashMap<>();`

If you use the documented examples, the Jackson conversion to HttpTask.Input on line 102 throws an IllegalArgumentException. Documentation should be (notice the curly brackets):
```
    "headers": {
        "Accept": "application/json",
        "Content-Type": "application/json"
    }
```

**Comment by v1r3n** [comment]
Fixed:
https://netflix.github.io/conductor/metadata/#wiring-inputs-and-outputs
