### ISSUE TITLE
Tak is getting timed out for frequest requests

### ISSUE THREAD

**Issue by prajithasasidar** [Netflix/conductor#440]
Worker tasks are getting timed out if we request frequently.

We are getting error from the following lines of code

	long timeout = 1000 * taskType.getTimeoutSeconds();
		long now = System.currentTimeMillis();
		long elapsedTime = now - (task.getStartTime() + (task.getStartDelayInSeconds()*1000));
		
		if (elapsedTime < timeout) {
			return;
		}

task.getStartTime()  is zero whenever we get time out.

Can you please suggest. we are using mysql and not using docker also.

**Comment by pctreddy** [comment]
@prajithasasidar Can you paste the error that you are getting and the also task definition ?
