### ISSUE TITLE
How to End a workflow after a decisions 

### ISSUE THREAD

**Issue by rabonja** [Netflix/conductor#444]
I have a decision that will return a true or false.  If the return is true I have a more task to run.  But for the false I just want to end the work flow completely.  It there a specific entry to put in for ending the work flow in the false case? 

"false": [
            ]

**Comment by v1r3n** [comment]
@rabonja you can have a branching where `false` leads to no more tasks.  That will essentially end the workflow.  `true` branch of the decision could run a set of tasks.  equivalent of this in a programming lang will be something like

```java
void workflow() {
   if(true) {
      //bunch of statements
   }
   //else do nothing which essentially returns out of the function
}
