### ISSUE TITLE
configure POST /workflow/{name} to Return "output" instead of workflow id 

### ISSUE THREAD

**Issue by vish-k** [Netflix/conductor#445]
Hello,
When workflow is started using _POST /workflow/{name}_, the response is workflow id & to see output, we have to execute _GET /api/workflow/{workflow-id}_.

Is it possible to configure the workflow to return the output instead of just workflow id in response to _POST /workflow/{name}_ ?

My use case is, to execute few "http_request" and return combined/merged response but I am trying to avoid second _GET /api/workflow/{workflow-id}_ to get "output"

**Comment by pctreddy** [comment]
@vish-k This feature is not supported and will break the contract and backward compatibility of existing integration. This change doe not see reasonable.
