### ISSUE TITLE
Question on value of queues.dynomite.nonQuorum.port

### ISSUE THREAD

**Issue by kpdude7** [Netflix/conductor#453]
Simple question: Given the following dynomite.yml:
dyn_o_mite:
  datacenter: us-east-1
  rack: us-east-1a
  listen: 0.0.0.0:8102
  dyn_listen: 0.0.0.0:8101
  dyn_seed_provider: simple_provider
  dyn_seeds:
     - 10.240.71.14:8101:us-east-1a:us-east-1:1111111111
     - 10.240.71.53:8101:us-east-1a:us-east-1:2222222222
     - 10.240.71.117:8101:us-east-1c:us-east-1:1111111111
     - 10.240.71.84:8101:us-east-1c:us-east-1:2222222222
     - 10.240.71.99:8101:us-east-1c:us-east-1:3333333333
     - 10.240.71.155:8101:us-east-1d:us-east-1:1111111111
     - 10.240.71.135:8101:us-east-1d:us-east-1:2222222222
     - 10.240.71.160:8101:us-east-1d:us-east-1:3333333333
  tokens: 3333333333
  servers:
  - 127.0.0.1:6379:1
data_store: 0
  stats_listen: 0.0.0.0:22222
  mbuf_size: 65536
  max_msgs: 300000
  read_consistency: dc_safe_quorum
  write_consistency: dc_safe_quorum
  auto_eject_hosts: true
  server_retry_timeout: 30000
  server_failure_limit: 3
  timeout: 10000

What should the value of queues.dynomite.nonQuorum.port be in conductor.yml?
1. 8101
2. 8102
3. 6379
4. 22122
5. 22222
(NOTE: The redis process is running on 0.0.0.0:6379.)

**Comment by v1r3n** [comment]
`22122`
