### ISSUE TITLE
Elasticsearch: is it possible to connect to the REST API port instead of the native port with the current implementation?

### ISSUE THREAD

**Issue by picaron** [Netflix/conductor#455]
In our deployment, we do not allow services to connect to the native elasticsearch port for security reasons.

Is it possible to connect to Elasticsearch via the REST API port with the current implementation?

Also note that in future versions of Elasticsearch the native port will no longer be usable and you will have to use the REST API

See: https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/client.html)

**Comment by v1r3n** [comment]
@picaron The client used is a transport client, but it should be possible to switch to Http client with minimal changes.

**Comment by picaron** [comment]
ok good to know, thanks @v1r3n 

one more thing, are there any plans to make the ES 5 module the default one instead of the default ES 2 implementation?

**Comment by v1r3n** [comment]
@picaron Yes, we do plan to switch to ES 5. 

 @pctreddy

**Comment by malpani** [comment]
+1 - this issue is closed, is there a way to already use the rest APIs @v1r3n ?
