### ISSUE TITLE
caseExpression in Decision System Task - Example

### ISSUE THREAD

**Issue by NvtcMstr** [Netflix/conductor#459]
I have Issues using the caseExpression of the Decision Task,  can someone provide an Example of how to use it in Combination with the workflow input value?  I want to express something like this: ${workflow.input.value} >10 ? 1 : 0

**Comment by imcyee** [comment]
In case anyone stumbled across this.
```
inputParameters: {'isOkay': '${workflow.input.isOkay}'},
caseExpression: `function scriptFn(){if($.isOkay == false){ return 'not_okay';} else if($.isOkay == true){ return 'okay'; }else{ return 'okay_but_not_okay'}};scriptFn()`,
```
