### ISSUE TITLE
Problem with spaces in the URI

### ISSUE THREAD

**Issue by rabonja** [Netflix/conductor#460]
I was wondering if there is a way around spaces in the URI?  When one of my attribues have a space in them it causes and error of "response": "Illegal character in query at index 211: which is right where the space is located.

**Comment by saidatta** [comment]
AFAIK Syntactically, a URI must not contain a literal space character and it must be encoded; semantically, a `%20` is a proper encoding which is obviously not a space but it represents a space.

**Comment by rabonja** [comment]
Does it not encode already for an http request?  Or is there a way to have it encoded using conductor?

**Comment by ivoribeiro** [comment]
Same problem here
