### ISSUE TITLE
info required

### ISSUE THREAD

**Issue by ajayaks** [Netflix/conductor#48]
Hi,

Would you please suggest some examples or links for below:-

1. Calling remote application or service on other machine. Please suggest whats required on conductor side and whats required for that service on remote machine? 
2. Want to register conductor under eureka server and other micro services.
3. Want to change from jetty server to tomcat.

please suggest.

Regards
Ajay

**Comment by v1r3n** [comment]
Hi Ajay,

1. Conductor provides a task type called HTTP, that can be used to make HTTP calls to remote service and store the results of the remote service.  Take a look at the [kitchensink](https://netflix.github.io/conductor/metadata/kitchensink/) example and look for a task named ```search_elasticsearch```.
2. Check the [eureka](https://github.com/Netflix/eureka) documentation on how to register services.
3. Take a look at the [ConductorServer.java](https://github.com/Netflix/conductor/blob/dev/server/src/main/java/com/netflix/conductor/server/ConductorServer.java) that configures Guice and other dependencies.  You can replace jetty with embedded tomcat or just create a war file that contains all the required dependencies.

**Comment by ajayaks** [comment]
Hi Viren,
Thanks,I have registered conductor in eureka server as an eureka client.

I have another question as below, 
I have created some tasks an workflows but everything got deleted when i restarted server. I want to make them persist so please suggest some steps or documentation for the same.


Regards
Ajay

**Comment by ajayaks** [comment]
Hi,

I have setup dynomite on my local machine and would yo suggest changes i have to do so that tasks, workflow i define should persist in dynomite and available for use later. 

Regards
Ajay

**Comment by v1r3n** [comment]
For the persistence, you want to setup dynomite cluster where the data is persisted.  Check dynomite docs for how to achieve that.
Docker images will be transient and loose data when you restart them.
