### ISSUE TITLE
Python client Worker doesn't support long-poll or taskDomains

### ISSUE THREAD

**Issue by booooh** [Netflix/conductor#480]
As we have a dynamic python entity that would need to occasionally poll for tasks - we wanted to use the python worker client library that is provided in the repo.

It seems that right now, long-polling and task domains are not supported in the provided python client. I opened #477  with a proposed fix that I tested for our usage.

Please let me know if there's anything else you'd like me to do in order to get this upstream.

**Comment by cyzhao** [comment]
Thanks for the PR, we will take a look PR.

**Comment by booooh** [comment]
Closed by #477
