### ISSUE TITLE
Crash when running v1.8.2-rc11 with es5 patch and redis persistence + possible solution

### ISSUE THREAD

**Issue by nop00** [Netflix/conductor#489]
I've been trying to run Conductor `v1.8.2-rc11` with es5 patch and redis persistence these past few days, and the ride was, uh, bumpy :)

I followed the instructions in [es5-persistence's readme](https://github.com/Netflix/conductor/blob/master/es5-persistence/README.md), built (`gradlew build -x test`), configured then started the server, but it crashed with `Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/ResourceAlreadyExistsException`.

Long story short, I ended up pinpointing it on `v1.8.2-rc10`, where dependency locks were introduced.  
The `es5-persistence` and `redis-persistence` projects both depend on elasticsearch, but different versions of it (2.4.6 and 5.6.8, respectively). I suppose that, at runtime, both `es5-persistence` and `redis-persistence` are loaded, so a choice has to be made about which version of elasticsearch to load, and the choice is apparently to load elasticsearch v2.4.6, which does not include the `ResourceAlreadyExistsException` type (it appeared in 5.1.1), hence the crash.

My solution to get things to run was basically to remove any es2-related code. Here's what I did:
* follow the [usual instructions for es5](https://github.com/Netflix/conductor/blob/master/es5-persistence/README.md)
* remove all es2-related code in the `redis-persistence` project, namely:
  * `redis-persistence/EmbeddedElasticSearch.java`
  * `redis-persistence/ElasticSearchDAO.java`
  * `redis-persistence/ElasticsearchModule.java`
  * `redis-persistence/.../main/...dao/index/query/parser/*`
  * `redis-persistence/.../test/...dao/index/query/parser/*`
* remove `compile "org.elasticsearch:elasticsearch:${revElasticSearch5}"` from `redis-persistence/build.gradle`
* add `compile project(':conductor-es5-persistence')` to dependencies in `redis-persistence/build.gradle`
* in `redis-persistence/RedisESWorkflowModule.java`, change:
  * `import com.netflix.conductor.dao.index.ElasticSearchDAO;` to `import com.netflix.conductor.dao.es5.index.ElasticSearchDAO;`
  * `import com.netflix.conductor.dao.index.ElasticSearchModule;` to `import com.netflix.conductor.dao.es5.index.ElasticSearchModule;`
* in `redis-persistence/RedisExecutionDAOTest.java`, change:
  * `import com.netflix.conductor.dao.index.ElasticSearchDAO;` to `import com.netflix.conductor.dao.es5.index.ElasticSearchDAO;`
* remove the reference to es2 in `mysql-persistence/build.gradle` (i.e `compile "org.elasticsearch:elasticsearch:${revElasticSearch2}"`). I'm not sure removing it is required, but the dependency seems unneeded, as I don't see any es2-related code in this project.
* remove `revElasticSearch2` from `versionsOfDependencies.gradle`, as nobody uses it anymore
* I also patched the es versions in the following .lock files by hand, but I guess you could just `./gradlew generateLock saveLock`?
  * `mysql-persistence/dependencies.lock`
  * `redis-persistence/dependencies.lock`
  * `server/dependencies.lock`

To spare you the trouble of doing all of this by hand, [here's a diff](https://gist.github.com/nop00/88ef95b82d2506db89551ddd0b5ddc2e) you can `git apply`.  

I'm not 100% sure everything works, but:
* I ran the tests, and though not every one of them passes, it's not worse than with an unpatched v1.8.2-rc11 (with which some of the tests fail too).  
* I also checked that I could start the kitchensink workflow, but nothing more (I'm not super familiar with using Conductor yet).  

Of course this is hardly a solution: I'm thinking maybe you could extract all the es2 code from `redis-persistence` into an `es2-persistence` project to make switching between es2 and es5 easier? It would still not be perfect, but far better than my ugly patch.  
I guess I could submit a PR, but given my level of familiarity with Java and its ecosystem, I'm afraid it would not be that much of a time save (last time I wrote a Java project was something like 15 years ago). 
 Still, I could write one if you'd like.

**Comment by cyzhao** [comment]
@nop00 thanks for the notes, we will definitely clean this up. Your PR is also welcome.

**Comment by kishorebanala** [comment]
@nop00 We've refactored code to separate es modules from redis in v1.9.X.
