### ISSUE TITLE
ElasticSearch index storage requirements

### ISSUE THREAD

**Issue by picaron** [Netflix/conductor#490]
Hi !

We are currently evaluating the storage requirements for the ElasticSearch index maintained by Conductor.

I have a few questions related to that: 

- Does Conductor eventually cleanup old execution metadata or the index will keep growing forever?
- Is there a way to configure a limit/rotation on the index size via the Conductor config?
- Do you have a rule of thumb to calculate ES storage requirements for Conductor?

Thanks in advance!

**Comment by v1r3n** [comment]
@picaron 
* There is not automated clean up of the indexing.  However, the documents have timestamps (startTime) which can be used to have a job to clean up older entries based on the purge policy.
* Currently, there is no way to configure the limit/rotation for the indices.  
* Storage requirements will really depend on the no. of workflows, avg. payload size and retention policy.  Ideally, someone with the Elasticsearch background will be the best to answer that question given the data points.

**Comment by picaron** [comment]
thanks for the answers @v1r3n !

I've just found that there is a tool from ElasticSearch named [Curator](https://www.elastic.co/guide/en/elasticsearch/client/curator/5.x/index.html) serving exactly that purpose
