### ISSUE TITLE
Need input

### ISSUE THREAD

**Issue by thinkdell01** [Netflix/conductor#500]
Planning to do below. Not sure how to achieve this 
1. Start a task1 -> Webservice call to external service to initial a work "Create a document" 
2. Wait for someone to confirm that "Document is created" ( This is manual) 
3. Mark t1 completed and Read the document. 
4. Create task t2

**Comment by saidatta** [comment]
If it is a 2 task workflow, then register the 2 tasks with conductor.

Then, In the execute logic for the first task, you probably have to poll the external service to retrieve the document status is complete. 

Once you recieve the accurate status, then you mark the task1 complete in the execute method. (you can take a look at the example on how to mark the task as complete.)
