### ISSUE TITLE
"TypeError: Cannot read property &#39;forEach&#39; 

### ISSUE THREAD

**Issue by ajayaks** [Netflix/conductor#51]
Hi,

Getting below error when calling workflow having http task. I have defined below in the input parameter as below.

"inputParameters": {
        "http_request": {
          "uri": "http://localhost:8880/apis/testNames",
          "method": "GET",
          "accept": "application/json;charset=UTF-8"
        }
      }

500 - Internal Server Error
"TypeError: Cannot read property &#39;forEach&#39; of undefined<br> &nbsp; &nbsp;at _callee2$ (/Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/dist/webpack:/src/api/wfe.js:49:5)<br> &nbsp; &nbsp;at tryCatch (/Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/node_modules/regenerator-runtime/runtime.js:64:40)<br> &nbsp; &nbsp;at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/node_modules/regenerator-runtime/runtime.js:355:22)<br> &nbsp; &nbsp;at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/node_modules/regenerator-runtime/runtime.js:116:21)<br> &nbsp; &nbsp;at tryCatch (/Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/node_modules/regenerator-runtime/runtime.js:64:40)<br> &nbsp; &nbsp;at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/node_modules/regenerator-runtime/runtime.js:297:24)<br> &nbsp; &nbsp;at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/node_modules/regenerator-runtime/runtime.js:116:21)<br> &nbsp; &nbsp;at step (/Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/dist/server.js:8603:192)<br> &nbsp; &nbsp;at /Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/dist/server.js:8603:362<br> &nbsp; &nbsp;at run (/Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/node_modules/core-js/modules/es6.promise.js:87:22)\n"

Please suggest

**Comment by ajayaks** [comment]
Dont know the purpose but i have fixed the issue locally and its working.
Please let me know if its a valid issue.

For me it was showing "schemaVersion": 0, and as per logic it was using getTaskInputV1(...).
I have used getTaskInputV2() and its working after that.

**Comment by v1r3n** [comment]
Closing for now - we will add a validation to ensure the schemaVersion is set to a valid value.
