### ISSUE TITLE
TaskKey error

### ISSUE THREAD

**Issue by juaby** [Netflix/conductor#511]
version : 1.8.8
os : centos 7
db : mysql
index : es
1, reg tasks
2, reg workflow
3, start workflow and save workflowId
4, schedule workflow means : after workflow COMPLETED, restart workflow
5, worker client not exe task and workflow status = RUNNING and log tips:
com.netflix.conductor.dao.mysql.MySQLExecutionDAO  - Task already scheduled, skipping the run e3db0c00-71b0-4827-8251-314998d7a518, ref=OPEN, key=OPEN_0

but db = mem is ok

here:

String EXISTS_SCHEDULED_TASK = "SELECT EXISTS(SELECT 1 FROM task_scheduled WHERE workflow_id = :workflowId AND task_key = :taskKey)";
		boolean exist = connection.createQuery(EXISTS_SCHEDULED_TASK)
				.addParameter("workflowId", task.getWorkflowInstanceId())
				.addParameter("taskKey", taskKey)
				.executeScalar(Boolean.class);

this is sql : SELECT EXISTS(SELECT 1 FROM task_scheduled WHERE workflow_id = :workflowId AND task_key = :taskKey)

reason :  :smiley: 
rewind workflow gen taskKey = defName + "" + retryCount
removeScheduledTask with taskKey = defName + "_" + retryCount

suggestion : :smiley: 
tasKey = function(task) {
     return task.defName + SPLIT_TAG + task.retryCount;
}

**Comment by apanicker-nflx** [comment]
@juaby Please upgrade to the newest version (2.7.+). This issue should be resolved in the newer versions.
Please reopen if you still see this issue.
