### ISSUE TITLE
JSONPath boolean expression evaulation.

### ISSUE THREAD

**Issue by jagadeeshb22** [Netflix/conductor#515]
@v1r3n ,
Do we have a solution for the decision case's caseValueParam expression which gives true/false exactly.

Can you please provide an example for that?

I tried the below example to know the return value true or false so that, I can make true or false decision cases accordingly.
![image](https://user-images.githubusercontent.com/38783638/39358209-03770172-4a33-11e8-9246-43ea0c6d43f2.png)

The given value “1000” is not presented in the first task’s output array. 
After executing the above workflow the case output gives empty array - [ ].
Is there any expression to get true/false?
It would be a great help.

Thanks..!

**Comment by SoerenKn** [comment]
You can use a caseExpression with a javascript instead of the caseValueParam. Should look somehow like this:             

           {
		  "name": "status?",
                  "taskReferenceName": "status",
                  "inputParameters": {
                    "id": "${task1.output.id}"
                  },
                  "type": "DECISION",
                  "caseExpression": "if ($.id == 1000) '1'; else '0';",
                  "decisionCases": {
                    "0": [  ....

**Comment by jagadeeshb22** [comment]
@SoerenKn ,
Thanks..!. It really works for me.

At the same time, when I try to loop through the first tasks output array with the caseExpression, getting the issues.
Below is the first task's output array.
![image](https://user-images.githubusercontent.com/38783638/39418103-f7b2525c-4c75-11e8-897d-dedfe041c8a0.png)

The workflow definition's decision case is as follows:
![image](https://user-images.githubusercontent.com/38783638/39418159-5914dbfa-4c76-11e8-80e7-f01afd124f5e.png)

Can you please suggest me to resolve this?
Many thanks..!

**Comment by jagadeeshb22** [comment]
I achieved the above problem with the below caseExpression.

![image](https://user-images.githubusercontent.com/38783638/39424757-c8951034-4c95-11e8-9401-bbde6ee06cb4.png)

Thanks again @SoerenKn
