### ISSUE TITLE
The worker task needs to be auto-triggered and auto-completed

### ISSUE THREAD

**Issue by hrishikeshnerurkar** [Netflix/conductor#516]
I have a simple workflow starting with event task --> decision task --> (Valid -> invoke http task) / (Invalid -> Invoke a simple worker task) --> finish

In Valid workflow, the workflow completes without any human intervention. But in Invalid workflow, the worker task remains in SCHEDULED state and needs to be polled and marked as COMPLETED with /tasks/ API calls (human intervention).

Is there a way to get the worker task completed without making API calls?

label:"help wanted"

**Comment by apanicker-nflx** [comment]
Please follow the documentation [here](https://netflix.github.io/conductor/gettingstarted/client/#worker) to learn more about using the Worker and the WorkflowTaskCoordinator which provides a framework and automates the polling and managing the execution thread for a task within a worker.
