### ISSUE TITLE
Example of update of task status by remote agents (task executors)

### ISSUE THREAD

**Issue by virursingh** [Netflix/conductor#53]
Hi,

I am looking for examples of how the task status is updated by remote executors.
I tried the task management APIs (POST on /api/tasks) but it did not work.
Some examples in the Doc would be useful to the users.

Thanks,

-Viru.

**Comment by v1r3n** [comment]
Here is a sample JSON:

```json
{
  "workflowInstanceId": "workflow_instance_id",
  "taskId": "task_id",
  "callbackAfterSeconds": 0,
  "workerId": "cpeworkflowtests-perf-i-0202ee6a4e666246b",
  "reasonForIncompletion": "reason why task failed",
  "outputData": {},
  "taskStatus": "COMPLETED"
}
```

**Comment by virursingh** [comment]
Hi,

Appreciate the response.
I tried it already but the task status did not get changed (from
IN_PROGRESS to COMPLETED).

The .../api/task/'task-id' output does not change.

What is the role of "workerId" parameter here? Does it need to be present
in the system?

Thanks,

-Viru.

**Comment by virursingh** [comment]
let me add some details as well to make sure if I am using the right APIs.

Here are the task details:

bash-3.2$ curl -X GET --header 'Accept: application/json' '
http://localhost:8080/api/tasks/0656166e-8f88-4e51-8d9b-0e4a31228be3'
{"workflowInstanceId":"555a7bb3-4198-4a93-9cb1-19e13a5b4b54","taskId":"0656166e-8f88-4e51-8d9b-0e4a31228be3","callbackAfterSeconds":0,"status":"IN_PROGRESS","taskType":"echoTask","inputData":{"istr":"Howdy"},"referenceTaskName":"echoTask","retryCount":0,"seq":1,"pollCount":2,"taskDefName":"echoTask","scheduledTime":1485775328957,"startTime":1485775548114,"endTime":0,"updateTime":1485776459978,"startDelayInSeconds":0,"retried":false,"callbackFromWorker":true,"responseTimeoutSeconds":3600,"queueWaitTime":219157,"taskStatus":"IN_PROGRESS"}

Task update command :
curl -X POST --header 'Content-Type: application/json' --header 'Accept:
text/plain' -d @taskinfo http://localhost:8080/api/tasks
taskinfo:
{
  "workflowInstanceId": "555a7bb3-4198-4a93-9cb1-19e13a5b4b54",
  "taskId": "0656166e-8f88-4e51-8d9b-0e4a31228be3",
  "callbackAfterSeconds": 0,
  "reasonForIncompletion": "no reason",
  "workerId": "test-worker-0202ee6a4e666246b",
  "outputData": {},
  "taskStatus": "COMPLETED"
}

Post execution of the above command I an getting the same result on the
task info. I don't see the status as completed.

I don't see any errors either.

Thanks!

**Comment by v1r3n** [comment]
Use the following JSON (note the change from taskStatus to status in the field).  

```json
{
  "workflowInstanceId": "workflow_instance_id",
  "taskId": "task_id",
  "callbackAfterSeconds": 0,
  "reasonForIncompletion": "reason why task failed",
  "outputData": {},
  "status": "COMPLETED"
}
```

**Comment by virursingh** [comment]
Hi Viren,

Appreciate the response. I realized the problem was 'Accept: text/plain' in
the curl call.
After I replaced it with 'Accept: application/json' it worked fine.
Unfortunately the call
was failing silently (scope for error message here).

Thanks,

-Viru.
