### ISSUE TITLE
HELP : How to remove duplicating  HTTP tasks from given workflow ? 

### ISSUE THREAD

**Issue by kchaturanga** [Netflix/conductor#534]
I have a workflow with two DECISION tasks, and to get the workflow working I had to make the same task "applicationinstance_preconfirm_paymentauth" and "applicationinstance_preconfirm_datasave" more than once , 

This workflow is working as I expected , And my question is , is there any possibility to write the same workflow with same logic *WITHOUT* duplicating  HTTP tasks ? 

I
Please find the workflow 

 {
  "createTime": 1525927431675,
  "name": "applicationinstance_rez_pre_confirmation",
  "description": "applicationinstance_rez_preconfirm_confirmation workflow",
  "version": 9,
  "tasks": [
    {
      "name": "applicationinstance_preconfirm_datainit",
      "taskReferenceName": "applicationinstance_preconfirm_datainit",
      "inputParameters": {
        "http_request": {
          "uri": "${workflow.input.urls.initializer.initpreconfirm}",
          "method": "POST",
          "body": "${workflow.input}"
        }
      },
      "type": "HTTP",
      "startDelay": 0
    },
    {
      "name": "applicationinstance_productvalidate_fork",
      "taskReferenceName": "applicationinstance_productvalidate_fork",
      "inputParameters": {
        "dynamicTasks": "${applicationinstance_preconfirm_datainit.output.response.body.productvalidate.tasklist}",
        "dynamicTasksInput": "${applicationinstance_preconfirm_datainit.output.response.body.productvalidate.inputlist}"
      },
      "type": "FORK_JOIN_DYNAMIC",
      "dynamicForkTasksParam": "dynamicTasks",
      "dynamicForkTasksInputParamName": "dynamicTasksInput",
      "startDelay": 0
    },
    {
      "name": "applicationinstance_productvalidate_join",
      "taskReferenceName": "applicationinstance_productvalidate_join",
      "type": "JOIN",
      "startDelay": 0
    },
    {
      "name": "applicationinstance_productvalidate_update",
      "taskReferenceName": "applicationinstance_productvalidate_update",
      "inputParameters": {
        "http_request": {
          "uri": "${workflow.input.urls.preconfirm.updateValidationStatus}",
          "method": "POST",
          "body": {
            "wfin": "${workflow.input}",
            "forkout": "${applicationinstance_productvalidate_join.output}"
          }
        }
      },
      "type": "HTTP",
      "startDelay": 0
    },
    {
      "name": "applicationinstance_preconfirm_validation_success_switch",
      "taskReferenceName": "applicationinstance_preconfirm_validation_success_switch",
      "inputParameters": {
        "case_value_param": "${applicationinstance_productvalidate_update.output.response.body.productvalidationsuccess}"
      },
      "type": "DECISION",
      "caseValueParam": "case_value_param",
      "decisionCases": {
        "Y": [
          {
            "name": "applicationinstance_preconfirm_flight_switch",
            "taskReferenceName": "applicationinstance_preconfirm_flight_switch",
            "inputParameters": {
              "case_value_param": "${applicationinstance_productvalidate_update.output.response.body.continueforflight}"
            },
            "type": "DECISION",
            "caseValueParam": "case_value_param",
            "decisionCases": {
              "Y": [
                {
                  "name": "applicationinstance_preconfirm_flightconfirm",
                  "taskReferenceName": "applicationinstance_preconfirm_flightconfirm",
                  "inputParameters": {
                    "http_request": {
                      "uri": "${workflow.input.urls.preconfirm.flightconfirm}",
                      "method": "POST",
                      "body": {
                        "initout": "${applicationinstance_preconfirm_datainit.output.response.body}",
                        "workflowin": "${workflow.input}"
                      }
                    }
                  },
                  "type": "HTTP",
                  "startDelay": 0
                },
                {
                  "name": "applicationinstance_preconfirm_updateflightinfo",
                  "taskReferenceName": "applicationinstance_preconfirm_updateflightinfo",
                  "inputParameters": {
                    "http_request": {
                      "uri": "${workflow.input.urls.preconfirm.flightupdate}",
                      "method": "POST",
                      "body": {
                        "workflowin": "${workflow.input}",
                        "flightout": "${applicationinstance_preconfirm_flightconfirm.output.response.body}"
                      }
                    }
                  },
                  "type": "HTTP",
                  "startDelay": 0
                },
                {
                  "name": "applicationinstance_preconfirm_paymentauth",
                  "taskReferenceName": "applicationinstance_preconfirm_paymentauth",
                  "inputParameters": {
                    "http_request": {
                      "uri": "${workflow.input.urls.preconfirm.paymentinit}",
                      "method": "POST",
                      "body": {
                        "paymentRequest": "${applicationinstance_preconfirm_datainit.output.response.body.paymentRequest}",
                        "initout": "${applicationinstance_preconfirm_datainit.output.response.body}",
                        "workflowInput": "${workflow.input}"
                      }
                    }
                  },
                  "type": "HTTP",
                  "startDelay": 0
                },
                {
                  "name": "applicationinstance_preconfirm_datasave",
                  "taskReferenceName": "applicationinstance_preconfirm_datasave",
                  "inputParameters": {
                    "http_request": {
                      "uri": "${workflow.input.urls.datasaver.saveDraft}",
                      "method": "POST",
                      "body": {
                        "initout": "${applicationinstance_preconfirm_datainit.output.response.body}",
                        "workflowin": "${workflow.input}",
                        "flightupdateout": "${applicationinstance_preconfirm_updateflightinfo.output.response.body}",
                        "paymentout": "${applicationinstance_preconfirm_paymentauth.output.response.body}"
                      }
                    }
                  },
                  "type": "HTTP",
                  "startDelay": 0
                }
              ],
              "N": [
                {
                  "name": "applicationinstance_preconfirm_paymentauth",
                  "taskReferenceName": "applicationinstance_preconfirm_paymentauth",
                  "inputParameters": {
                    "http_request": {
                      "uri": "${workflow.input.urls.preconfirm.paymentinit}",
                      "method": "POST",
                      "body": {
                        "paymentRequest": "${applicationinstance_preconfirm_datainit.output.response.body.paymentRequest}",
                        "initout": "${applicationinstance_preconfirm_datainit.output.response.body}",
                        "workflowInput": "${workflow.input}"
                      }
                    }
                  },
                  "type": "HTTP",
                  "startDelay": 0
                },
                {
                  "name": "applicationinstance_preconfirm_datasave",
                  "taskReferenceName": "applicationinstance_preconfirm_datasave",
                  "inputParameters": {
                    "http_request": {
                      "uri": "${workflow.input.urls.datasaver.saveDraft}",
                      "method": "POST",
                      "body": {
                        "initout": "${applicationinstance_preconfirm_datainit.output.response.body}",
                        "workflowin": "${workflow.input}",
                        "flightupdateout": "${applicationinstance_preconfirm_updateflightinfo.output.response.body}",
                        "paymentout": "${applicationinstance_preconfirm_paymentauth.output.response.body}"
                      }
                    }
                  },
                  "type": "HTTP",
                  "startDelay": 0
                }
              ]
            },
            "startDelay": 0
          }
        ],
        "N": [
          {
            "name": "applicationinstance_preconfirm_datasave",
            "taskReferenceName": "applicationinstance_preconfirm_datasave",
            "inputParameters": {
              "http_request": {
                "uri": "${workflow.input.urls.datasaver.saveDraft}",
                "method": "POST",
                "body": {
                  "initout": "${applicationinstance_preconfirm_datainit.output.response.body}",
                  "workflowin": "${workflow.input}",
                  "flightupdateout": "${applicationinstance_preconfirm_updateflightinfo.output.response.body}",
                  "paymentout": "${applicationinstance_preconfirm_paymentauth.output.response.body}"
                }
              }
            },
            "type": "HTTP",
            "startDelay": 0
          }
        ]
      },
      "startDelay": 0
    },
    {
      "name": "applicationinstance_preconfirm_finalize",
      "taskReferenceName": "applicationinstance_preconfirm_finalize",
      "inputParameters": {
        "http_request": {
          "uri": "${workflow.input.urls.preconfirm.finalize}",
          "method": "POST",
          "body": {
            "savedorder": "${applicationinstance_preconfirm_datasave.output.response.body.order}",
            "workflowin": "${workflow.input}"
          }
        }
      },
      "type": "HTTP",
      "startDelay": 0
    }
  ],
  "outputParameters": {
    "statues": "${applicationinstance_preconfirm_datasave.output}"
  },
  "schemaVersion": 2
}
 
![aaaaaaaa](https://user-images.githubusercontent.com/2740501/39852921-f8e1aeb0-543c-11e8-9ca9-71bdd2b58969.png)

**Comment by apanicker-nflx** [comment]
If the order in which these 2 tasks are executed are always the same, you can consider moving them into a SUB_WORKFLOW. Please follow the documentation [here](https://netflix.github.io/conductor/configuration/systask/#sub-workflow)
