### ISSUE TITLE
UI: Filter by workflow status returns no results

### ISSUE THREAD

**Issue by ms1111** [Netflix/conductor#538]
On the master branch (v1.9.1), after bringing up the components in Docker:

```
./gradlew build
cd docker
docker-compose up
```

"Executions -> All" shows one RUNNING workflow:

![image](https://user-images.githubusercontent.com/17057295/39963255-b51550b6-5634-11e8-8101-11a12fa6289d.png)

But if I filter by status RUNNING, or go to "Executions -> Running", I get no results.

![image](https://user-images.githubusercontent.com/17057295/39963259-ca302106-5634-11e8-9d95-a251f59bf934.png)

(The same is true after [launching another instance of the workflow](https://netflix.github.io/conductor/metadata/kitchensink/#start-workflow-execution) - two workflows show up in RUNNING state under "Executions -> All", but none under "Executions -> Running".)

The free text query and filter by workflow type appear to be working. For example, I can search on the workflow ID and it shows up:

![image](https://user-images.githubusercontent.com/17057295/39963283-41d4214e-5635-11e8-9054-688f5381c35d.png)

The workflow type filter also works:

![image](https://user-images.githubusercontent.com/17057295/39963285-52bdfaf2-5635-11e8-838a-7dbb6631c404.png)

**Comment by apanicker-nflx** [comment]
Please upgrade to the newest versions (2.7.+). 
Please reopen if you still see the issue.
