### ISSUE TITLE
UI: Display workflow status under Executions

### ISSUE THREAD

**Issue by ms1111** [Netflix/conductor#540]
In my current, pre-Conductor life, I have users asking me where their jobs are and how many are in the queue for long tasks.

It would be nice to be able to point them at Conductor to see the latest status for each execution. I'm thinking of this table:

![image](https://user-images.githubusercontent.com/17057295/39963369-5e9b1448-5637-11e8-9333-0625e76b6db3.png)

It would be useful to have a column showing the currently SCHEDULED and IN_PROGRESS tasks. One idea would be to cram it into a single column, separating the workflow steps by commas, and identifying the ones that are SCHEDULED but not IN_PROGRESS. For example, in the kitchensink workflow you could have `task_1_1, wf_dyn (SCHEDULED)` if `task_1_1` is `IN_PROGRESS` and `wf_dyn` is `SCHEDULED`.

**Comment by saidatta** [comment]
+1, More visibility on how many tasks are left to complete would be helpful

**Comment by tarunbheemajava** [comment]
I need to make the attached task dynamic and event driven.  But when I tried to make task dynamic it is failing . 
Definition of my workflow
{
  "name": "testTwodynamic",
  "description": "Dynamic workflow",
  "version": 1,
    "tasks": [
      {
        "name": "task_a",
        "taskReferenceName": "task_a",
        "inputParameters": {
          "firstname": "${workflow.input.firstname}"
     
        },
        "type": "DYNAMIC",
     "dynamicTaskNameParam": "taskToExecute"
      },
      {
        "name": "task_b",
        "taskReferenceName": "task_b",
        "inputParameters": {
          "lastname": "${workflow.input.lastname}"
        },
        "type": "SIMPLE",
        "startDelay": 0
      }
    ],
    "outputParameters": {
    "outputvalue": "${task_a.input.firstname}${task_b.input.lastname}"
  },
    "schemaVersion": 2
  
}

![image](https://user-images.githubusercontent.com/20147720/44113017-5b2826aa-9fcc-11e8-995f-6435f1ddb490.png)

[Workflow Cretion Netflix.docx](https://github.com/Netflix/conductor/files/2288181/Workflow.Cretion.Netflix.docx)

**Comment by tarunbheemajava** [comment]
I want to make my task dynamic and event driven for simple tasks i.e., task_a and task_b part by part to understand so that I want to implement kitchensink .
