### ISSUE TITLE
Race condition when running multiple instances of conductor server

### ISSUE THREAD

**Issue by akashbhunchal** [Netflix/conductor#543]
Hi,

I have a common redis (single instance) and a common ES for conductor. I am running conductor server behind a load balancer. When I run m ore than one servers , multiple workers pick up the same job at the same time (duplicate execution starts).

Is there something I need to do to avoid this. This is stopping me from running an HA conductor instance.

I see that 
`public synchronized List<Message> pop(int messageCount, int wait, TimeUnit unit)
`
in RedisQueue.java. This (synchronization) would not work across multiple JVMs.

**Comment by mudit3774** [comment]
@akashbhunchal : Thanks for raising this. Were you able to do a work around for this ?

**Comment by akashbhunchal** [comment]
Nope, We just removed one box from the loadbalancer. We now have just one instance running.

**Comment by jkaipa** [comment]
Any new development towards a solution for the issue in question?

**Comment by apanicker-nflx** [comment]
Please use the [WorkflowTaskCoordinator](https://netflix.github.io/conductor/gettingstarted/client/#workflowtaskcoordinator) which provides a framework and automates the polling of tasks and managing the execution threads of tasks within workers. The WorkflowTaskCoordinator ensures that when multiple workers are polling for the same task, only one worker will actually process a given task. This is ensured using the [ack mechanism](https://github.com/Netflix/conductor/blob/master/client/src/main/java/com/netflix/conductor/client/task/WorkflowTaskCoordinator.java#L357-L369). Only if the `ack` is successful will the worker actually be given the task to execute.
