### ISSUE TITLE
[Question] Tasks was in the queue so long before being polled for processing

### ISSUE THREAD

**Issue by loisoft** [Netflix/conductor#553]
It is hard-code to wait 200 milliseconds for popping the tasks in queue.
Class: com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator
Method: private void pollAndExecute(WorkflowSystemTask systemTask)

```
int realPollCount = Math.min(workerQueue.remainingCapacity(), pollCount);
if (realPollCount <= 0) {				
       logger.warn("All workers are busy, not polling.  queue size {}, max {}", workerQueue.size(), workerQueueSize);
       return;
}

String name = systemTask.getName();
List<String> polled = taskQueues.pop(name, realPollCount, 200);
```
In case of realPollCount > number of messages in the queue, it always waits until timeout

**Comment by loisoft** [comment]
@v1r3n could you please help?

**Comment by cyzhao** [comment]
@loisoft is 200 milliseconds a long wait for you? what would you suggest?

**Comment by v1r3n** [comment]
200 is the max time it will wait if there are no items in the queue.  If there are items in the queue ready to be polled, it does not wait for 200ms.

**Comment by loisoft** [comment]
@v1r3n @cyzhao:

As I know, we can prevent this timeout by adjusting the configuration: 

> workflow.system.task.worker.poll.count

However, in some cases, I would enhance overall workflow performance. So 

Could this timeout number be configurable?

Thanks,

**Comment by apanicker-nflx** [comment]
@loisoft You could convert this value to a property that is read when the server starts up thus making it configurable.
