### ISSUE TITLE
Is it possible to refer one task in other  task

### ISSUE THREAD

**Issue by veveeranishwar** [Netflix/conductor#565]
like in java we call one method in other method, is it possible to do same in workflow for tasks

**Comment by v1r3n** [comment]
@veveeranishwar can you provide an example?  You can refer to the task's input or output parameters, not sure what you mean by reffering the tasks.

**Comment by veveeranishwar** [comment]
For an example i have 2 task 
{
 "name": "task1",
"taskReferenceName": "task1",
// this task has decision and sub workflow as well
}

on certain condition I need to execute the same logic which task1 is having  in another task say task 2. I don't want to repeat the same logic in task2 also, instead can I point task2 to execute task1 , is it possible.

 here is my task2
{
"name": "task2",
"taskReferenceName": "task2",

//here I have to execute same logic which is in task1, is it possible to execute task1 here  or do I have to repeat same logic which task1 having
}

**Comment by v1r3n** [comment]
@veveeranishwar tasks are implemented and executed by workers which is external to Conductor server.  You should be able to organize the code such that both task1 and task2 either shares the same implementation or has other techniques such as common helpers or inheritance used to avoid duplication of logic.

**Comment by veveeranishwar** [comment]
how to do  inheritance  in workflows , can you help me on this

**Comment by apanicker-nflx** [comment]
@veveeranishwar Please follow the documentation [here](https://netflix.github.io/conductor/configuration/workflowdef/#wiring-inputs-and-outputs) to learn about wiring tasks together in your workflow.
