### ISSUE TITLE
how to get response of task executed under decisionCases

### ISSUE THREAD

**Issue by veveeranishwar** [Netflix/conductor#566]
I have  decision case , under which  I am having 3 task. How to get response of executed task .

{
taskname: "n1",
decisionCases :  {
0: { 
     taskname: "t1",
    }
1:  {
       taskname: "t2",
   }
}
{
taskname: "test",
//how to get response of above executed decision case.  we can get using specific name of the task like 
//t2.output.response, but during runtime I will not be knowing which case is executed.
}

Please can some one help on this.

**Comment by jagadeeshb22** [comment]
@v1r3n ,
Can you please let us know the solution for this?
Thanks..!

**Comment by ivoribeiro** [comment]
+1

**Comment by kishorebanala** [comment]
Please check this new Exclusive Join task to achieve this: https://netflix.github.io/conductor/configuration/systask/#exclusive-join
