### ISSUE TITLE
how to query workflows with multiple workflowId?

### ISSUE THREAD

**Issue by woosterdad** [Netflix/conductor#567]
how to query workflows with multiple workflowId?
I mean like SQL where clause:
workflowId IN ("c571690b-c451-493e-a91c-196957e16a1a",  "3593490c-1246-40a9-a233-88fb651d8d68")

**Comment by v1r3n** [comment]
You can query using the SQL where clause you specified above on the search endpoint.

**Comment by woosterdad** [comment]
Thanks, when I do this, it responses 'Unknown Version', did I do something wrong?
('localhost', 30608, 'GET', '/api/workflow/search?query=workflowId IN ("c571690b-c451-493e-a91c-196957e16a1a", "3593490c-1246-40a9-a233-88fb651d8d68")')
('response:', 400, 'Unknown Version', 11, '')
('content-length', '0')
('connection', 'close')
('server', 'Jetty(9.3.z-SNAPSHOT)')

**Comment by apanicker-nflx** [comment]
Closing this issue since its been inactive for a while. Please reopen if you still run into this with the latest version.
