### ISSUE TITLE
How to read javascript variable value in workflow?

### ISSUE THREAD

**Issue by GeethaIbm** [Netflix/conductor#571]
var myJSONString = JSON.stringify(createList);
for example if i want to access the myJSONString value in workflow how can i access that ?

**Comment by saidatta** [comment]
Use the JSONPath funcionality. While registering, define the input parameters for the WF / Task. Then, read it based on that.

**Comment by apanicker-nflx** [comment]
@saidatta Thanks for the response. Please follow the documentation [here](https://netflix.github.io/conductor/configuration/workflowdef/#wiring-inputs-and-outputs) to learn more about this.
