### ISSUE TITLE
An example for WAIT task

### ISSUE THREAD

**Issue by srshanmug** [Netflix/conductor#58]
Hi, I am currently working on some prototypes using conductor orchestrating workflow. The prototype workflow has a http task to download an image and the next task's input param need to be the downloaded image. Since download takes time, I am planning to use WAIT. Could you provide an example WAIT task? Kitchensink example does not have a reference  to WAIT task.
Another option I am trying to use is - Fork and Join. Fork on one task and join on the task. Fork example has a sub workflow within it. Is subworkflow necessary for a Fork task?

Thank you,
Sri

**Comment by v1r3n** [comment]
WAIT task can be added by creating a task with taskType as WAIT.  WAIT task acts as a gate and does not move forward until mark completed either by posting a message to SQS or manually invoking REST endpoint.

https://netflix.github.io/conductor/metadata/systask/#wait

Subworkflow is not necessary for the fork task.  Fork can create any task of tasks.

**Comment by v1r3n** [comment]
Closing the issue.  Please re-open/create if you need further help.
