### ISSUE TITLE
domain task not activated

### ISSUE THREAD

**Issue by liulwx** [Netflix/conductor#580]
Dear all:
       Since I have created a  workflow instance which set the domain. However, when my task worker not working. After some time, I start that task worker, and the task cannot be polled. On the other hand, If I keep that task worker working, I can poll that task. 
     Where can I set the time when the task be pushed into the default queue?

**Comment by jvemugunta** [comment]
Hi, 
I was able to replicate the problem. I have opened the issue. I am researching on what is the right place to fix the bug. I struggled for a week now to understand the issue

https://github.com/Netflix/conductor/issues/614

**Comment by liulwx** [comment]
Hello:
I have already solved the problem. The domain queue is selected here. https://github.com/Netflix/conductor/blob/39a851fcf7cfe807f6288a39f08c455eb165ce11/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L790
If we don't set it manually, the default time is 10. It means that if the last poll time is bigger than 10s, the workerflow won't be pushed to that domain queue. Instead, It is pushed into the default queue. I set the last_poll time to the extremely large value. And the problem was solved.

**Comment by jvemugunta** [comment]
It seems to be not working for me.
I have set the value to 365 days as below

**tasks.active.worker.lastpoll=31536000**

The worker is not pulling the task

**Comment by jvemugunta** [comment]
Please do this and let me know your results
1) Start the workflow
2) and start your worker client (This should be the second step so that polling for tasks happens after you start the workflow)
3) Your worker should not receive any data

**My worker code**

import com.netflix.conductor.client.http.TaskClient;
import com.netflix.conductor.client.task.WorkflowTaskCoordinator;
import com.netflix.conductor.client.worker.Worker;

```
public class DomainClient {

    public static void main(String[] args) {

       System.setProperty("conductor.worker.T1.domain", "mydomain");
       
        TaskClient taskClient = new TaskClient();
        taskClient.setRootURI("http://localhost:8080/api/");

        int threadCount = 4;
        Worker worker1 = new DomainWorker("T1");
        Worker worker2 = new DomainWorker("T1");
        Worker worker3 = new DomainWorker("T1");
      
        WorkflowTaskCoordinator.Builder builder = new WorkflowTaskCoordinator.Builder();
        WorkflowTaskCoordinator coordinator = builder.withWorkers(worker1,worker2,worker3).withThreadCount(threadCount)
                .withTaskClient(taskClient).build();

        // Start for polling and execution of the tasks
        coordinator.init();

    }
```
**Workflow Curl commands**

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' 'http://localhost:8080/api/metadata/taskdefs' -d '
[{
  "name": "T1",
  "retryCount": 3,
  "timeoutSeconds": 1200,
  "inputKeys": [
    "sourceRequestId",
    "qcElementType"
  ],
  "outputKeys": [
    "state",
    "skipped",
    "result"
  ],
  "timeoutPolicy": "TIME_OUT_WF",
  "retryLogic": "FIXED",
  "retryDelaySeconds": 600,
  "responseTimeoutSeconds": 3600
}]
'

curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' 'http://localhost:8080/api/metadata/workflow' -d '
[{
  "name": "sample",
  "description": "sample workflow",
  "version": 1,
  "tasks": [
    {
      "name": "T1",
      "taskReferenceName": "T1",
      "type": "SIMPLE",
      "inputParameters": {
        "fileName": "${workflow.input.fileName}"
      }
    }
  ],
  "outputParameters": {
   
  },
  "schemaVersion": 2
}]
'


curl -i -X POST --header 'Content-Type: application/json' --header 'Accept: text/plain' 'http://localhost:8080/api/workflow' -d '
{
  "name": "sample",
  "version": 1,
  "correlatonId": "corr1",
  "input": {
    "fileName": "f1"
  },
  "taskToDomain": {
    "T1": "mydomain"
  }
}
'
```

**Comment by liulwx** [comment]
There are two configure file. Have you noticed which configure file is used?

**Comment by jvemugunta** [comment]
@liulwx I didn't under your question. Can you please elaborate?

**Comment by liulwx** [comment]
@jvemugunta 
At first, I have already found the solution to my question!!!!
My question is that I want to use the task domain, but it doesn't work normally. If I keep polling the task using domain X. I can successfully push the task to the domain X. However, If I don't polling, the task cannot be pushed to that domain X, it will be pushed into the default  queue. And I cannot pulled the task from domain X. 

The reason is that the tasks.active.worker.lastpoll is not set in my configure file and it use the default value 10. After I set the  tasks.active.worker.lastpoll, the problem is solved.
By the way, you should notice which configuration file is used. The configuration file will be shown at the time you start the server. I don't know the way you start the server. I used docker_compose. 
https://github.com/Netflix/conductor/blob/f59175395055001723a4d271a3090e801bd071ac/docker/server/bin/startup.sh#L12

**Comment by jvemugunta** [comment]
@liulwx I completely understand the behavior. I think the behavior is misleading and to me looks wrong. If I start the workFlow with taskToDomain as 

```
"taskToDomain": {
    "T1": "mydomain"
  }
```
The queue should not be  default queue. It should be mydomain:T1 and should not be dependent on how the worker polls the tasks

I am not using docker and I am starring the conductor server as 
java -jar conductor-server-1.10.0-SNAPSHOT-all.jar ~/git_repos/server.properties

**Comment by kishorebanala** [comment]
This must have been resolved in https://github.com/Netflix/conductor/pull/864

Please open another issue if you still have concerns.
