### ISSUE TITLE
Conductor code quality with SonarQube scan

### ISSUE THREAD

**Issue by jagadeeshb22** [Netflix/conductor#589]
Hi @v1r3n ,

Are you using any code scan tools to scan the conductor code?
I see that when we scan the conductor code with SonarQube, there are some issues found in the code.

Below are the some issues from SonarQube scan in ConductorServer class.

![image](https://user-images.githubusercontent.com/38783638/41220762-0013ed5e-6d80-11e8-9c16-058a8bdf643f.png)
-------------------------------------------------

![image](https://user-images.githubusercontent.com/38783638/41220795-16a6debe-6d80-11e8-938c-00ee428df932.png)
-------------------------------------------------

![image](https://user-images.githubusercontent.com/38783638/41220893-53512414-6d80-11e8-8a13-266089259ce7.png)
--------------------------------------------------

![image](https://user-images.githubusercontent.com/38783638/41221049-b3ad75a6-6d80-11e8-9333-27f2c9e38441.png)

Can we ignore these? Or are you using any other tools to scan the code. 
Please let us know.
Thanks..!

**Comment by apanicker-nflx** [comment]
@jagadeeshb22 Thanks for the feedback. We plan to integrate with static code analysis tools like SonarQube soon and fix issues as necessary wrt impact and priority. Please feel free to submit a PR with any fixes that you consider as important and we will be happy to review and merge.
