### ISSUE TITLE
Is there a graphical workflow editor?

### ISSUE THREAD

**Issue by rbeers** [Netflix/conductor#599]
We are considering using Conductor for our project and wondered if there is a graphical editor to produce workflows in Conductor json format?  If not, is the best option to roll our own or are there any plans for a future editor?

**Comment by saidatta** [comment]
From my research, I did not find any graphical editor for workflow edits. You might have already came across the python and java client libraries that are used to handle those operations.

**Comment by cyzhao** [comment]
@rbeers current there is no workflow editor, there is a plan to create one but not in the near term.
