### ISSUE TITLE
Is there auto scaling for Conductor servers and its related components?

### ISSUE THREAD

**Issue by saidatta** [Netflix/conductor#601]
What tools do you guys use to scale up conductor servers / dynomite / elastic search?

Currently, I manually have to look through spectator metrics and other aws metrics to predict server is getting overrwhelmed and need to manually scale it up. Is there any other simplified strategy?

**Comment by saidatta** [comment]
After researching for a bit, suggestions I have found would be to use ElasticCache+Redis or dynomite-manager+Eureka?

I am not entirely certain on the latter suggestion.

**Comment by clari-akhilesh** [comment]
@saidatta , how did you manage to configure spectator for metrics? we're currently using the prebuilt conductor jars for deploying the server. any insight would be extremely helpful. thanks in advance.

**Comment by jwulf** [comment]
Take a look at https://github.com/Netflix/conductor/issues/600
