### ISSUE TITLE
For Request to be Authenticated ,It need to be supplied with Authorization header

### ISSUE THREAD

**Issue by Nitishsri85** [Netflix/conductor#602]
I have a servlet which is making a rest call to the conductor APIs and successfully creating the Workflows and Tasks but the response is returning as text/html and not the plain/text or JSON. Since, this call is made from outside, Can someone tell me does this call require any special headers to be set like Authorization header api key header? If yes, then what would be its value?

Please let me know how I get the same

**Comment by jvemugunta** [comment]
what is your accepted behavior? Probably the client is not sending the **Accept** http header right

I am getting the right response header as **text/plain** when my request **Accept** header is **text/plain**

Hope this helps

`curl -i -X POST --header 'Content-Type: application/json' --header 'Accept: text/plain' 'http://localhost:8080/api/workflow' -d '
> {
>   "name": "sample",
>   "version": 1,
>   "correlatonId": "corr1",
>   "input": {
>     "fileName": "f1"
>   },
>   "taskToDomain": {
>     "T1": "mydomain"
>   }
> }
> '
HTTP/1.1 200 OK
Date: Fri, 22 Jun 2018 02:04:47 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, DELETE, PUT
Access-Control-Allow-Headers: Content-Type, api_key, Authorization
**Content-Type: text/plain**
Transfer-Encoding: chunked
Server: Jetty(9.3.9.v20160517)
`
