### ISSUE TITLE
[help wanted] If all the unit test cases pass for a new persistence module, is it ok to assume everything is working fine 

### ISSUE THREAD

**Issue by manudilipshah** [Netflix/conductor#613]
I have written cassandra integration for conductor.It passes all the unit test cases.
Is it ok to assume everything is working fine or if something else needs to be tested what is it?

**Comment by jvemugunta** [comment]
I am not sure. I was using MYSQL database module and found a deadlock with concurrent threads are trying to poll the same task at the same time. I have opened a pull request and fixed the bug. I am waiting for the comments for the authors if my code can be merged into the main stream.

Here is the pull request
https://github.com/Netflix/conductor/pull/621

**Comment by apanicker-nflx** [comment]
@manudilipshah Along with unit tests, also submit integration tests which are executed in the test-harness module, if you are contributing a new persistence module.
