### ISSUE TITLE
how to create new tasks and add in queue so that the worker can be assigned with these tasks

### ISSUE THREAD

**Issue by parmeshdayal** [Netflix/conductor#622]
I  am able to create new workers and add it to the workflowtaskcoordinator.The workers start polling for the tasks , since the task list is empty.the code isnt working

How should i add the tasks (specifically HTTP task) in the queue that the workers is polling for.

here is the snippet of the code:- 
Worker worker1 = new SampleWorker("task_111");

WorkflowTaskCoordinator.Builder builder = new WorkflowTaskCoordinator.Builder();
		WorkflowTaskCoordinator coordinator = builder.withWorkers(worker1, worker2).withThreadCount(threadCount).withTaskClient(taskClient).build();
		
//Start for polling and execution of the tasks
coordinator.init();

**Comment by jvemugunta** [comment]
You need to start the workflow to see the Workers executed on the client side.

Do you start your workflow? You can use curl commands to start your workflow

**Comment by parmeshdayal** [comment]
Can you point out some document that could explain what is a workflow and how it is different between workflowcoordinator ?

And is there a way to start a workflow through java client .

if yes , would be highly obliged if you could provide me with code snippet.

Also my main motive is to run some HTTP tasks that query rest endpoints using  the workers .

**Comment by parmeshdayal** [comment]
I also tried creating a new workflow following this link: https://netflix.github.io/conductor/metadata/
but  I am receiving this error:{code=NOT_FOUND, message=No such workflow found by name=encode_and_deploy, version=1}

this was done using swagger api start workflow request.

here is the json:
{
  "name": "encode_and_deploy",
  "description": "Encodes a file and deploys to CDN",
  "version": 1,
  "tasks": [
    {
      "name": "encode",
      "taskReferenceName": "encode",
      "type": "SIMPLE",
      "inputParameters": {
        "fileLocation": "${workflow.input.fileLocation}"
      }
    },
    {
      "name": "deploy",
      "taskReferenceName": "d1",
      "type": "SIMPLE",
      "inputParameters": {
        "fileLocation": "${encode.output.encodeLocation}"
      }

    }
  ],
  "outputParameters": {
    "cdn_url": "${d1.output.location}"
  },
  "schemaVersion": 2
}

**Comment by parmeshdayal** [comment]
I was able to create workflows with tasks in it. **still my workers are not not picking those tasks.**
The work flow is visible in the conductor UI under metadata/workflow def.
The task added into the workflow is not visible on the UI under metadata tasks.

Please suggest some workarounds for the bold text

**Comment by dileepkeely** [comment]
1.Can you please let me know  where we need to place the WORKFLOW defined json file, that act as an input.
2. Where should I be writing the code for Worker to be registered.  Do  we need to  write it along with conductor jar and deploy this as part of the condcutor generated jar?
 Please suggest. I want to orchestarte our microservices.
```
Worker worker1 = new SampleWorker("task_111");

WorkflowTaskCoordinator.Builder builder = new WorkflowTaskCoordinator.Builder();
WorkflowTaskCoordinator coordinator = builder.withWorkers(worker1, worker2).withThreadCount(threadCount).withTaskClient(taskClient).build();

//Start for polling and execution of the tasks
coordinator.init();
```

**Comment by apanicker-nflx** [comment]
Please follow the updated documentation [here](https://netflix.github.io/conductor/gettingstarted/basicconcepts/) on how to get started with using conductor. Also, please go through the [developer labs](https://netflix.github.io/conductor/labs/beginner/) to acclimatize yourself.

**Comment by yumeihua1205** [comment]
> 1.Can you please let me know where we need to place the WORKFLOW defined json file, that act as an input.
> 2. Where should I be writing the code for Worker to be registered. Do we need to write it along with conductor jar and deploy this as part of the condcutor generated jar?
> Please suggest. I want to orchestarte our microservices.
> 
> ```
> Worker worker1 = new SampleWorker("task_111");
> 
> WorkflowTaskCoordinator.Builder builder = new WorkflowTaskCoordinator.Builder();
> WorkflowTaskCoordinator coordinator = builder.withWorkers(worker1, worker2).withThreadCount(threadCount).withTaskClient(taskClient).build();
> 
> //Start for polling and execution of the tasks
> coordinator.init();
> ```

@dileepkeely Hi,  we will start to orchestarte our microservices, also meet the deploy issue, I am confusing about how to deploye the worker, could you please share some info, ths.
