### ISSUE TITLE
Polling for tasks using In memory

### ISSUE THREAD

**Issue by parmeshdayal** [Netflix/conductor#623]
Can Worker  poll for task when server is running  In memory?? ( without running dyanmite ,redis and elastic search)

**Comment by jvemugunta** [comment]
Yes, The worker code is just an HTTP client to poll the tasks. This is easiest way to test your code

**Comment by v1r3n** [comment]
@parmeshdayal @jvemugunta Please be aware, the in-memory implementation is only meant for testing and should't be used for production env.

**Comment by apanicker-nflx** [comment]
Closing since already answered.
