### ISSUE TITLE
com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl - pointing to wrong host

### ISSUE THREAD

**Issue by sudvarma** [Netflix/conductor#624]
conductor-server_1  | 0    [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
conductor-server_1  | 8    [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Adding host connection pool for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up]
conductor-server_1  | 8    [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Priming connection pool for host:Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up], with conns:10
************************************************************************************************

server/config/config.properties

db=dynomite
workflow.dynomite.cluster.hosts=localhost:8102:local-dc
workflow.dynomite.cluster.name=dyn_o_mite
workflow.namespace.prefix=conductor
workflow.namespace.queue.prefix=conductor_queues
queues.dynomite.threads=10
queues.dynomite.nonQuorum.port=22122
workflow.elasticsearch.url=localhost:9300
workflow.elasticsearch.index.name=conductor
conductor.additional.modules=class_extending_com.google.inject.AbstractModule
loadSample=true
EC2_AVAILABILITY_ZONE=local-dc

********************************************************************************

Tasks are not moving to IN_PROGRESS state even on polling for the task type (GET /tasks/poll/{tasktype})

**Comment by akshat-g** [comment]
Is 'ais_post' the task you are polling? That is the system task. SystemTaskCoordinator will take care of that.
