### ISSUE TITLE
Task DOES NOT proceed to IN_PROGRESS

### ISSUE THREAD

**Issue by sudvarma** [Netflix/conductor#626]
Steps followed :

1. Created TaskDef
[
{
  "name": "ais_post",
  "retryCount": 1,
  "timeoutSeconds": 600
}
]

2. Created Workflow Def

{
    "name": "Booking_Orch",
    "correlationId": "23",
    "description": "Booking workflow",
    "version": 1,
    "tasks": [
        {
            "type": "HTTP",
            "name": "ais_post",
            "taskReferenceName": "save_ais_booking",
            "inputParameters": {
                "http_request": {
                    "uri": "${workflow.input.ais_post_url}",
                    "method": "POST",
                    "body": "${workflow.input.ais_post_body}",
                    "Accept": "application/json",
                    "Content-Type": "application/json"
                }
            }
        }
    ],
    "schemaVersion": 2
}

3. Started Workflow with input parameters
{
  "name": "Booking_Orch",
  "version": 1,
  "correlationId": "23",
  "input": {
        "ais_post_url": "http://<host>:<port>/service/us/32818/problems/search",          
        "ais_post_body": {
              "status": [
                      "NEW",
                      "ERROR",
                      "ASSIGNED",
                      "WORK_IN_PROGRESS",
                      "ANSWERED"
                ]
	    }
   },
  "taskToDomain": {}
 }

4. Workflow goes to RUNNING state - if wrong URL provided goes to FAILED state

5. Polls for task "ais_task" [/tasks/poll/{tasktype}]
   Returns 204 - with no response. The task doesn't proceed.

Polling for sample kitchensink workflow's task_1 returns 200 with proper response and task proceeds to IN_PROGRESS. Tried with both "memory" option and "dynomite" option in the config.properties

Are there any additional steps needed - please advice.

**Comment by sudvarma** [comment]
The workflow goes into RUNNING state. But no clue about the state of the task. 
/tasks/in_progress/ais_post API returns no valid task.

**Comment by sudvarma** [comment]
Incase the URL referred in the task is made not accessible - the workflow fails promptly on starting the workflow. No error in logs. Please find the attached screenshot.

<img width="1440" alt="lwscreenshot 2018-04-21 at 9 19 55 am" src="https://user-images.githubusercontent.com/34787500/42016354-dbf7ad56-7ac8-11e8-913d-2ea84b109016.png">
<img width="1440" alt="lwscreenshot 2018-04-21 at 9 19 54 am" src="https://user-images.githubusercontent.com/34787500/42016356-dcff896c-7ac8-11e8-858b-41ebe3d0b386.png">

**Comment by sudvarma** [comment]
Once the URL is accessible - no clue - please find the attached screen shot.

<img width="962" alt="screen shot 2018-06-28 at 12 07 15 pm" src="https://user-images.githubusercontent.com/34787500/42017826-fd0c3d18-7acd-11e8-8126-5462fdb4d10f.png">

<img width="947" alt="screen shot 2018-06-28 at 12 07 02 pm" src="https://user-images.githubusercontent.com/34787500/42017828-fe398a74-7acd-11e8-8c0d-5a73f6d81def.png">

Is there a way to dump the output from task/workflow?

Also after a long time - i see the below error being printed the prompt

conductor-server_1  | Caused by: com.netflix.dyno.connectionpool.exception.PoolTimeoutException: PoolTimeoutException: [host=Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up], latency=800444(0), attempts=0]Fast fail waiting for connection from pool

**Comment by apanicker-nflx** [comment]
From the logs and error messages posted above, it seems that dynomite is not setup correctly to be used. Please follow the documentation [here](https://netflix.github.io/conductor/server/#configuration-parameters) to ensure your configuration is correct.
