### ISSUE TITLE
Run simple hello world example using basic micro service

### ISSUE THREAD

**Issue by parmeshdayal** [Netflix/conductor#629]
I'm able to create workers and also register a workflow with tasks added to it.
but I'm unable to make the workers execute those tasks .

**Here is how I'm creating the worker:**

TaskClient taskClient = new TaskClient();
taskClient.setRootURI("http://localhost:8080/api/")

Worker worker1 = new SampleWorker("serve _deciderQueue");

WorkflowTaskCoordinator.Builder builder = new WorkflowTaskCoordinator.Builder();
		WorkflowTaskCoordinator coordinator = builder.withWorkers(worker1, worker2).withThreadCount(threadCount).withTaskClient(taskClient).build();
//Start for polling and execution of the tasks
coordinator.init();

**I registered the workflow using the curl commands  through swagger api**

But my workers are unable to execute the tasks .

**The task list is coming out to empty when polling for the task is done in conductor.init method.**

Any help is appreciated!

**Comment by jvemugunta** [comment]
send your curl commands and also send the source code for SampleWorker

**Comment by parmeshdayal** [comment]
**here is the curl command:**
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{ \ 
     "name": "http_flow", \ 
     "description": "Simple http flow", \ 
     "version": 1, \ 
     "schemaVersion": 2, \ 
     "inputParameters": [], \ 
     "tasks": [ \ 
         { \ 
             "name": "get_version", \ 
             "taskReferenceName": "get_version", \ 
             "type": "HTTP", \ 
             "startDelay": 0, \ 
             "inputParameters": { \ 
                 "http_request": { \ 
                     "uri": "http://localhost:9200", \ 
                     "method": "GET", \ 
                     "contentType": "application/json" \ 
                 } \ 
             } \ 
         } \ 
     ], \ 
     "outputParameters": {} \ 
 } \ 
 ' 'http://localhost:8080/api/metadata/workflow'

**Sample worker:**
public class SampleWorker implements Worker {

	private String taskDefName;
	
	public SampleWorker(String taskDefName) {
		this.taskDefName = taskDefName;
	}
	
	@Override
	public String getTaskDefName() {
		return taskDefName;
	}

	@Override
	public TaskResult execute(Task task) {
		
		System.out.printf("Executing %s%n", taskDefName);
		TaskResult result = new TaskResult(task);
		result.setStatus(Status.COMPLETED);
		
		//Register the output of the task
		result.getOutputData().put("outputKey1", "value");
		result.getOutputData().put("oddEven", 1);
		result.getOutputData().put("mod", 4);
		
		return result;
	}

**Comment by preeth-gopalakrishnan** [comment]
Worker should be initialized with the taskname
