### ISSUE TITLE
Add support for execution of ephemeral workflows.

### ISSUE THREAD

**Issue by gorzell** [Netflix/conductor#631]
We have a use case where we need to be able to submit a large/arbitrary number of different workflow definitions to be executed by Conductor.  I don't think that it makes sense to first add each of these definitions to the Metadata store in order to then execute at least once and quite possibly only once.  Instead I would like to add an API through which you can schedule a workflow execution by providing the definition directly, and that definition will only exist for that execution.  A side benefit is that this also has the potential to be really useful for testing.

## Design
I think that the best way to accomplish this is to modify the ExecutionService and supporting storage and execution classes to always contain the  WorkflowDefinition, rather than look it up from the Metadata service as it does today.

* Refactor WorflowId and Version into a WorkflowReference object to better express that they are always required as a pair.
* Refactor `Workflow` to contain a `WorkflowDefinition` and perhaps a `WorkflowReference`, although the reference would only be for tracking purposes and should never be used for a lookup.
* Persist the WorkflowDefinition as part of execution.
* Add an API for submitting a `WorkflowDefinition` to be scheduled for execution.

**Comment by v1r3n** [comment]
@gorzell 
I think having ephemeral workflows have a merit and I can see more use cases for it.
The above design proposal makes sense.  However, few points:

* TaskDefs are also looked up at some point of time during execution.  Today some of the properties are looked up from TaskDefs, I think they should also be moved under WorkflowTask to WorkflowDefinition is self sufficient for such workflows.
* A possible enhancement could be to use this approach for all the workflows, where when submitting a workflow for execution, you could pass WorkflowDefinition or pre-defined workflow with name/version pair which is looked up to retrieve WorkflowDefinition and then used for execution.   This will make execution path streamlined.  The downside is that if the definition is changed - the running workflows will not get the updated definition and will have to be updated.

@cyzhao I think we have similar requirements too.

**Comment by gorzell** [comment]
@v1r3n 
> A possible enhancement could be to use this approach for all the workflows

That is the approach I also think is best and have been working on, so I don't consider this an enhancement :-).  It is a bit complicated when considering backwards compatibility in the data objects and there is quite a bit of intermingled logic that needs to be sorted out.

I will take a look at the task defs.  I would generally think running workflows not having their definitions change is a feature rather than a downside, however I also realize that you all have some really long running flows.

**Comment by cyzhao** [comment]
I like the approach, I think it is a merit to have the snapshot of workflow/task definitions stored as part of workflow execution so workflow/task definition changes won't impact existing workflow executions, especially when backward breaking changes are introduced.
