### ISSUE TITLE
com.netflix.dyno.connectionpool : PoolTimeoutException : when polling for task

### ISSUE THREAD

**Issue by sudvarma** [Netflix/conductor#632]
conductor-server_1  | java.lang.RuntimeException: java.lang.RuntimeException: com.netflix.dyno.connectionpool.exception.PoolTimeoutException: PoolTimeoutException: [host=Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up], latency=800407(0), attempts=0]Fast fail waiting for connection from pool

config.properties
db=memory
workflow.dynomite.cluster.hosts=localhost:8102:local-dc
workflow.dynomite.cluster.name=dyn_o_mite
workflow.namespace.prefix=conductor
workflow.namespace.queue.prefix=conductor_queues
queues.dynomite.threads=10
queues.dynomite.nonQuorum.port=22122
workflow.elasticsearch.url=localhost:9300
workflow.elasticsearch.index.name=conductor
conductor.additional.modules=class_extending_com.google.inject.AbstractModule
loadSample=true

**Comment by saidatta** [comment]
It might be a symptom that your db is overwhelmed. Have you tried using a dynomite?

**Comment by jwulf** [comment]
Need to scale up the Dynomite backend I think. I see this when doing throughput load testing. No data is lost, but the world stops for a second.
