### ISSUE TITLE
Conductor with Redis Cluster in own Data Center

### ISSUE THREAD

**Issue by jvemugunta** [Netflix/conductor#633]
Can you please advise if we could Conductor with Dynomite/Redis Cluster running in our own Data Center. We have regulatory issues and we can't run our code on cloud. 

We have been evaluating Netflix Conductor as the workflow engine for our company. I am impressed with the architecture and code is precise. We are thinking of rolling this engine for our enterprise.

Any guidance you provide is highly appreciated. Redis and Dynomite is all new for us and some advice if running Redis Cluster in our datacenter is a recommended option.

I am looking at the settings and sample configuration on running Redis cluster in our DataCenter

Thank you,

**Comment by jvemugunta** [comment]
Hi @v1r3n , Can you answer the above questions?

**Comment by cyzhao** [comment]
As long as you can set up Dynomite/Redis in your own data center, Conductor should be abele to work with it fine.

**Comment by v1r3n** [comment]
@jvemugunta Dynomite can be setup in a datacenter.  Refer to the guide at https://github.com/Netflix/dynomite on how to setup a Dynomite cluster.  
Reach out to Dynomite team (as listed on the dynomite readme) for help and questions on dynomite setup.

Alternatively, you should be able to use Redis cluster setup in a datacenter.
