### ISSUE TITLE
How to run kitchensink demo

### ISSUE THREAD

**Issue by jeremyjjbrown** [Netflix/conductor#64]
I'm running conductor from the docker image and any workflows I trigger just sit with the first task on SCHEDULED. The log provides nothing useful.

I've run the kitchensink workflow with various versions of 
{  
   "mod": 1,  
   "oddEven": "odd"  
} 
/api/workflow/main_workflow?version=1&correlationId=1

Could someone provide and example of how to trigger the example?

**Comment by v1r3n** [comment]
I have created a guide here.  Hope this helps:

https://netflix.github.io/conductor/metadata/kitchensink/#running-kitchensink-workflow

**Comment by jeremyjjbrown** [comment]
Thanks for creating this. but I still have no idea how to kickoff a workflow. `-DloadSample=true` when I start up the server is not very flexible.

**Comment by v1r3n** [comment]
@jeremyjjbrown  
I have updated the guide with curl commands to start the workflow.
https://netflix.github.io/conductor/metadata/kitchensink/#running-kitchensink-workflow

Also, added a sample worker in Java and Python.  Documentation here:
https://netflix.github.io/conductor/worker/

**Comment by kartikzheng** [comment]
> @jeremyjjbrown I have updated the guide with curl commands to start the workflow. https://netflix.github.io/conductor/metadata/kitchensink/#running-kitchensink-workflow
> 
> Also, added a sample worker in Java and Python. Documentation here: https://netflix.github.io/conductor/worker/

Hello, these links are invalid. Do you have a new link address? thank you
