### ISSUE TITLE
How can I view conductor server metrics?

### ISSUE THREAD

**Issue by akshat-g** [Netflix/conductor#640]
I have read spectator codebase to study how it collects metrics conductor server. However where can I view these metrics? How are they exposed?

**Comment by akshat-g** [comment]
@kishorebanala - thanks. is there any documentation by Netflix where I can find how to do this?

**Comment by saidatta** [comment]
Does anyone use `jconsole` for collecting metrics? I have got that part of it working but I had trouble understanding some of the keys.
