### ISSUE TITLE
Netflix Team - Enterprise Guidance 

### ISSUE THREAD

**Issue by jvemugunta** [Netflix/conductor#641]
I lead the Enterprise Architecture Team at Florida Blue. We are convinced Netflix Conductor is the right workflow engine for our company. We want to push into production in the next month and want to run this platform in our DataCenters. We have regulatory rules and can't run on cloud

Few questions 
1) How many workflows does Netflix run every day?
2) Do you have the list of companies that are using Netflix Conductor in Production
3) We are building a dedicated team on this platform. Does Netflix encourages collaboration for enhancements?
4) Debating on the database storage - MYSQL vs REDIS. We need Point of Time Recovery for 7 years worth of Workflows. Does REDIS support this kind of storage and point of time recovery  requirements like traditional RDBMS systems  

Appreciate your guidance

**Comment by cyzhao** [comment]
1. We run over 10 millions workflows per month.
2. I don't have a list. @v1r3n do you?
3. Yes we encourage collaboration, we are currently collaborating with Github on 2.0 development where gRPC support are being introduced, plus other features.
4. @ipapapa can you address this question?

**Comment by jvemugunta** [comment]
Thank you @cyzhao . Very encouraging.

- How complex are the workflows used at Netflix? Most of our workflows are long lived tasks and are very complex in nature that can span for days to weeks. We are thinking about using WAIT tasks to meet this requirement. Are there better alternatives?

- Regrading Workers, When there are no a scheduled tasks , constant polling for tasks can lead to performance on RDBMS database engines . I don't know how this works internally with REDIS. Do we have plans to introduce some kind of caching layer over DB system when an empty task is polled for an infinite amount of time

- **Transactional Support** -  The current DAO model for REDIS doesn't support transactions. I was able to prove by enabling a break point in the code and let few inserts happen into REDIS and stop the server. The client gets the error message as "unable to start the workflow". When the REDIS server is bought back, I see the workflow state in "NON-WORKABLE" conditions" with only partial data in the REDIS keys. Is there an API we can use to clean up these "INCOMPLETE" workflow data from the underlying DB system

- Race Conditions - I can see race conditions with MYSQL DAO code and getting surfaced with high volume perf testing (100 concurrent users with 1000 iterations ) in this code. I didn't spend if the same is true for REDIS DAOs
https://github.com/Netflix/conductor/blob/bdd7061d6c5609b43e8969fefce938be93a571e1/mysql-persistence/src/main/java/com/netflix/conductor/dao/mysql/MySQLQueueDAO.java#L247-L263

**Comment by ipapapa** [comment]
@jvemugunta 4. I do not recall seeing an API that can do that in Redis. At Netflix, we mainly use it against [Dynomite](https://github.com/netflix/dynomite)/Redis. You can read the [Redis persistence documentation](https://redis.io/topics/persistence) for more details. For disaster recovery, we store the data to the drive and backup it daily to S3.

**Comment by v1r3n** [comment]
@jvemugunta 

We don't actively maintain the list of production users of Conductor outside Netflix.  Based on the information we have so far, we have seen it being used across wide set of industry including media/entertainment, supply chain and others.

**Comment by jvemugunta** [comment]
thanks @cyzhao @ipapapa @v1r3n for your comments. 

Constant polling for empty tasks may be overkill for relational databases resulting into deadlocks with concurrent worker threads polling for same tasks. I am researching on the caching techniques. Will reach out to you if I find an efficient solution.

**Comment by mudit3774** [comment]
Thanks @jvemugunta for the question. @cyzhao do we have concrete plans for transactional support in 2.0 ? Is there a ticket we can follow ?

**Comment by cyzhao** [comment]
@mudit3774 we don't have a concrete plan yet, currently we don't use github as ticketing system but we will definitely consider.
