### ISSUE TITLE
How to run conductor UI using pre-built binaries listening at 5000 port with server already running at 8080 port?

### ISSUE THREAD

**Issue by akshat-g** [Netflix/conductor#643]
I have run conductor server using pre-built binaries. I am unable to run stand alone conductor UI using pre built binaries at 5000 port with server listening at 8080 port. Any help is appreciated.

**Comment by rbeers** [comment]
Node api is looking for WF_SERVER environment variable.

```shell
export WF_SERVER=http://localhost:8080/api/
node server.js
```

See: https://github.com/Netflix/conductor/blob/master/docker/ui/bin/startup.sh

Hope that helps.

**Comment by akshat-g** [comment]
@rbeers - For this I will have to pull the code. How to run using pre-built binaries?
