### ISSUE TITLE
Pointers to use dynamodb as backend implementation

### ISSUE THREAD

**Issue by rverma-nikiai** [Netflix/conductor#647]
Hi Team,
First of all really appreciate for great work. I could understand that using dynamodb as backend would be against open-source. But can you give me pointers on what are components involved in implementing a persistence for conductor. Can dynamodb act as sole persistence avoiding mysql and redis dependencies completely.

**Comment by kishorebanala** [comment]
You can follow current implementations of `com.netflix.conductor.dao` in `core` module, and provide your own similar implementations for dynamodb.

**Comment by apanicker-nflx** [comment]
@rverma-nikiai Please follow the documentation [here](https://netflix.github.io/conductor/extend/#backend) to provide an implementation for dynamodb as the backend.
