### ISSUE TITLE
basic UI for creating workflow

### ISSUE THREAD

**Issue by sudvarma** [Netflix/conductor#649]
Any reference to basic UI for creating/modifying workflow. It is just for demo purpose.

**Comment by rbeers** [comment]
I'm currently exploring draw.io and doing something similar to the AWS Step Functions plugin:
https://github.com/sakazuki/step-functions-draw.io

**Comment by apanicker-nflx** [comment]
Currently, we do not have a UI for creating worflows. It can only be done programmatically and/or using JSON and JSONPath. 
Please feel free to submit a PR with an implementation and we would be happy to review and merge the same.

**Comment by vbratitsa** [comment]
> Currently, we do not have a UI for creating worflows. It can only be done programmatically and/or using JSON and JSONPath.
> Please feel free to submit a PR with an implementation and we would be happy to review and merge the same.

Hi, passed year after your answer, is there any UI for creating worflows was developed?)

**Comment by kishorebanala** [comment]
@vbratitsa We're pipelining the release of revamped UI later this year. We don't have concrete timelines yet, we'll update as we know more.

**Comment by originswift-sys** [comment]
Bump. Any updates on this?

**Comment by apanicker-nflx** [comment]
This ability was added to the UI in [v3.6.0](https://github.com/Netflix/conductor/releases/tag/v3.6.0)
