### ISSUE TITLE
Documentation Bug: Incorrect description for `subWorkflowParam`

### ISSUE THREAD

**Issue by makesitgo** [Netflix/conductor#652]
**See:** https://netflix.github.io/conductor/metadata/systask/#sub-workflow

The description of the `subWorkflowParam` is copy-pasted from the above system task: Join.

name | description
-- | --
subWorkflowParam | List of task reference name, for which the JOIN will wait for completion.

**Fix:** Provide the correct description for the subWorkflowParam

**Comment by apanicker-nflx** [comment]
Thanks for pointing this out. We are currently revamping the entire documentation and will make this fix.
