### ISSUE TITLE
Decouple Conductor from Spectator

### ISSUE THREAD

**Issue by mudit3774** [Netflix/conductor#656]
Hey, 

It seems that both Conductor worker and server is tightly coupled with Spectator. Would it make sense to add a metrics interface (extracted from com.netflix.conductor.metrics.Monitors and com.netflix.conductor.client.task.WorkflowTaskMetrics) and make changes to code to this interface ? We can have Spectator as the default implementation. 

This is driven by the fact that adopters would want to integrate conductor in their production setups and would want to leverage their existing app monitoring and alerting frameworks within the organization and might not want to invest in the overhead of a prod setup and deployment of Atlas. 

Let me know if I am missing something. I would be interested in making the change if it makes sense. Let me know your thoughts.

**Comment by mudit3774** [comment]
@cyzhao @v1r3n Will this be a contribution that you guys are willing to consider and is aligned with the goal of adoption ?

**Comment by cyzhao** [comment]
@mudit3774 Spectator is already pluggable where any Registry implementation can be plugged in to send metrics to other monitoring systems. Spectator also provides Metrics3 implementation out of box - http://netflix.github.io/spectator/en/latest/registry/metrics3/

**Comment by mudit3774** [comment]
Understood. Thanks for the response.
