### ISSUE TITLE
What is the recommended number of Task Threads?

### ISSUE THREAD

**Issue by saidatta** [Netflix/conductor#659]
What is the recommended task threads do I need to create for a single worker? 
From my understanding, the task threads need to be equal or more than the number of tasks within the  workflow? 

What if I have dynamic join that spawns 500 tasks? Do I need to put 500 task threads, or is it okay if I can tweak it down to a relatively smaller amount (Say, 200 task threads)?

**Comment by saidatta** [comment]
@v1r3n

**Comment by apanicker-nflx** [comment]
Hi @saidatta , as mentioned [here](https://github.com/Netflix/conductor/blob/master/client/src/main/java/com/netflix/conductor/client/task/WorkflowTaskCoordinator.java#L88), the number of task threads must be greater than or equal to the number of worker processes to avoid starvation. 

If you have 500 unique tasks (i.e. 500 different task definitions), then you would need to have 500 different workers to process these tasks. However, if all 500 of these are the same task definition, then you can have even a single worker with 'n' threads to process them. It means that only 'n' tasks will be processed simultaneously at any point of time.
