### ISSUE TITLE
Has anyone integrated spectator with Atlas here?

### ISSUE THREAD

**Issue by akshat-g** [Netflix/conductor#661]
How to publish conductor server metrics to Atlas? I have local atlas server running.

**Comment by jvemugunta** [comment]
I do have similar requirement. Appreciate any guidance on how to integrate Spectator with Atlas.

**Comment by apanicker-nflx** [comment]
I would recommend reading the conductor documenation [here](https://netflix.github.io/conductor/metrics/server/#publishing-metrics) spectator documentation [here](http://netflix.github.io/spectator/en/latest/) to publish metrics to atlas using spectator.
