### ISSUE TITLE
Claiming a specific task from the queue

### ISSUE THREAD

**Issue by ms1111** [Netflix/conductor#663]
Hi, I'm wondering if there's a way to claim a specific task (by ID) from the queue.

I might have a situation where tasks are flowing from one process to a second via an out-of-band queuing mechanism, but I still want Conductor to have some visibility of the workflow.

For example:

1. Process 1 starts the workflow.
2. Process 2 polls for a task (any task), does some work, and completes the task. It kicks off process 3 out-of-band and gives it the new task ID.
3. Process 3 (worker ID XXX) tells Conductor it's working on the task.
4. Conductor removes the task from the queue and updates it to be IN_PROGRESS and the worker ID is XXX.

There's an API to update a task, but if the new status is IN_PROGRESS it [puts it back in the queue](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L521) so I don't think that's quite what I'm looking for.

Thanks,
Mike

**Comment by apanicker-nflx** [comment]
It is not possible to claim a specific task from the queue.
From the example case, it seems like you would want your external processes to mint and orchestrate tasks among themselves, which removes the purpose of orchestration and scheduling done by conductor.

**Comment by apanicker-nflx** [comment]
Closing this issue for now. Please reopen and provide more details about your use-case.
