### ISSUE TITLE
Add checkstyle plugin as part of the gradle build

### ISSUE THREAD

**Issue by josedab** [Netflix/conductor#665]
I noticed there are some inconsistencies on the formatting of the backend code:
- Some classes of the project are with tabs, others with spaces
- No spaces before/after code blocks
- Different indentation on code blocks
- For more ideas, see for example [Google Java Style Guide](http://checkstyle.sourceforge.net/reports/google-java-style-20170228.html)

While some of the rules above are optional, I believe having consistent formatting rules will help the project in the long term:
- Changes will be related to logic and not formatting
- It makes it easier to new people trying to contribute. One less thing to think about.

I believe, using the [checkstyle plugin](https://docs.gradle.org/current/userguide/checkstyle_plugin.html) will help detect these issues and make the contributor aware of formatting inconsistencies before committing/pushing code. As a bonus, the checkstyle plugin can be run as part of the build and used as a check before a PR gets merged.

Any thoughts on this? Is it something people are willing to have?

**Comment by josedab** [comment]
Willing to write a PR related to this issue, just want to make sure contributors are ok with this before spending more time. On top of that, my recommendation would be to adopt the [Google Java Style Guide](http://checkstyle.sourceforge.net/reports/google-java-style-20170228.html) as I found it easy to follow and with enough documentation to point to.

**Comment by josedab** [comment]
@cyzhao Any thoughts? I can see `pmd` also playing a role in the project, but would like to know if the team has specific thoughts on this.

**Comment by apanicker-nflx** [comment]
This would definitely be a nice-to-have. Please feel free to submit a PR with the formatting and PMD plugin changes.

**Comment by josedab** [comment]
Awesome! Not currently working in the project but if I find some time, I will definitely do 👍

**Comment by apanicker-nflx** [comment]
Closing this issue for now.
