### ISSUE TITLE
Doubts on working of Netflix Conductor 

### ISSUE THREAD

**Issue by MohneeshParkhi** [Netflix/conductor#666]
I am totally new to Conductor and experimenting with it to orchestrate a workflow, but have doubts regarding following topics:

A) What is role of inputKeys and outputKeys in Task metadata definition ? Why we used them?
B) What is role of Input Template in Task Meta data defintions ?
C) When writing a Workflow definition, it contains Task definition as JSON object. Task's JSON object contains two keys i.e. input parameters and output Parameters. How they can be used ?

D) Can any person provide me a link to a working example on git to understand its working.

**Comment by saidatta** [comment]
A) `inputKeys` are input `keyNames` the workflow is expecting, I believe outputKeys have a similar purpose. You need inputKeys for defining what inputKeys the workflow needs to expect while being triggered

B) Not sure what you mean.

C) `inputParameters` and `outputParameters` are used to essentially provide a way to exchange information between tasks. If task3 wants to use task2's output, then you need assign the task2's output using JSONPATH within the inputParameters of task3 definition.

D) Have you taken a look at the kitchenSink Example within the codebase.

**Comment by josedab** [comment]
As @saidatta said, I believe [kitchensink example](https://netflix.github.io/conductor/metadata/kitchensink/) is the best way to go.  It helped me understand data flows between tasks and how input and output parameters work.
