### ISSUE TITLE
How to make workflow tasks execution process as synchronous instead of asynchronous

### ISSUE THREAD

**Issue by gsambasiva** [Netflix/conductor#667]
I have a workflow consists of two tasks.
We are having status for task execution level and workflow execution level.

I want workflow status to be updated as completed, If both tasks executions is completed.
But somehow, workflow status is shown as completed, even though second task is in scheduled state.

Is it because of asynchronous behavior of workflow execution?  
If yes can anyone suggest how to make my workflow execution as synchronous?

**Comment by josedab** [comment]
Can you post your task and workflow definitions?

**Comment by apanicker-nflx** [comment]
Closing this as we haven't been able to reproduce this issue. Please reopen if you still encounter this and provide workflow and task definitions for the same.
