### ISSUE TITLE
[Question] How to disable use of elastic search completely

### ISSUE THREAD

**Issue by manudilipshah** [Netflix/conductor#668]
I have persistence set to mysql but I don't have an elastic search running.I believe it is not required for workflows to run.

I see errors related to that in the logs.Is there a way I can disable that?

**Comment by saidatta** [comment]
I am not sure whether Conductor has Toggle of ElasticSearch.

If there isnt, try running a bare bones ES docker image (from docker-compose.yaml) and link the network address in config.properties.

**Comment by faraday-m** [comment]
Is it possible to run mysql with in-memory elasticsearch instance? It works when we set db in memory mode but doesn't work for mysql config.
I couldn't find any things in mysql or server implementation that requires running elasticsearch. Which files should I look? 
And would it be possible to run Conductor with other index engines like Apache Solr?

**Comment by apanicker-nflx** [comment]
Currently, disabling use of elasticsearch completely is not allowed. However, you should be able to plugin other index engines instead of ES by implementing [IndexDAO](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/dao/IndexDAO.java) and plugging it in.
