### ISSUE TITLE
Task update endpoint returning mismatch of content-type header and actual body

### ISSUE THREAD

**Issue by mdecuir** [Netflix/conductor#67]
Commit d6d483fa149d6c7e3d9eec5a3280874ae80c0574 changed the task update method to return the task id as a string.

The tasks endpoint of the http interface is returning this value now, but still using a content-type header of application/json.  As a result, the Swagger UI and the python client are reporting errors when they try to parse the response as valid json when it is actually just a string.

**Comment by v1r3n** [comment]
@mdecuir thanks for pointing out.  I have fixed it in the subsequent commit.  I have also merged the python_client branch into dev.

**Comment by mdecuir** [comment]
I haven't looked back at the python client code, but this commit appears to resolve the issue nicely.
