### ISSUE TITLE
[Question] How to retry a failed workflow

### ISSUE THREAD

**Issue by manudilipshah** [Netflix/conductor#670]
I was trying to figure out the following API's
POST /workflow/{workflowId}/rerun
POST /workflow/{workflowId}/restart
POST /workflow/{workflowId}/retry

I was able to run restart using the following request
curl -X POST http://<conductor-ip>:8080/api/workflow/<workflow-id>/restart

Can you give some examples on how to rerun and retry workflows

**Comment by saidatta** [comment]
Have you tried using the `workflow-id` that is outputted after starting the workflow?

**Comment by manudilipshah** [comment]
Yes @saidatta I tried.If it works for you can you please comment with the complete request along with the request body if any

**Comment by kishorebanala** [comment]
@manudilipshah You can learn more about all the API's available with Swagger, which should be available out of box. Also there is limited documentation on how to use certain API's. Eg:
https://netflix.github.io/conductor/runtime/#rerun
And for retry, you just have to pass in workflowId in query params.
