### ISSUE TITLE
Same event listener for different workflows

### ISSUE THREAD

**Issue by MLauri** [Netflix/conductor#675]
Hi guys,
is it possible to manage via a unique event handler the same "event task" used in different workflows?
For example; suppose I have two workflows defined as:

_**Wkf1: TaskA -> Event1 -> Task B
Wkf2: TaskX -> Event1 -> TaskY**_

If I'm not wrong from documentation seems that I have to define two event handlers for managing the same Event1 for each workflow.

```
{
            "name": "event1 handler for wkf1",
            "event": "conductor:wkf1:event1",
            "actions": [
                {
                    "action": "dosomething"...,
                }
            ],
            "active": "true"
}

{
            "name": "event1 handler for wkf2",
            "event": "conductor:wkf2:event1",
            "actions": [
                {
                    "action": "dothesamethingaseventhandlerforwkf1"...,
                }
            ],
            "active": "true"
}
```

Is it possible to use the same event handler for both wkf1 and wkf2 (assuming conductor as the queue manager)?

**Comment by kishorebanala** [comment]
@MLauri You're right, Event Handler expects Workflow Id and Task reference name or Id. We have it in our roadmap to support Event multiplexing and demultiplexing, but feel free to send a PR.
