### ISSUE TITLE
[QUESTION] Does UI support authentication?

### ISSUE THREAD

**Issue by AlexeyPirogov** [Netflix/conductor#676]
I started a docker image and opened web-ui.
However, I didn't find how to create a new user and manage permissions.

Does Conductor has authentication functionality?
Or maybe in Netflix it is closely linked to Netflix internal authentication service and team didn't put it here.

**Comment by kishorebanala** [comment]
@AlexeyPirogov No, Conductor UI doesn't support Authentication and Authorization at this time.

**Comment by elisherer** [comment]
It does now 😊 [v2.28.0](https://github.com/Netflix/conductor/releases/tag/v2.28.0)
