### ISSUE TITLE
Remove IndexDao dependency from RedisExecutionDAO

### ISSUE THREAD

**Issue by mudit3774** [Netflix/conductor#677]
Hey, 

I was going through RedisExecutionDAO and it seems that in a lot of functions IndexDao is called either to index or get values. I am not able to understand why would we not have such call in a layer above this i.e. ExecutionService.java. The issue is that it is misleading, when I do a executionDAO.createWorkflow(wf); it writes to both Redis and internally indexes the workflow using an index dao. Also, if I want to switch-off indexing, I will have to touch the RedisExecutionDao and all other DAOs that internally call index(). 

Also, it will enable us to easily build features like asyncIndexer and completely switching off Indexing (maintaining one less component in production, if I am fine with giving up some features) as requested in a few tickets. 

@cyzhao @v1r3n @apanicker-nflx @kishorebanala Would love to know your views on the same. Let me know if I missed something here. 

P.S : I will be willing to write a design change proposal for review and submit a PR if this is something that is aligned with the overall goal for conductor.

**Comment by cyzhao** [comment]
@mudit3774 I agree, we wanted to change this as well but didn't get a chance yet, you are welcome to submit a PR.

**Comment by mudit3774** [comment]
@cyzhao : Thanks! I will try to pick this up in the second half of August. 

I wanted to discuss a few design changes : 

1. Some DAO functions completely depend on indexDAO, specifically : addTaskExecLog, getWorkflowsByCorrelationId and addMessage etc. I am assuming, we can live with NOOP in these methods unless we plan to implement them at a later stage. 

2. Would it make sense to pull out an archived service to interact with archived workflows using indexDAO ? 

Also, I will break it down into smaller changes and open independent tickets.

**Comment by cyzhao** [comment]
@mudit3774  your plan sounds good to me, please proceed.

**Comment by apanicker-nflx** [comment]
This change has been made as part of #858.
