### ISSUE TITLE
Working with http_request Task type to hit microservice

### ISSUE THREAD

**Issue by MohneeshParkhi** [Netflix/conductor#678]
I want to hit a service running on mine local host. So followed the documentation to write a chunk of code.
Yet, API is not called by task definition when i am polling for execution of that task.

Doubts:

a) How does polling system executes the task in Worker system.

b) how to hit a micro-service using client application. Any working example link will be a great help.

**Comment by preeth-gopalakrishnan** [comment]
The http task is a system task which will run within the conductor and will not run on a Worker.
Workers are defined for custom tasks.( tasks of type 'Simple' )

A sample workflow (from kitchen sink example) which invokes an HTTP API. This will run within the conductor.
	{
		"name": "worflow_http",
		"description": "invokes an API",
		"version": 1,
		"tasks": [
			 {
			      "name": "search_elasticsearch",
			      "taskReferenceName": "get_es_1",
			      "inputParameters": {
			        "http_request": {
			          "uri": "http://localhost:9200/conductor/_search?size=10",
			          "method": "GET"
			        }
			      },
			      "type": "HTTP"
			  }
		],
		"schemaVersion": 2
	}

**Comment by MohneeshParkhi** [comment]
Thanks prateek
