### ISSUE TITLE
Netflix Conductor UI Retry workflow by editing request

### ISSUE THREAD

**Issue by SivakumarRavi** [Netflix/conductor#680]
Hi ,
In netflix conductor UI we have retry option to retry a workflow if it fails.
Is it possible to edit the input to failed task and retry from the failed task?
Please suggest any solution. Thanks in advance

**Comment by v1r3n** [comment]
@SivakumarRavi you can take the input of the failed workflow and start another instance if that is an option for you.

**Comment by apanicker-nflx** [comment]
Closing this issue as this has already been answered.
