### ISSUE TITLE
[Question]How to obtain state and outputParameters of workflow instances without `GET /workflow/{id}` API in real time?

### ISSUE THREAD

**Issue by startan** [Netflix/conductor#681]
How to obtain state and outputParameters of workflow instances without `GET /workflow/{id}` API in real time?
We can only update the status of workflow pulling data from server timely. Do you provided a notice api in a push way.

**Comment by josedab** [comment]
@startan I believe the current code does not support support what you are asking. Only mechanism at the moment is through polling.

**Comment by apanicker-nflx** [comment]
@startan You can use the `workflowStatusListenerEnabled` in the [WorkflowDefinition](https://netflix.github.io/conductor/configuration/workflowdef/#workflow-definition) to enable sending out notifications when workflow enters a terminal state. Please follow the documentation [here](https://netflix.github.io/conductor/extend/#workflow-status-listener) to extend this to wire up your custom implementation of notification system.
