### ISSUE TITLE
Conductor is sending POST instead of GET

### ISSUE THREAD

**Issue by star-yar** [Netflix/conductor#682]
I've built a task in my workflow that should call GET but doing POST call
```{
    "name": "task_1",
    "taskReferenceName": "task_1",
    "type": "HTTP",
    "inputParameters": {
        "http_request": {
            "uri": "http://localhost/database",
            "method": "GET",
            "body": {
                "param": "paramData"
            }
        }
}
```

**Comment by preeth-gopalakrishnan** [comment]
Could be because you are including "body" for the GET request.
GET request would not have a body part. 
There is a "header" parameter.
headers | A map of additional http headers to be sent along with the request.

**Comment by josedab** [comment]
My recommendation is to avoid sending GET requests with payload data: 
It is discouraged on the [HTTP RFC 2616 specification](https://tools.ietf.org/html/rfc2616#section-4.3) and most of the server implementations use this as a base guideline.

For a more detailed explanation, see accepted answer on: https://stackoverflow.com/questions/978061/http-get-with-request-body

Having said that, if you think the GET request is the way to go for your use case, you could put that data as one/several parameters in the url:
```
 "method": "GET",
 "uri": "http://myhostname/api?myparam=myparamValue",
```
Hope it helps :)

**Comment by star-yar** [comment]
@josedab, that helps a lot. Much thanks!
