### ISSUE TITLE
Task Management-Log result

### ISSUE THREAD

**Issue by MLauri** [Netflix/conductor#688]
Hi guys,
seems that the management of log data in task doesn't work properly for last releases.
I made different tests using Swagger and the listed endpoints:

```
GET  :  /tasks/{taskId}/log 
POST:  /tasks/{taskId}/log 
```

With version 1.10.11 and 1.10.12 POST action doesn't work.
Instead with version 1.10.5 it's possible to add new log to a task despite an error in the response data ("SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data").
Thanks in advance.

**Comment by kishorebanala** [comment]
This has been fixed in v1.11+
