### ISSUE TITLE
Starting server using maven central based dependencies

### ISSUE THREAD

**Issue by MohneeshParkhi** [Netflix/conductor#692]
I am trying to start conductor using maven central based dependencies following the guidelines, it is giving exception as given below.

I tried to force update mine POM in Project, still facing same exception.

**"Missing artifact com.netflix.conductor:conductor-server-all:jar:1.6.0"** ,  which clearly dipicts that corresponding artifact is missing.

How can i achieve this task, can any person help me ?

**Comment by apanicker-nflx** [comment]
Please follow the instructions [here](https://netflix.github.io/conductor/server/#1-build-from-source) for starting the server.
