### ISSUE TITLE
UI build error

### ISSUE THREAD

**Issue by star-yar** [Netflix/conductor#697]
Trying to build UI with docker.

...
Step 4/11 : RUN mkdir -p /app/ui
 ---> Running in c07047e86a7a
Removing intermediate container c07047e86a7a
 ---> b70b9cb8c275
Step 5/11 : COPY ./docker/ui/bin /app
 ---> 6f68a5e23150
Step 6/11 : COPY ./ui /app/ui
 ---> f8cadec4cbc8
Step 7/11 : RUN chmod +x /app/startup.sh
 ---> Running in 29931522175d
Removing intermediate container 29931522175d
 ---> 6aeeea3a6970
Step 8/11 : RUN cd /app/ui   && npm install   && npm run build --server
 ---> Running in b638d86fb791

> dtrace-provider@0.8.6 install /app/ui/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

make: Entering directory '/app/ui/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/app/ui/node_modules/dtrace-provider/build'

> uws@9.14.0 install /app/ui/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

> base62@1.2.7 postinstall /app/ui/node_modules/base62
> node scripts/install-stats.js || exit 0

> radium@0.18.1 postinstall /app/ui/node_modules/radium
> cd lib || npm run lib

> history@1.17.0 postinstall /app/ui/node_modules/history
> node ./npm-scripts/postinstall.js

> react-router@1.0.3 postinstall /app/ui/node_modules/react-router
> node ./npm-scripts/postinstall.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1394 packages from 1130 contributors and audited 11002 packages in 162.374s
found 20 vulnerabilities (13 low, 1 moderate, 5 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

> nf-workflow-ui@1.0.0 build /app/ui
> gulp build --release

[07:29:27] Failed to load external module @babel/register
[07:29:27] Requiring external module babel-register
gulp[284]: ../src/node_contextify.cc:631:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! nf-workflow-ui@1.0.0 build: `gulp build --release`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the nf-workflow-ui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-02T07_29_27_722Z-debug.log
The command '/bin/sh -c cd /app/ui   && npm install   && npm run build --server' returned a non-zero code: 134

**Comment by danielsitnik** [comment]
Same error here.

**Comment by Mortimor1** [comment]
cd docker/ui
change Dockerfile
change line '  && npm install\' to '  && npm install --no-optional --no-shrinkwrap --no-package-lock\'

**Comment by danielsitnik** [comment]
This is not a solution, but in my case I manually changed the package-lock.json and upgraded the package "natives" to version 1.1.3, after this `docker-compose build` worked.

Now I get errors on startup.sh when I try `docker-compose up`:

```
Starting Conductor UI
/app/startup.sh: line 3:  : not found
/app/startup.sh: line 5:  : not found
/app/startup.sh: cd: line 7: can't cd to /app/ui/dist : No such file or directory
/app/startup.sh: line 15: syntax error: unexpected end of file (expecting "then")
```

**Comment by Mortimor1** [comment]
At least it helped me.
He also writes that he can not find the "dist" as it is when compiling.
I also cloned the repository with the tag "v1.11.0"
and it's better to do 'docker-compose build --no-cache'
so that there are no unintelligible errors.

using google translete.

**Comment by apanicker-nflx** [comment]
Please use the latest conductor version 2.7.+ . This issue should be resolved in the newer versions.
