### ISSUE TITLE
Run UI via jar or war

### ISSUE THREAD

**Issue by ajayaks** [Netflix/conductor#70]
Hi,

I am running conductor server via jar but UI is still i am running via gulp.

How to run UI also via jar or war? Please suggest.
Regards
Ajay

**Comment by v1r3n** [comment]
UI does not use Java - it is written in javascript and uses node.js.  For production usage, you should be creating a UI build using ```gulp build``` and use the ```server.js``` in the dist folder to start the server.  
From the ```dist``` folder run the following to bring up server:

```shell
export WF_SEVER=http://serverhost:port/api
node server.js
```

**Comment by ajayaks** [comment]
I tried but the UI is not coming up.

I am trying to open ui at localhost:5000 and localhost:3000 but noting coming. "This site can’t be reached"

{"name":"Conductor UI","hostname":"ip-192-168-222-18.ec2.internal","pid":83029,"level":30,"msg":"Serving static /Users/ajay/test/conductor/ui/dist","time":"2017-02-10T23:11:23.751Z","src":{"file":"/Users/ajay/test/conductor/ui/dist/webpack:/src/server.js","line":13,"func":"canUseDOM"},"v":0}
{"name":"Conductor UI","hostname":"ip-192-168-222-18.ec2.internal","pid":83029,"level":30,"msg":"Workflow UI listening at http://:::5000","time":"2017-02-10T23:11:23.829Z","src":{"file":"/Users/ajay/test/conductor/ui/dist/webpack:/src/server.js","line":22},"v":0}

**Comment by v1r3n** [comment]
Can you share the exact commands you used to start the server?  Error seems to indicate the server has not started or is not reachable.  Have you also started the Conductor server?

**Comment by ajayaks** [comment]
Conductor server i am running with jar like below and running on port 8080 and swagger apis are available.
java -DloadSample=true  -jar build/libs/conductor-server-1.7.0-SNAPSHOT-all.jar


For UI i have built wit grunt and running like below:-

Already exported WF_SERVER=http://localhost:8080/api 
node dist/server.js

**Comment by v1r3n** [comment]
can you check that there is a process listening on port 5000 when you start the conductor UI?

**Comment by ajayaks** [comment]
nopes, its not running on 5000 port.

**Comment by v1r3n** [comment]
Can you share the error logs from UI along with screenshot?

**Comment by ajayaks** [comment]
I am seeing any error but UI is not coming.


When i run UI "node dist/server.js" , its showing below but not showing "Server is online" and not automatically opening a new browser tab. I tried to open it manually at 3000 and 5000 but not working.
http://localhost:3000/#/
http://localhost:5000/#/

I have already setup the WF_SERVER

{"name":"Conductor UI","hostname":"Ajays-MacBook-Pro.local","pid":97255,"level":30,"msg":"Serving static /Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui","time":"2017-02-13T20:01:23.043Z","src":{"file":"/Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/dist/webpack:/src/server.js","line":13,"func":"canUseDOM"},"v":0}
{"name":"Conductor UI","hostname":"Ajays-MacBook-Pro.local","pid":97255,"level":30,"msg":"Workflow UI listening at http://:::5000","time":"2017-02-13T20:01:23.112Z","src":{"file":"/Users/ajay/OfficeWork/Office_Code/ECMS_Conductor/conductor/ui/dist/webpack:/src/server.js","line":22},"v":0}

**Comment by ajayaks** [comment]
Hi Viren , any update on this?

**Comment by v1r3n** [comment]
@ajayaks can you share the screenshot?  Also, can you confirm if there is a process running on port 5000?

One more thing, when you do export WF_SERVER, ensure it ends with a ```/```.
e.g. from the ui directory:

```shell
npm install
gulp build
cd dist
WF_SERVER=http://localhost:8080/api/; node server.js
```

Please send screenshot and your OS version.

**Comment by ajayaks** [comment]
Correct , i was missing the "/" in last , working fine now.
