### ISSUE TITLE
Register the Conductor with Eureka

### ISSUE THREAD

**Issue by dileepkeely** [Netflix/conductor#700]
Please let me know how do I register the conductor server to  EurekaDiscovery server.
Question1: In which class of the conductor code do I need to mark the class as @EnableDiscoveryClient.
Question2: Once registered with eureakdiscovery server how should the WORKER need to poll.

**Comment by josedab** [comment]
@dileepkeely I believe `@EnableDiscoveryClient` is a spring annotation. I am not aware of the use of a similar annotation for the guice framework.
There is already an integration with the eureka client. You can see more on `WorkflowTaskCoordinator`
