### ISSUE TITLE
JSON workflow DSL

### ISSUE THREAD

**Issue by dileepkeely** [Netflix/conductor#701]
Please suggest:
Referring to kitchen sink example, I came to know that the WORKFLOW tht we define as a JSON i.e "kitchensink.json" is implemented in ConductorServer.java like below:
```
InputStream stream = Main.class.getResourceAsStream("/kitchensink.json");
		client.resource("http://localhost:" + port + "/api/metadata/workflow").type(MediaType.APPLICATION_JSON).post(stream);
```
Please let me know for a PRODUCTION environment, where should we define and use the JSON workflow DSL.

**Comment by josedab** [comment]
@dileepkeely That code is getting the data from the `kitchensink.json` file and calling the api to register the workflow definition.
In production you could do the same using the client within the project or through curl. The `kitchensink.json` file is a valid workflow definition so you could use it there as well.

I don't recommend to load the sample in production as part of the starting process though, as the population of metadata would be something you do separately.
Does it help?

**Comment by apanicker-nflx** [comment]
Thanks @josedab for your response.
@dileepkeely As suggested, the kitchensink workflow is meant to be used as an example only. For production flows, please use the metadata APIs [here](https://netflix.github.io/conductor/apispec/#task-workflow-metadata) to register your JSON-DSL based workflow and task blueprints with the conductor server.
