### ISSUE TITLE
Running UI from docker-compose failed

### ISSUE THREAD

**Issue by HardiChandra** [Netflix/conductor#702]
Hi, 

I am running docker-compose up and when I tried to access localhost:5000 
I got "The site can't be reached message" I tried to dig in to the log and find this 

```
conductor-ui_1      | internal/modules/cjs/loader.js:583
conductor-ui_1      |     throw err;
conductor-ui_1      |     ^
conductor-ui_1      | 
conductor-ui_1      | Error: Cannot find module '/app/ui/dist/server.js'
conductor-ui_1      |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
conductor-ui_1      |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
conductor-ui_1      |     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
conductor-ui_1      |     at startup (internal/bootstrap/node.js:266:19)
conductor-ui_1      |     at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

Did I miss any steps? Thank you in advance

**Comment by zmzhy20090101** [comment]
1. in docker\ui\Dockerfile , remove
(# Get and install conductor UI
RUN cd /app/ui \
  && npm install \
  && npm run build --server)

2. then pack locally ,  (npm install  && npm run build --server) 
retry docker-compose build, this's my way, I hope it will help you

**Comment by HardiChandraTW** [comment]
Hmm, doesn't seem to be the best solution. But it worked.
Thank you very much @zmzhy20090101 👻

**Comment by HardiChandra** [comment]
Not the best solution I believe, but this work..
Thank you very much @zmzhy20090101 👻

**Comment by anshumanr** [comment]
I did not know how to get into those logs or how to `pack locally` so I changed the line
`&& npm install \`
to
`&& npm install --no-shrinkwrap --update-binary \`
This worked for me.

**Comment by sreedharguda** [comment]
Please help me on the docker file for conductor ui app.
