### ISSUE TITLE
Tool for modeling workflow

### ISSUE THREAD

**Issue by ZakariaAmri** [Netflix/conductor#707]
We are presently working on worflow management, and Conductor happens to be of a great help concerning the orchestration of our tasks. However we'd like to use a proper interface so an average user could use it. Your solution does not provide such a tool, therefore we wondered it there is currently people working on it ? Are you using a particular software to get round this lack ? And have you ever think about [Node-RED](https://github.com/node-red/node-red) to supplement your microservice engine ?

**Comment by apanicker-nflx** [comment]
@ZakariaAmri Currently, we do not have a UI tool to help with modeling workflows. However, this is a long-term goal and we would welcome any contributions from the community in this regard.
