### ISSUE TITLE
[Question]Is there a problem using repeatable workflows?

### ISSUE THREAD

**Issue by manudilipshah** [Netflix/conductor#719]
I am using repeatable workflows in the following way

{
   "name":"restartWorkflow",
   "version":1,
   "tasks":[
      {
         "name":"configureTTL",
         "taskReferenceName":"configureTTL",
         "type":"configureTTL",
         "inputParameters": {
        	"ttl": "${workflow.input.ttl}"
    	 },
         "startDelay":0
      },
      {
         "name":"waitForTTLExpiry",
         "taskReferenceName":"waitForTTLExpiry",
         "type":"waitForTTLExpiry",
         "inputParameters": {
        	"frequency": "${workflow.input.frequency}"
    	 },
         "startDelay":0
      },
{
         "name":"restartWorkflow",
         "taskReferenceName":"restartWorkflow",
         "inputParameters":{
            "http_request":{
            	"uri" :"http://<endpoint to create workflow API>",
            	"method" : "POST",
            	"body" : "${workflow.input}",
            }
         },
         "type":"HTTP",
         "startDelay":0
      }
   ],
   "schemaVersion":2
}

It works fine.Will this create some issues going forward?

**Comment by apanicker-nflx** [comment]
@manudilipshah In the example above, you are not really using repeatable workflows (I am assuming you mean recursive/re-entrant). Although the name `restartWorkflow` is re-used. The first `name` field is the name of the workflow. However, the second `name` field is the name of the task and these are mutually exclusive. This should not create any issues.
