### ISSUE TITLE
Conductor as eureka client

### ISSUE THREAD

**Issue by ajayaks** [Netflix/conductor#72]
Hi, 

I have done some code changes to start conductor service as eureka client so that all other spring boot micro services can be used as a work tasks.

I want to know is it required for me to upload the code changes or we would have this feature in coming releases. I don't to do local merge everytime i download the latest code. Please suggest.

Regards
Ajay

**Comment by v1r3n** [comment]
Can you share the changes you have made to register conductor with Eureka?
We might be able to add it to the main branch if the solution will work for everyone.

**Comment by ajayaks** [comment]
Sure, how should i share the code change?  Via pushing on dev branch or somewhere else?

**Comment by v1r3n** [comment]
fork conductor to your personal repo and commit changes.
