### ISSUE TITLE
Assigning task to Worker Thread : Confusion regarding how Worker task executes and update status to Conductor.

### ISSUE THREAD

**Issue by MohneeshParkhi** [Netflix/conductor#720]
Hi, I am experimenting with Netflix's Conductor and bugged with a doubt into mine brain which keeps me ping all time, can anybody help to resolve this one:

There is execute() method within worker interface, now doubts:
a)Should i overload it to update a task status or write a whole task like reading file or insert value in database and then update the status.
b) Should i design an application which calls execute() method of worker interface to read a file. Am i Right or wrong here ? If Wrong, then how i can read a file using Conductor's task ?
   
Or I have another vision, Any process like reading a file or inserting value in database is executes via Java
application, then after getting a success based response say an positive returned integer value, i send the JSON for updating the Task Status. That's it.

In aforesaid case, how Conductor controls the workflow ?

Need to understand a Workflow between Client application and Conductor Server ?

**Comment by jkaipa** [comment]
This is what I understood.
You can have multiple workers running on the same machines which has the ability to execute specific task definition name.
Ex. If you have a task definition name as MoveFiles, You can have multiple workers running on the same machine to listen to MoveFiles related tasks in the queue. The WorkflowTaskCoordinator would schedule the MoveFiles tasks among these workers.

Look at the Main.java and SampleWorker.java. You will have the workers running in your machine always (assuming the conductor is running in a different machine). 
		Worker worker1 = new SampleWorker("MoveFiles");
		Worker worker2 = new SampleWorker("MoveFiles");
		Worker worker3 = new SampleWorker("MoveFiles");
		//Create WorkflowTaskCoordinator
		WorkflowTaskCoordinator.Builder builder = new WorkflowTaskCoordinator.Builder();
		WorkflowTaskCoordinator coordinator = builder.withWorkers(worker1, worker2, worker3).withThreadCount(threadCount).withTaskClient(taskClient).build();
 Your SampleWorker.java is specific to MoveFiles and have all intelligence to accomplish that task. i.e the execute method of SampleWorker will extract inputs from the task object and does what you need to do then update the status as completed.

I think this add a bit to your understanding. Sorry if confusion is increased.

**Comment by apanicker-nflx** [comment]
Thanks @jkaipa for the response.
@MohneeshParkhi Please refer the documentation [here](https://netflix.github.io/conductor/gettingstarted/client/#worker) to learn more about how to implement your worker.
