### ISSUE TITLE
How to create a task and workflow for uploading a file from your path.

### ISSUE THREAD

**Issue by amitprakash30** [Netflix/conductor#721]
Could you please provide a sample workflow json.

**Comment by amitprakash30** [comment]
@v1r3n Could you please provide a way to upload a file in a task within a workflow .Also can you also provide a way to do it programatically

**Comment by APrakash1989** [comment]
Can anyone please update on this @v1r3n  ? We are stuck at this point and we need a help on this .Please reply

**Comment by saidatta** [comment]
Should be straightforward unless I misunderstood the question.

- Register a simple workflow and task with conductor
- Implement your worker code base that uploads the file.
- Use the task polling capabilities to register that code base to the associated Registered task
- Then, execute that task poller.

**Comment by apanicker-nflx** [comment]
Thanks @saidatta for your response.
@amitprakash30 @APrakash1989 Please refer the documentation [here](https://netflix.github.io/conductor/) to learn more about how to create tasks and workflows.
Please go through the [beginner labs](https://netflix.github.io/conductor/labs/beginner/) to get a quick feel about how conductor can be used in your use-case.
