### ISSUE TITLE
How to make subworkflow optional?

### ISSUE THREAD

**Issue by animagus32** [Netflix/conductor#731]
I'm using dynamic fork join task . The task forks into 2 subworkflow , but if one subworkflow fails ,the origin workflow failed too,  despite i have set the "optional=true" for each subworkflow

**Comment by animagus32** [comment]
sorry  it worked

**Comment by swarooppradhan** [comment]
I am having same issue.. may be i'm missing something.
I have set optional as true on dynamic task for each subworkflow but if one subworkflow fails, the original workflow fails too. I am using version 1.12.3

**Comment by muffadal53** [comment]
@animagus32 : Can you please share an example workflow showing where all do we need to set "optional=true" if we are using "FORK_JOIN_DYNAMIC" and "JOIN" with forked subworkflows to avoid "if one subworkflow fails ,then origin workflow also fails."

Regards.
