### ISSUE TITLE
How to set reason when using failureWorkflow ?

### ISSUE THREAD

**Issue by animagus32** [Netflix/conductor#732]
i'm using failureWorkflow to manage workflow failure, but the reason of failureWorkflow is always null . How to set this ?

**Comment by APrakash1989** [comment]
Could you please help me how to create a workflow for uploading a file using an endpoint if you have used anything like this .

**Comment by apanicker-nflx** [comment]
@animagus32 The `reason` that is passed as input to the `failureWorkflow` is the reasonForIncompletion which is set on the task whose failure caused the workflow to fail.

@APrakash1989 Please open a new issue detailing your use-case and the issue that you are running into. Also please go through the documentation [here](https://netflix.github.io/conductor/) to learn more about how to use conductor for your use-cases.
