### ISSUE TITLE
Excuting "gulp watch" error!

### ISSUE THREAD

**Issue by FreeceLian** [Netflix/conductor#74]
**OS :        Windows7 64bit
Branch :  dev**

**I enter ui and do "npm install" then get two WARN:**
`D:\MyWorkSet\Github\conductor\ui>npm install`
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):`
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})`

**then "gulp watch" error:**
`D:\MyWorkSet\Github\conductor\ui>gulp watch`
`[14:36:57] Requiring external module babel-register`
`[14:37:17] Using gulpfile D:\MyWorkSet\Github\conductor\ui\gulpfile.babel.js`
`[14:37:17] Starting 'watch'...`
`[14:37:17] Starting 'clean'...`
`[14:37:17] Finished 'clean' after 12 ms`
`[14:37:17] Starting 'set-env'...`
`[14:37:17] Finished 'set-env' after 4.73 ms`
`[14:37:17] Starting 'serve'...`
`Stats : undefined`
`[14:37:17] Starting 'watchTask'...`
`[14:37:17] Finished 'watchTask' after 99 ms`
`[14:37:17] Starting 'public'...`
`[14:37:17] Finished 'public' after 13 ms`
`[14:37:17] Starting 'styles'...`
`[14:37:17] Finished 'styles' after 9.82 ms`
`[14:37:17] Starting 'fonts'...`
`[14:37:17] Finished 'fonts' after 1.67 ms`
`[14:37:17] Starting 'lint'...`
`[14:37:18] Finished 'lint' after 317 ms`
`[14:37:18] Starting 'images'...`
`[14:37:18] Finished 'images' after 2.8 ms`

`events.js:160`
`      throw er; // Unhandled 'error' event`
`      ^`
`Error: spawn D:\MyWorkSet\Github\conductor\ui\node_modules\optipng-bin\vendor\optipng.exe` `ENOENT`
`    at exports._errnoException (util.js:1022:11)`
`    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)`
`    at onErrorNT (internal/child_process.js:359:16)`
`    at _combinedTickCallback (internal/process/next_tick.js:74:11)`
`    at process._tickCallback (internal/process/next_tick.js:98:9)`

_Maybe conductor doesn't supports Win7?_

**Comment by v1r3n** [comment]
what version of node and npm are you running?

**Comment by FreeceLian** [comment]
@v1r3n 

`C:\Users>node -v`
`v6.9.5`

`C:\Users>npm -v`
`3.10.10`

**Comment by v1r3n** [comment]
@FreeceLian node and npm versions are fine.  Do you have access to Linux, Mac or later versions of Windows where you can try this out?  I will have to get hold of a win 7 machine to try this out.

**Comment by FreeceLian** [comment]
@v1r3n OK , I'll try this at CentOS Linux 7.2 . But I think maybe using docker is a better way? BTW,my own work PC is Win7(cannot change...) and cannot support docker.... so I hope the problem can be solved.

**Comment by niwy** [comment]
Met the same problem on Win 7, and I'm a corporate proxy.

I tried to install pngopt-bin, but getting the following errors. I'm not sure the problem is related to proxy, since most modules can be well installed.

`D:\workspace\java\conductor\ui>npm install --save optipng-bin

> optipng-bin@3.1.2 postinstall D:\workspace\java\conductor\ui\node_modules\opti
png-bin
> node lib/install.js

  ‼ tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 3128
3128:80
  ‼ optipng pre-build test failed
  i compiling from source
  × RequestError: tunneling socket could not be established, cause=getaddrinfo
ENOTFOUND 3128 3128:80
    at ClientRequest.<anonymous> (D:\workspace\java\conductor\ui\node_modules\go
t\index.js:74:21)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at ClientRequest.onError (D:\workspace\java\conductor\ui\node_modules\tunnel
-agent\index.js:178:21)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
nf-workflow-ui@1.0.0 D:\workspace\java\conductor\ui
`-- optipng-bin@3.1.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})`

**Comment by v1r3n** [comment]
@FreeceLian @niwy any chance you can try this outside the corporate network and possibly on a *nix machine?

**Comment by FreeceLian** [comment]
@v1r3n I'm afraid not.I can only try it on a Win7 machine with free network or other OS machines with corporate proxy.  Now I'm trying it on a CentOS machine , but i meet the certification problem because gradle doesn't support NTLM proxy well.

**Comment by v1r3n** [comment]
@FreeceLian @niwy some related discussion on the similar error, might be helpful:

https://github.com/npm/npm/issues/3354
http://stackoverflow.com/questions/33162560/error-tunneling-socket-could-not-be-established-cause-connect-econnrefused-10

**Comment by niwy** [comment]
@v1r3n Thanks for the reference link. I have tried many configuration methods to set proxy, however none of them could solve the "gulp watch" problem. I will test the UI server at home without proxy later.

**Comment by FreeceLian** [comment]
@v1r3n Thanks. But my problem isn't the npm proxy setting.  I can always keep my network active in my Win7 machine, but meet the "gulp watch" problem. Or i can use a CentOS machine behind proxy, i'm sure the network is connected, but i meet the gradle problem:"unable to find valid certification path to requested target". I think my npm is fine because i can do the "npm install".

**Comment by FreeceLian** [comment]
@v1r3n Now I have solved the proxy problem and try it at CentOS 7.2 but meet the same problem as Win7. I wonder if i get a wrong step :

1. `git clone git@github.com:Netflix/conductor.git`
2. modify conductor/gradle/wrapper/gradle-wrapper.properties 
    `distributionUrl=gradle-2.14.1-bin.zip`
    because I use a modified gradle to replace the original one due to the proxy problem
3. `cd server`
    `../gradlew server`
   It works.
   `8044 [main] INFO  com.netflix.conductor.server.ConductorServer  - Kitchen sink workflows are created!`
4. install node 
    `[root@SZX1000138239 wrapper]# node -v`
    `v6.10.0`
5. `cd ui`
    `npm install`
    get a lot of WARNs during the install
    `npm WARN deprecated node-uuid@1.4.7: use uuid module instead`
    `npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
    `npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
    `npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.`
    `npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.`
    `npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade`
    `npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
    `npm WARN prefer global marked@0.3.6 should be installed with -g`
    
    After the install , execute `npm install` again, it shows
    `npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):`
    `npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`
6. install gulp: `npm install gulp -g`
    some WARNs:
    `npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
    `npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
    `npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.`
    
    After the install, execute `gulp -v`   (dir: conductor/ui)
    `[17:00:30] Requiring external module babel-register`
    `[17:00:30] CLI version 3.9.1`
    `[17:00:30] Local version 3.9.1`
7. `gulp watch`
    Then I get the completely same error as Win7.

**Comment by cquon** [comment]
Running into a similar error.  I am running Centos7.  I have had to manually install many of the dependencies with npm.  Finally after all dependency errors were no longer being thrown:

$ node -v
v7.6.0
$ npm -v
4.1.2

$ gulp watch
[13:41:08] Requiring external module babel-register
process.argv =====>  [ '/usr/local/bin/node', '/bin/gulp', 'watch' ]
DEBUG =====>  true
WATCH =====>  true
[13:41:13] Using gulpfile ~/Development/conductor/conductor/ui/gulpfile.babel.js
[13:41:13] Starting 'watch'...
[13:41:13] Starting 'clean'...
[13:41:13] Finished 'clean' after 12 ms
[13:41:13] Starting 'set-env'...
[13:41:13] Finished 'set-env' after 4.01 ms
[13:41:13] Starting 'serve'...
Stats : undefined
[13:41:13] Starting 'watchTask'...
[13:41:13] Finished 'watchTask' after 25 ms
[13:41:13] Starting 'public'...
[13:41:13] Finished 'public' after 8.35 ms
[13:41:13] Starting 'styles'...
[13:41:13] Finished 'styles' after 4.97 ms
[13:41:13] Starting 'fonts'...
[13:41:13] Finished 'fonts' after 1.24 ms
[13:41:13] Starting 'lint'...
[13:41:13] Finished 'lint' after 18 ms
[13:41:13] Starting 'images'...
[13:41:13] Finished 'images' after 1.55 ms
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1028:11)
    at WriteWrap.afterWrite (net.js:804:14)

**Comment by v1r3n** [comment]
@FreeceLian @cquon can you try ```npm install browser-sync``` and then try again?  I was able to reproduce this once on a container.  If that works for you, will try to fix it.

**Comment by FreeceLian** [comment]
@v1r3n 
`[root@SZX1000138239 ui]# npm install browser-sync`
`npm WARN deprecated node-uuid@1.4.7: use uuid module instead`
`nf-workflow-ui@1.0.0 /opt/conductor/ui`
`└─┬ browser-sync@2.18.8`
`  └─┬ localtunnel@1.8.2`
`    └─┬ request@2.78.0`
`      ├─┬ http-signature@1.1.1`
`      │ └── sshpk@1.11.0`
`      └── qs@6.3.2`

`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):`
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

After this, execute `gulp watch`, the error is still the same.

**Comment by cquon** [comment]
Same for me as well

$ npm install --save-dev browser-sync
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
nf-workflow-ui@1.0.0 /home/cquon/Development/conductor/conductor/ui
\u2514\u2500\u252c browser-sync@2.18.8 
  \u2514\u2500\u252c localtunnel@1.8.2
    \u2514\u2500\u252c request@2.78.0
      \u2514\u2500\u2500 qs@6.3.2 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[cquon@coreycentos7 ui]$ gulp watch
[11:18:39] Requiring external module babel-register
process.argv =====>  [ '/usr/local/bin/node', '/bin/gulp', 'watch' ]
DEBUG =====>  true
WATCH =====>  true
[11:18:44] Using gulpfile ~/Development/conductor/conductor/ui/gulpfile.babel.js
[11:18:44] Starting 'watch'...
[11:18:44] Starting 'clean'...
[11:18:44] Finished 'clean' after 8.53 ms
[11:18:44] Starting 'set-env'...
[11:18:44] Finished 'set-env' after 2.12 ms
[11:18:44] Starting 'serve'...
Stats : undefined
[11:18:44] Starting 'watchTask'...
[11:18:44] Finished 'watchTask' after 30 ms
[11:18:44] Starting 'public'...
[11:18:44] Finished 'public' after 9.7 ms
[11:18:44] Starting 'styles'...
[11:18:44] Finished 'styles' after 5.72 ms
[11:18:44] Starting 'fonts'...
[11:18:44] Finished 'fonts' after 1.39 ms
[11:18:44] Starting 'lint'...
[11:18:44] Finished 'lint' after 26 ms
[11:18:44] Starting 'images'...
[11:18:44] Finished 'images' after 1.53 ms
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1028:11)
    at WriteWrap.afterWrite (net.js:804:14)

**Comment by chetan3434** [comment]
Running into similar error on executing `docker-compose build` command.
Is there any fix/workaround for this issue?

**Comment by dcompgriff** [comment]
I'm running into the same issue with the ui docker container. I'll note that I am also behind a corporate proxy.

**Comment by rmotapar** [comment]
We are running to the same error. Any resolution or workaround? Thanks!

[10:21:13] Finished 'images' after 1.51 ms

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn C:\dev\garnet\netflix\conductor\ui\node_modules\optipng-bin\vendor\optipng.exe ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by marc-christian-schulze** [comment]
For me it was simply the missing libpng on my Ubuntu box.
So installing libpng-dev solved the issue for me.
