### ISSUE TITLE
Getting started documentation is incorrect

### ISSUE THREAD

**Issue by stephen-kruger** [Netflix/conductor#741]
It seems there is step missing (from https://netflix.github.io/conductor/intro/) to actually install the deps : 

Workspaces/conductor>cd ui
conductor/ui>gulp watch
[11:53:09] Failed to load external module @babel/register
[11:53:09] Failed to load external module babel-register
[11:53:09] Failed to load external module babel-core/register
[11:53:09] Failed to load external module babel/register
[11:53:09] Local gulp not found in ~/Workspaces/conductor/ui
[11:53:09] Try running: npm install gulp
conductor/ui>

**Comment by jvemugunta** [comment]
try 
npm run watch

**Comment by stephen-kruger** [comment]
Shows same behaviour as gulp watch.
UI loads on port 3000 but has fatal console errors: 
1)GET http://localhost:3000/js/app.js net::ERR_ABORTED 404 (Not Found)
2)Refused to execute script from 'http://localhost:3000/js/app.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
3)GET http://localhost:3000/fonts/sourcesanspro.woff net::ERR_ABORTED 404 (Not Found)

**Comment by apanicker-nflx** [comment]
The documentation should be fixed now. Please refer [this](https://netflix.github.io/conductor/server/#3-use-the-pre-configured-docker-image) to start the server in a docker container and access the UI.
