### ISSUE TITLE
Publishing release notes / changelogs?

### ISSUE THREAD

**Issue by Jiehong** [Netflix/conductor#752]
Migrating from 1.10.x to 1.11.x, I'm unable to find a release note with changes, and what to expect, how to migrate.

The file named `CHANGELOG.md` is empty, and has an initial commit set 2 years ago.

Would it be possible to better handle the releasing process and communication?

**Comment by apanicker-nflx** [comment]
@Jiehong Thank you for the feedback. We have started adding [release notes](https://github.com/Netflix/conductor/releases) recently. Also, the documentation has been updated to reflect the new features and fields and we will be more careful and diligent about these going forward.

**Comment by Jiehong** [comment]
@apanicker-nflx : thanks!
