### ISSUE TITLE
No API to remove a workflow?

### ISSUE THREAD

**Issue by stephen-kruger** [Netflix/conductor#758]
I have created a new workflow using http://localhost:8080/api/metadata/workflow/

However trying to delete it (using http://localhost:8080/api/workflow/encode_and_deploy/remove or http://localhost:8080/api/workflow/encode_and_deploy

shows the error: "No such workflow found by id: encode_and_deploy"
The problem is, workflows are not referenced by an id, they only have a name, so how are we supposed to delete it?

For example the call to http://localhost:8080/api/metadata/workflow lists: 

{"createTime": 1536554348263,
        "name": "encode_and_deploy",
        "description": "Encodes a file and deploys to CDN",
        "version": 1,
        "tasks": [ ....

**Comment by saidatta** [comment]
you cannot use the name as a standalone identifier for referencing a workflow.

When you start a workflow a GUID is generated, which you can leverage for doing any actions on it.
You can also retrieve all running workflows, and filter through them.
You can also leverage the corelation-id

https://netflix.github.io/conductor/runtime/

**Comment by saidatta** [comment]
Might be helpful

https://github.com/Netflix/conductor/pull/679

**Comment by apanicker-nflx** [comment]
Thanks @saidatta for providing the answer.
