### ISSUE TITLE
Response of api updating a task has been changed.

### ISSUE THREAD

**Issue by shouhei** [Netflix/conductor#764]
After [this commit](https://github.com/Netflix/conductor/commit/ae403c9a0a43b7a525dcf0012fc9b080cf44ba8e#diff-7143b9a69e2e1c1c9127eada224a0920L147), Response of api updating a task  has changed from json string  to plain text string. In its impact python example script `kitchensink_workers.py` has been raising some exceptions.  This change has intend ?

before:

> "7efe673f-0c3c-4f60-bdd5-b4d17590d093"

after:

> 7efe673f-0c3c-4f60-bdd5-b4d17590d093

**Comment by kishorebanala** [comment]
Apologies for the inconvenience. We use Java client, and Python client is completely managed by the community. Hence, it's really hard for us to track breaking changes in Python client. We'll be more careful in reviewing breaking changes hereon. But, please feel free to send a PR with patch if something has to be fixed immediately.
