### ISSUE TITLE
How to specify "Callback After" attribute of a task executes on a Dynamic Fork

### ISSUE THREAD

**Issue by kchaturanga** [Netflix/conductor#767]
I have a dynamic fork 

Is it possible to spacify "Callback After" in "somename_activity_1" and "somename_activity_2" 

```

{
  "inputParameters": {
     "dynamicTasks": "${taskA.output.dynamicTasksJSON}",
     "dynamicTasksInput": "${taskA.output.dynamicTasksInputJSON}"
  }
  "type": "FORK_JOIN_DYNAMIC",
  "dynamicForkTasksParam": "dynamicTasks",
  "dynamicForkTasksInputParamName": "dynamicTasksInput"
}

```

```

{
  "dynamicTasksInputJSON": {
    "somename_thirdparty_activity_10003_01": {
      "width": 100,
      "height": 100,
      "params": {
        "recipe": "jpg"
      }
    },
    "somename_thirdparty_activity_10003_02": {
      "width": 200,
      "height": 200,
      "params": {
        "recipe": "jpg"
      }
    }
  },
  "dynamicTasksJSON": [
     { 
                           "name": "somename_activity_1",
                           "taskReferenceName": "somename_thirdparty_activity_10003_01",
                           "type": "HTTP",
                           "inputParameters": {
                              "http_request": {
                                 "method": "POST",
                                 "body": "${somename_thirdparty_activity_10003.input}",
                                 "uri": "${workflow.input.urls.somename}"
                              }
                           }
                        },
     { 
                           "name": "somename_activity_2",
                           "taskReferenceName": "somename_thirdparty_activity_10003_02",
                           "type": "HTTP",
                           "inputParameters": {
                              "http_request": {
                                 "method": "POST",
                                 "body": "${somename_thirdparty_activity_10003.input}",
                                 "uri": "${workflow.input.urls.somename}"
                              }
                           }
                        }
  ]
}
```

**Comment by apanicker-nflx** [comment]
@kchaturanga The tasks `somename_activity_1` and `somename_activity_2` are HTTP tasks, which effectively mean that they are [system tasks](https://netflix.github.io/conductor/configuration/systask/#http). System tasks are executed within the conductor server and the server manages the complete lifecycle of such tasks and `callbackAfterSeconds` cannot be set on such tasks.
If you were to implement this as a SIMPLE task, then you could set this value in the `TaskResult` that is sent back from your worker when you update the task.

**Comment by kchaturanga** [comment]
> @kchaturanga The tasks `somename_activity_1` and `somename_activity_2` are HTTP tasks, which effectively mean that they are [system tasks](https://netflix.github.io/conductor/configuration/systask/#http). System tasks are executed within the conductor server and the server manages the complete lifecycle of such tasks and `callbackAfterSeconds` cannot be set on such tasks.
> If you were to implement this as a SIMPLE task, then you could set this value in the `TaskResult` that is sent back from your worker when you update the task. You can refer the documentation [here](https://netflix.github.io/conductor/faq/#how-do-you-schedule-a-task-to-be-put-in-the-queue-after-some-time-eg-1-hour-1-day-etc) to achieve this.

Thank you :) ..
