### ISSUE TITLE
MASSL / 2-way Certificate Authentication support for Netflix Conductor

### ISSUE THREAD

**Issue by rajeshik** [Netflix/conductor#769]
It looks like Netflix Conductor can perform Basic Authentication.
Can Netflix Conductor support MASSL / 2-way Certificate Authentication or OAuth 2.0 Authentication.

**Comment by picaron** [comment]
for HTTP tasks, it currently supports only basic auth or [2-legged OAuth 1.0](https://github.com/Netflix/conductor/blob/master/contribs/src/main/java/com/netflix/conductor/contribs/http/HttpTask.java#L153)

**Comment by apanicker-nflx** [comment]
@picaron Thanks for your response.
@rajeshik Currently, only the basic authentication (OAuth 1.0) is supported. Please feel free to make a contribution for OAuth 2.0 authentication support.
