### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by RogerDunn** [Netflix/conductor#77]
Following the instructions for installing and running (from https://netflix.github.io/conductor/intro/), I've cloned the repo to a new clean directory, and run ../gradlew server from the server directory (running from Terminal on a MacOS Sierra box (10.12.3).  I'm seeing an issue that appears to be related to nebula, issue appears building either from dev or master branches: "Publication nebula not found in project".

Is there something I need to configure locally in order for the build to succeed?

Thank you!

_[...gradlew output begins with downloading a series of pom and jar files, followed by the nebula_ related error:]
Inferred project: conductor, version: 1.6.2-SNAPSHOT
Download https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/1.2.4/shadow-1.2.4.pom
Download https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/1.2.4/shadow-1.2.4.jar
Publication nebula not found in project :.
[buildinfo] Not using buildInfo properties file for this build.
Publication named 'shadow' does not exist for project ':conductor-common' in task ':conductor-common:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':' in task ':artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-test-harness' in task ':conductor-test-harness:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-redis-persistence' in task ':conductor-redis-persistence:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-jersey' in task ':conductor-jersey:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-ui' in task ':conductor-ui:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-core' in task ':conductor-core:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-client' in task ':conductor-client:artifactoryPublish'.
Publication named 'shadow' does not exist for project ':conductor-contribs' in task ':conductor-contribs:artifactoryPublish'.
:conductor-common:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conductor-common:compileJava'.
> invalid source release: 1.8

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by v1r3n** [comment]
What version of java are you running with?
I see this in your logs:

```invalid source release: 1.8```  

Conductor will need JDK 1.8 to build.

**Comment by RogerDunn** [comment]
Doh!  Thank you - I had switched to an alternate Mac and failed to notice the difference in the bash profile.  Yup, JAVA_HOME was pointing at 1.7, not 1.8 - thank you for the speedy help.
