### ISSUE TITLE
Conductor docker image in docker hub

### ISSUE THREAD

**Issue by preeth-gopalakrishnan** [Netflix/conductor#770]
Hi,
Currently there is no public docker image in the docker hub under the 
https://hub.docker.com/u/netflixoss/.
Are there any plans to publish this here?

thanks

**Comment by saidatta** [comment]
I agree. Though, have you checked out the docker-compose.yaml file within the repo?

**Comment by LiranBri** [comment]
+1

**Comment by apanicker-nflx** [comment]
Currently there are no plans (in the short-term future) to publish the conductor docker image to docker hub. However, as @saidatta mentioned you can create your own docker image from the docker folder.

**Comment by vikas1389** [comment]
Docker-compose gives error - it doesnt download depedencies well.

**Comment by vikas1389** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':conductor-server'.
> Could not resolve all dependencies for configuration ':conductor-server:runtimeCopy'.
   > Could not resolve com.netflix.runtime:health-api:1.1.+.
     Required by:
         project :conductor-server > project :conductor-jersey
         project :conductor-server > project :conductor-grpc-server > project :conductor-grpc
      > Failed to list versions for com.netflix.runtime:health-api.
         > Could not list versions using M2 pattern 'https://dl.bintray.com/netflixoss/oss-candidate/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier])(.[ext])'.
            > Could not get resource 'https://dl.bintray.com/netflixoss/oss-candidate/com/netflix/runtime/health-api/'.
               > Could not GET 'https://dl.bintray.com/netflixoss/oss-candidate/com/netflix/runtime/health-api/'. Received status code 504 from server: Gateway Time-out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3m 3s
ERROR: Service 'conductor-server' failed to build: The command '/bin/sh -c ./gradlew build -x test' returned a non-zero code: 1

**Comment by ntk148v** [comment]
Hi folks,

I've published Conductor images to Docker Hub:
- https://hub.docker.com/r/kiennt26/netflix-conductor-ui
- https://hub.docker.com/r/kiennt26/netflix-conductor-server
- https://hub.docker.com/r/kiennt26/netflix-conductor-aio

Build script and sample compose files are available here:
https://github.com/ntk148v/dockerfiles/tree/master/conductor
