### ISSUE TITLE
Wrong error message when resuming a non-paused workflow

### ISSUE THREAD

**Issue by Jiehong** [Netflix/conductor#773]
The code test for non-paused status, but the message says "is PAUSED":

https://github.com/Netflix/conductor/blob/809be627b9aa4f9c7901fb289abe2840f6885f86/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L655

**Comment by apanicker-nflx** [comment]
Thanks for pointing it out. Should be fixed now.
