### ISSUE TITLE
docs: base_url is not defined

### ISSUE THREAD

**Issue by panthony** [Netflix/conductor#775]
Hi,

There is the following javascript error on the documentation site:

> ReferenceError: base_url is not defined (search.js:2)

```js
require.config({
   baseUrl: base_url + "/search/"
});
```

Which break the [search functionality](https://netflix.github.io/conductor/search.html?q=task) of the documentation.

**Comment by kishorebanala** [comment]
@panthony Thanks for pointing this out. We'll update base_url to avail search functionality.

**Comment by apanicker-nflx** [comment]
@panthony Thanks for the feedback. We have updated the documentation and fixed the issue.
