### ISSUE TITLE
No Heartbeat / Failover?

### ISSUE THREAD

**Issue by panthony** [Netflix/conductor#776]
Hi there,

Similar to #162, I tried to see how conductor would behave if a worker just died, for this I created a simple worker that I killed right after starting the workflow.

Conductor would not see that the worker died and would still show the task as being "in progress", restarting the worker would not pick the task back either.

The closest thing that I found to an heart beat is `responseTimeoutSeconds` but I failed to make it works or understand how it works.

I cannot use the "timeoutSeconds" feature because a same task could take few seconds to few weeks depending on its input.

Is there a way for conductor to take back a task if the associated worker does not show any sign of life anymore ?

Any pointer would be greatly appreciated.

Here's the used config:

**workflow**
```json
{
  "name": "test_heartbeat_workflow",
  "version": 1,
  "tasks": [

      {
        "name": "test_heartbeat",
        "taskReferenceName": "test_heartbeat",
        "type": "SIMPLE"
      }
  ],
  "schemaVersion": 2
}
```

**taskDef**
```
[
  {
    "name": "test_heartbeat",
    "retryCount": 50,
    "timeoutSeconds": 0,
    "inputKeys": [
    ],
    "timeoutPolicy": "RETRY",
    "retryLogic": "FIXED",
    "retryDelaySeconds": 5,
    "responseTimeoutSeconds": 5
  }
]
```

**worker**
```java
package com.oncrawl.analysis.conductor;

import com.netflix.conductor.client.worker.Worker;
import com.netflix.conductor.common.metadata.tasks.Task;
import com.netflix.conductor.common.metadata.tasks.TaskResult;

import java.util.concurrent.TimeUnit;

public class SampleWorker implements Worker {

  @Override
  public String getTaskDefName() {
    return "test_heartbeat";
  }

  @Override
  public TaskResult execute(Task task) {
    System.out.println("executing " + getTaskDefName());

    try {
      Thread.sleep(TimeUnit.MINUTES.toMillis(5L));
    } catch (InterruptedException e) {
      e.printStackTrace();
    }

    return new TaskResult(task);
  }
}

```

**Comment by panthony** [comment]
Adding the "WorkflowSweeper" (https://github.com/Netflix/conductor/issues/362#issuecomment-355409552) slightly changed the behavior.

Looks like the first time I kill the worker it get picked up as the first task is flagged as "TIMEOUT" and a second one is immediately created as "scheduled".

But If I kill it a second time the newly created task will stay as "IN_PROGRESS"...

**Comment by panthony** [comment]
@jvemugunta Thanks for your anwser, I'll take a look at your PR (once you reverted the format changes it makes it too hard to see what was truly updated) and if it does fix by issue I'll close it as duplicate !

**Comment by jvemugunta** [comment]
@panthony - Please review my PR now and you may want to test with my changes and see if it works for you. I have now move to intelliJ IDE and hopefully the formatting got fixed

**Comment by apanicker-nflx** [comment]
@jvemugunta Thanks for your response and the contribution towards the fix.
@panthony You are on the right track, the `responseTimeoutSeconds` is intended to be used as a heartbeat mechanism from the workers to ensure that the task is processed and the worker has not died while processing the task. Please refer the documentation [here](https://netflix.github.io/conductor/tasklifecycle/#response-timeout-seconds) regarding this.
