### ISSUE TITLE
Bug with timeoutPolicy": "RETRY and retryCount > 0

### ISSUE THREAD

**Issue by jvemugunta** [Netflix/conductor#780]
Found a bug when the Task definition is defined with retryCount > 0

Here is are the steps to re-create the issue

**Task definition**

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' 'http://localhost:8080/api/metadata/taskdefs' -d '
[{
  "name": "T1",
  "retryCount": 2,
  "timeoutSeconds": 10,
  "inputKeys": [
    "sourceRequestId",
    "qcElementType"
  ],
  "outputKeys": [
    "state",
    "skipped",
    "result"
  ],
  "timeoutPolicy": "RETRY",
  "retryLogic": "FIXED",
  "retryDelaySeconds": 0,
  "responseTimeoutSeconds": 0
}]
'

```

**Workflow Definition**

```
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' 'http://localhost:8080/api/metadata/workflow' -d '
[{
  "name": "sample",
  "description": "sample workflow",
  "version": 1,
  "tasks": [
    {
      "name": "T1",
      "taskReferenceName": "T1",
      "type": "SIMPLE",
      "inputParameters": {
        "fileName": "${workflow.input.fileName}"
      }
    }
  ],
  "outputParameters": {
   
  },
  "schemaVersion": 2
}]

```

**Create a new workflow instance**

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: text/plain' 'http://localhost:8080/api/workflow' -d '
{
  "name": "sample",
  "version": 1,
  "correlatonId": "corr1",
  "input": {
    "fileName": "f1"
  }
}
'
```

**Now, the state of workflow and task in the UI page** 

<img width="1680" alt="page-1" src="https://user-images.githubusercontent.com/7503683/45923833-bc7a5e80-bebe-11e8-84ed-04861c834d30.png">

**Poll for the task**

```
curl -X GET --header 'Accept: application/json' 'http://localhost:8080/api/tasks/poll/T1';echo

{"taskType":"T1","status":"IN_PROGRESS","inputData":{"fileName":"f1"},"referenceTaskName":"T1","retryCount":0,"seq":1,"pollCount":1,"taskDefName":"T1","scheduledTime":1537672421681,"startTime":1537672453413,"endTime":0,"updateTime":1537672453413,"startDelayInSeconds":0,"retried":false,"executed":false,"callbackFromWorker":true,"responseTimeoutSeconds":0,"workflowInstanceId":"64654638-2e02-4672-a2b5-932633175408","workflowType":"sample","taskId":"91f93cfe-15b8-4dd6-be79-7aa7b9a7f5d8","callbackAfterSeconds":0,"workflowTask":{"name":"T1","taskReferenceName":"T1","inputParameters":{"fileName":"${workflow.input.fileName}"},"type":"SIMPLE","startDelay":0},"rateLimitPerFrequency":0,"rateLimitFrequencyInSeconds":0,"queueWaitTime":31732,"taskStatus":"IN_PROGRESS"}
```

**Now, the state of workflow and task in the UI page** 

<img width="1680" alt="page-2" src="https://user-images.githubusercontent.com/7503683/45923846-04998100-bebf-11e8-90b8-801d34975146.png">

**Wait for 60 seconds or so and you should see a screen as below**

<img width="1680" alt="page-3" src="https://user-images.githubusercontent.com/7503683/45923852-298df400-bebf-11e8-9439-302395d3d1f2.png">

**Poll for the task**

```
curl -X GET --header 'Accept: application/json' 'http://localhost:8080/api/tasks/poll/T1';echo

{"taskType":"T1","status":"IN_PROGRESS","inputData":{"fileName":"f1"},"referenceTaskName":"T1","retryCount":0,"seq":1,"pollCount":2,"taskDefName":"T1","scheduledTime":1537672421681,"startTime":1537672453413,"endTime":1537672545588,"updateTime":1537672575381,"startDelayInSeconds":0,"retried":true,"executed":false,"callbackFromWorker":true,"responseTimeoutSeconds":0,"workflowInstanceId":"64654638-2e02-4672-a2b5-932633175408","workflowType":"sample","taskId":"91f93cfe-15b8-4dd6-be79-7aa7b9a7f5d8","reasonForIncompletion":"Task timed out after 92167 millisecond.  Timeout configured as 10000","callbackAfterSeconds":0,"workflowTask":{"name":"T1","taskReferenceName":"T1","inputParameters":{"fileName":"${workflow.input.fileName}"},"type":"SIMPLE","startDelay":0},"rateLimitPerFrequency":0,"rateLimitFrequencyInSeconds":0,"queueWaitTime":31732,"taskStatus":"IN_PROGRESS"}
```
**Now, the state of workflow and task in the UI page . The "TIMEOUT task is changed as "IN_PROGRESS" instead of "SCHEDULED" task. This is BUG-1**

<img width="1680" alt="page-4" src="https://user-images.githubusercontent.com/7503683/45923929-0bc18e80-bec1-11e8-86c1-0922c0657c3c.png">

**Poll for the task**

```
 curl -X GET --header 'Accept: application/json' 'http://localhost:8080/api/tasks/poll/T1';echo

{"taskType":"T1","status":"IN_PROGRESS","inputData":{"fileName":"f1"},"referenceTaskName":"T1","retryCount":1,"seq":2,"pollCount":1,"taskDefName":"T1","scheduledTime":1537672545581,"startTime":1537672602679,"endTime":0,"updateTime":1537672602679,"startDelayInSeconds":0,"retriedTaskId":"91f93cfe-15b8-4dd6-be79-7aa7b9a7f5d8","retried":false,"executed":false,"callbackFromWorker":true,"responseTimeoutSeconds":0,"workflowInstanceId":"64654638-2e02-4672-a2b5-932633175408","taskId":"d16dbd53-e208-45a7-bcc7-c1710174758b","reasonForIncompletion":"Task timed out after 92167 millisecond.  Timeout configured as 10000","callbackAfterSeconds":0,"workflowTask":{"name":"T1","taskReferenceName":"T1","inputParameters":{"fileName":"${workflow.input.fileName}"},"type":"SIMPLE","startDelay":0},"rateLimitPerFrequency":0,"rateLimitFrequencyInSeconds":0,"queueWaitTime":57098,"taskStatus":"IN_PROGRESS"}
```

**Now, the state of workflow and task in the UI page . Both the tasks are changed as IN_PROGRESS. This is BUG-2**

<img width="1680" alt="page-5" src="https://user-images.githubusercontent.com/7503683/45923961-bf2a8300-bec1-11e8-9095-6c7c9e2d47a3.png">

**Comment by jvemugunta** [comment]
@v1r3n and @cyzhao - Can you please validate this bug? I want to create the pull request for fixing this bug. This is purely a race condition that is causing the bug

**Comment by cyzhao** [comment]
@jvemugunta great find, can you elaborate on how racing condition causes the problem?

**Comment by jvemugunta** [comment]
@cyzhao 

if you look at this class

https://github.com/Netflix/dyno-queues/blob/e92d2aa584de32e4169f78c8311e04da2d5b3784/dyno-queues-redis/src/main/java/com/netflix/dyno/queues/redis/RedisDynoQueue.java#L518-L526

https://redis.io/commands/zrangebyscore

The score keeps changing in push, pop and processUnacks methods
Set<String> scanned = quorumConn.zrangeByScore(myQueueShard, 0, now, offset, count);

However, when the pull happens, there is good chance the pop method will pull the message that resulted in the TimeOUT as processUnacks runs on a background thread every 60 seconds

The solution is not remove messages from the queue when the Task is not IN_PROGRESS or SCHEDULED. Please refer to my #781 on the fix.

I have tested and it seems to work. I am not sure if we need to apply the same fix on updateTask method

https://github.com/Netflix/conductor/blob/b53d6057f96721530d4fe62cddd3430ee9662f20/core/src/main/java/com/netflix/conductor/core/execution/WorkflowExecutor.java#L525-L543

It is hard to debug and replicate these bugs in a multi-threaded environment and you have to visualize in your mind on what the code does at runtime. I realized this bug when doing load tests

Does this make sense?

**Comment by cyzhao** [comment]
@jvemugunta thanks for the clarification, makes sense. I don't think we need to apply the same fix to WorkflowExecutor as task is always popped before updateTask.

**Comment by jvemugunta** [comment]
@cyzhao - Let us first merge the PR #771 before we handle this one. #771 is a big one and all major bugs have been addressed
