### ISSUE TITLE
TERMINATION OF A WORKFLOW YOU GET A FAILURE RESPONSE

### ISSUE THREAD

**Issue by harikareddy7** [Netflix/conductor#786]
The problem we are having is with either bulk or single termination of a workflow you get a failure response and the workflow is not terminated. 
currently we are using 
Conductor version: 1.13.0
Elastic search version: 5.6.10

**Comment by apanicker-nflx** [comment]
Please use the latest conductor version 2.7.+ . This issue should be resolved in the newest versions.
