### ISSUE TITLE
EndTime is always updated for tasks

### ISSUE THREAD

**Issue by bitbier** [Netflix/conductor#789]
We've been using conductor for a few months and the other day, we were trying to debug an issue to see why a particular workflow was taking longer than normal.

We use the conductor-ui, and when we inspected the the Task Details, we realized that the `endTime` for the task were closely related to the end time of the entire workflow. At first I thought this was some kind of indexing error, but when we pulled the JSON of the final workflow run, the times are indeed off. The way our workflows are structure is that there are some serial tasks along with parallel tasks. Some of these serial tasks we know take a few minutes to complete, so it should stand to reason that the end time should be significantly less than the end time of the later tasks. This is not the case.

I haven't had time to trace the code, but it looks like the `updateTask()` method is being called on the tasks at every decision point in the workflow. I'm not sure if this is expected to happen or if conductor can be smart and only update those tasks need it. I think it may be making additional network calls to redis and also to ES that it doesn't need to.

Anyways, it looks like in the `RedisExecutionDAO`'s `updateTask()`, there is a following check:

```
		if (task.getStatus() != null && task.getStatus().isTerminal()) {
			task.setEndTime(System.currentTimeMillis());
		}
```

If this method is indeed called multiple times on already completed tasks, then this is what is setting the endTime. If I have time soon, I plan on making a PR to fix this issue, but I wanted to make this issue known for others until it's fixed.

**NOTE**: It seems like this doesn't happen on `SystemTask`s (`DECISION`, `JOIN`, `EVENT`, etc) those `endTimes` seem correct.

Conductor version: 1.12.0

**Comment by kishorebanala** [comment]
@bitbier Thanks for reporting the issue. It's been a while, but we'll take a look.

**Comment by apanicker-nflx** [comment]
Closing this issue, since this should be fixed as part of recent changes.
