### ISSUE TITLE
Kubernetes - Conductor with replication set to 3

### ISSUE THREAD

**Issue by jkaipa** [Netflix/conductor#791]
@v1r3n - If we configure to run conductor in 3 pods of the same kubernetes cluster pointing to the same dynamodb & es engine and start a workflow through one conductor instance, wont the "same" task be picked up by other conductor instances and schedule causing duplicate execution of the task by workers?
I am trying to understand how I can configure conductor on kubernetes to scale out.

**Comment by v1r3n** [comment]
Conductor relies on the underlying store to "discover" instances, so if there are multiple nodes connected to the same underlying redis store, they all will pick up tasks - However, Conductor is a distributed orchestration engine, it ensures there are no duplicate task execution scheduled.  

Refer to the dyno queues blog on how we achieve this:
https://medium.com/netflix-techblog/distributed-delay-queues-based-on-dynomite-6b31eca37fbc

(Dyno queues is underlying queuing mechanism by which conductor schedules the task execution)

**Comment by jkaipa** [comment]
Thank you 👍
