### ISSUE TITLE
Input data Integer on Workflow and is convert to String

### ISSUE THREAD

**Issue by Leggrand** [Netflix/conductor#796]
Hello,

I has input the data on workflow call, some datas is integer, but when task is executed this data is convert to string. I was search on issues and the [#360](https://github.com/Netflix/conductor/issues/360) is similar with my situation. Look the datas:

Workflow declaration:
`[{
	"name":"Heraclito",
	"description":"Workflow Heraclito",
	"version":1,
	"tasks":[
		{
			"name": "fork_join",
			"taskReferenceName": "rf_garfo",
			"type": "FORK_JOIN",
			"forkTasks": [
				[{
				   "name":"rf_update_company",
				   "taskReferenceName":"rf_update_company",
				   "inputParameters":{
					  "http_request":{
						 "uri":"https://leg19238akulman.acomp.com/services/company/59",
						 "method":"PUT",
						 "contentType":"application/json",
						 "body":{
							"Id":59,
							"StatusId":"${workflow.input.Company.StatusId}",
							"Code": "00037859000107",
							"CodeTypeId":1,
							"GLN": "20934",
							"Enabled": "${workflow.input.Company.Enabled}",
							"CompanyRootId":55174,
							"IsHeadquarter": "${workflow.input.Company.IsHeadquarter}",
							"Deleted": "${workflow.input.Company.Deleted}"
						 },
						 "headers":{
							"UserId":"${workflow.input.UserId}",
							"Authorization": "${workflow.input.Authorization}"
						 }
					  }
				   },
				   "type":"HTTP"
				}],
				[{
				   "name":"rf_update_address",
				   "taskReferenceName":"rf_update_address",
				   "inputParameters":{
					  "http_request":{
						 "uri":"https://leg19238akulman.acomp.com/services/address/8059",
						 "method":"PUT",
						 "contentType":"application/json",
						 "body":{
							"Id":8059,
							"StreetAddress": "${workflow.input.Addresses[0].StreetAddress}",
							"Number": "${workflow.input.Addresses[0].Number}",
							"AdditionalInformation": "${workflow.input.Addresses[0].AdditionalInformation}",
							"District": "${workflow.input.Addresses[0]District}",
							"PostalCode": "${workflow.input.Addresses[0].PostalCode}",
							"CompanyId":59,
							"AddressTypeId": "${workflow.input.Addresses[0].AddressTypeId}",
							"CityId": "${workflow.input.Addresses[0].CityId}",
							"AddressType": "${workflow.input.Addresses[0].AddressType}"
						 },
						 "headers":{
							"UserId":"${workflow.input.UserId}",
							"Authorization": "${workflow.input.Authorization}"
						 }
					  }
				   },
				   "type":"HTTP"
				}]
			]
		},
		{
			"name": "join",
			"taskReferenceName": "rf_joint",
			"type": "JOIN",
			"joinOn": [
				"rf_update_company",
				"rf_update_address"
			]
		}
	],
	"schemaVersion":2
}]`

Input task on workflow
`{
   "http_request": {
      "uri": "https://leg19238akulman.acomp.com/services/company/59",
      "method": "PUT",
      "contentType": "application/json",
      "body": {
         "Id": "59",
         "StatusId": 2,
         "Code": "00037859000107",
         "CodeTypeId": "1",
         "GLN": "20934",
         "Enabled": true,
         "CompanyRootId": "55174",
         "IsHeadquarter": true,
         "Deleted": false
      },
      "headers": {
         "UserId": "e42d0435-f22e-4145-85d1-d58c2fc30198",
         "Authorization": "bearer b5v_GwVHdqqYI_c6I6QUYBA7gV5oSzdEOouoSfT-qnDM8VQ5OergIauzEr9yehYN68ddJbed9K8PkuxJ2OwlQhH47-ru8HCIzcTSip23wKxDFPQfeDP9avPfxQ-nCSMvZwYSaotLeFnhFG7f4NsqRFqhnDBd_gL3ffqT1oCW5ZU6pbmk4DdoZPFdi1jySz1clD2q-sqn1BkSTIB05c2ZF6JHQWnjAkU4WTvhEvhSNLn3GIjpSA8IOhCVxTSGtSh0jVzBbWnzzFhyaamN24AYTtGvYN1ldAYaklnWyCGv3PfjQglBM-GS1VovEV4S3xAGl1j-Wt2gfGpbhcMadI7PO-Quk5-e6UwXznpX4k"
      }
   }
}`

**Comment by cyzhao** [comment]
Duplicated with #360.
