### ISSUE TITLE
Support for newer java versions

### ISSUE THREAD

**Issue by muraliman** [Netflix/conductor#799]
Hi,

Is there any update planned for supporting latest versions of Java (Java 9, 10 or 11) in the near future?

**Comment by cyzhao** [comment]
@muraliman not this year but will happen early next year.

**Comment by patrickmayer0** [comment]
Any tentative date for Java 11 support?

**Comment by anuraggupta** [comment]
@cyzhao any update on Java 11 support ?

**Comment by aravindanr** [comment]
@anuraggupta Java 11 support is in our roadmap, but it's not high on the list. We are curious to know what you plan to get out Java 11 support in Conductor?
