### ISSUE TITLE
Stuck on gradle build/local server

### ISSUE THREAD

**Issue by jcantosz** [Netflix/conductor#8]
Hi,

I am attempting to install/test the conductor, however when I run the `../gradlew server` command building does not advance beyond 96% (`"Building 96% > :conductor-test-harness:server"`). Any guidance would be appreciated.

**Installation Steps**
1. Created Ubuntu 14.04 server
2. Installed DynomiteDB (http://www.dynomitedb.com/docs/dynomite/v0.5.8/quick-start-ubuntu/)
3. Installed java + jetty using (https://hostpresto.com/community/tutorials/how-to-install-jetty-8-on-ubuntu-14-04/)
4. Followed quickstart guide: https://netflix.github.io/conductor/intro/

**System Info**
`~# uname -a`
```
Linux hostname 4.4.0-45-generic #66~14.04.1-Ubuntu SMP Wed Oct 19 15:05:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Build Output**
`~/conductor/test-harness# ../gradlew server`
[conductor-build-output.txt](https://github.com/Netflix/conductor/files/664195/conductor-build-output.txt)

Thanks,
~Jesse

**Comment by v1r3n** [comment]
```server``` task starts the jetty container on port 8080 and will continue running until you terminate using ```Ctrl+c``` or kill the process.  Once you see the following line in the logs you should be good to go.  
```Started server on http://localhost:8080/```

You can access the swagger UI at the following URL:
http://localhost:8080/swagger-ui/

**Comment by jcantosz** [comment]
Thanks for the quick response! I am able to see the swagger UI (I seem to have a CORS issue to resolve). I was assuming this would bring up the server for the UI as well (http://localhost:3000/) which I am not seeing. 

Is there a reason the building does not progress beyond 96%?

**Comment by v1r3n** [comment]
UI runs as a separate process using node server.
You want to follow the steps under "Start UI Server" section on getting started page.

The build never completes, because the way gradle works, it starts the server task, and will not mark it as complete until the server task completes (which is when you terminate the server).
