### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by peng-w** [Netflix/conductor#802]
Hello：
When I run Conductor UI in docker mode，I can't access any url address。
Error is：
![bug](https://user-images.githubusercontent.com/6479081/46599050-c1731b00-cb18-11e8-8553-53479401feba.png)
![bug2](https://user-images.githubusercontent.com/6479081/46599051-c1731b00-cb18-11e8-8a1a-11b2b8d43723.png)
Is that a bug?Or is there something wrong with my operate?

**Comment by saidatta** [comment]
are you sure your conductor server is running?

**Comment by peng-w** [comment]
> are you sure your conductor server is running?

Yes,I'm sure. The server is running,I was able to communicate with server using postman

**Comment by saidatta** [comment]
Any stack trace in the conductor server log?

**Comment by peng-w** [comment]
> Any stack trace in the conductor server log?

![server-logs](https://user-images.githubusercontent.com/6479081/46779524-cae3c980-cd4a-11e8-83d0-9708c795232d.png)

without any error in server

**Comment by peng-w** [comment]
Correct , i was missing the "/" in last too, working fine now.
closing - as reported in #70
