### ISSUE TITLE
There is any Netflix Conductor benchmark?

### ISSUE THREAD

**Issue by artpdr** [Netflix/conductor#807]
Hi everyone,

Does anyone know if there are benchmarks with Netflix Conductor? For example, to assess how much time it takes to start to execute a workflow after POSTing its definition using different numbers of tasks, and how much time it takes to retrieve such workflows to assess the status of the tasks.

What is the greatest number of tasks that you can insert in a workflow and how much time it take to start to execute?

In my case, I can't give a precise number right now, but once I have tested to place a workflow with about 500000 to 1M tasks and it never started to execute. I eventually cancelled the request as it was taking too much time. This test was done with Netflix Conductor running in a Docker container in my laptop.

I would really appreciate any help you can provide.

Thank you very much,

Artur

**Comment by cyzhao** [comment]
@artpdr we don't have benchmark yet, but we will work on performance test soon. I am curious to know about your use case where you need to run 500000 to 1M tasks for a workflow, having too many tasks is an anti-pattern and it is not what Conductor is designed for, the system just can't handle large volume of tasks, as a matter of fact we are planning to put a limit on number of tasks (a few hundreds the most) you can start for a workflow.

**Comment by artpdr** [comment]
@cyzhao Thanks for answering. One use case that might require such amount of tasks is grid search cross validation, where the cross validation process might have repetitions and there are many different models employing different features and different hyperparameters being trained and tested in parallel on the same workflow.

**Comment by artpdr** [comment]
@cyzhao What do you think about splitting the entire workflow composed of thousands of tasks in smaller workflows with less tasks (in the order of hundreds)

**Comment by cyzhao** [comment]
@artpdr yes that would be a reasonable workaround.

**Comment by artpdr** [comment]
Nice to hear from you @cyzhao . Do you have any script planned (test plan) to make performance tests on Conductor? I might conduct some tests in the next days on the system using different number of tasks in a workflow and different workflows running in parallel with different number of tasks also...
Btw do you know any other system that can support my use case of running cross validation workflows  (composed by different tasks running asynchronously)? Thanks in advance.

**Comment by vardior** [comment]
Hi,

I'm currently facing a similar issue regarding subtasking,
I'm currently splitting a large task into several multiple tasks (for example, a need a process a large file with each subtask taking a certain interval of the file).
After a few hundred tasks (generated dynamically with a parent "splitter" task), conductor stops responding. My fork creation request never returns AND any queries regarding the workflow are stuck aswell.

In case that's an anti-pattern, is there a better solution regarding multiple instance of the same task?

**Comment by kishorebanala** [comment]
@vardior This is currently a limitation in Conductor, where having a large number of tasks in a workflow could slowdown the server. Whenever the workflow is being evaluated, it loads all the tasks as well, and it could easily make up for a large payload (multiplied by number of decides across the server for each task update).

A workaround is to use sub workflows to branch out tasks, and always keep the max number of tasks in a workflow at reasonable number, say 100. For eg., if you have 500 tasks, split into 5 sub workflows of 100 each, or even to multiple levels at a granularity that seems reasonable to you.

**Comment by asofiasbo** [comment]
@kishorebanala Can you elaborate on the limitation? I performed some tests and ran out of memory when tried to execute workflows with +1000 tasks, but I couldn't trace back the problem to its origin. Why does Conductor only support a "small" number os tasks per workflow? Is this related to the way queues are implemented? Can you give me some details to help me understand this limitation? Thank you!

**Comment by kishorebanala** [comment]
@asofiasbo Well, the limitation is not on scheduling the tasks (and there by, not on task queues), but on workflow evaluation. Every time a task is updated, the workflow will be evaluated. And, every time a workflow is evaluated, all of it's tasks are loaded. And with 1000's of tasks being updated in parallel, without locking, workflows are evaluated thousands of times, which could introduce a huge load on Conductor server.

This could be mitigated with recently introduced [distributed locking](https://netflix.github.io/conductor/technicaldetails/#maintaining-workflow-consistency-with-distributed-locking-and-fencing-tokens) solution, which avoids running multiple decides at once. However, it is still a best practice to keep number of tasks in a workflow bounded, respecting the persistence layer's capabilities. Eg. when using Cassandra, we would be running into wide rows with large number of tasks.
