### ISSUE TITLE
Please help 

### ISSUE THREAD

**Issue by kchaturanga** [Netflix/conductor#808]
Using config file/usr/conductor/conductor-config.properties
Using log4j config /usr/conductor/log4j.properties
0    [main] INFO  com.netflix.conductor.server.ConductorServer  - External payload storage is not configured, provided: , supported values are: [S3]
java.lang.IllegalArgumentException: No enum constant com.netflix.conductor.server.ConductorServer.ExternalPayloadStorageType.
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.netflix.conductor.server.ConductorServer$ExternalPayloadStorageType.valueOf(ConductorServer.java:68)
	at com.netflix.conductor.server.ConductorServer.<init>(ConductorServer.java:120)
	at com.netflix.conductor.server.Main.main(Main.java:44)
------------------------------------------------
Config is this 

db=redis

# For AWS Elasticache Redis (cluster mode enabled) the format is configuration_endpoint:port:us-east-1e. 
# The region in this case does not matter
workflow.dynomite.cluster.hosts=*******.cache.amazonaws.com:6379:us-east-1e
workflow.dynomite.connection.maxConnsPerHost=31

queues.dynomite.nonQuorum.port=6379

**Comment by saidatta** [comment]
your db needs to be `redis_cluster` for ECR

Please take a look at the property documentation - https://netflix.github.io/conductor/server/

**Comment by kchaturanga** [comment]
> your db needs to be `redis_cluster` for ECR
> 
> Please take a look at the config properties documentation - https://netflix.github.io/conductor/server/
> Also, make sure the appropriate security group with ports are assigned to the ECR. if you are in a corporate subnet

Thank you .. I will try ..
