### ISSUE TITLE
Null input for  task_30 in  kitchensink demo 

### ISSUE THREAD

**Issue by lydialmr120** [Netflix/conductor#81]
While running the kitchensink demo,the get_es_1 task completed successful,but the task_30's input value is null.

get_es_1 task Output:
{ "response": { "body": { "took": 5, "timed_out": false, "_shards": { "total": 5, "successful": 5, "failed": 0 }, "hits": { "total": 20, "max_score": 1, "hits": [ { "_index": "conductor", "_type": "task", "_id": "1b2f2630-d1a5-4f52-9c81-871bd86b6be8", "_score": 1, "_source": { "workflowId": "77f797ad-afe2-45d8-8e35-51ff619f5c1d", "scheduledTime": "2017-02-09T08:09:57Z", "startTime": "2017-02-09T08:09:57Z", "updateTime": "2017-02-09T08:09:57Z", "endTime": "2017-02-09T08:09:56Z", "status": "IN_PROGRESS", "executionTime": -64, "queueWaitTime": 20, "taskDefName": "SUB_WORKFLOW", "taskType": "SUB_WORKFLOW" } }, { "_index": "conductor", "_type": "task", "_id": "af3031c1-e76c-49cc-9b67-b3ee5c5b8d9b", "_score": 1, "_source": { "workflowId": "77f797ad-afe2-45d8-8e35-51ff619f5c1d", "scheduledTime": "2017-02-09T07:53:38Z", "startTime": "1970-01-01T00:00:00Z", "updateTime": "2017-02-09T08:09:57Z", "endTime": "2017-02-09T08:09:57Z", "status": "COMPLETED", "executionTime": 1486627797097, "queueWaitTime": 0, "taskDefName": "task_4", "taskType": "task_4" } }, { "_index": "conductor", "_type": "workflow", "_id": "b3ea9b56-c6ce-4574-a94e-e3454a1a44ac", "_score": 1, "_source": { "workflowType": "sub_flow_1", "version": 1, "workflowId": "b3ea9b56-c6ce-4574-a94e-e3454a1a44ac", "startTime": "2017-02-09T08:09:57Z", "status": "RUNNING", "input": "{workflowInput={}, subWorkflowName=sub_flow_1, subWorkflowVersion=1}", "output": "{}", "executionTime": 0, "updateTime": "2017-02-09T08:20:37Z" } }, { "_index": "conductor", "_type": "task", "_id": "4a5eb4e8-67d0-499e-8b50-743fbd13ed7d", "_score": 1, "_source": { "workflowId": "079190b3-9f6c-425f-ba59-e98c4044bf0e", "scheduledTime": "2017-02-09T06:23:51Z", "startTime": "1970-01-01T00:00:00Z", "updateTime": "2017-02-09T06:54:15Z", "endTime": "2017-02-09T06:54:15Z", "status": "COMPLETED", "executionTime": 1486623255278, "queueWaitTime": 0, "taskDefName": "task_5", "taskType": "task_5" } }, { "_index": "conductor", "_type": "task", "_id": "f52cd10e-b04f-4ea9-91f3-76ad90c4c54d", "_score": 1, "_source": { "workflowId": "079190b3-9f6c-425f-ba59-e98c4044bf0e", "scheduledTime": "2017-02-09T06:54:15Z", "startTime": "1970-01-01T00:00:00Z", "updateTime": "2017-02-09T06:54:15Z", "endTime": "1970-01-01T00:00:00Z", "status": "SCHEDULED", "executionTime": 0, "queueWaitTime": 0, "taskDefName": "task_30", "taskType": "task_30" } }, { "_index": "conductor", "_type": "task", "_id": "c369c1b1-57c5-4256-a766-87148c05ad73", "_score": 1, "_source": { "workflowId": "079190b3-9f6c-425f-ba59-e98c4044bf0e", "scheduledTime": "2017-02-09T06:54:15Z", "startTime": "2017-02-09T06:54:15Z", "updateTime": "2017-02-09T06:54:15Z", "endTime": "2017-02-09T06:54:15Z", "status": "COMPLETED", "executionTime": 312, "queueWaitTime": 12, "taskDefName": "search_elasticsearch", "taskType": "HTTP" } }, { "_index": "conductor", "_type": "workflow", "_id": "14900542-dffa-40b2-bf08-4fd451aa0798", "_score": 1, "_source": { "workflowType": "kitchensink", "version": 1, "workflowId": "14900542-dffa-40b2-bf08-4fd451aa0798", "startTime": "2017-02-09T07:38:26Z", "status": "TERMINATED", "input": "{input={task2Name=task_5, mod=1, oddEven=0}}", "output": "{workflowIds=[], statues=[]}", "executionTime": 50819, "updateTime": "2017-02-09T07:39:17Z", "endTime": "2017-02-09T07:39:17Z" } }, { "_index": "conductor", "_type": "task", "_id": "fa8992cc-dba5-443b-8025-e61a214c992d", "_score": 1, "_source": { "workflowId": "77f797ad-afe2-45d8-8e35-51ff619f5c1d", "scheduledTime": "2017-02-09T08:09:57Z", "startTime": "2017-02-09T08:09:57Z", "updateTime": "2017-02-09T08:09:57Z", "endTime": "2017-02-09T08:09:56Z", "status": "IN_PROGRESS", "executionTime": -68, "queueWaitTime": 15, "taskDefName": "JOIN", "taskType": "JOIN" } }, { "_index": "conductor", "_type": "task", "_id": "fbd5fa46-3418-468a-8a46-3094ea4ea4a3", "_score": 1, "_source": { "workflowId": "77f797ad-afe2-45d8-8e35-51ff619f5c1d", "scheduledTime": "2017-02-09T07:53:38Z", "startTime": "2017-02-09T07:53:38Z", "updateTime": "2017-02-09T08:09:57Z", "endTime": "2017-02-09T08:09:57Z", "status": "COMPLETED", "executionTime": 978600, "queueWaitTime": 35, "taskDefName": "DECISION", "taskType": "DECISION" } }, { "_index": "conductor", "_type": "task", "_id": "5079eadd-1e72-48e1-8039-b45f7c6f353e", "_score": 1, "_source": { "workflowId": "77f797ad-afe2-45d8-8e35-51ff619f5c1d", "scheduledTime": "2017-02-09T08:09:56Z", "startTime": "2017-02-09T08:09:57Z", "updateTime": "2017-02-09T08:09:57Z", "endTime": "2017-02-09T08:09:57Z", "status": "COMPLETED", "executionTime": 71, "queueWaitTime": 66, "taskDefName": "FORK", "taskType": "FORK" } } ] } }, "headers": { "Content-Length": [ "4265" ], "Content-Type": [ "application/json; charset=UTF-8" ] }, "statusCode": 200 } }

task_30 task Input
{ "statuses": [], "fistWorkflowId": null }

**Comment by v1r3n** [comment]
@lydialmr120 thanks for pointing this out.  If you use the latest version from dev, the issue has been fixed.  

https://github.com/Netflix/conductor/commit/f896c70fde514fd0292a01d74400ac817ef8ad11

**Comment by v1r3n** [comment]
Closing the issue.  Please re-open if the error still exists.
