### ISSUE TITLE
WorkflowDefinition having SIMPLE task is not getting executed and it is in RUNNING STATE only.

### ISSUE THREAD

**Issue by gsambasiva** [Netflix/conductor#811]
Hi,

I have a workflow with SIMPLE task, and when I tried to execute the Workflow, It's is in RUNNING status only.

And the workflow task status is SCHEDULED.

Here is the example:

**Workflow Definition:**
{
    "name": "simple_workflow",
    "version": 1,
    "tasks": [
      {
        "name": "task_a",
        "taskReferenceName": "task_a",
        "inputParameters": {
          "message_a": "${workflow.input.message}"
        },
        "type": "SIMPLE",
        "startDelay": 0
      }
    ],
    "schemaVersion": 2
  }

**Workflow Task**

[
  {
    "name": "task_a",
    "retryCount": 1,
    "timeoutSeconds": 1200,
    "timeoutPolicy": "TIME_OUT_WF",
    "retryLogic": "FIXED",
    "retryDelaySeconds": 60,
    "inputKeys": [
      "message"
    ],
    "responseTimeoutSeconds": 3600
  }
]

**OutPut**

{
    "ownerApp": null,
    "createTime": 1539600131480,
    "updateTime": 1539600131605,
    "createdBy": null,
    "updatedBy": null,
    "status": "RUNNING",
    "endTime": 0,
    "workflowId": "dc9f3eed-7a75-472e-879f-d6bf46413d64",
    "parentWorkflowId": null,
    "parentWorkflowTaskId": null,
    "tasks": [
        {
            "taskType": "task_a",
            "status": "SCHEDULED",
            "inputData": {
                "message_a": "Hellow World!"
            },
            "referenceTaskName": "task_a",
            "retryCount": 0,
            "seq": 1,
            "correlationId": null,
            "pollCount": 0,
            "taskDefName": "task_a",
            "scheduledTime": 1539600131531,
            "startTime": 0,
            "endTime": 0,
            "updateTime": 1539600131590,
            "startDelayInSeconds": 0,
            "retriedTaskId": null,
            "retried": false,
            "callbackFromWorker": true,
            "responseTimeoutSeconds": 3600,
            "workflowInstanceId": "dc9f3eed-7a75-472e-879f-d6bf46413d64",
            "taskId": "473014aa-c732-44e6-be23-c20d9e1b7bee",
            "reasonForIncompletion": null,
            "callbackAfterSeconds": 0,
            "workerId": null,
            "outputData": {},
            "workflowTask": {
                "name": "task_a",
                "taskReferenceName": "task_a",
                "description": null,
                "inputParameters": {
                    "message_a": "${workflow.input.message}"
                },
                "type": "SIMPLE",
                "dynamicTaskNameParam": null,
                "caseValueParam": null,
                "caseExpression": null,
                "decisionCases": {},
                "dynamicForkJoinTasksParam": null,
                "dynamicForkTasksParam": null,
                "dynamicForkTasksInputParamName": null,
                "defaultCase": [],
                "forkTasks": [],
                "startDelay": 0,
                "joinOn": [],
                "sink": null,
                "optional": null,
                "subWorkflowParam": null
            },
            "domain": null,
            "taskStatus": "SCHEDULED",
            "queueWaitTime": 0
        }
    ],
    "input": {
        "message": "Hellow World!"
    },
    "output": {},
    "workflowType": "simple_workflow",
    "version": 1,
    "correlationId": null,
    "reRunFromWorkflowId": null,
    "reasonForIncompletion": null,
    "schemaVersion": 2,
    "event": null,
    "taskToDomain": {},
    "failedReferenceTaskNames": [],
    "startTime": 1539600131480
}

**Comment by apanicker-nflx** [comment]
@gsambasiva This seems to be expected behavior. Conductor will set the task to SCHEDULED status and queue this task. A [worker](https://github.com/Netflix/conductor/blob/master/client/src/main/java/com/netflix/conductor/client/worker/Worker.java) should poll for this task, [execute](https://github.com/Netflix/conductor/blob/master/client/src/main/java/com/netflix/conductor/client/worker/Worker.java#L46) the task and then [update](https://github.com/Netflix/conductor/blob/master/jersey/src/main/java/com/netflix/conductor/server/resources/TaskResource.java#L106) conductor with the [TaskResult](https://github.com/Netflix/conductor/blob/master/common/src/main/java/com/netflix/conductor/common/metadata/tasks/TaskResult.java) to move the status of the workflow.
