### ISSUE TITLE
Integer input in a nested JSON to parent workflow , which internally calls itself, gets changed from Integer to String

### ISSUE THREAD

**Issue by rksinha** [Netflix/conductor#812]
Issue explained after Workflow definitions. Please scroll down. Attached all required stuff to generate the workflow.

**PARENT WORKFLOW -** 
{
  "createTime": 1539589685646,
  "name": "state_something_change",
  "description": "",
  "version": 1,
  "tasks": [
    {
      "name": "something_type_check",
      "taskReferenceName": "something_type_check_something",
      "inputParameters": {
        "something_type": "${workflow.input.something_type}"
      },
      "type": "DECISION",
      "caseValueParam": "something_type",
      "decisionCases": {
        "FOOD": [
          {
            "name": "fork_join_tasks",
            "taskReferenceName": "fork_join_tasks_1",
            "type": "FORK_JOIN",
            "forkTasks": [
              [
                {
                  "name": "http_post",
                  "taskReferenceName": "instrument_something_dp",
                  "inputParameters": {
                    "http_request": {
                      "uri": "http://SOME_IP:9001/message",
                      "method": "POST",
                      "body": {
                        "something_id": "${workflow.input.something_id}",
                        "state_status": "${workflow.input.state_status}",
                        "something": "${workflow.input.something}",
                        "reason": "${workflow.input.reason}",
                        "something_type": "${workflow.input.something_type}",
                        "final_something": "${workflow.input.something.state.something}",
                        "timestamp": "${workflow.input.timestamp}"
                      },
                      "headers": {
                        "eventId": 1,
                        "uuid": "174D696P-92F9-4203-A8E1-4D2A2EFEEC68",
                        "appName": "Flo",
                        "timestamp": 1538645732000,
                        "experimentId": "",
                        "schemaVersion": "1.0.0",
                        "name": "FoodsomethingPrediction_v1"
                      }
                    }
                  },
                  "type": "HTTP",
                  "startDelay": 0
                }
              ],
              [
                {
                  "name": "http_post",
                  "taskReferenceName": "nullify_eca",
                  "inputParameters": {
                    "http_request": {
                      "uri": "http://SOME_IP:8083/api/v1/eca/nullify-by-group",
                      "method": "POST",
                      "body": {
                        "groupName": "eca-something-${workflow.input.something_id}",
                        "nullifiedBy": "flo"
                      }
                    }
                  },
                  "type": "HTTP",
                  "startDelay": 0
                }
              ]
            ],
            "startDelay": 0
          },
          {
            "name": "join_tasks",
            "taskReferenceName": "join_tasks_1",
            "type": "JOIN",
            "startDelay": 0,
            "joinOn": [
              "instrument_something_dp",
              "nullify_eca"
            ]
          },
          {
            "name": "fork_join_tasks",
            "taskReferenceName": "fork_join_all_stage",
            "type": "FORK_JOIN",
            "forkTasks": [
              [
                {
                  "name": "something_event_completion_check",
                  "taskReferenceName": "something_event_assignment_check_something",
                  "inputParameters": {
                    "assignment_completed": "${workflow.input.something.assignment.completed}"
                  },
                  "type": "DECISION",
                  "caseValueParam": "assignment_completed",
                  "decisionCases": {
                    "false": [
                      {
                        "name": "set_reminder_eca_sub_workflow",
                        "taskReferenceName": "set_reminder_eca_assignment_stage_1",
                        "inputParameters": {
                          "instanceId": "${workflow.input.something_id}",
                          "event": "assigned",
                          "timeoutAt": "${workflow.input.something.assignment.something}",
                          "ecaGroupName": "eca-something-${workflow.input.something_id}",
                          "waitTaskRefName": "wait_for_eca",
                          "workflowRefId": "${workflow.workflowId}"
                        },
                        "type": "SUB_WORKFLOW",
                        "startDelay": 0,
                        "subWorkflowParam": {
                          "name": "set_reminder_eca",
                          "version": 1
                        }
                      }
                    ]
                  },
                  "startDelay": 0
                }
              ],
              [
                {
                  "name": "something_event_completion_check",
                  "taskReferenceName": "something_event_pickedup_check_something",
                  "inputParameters": {
                    "pickup_completed": "${workflow.input.something.pickup.completed}"
                  },
                  "type": "DECISION",
                  "caseValueParam": "pickup_completed",
                  "decisionCases": {
                    "false": [
                      {
                        "name": "set_reminder_eca_sub_workflow",
                        "taskReferenceName": "set_reminder_eca_pickedup_stage_2",
                        "inputParameters": {
                          "instanceId": "${workflow.input.something_id}",
                          "event": "pickedup",
                          "timeoutAt": "${workflow.input.something.pickup.something}",
                          "ecaGroupName": "eca-something-${workflow.input.something_id}",
                          "waitTaskRefName": "wait_for_eca",
                          "workflowRefId": "${workflow.workflowId}"
                        },
                        "type": "SUB_WORKFLOW",
                        "startDelay": 0,
                        "subWorkflowParam": {
                          "name": "set_reminder_eca",
                          "version": 1
                        }
                      }
                    ]
                  },
                  "startDelay": 0
                }
              ],
              [
                {
                  "name": "something_event_completion_check",
                  "taskReferenceName": "something_event_delivered_check_something",
                  "inputParameters": {
                    "state_completed": "${workflow.input.something.state.completed}"
                  },
                  "type": "DECISION",
                  "caseValueParam": "state_completed",
                  "decisionCases": {
                    "false": [
                      {
                        "name": "set_reminder_eca_sub_workflow",
                        "taskReferenceName": "set_reminder_eca_delivered_stage_3",
                        "inputParameters": {
                          "instanceId": "${workflow.input.something_id}",
                          "event": "delivered",
                          "timeoutAt": "${workflow.input.something.state.something}",
                          "ecaGroupName": "eca-something-${workflow.input.something_id}",
                          "waitTaskRefName": "wait_for_eca",
                          "workflowRefId": "${workflow.workflowId}"
                        },
                        "type": "SUB_WORKFLOW",
                        "startDelay": 0,
                        "subWorkflowParam": {
                          "name": "set_reminder_eca",
                          "version": 1
                        }
                      }
                    ]
                  },
                  "startDelay": 0
                }
              ],
              [
                {
                  "name": "something_event_completion_check",
                  "taskReferenceName": "something_event_delivered_check_something",
                  "inputParameters": {
                    "state_completed": "${workflow.input.something.state.completed}"
                  },
                  "type": "DECISION",
                  "caseValueParam": "state_completed",
                  "decisionCases": {
                    "false": [
                      {
                        "name": "set_reminder_eca_sub_workflow",
                        "taskReferenceName": "set_reminder_eca_cancelled_stage_3",
                        "inputParameters": {
                          "instanceId": "${workflow.input.something_id}",
                          "event": "cancelled",
                          "timeoutAt": "${workflow.input.something.state.something}",
                          "ecaGroupName": "eca-something-${workflow.input.something_id}",
                          "waitTaskRefName": "wait_for_eca",
                          "workflowRefId": "${workflow.workflowId}"
                        },
                        "type": "SUB_WORKFLOW",
                        "startDelay": 0,
                        "subWorkflowParam": {
                          "name": "set_reminder_eca",
                          "version": 1
                        }
                      }
                    ]
                  },
                  "startDelay": 0
                }
              ]
            ],
            "startDelay": 0
          },
          {
            "name": "join_tasks",
            "taskReferenceName": "join_tasks_all_stage",
            "type": "JOIN",
            "startDelay": 0
          },
          {
            "name": "wait_task",
            "taskReferenceName": "wait_for_eca",
            "type": "WAIT",
            "startDelay": 0
          },
          {
            "name": "fetch_state_something_nullify_eca_sub_workflow",
            "taskReferenceName": "fetch_state_something_nullify_eca_task",
            "inputParameters": {
              "instanceId": "${workflow.input.something_id}",
              "triggerBy": "${wait_for_eca.output.triggerBy}",
              "triggerReason": "${wait_for_eca.output.triggerReason}",
              "somethingType": "${workflow.input.something_type}"
            },
            "type": "SUB_WORKFLOW",
            "startDelay": 0,
            "subWorkflowParam": {
              "name": "fetch_state_something_nullify_eca",
              "version": 1
            }
          }
        ]
      },
      "startDelay": 0
    }
  ],
  "restartable": true,
  "schemaVersion": 2
}

**SUBWORKFLOW** 

{
  "createTime": 1539604622701,
  "name": "fetch_state_something_nullify_eca",
  "description": "",
  "version": 1,
  "tasks": [
    {
      "name": "triggered_by_check_something",
      "taskReferenceName": "triggered_by_check",
      "inputParameters": {
        "trigger_by": "${workflow.input.triggerBy}"
      },
      "type": "DECISION",
      "caseValueParam": "trigger_by",
      "decisionCases": {
        "EVENT_BREACH": [
          {
            "name": "http_post",
            "taskReferenceName": "state_something_change_current",
            "inputParameters": {
              "http_request": {
                "uri": "http://localhost:8080/api/workflow",
                "method": "POST",
                "body": {
                  "name": "state_something_change",
                  "version": 1,
                  "input": {
                    "something_id": "1148189392",
                    "state_status": "unassigned",
                    "predictions": {
                      "assignment": {
                        "something": 1112131231231,
                        "completed": false
                      },
                      "pickup": {
                        "something": 1112131231231,
                        "completed": false
                      },
                      "state": {
                        "something": 1112131231231,
                        "completed": false
                      }
                    },
                    "reason": "UNASSIGNED_EVENT",
                    "something_type": "something",
                    "timestamp": 1223343435
                  }
                },
                "headers": {
                  "Accept": "text/plain"
                }
              }
            },
            "type": "HTTP",
            "startDelay": 0
          }
        ],
        "EVENT": [
          {
            "name": "terminal_event_check_something",
            "taskReferenceName": "terminal_event_check",
            "inputParameters": {
              "trigger_reason": "${workflow.input.triggerReason}"
            },
            "type": "DECISION",
            "caseValueParam": "trigger_reason",
            "decisionCases": {
              "delivered_event": [
                {
                  "name": "http_post",
                  "taskReferenceName": "nullify_eca_1",
                  "inputParameters": {
                    "http_request": {
                      "uri": "http://SOME_IP:8083/api/v1/eca/nullify-by-group",
                      "method": "POST",
                      "body": {
                        "groupName": "eca-something-${workflow.input.instanceId}",
                        "nullifiedBy": "flo"
                      }
                    }
                  },
                  "type": "HTTP",
                  "startDelay": 0
                }
              ],
              "cancelled_event": [
                {
                  "name": "http_post",
                  "taskReferenceName": "nullify_eca_2",
                  "inputParameters": {
                    "http_request": {
                      "uri": "http://SOME_IP:8083/api/v1/eca/nullify-by-group",
                      "method": "POST",
                      "body": {
                        "groupName": "eca-something-${workflow.input.instanceId}",
                        "nullifiedBy": "flo"
                      }
                    }
                  },
                  "type": "HTTP",
                  "startDelay": 0
                }
              ]
            },
            "startDelay": 0
          }
        ]
      },
      "startDelay": 0
    }
  ],
  "restartable": true,
  "schemaVersion": 2
}

So when inside **SUBWORKFLOW** , above defined **PARENT WORKFLOW** is called via start workflow API.

The integer values  1112131231231 which are part of input ("something": 1112131231231), are changed to String "1112131231231". Have tried calling **PARENT WORKFLOW** task (type:sub_workflow) as well, same thing is happening. 

Why is an integer in nested JSON getting converted to string, this is breaking the workflow when the recursive flow is getting triggered.

TASK DEFS

{
 "name": "http_get",
 "description": "http get api call",
 "retryCount": 2,
 "timeoutSeconds": 3,
 "timeoutPolicy": "RETRY",
 "retryLogic": "FIXED",
 "retryDelaySeconds": 5,
 "responseTimeoutSeconds": 5,
 "rateLimitPerFrequency": 0,
 "rateLimitFrequencyInSeconds": 1
}

{
 "name": "http_post",
 "description": "http get api call",
 "retryCount": 2,
 "timeoutSeconds": 3,
 "timeoutPolicy": "RETRY",
 "retryLogic": "FIXED",
 "retryDelaySeconds": 5,
 "responseTimeoutSeconds": 5,
 "rateLimitPerFrequency": 0,
 "rateLimitFrequencyInSeconds": 1
}
@cyzhao @v1r3n

**Comment by mudit3774** [comment]
@rksinha : This PR might fix what you are facing : https://github.com/Netflix/conductor/pull/809
