### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by muraliman** [Netflix/conductor#816]
Hi, Can anyone provide me some inputs on improving the performance and response times in conductor. Any specific components, classes or parameters to start looking at. Currently every HTTP task seems to be taking 3-4 seconds to complete. Are there are improvements that can be done to reduce this time?

**Comment by cyzhao** [comment]
HTTP task invokes external HTTP APIs, do you know where the time is spent? what is your external API latency?

**Comment by jwulf** [comment]
How do I instrument Conductor to measure where time is being spent?

**Comment by jwulf** [comment]
Answering myself: https://github.com/Netflix/conductor/issues/600

**Comment by apanicker-nflx** [comment]
Please refer to the documentation [here](https://netflix.github.io/conductor/metrics/server/#publishing-metrics) to learn more about how to publish metrics from conductor.
