### ISSUE TITLE
conductor persist with redis and cassandra cluster

### ISSUE THREAD

**Issue by gaopc2018** [Netflix/conductor#819]
Hi conductor team,

This is Pengcheng Gao. we are investigating conductor as one of our workflow option.

We have a coupang of questions on backend option. 

1)Is it alright directly use Redis cluster without Dynomite on production?

2) can we use Cassandra as backend? is there any plugin already written for Cassandra.

Kind Regards
PengCheng Gao

**Comment by cyzhao** [comment]
@gaopc2018 yes, you can use redis directly. To your second answer, we are working on Cassandra DAO implementation for workflow execution data now and it will be ready sometime this year.

**Comment by gaopc2018** [comment]
HI @cyzhao,

Thank you for your response.

If we use AWS ElastiCache or Redis directly as the backend, could there is any issue compare with Dynomite? I read Dynomite give a better failover recovery. Does this mean we will rely on the failover recovery of AWS ElastiCache or Redis cluster?

is there anything else we could missing with using AWS ElastiCache or Redis directly?

Kind Regards
GP

**Comment by cyzhao** [comment]
From Conductor's point of view, it should work the same way.

**Comment by apanicker-nflx** [comment]
@gaopc2018 Please check out the [Cassandra DAO implementation](https://github.com/Netflix/conductor/tree/master/cassandra-persistence). This currently only provides a partial implementation, meaning that only the execution DAO has been implemented and the metadata DAO and queue DAO are not implemented yet. 
Please feel free to submit a PR extending from this and we will review and merge the same.
