### ISSUE TITLE
The result of search is not correct occasionally

### ISSUE THREAD

**Issue by chinajuanbob** [Netflix/conductor#826]
version 1.12

This does not happen every time, but hit it while doing heavy load:

query `/api/workflow/search?freeText=correlationId:"26edd416-3367-43c3-9110-8758f0751b19"&query=status="RUNNING"`

return

```
{
    "totalHits": 1,
    "results": [
        {
            "workflowType": "aaa",
            "version": 1,
            "workflowId": "691e502a-c262-4830-a980-241ba82578a1",
            "correlationId": "26edd416-3367-43c3-9110-8758f0751b19",
            "startTime": "2018-10-20T15:23:55Z",
            "updateTime": "2018-10-20T15:29:06Z",
            "endTime": "2018-10-20T15:29:06Z",
            "status": "TERMINATED",       <---------------- here
            "input": "...",
            "output": "...",
            "executionTime": 310967,
            "inputSize": 108,
            "outputSize": 173
        }
    ]
}
```

**Comment by chinajuanbob** [comment]
The same result with query to `/api/workflow/search?freeText=correlationId:"26edd416-3367-43c3-9110-8758f0751b19" AND status:"RUNNING"`, the result of search other statues of given correlationId are correct.

**Comment by saidatta** [comment]
What db are you using? Are you encountering a similar issue with a much more recent version?

**Comment by chinajuanbob** [comment]
redis+es5. I don't get chance to use a more recent version.  Is V2 compatible with V1 clents, I mean, is there any break changes?

**Comment by saidatta** [comment]
I experience a similar issue with 1.2, when i upgraded to 1.9. I didnt seem to encounter the issue.

**Comment by apanicker-nflx** [comment]
@chinajuanbob Are you able to consistently reproduce this issue? Searches against elasticsearch are eventually consistent and you could be seeing some stale data for a little while. 
Please reopen if you think its a different issue.
