### ISSUE TITLE
Make RedisDAO configurable to call async function on indexDAO

### ISSUE THREAD

**Issue by mudit3774** [Netflix/conductor#829]
I see that there are async functions in IndexDAO for indexing and removing workflows and tasks, would it make sense to have it configurable in RedisDAO ? 

Please let me know if I am missing something here.

**Comment by cyzhao** [comment]
@pctreddy any context on these async methods that are not being used?

**Comment by apanicker-nflx** [comment]
@mudit3774 The RedisDAO does not call IndexDAO internally anymore. This has been extracted to a higher level service. It would be a nice-to-have enhancement to be able to call the async methods within the IndexDAO from within this layer. Please feel free to contribute to this enhancement.
