### ISSUE TITLE
Is Javascript client necessary?

### ISSUE THREAD

**Issue by donglaizhang** [Netflix/conductor#832]
Hey Conductor Team,

I found Conductor provided three languages clients including JAVA, python and Golang. Does the team have plan to make a Javascript client-sdk for server side javascript to use? I think most logic could be same with other client. 

Regards,
Donglai

**Comment by cyzhao** [comment]
@donglaizhang we don't have a need for it in the near future, please contribute and we will be more than happy to review and merge.

**Comment by chinajuanbob** [comment]
https://github.com/chinajuanbob/conductor-nodejs-worker

**Comment by donglaizhang** [comment]
thank you @chinajuanbob. the implementation is relatively simple, and we already have implemented one to use internally.

**Comment by boshido** [comment]
I think this one may relate
https://github.com/Netflix/conductor/issues/867
