### ISSUE TITLE
Failure to start conductor server after upgrading to release version v2.0.0

### ISSUE THREAD

**Issue by wesleysong9** [Netflix/conductor#833]
Hi Conductor team,

Previously we use the release version v1.12.3, when starting the conductor server by gradle task conductor:server server with our customized config, it works fine. We have our customized configuration to connect to our redis cluster and ElasticSearch. 

Below attached our customized configuration file for the conductor server(Using redis cluster and elasticsearch)

server.properties

db=redis_cluster
workflow.dynomite.cluster.hosts=reconciliation-ecc.nquffl.clustercfg.apn2.cache.amazonaws.com:6379:ap-northeast-2c
workflow.dynomite.cluster.name=reconciliation-ecc
workflow.dynomite.connection.maxConnsPerHost=31
workflow.namespace.prefix=conductor
workflow.namespace.queue.prefix=conductor_queues
queues.dynomite.threads=10
queues.dynomite.nonQuorum.port=6379
workflow.elasticsearch.instanceType=external
workflow.elasticsearch.url=10.213.0.252:9300
workflow.elasticsearch.index.name=conductor
workflow.elasticsearch.version=5
EC2_AVAILABILITY_ZONE=ap-northeast-2c

But we find today that there is a new release version of v2.0.0, so we upgraded the conductor version to the latest one. After upgraded, we meet the below issue when start the conductor server.

Error message:
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for com.netflix.dyno.queues.ShardSupplier was bound.
  while locating com.netflix.dyno.queues.ShardSupplier
    for the 3rd parameter of com.netflix.conductor.dyno.RedisQueuesProvider.<init>(RedisQueuesProvider.java:32)
  at com.netflix.conductor.dao.RedisWorkflowModule.configure(RedisWorkflowModule.java:33)

2) No implementation for redis.clients.jedis.JedisCommands annotated with @com.google.inject.name.Named(value=DynoReadClient) was bound.
  while locating redis.clients.jedis.JedisCommands annotated with @com.google.inject.name.Named(value=DynoReadClient)
    for the 2nd parameter of com.netflix.conductor.dyno.RedisQueuesProvider.<init>(RedisQueuesProvider.java:32)
  at com.netflix.conductor.dao.RedisWorkflowModule.configure(RedisWorkflowModule.java:33)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.netflix.conductor.bootstrap.Main.main(Main.java:53)

Task :conductor-server:server FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conductor-server:server'.

Can anyone help on this? what is missing for the configuration for the latest release version?

Thanks!

**Comment by wesleysong9** [comment]
I do not think this #835 fixed the issue I mentioned, can anyone support for this issue?

**Comment by cyzhao** [comment]
#927 should fix this.
