### ISSUE TITLE
when i use standared alone redis, i can't trigger a workflow instance, but in-memory-mode can

### ISSUE THREAD

**Issue by ztyandjw** [Netflix/conductor#837]
hi,

in-memory mode is ok, but when i changed the mode to single redis.
i can't trigger a workflow instance, the workflow id return to me, but my worker instance did not work... then i changed to in-memory,  erverything is ok....

my app.config

db=redis
workflow.dynomite.cluster.hosts=127.0.0.1:6379:us-east-1e
workflow.dynomite.connection.maxConnsPerHost=31
queues.dynomite.nonQuorum.port=6379

**Comment by pavansistla** [comment]
Can you check "EC2_AVAILABILITY_ZONE" is pointing to us-east-1e

**Comment by ztyandjw** [comment]
> Can you check "EC2_AVAILABILITY_ZONE" is pointing to us-east-1e

thank you, fix it

**Comment by jwulf** [comment]
Bump, can we close this now?

**Comment by apanicker-nflx** [comment]
Closing this issue as it has been answered/fixed.

**Comment by 0532** [comment]
m
