### ISSUE TITLE
API for task output

### ISSUE THREAD

**Issue by ajayaks** [Netflix/conductor#84]
Hi, 

I have 3 questions , please suggest.

1st question :
In UI we can see the task status inside workflow and the input/output of the task.

I want to get the output of task so is there any apis for that ?

2nd question

I have created a workflow with some 2-3 tasks now i want to change the workflow means i want to add more task or replace the one , current apis is throwing exception now.

3rd question
Current UI is basic for getting the data , do we have support for post in current UI so that we can define some tasks or workflow from UI?

Please suggest.
Regards
Ajay

**Comment by v1r3n** [comment]
@ajayaks check out the swagger APIs - there is an API for getting task details ```GET /tasks/{id}``` that will allow you to get the task details along with the output.

For updating, which API are you using and what exception are you getting?  Please always include these details.  Some of the update APIs take an array of objects, so you might have to wrap your workflow definition inside a JSON array when sending an update.

Support for updates from UI is something we plan to add in the future.
