### ISSUE TITLE
ISSUE: No implementation for com.netflix.dyno.queues.ShardSupplier was bound

### ISSUE THREAD

**Issue by JasperB** [Netflix/conductor#842]
Hi Conductor @cyzhao ,

When we try to use v2.0.0 to start the conductor server, we met this issue caused by No implementation for com.netflix.dyno.queues.ShardSupplier, details:
1) No implementation for com.netflix.dyno.queues.ShardSupplier was bound.
  while locating com.netflix.dyno.queues.ShardSupplier
    for the 3rd parameter of com.netflix.conductor.dyno.RedisQueuesProvider.<init>(RedisQueuesProvider.java:32)
  at com.netflix.conductor.dao.RedisWorkflowModule.configure(RedisWorkflowModule.java:33)

2) No implementation for redis.clients.jedis.JedisCommands annotated with @com.google.inject.name.Named(value=DynoReadClient) was bound.
  while locating redis.clients.jedis.JedisCommands annotated with @com.google.inject.name.Named(value=DynoReadClient)
    for the 2nd parameter of com.netflix.conductor.dyno.RedisQueuesProvider.<init>(RedisQueuesProvider.java:32)
  at com.netflix.conductor.dao.RedisWorkflowModule.configure(RedisWorkflowModule.java:33)

Seems the inject failed by @com.google.inject.name.Named(value=DynoReadClient) was bound.
  while locating redis.clients.jedis.JedisCommands, could you help to check it?

**we're using the server.properties as:**
_db=redis_cluster
#Dynomite Cluster details.
#format is host:port:rack separated by semicolon
workflow.dynomite.cluster.hosts=xxxx.nquffl.clustercfg.apn2.cache.amazonaws.com:6379:ap-northeast-2c

workflow.dynomite.cluster.name=reconciliation-ecc
workflow.dynomite.connection.maxConnsPerHost=31
#namespace for the keys stored in Dynomite/Redis
workflow.namespace.prefix=conductor
#namespace prefix for the dyno queues
workflow.namespace.queue.prefix=conductor_queues
#no. of threads allocated to dyno-queues
queues.dynomite.threads=10
#non-quorum port used to connect to local redis.  Used by dyno-queues
queues.dynomite.nonQuorum.port=6379
workflow.elasticsearch.instanceType=external
#Transport address to elasticsearch
workflow.elasticsearch.url=10.213.x.x:9300
#Name of the elasticsearch cluster
workflow.elasticsearch.index.name=conductor
#Elasticsearch major release version.
workflow.elasticsearch.version=5
#For a single node dynomite or redis server, make sure the value below is set to same as rack specified in the "workflow.dynomite.cluster.hosts" property.
EC2_AVAILABILITY_ZONE=ap-northeast-2c_

**Comment by cyzhao** [comment]
@JasperB this is because RedisClusterModule missed two bindings, one for ShardSupplier and one for JedisCommands named by READ_CLIENT_INJECTION_NAME, since we don't use it so the problem is not caught, we will fix it but please feel free to send a PR if you need the fix sooner.

**Comment by JasperB** [comment]
@cyzhao Thank you for the reply this. I have one question before send the PR, does these two bindings will cause the problem if we use the redis_cluster model? with above configuration it running fine in release 1.12.

**Comment by sivacham** [comment]
I am also facing the same issue while deploying to PCF . Did the issue get resolved or do we have any release that has fixed this issue ?

**Comment by rksinha** [comment]
@cyzhao @JasperB @mudit3774 PR for above fix : https://github.com/Netflix/conductor/pull/927
