### ISSUE TITLE
EXPONENTIAL_BACKOFF Retry Logic is not really exponential

### ISSUE THREAD

**Issue by houz42** [Netflix/conductor#844]
The [task definition](https://netflix.github.io/conductor/metadata/#task-definition) in the document says 

> EXPONENTIAL_BACKOFF : reschedule after `retryDelaySeconds  * attempNo`

But it is not really exponential. It should be `retryDelaySeconds ** attempNo`.

**Comment by cyzhao** [comment]
Agree, but it should be retryDelaySeconds * (2 ** retryCount), we will fix it.
