### ISSUE TITLE
Clarification on SimpleTask mapper which sets task type as name

### ISSUE THREAD

**Issue by jagadeeshb22** [Netflix/conductor#845]
@cyzhao / @v1r3n  / @jvemugunta 

I saw the class level comment -- **There is not type defined for simples task**
And also found below lines in 
https://github.com/Netflix/conductor/blob/dev/core/src/main/java/com/netflix/conductor/core/execution/mapper/SimpleTaskMapper.java

simpleTask.setTaskType(taskToSchedule.getName());
simpleTask.setTaskDefName(taskToSchedule.getName());

**Comment by apanicker-nflx** [comment]
@jagadeeshb22 `SIMPLE` task is any task that is executed by a worker outside of Conductor. In the `SimpleTaskMapper`, the task type is set to the task definition name.
