### ISSUE TITLE
Conductor stops logging

### ISSUE THREAD

**Issue by harshkumar1** [Netflix/conductor#863]
There are couple of exception stack trace in Conductor Server post that even though the server works fine but there are no logs generated across server, dynomite & elastic search
Deployment: k8s Cluster

Attached here is the Conductor server log
[flowmanager-server.log](https://github.com/Netflix/conductor/files/2571595/flowmanager-server.log)

**Comment by kishorebanala** [comment]
@harshkumar1 I'm not sure I understood "there are no logs generated across server, dynomite & elastic search". I see a few failed requests, and everything else looks fine.
```
94622226 [qtp205496410-5587] ERROR com.netflix.conductor.server.resources.ApplicationExceptionMapper  - No such workflow found by id: undefined
com.netflix.conductor.core.execution.ApplicationException: No such workflow found by id: undefined
```
If you're looking for logs from all other service implementations you mentioned, consider running at least one successful workflow implementation.

Closing this issue as it has been a while. Please feel free to open another issue if this doesn't resolve your concern.
