### ISSUE TITLE
http_request fails with Can not deserialize instance of java.lang.String out of START_OBJECT token

### ISSUE THREAD

**Issue by benbenja** [Netflix/conductor#87]
Hi Team,

        I am trying to register kitchensink workflow and getting following error for HTTP task type. I am using devopsopen/docker-netflix-conductor image. Could you please help with the same

{
	  "type": "HTTP",
      "name": "search_elasticsearch",
      "taskReferenceName": "get_es_1",
      "inputParameters": {
        "http_request": {
          "uri": "http://localhost:9200/wfe/workflow/_search?size=10",
          "method": "GET"
        }
      }
    }

INTERNAL_ERROR - Can not deserialize instance of java.lang.String out of START_OBJECT token\n at [Source: HttpInputOverHTTP@778db043[c=4042,s=STREAM]; line: 1, column: 3511] (through reference chain: com.netflix.conductor.common.metadata.workflow.WorkflowDef[\"tasks\"]->java.util.LinkedList[3]->com.netflix.conductor.common.metadata.workflow.WorkflowTask[\"inputParameters\"]->java.util.LinkedHashMap[\"http_request\"])","instance":"server_id"}

Thanks,
Ben

**Comment by v1r3n** [comment]
Seems like you have an older version of Conductor - can you try with the latest from the dev/master branch?

**Comment by v1r3n** [comment]
@benbenja if you are using docker, update your docker image.
