### ISSUE TITLE
[BUG]Multiple workers concurrent race Issue 

### ISSUE THREAD

**Issue by JasperB** [Netflix/conductor#871]
We have one workflow with 3 tasks, one of them is dynamically fork task, when we start 3 clients with 300 workers on each client, then ran some tests we found some issue regarding the workflow status inconsistently. 
We took some time to investigate this problem, seems it caused by the multi-thread issue, one thread index the workflow as "COMPLETED" to ES, but later(several mis-seconds) the other task thread index the workflow as "RUNNING" to ES because in this thread the workflow instance still own the status.termina as false, that's cause the workflow status incorrect.

@cyzhao @v1r3n Did you guys met this issue? Any suggestion to fix this？

![1542523462346](https://user-images.githubusercontent.com/7287153/48669488-8cf37580-eb40-11e8-92d4-19e5fbe035f3.jpg)

**Comment by JasperB** [comment]
From above screenshot, you can see the first thread index the workflow as "TIMEOUT" to ES, but later the other thread index the workflow as "RUNNING" to ES, that means sometimes the workflow status will be override by the later threads.

**Comment by JasperB** [comment]
@cyzhao @v1r3n did you guys met this issue, it also happened in poll tasks, means multiple workers may poll and ack same task, it's a bug which will cause the same task execute multiple times, do you guys have any idea to fix this issue? BTW we're using the aws redis-cluster and 4 clients server with multiple workers in each client.

Multiple worker race the tasks as below:
![image](https://user-images.githubusercontent.com/7287153/48890620-48cfe000-ee74-11e8-8b24-536a58434281.png)

**Comment by cyzhao** [comment]
@JasperB sorry for late response, we are aware of this issue and will look into this soon. However, if you already have plan to fix this please let us know.

@apanicker-nflx @kishorebanala

**Comment by kishorebanala** [comment]
@JasperB We have this on our roadmap, though not a higher priority. Please feel free to send us a PR, if this needs to be fixed sooner. Thanks for reporting the issue.

**Comment by HenryLauu** [comment]
any updates? I got a task polled by workers twice. 
`"retryCount":0,
         "seq":2,
         "pollCount":2,`

**Comment by kishorebanala** [comment]
@HenryLauu Can you provide more details about task being poll twice by workers please? It'd help to see the workflow execution with timestamps, posted somewhere as a snippet.

**Comment by HenryLauu** [comment]
Hi @kishorebanala . Sorry for the delay . Here are some task details:
"ownerApp": "",
   "createTime": 1599471668218,
   "updateTime": 1599471678635,
   "status": "FAILED",
   "endTime": 1599471678635,
   "workflowId": "4c24f6ef-76fe-49f2-b723-612261045125",
   "parentWorkflowId": "f6a3cbf8-8a31-453b-8761-f37f767871eb",
   "parentWorkflowTaskId": "7eee29a5-ec90-4577-8f12-1eea3b3ea3ff",

another poll:
"ownerApp": "",
   "createTime": 1599471668156,
   "updateTime": 1599471726170,
   "status": "COMPLETED",
   "endTime": 1599471726170,
   "workflowId": "cd537c38-4c0d-4e75-963f-34fb2a335509",
   "parentWorkflowId": "f6a3cbf8-8a31-453b-8761-f37f767871eb",
   "parentWorkflowTaskId": "7eee29a5-ec90-4577-8f12-1eea3b3ea3ff",

**Comment by HenryLauu** [comment]
> Hi @kishorebanala . Sorry for the delay . Here are some task details:
> "ownerApp": "",
> "createTime": 1599471668218,
> "updateTime": 1599471678635,
> "status": "FAILED",
> "endTime": 1599471678635,
> "workflowId": "4c24f6ef-76fe-49f2-b723-612261045125",
> "parentWorkflowId": "f6a3cbf8-8a31-453b-8761-f37f767871eb",
> "parentWorkflowTaskId": "7eee29a5-ec90-4577-8f12-1eea3b3ea3ff",
> 
> another poll:
> "ownerApp": "",
> "createTime": 1599471668156,
> "updateTime": 1599471726170,
> "status": "COMPLETED",
> "endTime": 1599471726170,
> "workflowId": "cd537c38-4c0d-4e75-963f-34fb2a335509",
> "parentWorkflowId": "f6a3cbf8-8a31-453b-8761-f37f767871eb",
> "parentWorkflowTaskId": "7eee29a5-ec90-4577-8f12-1eea3b3ea3ff",

I am using mysql as storage and zookeeper as lock service

**Comment by HenryLauu** [comment]
hi @kishorebanala any advice to fix this problem? We have this issue in production

**Comment by HenryLauu** [comment]
please refer to this issue for details: #1859
