### ISSUE TITLE
MySQL Perf. Degradation Multiple Workers

### ISSUE THREAD

**Issue by RileyMichael** [Netflix/conductor#872]
We're currently running into performance issues when running (small amount) multiple workers against a MySQL backed conductor.

- Conductor Server pointed to MySQL DB. (K8s, 2 cpu & 1500Mi)
- 5 workers, 4 threads per task, 1s poll delay. (each worker is a K8s pod, 2 cpu & 1500Mi)
- External ES
- SQL related config:
```
conductor.mysql.connection.idle.timeout: 300000
conductor.mysql.connection.pool.idle.min: 20
conductor.mysql.connection.pool.size.max: 100
conductor.mysql.transaction.isolation.level: TRANSACTION_READ_COMMITTED
```

Various logs occurring frequently:
```
com.netflix.conductor.dao.mysql.MySQLQueueDAO  - CONFLICT Could not pop all messages for given ids: [9a01cf7a-152e-43a2-9d96-bb7d81e4cfe6] (0 messages were popped)
com.netflix.conductor.core.execution.WorkflowExecutor  - Task is already completed as COMPLETED@1542754301428, workflow status=RUNNING, workflowId=29377792-8fe1-4e01-a3e8-f1f4426fa493, taskId=9a01cf7a-152e-43a2-9d96-bb7d81e4cfe6
```

Running a single worker, a workflow will complete in ~60 seconds. As the number of polling workers scales, so does the completion time (and the UI because visibly un-performant). (e.g. 4 workers ~120 seconds, 6 ~200 seconds)

Is this a known issue (SQL not being performant) or is this a misconfiguration / env. issue?

Thanks.

**Comment by dskarataev** [comment]
@RileyMichael why did you close this? How did you fix the problem?

**Comment by RileyMichael** [comment]
@dskarataev It was an environment issue, too much latency between the conductor servers & the database which became apparent as we added more polling workers.

**Comment by ravisund** [comment]
@RileyMichael  can you provide insight into environment issue ? how did reduce the latency from 200secs to 20secs ?

**Comment by belencoding** [comment]
i meet the same issue, How do you configure it? thanks
