### ISSUE TITLE
conductor:server can not start

### ISSUE THREAD

**Issue by raozhiyong11** [Netflix/conductor#882]
I used version `conductor-2.1.0`  and install with docker:

> `cd docker`
> `docker-compose up`

conductor:ui,v1r3n/dynomite,elasticsearch:2.4  was started success,but conductor:server throws error:

`Starting Conductor server
Property file: config.properties
config.properties
Using 'config.properties'
Using config file/app/config/config.properties
0    [main] INFO  com.netflix.conductor.bootstrap.ModulesProvider  - Starting conductor server using dynomite/redis cluster.
61   [main] INFO  com.netflix.conductor.bootstrap.ModulesProvider  - External payload storage is not configured, provided: , supported values are: [S3]
java.lang.IllegalArgumentException: No enum constant com.netflix.conductor.bootstrap.ModulesProvider.ExternalPayloadStorageType.
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.netflix.conductor.bootstrap.ModulesProvider$ExternalPayloadStorageType.valueOf(ModulesProvider.java:37)
        at com.netflix.conductor.bootstrap.ModulesProvider.selectModulesToLoad(ModulesProvider.java:105)
        at com.netflix.conductor.bootstrap.ModulesProvider.get(ModulesProvider.java:50)
        at com.netflix.conductor.bootstrap.Main.main(Main.java:53)
516  [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: HTTP
697  [main] INFO  com.netflix.conductor.contribs.http.HttpTask  - HttpTask initialized...
697  [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: JSON_JQ_TRANSFORM
2276 [main] INFO  com.netflix.archaius.guice.ConfigurationInjectingListener  - Initializing ConfigurationInjectingListener
2572 [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
2572 [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Getting Hosts from TokenMapSupplier
2577 [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Adding host connection pool for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
2577 [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Priming connection pool for host:Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null], with conns:10
2682 [pool-3-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 10 of 10 to Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
2690 [main] INFO  com.netflix.dyno.connectionpool.TokenPoolTopology  - Adding Host to TopologyHost [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
2693 [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - registered mbean com.netflix.dyno.connectionpool.impl:type=MonitorConsole
2697 [main] INFO  com.netflix.dyno.jedis.DynoJedisClient  - Starting connection pool for app conductor
2697 [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Getting Hosts from TokenMapSupplier
2697 [pool-6-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Adding host connection pool for host: Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
2698 [pool-6-thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Priming connection pool for host:Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null], with conns:10
2703 [pool-6-thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Successfully primed 10 of 10 to Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
2705 [main] INFO  com.netflix.dyno.connectionpool.TokenPoolTopology  - Adding Host to TopologyHost [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
2705 [main] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - mbean com.netflix.dyno.connectionpool.impl:type=MonitorConsole has already been registered !
2712 [main] INFO  com.netflix.conductor.dyno.RedisQueuesProvider  - DynoQueueDAO initialized with prefix conductor_queues.test!
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
5035 [main] INFO  com.netflix.conductor.core.events.EventProcessor  - Event Processing is ENABLED. executorThreadCount set to 2
5037 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - System Task Worker initialized with 10 threads and a callback time of 30 seconds and queue size: 100 with pollCount: 10 and poll interval: 50
5037 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: SUB_WORKFLOW
5037 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: WAIT
5037 [main] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Adding the queue for system task: EVENT
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{PM6hs30pSfCezoydcl28eQ}{es}{172.21.0.3:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
        at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
        at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:730)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
        at com.netflix.conductor.dao.es5.index.ElasticSearchDAOV5.setup(ElasticSearchDAOV5.java:157)
        at com.netflix.conductor.bootstrap.Main.main(Main.java:71)
5041 [Thread-3] INFO  com.netflix.conductor.core.execution.tasks.SystemTaskWorkerCoordinator  - Started listening for system task: HTTP
5042 [Thread-1] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Removing host dyno1 from selectionStrategy, cpHealthTracker, cpMonitor
5045 [Thread-1] INFO  com.netflix.dyno.connectionpool.TokenPoolTopology  - Removing Host from TopologyHost [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
5045 [Thread-1] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Shutting down connection pool for host:Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
5044 [Thread-2] INFO  com.netflix.dyno.connectionpool.impl.ConnectionPoolImpl  - Removing host dyno1 from selectionStrategy, cpHealthTracker, cpMonitor
5045 [Thread-2] INFO  com.netflix.dyno.connectionpool.TokenPoolTopology  - Removing Host from TopologyHost [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]
5045 [Thread-2] INFO  com.netflix.dyno.connectionpool.impl.HostConnectionPoolImpl  - Shutting down connection pool for host:Host [hostname=dyno1, ipAddress=null, port=8102, rack: us-east-1c, datacenter: us-east-1, status: Up, hashtag=null]`

Does anyone else have this problem,How to solve ?

**Comment by artpdr** [comment]
@raozhiyong11 use the last conductor version (the one in master or dev...).  
I think your docker-compose might be outdated.... This is the updated one: https://github.com/Netflix/conductor/blob/master/docker/docker-compose.yaml
