### ISSUE TITLE
Bug: timeoutSeconds / responseTimeoutSeconds not making task re-scheduled

### ISSUE THREAD

**Issue by LiranBri** [Netflix/conductor#883]
Hello,

I tried to use  *responseTimeoutSeconds* but task never gets re-scheduled for another processing.

I also tried with timeoutSeconds instead of responseTimeoutSeconds- and got the same behavior.
also note that when I tried timeoutSeconds, and looked in the UI at the json of the task, it didn't specify "timeoutSeconds" there.
in addition, in the docs it says "Time in milliseconds" even though the name suggests its "seconds" .. so one of them is probably wrong or misleading

for your convenience, here are the exact curl commands to reproduce the bug:

1. create the task definition
```
curl -X POST \
  http://localhost:8080/api/metadata/taskdefs \
  -H 'Content-Type: application/json' \
  -d '[
	{
	  "name": "retry-task",
	  "retryCount": 1,
	  "responseTimeoutSeconds": 10,
	  "inputKeys": ["date"],
	  "outputKeys": ["year"],
	  "timeoutPolicy": "RETRY",
	  "retryLogic": "FIXED",
	  "retryDelaySeconds": 0
	}
]'
```

2. create the workflow definition
```
curl -X POST \
  http://localhost:8080/api/metadata/workflow \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "retry-task",
  "description": "Gets date and returns year from it",
  "version": 1,
  "tasks": [
    {
      "name": "retry-task",
      "taskReferenceName": "retry-task",
      "type": "SIMPLE",
      "inputParameters": {
        "date": "${workflow.input.date}"
      }
    }
  ],
  "outputParameters": {
  },
  "schemaVersion": 2
}'
```

3. start a new workflow instance
```
curl -X POST \
  http://localhost:8080/api/workflow/retry-task \
  -H 'Content-Type: application/json' \
  -d '{"date": "1800-01-01"}'
```

4. poll pending task as worker (move it to IN_PROGRESS)
```
curl -X GET \
  'http://localhost:8080/api/tasks/poll/batch/retry-task?count=1&timeout=1000&workerid=postman' \
  -H 'Content-Type: application/json' \
```

5. send ack as worker (take task id from previous response)
```
curl -X POST \
  http://localhost:8080/api/tasks/e134b6c8-7221-42a4-ab2f-9c3c382ab14a/ack \
  -H 'Content-Type: application/json' \
```

6. no matter how much time I wait, task is still in status IN_PROGRESS, and if I repeat step (4) to poll pending tasks I get an empty response

If i can do anything else to help investigate this, please let me know

my required flow is as follows:

task is polled by worker
worker sends ack that he received the task
worker machine crashes
worker come back to life
after 10 seconds without any result status of 'COMPLETED', the task would be retried
task is polled (again) by worker
...
...
this process would happen again and again up to 3 times, or until 'COMPLETED' status is reported

**Comment by cyzhao** [comment]
@LiranBri are you getting this when you run it locally with docker? It looks like sweeper is not running properly in your setup hence timeouts are not enforced.

**Comment by LiranBri** [comment]
Hi @cyzhao , I realize that it's open source and you are doing everything voluntarily. but since I'm struggling with this issue for about 2 months now I would really appreciate if you can try to take a second look at this issue. thank you!

**Comment by saidatta** [comment]
I believe he might be referring WorkflowSweeper within the codebase. Take a look at this https://github.com/Netflix/conductor/issues/362 . I am not sure if it is the solution but might give you some direction.

**Comment by LiranBri** [comment]
thank you @saidatta . after adding this line of code, the task indeed goes into TIMED_OUT and a new one is created in SCHEDULED mode, which can then be polled again.

however, the second one doesn't get timed out if there is no response for it, so the second task stays at IN PROGRESS and the workflow stays at RUNNING stay

**Comment by apanicker-nflx** [comment]
@LiranBri We tested this out in our machine using the configuration you posted above but were unable to reproduce the issue. The task correctly TIMED_OUT after the retry as well and the workflow moved to a FAILED status. Can you check the workflow sweeper frequency configuration on your deployment and ensure that the workflow sweeper is running.

**Comment by mstz** [comment]
I met the same issue, too.
The sweeper sometimes took affect, sometimes failed.
There was some timeout tasks without being rescheduled or marked staying 'IN_PROGRESS'.

**Comment by mstz** [comment]
![image](https://user-images.githubusercontent.com/11886800/56208884-c941e800-6084-11e9-8f61-cc380185e72f.png)

**Comment by 77yang** [comment]
I have the same issue😓

**Comment by kishorebanala** [comment]
@77yang Can you provide more details to help reproduce this please? cc: @apanicker-nflx

**Comment by 77yang** [comment]
@kishorebanala  I restarted it, issue gone😓
