### ISSUE TITLE
Have a fork with three tines and two have waits in them

### ISSUE THREAD

**Issue by johnlongo** [Netflix/conductor#884]
I'm running conductor v1.12 and have a fork with three tines, two of which have waits. when I post complete the two waiting tasks I still need to manually post complete the join. I would think the join would auto complete once the two waiting tasks are posted complete. Is this a bug or do I sill need to post complete the join task as well. any information is greatly appreciated.

**Comment by apanicker-nflx** [comment]
@johnlongo Can you please try reproducing this with a newer version of Conductor (>=v2.5)? 
The join task need to be manually completed and should auto complete once the tines are completed. 
Please reopen the issue if you are able to reproduce using the latest versions.
