### ISSUE TITLE
Support for Elasticsearch 6

### ISSUE THREAD

**Issue by emersonborges** [Netflix/conductor#889]
We are planning to implement the support for Elasticsearch 6 for our company needs and send the PR soon. But we would like an opinion on how to handle both, Elasticsearch 5 and Elasticsearch 6.

Options:

- Support for both with some kind of configuration, but we don't know how to do that exactly.
- Support for only Elasticsearch 6 in new versions and Elasticsearch 5 in older versions.

Any suggestions?

**Comment by ahai1980** [comment]
only Elasticsearch 6 in new versions
