### ISSUE TITLE
Exception passing json as workflow input

### ISSUE THREAD

**Issue by ajayaks** [Netflix/conductor#89]
Hi, 

I would like to pass json structure to workflow input and all other tasks in the workflow would use the same json for their input tasks.  Like "body":"${workflow.input.**collector**}"

Problem is when i adding below json in workflow in input parameter i am getting error below.

  "inputParameters": [
      {
        "**collector**":{
  "id": "f6c25e71-0e38-428b-b895-19dceb4602fb",
  "startDate": "2017-01-01T16:21:00Z",
  "endDate": "2019-01-01T16:21:00Z",
  "dateCreated": "2017-01-03T16:33:00.996Z",
  "dateModified": "2017-01-03T16:33:00.996Z",
  "status": "CLOSED",
  "info": {},
  "Instances": {
    "Instance": {},
    }
  }
 }   
 ]

{
  "code": "INTERNAL_ERROR",
  "message": "INTERNAL_ERROR - Can not deserialize instance of java.lang.String out of START_OBJECT token\n at [Source: HttpInputOverHTTP@1efbf3eb[c=7305,s=STREAM]; line: 163, column: 7] (through reference chain: java.util.ArrayList[0]->com.netflix.conductor.common.metadata.workflow.WorkflowDef[\"inputParameters\"]->java.util.ArrayList[0])",
  "instance": "Ajays-MacBook-Pro.local"
}

Please suggest.

Regards
Ajay

**Comment by v1r3n** [comment]
@ajayaks you are passing inputParameters as an array with a map inside.  inputParameter should be a JSON map.  The JSON body you posted above is not a valid JSON - can you send in the JSON input you are sending?

Also, can you confirm you are using the latest from dev branch?

**Comment by ajayaks** [comment]
Hi viren , 

i want to pass below complete json to multiple tasks. So i think we have to do something "${workflow.input.<>}"


{
"id": "f6c25e71-0e38-428b-b895-19dceb4602fb",
"startDate": "2017-01-01T16:21:00Z",
"endDate": "2019-01-01T16:21:00Z",
"dateCreated": "2017-01-03T16:33:00.996Z",
"dateModified": "2017-01-03T16:33:00.996Z",
"status": "CLOSED",
"info": {},
"Instances": {
"Instance": {},
}
}

No , i am using little old code. Any new changes we have or any big change.

**Comment by v1r3n** [comment]
@ajayaks Can you send me the full JSON payload you are using to start the workflow that is giving the exception?  The one you pasted in the beginning of the thread is not a valid JSON.

**Comment by ajayaks** [comment]
Hi Viren, below is the json , its a valid json.
{
  "id": "f6c25e71-0e38-428b-b895-19dceb4602fb",
  "startDate": "2017-01-01T16:21:00Z",
  "endDate": "2019-01-01T16:21:00Z",
  "dateCreated": "2017-01-03T16:33:00.996Z",
  "dateModified": "2017-01-03T16:33:00.996Z",
  "status": "CLOSED",
  "order": {
    "id": "830c8c47-79b3-43ed-9459-c1b4dee47bad",
    "startDate": "2017-01-01T16:21:00Z",
    "endDate": "2019-01-01T16:21:00Z",
    "status": "INCOMPLETE",
    "name": "THY-JAN17-010821",
    "description": "THY-JAN17-010821",
    "Groups": {
      "Group": {
        "id": "JAN",
        "name": "THY-JAN17",
        "startDate": "2017-01-01T16:21:00Z",
        "endDate": "2019-01-01T16:21:00Z",
        "defaultDisplayGroup": "false"
      }
    },
    "deadlines": {
      "shipmentdate": "2016-12-22T16:21:00Z"
    }
  },
  "Instances": {
    "Instance": {
      "Profile": {
        "name": "TEST",
        "id": "a2507eb5-ae44-4502-9a00-6516ebf82218",
        "status": "AVAILABLE",
        "veichle": {
          "name": "AB321",
          "info": {
            "id": "",
            "name": ""
          }
        }
      },
      "definitionCollection": {},
      "Collection": {},
      "MetadataCollection": {
        "Metadata": []
      }
    }
  }
}

**Comment by v1r3n** [comment]
@ajayaks are you passing this as workflow input?  Sorry, its a bit confusing, are you getting error when you try to start the workflow? If that is the case, is the above JSON you pass as the input to the workflow?

**Comment by ajayaks** [comment]
Yes, i am passing the above json as input parameter to workflow as multiple tasks need the same json so if start defining the json for each tasks in one workflow then workflow definition  will be very big.

I am getting the error while updating or creating the workflow. If i simply remove the above json from workflow input and define it under any task inputparameter then its working but not as input to workflow.

**Comment by v1r3n** [comment]
@ajayaks thanks.  I was able to start the kitchensink workflow by passing the above JSON as input.
I passed the above JSON as it is without any changes.

Here is the workflow that got started and input:

```json
{
  "createTime": 1487574070656,
  "updateTime": 1487574070678,
  "status": "RUNNING",
  "endTime": 0,
  "workflowId": "99efad3e-8976-42d3-9b06-0f406b1eac45",
  "tasks": [
    {
      "taskType": "task_1",
      "status": "SCHEDULED",
      "inputData": {
        "mod": null,
        "oddEven": null
      },
      "referenceTaskName": "task_1",
      "retryCount": 0,
      "seq": 1,
      "pollCount": 0,
      "taskDefName": "task_1",
      "scheduledTime": 1487574070671,
      "startTime": 0,
      "endTime": 0,
      "updateTime": 1487574070671,
      "startDelayInSeconds": 0,
      "retried": false,
      "callbackFromWorker": true,
      "responseTimeoutSeconds": 3600,
      "workflowInstanceId": "99efad3e-8976-42d3-9b06-0f406b1eac45",
      "taskId": "49aee0f7-d93d-4c47-9bf5-9317e31ed088",
      "callbackAfterSeconds": 0,
      "polledTime": 0,
      "queueWaitTime": 0
    }
  ],
  "input": {
    "id": "f6c25e71-0e38-428b-b895-19dceb4602fb",
    "startDate": "2017-01-01T16:21:00Z",
    "endDate": "2019-01-01T16:21:00Z",
    "dateCreated": "2017-01-03T16:33:00.996Z",
    "dateModified": "2017-01-03T16:33:00.996Z",
    "status": "CLOSED",
    "order": {
      "id": "830c8c47-79b3-43ed-9459-c1b4dee47bad",
      "startDate": "2017-01-01T16:21:00Z",
      "endDate": "2019-01-01T16:21:00Z",
      "status": "INCOMPLETE",
      "name": "THY-JAN17-010821",
      "description": "THY-JAN17-010821",
      "Groups": {
        "Group": {
          "id": "JAN",
          "name": "THY-JAN17",
          "startDate": "2017-01-01T16:21:00Z",
          "endDate": "2019-01-01T16:21:00Z",
          "defaultDisplayGroup": "false"
        }
      },
      "deadlines": {
        "shipmentdate": "2016-12-22T16:21:00Z"
      }
    },
    "Instances": {
      "Instance": {
        "Profile": {
          "name": "TEST",
          "id": "a2507eb5-ae44-4502-9a00-6516ebf82218",
          "status": "AVAILABLE",
          "veichle": {
            "name": "AB321",
            "info": {
              "id": "",
              "name": ""
            }
          }
        },
        "definitionCollection": {},
        "Collection": {},
        "MetadataCollection": {
          "Metadata": []
        }
      }
    }
  },
  "output": {
    "workflowIds": [],
    "statues": []
  },
  "workflowType": "kitchensink",
  "version": 1,
  "schemaVersion": 2,
  "startTime": 1487574070656
}
```

**Comment by ajayaks** [comment]
Strange , i am trying to update workflow and below the json for workflow update , you can use the same for creating a new workflow but i am getting same issue.  Would you please look in below whats wrong going on.



[
  {
    "ownerApp": "aks",
    "createTime": 1486515246281,
    "updateTime": 0,
    "createdBy": "string",
    "updatedBy": "string",
    "name": "dummy_workfow",
    "description": "dummy workflow",
    "version": 0,
    "tasks": [
      {
        "name": "dummy_task",
        "taskReferenceName": "dummy_task",
        "inputParameters": {
          "http_request": {
            "uri": "http://localhost:8880/apis/airports",
            "method": "GET"
          }
        },
        "type": "HTTP",
        "dynamicTaskNameParam": "string",
        "caseValueParam": "string",
        "dynamicForkJoinTasksParam": "string",
        "dynamicForkTasksParam": "string",
        "dynamicForkTasksInputParamName": "string",
        "defaultCase": [
          {
            "type": "SIMPLE",
            "startDelay": 0
          }
        ],
        "forkTasks": [
          [
            {
              "type": "SIMPLE",
              "startDelay": 0
            }
          ]
        ],
        "startDelay": 0,
        "joinOn": [
          "string"
        ],
        "subWorkflowParam": {
          "name": "string"
        }
      },
      {
        "name": "dummy_task1",
        "taskReferenceName": "dummy_task1",
        "inputParameters": {
          "http_request": {
            "uri": "http://localhost:8880/apis/aircraftTypes",
            "method": "GET"
          }
        },
        "type": "HTTP",
        "dynamicTaskNameParam": "string",
        "caseValueParam": "string",
        "dynamicForkJoinTasksParam": "string",
        "dynamicForkTasksParam": "string",
        "dynamicForkTasksInputParamName": "string",
        "defaultCase": [
          {
            "type": "SIMPLE",
            "startDelay": 0
          }
        ],
        "forkTasks": [
          [
            {
              "type": "SIMPLE",
              "startDelay": 0
            }
          ]
        ],
        "startDelay": 0,
        "joinOn": [
          "string"
        ],
        "subWorkflowParam": {
          "name": "string"
        }
      },
      {
        "name": "at_processing",
        "taskReferenceName": "avant_processing",
        "type": "FORK_JOIN",
        "dynamicTaskNameParam": "string",
        "caseValueParam": "string",
        "dynamicForkJoinTasksParam": "string",
        "dynamicForkTasksParam": "string",
        "dynamicForkTasksInputParamName": "string",
        "forkTasks": [
          [
            {
              "name": "dummy_task2",
              "taskReferenceName": "siffile_generation_task",
              "inputParameters": {
                "http_request": {
                  "uri": "http://localhost:8880/packager/createSifFile",
                  "method": "POST",
                  "body": "${workflow.input.packager}"
                }
              },
              "type": "HTTP"
            }
          ],
          [
            {
              "name": "dummy_task3",
              "taskReferenceName": "sqlfile_generation_task",
              "inputParameters": {
                "http_request": {
                  "uri": "http://localhost:8880/apis/airports/route",
                  "method": "GET"
                }
              },
              "type": "HTTP"
            },
            {
              "name": "dummy_task6",
              "taskReferenceName": "sqlschema_generation_task",
              "inputParameters": {
                "http_request": {
                  "uri": "http://localhost:8880/apis/airports/route",
                  "method": "GET"
                }
              },
              "type": "HTTP"
            }
          ],
          [
            {
              "name": "dummy_task5",
              "taskReferenceName": "image_transformation_task_tool1",
              "inputParameters": {
                "http_request": {
                  "method": "GET",
                  "uri": "http://localhost:8880/apis/Types"
                }
              },
              "type": "HTTP"
            },
            {
              "name": "dummy_task5",
              "taskReferenceName": "image_transformation_task_tool2",
              "inputParameters": {
                "http_request": {
                  "method": "GET",
                  "uri": "http://localhost:8880/apis/Types"
                }
              },
              "type": "HTTP"
            },
            {
              "name": "dummy_task5",
              "taskReferenceName": "image_transformation_task_tool3",
              "inputParameters": {
                "http_request": {
                  "method": "POST",
                  "uri": "http://localhost:8880/apis/airlines/00000159-91f7-dec6-a5db-99f7b8e50000/classes",
                  "body": {
                    "name": "ExecutiveClass",
                    "seatingClassInternalId": "string"
                  }
                }
              },
              "type": "HTTP"
            }
          ]
        ],
        "startDelay": 0,
        "joinOn": [
          "string"
        ],
        "subWorkflowParam": {
          "name": "string"
        }
      },
      {
        "name": "dummy_task4",
        "taskReferenceName": "join1",
        "type": "JOIN",
        "startDelay": 0,
        "joinOn": [
          "siffile_generation_task",
          "sqlfile_generation_task",
          "image_transformation_task"
        ]
      }
    ],
    "inputParameters":
     {
    "id": "f6c25e71-0e38-428b-b895-19dceb4602fb",
    "startDate": "2017-01-01T16:21:00Z",
    "endDate": "2019-01-01T16:21:00Z",
    "dateCreated": "2017-01-03T16:33:00.996Z",
    "dateModified": "2017-01-03T16:33:00.996Z",
    "status": "CLOSED",
    "order": {
      "id": "830c8c47-79b3-43ed-9459-c1b4dee47bad",
      "startDate": "2017-01-01T16:21:00Z",
      "endDate": "2019-01-01T16:21:00Z",
      "status": "INCOMPLETE",
      "name": "THY-JAN17-010821",
      "description": "THY-JAN17-010821",
      "Groups": {
        "Group": {
          "id": "JAN",
          "name": "THY-JAN17",
          "startDate": "2017-01-01T16:21:00Z",
          "endDate": "2019-01-01T16:21:00Z",
          "defaultDisplayGroup": "false"
        }
      },
      "deadlines": {
        "shipmentdate": "2016-12-22T16:21:00Z"
      }
    },
    "Instances": {
      "Instance": {
        "Profile": {
          "name": "TEST",
          "id": "a2507eb5-ae44-4502-9a00-6516ebf82218",
          "status": "AVAILABLE",
          "veichle": {
            "name": "AB321",
            "info": {
              "id": "",
              "name": ""
            }
          }
        },
        "definitionCollection": {},
        "Collection": {},
        "MetadataCollection": {
          "Metadata": []
        }
      }
    }
  }
    ,
    "failureWorkflow": "string",
    "schemaVersion": 0
  }
]

**Comment by v1r3n** [comment]
to update the workflow, which API endpoint are you calling?  Can you also share the stack trace and error details?

**Comment by v1r3n** [comment]
@ajayaks When you create the workflow definition, the inputParameters are a list of string (keys) that the workflow accepts when starting the execution.

https://github.com/Netflix/conductor/blob/dev/common/src/main/java/com/netflix/conductor/common/metadata/workflow/WorkflowDef.java#L44

You should pass the input parameters as you described above when **starting** the workflow execution not when defining.  Also, the schema version above is set to **0**.  You want to set it to **2**

I was able to change the "inputParameters" to a list of string keys and register the workflow.  Give it a try.  Pass the actual values when you start the workflow executions.

**Comment by ajayaks** [comment]
Hi Viren,  No success , seems i am missing or doing something silly. I tried to create the workflow like below.

Would you please  create a workflow using below json and send me the correct input that you are passing while creating workflow.

One more thing , Is it also meaning if we define input parameters during workflow creation then we cannot change it later during workflow update?

{
  "ownerApp": "aks",
  "createTime": 0,
  "updateTime": 0,
  "createdBy": "string",
  "updatedBy": "string",
  "name": "dummy_test_workflow",
  "description": "dummy_test_workflow ",
  "version": 0,
  "tasks": [
    {
      "name": "string",
      "taskReferenceName": "string",
      "inputParameters": {},
      "type": "string",
      "dynamicTaskNameParam": "string",
      "caseValueParam": "string",
      "decisionCases": {},
      "dynamicForkJoinTasksParam": "string",
      "dynamicForkTasksParam": "string",
      "dynamicForkTasksInputParamName": "string",
      "defaultCase": [
        {}
      ],
      "forkTasks": [
        [
          {}
        ]
      ],
      "startDelay": 0,
      "joinOn": [
        "string"
      ],
      "subWorkflowParam": {
        "name": "string",
        "version": {}
      }
    }
  ],
  "inputParameters": [ 
    "id": "f6c25e71-0e38-428b-b895-19dceb4602fb",
    "startDate": "2017-01-01T16:21:00Z",
    "endDate": "2019-01-01T16:21:00Z",
    "dateCreated": "2017-01-03T16:33:00.996Z",
    "dateModified": "2017-01-03T16:33:00.996Z",
    "status": "CLOSED",
    "order": {
      "id": "830c8c47-79b3-43ed-9459-c1b4dee47bad",
      "startDate": "2017-01-01T16:21:00Z",
      "endDate": "2019-01-01T16:21:00Z",
      "status": "INCOMPLETE",
      "name": "THY-JAN17-010821",
      "description": "THY-JAN17-010821",
      "Groups": {
        "Group": {
          "id": "JAN",
          "name": "THY-JAN17",
          "startDate": "2017-01-01T16:21:00Z",
          "endDate": "2019-01-01T16:21:00Z",
          "defaultDisplayGroup": "false"
        }
      },
      "deadlines": {
        "shipmentdate": "2016-12-22T16:21:00Z"
      }
    },
    "Instances": {
      "Instance": {
        "Profile": {
          "name": "TEST",
          "id": "a2507eb5-ae44-4502-9a00-6516ebf82218",
          "status": "AVAILABLE",
          "veichle": {
            "name": "AB321",
            "info": {
              "id": "",
              "name": ""
            }
          }
        },
        "definitionCollection": {},
        "Collection": {},
        "MetadataCollection": {
          "Metadata": []
        }
      }
    }
     ]
  ,
  "outputParameters": {},
  "failureWorkflow": "string",
  "schemaVersion": 0
}

**Comment by v1r3n** [comment]
@ajayaks I would suggest, please take a look at the kitchensink workflow as the starting point and modify it.  The above JSON does not conform to the workflow definition schema.

https://netflix.github.io/conductor/metadata/kitchensink/

> One more thing , Is it also meaning if we define input parameters during workflow creation then we cannot change it later during workflow update?

InputParameters during workflow definition can be certainly changed.  They serve mostly for the documentation for the users of workflow to identify what input parameters are required.

**Comment by ajayaks** [comment]
Hi Viren,

i looked in kitchensink workflow but didnt find info about workflow  input parameter with json.


I have crearted below json from model json via swagger , just added json as string in input parameter its working if i simply remove the json from workflow input parameter

{
  "ownerApp": "aks",
  "createTime": 0,
  "updateTime": 0,
  "createdBy": "string",
  "updatedBy": "string",
  "name": "dummy_test_workflow1",
  "description": "dummy_test_workflow 1",
  "version": 0,
  "tasks": [
    {
      "name": "string",
      "taskReferenceName": "string",
      "inputParameters": {},
      "type": "string",
      "dynamicTaskNameParam": "string",
      "caseValueParam": "string",
      "decisionCases": {},
      "dynamicForkJoinTasksParam": "string",
      "dynamicForkTasksParam": "string",
      "dynamicForkTasksInputParamName": "string",
      "defaultCase": [
        {}
      ],
      "forkTasks": [
        [
          {}
        ]
      ],
      "startDelay": 0,
      "joinOn": [
        "string"
      ],
      "subWorkflowParam": {
        "name": "string",
        "version": {}
      }
    }
  ],
  "inputParameters": [ 
   "{
    \"name\":\"John\",
    \"age\":30,
    \"cars\": [
        { \"name\":\"Ford\", \"models\":[ \"Fiesta\", \"Focus\", \"Mustang\" ] },
        { \"name\":\"BMW\", \"models\":[ \"320\", \"X3\", \"X5\" ] },
        { \"name\":\"Fiat\", \"models\":[ \"500\", \"Panda\" ] }
    ]
 }"
     ]
  ,
  "outputParameters": {},
  "failureWorkflow": "string",
  "schemaVersion": 2
}

**Comment by v1r3n** [comment]
@ajayaks to simplify, remove the  inputParameters from your workflow definition.  You can pass them when you start the workflow.

**Comment by ajayaks** [comment]
Hi Viren ,

I think that should work but i am getting one problem when passing big json. As per mapping
"input" : {
            "type" : "string",
            "index" : "not_analyzed"
          }

I was looking for issue and found below 
http://stackoverflow.com/questions/24019868/utf8-encoding-is-longer-than-the-max-length-32766 , so should i change the "index":"no"  for input  parameter? Will it impact something or i'll be able to use it normally?

Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 127004
	at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:284)
	at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:150)
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:682)
	... 26 more

**Comment by v1r3n** [comment]
You can change it to either `analyzed` or `no`.  Both will work.

**Comment by ajayaks** [comment]
i have kept it "not_analyzed" but added "ignore_above": 256 and its working after that so input is like below:-

"input": {
        "type": "string",
        "index": "not_analyzed",
        "ignore_above": 256
    }

And your suggestion of passing the json during workflow start solved the issue, so instead of adding the json in workflow definition , its better to pass it during calling workflow.

**Comment by v1r3n** [comment]
let me know if this solves the issue, we can close it.

**Comment by ajayaks** [comment]
yes, we can close the issue.Thanks for your spporrt
