### ISSUE TITLE
How to start workflow by handler with correlationId from input?

### ISSUE THREAD

**Issue by DmytroPvl** [Netflix/conductor#890]
I'm trying to start workflow by handler
```
{
	"name": "CreateContentEvent",
	"event": "conductor:Publish-CreateContentEvent:CreateContentEvent",
	"condition": "true",
	"actions": [{
			"action": "start_workflow",
			"start_workflow": {
				"name": "Create-Object",
				"input": {
					"data": {
						"caption": "${data.caption}",
						"elements": []
					},
					"payload": {
						"correlationId": "${payload.correlationId}",
						"catalogueId": "${data.id}"
					}
				},
				"correlationId": "${payload.correlationId}"
			},
			"expandInlineJSON": false
		}
	],
	"active": true
}
```
But variable ${payload.correlationId} evaluates correctly only for input parameters and not for correlationId:

![image](https://user-images.githubusercontent.com/29101016/49648608-1525b600-fa2f-11e8-8f06-c43f2101809e.png)

**Comment by kishorebanala** [comment]
@DmytroPvl In `start_workflow`, `correlationId` is not evaluated. Only the jsonPath arguments passed into `input` will be evaluated. `correlationId` just copies it over verbatim. But, please feel free to update EventHandler to evaluate `correlationId` as well.
