### ISSUE TITLE
[Question / Docs improvement]: callbackAfterSeconds can be used as an Heartbeat mechanism?

### ISSUE THREAD

**Issue by artpdr** [Netflix/conductor#896]
Hi,

Is it possible to use callbackAfterSeconds as an heartbeat mechanism?

Imagine that I have a worker task that can take between 60 seconds and 3600 seconds to become completed. If I set timeoutSeconds to a value larger than 3600, I ensure that all the tasks will be processed sooner or later even if the current worker crashes (assuming the task has retryCount > 0). This isn't bad at all, but if the majority of tasks just takes 60 seconds to be processed and the worker processing such tasks crashes, we need to wait almost an hour until the task can be processed by another worker.

However, if my task is defined with responseTimeoutSeconds: 360, besides the timeoutSeconds as before, after polling the task a first time and acknowledging it (ACK) I can set callbackAfterSeconds: 120; and I always POST the task every 60 seconds with IN_PROGRESS status until the worker finishes to process what needs to be processed according to the task in question. From the experiment I've made, the task isn't placed in the queue to be available for other workers unless the worker doesn't POST the task with callbackAfterSeconds:120 for more than 360 seconds. 

So... Can anyone confirm that we may use callbackAfterSeconds as an heartbeat mechanism? It would be very good to have some documentation for callbackAfterSeconds, which I didn't find in https://netflix.github.io/conductor/. I can contribute to this documentation if I am understanding this correctly. Contributing to the worker-client to do the heartbeats would also be an option.

Thanks!

**Comment by artpdr** [comment]
@cyzhao, Please, can you confirm that callbackAfterSeconds can be used as an Heartbeat mechanism? I think you mentioned it could be used for that in issue #798. 
Is it useful some documentation for it or some mechanism in the conductor-client to perform the heartbeats when needed?
Thanks

**Comment by cyzhao** [comment]
@artpdr callbackAfterSeconds can't be used as heartbeat, what is does it to return the task back to the queue and make it visible to workers after callbackAfterSeconds. Currently Conductor doesn't provide a mechanism to support this, however a heartbeat mechanism can be introduced to allow workers to reset responseTimeoutSeconds, let me know if you want to take a stab at this then we can get into details.

**Comment by artpdr** [comment]
@cyzhao thanks for answering. 
I see that callbackAfterSeconds is not exactly an heartbeat mechanism. However, if a worker keeps posting a task with callbackAfterSeconds until it set COMPLETED in this worker, it can be seen somehow as an heartbeat mechanism because the task will be turned to the queue to become visible by other workers only in the case that the first worker stops to post the task with callbackAfterSeconds or with a FAILED status.
Nonetheless, I see that is more elegant a true heartbeat solution and I will try to explore the code of the conductor-server in the next days to see how the heartbeat mechanism may be introduced. I hope to give news soon with a possible solution for the implementation. 
Cheers.
