### ISSUE TITLE
Spectator publish metrics to Atlas

### ISSUE THREAD

**Issue by jkaipa** [Netflix/conductor#901]
@cyzhao I could see the spectator metrics through jconsole. How to configure conductor to publish spectator metrics to Atlas?

**Comment by cyzhao** [comment]
@jkaipa pls check out: 

https://github.com/Netflix/spectator/tree/master/spectator-reg-atlas
http://netflix.github.io/spectator/en/latest/registry/servo/
http://netflix.github.io/spectator/en/latest/intro/netflix/
