### ISSUE TITLE
Google Pub/Sub as a sink

### ISSUE THREAD

**Issue by jakon89** [Netflix/conductor#904]
I would like to use Pub/Sub instead of SQS for events.

* Have you ever considered adding support for Pub/Sub in contribs?
* What are your tips regarding new queue implementation before creating PR?

I am in the middle of creating PubSub & conductor integration and would love to get your feedback before I issue MR.

**Comment by jakon89** [comment]
After reading the code I have a couple of thoughts. 

In Pub/Sub, unlike SQS and Conductor, there is no term 'queue' that represents resource where we can both send and receive. There are subscriptions and topics which allows reading and writing, respectively, to/from the topic.

This means that current abstraction `ObservableQueue` doesn't fit exactly with Pub/Sub model - `ObservableQueue` has both `publish` and `receive` methods.

This means that sink in form of `googlePubSub:$google-project:$subscription-name` (similar to `sqs:$queue_name`) could be used in Event task, but it won't be possible to use the same string when registering Event Handler as we can't read from subscription - Google Pub/Sub `EventQueueProvider` will not know if should return implementation that should allow sending or receiving messages. If we use the same sink form we won't be able to distinguish if we are in the context of publishing or receiving a message.

I see two ways of solving this:

* use `googlePubSub:subscription:$google-project:$subscription-name` and  `googlePubSub:topic:$google-project:$topic-name` when defining resources in Event Task/Event handler. This way Google Pub/Sub EventQueueProvider will be able to serve implementation of `ObservableQueue` which implements reading or receiving events underneath. This approach is the simplest one, it doesn't require changing core code at all. Something like this will suffice:

```java
    @Override
    public ObservableQueue getQueue(String queueURI) {
        if (isTopic(queueURI)) {
            return topics.computeIfAbsent(queueURI, q -> {
// it treats queueURI as topic name and allows only sending messages to
                return new PubSubTopicObservableQueue(...);
            });
        }

        return subscriptions.computeIfAbsent(queueURI, q -> {
// it treats queueURI as subscription name and allows only reading 
            return new PubSubSubscriptionObservableQueue(...);
        });
    }
````

* split `ObservableQueue` to `QueueProducer` and `QueueReceiver` (there are just example names). 
All core code that uses `ObservableQueue` will have to be refactored to use new types - either `QueueProducer` or `QueueReceiver`.


WDYT?

**Comment by dskarataev** [comment]
We are also interested to send messages with workflow results to SNS instead of SQS, so different systems can subscribe to these messages and do some actions. How is it done in Netflix?

**Comment by andrey-borue** [comment]
Hi @jakon89 
Do you have results for this task? I'm also interested in using Google Pub/Sub.
