### ISSUE TITLE
Work with microservices

### ISSUE THREAD

**Issue by aquacadabra** [Netflix/conductor#921]
Sorry if my English is not good

We're investigating Conductor to use it in our next microservices project (our first microservices project as well) and after reading official the document we still have many questions on how to use Conductor properly. 

Please someone help to clarify these points:

1. Documentation
Is there any more complete document than the official one at https://netflix.github.io/conductor/? After reading that document, we still  found it difficult to start working with Conductor. 

2. Task
- How is the retry policy applied? Does it count each time task is sent over poll API? With HTTP Task does it count each time the task calls to external API?

3. Task Worker
- We have room service and now we need room worker. Should we implemented the worker to run inside room service? When we run multiple instances of room services and each of them poll for the same task type, does all instances receive the same tasks?
- If we should not add worker to each service instances what is the recommend way to do that?

4. Compensating workflow
- In some workflow we'll need to compensate the completed tasks if one task is fail down the road. What  is the proper way to do that? We're thinking about have two workflows, one normal workflow and one workflow to compensate it. The compensating one will be activated by task fail event.

**Comment by apanicker-nflx** [comment]
1. Currently, that is the only documentation available. However, we realize that it is a bit antiquated and will update the documentation soon with better onboarding examples. Thanks for the feedback.

2. 
> How is the retry policy applied?
The retry policy is applied when the task execution fails and the task is retried based on the number of retries configured in the task definition. 
>  Does it count each time task is sent over poll API?
The retry count is counted/updated each time the task changes status from IN_PROGRESS to a terminal state (FAILED/TIMED_OUT). The task could be sent multiple times over the poll API if the task is set to use the `callbackAfterSeconds` and this only increases the pollCount for the task but does not affect the retry count.
> With HTTP Task does it count each time the task calls to external API?
For HTTP task, the retry count behavior is the same as that for a SIMPLE task. Each call from the client to the API is not counted. So, if the HTTP client is set to 3 retries and the task retry count is set to 3, then the task can call the external API 12 times (3 original + 3*3 retries). 

3. You can implement the room worker within your room service. The room worker would need to implement the `Worker` interface and then be plugged into the `WorkflowTaskCoordinator`.
When running multiple instances of room services, all instances can poll for the same task type, however, only one instance will process an instance of a given task at a given point of time. The `ack` mechanism within the `WorkflowTaskCoordinator` ensures this.

4. You can configure a `failureWorkflow` in your workflow definition such that the failure workflow will be triggered if the original workflow fails. This failure workflow can be used as a compensating workflow.
