### ISSUE TITLE
Unable to start Conductor using cassandra

### ISSUE THREAD

**Issue by pavansistla** [Netflix/conductor#928]
I am unable to launch conductor locally using cassandra in server.properties 
_server.properties_
      db=CASSANDRA
      workflow.cassandra.host=host
      workflow.cassandra.port=port
      workflow.cassandra.keyspace=key

I found out that QueueDAO and MetadataDAO implementations for cassandra are missing.
Can you please correct me if I am missing any thing here in the process of starting the conductor.

**Comment by apanicker-nflx** [comment]
The CassandraDAO is a partial implementation as documented here - https://github.com/Netflix/conductor/blob/master/cassandra-persistence/README.md.

Please feel free to contribute to the missing modules.

**Comment by Bethalaayyappa** [comment]
Hi Conductor Team,

Same me also trying to connect with Cassandra. The following issue i observed. Please correct me if i am going wrong.
The below mentioned lines of code expecting break statement in **ModulesProvider.java**

            case CASSANDRA:
                modules.add(new CassandraModule());
                logger.info("Starting conductor server using cassandra.");
            case REDIS_SENTINEL:
                modules.add(new RedisSentinelModule());
                modules.add(new RedisWorkflowModule());
                logger.info("Starting conductor server using redis_sentinel.");
                break;
        }

**Comment by Bethalaayyappa** [comment]
Hi Team,

Is it required to implement MetadataDAO and QueueDAO for cassandra implmentation.
Question) Cassandra and Redis sanitel both required in modulesproviders.java  files ?

Please help me....

**Comment by apanicker-nflx** [comment]
@Bethalaayyappa you are right, the `break` statement is missing here. Thanks for pointing it out.
> Is it required to implement MetadataDAO and QueueDAO for cassandra implmentation.
These are required to use the C* DAO implementation. As mentioned in earlier comment, please feel free to contribute the missing implementations to this module.
