### ISSUE TITLE
Retrying/Scheduling a failed HTTP task is broken in 2.5.2

### ISSUE THREAD

**Issue by surajrrao** [Netflix/conductor#937]
Retrying/Scheduling a failed HTTP task is broken in 2.5.2, though the same works fine with 1.8.3

**Comment by apanicker-nflx** [comment]
@surajrrao We are working on a fix for this and will be releasing one soon. Thanks for the feedback.

**Comment by surajrrao** [comment]
@apanicker-nflx - Thanks for responding! Just to clarify - is this issue fixed already? I see you have closed this ticket & also i see 2.5.3 version available now.

**Comment by apanicker-nflx** [comment]
v2.5.3 does not have a fix for this, we will be releasing a fix for this either today or tomorrow.
