### ISSUE TITLE
Support for executing workflow from an intermediate step in the workflow

### ISSUE THREAD

**Issue by choubisat** [Netflix/conductor#938]
Conductor supports restarting the workflow. However, there seems to be no support for starting the workflow from an intermediate task in the workflow. We are evaluating workflow engines for our use cases, that include many user-centric tasks. Some of the use cases require us to conditionally iterate ("loop") over the tasks in the workflow or choose any random task which is part of the workflow ( i.e. a "goto task_xxx") , much like how a state machine would work.

Various blogs have captured, that the support for Amazon states language is on the road map for conductor. What is the status or plan for this enhancement? Is there any target date ?

**Comment by apanicker-nflx** [comment]
@choubisat Constructs of "loop" and "goto" task is not currently supported within a workflow execution in Conductor. We do have a plan to add support for these in our long-term roadmap, however, if this is an urgent requirement for you, please feel free to submit a pull request for the same and we would be happy to review and merge.

**Comment by mudit3774** [comment]
Thanks for the update @apanicker-nflx, @choubisat there were some old tickets for the same : https://github.com/Netflix/conductor/issues/35 We are also interested in adding this support. 

One way to do this would be to add a GoTo construct that moves us to that task by marking it in progress and all tasks can re-execute. We also need a way to save this. This would also require some changes in the UI. Something similar is suggested in #35 

@cyzhao @apanicker-nflx @choubisat  @v1r3n @mashurex would like to know your views then we can proceed with the execution.
