### ISSUE TITLE
Access Global variables & Assign a value to them

### ISSUE THREAD

**Issue by jagadeeshb22** [Netflix/conductor#944]
@jvemugunta / @v1r3n 
How can we define a variable globally which is available for each task, and assign a specific value in a decision case to it, and access that as output of that specific task?
Can you help on me this?

Thanks in Advance.

**Comment by v1r3n** [comment]
Conductor does not define global variables.  There are workflow input that are available to each task for these are inputs that cannot be changed.  

Each task can output a variable based on some logic and the variable name can be same across different tasks - not sure if that is what you are looking for.

**Comment by jagadeeshb22** [comment]
Thanks @v1r3n.
My actual requirement is like -- I have a decision case with YES or NO options.
In YES case, I need to take a variable, and use it in further task. At the same time with NO.
So, based on the decision any one will execute, and a value needs to be assigned to that variable in that case. I need to use that.
Is that possible ? 
![image](https://user-images.githubusercontent.com/38783638/51327764-0a335c00-1a98-11e9-9b60-f8863d4895e1.png)

As per the diagram, 
I defined two tasks t2, t3 with the inputParameters with Val, and I need to access the val from the executed case. How can we give the task reference name to get that executed task's Val?
Could you please suggest on this?

**Comment by mashurex** [comment]
You could probably do one of a couple of things:

1. Wire the output of `t2` or `t3` to the same workflow output parameter and wire `workflow.output.parameterName` to the input of `t4`
2. Wire the output of `t2` to one input parameter on `t4` and wire the output of `t3` to another input parameter on `t4` and handle coalescing them at task implementation or worker level
3. Wire the input of t2 and t3 to the same task input parameter using JavaScript `||` like so: `${t2.output.parameterName || t3.output.parameterName}`. However, this might not work if the expression engine doesn't know how to handle it.

**Comment by apanicker-nflx** [comment]
@jagadeeshb22 Please refer to the documentation of the `EXCLUSIVE_JOIN` [here](https://netflix.github.io/conductor/configuration/systask/#exclusive-join). This should fulfill the use-case that you suggested.
