### ISSUE TITLE
Conductor usability

### ISSUE THREAD

**Issue by F1reworks** [Netflix/conductor#952]
Hello, do you have any tuning guides? 
I tryed using conductor for simple workflows with 5-7 small microservices each. The perfomance results are inappropriate. I tryed to disable conductor data base, changed polling intervals, disabled any disk io or data base interacting inside workers. But latency between scheduled time and start time is about 300 ms, workers are spending 100-400 ms on very simple tasks, lag between task end time and sheduling next task is about 300-400ms. So very simple workflow takes 4-6 seconds to complete. Here is a part of common log from UI.
![conductor](https://user-images.githubusercontent.com/32437460/51373310-c1c08080-1b21-11e9-82e6-be66ab0b7da8.png)
What can I change for improve perfomance? Or may be conductor was made for operating with big long running services and it is normal time consumption between invocations, and I should not use conductor for orchestrating so small tasks?

**Comment by ynfeng** [comment]
mark

**Comment by F1reworks** [comment]
Hello @v1r3n, for testing I disabled conductor data base and used in memory instance. 
Environment: conductor and workers run localy in one PC. Workflow start requests were generated throw conductor-client library on the same PC. I used 10 threads for stress load. I mentioned that load speed also not very high. I use 8 cores i7 processor with 12GB RAM. And during testing CPU utilization was not more than 15%.

**Comment by ynfeng** [comment]
I think the worker's task poll model will make conductor server and backend storage pressure is too high. For example, there are 500 workers.

**Comment by F1reworks** [comment]
Okey. I managed to fix some configuration parameters and get throuput about 40 request per second. Workers are working much faster, but tasks stayed scheduled for a long time 2-4 minutes. How can I increase pooling speed?

**Comment by F1reworks** [comment]
Hello, @JasperB. Yes, we tryed different perams. So we increased performance slightly. We found out that most CPU consumed by elasticsearch, conductor threads made CPU load only 5-10%. Try to use separate elasticsearch engine, but network overhead were too big.

**Comment by JasperB** [comment]
@F1reworks it's weird. The conductor only load the data from ES once the workflow not exist in redis, which only happened you archived your workflow or the workflow can't get from redis. So I think there is something wrong for configuration.

**Comment by F1reworks** [comment]
@JasperB for testing we used in memory configuration with out redis.

**Comment by xerxeArt** [comment]
Hello,
How do I change these configurations on the fly?
For instance:
`this.pollInterval = config.getIntProperty("workflow.system.task.worker.poll.interval", 50)`
I am running Conductor with docker-compose.

**Comment by xerxeArt** [comment]
> Okey. I managed to fix some configuration parameters and get throuput about 40 request per second. Workers are working much faster, but tasks stayed scheduled for a long time 2-4 minutes. How can I increase pooling speed?

Hello @F1reworks , could you show me your configuration?
I used the configuration attached [here](https://github.com/Netflix/conductor/issues/1183#issuecomment-501987677) with many variations, but I couldn't get good results.
