### ISSUE TITLE
WAIT tasks are not scheduled to the tasks queue and the workflow stops

### ISSUE THREAD

**Issue by surendrapamidi** [Netflix/conductor#96]
DeciderService.java does not have the CASE statement for handling WAIT tasks to be added to the tasks queue. The workflow simply stops at the WAIT task.

Ex:
case WAIT:
 if(taskId == null) taskId = IDGenerator.generate();
 Task waitTask = SystemTask.waitTask(workflow.getWorkflowId(), IDGenerator.generate(),
 workflow.getCorrelationId(), taskToSchedule.getTaskReferenceName());
 tasks.add(waitTask);
 Break;

**Comment by v1r3n** [comment]
@surendrapamidi this has been fixed in the latest update.
