### ISSUE TITLE
How to use external s3 payload storage

### ISSUE THREAD

**Issue by microsoftly** [Netflix/conductor#962]
There are no docs around this feature, but the logs show 
`[main] INFO  com.netflix.conductor.bootstrap.ModulesProvider  - External payload storage is not configured, provided: , supported values are: [S3]`
As well as the source referring to it https://github.com/Netflix/conductor/blob/master/client/src/main/java/com/netflix/conductor/client/config/ConductorClientConfiguration.java#L51, but not explicitly supporting it in a clear way (e.g.  https://github.com/Netflix/conductor/blob/e195254bad8e8c0c6bf327b427f87e6327167828/core/src/main/java/com/netflix/conductor/core/config/Configuration.java#L58)

Can you show an example on how to use this feature?

**Comment by apanicker-nflx** [comment]
We are currently in the process of adding documentation for the new features and the `ExternalPayloadStorage` is one of these. 
As you correctly pointed out, this is not enabled by default. This feature would explicitly need to be turned on and can only be used from the Java client.

**Comment by apanicker-nflx** [comment]
Please refer the documentation [here](https://netflix.github.io/conductor/externalpayloadstorage/) for using the external s3 payload storage. You can extend this to provide your own implementation by following the steps [here](https://netflix.github.io/conductor/extend/#external-payload-storage).

If you are not using the Java client, please feel free to contribute your implementation for this in another client implementation.
