### ISSUE TITLE
ExecutionDAO: new method for counting all tasks

### ISSUE THREAD

**Issue by Jiehong** [Netflix/conductor#968]
Hello,

I'd like to add (i.e. provide a PR) the following method in `ExecutionDAO`:

`long getTotalNumberOfTaskExecution(final String taskDefName);`

Its purpose is to have a way to know the number of task executed/in execution for a given taskDef.
This information might be useful to provide some paging information in the services for example.

What do you think?

**Comment by AlexVinogradov** [comment]
Agreed, i could be really useful, not only for the TaskExecution but for all the objects.

**Comment by apanicker-nflx** [comment]
This API [getInProgressTaskCount(String taskDefName](https://github.com/Netflix/conductor/blob/master/core/src/main/java/com/netflix/conductor/dao/ExecutionDAO.java#L204-L209) already exists to provide information about the number of tasks currently being executed for a given taskDef.

To get a count of all the task executions for a given taskDef the search API from the indexDAO can be used which would be more generic for searching across tasks.

**Comment by apanicker-nflx** [comment]
Closing this issue, since the search API in indexDAO on tasks meets the need for a exhaustive view across all task executions and the existing API in executionDAO provides the count for current executions.

Please reopen if you still feel there is a need for a new API.

**Comment by andrea11** [comment]
Hello @apanicker-nflx,
I would like about this subject, which could be the best approach to have a count for WorkflowDef. May be better to add them to the IndexDAO or perhaps to have a new method in the MetadataDAO. What do you suggest?

Thanks
