### ISSUE TITLE
ACK the notify COMPLETED queue

### ISSUE THREAD

**Issue by surendrapamidi** [Netflix/conductor#97]
Need to ack the messages in the queue once the message is read from the notify COMPLETED queues. The messages are left on the queue and are read every time the queue is polled.

if(!ot.isPresent()) {
  logger.error("No matching tasks to be found to be marked as completed for workflow {}", workflowId);
  queue.ack(Arrays.asList(msg));**// this instruction is missing...**
  return;
}

**Comment by apanicker-nflx** [comment]
This has been fixed for some time now. Please reopen if you still run into this.
