### ISSUE TITLE
Partial logs for HTTP request task

### ISSUE THREAD

**Issue by emiteze** [Netflix/conductor#976]
We are using conductor in our company as orchestration engine and we need to adapt the current HTTP task to ommit request body and response body from logs (ES and application's log like log4j), if choosen by user (e.g: by input parameter).

This is good when you have big payloads in request or response and by not logging them you may have a slightly better performance, or when you have sensitive data in request or response and you don't want to log them in your backend.

Would be this a good contribution to conductor or do you guys think that this is much specific to our use case?

If you guys say yes, then we can open a PR soon to this.

**Comment by kishorebanala** [comment]
@emiteze Interesting. We always found logs helpful, particularly when Http task fails. Having logs in the UI helps users triangulate the issue quickly. However, if we can add some sort of filters to selectively remove certain fields from the request or response, that'd be great. @apanicker-nflx @cyzhao Thoughts?
