### ISSUE TITLE
UI: Wrong number of executions

### ISSUE THREAD

**Issue by dskarataev** [Netflix/conductor#984]
Hello, I found that if I run many workflows at the same time, let's say 10000 in 1 hour, and during that time I applied the RUNNING filter in executions search, then after they all will be executed I still see a positive number like 1750 executions supposed to be running but the list of executions is empty already.

Do you know possible reasons for that? And how to fix? Are there any restrictions of updating interval for ElasticSeach index? Maybe I send too many requests (I tried 100 concurrent requests to start workflows) and somehow ES index is updated in the wrong way?

Thank you.

![image](https://user-images.githubusercontent.com/1011632/52460300-2c526280-2b9c-11e9-88b5-db7c909de1f0.png)

**Comment by dskarataev** [comment]
I think I found the reason while debugging the UI requests to the server. The actual status of these workflows is already COMPLETED but somehow this was not updated for search/filtering purpose. So, I have a "result->hits" response with a chunk of 100 workflows when clicking Seach on this page, but their status is COMPLETED so probably UI isn't showing them (that is right). So, the number of "found workflows" also should be zero in that case.

**Comment by dskarataev** [comment]
I also think it is maybe related to the issue #759, because before that workflows were stuck in RUNNING but later all of them magically changed to COMPLETED after I manually paused and resumed 24 of them.

**Comment by apanicker-nflx** [comment]
@dskarataev Thanks for testing and the feedback. We are looking into #759 and will post an update soon. Please follow along on #759
