### ISSUE TITLE
[QUESTION] Are running workflows affected by workflow-definition updates?

### ISSUE THREAD

**Issue by JohnHaze** [Netflix/conductor#987]
Does a running workflow overtake die updated definition ?

**Comment by kishorebanala** [comment]
@JohnHaze If you're using the `version` parameter in Workflow definition when updating, then it shouldn't be a problem. Eg: if a workflow is running version:5, and you update metadata to version:6, the running workflows won't be affected, and new workflows could use version:6

**Comment by JohnHaze** [comment]
@kishorebanala Thank you so much for your reply. 
What happens in the case of an update of the same version of the workflow?
