### ISSUE TITLE
can not resolve module "moment" in ./src/components/workflow/executions/WorkflowDetails.js

### ISSUE THREAD

**Issue by mwangtarget** [Netflix/conductor#99]
when running gulp watch in the UI folder, got following error:

"ERROR in ./src/components/workflow/executions/WorkflowDetails.js
Module not found: Error: Cannot resolve module 'moment' in #######\ui\src\components\workflow\executions
 @ ./src/components/workflow/executions/WorkflowDetails.js 43:14-31
"

**Comment by v1r3n** [comment]
can you run ```npm install``` and try again?

**Comment by mwangtarget** [comment]
yes, working now, thanks very much

I just followed the getting started following before.
might better to  update it to include npm install step as well.
https://netflix.github.io/conductor/intro/
