### ISSUE TITLE
Question: Java client "ack" ability after execute

### ISSUE THREAD

**Issue by demichej** [Netflix/conductor#996]
Hello, I know that the TaskClient has the "ack" endpoint setup on it in the Java Client library. One use case that we're looking at is having a "SIMPLE" task, and when we're doing "executing" the task we'd like to then "ack" it. The reason being is that we'd like to add some output data on it and then basically put it in a "WAIT" stage by ack-ing it. 

Is there an ability to set some "ack" flag on the TaskResult? If not, what's the recommended way of accomplishing this? Should we construct our Woker with the TaskClient set on the WorkflowTaskCoordinator? And then call it in there? 

Thanks, and maybe there's a different strategy all together you could suggest. Basically we want a "SIMPLE" task, but then we want it to go into a WAIT stage. 

Thanks.

(I am unable to add the "question" tag, sorry).

**Comment by v1r3n** [comment]
One way to achieve this would be to "complete" the simple task with status as IN_PROGRESS and set the callbackAfter to a timeout value after which the task will be rescheduled.  If you do not want the task to be rescheduled, then you can set the callbackAfter value to a large and make a call to complete the task when the task is completed.

**Comment by demichej** [comment]
Thank you! This should work well enough.
