### ISSUE TITLE
docker-compose build error

### ISSUE THREAD

**Issue by iamthadiyan** [Netflix/conductor#999]
I am seeing the following error when I do `sudo docker-compose build` inside `conductor/docker` folder.

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not resolve all files for configuration ':conductor-grpc:protobuf'.
> > Could not resolve io.chaossystems.grpc:grpc-healthcheck:1.0.1.
>   Required by:
>       project :conductor-grpc
>    > Could not resolve io.chaossystems.grpc:grpc-healthcheck:1.0.1.
>       > **Could not get resource 'https://dl.bintray.com/netflixoss/oss-candidate/io/chaossystems/grpc/grpc-healthcheck/1.0.1/grpc-healthcheck-1.0.1.pom'.**
>          > Could not GET 'https://dl.bintray.com/netflixoss/oss-candidate/io/chaossystems/grpc/grpc-healthcheck/1.0.1/grpc-healthcheck-1.0.1.pom'.
>             > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
>    > Could not resolve io.chaossystems.grpc:grpc-healthcheck:1.0.1.
>       > Could not get resource 'https://dl.bintray.com/chaos-systems/mvn/io/chaossystems/grpc/grpc-healthcheck/1.0.1/grpc-healthcheck-1.0.1.pom'.
>          > **Could not GET 'https://dl.bintray.com/chaos-systems/mvn/io/chaossystems/grpc/grpc-healthcheck/1.0.1/grpc-healthcheck-1.0.1.pom'.**
>             > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
> See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings
> 
> BUILD FAILED in 7m 58s
> 

What am I missing here?

**Comment by apanicker-nflx** [comment]
`docker-compose build` builds the conductor server and ui images successfully with the latest version.
Does a `./gradlew build` work fine in your case?

**Comment by iamthadiyan** [comment]
> 
> 
> `docker-compose build` builds the conductor server and ui images successfully with the latest version.
> Does a `./gradlew build` work fine in your case?

No, `./gradelw build` fails with the same error.

> * What went wrong:
> Could not resolve all files for configuration ':conductor-grpc:protobuf'.
> > Could not resolve io.chaossystems.grpc:grpc-healthcheck:1.0.1.
>   Required by:
>       project :conductor-grpc
>    > Could not resolve io.chaossystems.grpc:grpc-healthcheck:1.0.1.
>       > Could not get resource 'https://dl.bintray.com/netflixoss/oss-candidate/io/chaossystems/grpc/grpc-healthcheck/1.0.1/grpc-healthcheck-1.0.1.pom'.
>          > **Could not GET 'https://dl.bintray.com/netflixoss/oss-candidate/io/chaossystems/grpc/grpc-healthcheck/1.0.1/grpc-healthcheck-1.0.1.pom'.**
> 

Also I am not able to get the resource https://dl.bintray.com/netflixoss/oss-candidate/io/chaossystems/grpc/grpc-healthcheck/1.0.1/grpc-healthcheck-1.0.1.pom from a browser also.

**Comment by kishorebanala** [comment]
@iamthadiyan Can you try making sure to include ```repositories{
    maven { url "https://dl.bintray.com/chaos-systems/mvn" }
}``` in conductor-grpc's build.gradle, and that you're referring to https://dl.bintray.com/chaos-systems/mvn/io/chaossystems/grpc/grpc-healthcheck/1.0.1/ for above mentioned dependency.

**Comment by kishorebanala** [comment]
This should've been available in latest versions. I'm closing this issue, but please feel free to reopen is you still see issues.

**Comment by empty85** [comment]
Hi All,

I just downloaded the conductor project from github. (Not able to clone is due to restrictions on my machine) 

When I am running this. I dunno why this is getting downloaded from jcenter instead of repositories{ maven { url "https://dl.bintray.com/chaos-systems/mvn" } }
$ ./gradlew build

> Task :conductor-grpc:extractProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':conductor-grpc:protobuf'.
> Could not resolve io.chaossystems.grpc:grpc-healthcheck:1.0.1.
  Required by:
      project :conductor-grpc
   > Could not resolve io.chaossystems.grpc:grpc-healthcheck:1.0.1.
      > Could not get resource 'https://jcenter.bintray.com/io/chaossystems/grpc/grpc-healthcheck/1.0.1/grpc-healthcheck-1.0.1.pom'.
         > Could not GET 'https://jcenter.bintray.com/io/chaossystems/grpc/grpc-healthcheck/1.0.1/grpc-healthcheck-1.0.1.pom'.
            > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/54.191.3.105] failed: connect timed out

**Comment by taojwmware** [comment]
@kishorebanala same issue on me too.

#11 519.4 FAILURE: Build failed with an exception.
#11 519.4 
#11 519.4 * What went wrong:
#11 519.4 Could not resolve all files for configuration ':conductor-grpc:protobuf'.
#11 519.4 > Could not resolve io.chaossystems.grpc:grpc-healthcheck:1.0.1.
#11 519.4   Required by:
#11 519.4       project :conductor-grpc
#11 519.4    > Could not resolve io.chaossystems.grpc:grpc-healthcheck:1.0.1.
#11 519.4       > Could not get resource 'https://dl.bintray.com/chaos-systems/mvn/io/chaossystems/grpc/grpc-healthcheck/1.0.1/grpc-healthcheck-1.0.1.pom'.
#11 519.4          > Could not GET 'https://dl.bintray.com/chaos-systems/mvn/io/chaossystems/grpc/grpc-healthcheck/1.0.1/grpc-healthcheck-1.0.1.pom'. Received status code 403 from server: **Forbidden**

**Comment by voratham** [comment]
Yes, I have a problem same on my ci-runner.  In past 4 - 5 month not found with this problem but i found on today

![image](https://user-images.githubusercontent.com/30921472/118511412-127d2e00-b75c-11eb-9918-b27fe2a490a5.png)

**Comment by taojwmware** [comment]
<img width="1835" alt="Screen Shot 2021-05-16 at 7 18 29 AM" src="https://user-images.githubusercontent.com/25186652/118525631-074ae380-b705-11eb-924b-ee664342eddd.png">
I think bintray is dead and we need to switch to other places.
